package hotelfx.persistence.model;
// Generated Aug 15, 2018 10:24:09 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * LogCompanyBalanceCashFlow generated by hbm2java
 */
public class LogCompanyBalanceCashFlow implements java.io.Serializable {

    private final LongProperty idhistory;
    private final ObjectProperty<TblBankAccount> tblBankAccountByIdreceiverCbbankAccount;
    private final ObjectProperty<TblBankAccount> tblBankAccountByIdsenderCbbankAccount;
    private final ObjectProperty<TblCompanyBalance> tblCompanyBalanceByIdsenderCompanyBalance;
    private final ObjectProperty<TblCompanyBalance> tblCompanyBalanceByIdreceiverCompanyBalance;
    private final ObjectProperty<TblEmployee> tblEmployee;
    private final ObjectProperty<BigDecimal> transferNominal;
    private final ObjectProperty<Date> historyDate;
    private final StringProperty historyNote;
    private final StringProperty historyStystemNote;

    private Set tblOpenCloseCashierBalanceDetails;

    public LogCompanyBalanceCashFlow() {
        this.idhistory = new SimpleLongProperty();
        this.tblBankAccountByIdreceiverCbbankAccount = new SimpleObjectProperty<>();
        this.tblBankAccountByIdsenderCbbankAccount = new SimpleObjectProperty<>();
        this.tblCompanyBalanceByIdsenderCompanyBalance = new SimpleObjectProperty<>();
        this.tblCompanyBalanceByIdreceiverCompanyBalance = new SimpleObjectProperty<>();
        this.tblEmployee = new SimpleObjectProperty<>();
        this.transferNominal = new SimpleObjectProperty<>();
        this.historyDate = new SimpleObjectProperty<>();
        this.historyNote = new SimpleStringProperty();
        this.historyStystemNote = new SimpleStringProperty();

        this.tblOpenCloseCashierBalanceDetails = new HashSet(0);
    }

    public LogCompanyBalanceCashFlow(long idhistory) {
        this();
        idhistoryProperty().set(idhistory);
    }

    public LogCompanyBalanceCashFlow(long idhistory, TblBankAccount tblBankAccountByIdreceiverCbbankAccount, TblBankAccount tblBankAccountByIdsenderCbbankAccount, TblCompanyBalance tblCompanyBalanceByIdsenderCompanyBalance, TblCompanyBalance tblCompanyBalanceByIdreceiverCompanyBalance, TblEmployee tblEmployee, BigDecimal transferNominal, Date historyDate, String historyNote, String historyStystemNote, Set tblOpenCloseCashierBalanceDetails) {
        this();
        idhistoryProperty().set(idhistory);
        tblBankAccountByIdreceiverCbbankAccountProperty().set(tblBankAccountByIdreceiverCbbankAccount);
        tblBankAccountByIdsenderCbbankAccountProperty().set(tblBankAccountByIdsenderCbbankAccount);
        tblCompanyBalanceByIdsenderCompanyBalanceProperty().set(tblCompanyBalanceByIdsenderCompanyBalance);
        tblCompanyBalanceByIdreceiverCompanyBalanceProperty().set(tblCompanyBalanceByIdreceiverCompanyBalance);
        tblEmployeeProperty().set(tblEmployee);
        transferNominalProperty().set(transferNominal);
        historyDateProperty().set(historyDate);
        historyNoteProperty().set(historyNote);
        historyStystemNoteProperty().set(historyStystemNote);

        this.tblOpenCloseCashierBalanceDetails = tblOpenCloseCashierBalanceDetails;
    }

    public LogCompanyBalanceCashFlow(LogCompanyBalanceCashFlow logCompanyBalanceCashFlow) {
        this();
        idhistoryProperty().set(logCompanyBalanceCashFlow.getIdhistory());
        tblBankAccountByIdreceiverCbbankAccountProperty().set(logCompanyBalanceCashFlow.getTblBankAccountByIdreceiverCbbankAccount());
        tblBankAccountByIdsenderCbbankAccountProperty().set(logCompanyBalanceCashFlow.getTblBankAccountByIdsenderCbbankAccount());
        tblCompanyBalanceByIdsenderCompanyBalanceProperty().set(logCompanyBalanceCashFlow.getTblCompanyBalanceByIdsenderCompanyBalance());
        tblCompanyBalanceByIdreceiverCompanyBalanceProperty().set(logCompanyBalanceCashFlow.getTblCompanyBalanceByIdreceiverCompanyBalance());
        tblEmployeeProperty().set(logCompanyBalanceCashFlow.getTblEmployee());
        transferNominalProperty().set(logCompanyBalanceCashFlow.getTransferNominal());
        historyDateProperty().set(logCompanyBalanceCashFlow.getHistoryDate());
        historyNoteProperty().set(logCompanyBalanceCashFlow.getHistoryNote());
        historyStystemNoteProperty().set(logCompanyBalanceCashFlow.getHistoryStystemNote());

        this.tblOpenCloseCashierBalanceDetails = logCompanyBalanceCashFlow.getTblOpenCloseCashierBalanceDetails();
    }

    public final LongProperty idhistoryProperty() {
        return this.idhistory;
    }

    public long getIdhistory() {
        return idhistoryProperty().get();
    }

    public void setIdhistory(long idhistory) {
        idhistoryProperty().set(idhistory);
    }

    public final ObjectProperty<TblBankAccount> tblBankAccountByIdreceiverCbbankAccountProperty() {
        return this.tblBankAccountByIdreceiverCbbankAccount;
    }

    public TblBankAccount getTblBankAccountByIdreceiverCbbankAccount() {
        return tblBankAccountByIdreceiverCbbankAccountProperty().get();
    }

    public void setTblBankAccountByIdreceiverCbbankAccount(TblBankAccount tblBankAccountByIdreceiverCbbankAccount) {
        tblBankAccountByIdreceiverCbbankAccountProperty().set(tblBankAccountByIdreceiverCbbankAccount);
    }

    public final ObjectProperty<TblBankAccount> tblBankAccountByIdsenderCbbankAccountProperty() {
        return this.tblBankAccountByIdsenderCbbankAccount;
    }

    public TblBankAccount getTblBankAccountByIdsenderCbbankAccount() {
        return tblBankAccountByIdsenderCbbankAccountProperty().get();
    }

    public void setTblBankAccountByIdsenderCbbankAccount(TblBankAccount tblBankAccountByIdsenderCbbankAccount) {
        tblBankAccountByIdsenderCbbankAccountProperty().set(tblBankAccountByIdsenderCbbankAccount);
    }

    public final ObjectProperty<TblCompanyBalance> tblCompanyBalanceByIdsenderCompanyBalanceProperty() {
        return this.tblCompanyBalanceByIdsenderCompanyBalance;
    }

    public TblCompanyBalance getTblCompanyBalanceByIdsenderCompanyBalance() {
        return tblCompanyBalanceByIdsenderCompanyBalanceProperty().get();
    }

    public void setTblCompanyBalanceByIdsenderCompanyBalance(TblCompanyBalance tblCompanyBalanceByIdsenderCompanyBalance) {
        tblCompanyBalanceByIdsenderCompanyBalanceProperty().set(tblCompanyBalanceByIdsenderCompanyBalance);
    }

    public final ObjectProperty<TblCompanyBalance> tblCompanyBalanceByIdreceiverCompanyBalanceProperty() {
        return this.tblCompanyBalanceByIdreceiverCompanyBalance;
    }

    public TblCompanyBalance getTblCompanyBalanceByIdreceiverCompanyBalance() {
        return tblCompanyBalanceByIdreceiverCompanyBalanceProperty().get();
    }

    public void setTblCompanyBalanceByIdreceiverCompanyBalance(TblCompanyBalance tblCompanyBalanceByIdreceiverCompanyBalance) {
        tblCompanyBalanceByIdreceiverCompanyBalanceProperty().set(tblCompanyBalanceByIdreceiverCompanyBalance);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeProperty() {
        return this.tblEmployee;
    }

    public TblEmployee getTblEmployee() {
        return tblEmployeeProperty().get();
    }

    public void setTblEmployee(TblEmployee tblEmployee) {
        tblEmployeeProperty().set(tblEmployee);
    }

    public final ObjectProperty<BigDecimal> transferNominalProperty() {
        return this.transferNominal;
    }

    public BigDecimal getTransferNominal() {
        return transferNominalProperty().get();
    }

    public void setTransferNominal(BigDecimal transferNominal) {
        transferNominalProperty().set(transferNominal);
    }

    public final ObjectProperty<Date> historyDateProperty() {
        return this.historyDate;
    }

    public Date getHistoryDate() {
        return historyDateProperty().get();
    }

    public void setHistoryDate(Date historyDate) {
        historyDateProperty().set(historyDate);
    }

    public final StringProperty historyNoteProperty() {
        return this.historyNote;
    }

    public String getHistoryNote() {
        return historyNoteProperty().get();
    }

    public void setHistoryNote(String historyNote) {
        historyNoteProperty().set(historyNote);
    }

    public final StringProperty historyStystemNoteProperty() {
        return this.historyStystemNote;
    }

    public String getHistoryStystemNote() {
        return historyStystemNoteProperty().get();
    }

    public void setHistoryStystemNote(String historyStystemNote) {
        historyStystemNoteProperty().set(historyStystemNote);
    }

    public Set getTblOpenCloseCashierBalanceDetails() {
        return this.tblOpenCloseCashierBalanceDetails;
    }

    public void setTblOpenCloseCashierBalanceDetails(Set tblOpenCloseCashierBalanceDetails) {
        this.tblOpenCloseCashierBalanceDetails = tblOpenCloseCashierBalanceDetails;
    }

}
