package hotelfx.persistence.model;
// Generated Oct 16, 2018 9:09:21 AM by Hibernate Tools 4.3.1

import java.util.Date;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;

/**
 * LogRoomTypeHistory generated by hbm2java
 */
public class LogRoomTypeHistory implements java.io.Serializable {

    private final LongProperty idrelation;
    private final ObjectProperty<TblRoomType> tblRoomType;
    private final ObjectProperty<Date> historyDate;
    private final LongProperty roomTypeQuantity;

    public LogRoomTypeHistory() {
        this.idrelation = new SimpleLongProperty();
        this.tblRoomType = new SimpleObjectProperty<>();
        this.historyDate = new SimpleObjectProperty<>();
        this.roomTypeQuantity = new SimpleLongProperty();

    }

    public LogRoomTypeHistory(long idrelation) {
        this();
        idrelationProperty().set(idrelation);
    }

    public LogRoomTypeHistory(long idrelation, TblRoomType tblRoomType, Date historyDate, Long roomTypeQuantity) {
        this();
        idrelationProperty().set(idrelation);
        tblRoomTypeProperty().set(tblRoomType);
        historyDateProperty().set(historyDate);
        roomTypeQuantityProperty().set(roomTypeQuantity);

    }

    public LogRoomTypeHistory(LogRoomTypeHistory logRoomTypeHistory) {
        this();
        idrelationProperty().set(logRoomTypeHistory.getIdrelation());
        tblRoomTypeProperty().set(logRoomTypeHistory.getTblRoomType());
        historyDateProperty().set(logRoomTypeHistory.getHistoryDate());
        roomTypeQuantityProperty().set(logRoomTypeHistory.getRoomTypeQuantity());

    }

    public final LongProperty idrelationProperty() {
        return this.idrelation;
    }

    public long getIdrelation() {
        return idrelationProperty().get();
    }

    public void setIdrelation(long idrelation) {
        idrelationProperty().set(idrelation);
    }

    public final ObjectProperty<TblRoomType> tblRoomTypeProperty() {
        return this.tblRoomType;
    }

    public TblRoomType getTblRoomType() {
        return tblRoomTypeProperty().get();
    }

    public void setTblRoomType(TblRoomType tblRoomType) {
        tblRoomTypeProperty().set(tblRoomType);
    }

    public final ObjectProperty<Date> historyDateProperty() {
        return this.historyDate;
    }

    public Date getHistoryDate() {
        return historyDateProperty().get();
    }

    public void setHistoryDate(Date historyDate) {
        historyDateProperty().set(historyDate);
    }

    public final LongProperty roomTypeQuantityProperty() {
        return this.roomTypeQuantity;
    }

    public Long getRoomTypeQuantity() {
        return roomTypeQuantityProperty().get();
    }

    public void setRoomTypeQuantity(Long roomTypeQuantity) {
        roomTypeQuantityProperty().set(roomTypeQuantity);
    }

}
