package hotelfx.persistence.model;
// Generated Apr 19, 2018 2:33:40 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * LogRoomTypePriceChangedHistory generated by hbm2java
 */
public class LogRoomTypePriceChangedHistory implements java.io.Serializable {

    private final LongProperty idhistory;
    private final ObjectProperty<TblEmployee> tblEmployee;
    private final ObjectProperty<TblRoomType> tblRoomType;
    private final ObjectProperty<BigDecimal> roomTypePrice;
    private final ObjectProperty<Date> historyDate;
    private final StringProperty historyNote;

    public LogRoomTypePriceChangedHistory() {
        this.idhistory = new SimpleLongProperty();
        this.tblEmployee = new SimpleObjectProperty<>();
        this.tblRoomType = new SimpleObjectProperty<>();
        this.roomTypePrice = new SimpleObjectProperty<>();
        this.historyDate = new SimpleObjectProperty<>();
        this.historyNote = new SimpleStringProperty();

    }

    public LogRoomTypePriceChangedHistory(long idhistory) {
        this();
        idhistoryProperty().set(idhistory);
    }

    public LogRoomTypePriceChangedHistory(long idhistory, TblEmployee tblEmployee, TblRoomType tblRoomType, BigDecimal roomTypePrice, Date historyDate, String historyNote) {
        this();
        idhistoryProperty().set(idhistory);
        tblEmployeeProperty().set(tblEmployee);
        tblRoomTypeProperty().set(tblRoomType);
        roomTypePriceProperty().set(roomTypePrice);
        historyDateProperty().set(historyDate);
        historyNoteProperty().set(historyNote);

    }

    public LogRoomTypePriceChangedHistory(LogRoomTypePriceChangedHistory logRoomTypePriceChangedHistory) {
        this();
        idhistoryProperty().set(logRoomTypePriceChangedHistory.getIdhistory());
        tblEmployeeProperty().set(logRoomTypePriceChangedHistory.getTblEmployee());
        tblRoomTypeProperty().set(logRoomTypePriceChangedHistory.getTblRoomType());
        roomTypePriceProperty().set(logRoomTypePriceChangedHistory.getRoomTypePrice());
        historyDateProperty().set(logRoomTypePriceChangedHistory.getHistoryDate());
        historyNoteProperty().set(logRoomTypePriceChangedHistory.getHistoryNote());

    }

    public final LongProperty idhistoryProperty() {
        return this.idhistory;
    }

    public long getIdhistory() {
        return idhistoryProperty().get();
    }

    public void setIdhistory(long idhistory) {
        idhistoryProperty().set(idhistory);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeProperty() {
        return this.tblEmployee;
    }

    public TblEmployee getTblEmployee() {
        return tblEmployeeProperty().get();
    }

    public void setTblEmployee(TblEmployee tblEmployee) {
        tblEmployeeProperty().set(tblEmployee);
    }

    public final ObjectProperty<TblRoomType> tblRoomTypeProperty() {
        return this.tblRoomType;
    }

    public TblRoomType getTblRoomType() {
        return tblRoomTypeProperty().get();
    }

    public void setTblRoomType(TblRoomType tblRoomType) {
        tblRoomTypeProperty().set(tblRoomType);
    }

    public final ObjectProperty<BigDecimal> roomTypePriceProperty() {
        return this.roomTypePrice;
    }

    public BigDecimal getRoomTypePrice() {
        return roomTypePriceProperty().get();
    }

    public void setRoomTypePrice(BigDecimal roomTypePrice) {
        roomTypePriceProperty().set(roomTypePrice);
    }

    public final ObjectProperty<Date> historyDateProperty() {
        return this.historyDate;
    }

    public Date getHistoryDate() {
        return historyDateProperty().get();
    }

    public void setHistoryDate(Date historyDate) {
        historyDateProperty().set(historyDate);
    }

    public final StringProperty historyNoteProperty() {
        return this.historyNote;
    }

    public String getHistoryNote() {
        return historyNoteProperty().get();
    }

    public void setHistoryNote(String historyNote) {
        historyNoteProperty().set(historyNote);
    }

}
