package hotelfx.persistence.model;
// Generated Apr 4, 2018 9:07:24 AM by Hibernate Tools 4.3.1

import java.util.Date;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * LogSystem generated by hbm2java
 */
public class LogSystem implements java.io.Serializable {

    private final LongProperty idlog;
    private final ObjectProperty<TblEmployee> tblEmployee;
    private final ObjectProperty<TblSystemUser> tblSystemUser;
    private final ObjectProperty<Date> logDateTime;
    private final StringProperty hostName;
    private final StringProperty logHeader;
    private final StringProperty logDetail;

    public LogSystem() {
        this.idlog = new SimpleLongProperty();
        this.tblEmployee = new SimpleObjectProperty<>();
        this.tblSystemUser = new SimpleObjectProperty<>();
        this.logDateTime = new SimpleObjectProperty<>();
        this.hostName = new SimpleStringProperty();
        this.logHeader = new SimpleStringProperty();
        this.logDetail = new SimpleStringProperty();

    }

    public LogSystem(long idlog) {
        this();
        idlogProperty().set(idlog);
    }

    public LogSystem(long idlog, TblEmployee tblEmployee, TblSystemUser tblSystemUser, Date logDateTime, String hostName, String logHeader, String logDetail) {
        this();
        idlogProperty().set(idlog);
        tblEmployeeProperty().set(tblEmployee);
        tblSystemUserProperty().set(tblSystemUser);
        logDateTimeProperty().set(logDateTime);
        hostNameProperty().set(hostName);
        logHeaderProperty().set(logHeader);
        logDetailProperty().set(logDetail);

    }

    public LogSystem(LogSystem logSystem) {
        this();
        idlogProperty().set(logSystem.getIdlog());
        tblEmployeeProperty().set(logSystem.getTblEmployee());
        tblSystemUserProperty().set(logSystem.getTblSystemUser());
        logDateTimeProperty().set(logSystem.getLogDateTime());
        hostNameProperty().set(logSystem.getHostName());
        logHeaderProperty().set(logSystem.getLogHeader());
        logDetailProperty().set(logSystem.getLogDetail());

    }

    public final LongProperty idlogProperty() {
        return this.idlog;
    }

    public long getIdlog() {
        return idlogProperty().get();
    }

    public void setIdlog(long idlog) {
        idlogProperty().set(idlog);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeProperty() {
        return this.tblEmployee;
    }

    public TblEmployee getTblEmployee() {
        return tblEmployeeProperty().get();
    }

    public void setTblEmployee(TblEmployee tblEmployee) {
        tblEmployeeProperty().set(tblEmployee);
    }

    public final ObjectProperty<TblSystemUser> tblSystemUserProperty() {
        return this.tblSystemUser;
    }

    public TblSystemUser getTblSystemUser() {
        return tblSystemUserProperty().get();
    }

    public void setTblSystemUser(TblSystemUser tblSystemUser) {
        tblSystemUserProperty().set(tblSystemUser);
    }

    public final ObjectProperty<Date> logDateTimeProperty() {
        return this.logDateTime;
    }

    public Date getLogDateTime() {
        return logDateTimeProperty().get();
    }

    public void setLogDateTime(Date logDateTime) {
        logDateTimeProperty().set(logDateTime);
    }

    public final StringProperty hostNameProperty() {
        return this.hostName;
    }

    public String getHostName() {
        return hostNameProperty().get();
    }

    public void setHostName(String hostName) {
        hostNameProperty().set(hostName);
    }

    public final StringProperty logHeaderProperty() {
        return this.logHeader;
    }

    public String getLogHeader() {
        return logHeaderProperty().get();
    }

    public void setLogHeader(String logHeader) {
        logHeaderProperty().set(logHeader);
    }

    public final StringProperty logDetailProperty() {
        return this.logDetail;
    }

    public String getLogDetail() {
        return logDetailProperty().get();
    }

    public void setLogDetail(String logDetail) {
        logDetailProperty().set(logDetail);
    }

}
