package hotelfx.persistence.model;
// Generated Aug 21, 2017 1:49:32 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javafx.beans.property.IntegerProperty;
import javafx.beans.property.SimpleIntegerProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * RefApplicantStatus generated by hbm2java
 */
public class RefApplicantStatus implements java.io.Serializable {

    private final IntegerProperty idstatus;
    private final StringProperty statusName;
    private final StringProperty statusNote;

    private Set tblApplicants;

    public RefApplicantStatus() {
        this.idstatus = new SimpleIntegerProperty();
        this.statusName = new SimpleStringProperty();
        this.statusNote = new SimpleStringProperty();

        this.tblApplicants = new HashSet(0);

    }

    public RefApplicantStatus(int idstatus) {
        this();
        idstatusProperty().set(idstatus);
    }

    public RefApplicantStatus(int idstatus, String statusName, String statusNote, Set tblApplicants) {
        this();
        idstatusProperty().set(idstatus);
        statusNameProperty().set(statusName);
        statusNoteProperty().set(statusNote);

        this.tblApplicants = tblApplicants;
    }

    public RefApplicantStatus(RefApplicantStatus refApplicantStatus) {
        this();
        idstatusProperty().set(refApplicantStatus.getIdstatus());
        statusNameProperty().set(refApplicantStatus.getStatusName());
        statusNoteProperty().set(refApplicantStatus.getStatusNote());

        this.tblApplicants = refApplicantStatus.getTblApplicants();
    }

    public final IntegerProperty idstatusProperty() {
        return this.idstatus;
    }

    public int getIdstatus() {
        return idstatusProperty().get();
    }

    public void setIdstatus(int idstatus) {
        idstatusProperty().set(idstatus);
    }

    public final StringProperty statusNameProperty() {
        return this.statusName;
    }

    public String getStatusName() {
        return statusNameProperty().get();
    }

    public void setStatusName(String statusName) {
        statusNameProperty().set(statusName);
    }

    public final StringProperty statusNoteProperty() {
        return this.statusNote;
    }

    public String getStatusNote() {
        return statusNoteProperty().get();
    }

    public void setStatusNote(String statusNote) {
        statusNoteProperty().set(statusNote);
    }

    public Set getTblApplicants() {
        return this.tblApplicants;
    }

    public void setTblApplicants(Set tblApplicants) {
        this.tblApplicants = tblApplicants;
    }

}
