package hotelfx.persistence.model;
// Generated Aug 21, 2017 1:49:32 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javafx.beans.property.IntegerProperty;
import javafx.beans.property.SimpleIntegerProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * RefAccountType generated by hbm2java
 */
public class RefAccountType implements java.io.Serializable {

    private final IntegerProperty idtype;
    private final StringProperty typeName;
    private final StringProperty typeNote;

    private Set sysAccounts;

    public RefAccountType() {
        this.idtype = new SimpleIntegerProperty();
        this.typeName = new SimpleStringProperty();
        this.typeNote = new SimpleStringProperty();

        this.sysAccounts = new HashSet(0);
    }

    public RefAccountType(int idtype) {
        this();
        idtypeProperty().set(idtype);
    }

    public RefAccountType(int idtype, String typeName, String typeNote, Set sysAccounts) {
        this();
        idtypeProperty().set(idtype);
        typeNameProperty().set(typeName);
        typeNoteProperty().set(typeNote);

        this.sysAccounts = sysAccounts;
    }

    public RefAccountType(RefAccountType refAccountType) {
        this();
        idtypeProperty().set(refAccountType.getIdtype());
        typeNameProperty().set(refAccountType.getTypeName());
        typeNoteProperty().set(refAccountType.getTypeNote());

        this.sysAccounts = refAccountType.getSysAccounts();
    }

    public final IntegerProperty idtypeProperty() {
        return this.idtype;
    }

    public int getIdtype() {
        return idtypeProperty().get();
    }

    public void setIdtype(int idtype) {
        idtypeProperty().set(idtype);
    }

    public final StringProperty typeNameProperty() {
        return this.typeName;
    }

    public String getTypeName() {
        return typeNameProperty().get();
    }

    public void setTypeName(String typeName) {
        typeNameProperty().set(typeName);
    }

    public final StringProperty typeNoteProperty() {
        return this.typeNote;
    }

    public String getTypeNote() {
        return typeNoteProperty().get();
    }

    public void setTypeNote(String typeNote) {
        typeNoteProperty().set(typeNote);
    }

    public Set getSysAccounts() {
        return this.sysAccounts;
    }

    public void setSysAccounts(Set sysAccounts) {
        this.sysAccounts = sysAccounts;
    }
    
    @Override
    public String toString(){
        return getTypeName();
    }

}
