package hotelfx.persistence.model;
// Generated Oct 24, 2018 12:59:27 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javafx.beans.property.IntegerProperty;
import javafx.beans.property.SimpleIntegerProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * RefBankAccountHolderStatus generated by hbm2java
 */
public class RefBankAccountHolderStatus implements java.io.Serializable {

    private final IntegerProperty idstatus;
    private final StringProperty statusName;
    private final StringProperty statusNote;

    private Set tblEmployeeBankAccounts;
    private Set tblRestoBankAccounts;
    private Set tblSupplierBankAccounts;
    private Set tblPartnerBankAccounts;
    private Set tblCustomerBankAccounts;

    public RefBankAccountHolderStatus() {
        this.idstatus = new SimpleIntegerProperty();
        this.statusName = new SimpleStringProperty();
        this.statusNote = new SimpleStringProperty();

        this.tblEmployeeBankAccounts = new HashSet(0);
        this.tblRestoBankAccounts = new HashSet(0);
        this.tblSupplierBankAccounts = new HashSet(0);
        this.tblPartnerBankAccounts = new HashSet(0);
        this.tblCustomerBankAccounts = new HashSet(0);
    }

    public RefBankAccountHolderStatus(int idstatus) {
        this();
        idstatusProperty().set(idstatus);
    }

    public RefBankAccountHolderStatus(int idstatus, String statusName, String statusNote, Set tblEmployeeBankAccounts, Set tblRestoBankAccounts, Set tblSupplierBankAccounts, Set tblPartnerBankAccounts, Set tblCustomerBankAccounts) {
        this();
        idstatusProperty().set(idstatus);
        statusNameProperty().set(statusName);
        statusNoteProperty().set(statusNote);

        this.tblEmployeeBankAccounts = tblEmployeeBankAccounts;
        this.tblRestoBankAccounts = tblRestoBankAccounts;
        this.tblSupplierBankAccounts = tblSupplierBankAccounts;
        this.tblPartnerBankAccounts = tblPartnerBankAccounts;
        this.tblCustomerBankAccounts = tblCustomerBankAccounts;
    }

    public RefBankAccountHolderStatus(RefBankAccountHolderStatus refBankAccountHolderStatus) {
        this();
        idstatusProperty().set(refBankAccountHolderStatus.getIdstatus());
        statusNameProperty().set(refBankAccountHolderStatus.getStatusName());
        statusNoteProperty().set(refBankAccountHolderStatus.getStatusNote());

        this.tblEmployeeBankAccounts = refBankAccountHolderStatus.getTblEmployeeBankAccounts();
        this.tblRestoBankAccounts = refBankAccountHolderStatus.getTblRestoBankAccounts();
        this.tblSupplierBankAccounts = refBankAccountHolderStatus.getTblSupplierBankAccounts();
        this.tblPartnerBankAccounts = refBankAccountHolderStatus.getTblPartnerBankAccounts();
        this.tblCustomerBankAccounts = refBankAccountHolderStatus.getTblCustomerBankAccounts();
    }

    public final IntegerProperty idstatusProperty() {
        return this.idstatus;
    }

    public int getIdstatus() {
        return idstatusProperty().get();
    }

    public void setIdstatus(int idstatus) {
        idstatusProperty().set(idstatus);
    }

    public final StringProperty statusNameProperty() {
        return this.statusName;
    }

    public String getStatusName() {
        return statusNameProperty().get();
    }

    public void setStatusName(String statusName) {
        statusNameProperty().set(statusName);
    }

    public final StringProperty statusNoteProperty() {
        return this.statusNote;
    }

    public String getStatusNote() {
        return statusNoteProperty().get();
    }

    public void setStatusNote(String statusNote) {
        statusNoteProperty().set(statusNote);
    }

    public Set getTblEmployeeBankAccounts() {
        return this.tblEmployeeBankAccounts;
    }

    public void setTblEmployeeBankAccounts(Set tblEmployeeBankAccounts) {
        this.tblEmployeeBankAccounts = tblEmployeeBankAccounts;
    }

    public Set getTblRestoBankAccounts() {
        return this.tblRestoBankAccounts;
    }

    public void setTblRestoBankAccounts(Set tblRestoBankAccounts) {
        this.tblRestoBankAccounts = tblRestoBankAccounts;
    }

    public Set getTblSupplierBankAccounts() {
        return this.tblSupplierBankAccounts;
    }

    public void setTblSupplierBankAccounts(Set tblSupplierBankAccounts) {
        this.tblSupplierBankAccounts = tblSupplierBankAccounts;
    }

    public Set getTblPartnerBankAccounts() {
        return this.tblPartnerBankAccounts;
    }

    public void setTblPartnerBankAccounts(Set tblPartnerBankAccounts) {
        this.tblPartnerBankAccounts = tblPartnerBankAccounts;
    }

    public Set getTblCustomerBankAccounts() {
        return this.tblCustomerBankAccounts;
    }

    public void setTblCustomerBankAccounts(Set tblCustomerBankAccounts) {
        this.tblCustomerBankAccounts = tblCustomerBankAccounts;
    }

    @Override
    public String toString() {
        return getStatusName();
    }
    
}
