package hotelfx.persistence.model;
// Generated Aug 21, 2017 1:49:32 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javafx.beans.property.IntegerProperty;
import javafx.beans.property.SimpleIntegerProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * RefCustomerType generated by hbm2java
 */
public class RefCustomerType implements java.io.Serializable {

    private final IntegerProperty idtype;
    private final StringProperty typeName;
    private final StringProperty typeNote;

    private Set tblCustomers;

    public RefCustomerType() {
        this.idtype = new SimpleIntegerProperty();
        this.typeName = new SimpleStringProperty();
        this.typeNote = new SimpleStringProperty();

        this.tblCustomers = new HashSet(0);
    }

    public RefCustomerType(int idtype) {
        this();
        idtypeProperty().set(idtype);
    }

    public RefCustomerType(int idtype, String typeName, String typeNote, Set tblCustomers) {
        this();
        idtypeProperty().set(idtype);
        typeNameProperty().set(typeName);
        typeNoteProperty().set(typeNote);

        this.tblCustomers = tblCustomers;
    }

    public RefCustomerType(RefCustomerType refCustomerType) {
        this();
        idtypeProperty().set(refCustomerType.getIdtype());
        typeNameProperty().set(refCustomerType.getTypeName());
        typeNoteProperty().set(refCustomerType.getTypeNote());

        this.tblCustomers = refCustomerType.getTblCustomers();
    }

    public final IntegerProperty idtypeProperty() {
        return this.idtype;
    }

    public int getIdtype() {
        return idtypeProperty().get();
    }

    public void setIdtype(int idtype) {
        idtypeProperty().set(idtype);
    }

    public final StringProperty typeNameProperty() {
        return this.typeName;
    }

    public String getTypeName() {
        return typeNameProperty().get();
    }

    public void setTypeName(String typeName) {
        typeNameProperty().set(typeName);
    }

    public final StringProperty typeNoteProperty() {
        return this.typeNote;
    }

    public String getTypeNote() {
        return typeNoteProperty().get();
    }

    public void setTypeNote(String typeNote) {
        typeNoteProperty().set(typeNote);
    }

    public Set getTblCustomers() {
        return this.tblCustomers;
    }

    public void setTblCustomers(Set tblCustomers) {
        this.tblCustomers = tblCustomers;
    }

    @Override
    public String toString() {
        return getTypeName();
    }

}
