package hotelfx.persistence.model;
// Generated Mar 5, 2018 11:24:30 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javafx.beans.property.IntegerProperty;
import javafx.beans.property.SimpleIntegerProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * RefCountry generated by hbm2java
 */
public class RefCountry implements java.io.Serializable {

    private final IntegerProperty idcountry;
    private final StringProperty countryName;
    private final StringProperty countryNote;

    private Set tblPeoples;

    public RefCountry() {
        this.idcountry = new SimpleIntegerProperty();
        this.countryName = new SimpleStringProperty();
        this.countryNote = new SimpleStringProperty();

        this.tblPeoples = new HashSet(0);
    }

    public RefCountry(int idcountry) {
        this();
        idcountryProperty().set(idcountry);
    }

    public RefCountry(int idcountry, String countryName, String countryNote, Set tblPeoples) {
        this();
        idcountryProperty().set(idcountry);
        countryNameProperty().set(countryName);
        countryNoteProperty().set(countryNote);

        this.tblPeoples = tblPeoples;
    }

    public RefCountry(RefCountry refCountry) {
        this();
        idcountryProperty().set(refCountry.getIdcountry());
        countryNameProperty().set(refCountry.getCountryName());
        countryNoteProperty().set(refCountry.getCountryNote());

        this.tblPeoples = refCountry.getTblPeoples();
    }

    public final IntegerProperty idcountryProperty() {
        return this.idcountry;
    }

    public int getIdcountry() {
        return idcountryProperty().get();
    }

    public void setIdcountry(int idcountry) {
        idcountryProperty().set(idcountry);
    }

    public final StringProperty countryNameProperty() {
        return this.countryName;
    }

    public String getCountryName() {
        return countryNameProperty().get();
    }

    public void setCountryName(String countryName) {
        countryNameProperty().set(countryName);
    }

    public final StringProperty countryNoteProperty() {
        return this.countryNote;
    }

    public String getCountryNote() {
        return countryNoteProperty().get();
    }

    public void setCountryNote(String countryNote) {
        countryNoteProperty().set(countryNote);
    }

    public Set getTblPeoples() {
        return this.tblPeoples;
    }

    public void setTblPeoples(Set tblPeoples) {
        this.tblPeoples = tblPeoples;
    }

    @Override
    public String toString(){
        return getCountryName();
    }
    
}
