package hotelfx.persistence.model;
// Generated Aug 21, 2017 1:49:32 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javafx.beans.property.IntegerProperty;
import javafx.beans.property.SimpleIntegerProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * RefCustomerStatus generated by hbm2java
 */
public class RefCustomerStatus implements java.io.Serializable {

    private final IntegerProperty idstatus;
    private final StringProperty statusName;
    private final StringProperty statusNote;

    private Set tblCustomers;

    public RefCustomerStatus() {
        this.idstatus = new SimpleIntegerProperty();
        this.statusName = new SimpleStringProperty();
        this.statusNote = new SimpleStringProperty();

        this.tblCustomers = new HashSet(0);
    }

    public RefCustomerStatus(int idstatus) {
        this();
        idstatusProperty().set(idstatus);
    }

    public RefCustomerStatus(int idstatus, String statusName, String statusNote, Set tblCustomers) {
        this();
        idstatusProperty().set(idstatus);
        statusNameProperty().set(statusName);
        statusNoteProperty().set(statusNote);

        this.tblCustomers = tblCustomers;
    }

    public RefCustomerStatus(RefCustomerStatus refCustomerStatus) {
        this();
        idstatusProperty().set(refCustomerStatus.getIdstatus());
        statusNameProperty().set(refCustomerStatus.getStatusName());
        statusNoteProperty().set(refCustomerStatus.getStatusNote());

        this.tblCustomers = refCustomerStatus.getTblCustomers();
    }

    public final IntegerProperty idstatusProperty() {
        return this.idstatus;
    }

    public int getIdstatus() {
        return idstatusProperty().get();
    }

    public void setIdstatus(int idstatus) {
        idstatusProperty().set(idstatus);
    }

    public final StringProperty statusNameProperty() {
        return this.statusName;
    }

    public String getStatusName() {
        return statusNameProperty().get();
    }

    public void setStatusName(String statusName) {
        statusNameProperty().set(statusName);
    }

    public final StringProperty statusNoteProperty() {
        return this.statusNote;
    }

    public String getStatusNote() {
        return statusNoteProperty().get();
    }

    public void setStatusNote(String statusNote) {
        statusNoteProperty().set(statusNote);
    }

    public Set getTblCustomers() {
        return this.tblCustomers;
    }

    public void setTblCustomers(Set tblCustomers) {
        this.tblCustomers = tblCustomers;
    }

    @Override
    public String toString() {
        return getStatusName();
    }

}
