package hotelfx.persistence.model;
// Generated Oct 30, 2018 10:45:55 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javafx.beans.property.IntegerProperty;
import javafx.beans.property.SimpleIntegerProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * RefEndOfDayDataStatus generated by hbm2java
 */
public class RefEndOfDayDataStatus implements java.io.Serializable {

    private final IntegerProperty idstatus;
    private final StringProperty statusName;
    private final StringProperty statusNote;

    private Set tblReservationRoomPriceDetails;
    private Set tblReservationBreakfastVouchers;
    private Set tblReservationCancelingFees;
    private Set tblReservationRoomTypeDetails;
    private Set tblReservationAdditionalItems;
    private Set tblReservationBrokenItems;
    private Set tblReservationAdditionalServices;

    public RefEndOfDayDataStatus() {
        this.idstatus = new SimpleIntegerProperty();
        this.statusName = new SimpleStringProperty();
        this.statusNote = new SimpleStringProperty();

        this.tblReservationRoomPriceDetails = new HashSet(0);
        this.tblReservationBreakfastVouchers = new HashSet(0);
        this.tblReservationCancelingFees = new HashSet(0);
        this.tblReservationRoomTypeDetails = new HashSet(0);
        this.tblReservationAdditionalItems = new HashSet(0);
        this.tblReservationBrokenItems = new HashSet(0);
        this.tblReservationAdditionalServices = new HashSet(0);
    }

    public RefEndOfDayDataStatus(int idstatus) {
        this();
        idstatusProperty().set(idstatus);
    }

    public RefEndOfDayDataStatus(int idstatus, String statusName, String statusNote, Set tblReservationRoomPriceDetails, Set tblReservationBreakfastVouchers, Set tblReservationCancelingFees, Set tblReservationRoomTypeDetails, Set tblReservationAdditionalItems, Set tblReservationBrokenItems, Set tblReservationAdditionalServices) {
        this();
        idstatusProperty().set(idstatus);
        statusNameProperty().set(statusName);
        statusNoteProperty().set(statusNote);

        this.tblReservationRoomPriceDetails = tblReservationRoomPriceDetails;
        this.tblReservationBreakfastVouchers = tblReservationBreakfastVouchers;
        this.tblReservationCancelingFees = tblReservationCancelingFees;
        this.tblReservationRoomTypeDetails = tblReservationRoomTypeDetails;
        this.tblReservationAdditionalItems = tblReservationAdditionalItems;
        this.tblReservationBrokenItems = tblReservationBrokenItems;
        this.tblReservationAdditionalServices = tblReservationAdditionalServices;
    }

    public RefEndOfDayDataStatus(RefEndOfDayDataStatus refEndOfDayDataStatus) {
        this();
        idstatusProperty().set(refEndOfDayDataStatus.getIdstatus());
        statusNameProperty().set(refEndOfDayDataStatus.getStatusName());
        statusNoteProperty().set(refEndOfDayDataStatus.getStatusNote());

        this.tblReservationRoomPriceDetails = refEndOfDayDataStatus.getTblReservationRoomPriceDetails();
        this.tblReservationBreakfastVouchers = refEndOfDayDataStatus.getTblReservationBreakfastVouchers();
        this.tblReservationCancelingFees = refEndOfDayDataStatus.getTblReservationCancelingFees();
        this.tblReservationRoomTypeDetails = refEndOfDayDataStatus.getTblReservationRoomTypeDetails();
        this.tblReservationAdditionalItems = refEndOfDayDataStatus.getTblReservationAdditionalItems();
        this.tblReservationBrokenItems = refEndOfDayDataStatus.getTblReservationBrokenItems();
        this.tblReservationAdditionalServices = refEndOfDayDataStatus.getTblReservationAdditionalServices();
    }

    public final IntegerProperty idstatusProperty() {
        return this.idstatus;
    }

    public int getIdstatus() {
        return idstatusProperty().get();
    }

    public void setIdstatus(int idstatus) {
        idstatusProperty().set(idstatus);
    }

    public final StringProperty statusNameProperty() {
        return this.statusName;
    }

    public String getStatusName() {
        return statusNameProperty().get();
    }

    public void setStatusName(String statusName) {
        statusNameProperty().set(statusName);
    }

    public final StringProperty statusNoteProperty() {
        return this.statusNote;
    }

    public String getStatusNote() {
        return statusNoteProperty().get();
    }

    public void setStatusNote(String statusNote) {
        statusNoteProperty().set(statusNote);
    }

    public Set getTblReservationRoomPriceDetails() {
        return this.tblReservationRoomPriceDetails;
    }

    public void setTblReservationRoomPriceDetails(Set tblReservationRoomPriceDetails) {
        this.tblReservationRoomPriceDetails = tblReservationRoomPriceDetails;
    }

    public Set getTblReservationBreakfastVouchers() {
        return this.tblReservationBreakfastVouchers;
    }

    public void setTblReservationBreakfastVouchers(Set tblReservationBreakfastVouchers) {
        this.tblReservationBreakfastVouchers = tblReservationBreakfastVouchers;
    }

    public Set getTblReservationCancelingFees() {
        return this.tblReservationCancelingFees;
    }

    public void setTblReservationCancelingFees(Set tblReservationCancelingFees) {
        this.tblReservationCancelingFees = tblReservationCancelingFees;
    }

    public Set getTblReservationRoomTypeDetails() {
        return this.tblReservationRoomTypeDetails;
    }

    public void setTblReservationRoomTypeDetails(Set tblReservationRoomTypeDetails) {
        this.tblReservationRoomTypeDetails = tblReservationRoomTypeDetails;
    }

    public Set getTblReservationAdditionalItems() {
        return this.tblReservationAdditionalItems;
    }

    public void setTblReservationAdditionalItems(Set tblReservationAdditionalItems) {
        this.tblReservationAdditionalItems = tblReservationAdditionalItems;
    }

    public Set getTblReservationBrokenItems() {
        return this.tblReservationBrokenItems;
    }

    public void setTblReservationBrokenItems(Set tblReservationBrokenItems) {
        this.tblReservationBrokenItems = tblReservationBrokenItems;
    }

    public Set getTblReservationAdditionalServices() {
        return this.tblReservationAdditionalServices;
    }

    public void setTblReservationAdditionalServices(Set tblReservationAdditionalServices) {
        this.tblReservationAdditionalServices = tblReservationAdditionalServices;
    }

}
