package hotelfx.persistence.model;
// Generated Aug 21, 2017 1:49:32 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javafx.beans.property.IntegerProperty;
import javafx.beans.property.SimpleIntegerProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * RefEmployeeResignType generated by hbm2java
 */
public class RefEmployeeResignType implements java.io.Serializable {

    private final IntegerProperty idtype;
    private final StringProperty typeName;
    private final StringProperty typeNote;

    private Set tblEmployeeResigns;

    public RefEmployeeResignType() {
        this.idtype = new SimpleIntegerProperty();
        this.typeName = new SimpleStringProperty();
        this.typeNote = new SimpleStringProperty();

        this.tblEmployeeResigns = new HashSet(0);
    }

    public RefEmployeeResignType(int idtype) {
        this();
        idtypeProperty().set(idtype);
    }

    public RefEmployeeResignType(int idtype, String typeName, String typeNote, Set tblEmployeeResigns) {
        this();
        idtypeProperty().set(idtype);
        typeNameProperty().set(typeName);
        typeNoteProperty().set(typeNote);
        this.tblEmployeeResigns = tblEmployeeResigns;
    }

    public RefEmployeeResignType(RefEmployeeResignType refEmployeeResignType) {
        this();
        idtypeProperty().set(refEmployeeResignType.getIdtype());
        typeNameProperty().set(refEmployeeResignType.getTypeName());
        typeNoteProperty().set(refEmployeeResignType.getTypeNote());

        this.tblEmployeeResigns = refEmployeeResignType.getTblEmployeeResigns();
    }

    public final IntegerProperty idtypeProperty() {
        return this.idtype;
    }

    public int getIdtype() {
        return idtypeProperty().get();
    }

    public void setIdtype(int idtype) {
        idtypeProperty().set(idtype);
    }

    public final StringProperty typeNameProperty() {
        return this.typeName;
    }

    public String getTypeName() {
        return typeNameProperty().get();
    }

    public void setTypeName(String typeName) {
        typeNameProperty().set(typeName);
    }

    public final StringProperty typeNoteProperty() {
        return this.typeNote;
    }

    public String getTypeNote() {
        return typeNoteProperty().get();
    }

    public void setTypeNote(String typeNote) {
        typeNoteProperty().set(typeNote);
    }

    public Set getTblEmployeeResigns() {
        return this.tblEmployeeResigns;
    }

    public void setTblEmployeeResigns(Set tblEmployeeResigns) {
        this.tblEmployeeResigns = tblEmployeeResigns;
    }

}
