package hotelfx.persistence.model;
// Generated Aug 21, 2017 1:49:32 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javafx.beans.property.IntegerProperty;
import javafx.beans.property.SimpleIntegerProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * RefEdcstatus generated by hbm2java
 */
public class RefEdcstatus implements java.io.Serializable {

    private final IntegerProperty idstatus;
    private final StringProperty statusName;
    private final StringProperty statusNote;

    private Set tblBankEdcs;

    public RefEdcstatus() {
        this.idstatus = new SimpleIntegerProperty();
        this.statusName = new SimpleStringProperty();
        this.statusNote = new SimpleStringProperty();

        this.tblBankEdcs = new HashSet(0);
    }

    public RefEdcstatus(int idstatus) {
        this();
        idstatusProperty().set(idstatus);
    }

    public RefEdcstatus(int idstatus, String statusName, String statusNote, Set tblBankEdcs) {
        this();
        idstatusProperty().set(idstatus);
        statusNameProperty().set(statusName);
        statusNoteProperty().set(statusNote);

        this.tblBankEdcs = tblBankEdcs;
    }

    public RefEdcstatus(RefEdcstatus refEdcstatus) {
        this();
        idstatusProperty().set(refEdcstatus.getIdstatus());
        statusNameProperty().set(refEdcstatus.getStatusName());
        statusNoteProperty().set(refEdcstatus.getStatusNote());

        this.tblBankEdcs = refEdcstatus.getTblBankEdcs();
    }

    public final IntegerProperty idstatusProperty() {
        return this.idstatus;
    }

    public int getIdstatus() {
        return idstatusProperty().get();
    }

    public void setIdstatus(int idstatus) {
        idstatusProperty().set(idstatus);
    }

    public final StringProperty statusNameProperty() {
        return this.statusName;
    }

    public String getStatusName() {
        return statusNameProperty().get();
    }

    public void setStatusName(String statusName) {
        statusNameProperty().set(statusName);
    }

    public final StringProperty statusNoteProperty() {
        return this.statusNote;
    }

    public String getStatusNote() {
        return statusNoteProperty().get();
    }

    public void setStatusNote(String statusNote) {
        statusNoteProperty().set(statusNote);
    }

    public Set getTblBankEdcs() {
        return this.tblBankEdcs;
    }

    public void setTblBankEdcs(Set tblBankEdcs) {
        this.tblBankEdcs = tblBankEdcs;
    }

}
