package hotelfx.persistence.model;
// Generated Aug 21, 2017 1:49:32 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javafx.beans.property.IntegerProperty;
import javafx.beans.property.SimpleIntegerProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * RefEmployeeSalaryType generated by hbm2java
 */
public class RefEmployeeSalaryType implements java.io.Serializable {

    private final IntegerProperty idtype;
    private final StringProperty typeName;
    private final StringProperty typeNote;

    private Set tblEmployees;

    public RefEmployeeSalaryType() {
        this.idtype = new SimpleIntegerProperty();
        this.typeName = new SimpleStringProperty();
        this.typeNote = new SimpleStringProperty();

        this.tblEmployees = new HashSet(0);
    }

    public RefEmployeeSalaryType(int idtype) {
        this();
        idtypeProperty().set(idtype);
    }

    public RefEmployeeSalaryType(int idtype, String typeName, String typeNote, Set tblEmployees) {
        this();
        idtypeProperty().set(idtype);
        typeNameProperty().set(typeName);
        typeNoteProperty().set(typeNote);
        this.tblEmployees = tblEmployees;
    }

    public RefEmployeeSalaryType(RefEmployeeSalaryType refEmployeeSalaryType) {
        this();
        idtypeProperty().set(refEmployeeSalaryType.getIdtype());
        typeNameProperty().set(refEmployeeSalaryType.getTypeName());
        typeNoteProperty().set(refEmployeeSalaryType.getTypeNote());

        this.tblEmployees = refEmployeeSalaryType.getTblEmployees();
    }

    public final IntegerProperty idtypeProperty() {
        return this.idtype;
    }

    public int getIdtype() {
        return idtypeProperty().get();
    }

    public void setIdtype(int idtype) {
        idtypeProperty().set(idtype);
    }

    public final StringProperty typeNameProperty() {
        return this.typeName;
    }

    public String getTypeName() {
        return typeNameProperty().get();
    }

    public void setTypeName(String typeName) {
        typeNameProperty().set(typeName);
    }

    public final StringProperty typeNoteProperty() {
        return this.typeNote;
    }

    public String getTypeNote() {
        return typeNoteProperty().get();
    }

    public void setTypeNote(String typeNote) {
        typeNoteProperty().set(typeNote);
    }

    public Set getTblEmployees() {
        return this.tblEmployees;
    }

    public void setTblEmployees(Set tblEmployees) {
        this.tblEmployees = tblEmployees;
    }

    @Override
    public String toString() {
        return getTypeName();
    }

}
