package hotelfx.persistence.model;
// Generated Nov 11, 2017 9:08:52 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javafx.beans.property.IntegerProperty;
import javafx.beans.property.SimpleIntegerProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * RefEmployeeLeaveType generated by hbm2java
 */
public class RefEmployeeLeaveType implements java.io.Serializable {

    private final IntegerProperty idtype;
    private final StringProperty typeName;
    private final StringProperty typeNote;

    private Set tblEmployeeLeaveDetails;
    private Set tblCalendarEmployeeLeaves;

    public RefEmployeeLeaveType() {
        this.idtype = new SimpleIntegerProperty();
        this.typeName = new SimpleStringProperty();
        this.typeNote = new SimpleStringProperty();

        this.tblEmployeeLeaveDetails = new HashSet(0);
        this.tblCalendarEmployeeLeaves = new HashSet(0);
    }

    public RefEmployeeLeaveType(int idtype) {
        this();
        idtypeProperty().set(idtype);
    }

    public RefEmployeeLeaveType(int idtype, String typeName, String typeNote, Set tblEmployeeLeaveDetails, Set tblCalendarEmployeeLeaves) {
        this();
        idtypeProperty().set(idtype);
        typeNameProperty().set(typeName);
        typeNoteProperty().set(typeNote);

        this.tblEmployeeLeaveDetails = tblEmployeeLeaveDetails;
        this.tblCalendarEmployeeLeaves = tblCalendarEmployeeLeaves;
    }

    public RefEmployeeLeaveType(RefEmployeeLeaveType refEmployeeLeaveType) {
        this();
        idtypeProperty().set(refEmployeeLeaveType.getIdtype());
        typeNameProperty().set(refEmployeeLeaveType.getTypeName());
        typeNoteProperty().set(refEmployeeLeaveType.getTypeNote());

        this.tblEmployeeLeaveDetails = refEmployeeLeaveType.getTblEmployeeLeaveDetails();
        this.tblCalendarEmployeeLeaves = refEmployeeLeaveType.getTblCalendarEmployeeLeaves();
    }

    public final IntegerProperty idtypeProperty() {
        return this.idtype;
    }

    public int getIdtype() {
        return idtypeProperty().get();
    }

    public void setIdtype(int idtype) {
        idtypeProperty().set(idtype);
    }

    public final StringProperty typeNameProperty() {
        return this.typeName;
    }

    public String getTypeName() {
        return typeNameProperty().get();
    }

    public void setTypeName(String typeName) {
        typeNameProperty().set(typeName);
    }

    public final StringProperty typeNoteProperty() {
        return this.typeNote;
    }

    public String getTypeNote() {
        return typeNoteProperty().get();
    }

    public void setTypeNote(String typeNote) {
        typeNoteProperty().set(typeNote);
    }

    public Set getTblEmployeeLeaveDetails() {
        return this.tblEmployeeLeaveDetails;
    }

    public void setTblEmployeeLeaveDetails(Set tblEmployeeLeaveDetails) {
        this.tblEmployeeLeaveDetails = tblEmployeeLeaveDetails;
    }

    public Set getTblCalendarEmployeeLeaves() {
        return this.tblCalendarEmployeeLeaves;
    }

    public void setTblCalendarEmployeeLeaves(Set tblCalendarEmployeeLeaves) {
        this.tblCalendarEmployeeLeaves = tblCalendarEmployeeLeaves;
    }

    @Override
    public String toString(){
        return getTypeName();
    }
    
}
