package hotelfx.persistence.model;
// Generated Aug 21, 2017 1:49:32 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javafx.beans.property.IntegerProperty;
import javafx.beans.property.SimpleIntegerProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * RefEdctransactionStatus generated by hbm2java
 */
public class RefEdctransactionStatus implements java.io.Serializable {

    private final IntegerProperty idstatus;
    private final StringProperty statusName;
    private final StringProperty statusNote;

    private Set tblReservationPaymentWithBankCards;

    public RefEdctransactionStatus() {
        this.idstatus = new SimpleIntegerProperty();
        this.statusName = new SimpleStringProperty();
        this.statusNote = new SimpleStringProperty();

        this.tblReservationPaymentWithBankCards = new HashSet(0);
    }

    public RefEdctransactionStatus(int idstatus) {
        this();
        idstatusProperty().set(idstatus);
    }

    public RefEdctransactionStatus(int idstatus, String statusName, String statusNote, Set tblReservationPaymentWithBankCards) {
        this();
        idstatusProperty().set(idstatus);
        statusNameProperty().set(statusName);
        statusNoteProperty().set(statusNote);

        this.tblReservationPaymentWithBankCards = tblReservationPaymentWithBankCards;
    }

    public RefEdctransactionStatus(RefEdctransactionStatus refEdctransactionStatus) {
        this();
        idstatusProperty().set(refEdctransactionStatus.getIdstatus());
        statusNameProperty().set(refEdctransactionStatus.getStatusName());
        statusNoteProperty().set(refEdctransactionStatus.getStatusNote());

        this.tblReservationPaymentWithBankCards = refEdctransactionStatus.getTblReservationPaymentWithBankCards();
    }

    public final IntegerProperty idstatusProperty() {
        return this.idstatus;
    }

    public int getIdstatus() {
        return idstatusProperty().get();
    }

    public void setIdstatus(int idstatus) {
        idstatusProperty().set(idstatus);
    }

    public final StringProperty statusNameProperty() {
        return this.statusName;
    }

    public String getStatusName() {
        return statusNameProperty().get();
    }

    public void setStatusName(String statusName) {
        statusNameProperty().set(statusName);
    }

    public final StringProperty statusNoteProperty() {
        return this.statusNote;
    }

    public String getStatusNote() {
        return statusNoteProperty().get();
    }

    public void setStatusNote(String statusNote) {
        statusNoteProperty().set(statusNote);
    }

    public Set getTblReservationPaymentWithBankCards() {
        return this.tblReservationPaymentWithBankCards;
    }

    public void setTblReservationPaymentWithBankCards(Set tblReservationPaymentWithBankCards) {
        this.tblReservationPaymentWithBankCards = tblReservationPaymentWithBankCards;
    }

    @Override
    public String toString() {
        return getStatusName();
    }

}
