package hotelfx.persistence.model;
// Generated Aug 21, 2017 1:49:32 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javafx.beans.property.IntegerProperty;
import javafx.beans.property.SimpleIntegerProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * RefFixedTangibleAssetType generated by hbm2java
 */
public class RefFixedTangibleAssetType implements java.io.Serializable {

    private final IntegerProperty idtype;
    private final StringProperty typeName;
    private final StringProperty typeNote;

    private Set tblFixedTangibleAssets;

    public RefFixedTangibleAssetType() {
        this.idtype = new SimpleIntegerProperty();
        this.typeName = new SimpleStringProperty();
        this.typeNote = new SimpleStringProperty();

        this.tblFixedTangibleAssets = new HashSet(0);
    }

    public RefFixedTangibleAssetType(int idtype) {
        this();
        idtypeProperty().set(idtype);
    }

    public RefFixedTangibleAssetType(int idtype, String typeName, String typeNote, Set tblFixedTangibleAssets) {
        this();
        idtypeProperty().set(idtype);
        typeNameProperty().set(typeName);
        typeNoteProperty().set(typeNote);
        this.tblFixedTangibleAssets = tblFixedTangibleAssets;
    }

    public RefFixedTangibleAssetType(RefFixedTangibleAssetType refFixedTangibleAssetType) {
        this();
        idtypeProperty().set(refFixedTangibleAssetType.getIdtype());
        typeNameProperty().set(refFixedTangibleAssetType.getTypeName());
        typeNoteProperty().set(refFixedTangibleAssetType.getTypeNote());

        this.tblFixedTangibleAssets = refFixedTangibleAssetType.getTblFixedTangibleAssets();
    }

    public final IntegerProperty idtypeProperty() {
        return this.idtype;
    }

    public int getIdtype() {
        return idtypeProperty().get();
    }

    public void setIdtype(int idtype) {
        idtypeProperty().set(idtype);
    }

    public final StringProperty typeNameProperty() {
        return this.typeName;
    }

    public String getTypeName() {
        return typeNameProperty().get();
    }

    public void setTypeName(String typeName) {
        typeNameProperty().set(typeName);
    }

    public final StringProperty typeNoteProperty() {
        return this.typeNote;
    }

    public String getTypeNote() {
        return typeNoteProperty().get();
    }

    public void setTypeNote(String typeNote) {
        typeNoteProperty().set(typeNote);
    }

    public Set getTblFixedTangibleAssets() {
        return this.tblFixedTangibleAssets;
    }

    public void setTblFixedTangibleAssets(Set tblFixedTangibleAssets) {
        this.tblFixedTangibleAssets = tblFixedTangibleAssets;
    }

    @Override
    public String toString() {
        return getTypeName();
    }

}
