package hotelfx.persistence.model;
// Generated Aug 21, 2017 1:49:32 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javafx.beans.property.IntegerProperty;
import javafx.beans.property.SimpleIntegerProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * RefFixedTangibleAssetDepreciationStatus generated by hbm2java
 */
public class RefFixedTangibleAssetDepreciationStatus implements java.io.Serializable {

    private final IntegerProperty idstatus;
    private final StringProperty statusName;
    private final StringProperty statusNote;

    private Set tblFixedTangibleAssets;

    public RefFixedTangibleAssetDepreciationStatus() {
        this.idstatus = new SimpleIntegerProperty();
        this.statusName = new SimpleStringProperty();
        this.statusNote = new SimpleStringProperty();

        this.tblFixedTangibleAssets = new HashSet(0);
    }

    public RefFixedTangibleAssetDepreciationStatus(int idstatus) {
        this();
        idstatusProperty().set(idstatus);
    }

    public RefFixedTangibleAssetDepreciationStatus(int idstatus, String statusName, String statusNote, Set tblFixedTangibleAssets) {
        this();
        idstatusProperty().set(idstatus);
        statusNameProperty().set(statusName);
        statusNoteProperty().set(statusNote);
        this.tblFixedTangibleAssets = tblFixedTangibleAssets;
    }

    public RefFixedTangibleAssetDepreciationStatus(RefFixedTangibleAssetDepreciationStatus refFixedTangibleAssetDepreciationStatus) {
        this();
        idstatusProperty().set(refFixedTangibleAssetDepreciationStatus.getIdstatus());
        statusNameProperty().set(refFixedTangibleAssetDepreciationStatus.getStatusName());
        statusNoteProperty().set(refFixedTangibleAssetDepreciationStatus.getStatusNote());

        this.tblFixedTangibleAssets = refFixedTangibleAssetDepreciationStatus.getTblFixedTangibleAssets();
    }

    public final IntegerProperty idstatusProperty() {
        return this.idstatus;
    }

    public int getIdstatus() {
        return idstatusProperty().get();
    }

    public void setIdstatus(int idstatus) {
        idstatusProperty().set(idstatus);
    }

    public final StringProperty statusNameProperty() {
        return this.statusName;
    }

    public String getStatusName() {
        return statusNameProperty().get();
    }

    public void setStatusName(String statusName) {
        statusNameProperty().set(statusName);
    }

    public final StringProperty statusNoteProperty() {
        return this.statusNote;
    }

    public String getStatusNote() {
        return statusNoteProperty().get();
    }

    public void setStatusNote(String statusNote) {
        statusNoteProperty().set(statusNote);
    }

    public Set getTblFixedTangibleAssets() {
        return this.tblFixedTangibleAssets;
    }

    public void setTblFixedTangibleAssets(Set tblFixedTangibleAssets) {
        this.tblFixedTangibleAssets = tblFixedTangibleAssets;
    }

    @Override
    public String toString() {
        return getStatusName();
    }

}
