package hotelfx.persistence.model;
// Generated Dec 9, 2017 10:48:36 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javafx.beans.property.IntegerProperty;
import javafx.beans.property.SimpleIntegerProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * RefHotelReceivableType generated by hbm2java
 */
public class RefHotelReceivableType implements java.io.Serializable {

    private final IntegerProperty idtype;
    private final StringProperty typeName;
    private final StringProperty typeNote;

    private Set tblHotelReceivables;

    public RefHotelReceivableType() {
        this.idtype = new SimpleIntegerProperty();
        this.typeName = new SimpleStringProperty();
        this.typeNote = new SimpleStringProperty();

        this.tblHotelReceivables = new HashSet(0);
    }

    public RefHotelReceivableType(int idtype) {
        this();
        idtypeProperty().set(idtype);
    }

    public RefHotelReceivableType(int idtype, String typeName, String typeNote, Set tblHotelReceivables) {
        this();
        idtypeProperty().set(idtype);
        typeNameProperty().set(typeName);
        typeNoteProperty().set(typeNote);

        this.tblHotelReceivables = tblHotelReceivables;
    }

    public RefHotelReceivableType(RefHotelReceivableType refHotelReceivableType) {
        this();
        idtypeProperty().set(refHotelReceivableType.getIdtype());
        typeNameProperty().set(refHotelReceivableType.getTypeName());
        typeNoteProperty().set(refHotelReceivableType.getTypeNote());

        this.tblHotelReceivables = refHotelReceivableType.getTblHotelReceivables();
    }

    public final IntegerProperty idtypeProperty() {
        return this.idtype;
    }

    public int getIdtype() {
        return idtypeProperty().get();
    }

    public void setIdtype(int idtype) {
        idtypeProperty().set(idtype);
    }

    public final StringProperty typeNameProperty() {
        return this.typeName;
    }

    public String getTypeName() {
        return typeNameProperty().get();
    }

    public void setTypeName(String typeName) {
        typeNameProperty().set(typeName);
    }

    public final StringProperty typeNoteProperty() {
        return this.typeNote;
    }

    public String getTypeNote() {
        return typeNoteProperty().get();
    }

    public void setTypeNote(String typeNote) {
        typeNoteProperty().set(typeNote);
    }

    public Set getTblHotelReceivables() {
        return this.tblHotelReceivables;
    }

    public void setTblHotelReceivables(Set tblHotelReceivables) {
        this.tblHotelReceivables = tblHotelReceivables;
    }

}
