package hotelfx.persistence.model;
// Generated Apr 6, 2018 2:02:42 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javafx.beans.property.IntegerProperty;
import javafx.beans.property.SimpleIntegerProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * RefHotelInvoiceType generated by hbm2java
 */
public class RefHotelInvoiceType implements java.io.Serializable {

    private final IntegerProperty idtype;
    private final StringProperty typeName;
    private final StringProperty typeNote;

    private Set tblHotelInvoices;

    public RefHotelInvoiceType() {
        this.idtype = new SimpleIntegerProperty();
        this.typeName = new SimpleStringProperty();
        this.typeNote = new SimpleStringProperty();

        this.tblHotelInvoices = new HashSet(0);
    }

    public RefHotelInvoiceType(int idtype) {
        this();
        idtypeProperty().set(idtype);
    }

    public RefHotelInvoiceType(int idtype, String typeName, String typeNote, Set tblHotelInvoices) {
        this();
        idtypeProperty().set(idtype);
        typeNameProperty().set(typeName);
        typeNoteProperty().set(typeNote);

        this.tblHotelInvoices = tblHotelInvoices;
    }

    public RefHotelInvoiceType(RefHotelInvoiceType refHotelInvoiceType) {
        this();
        idtypeProperty().set(refHotelInvoiceType.getIdtype());
        typeNameProperty().set(refHotelInvoiceType.getTypeName());
        typeNoteProperty().set(refHotelInvoiceType.getTypeNote());

        this.tblHotelInvoices = refHotelInvoiceType.getTblHotelInvoices();
    }

    public final IntegerProperty idtypeProperty() {
        return this.idtype;
    }

    public int getIdtype() {
        return idtypeProperty().get();
    }

    public void setIdtype(int idtype) {
        idtypeProperty().set(idtype);
    }

    public final StringProperty typeNameProperty() {
        return this.typeName;
    }

    public String getTypeName() {
        return typeNameProperty().get();
    }

    public void setTypeName(String typeName) {
        typeNameProperty().set(typeName);
    }

    public final StringProperty typeNoteProperty() {
        return this.typeNote;
    }

    public String getTypeNote() {
        return typeNoteProperty().get();
    }

    public void setTypeNote(String typeNote) {
        typeNoteProperty().set(typeNote);
    }

    public Set getTblHotelInvoices() {
        return this.tblHotelInvoices;
    }

    public void setTblHotelInvoices(Set tblHotelInvoices) {
        this.tblHotelInvoices = tblHotelInvoices;
    }

}
