package hotelfx.persistence.model;
// Generated Sep 1, 2018 10:12:55 AM by Hibernate Tools 4.3.1

import javafx.beans.property.IntegerProperty;
import javafx.beans.property.SimpleIntegerProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * RefItemType generated by hbm2java
 */
public class RefItemType implements java.io.Serializable {

    private final IntegerProperty idtype;
    private final StringProperty typeName;
    private final StringProperty typeNote;

    public RefItemType() {
        this.idtype = new SimpleIntegerProperty();
        this.typeName = new SimpleStringProperty();
        this.typeNote = new SimpleStringProperty();

    }

    public RefItemType(int idtype) {
        this();
        idtypeProperty().set(idtype);
    }

    public RefItemType(int idtype, String typeName, String typeNote) {
        this();
        idtypeProperty().set(idtype);
        typeNameProperty().set(typeName);
        typeNoteProperty().set(typeNote);

    }

    public RefItemType(RefItemType refItemType) {
        this();
        idtypeProperty().set(refItemType.getIdtype());
        typeNameProperty().set(refItemType.getTypeName());
        typeNoteProperty().set(refItemType.getTypeNote());

    }

    public final IntegerProperty idtypeProperty() {
        return this.idtype;
    }

    public int getIdtype() {
        return idtypeProperty().get();
    }

    public void setIdtype(int idtype) {
        idtypeProperty().set(idtype);
    }

    public final StringProperty typeNameProperty() {
        return this.typeName;
    }

    public String getTypeName() {
        return typeNameProperty().get();
    }

    public void setTypeName(String typeName) {
        typeNameProperty().set(typeName);
    }

    public final StringProperty typeNoteProperty() {
        return this.typeNote;
    }

    public String getTypeNote() {
        return typeNoteProperty().get();
    }

    public void setTypeNote(String typeNote) {
        typeNoteProperty().set(typeNote);
    }

    @Override
    public String toString() {
        return getTypeName();
    }
    
}
