package hotelfx.persistence.model;
// Generated Sep 25, 2018 10:09:46 AM by Hibernate Tools 4.3.1

import javafx.beans.property.IntegerProperty;
import javafx.beans.property.SimpleIntegerProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * RefItemExpiredDateStatus generated by hbm2java
 */
public class RefItemExpiredDateStatus implements java.io.Serializable {

    private final IntegerProperty idstatus;
    private final StringProperty statusName;
    private final StringProperty statusNote;

    public RefItemExpiredDateStatus() {
        this.idstatus = new SimpleIntegerProperty();
        this.statusName = new SimpleStringProperty();
        this.statusNote = new SimpleStringProperty();

    }

    public RefItemExpiredDateStatus(int idstatus) {
        this();
        idstatusProperty().set(idstatus);
    }

    public RefItemExpiredDateStatus(int idstatus, String statusName, String statusNote) {
        this();
        idstatusProperty().set(idstatus);
        statusNameProperty().set(statusName);
        statusNoteProperty().set(statusNote);

    }

    public RefItemExpiredDateStatus(RefItemExpiredDateStatus refItemExpiredDateStatus) {
        this();
        idstatusProperty().set(refItemExpiredDateStatus.getIdstatus());
        statusNameProperty().set(refItemExpiredDateStatus.getStatusName());
        statusNoteProperty().set(refItemExpiredDateStatus.getStatusNote());

    }

    public final IntegerProperty idstatusProperty() {
        return this.idstatus;
    }

    public int getIdstatus() {
        return idstatusProperty().get();
    }

    public void setIdstatus(int idstatus) {
        idstatusProperty().set(idstatus);
    }

    public final StringProperty statusNameProperty() {
        return this.statusName;
    }

    public String getStatusName() {
        return statusNameProperty().get();
    }

    public void setStatusName(String statusName) {
        statusNameProperty().set(statusName);
    }

    public final StringProperty statusNoteProperty() {
        return this.statusNote;
    }

    public String getStatusNote() {
        return statusNoteProperty().get();
    }

    public void setStatusNote(String statusNote) {
        statusNoteProperty().set(statusNote);
    }

}
