package hotelfx.persistence.model;
// Generated Aug 31, 2018 4:10:03 PM by Hibernate Tools 4.3.1

import javafx.beans.property.IntegerProperty;
import javafx.beans.property.SimpleIntegerProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * RefItemGuestType generated by hbm2java
 */
public class RefItemGuestType implements java.io.Serializable {

    private final IntegerProperty idtype;
    private final StringProperty typeName;
    private final StringProperty typeNote;

    public RefItemGuestType() {
        this.idtype = new SimpleIntegerProperty();
        this.typeName = new SimpleStringProperty();
        this.typeNote = new SimpleStringProperty();

    }

    public RefItemGuestType(int idtype) {
        this();
        idtypeProperty().set(idtype);
    }

    public RefItemGuestType(int idtype, String typeName, String typeNote) {
        this();
        idtypeProperty().set(idtype);
        typeNameProperty().set(typeName);
        typeNoteProperty().set(typeNote);

    }

    public RefItemGuestType(RefItemGuestType refItemGuestType) {
        this();
        idtypeProperty().set(refItemGuestType.getIdtype());
        typeNameProperty().set(refItemGuestType.getTypeName());
        typeNoteProperty().set(refItemGuestType.getTypeNote());

    }

    public final IntegerProperty idtypeProperty() {
        return this.idtype;
    }

    public int getIdtype() {
        return idtypeProperty().get();
    }

    public void setIdtype(int idtype) {
        idtypeProperty().set(idtype);
    }

    public final StringProperty typeNameProperty() {
        return this.typeName;
    }

    public String getTypeName() {
        return typeNameProperty().get();
    }

    public void setTypeName(String typeName) {
        typeNameProperty().set(typeName);
    }

    public final StringProperty typeNoteProperty() {
        return this.typeNote;
    }

    public String getTypeNote() {
        return typeNoteProperty().get();
    }

    public void setTypeNote(String typeNote) {
        typeNoteProperty().set(typeNote);
    }

    @Override
    public String toString() {
        return getTypeName();
    }

}
