package hotelfx.persistence.model;
// Generated Aug 21, 2017 1:49:32 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javafx.beans.property.IntegerProperty;
import javafx.beans.property.SimpleIntegerProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * RefItemObsoleteBy generated by hbm2java
 */
public class RefItemObsoleteBy implements java.io.Serializable {

    private final IntegerProperty idobsoleteBy;
    private final StringProperty obsoleteByName;
    private final StringProperty obsoleteByNote;

    private Set tblItemMutationHistories;

    public RefItemObsoleteBy() {
        this.idobsoleteBy = new SimpleIntegerProperty();
        this.obsoleteByName = new SimpleStringProperty();
        this.obsoleteByNote = new SimpleStringProperty();

        this.tblItemMutationHistories = new HashSet(0);
    }

    public RefItemObsoleteBy(int idobsoleteBy) {
        this();
        idobsoleteByProperty().set(idobsoleteBy);
    }

    public RefItemObsoleteBy(int idobsoleteBy, String obsoleteByName, String obsoleteByNote, Set tblItemMutationHistories) {
        this();
        idobsoleteByProperty().set(idobsoleteBy);
        obsoleteByNameProperty().set(obsoleteByName);
        obsoleteByNoteProperty().set(obsoleteByNote);

        this.tblItemMutationHistories = tblItemMutationHistories;
    }

    public RefItemObsoleteBy(RefItemObsoleteBy refItemObsoleteBy) {
        this();
        idobsoleteByProperty().set(refItemObsoleteBy.getIdobsoleteBy());
        obsoleteByNameProperty().set(refItemObsoleteBy.getObsoleteByName());
        obsoleteByNoteProperty().set(refItemObsoleteBy.getObsoleteByNote());

        this.tblItemMutationHistories = refItemObsoleteBy.getTblItemMutationHistories();
    }

    public final IntegerProperty idobsoleteByProperty() {
        return this.idobsoleteBy;
    }

    public int getIdobsoleteBy() {
        return idobsoleteByProperty().get();
    }

    public void setIdobsoleteBy(int idobsoleteBy) {
        idobsoleteByProperty().set(idobsoleteBy);
    }

    public final StringProperty obsoleteByNameProperty() {
        return this.obsoleteByName;
    }

    public String getObsoleteByName() {
        return obsoleteByNameProperty().get();
    }

    public void setObsoleteByName(String obsoleteByName) {
        obsoleteByNameProperty().set(obsoleteByName);
    }

    public final StringProperty obsoleteByNoteProperty() {
        return this.obsoleteByNote;
    }

    public String getObsoleteByNote() {
        return obsoleteByNoteProperty().get();
    }

    public void setObsoleteByNote(String obsoleteByNote) {
        obsoleteByNoteProperty().set(obsoleteByNote);
    }

    public Set getTblItemMutationHistories() {
        return this.tblItemMutationHistories;
    }

    public void setTblItemMutationHistories(Set tblItemMutationHistories) {
        this.tblItemMutationHistories = tblItemMutationHistories;
    }

    @Override
    public String toString() {
        return getObsoleteByName();
    }

}
