package hotelfx.persistence.model;
// Generated Mar 29, 2018 3:28:56 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javafx.beans.property.IntegerProperty;
import javafx.beans.property.SimpleIntegerProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * RefLostFoundStatus generated by hbm2java
 */
public class RefLostFoundStatus implements java.io.Serializable {

    private final IntegerProperty idstatus;
    private final StringProperty statusName;
    private final StringProperty statusNote;

    private Set tblFoundInformations;
    private Set tblLostInformations;

    public RefLostFoundStatus() {
        this.idstatus = new SimpleIntegerProperty();
        this.statusName = new SimpleStringProperty();
        this.statusNote = new SimpleStringProperty();

        this.tblFoundInformations = new HashSet(0);
        this.tblLostInformations = new HashSet(0);
    }

    public RefLostFoundStatus(int idstatus) {
        this();
        idstatusProperty().set(idstatus);
    }

    public RefLostFoundStatus(int idstatus, String statusName, String statusNote, Set tblFoundInformations, Set tblLostInformations) {
        this();
        idstatusProperty().set(idstatus);
        statusNameProperty().set(statusName);
        statusNoteProperty().set(statusNote);

        this.tblFoundInformations = tblFoundInformations;
        this.tblLostInformations = tblLostInformations;
    }

    public RefLostFoundStatus(RefLostFoundStatus refLostFoundStatus) {
        this();
        idstatusProperty().set(refLostFoundStatus.getIdstatus());
        statusNameProperty().set(refLostFoundStatus.getStatusName());
        statusNoteProperty().set(refLostFoundStatus.getStatusNote());

        this.tblFoundInformations = refLostFoundStatus.getTblFoundInformations();
        this.tblLostInformations = refLostFoundStatus.getTblLostInformations();
    }

    public final IntegerProperty idstatusProperty() {
        return this.idstatus;
    }

    public int getIdstatus() {
        return idstatusProperty().get();
    }

    public void setIdstatus(int idstatus) {
        idstatusProperty().set(idstatus);
    }

    public final StringProperty statusNameProperty() {
        return this.statusName;
    }

    public String getStatusName() {
        return statusNameProperty().get();
    }

    public void setStatusName(String statusName) {
        statusNameProperty().set(statusName);
    }

    public final StringProperty statusNoteProperty() {
        return this.statusNote;
    }

    public String getStatusNote() {
        return statusNoteProperty().get();
    }

    public void setStatusNote(String statusNote) {
        statusNoteProperty().set(statusNote);
    }

    public Set getTblFoundInformations() {
        return this.tblFoundInformations;
    }

    public void setTblFoundInformations(Set tblFoundInformations) {
        this.tblFoundInformations = tblFoundInformations;
    }

    public Set getTblLostInformations() {
        return this.tblLostInformations;
    }

    public void setTblLostInformations(Set tblLostInformations) {
        this.tblLostInformations = tblLostInformations;
    }

}
