package hotelfx.persistence.model;
// Generated Aug 21, 2017 1:49:32 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javafx.beans.property.IntegerProperty;
import javafx.beans.property.SimpleIntegerProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * RefLocationType generated by hbm2java
 */
public class RefLocationType implements java.io.Serializable {

    private final IntegerProperty idtype;
    private final StringProperty typeName;
    private final StringProperty typeNote;

    private Set tblLocations;

    public RefLocationType() {
        this.idtype = new SimpleIntegerProperty();
        this.typeName = new SimpleStringProperty();
        this.typeNote = new SimpleStringProperty();

        this.tblLocations = new HashSet(0);
    }

    public RefLocationType(int idtype) {
        this();
        idtypeProperty().set(idtype);
    }

    public RefLocationType(int idtype, String typeName, String typeNote, Set tblLocations) {
        this();
        idtypeProperty().set(idtype);
        typeNameProperty().set(typeName);
        typeNoteProperty().set(typeNote);
        this.tblLocations = tblLocations;
    }

    public RefLocationType(RefLocationType refLocationType) {
        this();
        idtypeProperty().set(refLocationType.getIdtype());
        typeNameProperty().set(refLocationType.getTypeName());
        typeNoteProperty().set(refLocationType.getTypeNote());

        this.tblLocations = refLocationType.getTblLocations();
    }

    public final IntegerProperty idtypeProperty() {
        return this.idtype;
    }

    public int getIdtype() {
        return idtypeProperty().get();
    }

    public void setIdtype(int idtype) {
        idtypeProperty().set(idtype);
    }

    public final StringProperty typeNameProperty() {
        return this.typeName;
    }

    public String getTypeName() {
        return typeNameProperty().get();
    }

    public void setTypeName(String typeName) {
        typeNameProperty().set(typeName);
    }

    public final StringProperty typeNoteProperty() {
        return this.typeNote;
    }

    public String getTypeNote() {
        return typeNoteProperty().get();
    }

    public void setTypeNote(String typeNote) {
        typeNoteProperty().set(typeNote);
    }

    public Set getTblLocations() {
        return this.tblLocations;
    }

    public void setTblLocations(Set tblLocations) {
        this.tblLocations = tblLocations;
    }

    @Override
    public String toString() {
        return typeName.get();
    }

}
