package hotelfx.persistence.model;
// Generated Mar 20, 2018 9:55:15 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javafx.beans.property.IntegerProperty;
import javafx.beans.property.SimpleIntegerProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * RefOpenCloseCashierBalanceStatus generated by hbm2java
 */
public class RefOpenCloseCashierBalanceStatus implements java.io.Serializable {

    private final IntegerProperty idstatus;
    private final StringProperty statusName;
    private final StringProperty statusNote;

    private Set tblOpenCloseCashierBalances;

    public RefOpenCloseCashierBalanceStatus() {
        this.idstatus = new SimpleIntegerProperty();
        this.statusName = new SimpleStringProperty();
        this.statusNote = new SimpleStringProperty();

        this.tblOpenCloseCashierBalances = new HashSet(0);
    }

    public RefOpenCloseCashierBalanceStatus(int idstatus) {
        this();
        idstatusProperty().set(idstatus);
    }

    public RefOpenCloseCashierBalanceStatus(int idstatus, String statusName, String statusNote, Set tblOpenCloseCashierBalances) {
        this();
        idstatusProperty().set(idstatus);
        statusNameProperty().set(statusName);
        statusNoteProperty().set(statusNote);

        this.tblOpenCloseCashierBalances = tblOpenCloseCashierBalances;
    }

    public RefOpenCloseCashierBalanceStatus(RefOpenCloseCashierBalanceStatus refOpenCloseCashierBalanceStatus) {
        this();
        idstatusProperty().set(refOpenCloseCashierBalanceStatus.getIdstatus());
        statusNameProperty().set(refOpenCloseCashierBalanceStatus.getStatusName());
        statusNoteProperty().set(refOpenCloseCashierBalanceStatus.getStatusNote());

        this.tblOpenCloseCashierBalances = refOpenCloseCashierBalanceStatus.getTblOpenCloseCashierBalances();
    }

    public final IntegerProperty idstatusProperty() {
        return this.idstatus;
    }

    public int getIdstatus() {
        return idstatusProperty().get();
    }

    public void setIdstatus(int idstatus) {
        idstatusProperty().set(idstatus);
    }

    public final StringProperty statusNameProperty() {
        return this.statusName;
    }

    public String getStatusName() {
        return statusNameProperty().get();
    }

    public void setStatusName(String statusName) {
        statusNameProperty().set(statusName);
    }

    public final StringProperty statusNoteProperty() {
        return this.statusNote;
    }

    public String getStatusNote() {
        return statusNoteProperty().get();
    }

    public void setStatusNote(String statusNote) {
        statusNoteProperty().set(statusNote);
    }

    public Set getTblOpenCloseCashierBalances() {
        return this.tblOpenCloseCashierBalances;
    }

    public void setTblOpenCloseCashierBalances(Set tblOpenCloseCashierBalances) {
        this.tblOpenCloseCashierBalances = tblOpenCloseCashierBalances;
    }

}
