package hotelfx.persistence.model;
// Generated Aug 21, 2017 1:49:32 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javafx.beans.property.IntegerProperty;
import javafx.beans.property.SimpleIntegerProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * RefPeopleStatus generated by hbm2java
 */
public class RefPeopleStatus implements java.io.Serializable {

    private final IntegerProperty idstatus;
    private final StringProperty statusName;
    private final StringProperty statusNote;

    private Set tblPeoples;

    public RefPeopleStatus() {
        this.idstatus = new SimpleIntegerProperty();
        this.statusName = new SimpleStringProperty();
        this.statusNote = new SimpleStringProperty();

        this.tblPeoples = new HashSet(0);
    }

    public RefPeopleStatus(int idstatus) {
        this();
        idstatusProperty().set(idstatus);
    }

    public RefPeopleStatus(int idstatus, String statusName, String statusNote, Set tblPeoples) {
        this();
        idstatusProperty().set(idstatus);
        statusNameProperty().set(statusName);
        statusNoteProperty().set(statusNote);

        this.tblPeoples = tblPeoples;
    }

    public RefPeopleStatus(RefPeopleStatus refPeopleStatus) {
        this();
        idstatusProperty().set(refPeopleStatus.getIdstatus());
        statusNameProperty().set(refPeopleStatus.getStatusName());
        statusNoteProperty().set(refPeopleStatus.getStatusNote());

        this.tblPeoples = refPeopleStatus.getTblPeoples();
    }

    public final IntegerProperty idstatusProperty() {
        return this.idstatus;
    }

    public int getIdstatus() {
        return idstatusProperty().get();
    }

    public void setIdstatus(int idstatus) {
        idstatusProperty().set(idstatus);
    }

    public final StringProperty statusNameProperty() {
        return this.statusName;
    }

    public String getStatusName() {
        return statusNameProperty().get();
    }

    public void setStatusName(String statusName) {
        statusNameProperty().set(statusName);
    }

    public final StringProperty statusNoteProperty() {
        return this.statusNote;
    }

    public String getStatusNote() {
        return statusNoteProperty().get();
    }

    public void setStatusNote(String statusNote) {
        statusNoteProperty().set(statusNote);
    }

    public Set getTblPeoples() {
        return this.tblPeoples;
    }

    public void setTblPeoples(Set tblPeoples) {
        this.tblPeoples = tblPeoples;
    }

    @Override
    public String toString() {
        return getStatusName();
    }

}
