package hotelfx.persistence.model;
// Generated Oct 31, 2017 1:41:16 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javafx.beans.property.IntegerProperty;
import javafx.beans.property.SimpleIntegerProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * RefPurchaseOrderPaymentStatus generated by hbm2java
 */
public class RefPurchaseOrderPaymentStatus implements java.io.Serializable {

    private final IntegerProperty idstatus;
    private final StringProperty statusName;
    private final StringProperty statusNote;

    private Set tblPurchaseOrders;

    public RefPurchaseOrderPaymentStatus() {
        this.idstatus = new SimpleIntegerProperty();
        this.statusName = new SimpleStringProperty();
        this.statusNote = new SimpleStringProperty();

        this.tblPurchaseOrders = new HashSet(0);
    }

    public RefPurchaseOrderPaymentStatus(int idstatus) {
        this();
        idstatusProperty().set(idstatus);
    }

    public RefPurchaseOrderPaymentStatus(int idstatus, String statusName, String statusNote, Set tblPurchaseOrders) {
        this();
        idstatusProperty().set(idstatus);
        statusNameProperty().set(statusName);
        statusNoteProperty().set(statusNote);

        this.tblPurchaseOrders = tblPurchaseOrders;
    }

    public RefPurchaseOrderPaymentStatus(RefPurchaseOrderPaymentStatus refPurchaseOrderPaymentStatus) {
        this();
        idstatusProperty().set(refPurchaseOrderPaymentStatus.getIdstatus());
        statusNameProperty().set(refPurchaseOrderPaymentStatus.getStatusName());
        statusNoteProperty().set(refPurchaseOrderPaymentStatus.getStatusNote());

        this.tblPurchaseOrders = refPurchaseOrderPaymentStatus.getTblPurchaseOrders();
    }

    public final IntegerProperty idstatusProperty() {
        return this.idstatus;
    }

    public int getIdstatus() {
        return idstatusProperty().get();
    }

    public void setIdstatus(int idstatus) {
        idstatusProperty().set(idstatus);
    }

    public final StringProperty statusNameProperty() {
        return this.statusName;
    }

    public String getStatusName() {
        return statusNameProperty().get();
    }

    public void setStatusName(String statusName) {
        statusNameProperty().set(statusName);
    }

    public final StringProperty statusNoteProperty() {
        return this.statusNote;
    }

    public String getStatusNote() {
        return statusNoteProperty().get();
    }

    public void setStatusNote(String statusNote) {
        statusNoteProperty().set(statusNote);
    }

    public Set getTblPurchaseOrders() {
        return this.tblPurchaseOrders;
    }

    public void setTblPurchaseOrders(Set tblPurchaseOrders) {
        this.tblPurchaseOrders = tblPurchaseOrders;
    }

}
