package hotelfx.persistence.model;
// Generated Aug 21, 2017 1:49:32 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javafx.beans.property.IntegerProperty;
import javafx.beans.property.SimpleIntegerProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * RefPartnerAgreementStatus generated by hbm2java
 */
public class RefPartnerAgreementStatus implements java.io.Serializable {

    private final IntegerProperty idstatus;
    private final StringProperty statusName;
    private final StringProperty statusNote;

    private Set tblPartnerAgreements;

    public RefPartnerAgreementStatus() {
        this.idstatus = new SimpleIntegerProperty();
        this.statusName = new SimpleStringProperty();
        this.statusNote = new SimpleStringProperty();

        this.tblPartnerAgreements = new HashSet(0);
    }

    public RefPartnerAgreementStatus(int idstatus) {
        this();
        idstatusProperty().set(idstatus);
    }

    public RefPartnerAgreementStatus(int idstatus, String statusName, String statusNote, Set tblPartnerAgreements) {
        this();
        idstatusProperty().set(idstatus);
        statusNameProperty().set(statusName);
        statusNoteProperty().set(statusNote);
        this.tblPartnerAgreements = tblPartnerAgreements;
    }

    public RefPartnerAgreementStatus(RefPartnerAgreementStatus refPartnerAgreementStatus) {
        this();
        idstatusProperty().set(refPartnerAgreementStatus.getIdstatus());
        statusNameProperty().set(refPartnerAgreementStatus.getStatusName());
        statusNoteProperty().set(refPartnerAgreementStatus.getStatusNote());

        this.tblPartnerAgreements = refPartnerAgreementStatus.getTblPartnerAgreements();
    }

    public final IntegerProperty idstatusProperty() {
        return this.idstatus;
    }

    public int getIdstatus() {
        return idstatusProperty().get();
    }

    public void setIdstatus(int idstatus) {
        idstatusProperty().set(idstatus);
    }

    public final StringProperty statusNameProperty() {
        return this.statusName;
    }

    public String getStatusName() {
        return statusNameProperty().get();
    }

    public void setStatusName(String statusName) {
        statusNameProperty().set(statusName);
    }

    public final StringProperty statusNoteProperty() {
        return this.statusNote;
    }

    public String getStatusNote() {
        return statusNoteProperty().get();
    }

    public void setStatusNote(String statusNote) {
        statusNoteProperty().set(statusNote);
    }

    public Set getTblPartnerAgreements() {
        return this.tblPartnerAgreements;
    }

    public void setTblPartnerAgreements(Set tblPartnerAgreements) {
        this.tblPartnerAgreements = tblPartnerAgreements;
    }

}
