package hotelfx.persistence.model;
// Generated Aug 21, 2017 1:49:32 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javafx.beans.property.IntegerProperty;
import javafx.beans.property.SimpleIntegerProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * RefPeopleGender generated by hbm2java
 */
public class RefPeopleGender implements java.io.Serializable {

    private final IntegerProperty idgender;
    private final StringProperty genderName;
    private final StringProperty genderNote;

    private Set tblPeoples;

    public RefPeopleGender() {
        this.idgender = new SimpleIntegerProperty();
        this.genderName = new SimpleStringProperty();
        this.genderNote = new SimpleStringProperty();

        this.tblPeoples = new HashSet(0);
    }

    public RefPeopleGender(int idgender) {
        this();
        idgenderProperty().set(idgender);
    }

    public RefPeopleGender(int idgender, String genderName, String genderNote, Set tblPeoples) {
        this();
        idgenderProperty().set(idgender);
        genderNameProperty().set(genderName);
        genderNoteProperty().set(genderNote);

        this.tblPeoples = tblPeoples;
    }

    public RefPeopleGender(RefPeopleGender refPeopleGender) {
        this();
        idgenderProperty().set(refPeopleGender.getIdgender());
        genderNameProperty().set(refPeopleGender.getGenderName());
        genderNoteProperty().set(refPeopleGender.getGenderNote());

        this.tblPeoples = refPeopleGender.getTblPeoples();
    }

    public final IntegerProperty idgenderProperty() {
        return this.idgender;
    }

    public int getIdgender() {
        return idgenderProperty().get();
    }

    public void setIdgender(int idgender) {
        idgenderProperty().set(idgender);
    }

    public final StringProperty genderNameProperty() {
        return this.genderName;
    }

    public String getGenderName() {
        return genderNameProperty().get();
    }

    public void setGenderName(String genderName) {
        genderNameProperty().set(genderName);
    }

    public final StringProperty genderNoteProperty() {
        return this.genderNote;
    }

    public String getGenderNote() {
        return genderNoteProperty().get();
    }

    public void setGenderNote(String genderNote) {
        genderNoteProperty().set(genderNote);
    }

    public Set getTblPeoples() {
        return this.tblPeoples;
    }

    public void setTblPeoples(Set tblPeoples) {
        this.tblPeoples = tblPeoples;
    }

    @Override
    public String toString() {
        return getGenderName();
    }

}
