package hotelfx.persistence.model;
// Generated Aug 21, 2017 1:49:32 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javafx.beans.property.IntegerProperty;
import javafx.beans.property.SimpleIntegerProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * RefPeopleReligion generated by hbm2java
 */
public class RefPeopleReligion implements java.io.Serializable {

    private final IntegerProperty idreligion;
    private final StringProperty religionName;
    private final StringProperty religionNote;

    private Set tblPeoples;

    public RefPeopleReligion() {
        this.idreligion = new SimpleIntegerProperty();
        this.religionName = new SimpleStringProperty();
        this.religionNote = new SimpleStringProperty();

        this.tblPeoples = new HashSet(0);
    }

    public RefPeopleReligion(int idreligion) {
        this();
        idreligionProperty().set(idreligion);
    }

    public RefPeopleReligion(int idreligion, String religionName, String religionNote, Set tblPeoples) {
        this();
        idreligionProperty().set(idreligion);
        religionNameProperty().set(religionName);
        religionNoteProperty().set(religionNote);

        this.tblPeoples = tblPeoples;
    }

    public RefPeopleReligion(RefPeopleReligion refPeopleReligion) {
        this();
        idreligionProperty().set(refPeopleReligion.getIdreligion());
        religionNameProperty().set(refPeopleReligion.getReligionName());
        religionNoteProperty().set(refPeopleReligion.getReligionNote());

        this.tblPeoples = refPeopleReligion.getTblPeoples();
    }

    public final IntegerProperty idreligionProperty() {
        return this.idreligion;
    }

    public int getIdreligion() {
        return idreligionProperty().get();
    }

    public void setIdreligion(int idreligion) {
        idreligionProperty().set(idreligion);
    }

    public final StringProperty religionNameProperty() {
        return this.religionName;
    }

    public String getReligionName() {
        return religionNameProperty().get();
    }

    public void setReligionName(String religionName) {
        religionNameProperty().set(religionName);
    }

    public final StringProperty religionNoteProperty() {
        return this.religionNote;
    }

    public String getReligionNote() {
        return religionNoteProperty().get();
    }

    public void setReligionNote(String religionNote) {
        religionNoteProperty().set(religionNote);
    }

    public Set getTblPeoples() {
        return this.tblPeoples;
    }

    public void setTblPeoples(Set tblPeoples) {
        this.tblPeoples = tblPeoples;
    }

    @Override
    public String toString() {
        return getReligionName();
    }

}
