package hotelfx.persistence.model;
// Generated Feb 7, 2018 2:38:05 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javafx.beans.property.IntegerProperty;
import javafx.beans.property.SimpleIntegerProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * RefPeopleIdentifierType generated by hbm2java
 */
public class RefPeopleIdentifierType implements java.io.Serializable {

    private final IntegerProperty idtype;
    private final StringProperty typeName;
    private final StringProperty typeNote;

    private Set tblPeoples;

    public RefPeopleIdentifierType() {
        this.idtype = new SimpleIntegerProperty();
        this.typeName = new SimpleStringProperty();
        this.typeNote = new SimpleStringProperty();

        this.tblPeoples = new HashSet(0);
    }

    public RefPeopleIdentifierType(int idtype) {
        this();
        idtypeProperty().set(idtype);
    }

    public RefPeopleIdentifierType(int idtype, String typeName, String typeNote, Set tblPeoples) {
        this();
        idtypeProperty().set(idtype);
        typeNameProperty().set(typeName);
        typeNoteProperty().set(typeNote);

        this.tblPeoples = tblPeoples;
    }

    public RefPeopleIdentifierType(RefPeopleIdentifierType refPeopleIdentifierType) {
        this();
        idtypeProperty().set(refPeopleIdentifierType.getIdtype());
        typeNameProperty().set(refPeopleIdentifierType.getTypeName());
        typeNoteProperty().set(refPeopleIdentifierType.getTypeNote());

        this.tblPeoples = refPeopleIdentifierType.getTblPeoples();
    }

    public final IntegerProperty idtypeProperty() {
        return this.idtype;
    }

    public int getIdtype() {
        return idtypeProperty().get();
    }

    public void setIdtype(int idtype) {
        idtypeProperty().set(idtype);
    }

    public final StringProperty typeNameProperty() {
        return this.typeName;
    }

    public String getTypeName() {
        return typeNameProperty().get();
    }

    public void setTypeName(String typeName) {
        typeNameProperty().set(typeName);
    }

    public final StringProperty typeNoteProperty() {
        return this.typeNote;
    }

    public String getTypeNote() {
        return typeNoteProperty().get();
    }

    public void setTypeNote(String typeNote) {
        typeNoteProperty().set(typeNote);
    }

    public Set getTblPeoples() {
        return this.tblPeoples;
    }

    public void setTblPeoples(Set tblPeoples) {
        this.tblPeoples = tblPeoples;
    }

    @Override
    public String toString(){
        return getTypeName();
    }
    
}
