package hotelfx.persistence.model;
// Generated Oct 3, 2018 4:36:44 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javafx.beans.property.IntegerProperty;
import javafx.beans.property.SimpleIntegerProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * RefRoomStatus generated by hbm2java
 */
public class RefRoomStatus implements java.io.Serializable {

    private final IntegerProperty idstatus;
    private final StringProperty statusName;
    private final StringProperty statusNote;

    private Set tblRoomStatusChangeHistoriesForRoomStatusOld;
    private Set tblRooms;
    private Set tblRoomCheckHouseKeepingAttendancesForRoomStatusBefore;
    private Set tblRoomCheckHouseKeepingAttendancesForRoomStatusAfter;
    private Set tblRoomStatusChangeHistoriesForRoomStatusNew;

    public RefRoomStatus() {
        this.idstatus = new SimpleIntegerProperty();
        this.statusName = new SimpleStringProperty();
        this.statusNote = new SimpleStringProperty();

        this.tblRoomStatusChangeHistoriesForRoomStatusOld = new HashSet(0);
        this.tblRooms = new HashSet(0);
        this.tblRoomCheckHouseKeepingAttendancesForRoomStatusBefore = new HashSet(0);
        this.tblRoomCheckHouseKeepingAttendancesForRoomStatusAfter = new HashSet(0);
        this.tblRoomStatusChangeHistoriesForRoomStatusNew = new HashSet(0);
    }

    public RefRoomStatus(int idstatus) {
        this();
        idstatusProperty().set(idstatus);
    }

    public RefRoomStatus(int idstatus, String statusName, String statusNote, Set tblRoomStatusChangeHistoriesForRoomStatusOld, Set tblRooms, Set tblRoomCheckHouseKeepingAttendancesForRoomStatusBefore, Set tblRoomCheckHouseKeepingAttendancesForRoomStatusAfter, Set tblRoomStatusChangeHistoriesForRoomStatusNew) {
        this();
        idstatusProperty().set(idstatus);
        statusNameProperty().set(statusName);
        statusNoteProperty().set(statusNote);

        this.tblRoomStatusChangeHistoriesForRoomStatusOld = tblRoomStatusChangeHistoriesForRoomStatusOld;
        this.tblRooms = tblRooms;
        this.tblRoomCheckHouseKeepingAttendancesForRoomStatusBefore = tblRoomCheckHouseKeepingAttendancesForRoomStatusBefore;
        this.tblRoomCheckHouseKeepingAttendancesForRoomStatusAfter = tblRoomCheckHouseKeepingAttendancesForRoomStatusAfter;
        this.tblRoomStatusChangeHistoriesForRoomStatusNew = tblRoomStatusChangeHistoriesForRoomStatusNew;
    }

    public RefRoomStatus(RefRoomStatus refRoomStatus) {
        this();
        idstatusProperty().set(refRoomStatus.getIdstatus());
        statusNameProperty().set(refRoomStatus.getStatusName());
        statusNoteProperty().set(refRoomStatus.getStatusNote());

        this.tblRoomStatusChangeHistoriesForRoomStatusOld = refRoomStatus.getTblRoomStatusChangeHistoriesForRoomStatusOld();
        this.tblRooms = refRoomStatus.getTblRooms();
        this.tblRoomCheckHouseKeepingAttendancesForRoomStatusBefore = refRoomStatus.getTblRoomCheckHouseKeepingAttendancesForRoomStatusBefore();
        this.tblRoomCheckHouseKeepingAttendancesForRoomStatusAfter = refRoomStatus.getTblRoomCheckHouseKeepingAttendancesForRoomStatusAfter();
        this.tblRoomStatusChangeHistoriesForRoomStatusNew = refRoomStatus.getTblRoomStatusChangeHistoriesForRoomStatusNew();
    }

    public final IntegerProperty idstatusProperty() {
        return this.idstatus;
    }

    public int getIdstatus() {
        return idstatusProperty().get();
    }

    public void setIdstatus(int idstatus) {
        idstatusProperty().set(idstatus);
    }

    public final StringProperty statusNameProperty() {
        return this.statusName;
    }

    public String getStatusName() {
        return statusNameProperty().get();
    }

    public void setStatusName(String statusName) {
        statusNameProperty().set(statusName);
    }

    public final StringProperty statusNoteProperty() {
        return this.statusNote;
    }

    public String getStatusNote() {
        return statusNoteProperty().get();
    }

    public void setStatusNote(String statusNote) {
        statusNoteProperty().set(statusNote);
    }

    public Set getTblRoomStatusChangeHistoriesForRoomStatusOld() {
        return this.tblRoomStatusChangeHistoriesForRoomStatusOld;
    }

    public void setTblRoomStatusChangeHistoriesForRoomStatusOld(Set tblRoomStatusChangeHistoriesForRoomStatusOld) {
        this.tblRoomStatusChangeHistoriesForRoomStatusOld = tblRoomStatusChangeHistoriesForRoomStatusOld;
    }

    public Set getTblRooms() {
        return this.tblRooms;
    }

    public void setTblRooms(Set tblRooms) {
        this.tblRooms = tblRooms;
    }

    public Set getTblRoomCheckHouseKeepingAttendancesForRoomStatusBefore() {
        return this.tblRoomCheckHouseKeepingAttendancesForRoomStatusBefore;
    }

    public void setTblRoomCheckHouseKeepingAttendancesForRoomStatusBefore(Set tblRoomCheckHouseKeepingAttendancesForRoomStatusBefore) {
        this.tblRoomCheckHouseKeepingAttendancesForRoomStatusBefore = tblRoomCheckHouseKeepingAttendancesForRoomStatusBefore;
    }

    public Set getTblRoomCheckHouseKeepingAttendancesForRoomStatusAfter() {
        return this.tblRoomCheckHouseKeepingAttendancesForRoomStatusAfter;
    }

    public void setTblRoomCheckHouseKeepingAttendancesForRoomStatusAfter(Set tblRoomCheckHouseKeepingAttendancesForRoomStatusAfter) {
        this.tblRoomCheckHouseKeepingAttendancesForRoomStatusAfter = tblRoomCheckHouseKeepingAttendancesForRoomStatusAfter;
    }

    public Set getTblRoomStatusChangeHistoriesForRoomStatusNew() {
        return this.tblRoomStatusChangeHistoriesForRoomStatusNew;
    }

    public void setTblRoomStatusChangeHistoriesForRoomStatusNew(Set tblRoomStatusChangeHistoriesForRoomStatusNew) {
        this.tblRoomStatusChangeHistoriesForRoomStatusNew = tblRoomStatusChangeHistoriesForRoomStatusNew;
    }

    @Override
    public String toString() {
        return statusNameProperty().get();
    }
    
}
