package hotelfx.persistence.model;
// Generated Dec 19, 2017 1:31:36 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javafx.beans.property.IntegerProperty;
import javafx.beans.property.SimpleIntegerProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * RefReturType generated by hbm2java
 */
public class RefReturType implements java.io.Serializable {

    private final IntegerProperty idtype;
    private final StringProperty typeName;
    private final StringProperty typeNote;

    private Set tblReturs;

    public RefReturType() {
        this.idtype = new SimpleIntegerProperty();
        this.typeName = new SimpleStringProperty();
        this.typeNote = new SimpleStringProperty();

        this.tblReturs = new HashSet(0);
    }

    public RefReturType(int idtype) {
        this();
        idtypeProperty().set(idtype);
    }

    public RefReturType(int idtype, String typeName, String typeNote, Set tblReturs) {
        this();
        idtypeProperty().set(idtype);
        typeNameProperty().set(typeName);
        typeNoteProperty().set(typeNote);

        this.tblReturs = tblReturs;
    }

    public RefReturType(RefReturType refReturType) {
        this();
        idtypeProperty().set(refReturType.getIdtype());
        typeNameProperty().set(refReturType.getTypeName());
        typeNoteProperty().set(refReturType.getTypeNote());

        this.tblReturs = refReturType.getTblReturs();
    }

    public final IntegerProperty idtypeProperty() {
        return this.idtype;
    }

    public int getIdtype() {
        return idtypeProperty().get();
    }

    public void setIdtype(int idtype) {
        idtypeProperty().set(idtype);
    }

    public final StringProperty typeNameProperty() {
        return this.typeName;
    }

    public String getTypeName() {
        return typeNameProperty().get();
    }

    public void setTypeName(String typeName) {
        typeNameProperty().set(typeName);
    }

    public final StringProperty typeNoteProperty() {
        return this.typeNote;
    }

    public String getTypeNote() {
        return typeNoteProperty().get();
    }

    public void setTypeNote(String typeNote) {
        typeNoteProperty().set(typeNote);
    }

    public Set getTblReturs() {
        return this.tblReturs;
    }

    public void setTblReturs(Set tblReturs) {
        this.tblReturs = tblReturs;
    }

}
