package hotelfx.persistence.model;
// Generated Nov 3, 2017 2:12:52 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javafx.beans.property.IntegerProperty;
import javafx.beans.property.SimpleIntegerProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * RefReturPaymentStatus generated by hbm2java
 */
public class RefReturPaymentStatus implements java.io.Serializable {

    private final IntegerProperty idstatus;
    private final StringProperty statusName;
    private final StringProperty statusNote;

    private Set tblReturs;

    public RefReturPaymentStatus() {
        this.idstatus = new SimpleIntegerProperty();
        this.statusName = new SimpleStringProperty();
        this.statusNote = new SimpleStringProperty();

        this.tblReturs = new HashSet(0);
    }

    public RefReturPaymentStatus(int idstatus) {
        this();
        idstatusProperty().set(idstatus);
    }

    public RefReturPaymentStatus(int idstatus, String statusName, String statusNote, Set tblReturs) {
        this();
        idstatusProperty().set(idstatus);
        statusNameProperty().set(statusName);
        statusNoteProperty().set(statusNote);

        this.tblReturs = tblReturs;
    }

    public RefReturPaymentStatus(RefReturPaymentStatus refReturPaymentStatus) {
        this();
        idstatusProperty().set(refReturPaymentStatus.getIdstatus());
        statusNameProperty().set(refReturPaymentStatus.getStatusName());
        statusNoteProperty().set(refReturPaymentStatus.getStatusNote());

        this.tblReturs = refReturPaymentStatus.getTblReturs();
    }

    public final IntegerProperty idstatusProperty() {
        return this.idstatus;
    }

    public int getIdstatus() {
        return idstatusProperty().get();
    }

    public void setIdstatus(int idstatus) {
        idstatusProperty().set(idstatus);
    }

    public final StringProperty statusNameProperty() {
        return this.statusName;
    }

    public String getStatusName() {
        return statusNameProperty().get();
    }

    public void setStatusName(String statusName) {
        statusNameProperty().set(statusName);
    }

    public final StringProperty statusNoteProperty() {
        return this.statusNote;
    }

    public String getStatusNote() {
        return statusNoteProperty().get();
    }

    public void setStatusNote(String statusNote) {
        statusNoteProperty().set(statusNote);
    }

    public Set getTblReturs() {
        return this.tblReturs;
    }

    public void setTblReturs(Set tblReturs) {
        this.tblReturs = tblReturs;
    }

}
