package hotelfx.persistence.model;
// Generated Sep 7, 2017 1:18:06 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javafx.beans.property.IntegerProperty;
import javafx.beans.property.SimpleIntegerProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * RefReservationBillType generated by hbm2java
 */
public class RefReservationBillType implements java.io.Serializable {

    private final IntegerProperty idtype;
    private final StringProperty typeName;
    private final StringProperty typeNote;

    private Set tblReservationAdditionalItems;
    private Set tblReservationAdditionalServices;
    private Set tblReservationBills;
    private Set tblReservationPayments;

    public RefReservationBillType() {
        this.idtype = new SimpleIntegerProperty();
        this.typeName = new SimpleStringProperty();
        this.typeNote = new SimpleStringProperty();

        this.tblReservationAdditionalItems = new HashSet(0);
        this.tblReservationAdditionalServices = new HashSet(0);
        this.tblReservationBills = new HashSet(0);
        this.tblReservationPayments = new HashSet(0);
    }

    public RefReservationBillType(int idtype) {
        this();
        idtypeProperty().set(idtype);
    }

    public RefReservationBillType(int idtype, String typeName, String typeNote, Set tblReservationAdditionalItems, Set tblReservationAdditionalServices, Set tblReservationBills, Set tblReservationPayments) {
        this();
        idtypeProperty().set(idtype);
        typeNameProperty().set(typeName);
        typeNoteProperty().set(typeNote);

        this.tblReservationAdditionalItems = tblReservationAdditionalItems;
        this.tblReservationAdditionalServices = tblReservationAdditionalServices;
        this.tblReservationBills = tblReservationBills;
        this.tblReservationPayments = tblReservationPayments;
    }

    public RefReservationBillType(RefReservationBillType refReservationBillType) {
        this();
        idtypeProperty().set(refReservationBillType.getIdtype());
        typeNameProperty().set(refReservationBillType.getTypeName());
        typeNoteProperty().set(refReservationBillType.getTypeNote());

        this.tblReservationAdditionalItems = refReservationBillType.getTblReservationAdditionalItems();
        this.tblReservationAdditionalServices = refReservationBillType.getTblReservationAdditionalServices();
        this.tblReservationBills = refReservationBillType.getTblReservationBills();
        this.tblReservationPayments = refReservationBillType.getTblReservationPayments();
    }

    public final IntegerProperty idtypeProperty() {
        return this.idtype;
    }

    public int getIdtype() {
        return idtypeProperty().get();
    }

    public void setIdtype(int idtype) {
        idtypeProperty().set(idtype);
    }

    public final StringProperty typeNameProperty() {
        return this.typeName;
    }

    public String getTypeName() {
        return typeNameProperty().get();
    }

    public void setTypeName(String typeName) {
        typeNameProperty().set(typeName);
    }

    public final StringProperty typeNoteProperty() {
        return this.typeNote;
    }

    public String getTypeNote() {
        return typeNoteProperty().get();
    }

    public void setTypeNote(String typeNote) {
        typeNoteProperty().set(typeNote);
    }

    public Set getTblReservationAdditionalItems() {
        return this.tblReservationAdditionalItems;
    }

    public void setTblReservationAdditionalItems(Set tblReservationAdditionalItems) {
        this.tblReservationAdditionalItems = tblReservationAdditionalItems;
    }

    public Set getTblReservationAdditionalServices() {
        return this.tblReservationAdditionalServices;
    }

    public void setTblReservationAdditionalServices(Set tblReservationAdditionalServices) {
        this.tblReservationAdditionalServices = tblReservationAdditionalServices;
    }

    public Set getTblReservationBills() {
        return this.tblReservationBills;
    }

    public void setTblReservationBills(Set tblReservationBills) {
        this.tblReservationBills = tblReservationBills;
    }

    public Set getTblReservationPayments() {
        return this.tblReservationPayments;
    }

    public void setTblReservationPayments(Set tblReservationPayments) {
        this.tblReservationPayments = tblReservationPayments;
    }

    @Override
    public String toString(){
        return getTypeName();
    }
    
}
