package hotelfx.persistence.model;
// Generated Aug 21, 2017 1:49:32 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javafx.beans.property.IntegerProperty;
import javafx.beans.property.SimpleIntegerProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * RefRoomCheckStatus generated by hbm2java
 */
public class RefRoomCheckStatus implements java.io.Serializable {

    private final IntegerProperty idstatus;
    private final StringProperty statusName;
    private final StringProperty statusNote;

    private Set tblRoomChecks;

    public RefRoomCheckStatus() {
        this.idstatus = new SimpleIntegerProperty();
        this.statusName = new SimpleStringProperty();
        this.statusNote = new SimpleStringProperty();

        this.tblRoomChecks = new HashSet(0);
    }

    public RefRoomCheckStatus(int idstatus) {
        this();
        idstatusProperty().set(idstatus);
    }

    public RefRoomCheckStatus(int idstatus, String statusName, String statusNote, Set tblRoomChecks) {
        this();
        idstatusProperty().set(idstatus);
        statusNameProperty().set(statusName);
        statusNoteProperty().set(statusNote);

        this.tblRoomChecks = tblRoomChecks;
    }

    public RefRoomCheckStatus(RefRoomCheckStatus refRoomCheckStatus) {
        this();
        idstatusProperty().set(refRoomCheckStatus.getIdstatus());
        statusNameProperty().set(refRoomCheckStatus.getStatusName());
        statusNoteProperty().set(refRoomCheckStatus.getStatusNote());

        this.tblRoomChecks = refRoomCheckStatus.getTblRoomChecks();
    }

    public final IntegerProperty idstatusProperty() {
        return this.idstatus;
    }

    public int getIdstatus() {
        return idstatusProperty().get();
    }

    public void setIdstatus(int idstatus) {
        idstatusProperty().set(idstatus);
    }

    public final StringProperty statusNameProperty() {
        return this.statusName;
    }

    public String getStatusName() {
        return statusNameProperty().get();
    }

    public void setStatusName(String statusName) {
        statusNameProperty().set(statusName);
    }

    public final StringProperty statusNoteProperty() {
        return this.statusNote;
    }

    public String getStatusNote() {
        return statusNoteProperty().get();
    }

    public void setStatusNote(String statusNote) {
        statusNoteProperty().set(statusNote);
    }

    public Set getTblRoomChecks() {
        return this.tblRoomChecks;
    }

    public void setTblRoomChecks(Set tblRoomChecks) {
        this.tblRoomChecks = tblRoomChecks;
    }

}
