package hotelfx.persistence.model;
// Generated Aug 31, 2017 2:12:52 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javafx.beans.property.IntegerProperty;
import javafx.beans.property.SimpleIntegerProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * RefReservationCheckInOutStatus generated by hbm2java
 */
public class RefReservationCheckInOutStatus implements java.io.Serializable {

    private final IntegerProperty idstatus;
    private final StringProperty statusName;
    private final StringProperty statusNote;

    private Set tblReservationCheckInOuts;

    public RefReservationCheckInOutStatus() {
        this.idstatus = new SimpleIntegerProperty();
        this.statusName = new SimpleStringProperty();
        this.statusNote = new SimpleStringProperty();

        this.tblReservationCheckInOuts = new HashSet(0);
    }

    public RefReservationCheckInOutStatus(int idstatus) {
        this();
        idstatusProperty().set(idstatus);
    }

    public RefReservationCheckInOutStatus(int idstatus, String statusName, String statusNote, Set tblReservationCheckInOuts) {
        this();
        idstatusProperty().set(idstatus);
        statusNameProperty().set(statusName);
        statusNoteProperty().set(statusNote);

        this.tblReservationCheckInOuts = tblReservationCheckInOuts;
    }

    public RefReservationCheckInOutStatus(RefReservationCheckInOutStatus refReservationCheckInOutStatus) {
        this();
        idstatusProperty().set(refReservationCheckInOutStatus.getIdstatus());
        statusNameProperty().set(refReservationCheckInOutStatus.getStatusName());
        statusNoteProperty().set(refReservationCheckInOutStatus.getStatusNote());

        this.tblReservationCheckInOuts = refReservationCheckInOutStatus.getTblReservationCheckInOuts();
    }

    public final IntegerProperty idstatusProperty() {
        return this.idstatus;
    }

    public int getIdstatus() {
        return idstatusProperty().get();
    }

    public void setIdstatus(int idstatus) {
        idstatusProperty().set(idstatus);
    }

    public final StringProperty statusNameProperty() {
        return this.statusName;
    }

    public String getStatusName() {
        return statusNameProperty().get();
    }

    public void setStatusName(String statusName) {
        statusNameProperty().set(statusName);
    }

    public final StringProperty statusNoteProperty() {
        return this.statusNote;
    }

    public String getStatusNote() {
        return statusNoteProperty().get();
    }

    public void setStatusNote(String statusNote) {
        statusNoteProperty().set(statusNote);
    }

    public Set getTblReservationCheckInOuts() {
        return this.tblReservationCheckInOuts;
    }

    public void setTblReservationCheckInOuts(Set tblReservationCheckInOuts) {
        this.tblReservationCheckInOuts = tblReservationCheckInOuts;
    }

}
