package hotelfx.persistence.model;
// Generated Mar 6, 2018 4:36:36 PM by Hibernate Tools 4.3.1

import javafx.beans.property.IntegerProperty;
import javafx.beans.property.SimpleIntegerProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * RefRoomInspectionStatus generated by hbm2java
 */
public class RefRoomInspectionStatus implements java.io.Serializable {

    private final IntegerProperty idstatus;
    private final StringProperty statusName;
    private final StringProperty statusNote;

    public RefRoomInspectionStatus() {
        this.idstatus = new SimpleIntegerProperty();
        this.statusName = new SimpleStringProperty();
        this.statusNote = new SimpleStringProperty();

    }

    public RefRoomInspectionStatus(int idstatus) {
        this();
        idstatusProperty().set(idstatus);
    }

    public RefRoomInspectionStatus(int idstatus, String statusName, String statusNote) {
        this();
        idstatusProperty().set(idstatus);
        statusNameProperty().set(statusName);
        statusNoteProperty().set(statusNote);

    }

    public RefRoomInspectionStatus(RefRoomInspectionStatus refRoomInspectionStatus) {
        this();
        idstatusProperty().set(refRoomInspectionStatus.getIdstatus());
        statusNameProperty().set(refRoomInspectionStatus.getStatusName());
        statusNoteProperty().set(refRoomInspectionStatus.getStatusNote());

    }

    public final IntegerProperty idstatusProperty() {
        return this.idstatus;
    }

    public int getIdstatus() {
        return idstatusProperty().get();
    }

    public void setIdstatus(int idstatus) {
        idstatusProperty().set(idstatus);
    }

    public final StringProperty statusNameProperty() {
        return this.statusName;
    }

    public String getStatusName() {
        return statusNameProperty().get();
    }

    public void setStatusName(String statusName) {
        statusNameProperty().set(statusName);
    }

    public final StringProperty statusNoteProperty() {
        return this.statusNote;
    }

    public String getStatusNote() {
        return statusNoteProperty().get();
    }

    public void setStatusNote(String statusNote) {
        statusNoteProperty().set(statusNote);
    }

}
