package hotelfx.persistence.model;
// Generated Aug 21, 2017 1:49:32 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javafx.beans.property.IntegerProperty;
import javafx.beans.property.SimpleIntegerProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * RefSystemUserLockStatus generated by hbm2java
 */
public class RefSystemUserLockStatus implements java.io.Serializable {

    private final IntegerProperty idstatus;
    private final StringProperty statusName;
    private final StringProperty statusNote;

    private Set tblSystemUsers;

    public RefSystemUserLockStatus() {
        this.idstatus = new SimpleIntegerProperty();
        this.statusName = new SimpleStringProperty();
        this.statusNote = new SimpleStringProperty();

        this.tblSystemUsers = new HashSet(0);
    }

    public RefSystemUserLockStatus(int idstatus) {
        this();
        idstatusProperty().set(idstatus);
    }

    public RefSystemUserLockStatus(int idstatus, String statusName, String statusNote, Set tblSystemUsers) {
        this();
        idstatusProperty().set(idstatus);
        statusNameProperty().set(statusName);
        statusNoteProperty().set(statusNote);

        this.tblSystemUsers = tblSystemUsers;
    }

    public RefSystemUserLockStatus(RefSystemUserLockStatus refSystemUserLockStatus) {
        this();
        idstatusProperty().set(refSystemUserLockStatus.getIdstatus());
        statusNameProperty().set(refSystemUserLockStatus.getStatusName());
        statusNoteProperty().set(refSystemUserLockStatus.getStatusNote());

        this.tblSystemUsers = refSystemUserLockStatus.getTblSystemUsers();
    }

    public final IntegerProperty idstatusProperty() {
        return this.idstatus;
    }

    public int getIdstatus() {
        return idstatusProperty().get();
    }

    public void setIdstatus(int idstatus) {
        idstatusProperty().set(idstatus);
    }

    public final StringProperty statusNameProperty() {
        return this.statusName;
    }

    public String getStatusName() {
        return statusNameProperty().get();
    }

    public void setStatusName(String statusName) {
        statusNameProperty().set(statusName);
    }

    public final StringProperty statusNoteProperty() {
        return this.statusNote;
    }

    public String getStatusNote() {
        return statusNoteProperty().get();
    }

    public void setStatusNote(String statusNote) {
        statusNoteProperty().set(statusNote);
    }

    public Set getTblSystemUsers() {
        return this.tblSystemUsers;
    }

    public void setTblSystemUsers(Set tblSystemUsers) {
        this.tblSystemUsers = tblSystemUsers;
    }

    @Override
    public String toString() {
        return getStatusName();
    }

}
