package hotelfx.persistence.model;
// Generated Sep 26, 2018 12:37:42 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javafx.beans.property.BooleanProperty;
import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleBooleanProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * SysCalendar generated by hbm2java
 */
public class SysCalendar implements java.io.Serializable {

    private final LongProperty idcalendar;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<Date> calendarDate;
    private final BooleanProperty dayOffStatus;
    private final StringProperty calendarNote;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    private Set tblCalendarEmployeeOvertimes;
    private Set tblCalendarEmployeePaymentDebtHistories;
    private Set tblCalendarEmployeeLeaves;
    private Set tblCalendarEmployeeAttendances;
    private Set tblCalendarEmployeeSchedules;

    public SysCalendar() {
        this.idcalendar = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.calendarDate = new SimpleObjectProperty<>();
        this.dayOffStatus = new SimpleBooleanProperty();
        this.calendarNote = new SimpleStringProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

        this.tblCalendarEmployeeOvertimes = new HashSet(0);
        this.tblCalendarEmployeePaymentDebtHistories = new HashSet(0);
        this.tblCalendarEmployeeLeaves = new HashSet(0);
        this.tblCalendarEmployeeAttendances = new HashSet(0);
        this.tblCalendarEmployeeSchedules = new HashSet(0);
    }

    public SysCalendar(long idcalendar) {
        this();
        idcalendarProperty().set(idcalendar);
    }

    public SysCalendar(long idcalendar, RefRecordStatus refRecordStatus, TblEmployee tblEmployeeByCreateBy, TblEmployee tblEmployeeByLastUpdateBy, Date calendarDate, Boolean dayOffStatus, String calendarNote, Date createDate, Date lastUpdateDate, Set tblCalendarEmployeeOvertimes, Set tblCalendarEmployeePaymentDebtHistories, Set tblCalendarEmployeeLeaves, Set tblCalendarEmployeeAttendances, Set tblCalendarEmployeeSchedules) {
        this();
        idcalendarProperty().set(idcalendar);
        refRecordStatusProperty().set(refRecordStatus);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        calendarDateProperty().set(calendarDate);
        dayOffStatusProperty().set(dayOffStatus);
        calendarNoteProperty().set(calendarNote);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

        this.tblCalendarEmployeeOvertimes = tblCalendarEmployeeOvertimes;
        this.tblCalendarEmployeePaymentDebtHistories = tblCalendarEmployeePaymentDebtHistories;
        this.tblCalendarEmployeeLeaves = tblCalendarEmployeeLeaves;
        this.tblCalendarEmployeeAttendances = tblCalendarEmployeeAttendances;
        this.tblCalendarEmployeeSchedules = tblCalendarEmployeeSchedules;
    }

    public SysCalendar(SysCalendar sysCalendar) {
        this();
        idcalendarProperty().set(sysCalendar.getIdcalendar());
        refRecordStatusProperty().set(sysCalendar.getRefRecordStatus());
        tblEmployeeByCreateByProperty().set(sysCalendar.getTblEmployeeByCreateBy());
        tblEmployeeByLastUpdateByProperty().set(sysCalendar.getTblEmployeeByLastUpdateBy());
        calendarDateProperty().set(sysCalendar.getCalendarDate());
        dayOffStatusProperty().set(sysCalendar.getDayOffStatus());
        calendarNoteProperty().set(sysCalendar.getCalendarNote());
        createDateProperty().set(sysCalendar.getCreateDate());
        lastUpdateDateProperty().set(sysCalendar.getLastUpdateDate());

        this.tblCalendarEmployeeOvertimes = sysCalendar.getTblCalendarEmployeeOvertimes();
        this.tblCalendarEmployeePaymentDebtHistories = sysCalendar.getTblCalendarEmployeePaymentDebtHistories();
        this.tblCalendarEmployeeLeaves = sysCalendar.getTblCalendarEmployeeLeaves();
        this.tblCalendarEmployeeAttendances = sysCalendar.getTblCalendarEmployeeAttendances();
        this.tblCalendarEmployeeSchedules = sysCalendar.getTblCalendarEmployeeSchedules();
    }

    public final LongProperty idcalendarProperty() {
        return this.idcalendar;
    }

    public long getIdcalendar() {
        return idcalendarProperty().get();
    }

    public void setIdcalendar(long idcalendar) {
        idcalendarProperty().set(idcalendar);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<Date> calendarDateProperty() {
        return this.calendarDate;
    }

    public Date getCalendarDate() {
        return calendarDateProperty().get();
    }

    public void setCalendarDate(Date calendarDate) {
        calendarDateProperty().set(calendarDate);
    }

    public final BooleanProperty dayOffStatusProperty() {
        return this.dayOffStatus;
    }

    public Boolean getDayOffStatus() {
        return dayOffStatusProperty().get();
    }

    public void setDayOffStatus(Boolean dayOffStatus) {
        dayOffStatusProperty().set(dayOffStatus);
    }

    public final StringProperty calendarNoteProperty() {
        return this.calendarNote;
    }

    public String getCalendarNote() {
        return calendarNoteProperty().get();
    }

    public void setCalendarNote(String calendarNote) {
        calendarNoteProperty().set(calendarNote);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

    public Set getTblCalendarEmployeeOvertimes() {
        return this.tblCalendarEmployeeOvertimes;
    }

    public void setTblCalendarEmployeeOvertimes(Set tblCalendarEmployeeOvertimes) {
        this.tblCalendarEmployeeOvertimes = tblCalendarEmployeeOvertimes;
    }

    public Set getTblCalendarEmployeePaymentDebtHistories() {
        return this.tblCalendarEmployeePaymentDebtHistories;
    }

    public void setTblCalendarEmployeePaymentDebtHistories(Set tblCalendarEmployeePaymentDebtHistories) {
        this.tblCalendarEmployeePaymentDebtHistories = tblCalendarEmployeePaymentDebtHistories;
    }

    public Set getTblCalendarEmployeeLeaves() {
        return this.tblCalendarEmployeeLeaves;
    }

    public void setTblCalendarEmployeeLeaves(Set tblCalendarEmployeeLeaves) {
        this.tblCalendarEmployeeLeaves = tblCalendarEmployeeLeaves;
    }

    public Set getTblCalendarEmployeeAttendances() {
        return this.tblCalendarEmployeeAttendances;
    }

    public void setTblCalendarEmployeeAttendances(Set tblCalendarEmployeeAttendances) {
        this.tblCalendarEmployeeAttendances = tblCalendarEmployeeAttendances;
    }

    public Set getTblCalendarEmployeeSchedules() {
        return this.tblCalendarEmployeeSchedules;
    }

    public void setTblCalendarEmployeeSchedules(Set tblCalendarEmployeeSchedules) {
        this.tblCalendarEmployeeSchedules = tblCalendarEmployeeSchedules;
    }

}
