package hotelfx.persistence.model;
// Generated Aug 21, 2017 1:49:32 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * SysProgram generated by hbm2java
 */
public class SysProgram implements java.io.Serializable {

    private final LongProperty idprogram;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final StringProperty codeProgram;
    private final StringProperty programName;
    private final StringProperty programTableName;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    private Set sysProgramAccounts;

    public SysProgram() {
        this.idprogram = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.codeProgram = new SimpleStringProperty();
        this.programName = new SimpleStringProperty();
        this.programTableName = new SimpleStringProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

        this.sysProgramAccounts = new HashSet(0);
    }

    public SysProgram(long idprogram) {
        this();
        idprogramProperty().set(idprogram);
    }

    public SysProgram(long idprogram, RefRecordStatus refRecordStatus, TblEmployee tblEmployeeByLastUpdateBy, TblEmployee tblEmployeeByCreateBy, String codeProgram, String programName, String programTableName, Date createDate, Date lastUpdateDate, Set sysProgramAccounts) {
        this();
        idprogramProperty().set(idprogram);
        refRecordStatusProperty().set(refRecordStatus);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        codeProgramProperty().set(codeProgram);
        programNameProperty().set(programName);
        programTableNameProperty().set(programTableName);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

        this.sysProgramAccounts = sysProgramAccounts;
    }

    public SysProgram(SysProgram sysProgram) {
        this();
        idprogramProperty().set(sysProgram.getIdprogram());
        refRecordStatusProperty().set(sysProgram.getRefRecordStatus());
        tblEmployeeByLastUpdateByProperty().set(sysProgram.getTblEmployeeByLastUpdateBy());
        tblEmployeeByCreateByProperty().set(sysProgram.getTblEmployeeByCreateBy());
        codeProgramProperty().set(sysProgram.getCodeProgram());
        programNameProperty().set(sysProgram.getProgramName());
        programTableNameProperty().set(sysProgram.getProgramTableName());
        createDateProperty().set(sysProgram.getCreateDate());
        lastUpdateDateProperty().set(sysProgram.getLastUpdateDate());

        this.sysProgramAccounts = sysProgram.getSysProgramAccounts();
    }

    public final LongProperty idprogramProperty() {
        return this.idprogram;
    }

    public long getIdprogram() {
        return idprogramProperty().get();
    }

    public void setIdprogram(long idprogram) {
        idprogramProperty().set(idprogram);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final StringProperty codeProgramProperty() {
        return this.codeProgram;
    }

    public String getCodeProgram() {
        return codeProgramProperty().get();
    }

    public void setCodeProgram(String codeProgram) {
        codeProgramProperty().set(codeProgram);
    }

    public final StringProperty programNameProperty() {
        return this.programName;
    }

    public String getProgramName() {
        return programNameProperty().get();
    }

    public void setProgramName(String programName) {
        programNameProperty().set(programName);
    }

    public final StringProperty programTableNameProperty() {
        return this.programTableName;
    }

    public String getProgramTableName() {
        return programTableNameProperty().get();
    }

    public void setProgramTableName(String programTableName) {
        programTableNameProperty().set(programTableName);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

    public Set getSysProgramAccounts() {
        return this.sysProgramAccounts;
    }

    public void setSysProgramAccounts(Set sysProgramAccounts) {
        this.sysProgramAccounts = sysProgramAccounts;
    }

}
