package hotelfx.persistence.model;
// Generated Aug 21, 2017 1:49:32 PM by Hibernate Tools 4.3.1

import java.util.Date;

import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.LongProperty;
import javafx.beans.property.StringProperty;

/**
 * SysSystem generated by hbm2java
 */
public class SysSystem implements java.io.Serializable {

    private final LongProperty idsystem;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<RefSystemStatus> refSystemStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final StringProperty codeSystem;
    private final StringProperty systemName;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    public SysSystem() {
        this.idsystem = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.refSystemStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.codeSystem = new SimpleStringProperty();
        this.systemName = new SimpleStringProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

    }

    public SysSystem(long idsystem) {
        this();
        idsystemProperty().set(idsystem);
    }

    public SysSystem(long idsystem, RefRecordStatus refRecordStatus, RefSystemStatus refSystemStatus, TblEmployee tblEmployeeByLastUpdateBy, TblEmployee tblEmployeeByCreateBy, String codeSystem, String systemName, Date createDate, Date lastUpdateDate) {
        this();
        idsystemProperty().set(idsystem);
        refRecordStatusProperty().set(refRecordStatus);
        refSystemStatusProperty().set(refSystemStatus);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        codeSystemProperty().set(codeSystem);
        systemNameProperty().set(systemName);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

    }

    public SysSystem(SysSystem sysSystem) {
        this();
        idsystemProperty().set(sysSystem.getIdsystem());
        refRecordStatusProperty().set(sysSystem.getRefRecordStatus());
        refSystemStatusProperty().set(sysSystem.getRefSystemStatus());
        tblEmployeeByLastUpdateByProperty().set(sysSystem.getTblEmployeeByLastUpdateBy());
        tblEmployeeByCreateByProperty().set(sysSystem.getTblEmployeeByCreateBy());
        codeSystemProperty().set(sysSystem.getCodeSystem());
        systemNameProperty().set(sysSystem.getSystemName());
        createDateProperty().set(sysSystem.getCreateDate());
        lastUpdateDateProperty().set(sysSystem.getLastUpdateDate());

    }

    public final LongProperty idsystemProperty() {
        return this.idsystem;
    }

    public long getIdsystem() {
        return idsystemProperty().get();
    }

    public void setIdsystem(long idsystem) {
        idsystemProperty().set(idsystem);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<RefSystemStatus> refSystemStatusProperty() {
        return this.refSystemStatus;
    }

    public RefSystemStatus getRefSystemStatus() {
        return refSystemStatusProperty().get();
    }

    public void setRefSystemStatus(RefSystemStatus refSystemStatus) {
        refSystemStatusProperty().set(refSystemStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final StringProperty codeSystemProperty() {
        return this.codeSystem;
    }

    public String getCodeSystem() {
        return codeSystemProperty().get();
    }

    public void setCodeSystem(String codeSystem) {
        codeSystemProperty().set(codeSystem);
    }

    public final StringProperty systemNameProperty() {
        return this.systemName;
    }

    public String getSystemName() {
        return systemNameProperty().get();
    }

    public void setSystemName(String systemName) {
        systemNameProperty().set(systemName);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

}
