package hotelfx.persistence.model;
// Generated Sep 25, 2017 8:58:22 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblApprovalJobRequired generated by hbm2java
 */
public class TblApprovalJobRequired implements java.io.Serializable {

    private final LongProperty idapprovalJobRequired;
    private final ObjectProperty<RefApprovalDataType> refApprovalDataType;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblJob> tblJob;
    private final StringProperty requiredNote;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    private Set tblApprovalJobPrivilages;

    public TblApprovalJobRequired() {
        this.idapprovalJobRequired = new SimpleLongProperty();
        this.refApprovalDataType = new SimpleObjectProperty<>();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblJob = new SimpleObjectProperty<>();
        this.requiredNote = new SimpleStringProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

        this.tblApprovalJobPrivilages = new HashSet(0);
    }

    public TblApprovalJobRequired(long idapprovalJobRequired) {
        this();
        idapprovalJobRequiredProperty().set(idapprovalJobRequired);
    }

    public TblApprovalJobRequired(long idapprovalJobRequired, RefApprovalDataType refApprovalDataType, RefRecordStatus refRecordStatus, TblEmployee tblEmployeeByLastUpdateBy, TblEmployee tblEmployeeByCreateBy, TblJob tblJob, String requiredNote, Date createDate, Date lastUpdateDate, Set tblApprovalJobPrivilages) {
        this();
        idapprovalJobRequiredProperty().set(idapprovalJobRequired);
        refApprovalDataTypeProperty().set(refApprovalDataType);
        refRecordStatusProperty().set(refRecordStatus);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblJobProperty().set(tblJob);
        requiredNoteProperty().set(requiredNote);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

        this.tblApprovalJobPrivilages = tblApprovalJobPrivilages;
    }

    public TblApprovalJobRequired(TblApprovalJobRequired tblApprovalJobRequired) {
        this();
        idapprovalJobRequiredProperty().set(tblApprovalJobRequired.getIdapprovalJobRequired());
        refApprovalDataTypeProperty().set(tblApprovalJobRequired.getRefApprovalDataType());
        refRecordStatusProperty().set(tblApprovalJobRequired.getRefRecordStatus());
        tblEmployeeByLastUpdateByProperty().set(tblApprovalJobRequired.getTblEmployeeByLastUpdateBy());
        tblEmployeeByCreateByProperty().set(tblApprovalJobRequired.getTblEmployeeByCreateBy());
        tblJobProperty().set(tblApprovalJobRequired.getTblJob());
        requiredNoteProperty().set(tblApprovalJobRequired.getRequiredNote());
        createDateProperty().set(tblApprovalJobRequired.getCreateDate());
        lastUpdateDateProperty().set(tblApprovalJobRequired.getLastUpdateDate());

        this.tblApprovalJobPrivilages = tblApprovalJobRequired.getTblApprovalJobPrivilages();
    }

    public final LongProperty idapprovalJobRequiredProperty() {
        return this.idapprovalJobRequired;
    }

    public long getIdapprovalJobRequired() {
        return idapprovalJobRequiredProperty().get();
    }

    public void setIdapprovalJobRequired(long idapprovalJobRequired) {
        idapprovalJobRequiredProperty().set(idapprovalJobRequired);
    }

    public final ObjectProperty<RefApprovalDataType> refApprovalDataTypeProperty() {
        return this.refApprovalDataType;
    }

    public RefApprovalDataType getRefApprovalDataType() {
        return refApprovalDataTypeProperty().get();
    }

    public void setRefApprovalDataType(RefApprovalDataType refApprovalDataType) {
        refApprovalDataTypeProperty().set(refApprovalDataType);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblJob> tblJobProperty() {
        return this.tblJob;
    }

    public TblJob getTblJob() {
        return tblJobProperty().get();
    }

    public void setTblJob(TblJob tblJob) {
        tblJobProperty().set(tblJob);
    }

    public final StringProperty requiredNoteProperty() {
        return this.requiredNote;
    }

    public String getRequiredNote() {
        return requiredNoteProperty().get();
    }

    public void setRequiredNote(String requiredNote) {
        requiredNoteProperty().set(requiredNote);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

    public Set getTblApprovalJobPrivilages() {
        return this.tblApprovalJobPrivilages;
    }

    public void setTblApprovalJobPrivilages(Set tblApprovalJobPrivilages) {
        this.tblApprovalJobPrivilages = tblApprovalJobPrivilages;
    }

}
