package hotelfx.persistence.model;
// Generated Aug 21, 2017 1:49:32 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblApplicant generated by hbm2java
 */
public class TblApplicant implements java.io.Serializable {

    private final LongProperty idapplicant;
    private final ObjectProperty<RefApplicantStatus> refApplicantStatus;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblJob> tblJobByApplymentJob2;
    private final ObjectProperty<TblJob> tblJobByApplymentJob1;
    private final ObjectProperty<TblPeople> tblPeople;
    private final StringProperty codeApplicant;
    private final ObjectProperty<Date> applymentDate;
    private final StringProperty applicantNote;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    public TblApplicant() {
        this.idapplicant = new SimpleLongProperty();
        this.refApplicantStatus = new SimpleObjectProperty<>();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblJobByApplymentJob2 = new SimpleObjectProperty<>();
        this.tblJobByApplymentJob1 = new SimpleObjectProperty<>();
        this.tblPeople = new SimpleObjectProperty<>();
        this.codeApplicant = new SimpleStringProperty();
        this.applymentDate = new SimpleObjectProperty<>();
        this.applicantNote = new SimpleStringProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();
    }

    public TblApplicant(long idapplicant) {
        this();
        idapplicantProperty().set(idapplicant);
    }

    public TblApplicant(long idapplicant, RefApplicantStatus refApplicantStatus, RefRecordStatus refRecordStatus, TblEmployee tblEmployeeByLastUpdateBy, TblEmployee tblEmployeeByCreateBy, TblJob tblJobByApplymentJob2, TblJob tblJobByApplymentJob1, TblPeople tblPeople, String codeApplicant, String idpeople, Date applymentDate, String applicantNote, Date createDate, Date lastUpdateDate) {
        this();
        idapplicantProperty().set(idapplicant);
        refApplicantStatusProperty().set(refApplicantStatus);
        refRecordStatusProperty().set(refRecordStatus);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblJobByApplymentJob2Property().set(tblJobByApplymentJob2);
        tblJobByApplymentJob1Property().set(tblJobByApplymentJob1);
        tblPeopleProperty().set(tblPeople);
        codeApplicantProperty().set(codeApplicant);
        applymentDateProperty().set(applymentDate);
        applicantNoteProperty().set(applicantNote);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);
    }

    public TblApplicant(TblApplicant tblApplicant) {
        this();
        idapplicantProperty().set(tblApplicant.getIdapplicant());
        refApplicantStatusProperty().set(tblApplicant.getRefApplicantStatus());
        refRecordStatusProperty().set(tblApplicant.getRefRecordStatus());
        tblEmployeeByLastUpdateByProperty().set(tblApplicant.getTblEmployeeByLastUpdateBy());
        tblEmployeeByCreateByProperty().set(tblApplicant.getTblEmployeeByCreateBy());
        tblJobByApplymentJob2Property().set(tblApplicant.getTblJobByApplymentJob2());
        tblJobByApplymentJob1Property().set(tblApplicant.getTblJobByApplymentJob1());
        tblPeopleProperty().set(tblApplicant.getTblPeople());
        codeApplicantProperty().set(tblApplicant.getCodeApplicant());
        applymentDateProperty().set(tblApplicant.getApplymentDate());
        applicantNoteProperty().set(tblApplicant.getApplicantNote());
        createDateProperty().set(tblApplicant.getCreateDate());
        lastUpdateDateProperty().set(tblApplicant.getLastUpdateDate());

    }

    public final LongProperty idapplicantProperty() {
        return this.idapplicant;
    }

    public long getIdapplicant() {
        return idapplicantProperty().get();
    }

    public void setIdapplicant(long idapplicant) {
        idapplicantProperty().set(idapplicant);
    }

    public final ObjectProperty<RefApplicantStatus> refApplicantStatusProperty() {
        return this.refApplicantStatus;
    }

    public RefApplicantStatus getRefApplicantStatus() {
        return refApplicantStatusProperty().get();
    }

    public void setRefApplicantStatus(RefApplicantStatus refApplicantStatus) {
        refApplicantStatusProperty().set(refApplicantStatus);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblJob> tblJobByApplymentJob2Property() {
        return this.tblJobByApplymentJob2;
    }

    public TblJob getTblJobByApplymentJob2() {
        return tblJobByApplymentJob2Property().get();
    }

    public void setTblJobByApplymentJob2(TblJob tblJobByApplymentJob2) {
        tblJobByApplymentJob2Property().set(tblJobByApplymentJob2);
    }

    public final ObjectProperty<TblJob> tblJobByApplymentJob1Property() {
        return this.tblJobByApplymentJob1;
    }

    public TblJob getTblJobByApplymentJob1() {
        return tblJobByApplymentJob1Property().get();
    }

    public void setTblJobByApplymentJob1(TblJob tblJobByApplymentJob1) {
        tblJobByApplymentJob1Property().set(tblJobByApplymentJob1);
    }

    public final ObjectProperty<TblPeople> tblPeopleProperty() {
        return this.tblPeople;
    }

    public TblPeople getTblPeople() {
        return tblPeopleProperty().get();
    }

    public void setTblPeople(TblPeople tblPeople) {
        tblPeopleProperty().set(tblPeople);
    }

    public final StringProperty codeApplicantProperty() {
        return this.codeApplicant;
    }

    public String getCodeApplicant() {
        return codeApplicantProperty().get();
    }

    public void setCodeApplicant(String codeApplicant) {
        codeApplicantProperty().set(codeApplicant);
    }

    public final ObjectProperty<Date> applymentDateProperty() {
        return this.applymentDate;
    }

    public Date getApplymentDate() {
        return applymentDateProperty().get();
    }

    public void setApplymentDate(Date applymentDate) {
        applymentDateProperty().set(applymentDate);
    }

    public final StringProperty applicantNoteProperty() {
        return this.applicantNote;
    }

    public String getApplicantNote() {
        return applicantNoteProperty().get();
    }

    public void setApplicantNote(String applicantNote) {
        applicantNoteProperty().set(applicantNote);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

}
