package hotelfx.persistence.model;
// Generated Aug 21, 2017 1:49:32 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblApprovalData generated by hbm2java
 */
public class TblApprovalData implements java.io.Serializable {

    private final LongProperty iddata;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final StringProperty codeData;
    private final StringProperty dataName;
    private final StringProperty dataNote;
    private final StringProperty dataType;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    private Set tblMemorandumInvoices;
    private Set tblReturs;
    private Set tblApprovalApproves;
    private Set tblPurchaseRequests;
    private Set tblPurchaseOrders;

    public TblApprovalData() {
        this.iddata = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.codeData = new SimpleStringProperty();
        this.dataName = new SimpleStringProperty();
        this.dataNote = new SimpleStringProperty();
        this.dataType = new SimpleStringProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

        this.tblMemorandumInvoices = new HashSet(0);
        this.tblReturs = new HashSet(0);
        this.tblApprovalApproves = new HashSet(0);
        this.tblPurchaseRequests = new HashSet(0);
        this.tblPurchaseOrders = new HashSet(0);
    }

    public TblApprovalData(long iddata) {
        this();
        iddataProperty().set(iddata);
    }

    public TblApprovalData(long iddata, RefRecordStatus refRecordStatus, TblEmployee tblEmployeeByLastUpdateBy, TblEmployee tblEmployeeByCreateBy, String codeData, String dataName, String dataNote, String dataType, Date createDate, Date lastUpdateDate, Set tblMemorandumInvoices, Set tblReturs, Set tblApprovalApproves, Set tblPurchaseRequests, Set tblPurchaseOrders) {
        this();
        iddataProperty().set(iddata);
        refRecordStatusProperty().set(refRecordStatus);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        codeDataProperty().set(codeData);
        dataNameProperty().set(dataName);
        dataNoteProperty().set(dataNote);
        dataTypeProperty().set(dataType);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

        this.tblMemorandumInvoices = tblMemorandumInvoices;
        this.tblReturs = tblReturs;
        this.tblApprovalApproves = tblApprovalApproves;
        this.tblPurchaseRequests = tblPurchaseRequests;
        this.tblPurchaseOrders = tblPurchaseOrders;
    }

    public TblApprovalData(TblApprovalData tblApprovalData) {
        this();
        iddataProperty().set(tblApprovalData.getIddata());
        refRecordStatusProperty().set(tblApprovalData.getRefRecordStatus());
        tblEmployeeByLastUpdateByProperty().set(tblApprovalData.getTblEmployeeByLastUpdateBy());
        tblEmployeeByCreateByProperty().set(tblApprovalData.getTblEmployeeByCreateBy());
        codeDataProperty().set(tblApprovalData.getCodeData());
        dataNameProperty().set(tblApprovalData.getDataName());
        dataNoteProperty().set(tblApprovalData.getDataNote());
        dataTypeProperty().set(tblApprovalData.getDataType());
        createDateProperty().set(tblApprovalData.getCreateDate());
        lastUpdateDateProperty().set(tblApprovalData.getLastUpdateDate());

        this.tblMemorandumInvoices = tblApprovalData.getTblMemorandumInvoices();
        this.tblReturs = tblApprovalData.getTblReturs();
        this.tblApprovalApproves = tblApprovalData.getTblApprovalApproves();
        this.tblPurchaseRequests = tblApprovalData.getTblPurchaseRequests();
        this.tblPurchaseOrders = tblApprovalData.getTblPurchaseOrders();
    }

    public final LongProperty iddataProperty() {
        return this.iddata;
    }

    public long getIddata() {
        return iddataProperty().get();
    }

    public void setIddata(long iddata) {
        iddataProperty().set(iddata);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final StringProperty codeDataProperty() {
        return this.codeData;
    }

    public String getCodeData() {
        return codeDataProperty().get();
    }

    public void setCodeData(String codeData) {
        codeDataProperty().set(codeData);
    }

    public final StringProperty dataNameProperty() {
        return this.dataName;
    }

    public String getDataName() {
        return dataNameProperty().get();
    }

    public void setDataName(String dataName) {
        dataNameProperty().set(dataName);
    }

    public final StringProperty dataNoteProperty() {
        return this.dataNote;
    }

    public String getDataNote() {
        return dataNoteProperty().get();
    }

    public void setDataNote(String dataNote) {
        dataNoteProperty().set(dataNote);
    }

    public final StringProperty dataTypeProperty() {
        return this.dataType;
    }

    public String getDataType() {
        return dataTypeProperty().get();
    }

    public void setDataType(String dataType) {
        dataTypeProperty().set(dataType);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

    public Set getTblMemorandumInvoices() {
        return this.tblMemorandumInvoices;
    }

    public void setTblMemorandumInvoices(Set tblMemorandumInvoices) {
        this.tblMemorandumInvoices = tblMemorandumInvoices;
    }

    public Set getTblReturs() {
        return this.tblReturs;
    }

    public void setTblReturs(Set tblReturs) {
        this.tblReturs = tblReturs;
    }

    public Set getTblApprovalApproves() {
        return this.tblApprovalApproves;
    }

    public void setTblApprovalApproves(Set tblApprovalApproves) {
        this.tblApprovalApproves = tblApprovalApproves;
    }

    public Set getTblPurchaseRequests() {
        return this.tblPurchaseRequests;
    }

    public void setTblPurchaseRequests(Set tblPurchaseRequests) {
        this.tblPurchaseRequests = tblPurchaseRequests;
    }

    public Set getTblPurchaseOrders() {
        return this.tblPurchaseOrders;
    }

    public void setTblPurchaseOrders(Set tblPurchaseOrders) {
        this.tblPurchaseOrders = tblPurchaseOrders;
    }

}
