package hotelfx.persistence.model;
// Generated Aug 21, 2017 1:49:32 PM by Hibernate Tools 4.3.1

import java.util.Date;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblApprovalJobPrivilage generated by hbm2java
 */
public class TblApprovalJobPrivilage implements java.io.Serializable {

    private final LongProperty idapprovalJobPrivilage;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblApprovalJobRequired> tblApprovalJobRequired;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblJob> tblJob;
    private final StringProperty privilageNote;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    public TblApprovalJobPrivilage() {
        this.idapprovalJobPrivilage = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblApprovalJobRequired = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblJob = new SimpleObjectProperty<>();
        this.privilageNote = new SimpleStringProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

    }

    public TblApprovalJobPrivilage(long idapprovalJobPrivilage) {
        this();
        idapprovalJobPrivilageProperty().set(idapprovalJobPrivilage);
    }

    public TblApprovalJobPrivilage(long idapprovalJobPrivilage, RefRecordStatus refRecordStatus, TblApprovalJobRequired tblApprovalJobRequired, TblEmployee tblEmployeeByCreateBy, TblEmployee tblEmployeeByLastUpdateBy, TblJob tblJob, String privilageNote, Date createDate, Date lastUpdateDate) {
        this();
        idapprovalJobPrivilageProperty().set(idapprovalJobPrivilage);
        refRecordStatusProperty().set(refRecordStatus);
        tblApprovalJobRequiredProperty().set(tblApprovalJobRequired);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblJobProperty().set(tblJob);
        privilageNoteProperty().set(privilageNote);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

    }

    public TblApprovalJobPrivilage(TblApprovalJobPrivilage tblApprovalJobPrivilage) {
        this();
        idapprovalJobPrivilageProperty().set(tblApprovalJobPrivilage.getIdapprovalJobPrivilage());
        refRecordStatusProperty().set(tblApprovalJobPrivilage.getRefRecordStatus());
        tblApprovalJobRequiredProperty().set(tblApprovalJobPrivilage.getTblApprovalJobRequired());
        tblEmployeeByCreateByProperty().set(tblApprovalJobPrivilage.getTblEmployeeByCreateBy());
        tblEmployeeByLastUpdateByProperty().set(tblApprovalJobPrivilage.getTblEmployeeByLastUpdateBy());
        tblJobProperty().set(tblApprovalJobPrivilage.getTblJob());
        privilageNoteProperty().set(tblApprovalJobPrivilage.getPrivilageNote());
        createDateProperty().set(tblApprovalJobPrivilage.getCreateDate());
        lastUpdateDateProperty().set(tblApprovalJobPrivilage.getLastUpdateDate());

    }

    public final LongProperty idapprovalJobPrivilageProperty() {
        return this.idapprovalJobPrivilage;
    }

    public long getIdapprovalJobPrivilage() {
        return idapprovalJobPrivilageProperty().get();
    }

    public void setIdapprovalJobPrivilage(long idapprovalJobPrivilage) {
        idapprovalJobPrivilageProperty().set(idapprovalJobPrivilage);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblApprovalJobRequired> tblApprovalJobRequiredProperty() {
        return this.tblApprovalJobRequired;
    }

    public TblApprovalJobRequired getTblApprovalJobRequired() {
        return tblApprovalJobRequiredProperty().get();
    }

    public void setTblApprovalJobRequired(TblApprovalJobRequired tblApprovalJobRequired) {
        tblApprovalJobRequiredProperty().set(tblApprovalJobRequired);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblJob> tblJobProperty() {
        return this.tblJob;
    }

    public TblJob getTblJob() {
        return tblJobProperty().get();
    }

    public void setTblJob(TblJob tblJob) {
        tblJobProperty().set(tblJob);
    }

    public final StringProperty privilageNoteProperty() {
        return this.privilageNote;
    }

    public String getPrivilageNote() {
        return privilageNoteProperty().get();
    }

    public void setPrivilageNote(String privilageNote) {
        privilageNoteProperty().set(privilageNote);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

}
