package hotelfx.persistence.model;
// Generated Aug 21, 2017 1:49:32 PM by Hibernate Tools 4.3.1

import java.util.Date;

import javafx.beans.property.IntegerProperty;
import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleIntegerProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblApprovalApprove generated by hbm2java
 */
public class TblApprovalApprove implements java.io.Serializable {

    private final LongProperty idapprove;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblApprovalData> tblApprovalData;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByIdemployee;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final StringProperty codeApprove;
    private final IntegerProperty iddataType;
    private final LongProperty idjobRequired;
    private final LongProperty idjobReal;
    private final ObjectProperty<Date> approveDate;
    private final StringProperty approveNote;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    public TblApprovalApprove() {
        this.idapprove = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblApprovalData = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByIdemployee = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.codeApprove = new SimpleStringProperty();
        this.iddataType = new SimpleIntegerProperty();
        this.idjobRequired = new SimpleLongProperty();
        this.idjobReal = new SimpleLongProperty();
        this.approveDate = new SimpleObjectProperty<>();
        this.approveNote = new SimpleStringProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

    }

    public TblApprovalApprove(long idapprove) {
        this();
        idapproveProperty().set(idapprove);
    }

    public TblApprovalApprove(long idapprove, RefRecordStatus refRecordStatus, TblApprovalData tblApprovalData, TblEmployee tblEmployeeByCreateBy, TblEmployee tblEmployeeByIdemployee, TblEmployee tblEmployeeByLastUpdateBy, String codeApprove, Integer iddataType, Long idjobRequired, Long idjobReal, Date approveDate, String approveNote, Date createDate, Date lastUpdateDate) {
        this();
        idapproveProperty().set(idapprove);
        refRecordStatusProperty().set(refRecordStatus);
        tblApprovalDataProperty().set(tblApprovalData);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblEmployeeByIdemployeeProperty().set(tblEmployeeByIdemployee);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        codeApproveProperty().set(codeApprove);
        iddataTypeProperty().set(iddataType);
        idjobRequiredProperty().set(idjobRequired);
        idjobRealProperty().set(idjobReal);
        approveDateProperty().set(approveDate);
        approveNoteProperty().set(approveNote);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

    }

    public TblApprovalApprove(TblApprovalApprove tblApprovalApprove) {
        this();
        idapproveProperty().set(tblApprovalApprove.getIdapprove());
        refRecordStatusProperty().set(tblApprovalApprove.getRefRecordStatus());
        tblApprovalDataProperty().set(tblApprovalApprove.getTblApprovalData());
        tblEmployeeByCreateByProperty().set(tblApprovalApprove.getTblEmployeeByCreateBy());
        tblEmployeeByIdemployeeProperty().set(tblApprovalApprove.getTblEmployeeByIdemployee());
        tblEmployeeByLastUpdateByProperty().set(tblApprovalApprove.getTblEmployeeByLastUpdateBy());
        codeApproveProperty().set(tblApprovalApprove.getCodeApprove());
        iddataTypeProperty().set(tblApprovalApprove.getIddataType());
        idjobRequiredProperty().set(tblApprovalApprove.getIdjobRequired());
        idjobRealProperty().set(tblApprovalApprove.getIdjobReal());
        approveDateProperty().set(tblApprovalApprove.getApproveDate());
        approveNoteProperty().set(tblApprovalApprove.getApproveNote());
        createDateProperty().set(tblApprovalApprove.getCreateDate());
        lastUpdateDateProperty().set(tblApprovalApprove.getLastUpdateDate());

    }

    public final LongProperty idapproveProperty() {
        return this.idapprove;
    }

    public long getIdapprove() {
        return idapproveProperty().get();
    }

    public void setIdapprove(long idapprove) {
        idapproveProperty().set(idapprove);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblApprovalData> tblApprovalDataProperty() {
        return this.tblApprovalData;
    }

    public TblApprovalData getTblApprovalData() {
        return tblApprovalDataProperty().get();
    }

    public void setTblApprovalData(TblApprovalData tblApprovalData) {
        tblApprovalDataProperty().set(tblApprovalData);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByIdemployeeProperty() {
        return this.tblEmployeeByIdemployee;
    }

    public TblEmployee getTblEmployeeByIdemployee() {
        return tblEmployeeByIdemployeeProperty().get();
    }

    public void setTblEmployeeByIdemployee(TblEmployee tblEmployeeByIdemployee) {
        tblEmployeeByIdemployeeProperty().set(tblEmployeeByIdemployee);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final StringProperty codeApproveProperty() {
        return this.codeApprove;
    }

    public String getCodeApprove() {
        return codeApproveProperty().get();
    }

    public void setCodeApprove(String codeApprove) {
        codeApproveProperty().set(codeApprove);
    }

    public final IntegerProperty iddataTypeProperty() {
        return this.iddataType;
    }

    public Integer getIddataType() {
        return iddataTypeProperty().get();
    }

    public void setIddataType(Integer iddataType) {
        iddataTypeProperty().set(iddataType);
    }

    public final LongProperty idjobRequiredProperty() {
        return this.idjobRequired;
    }

    public Long getIdjobRequired() {
        return idjobRequiredProperty().get();
    }

    public void setIdjobRequired(Long idjobRequired) {
        idjobRequiredProperty().set(idjobRequired);
    }

    public final LongProperty idjobRealProperty() {
        return this.idjobReal;
    }

    public Long getIdjobReal() {
        return idjobRealProperty().get();
    }

    public void setIdjobReal(Long idjobReal) {
        idjobRealProperty().set(idjobReal);
    }

    public final ObjectProperty<Date> approveDateProperty() {
        return this.approveDate;
    }

    public Date getApproveDate() {
        return approveDateProperty().get();
    }

    public void setApproveDate(Date approveDate) {
        approveDateProperty().set(approveDate);
    }

    public final StringProperty approveNoteProperty() {
        return this.approveNote;
    }

    public String getApproveNote() {
        return approveNoteProperty().get();
    }

    public void setApproveNote(String approveNote) {
        approveNoteProperty().set(approveNote);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

}
