package hotelfx.persistence.model;
// Generated Oct 18, 2018 4:38:29 PM by Hibernate Tools 4.3.1

import java.util.Date;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;

/**
 * TblBrokenItemDetailItemMutationHistory generated by hbm2java
 */
public class TblBrokenItemDetailItemMutationHistory implements java.io.Serializable {

    private final LongProperty idrelation;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblBrokenItemDetail> tblBrokenItemDetail;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblItemMutationHistory> tblItemMutationHistory;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    public TblBrokenItemDetailItemMutationHistory() {
        this.idrelation = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblBrokenItemDetail = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblItemMutationHistory = new SimpleObjectProperty<>();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

    }

    public TblBrokenItemDetailItemMutationHistory(long idrelation) {
        this();
        idrelationProperty().set(idrelation);
    }

    public TblBrokenItemDetailItemMutationHistory(long idrelation, RefRecordStatus refRecordStatus, TblBrokenItemDetail tblBrokenItemDetail, TblEmployee tblEmployeeByCreateBy, TblEmployee tblEmployeeByLastUpdateBy, TblItemMutationHistory tblItemMutationHistory, Date createDate, Date lastUpdateDate) {
        this();
        idrelationProperty().set(idrelation);
        refRecordStatusProperty().set(refRecordStatus);
        tblBrokenItemDetailProperty().set(tblBrokenItemDetail);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblItemMutationHistoryProperty().set(tblItemMutationHistory);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

    }

    public TblBrokenItemDetailItemMutationHistory(TblBrokenItemDetailItemMutationHistory tblBrokenItemDetailItemMutationHistory) {
        this();
        idrelationProperty().set(tblBrokenItemDetailItemMutationHistory.getIdrelation());
        refRecordStatusProperty().set(tblBrokenItemDetailItemMutationHistory.getRefRecordStatus());
        tblBrokenItemDetailProperty().set(tblBrokenItemDetailItemMutationHistory.getTblBrokenItemDetail());
        tblEmployeeByCreateByProperty().set(tblBrokenItemDetailItemMutationHistory.getTblEmployeeByCreateBy());
        tblEmployeeByLastUpdateByProperty().set(tblBrokenItemDetailItemMutationHistory.getTblEmployeeByLastUpdateBy());
        tblItemMutationHistoryProperty().set(tblBrokenItemDetailItemMutationHistory.getTblItemMutationHistory());
        createDateProperty().set(tblBrokenItemDetailItemMutationHistory.getCreateDate());
        lastUpdateDateProperty().set(tblBrokenItemDetailItemMutationHistory.getLastUpdateDate());

    }

    public final LongProperty idrelationProperty() {
        return this.idrelation;
    }

    public long getIdrelation() {
        return idrelationProperty().get();
    }

    public void setIdrelation(long idrelation) {
        idrelationProperty().set(idrelation);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblBrokenItemDetail> tblBrokenItemDetailProperty() {
        return this.tblBrokenItemDetail;
    }

    public TblBrokenItemDetail getTblBrokenItemDetail() {
        return tblBrokenItemDetailProperty().get();
    }

    public void setTblBrokenItemDetail(TblBrokenItemDetail tblBrokenItemDetail) {
        tblBrokenItemDetailProperty().set(tblBrokenItemDetail);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblItemMutationHistory> tblItemMutationHistoryProperty() {
        return this.tblItemMutationHistory;
    }

    public TblItemMutationHistory getTblItemMutationHistory() {
        return tblItemMutationHistoryProperty().get();
    }

    public void setTblItemMutationHistory(TblItemMutationHistory tblItemMutationHistory) {
        tblItemMutationHistoryProperty().set(tblItemMutationHistory);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

}
