package hotelfx.persistence.model;
// Generated Mar 7, 2018 11:35:25 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblBankEdc generated by hbm2java
 */
public class TblBankEdc implements java.io.Serializable {

    private final LongProperty idedc;
    private final ObjectProperty<RefEdcstatus> refEdcstatus;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblBank> tblBank;
    private final ObjectProperty<TblBankAccount> tblBankAccount;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final StringProperty codeEdc;
    private final StringProperty edcnumber;
    private final StringProperty edcname;
    private final StringProperty edcnote;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    private Set tblReservationPaymentWithBankCards;
    private Set tblBankEdcBankNetworkCards;

    public TblBankEdc() {
        this.idedc = new SimpleLongProperty();
        this.refEdcstatus = new SimpleObjectProperty<>();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblBank = new SimpleObjectProperty<>();
        this.tblBankAccount = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.codeEdc = new SimpleStringProperty();
        this.edcnumber = new SimpleStringProperty();
        this.edcname = new SimpleStringProperty();
        this.edcnote = new SimpleStringProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

        this.tblReservationPaymentWithBankCards = new HashSet(0);
        this.tblBankEdcBankNetworkCards = new HashSet(0);
    }

    public TblBankEdc(long idedc) {
        this();
        idedcProperty().set(idedc);
    }

    public TblBankEdc(long idedc, RefEdcstatus refEdcstatus, RefRecordStatus refRecordStatus, TblBank tblBank, TblBankAccount tblBankAccount, TblEmployee tblEmployeeByLastUpdateBy, TblEmployee tblEmployeeByCreateBy, String codeEdc, String edcnumber, String edcname, String edcnote, Date createDate, Date lastUpdateDate, Set tblReservationPaymentWithBankCards, Set tblBankEdcBankNetworkCards) {
        this();
        idedcProperty().set(idedc);
        refEdcstatusProperty().set(refEdcstatus);
        refRecordStatusProperty().set(refRecordStatus);
        tblBankProperty().set(tblBank);
        tblBankAccountProperty().set(tblBankAccount);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        codeEdcProperty().set(codeEdc);
        edcnumberProperty().set(edcnumber);
        edcnameProperty().set(edcname);
        edcnoteProperty().set(edcnote);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

        this.tblReservationPaymentWithBankCards = tblReservationPaymentWithBankCards;
        this.tblBankEdcBankNetworkCards = tblBankEdcBankNetworkCards;
    }

    public TblBankEdc(TblBankEdc tblBankEdc) {
        this();
        idedcProperty().set(tblBankEdc.getIdedc());
        refEdcstatusProperty().set(tblBankEdc.getRefEdcstatus());
        refRecordStatusProperty().set(tblBankEdc.getRefRecordStatus());
        tblBankProperty().set(tblBankEdc.getTblBank());
        tblBankAccountProperty().set(tblBankEdc.getTblBankAccount());
        tblEmployeeByLastUpdateByProperty().set(tblBankEdc.getTblEmployeeByLastUpdateBy());
        tblEmployeeByCreateByProperty().set(tblBankEdc.getTblEmployeeByCreateBy());
        codeEdcProperty().set(tblBankEdc.getCodeEdc());
        edcnumberProperty().set(tblBankEdc.getEdcnumber());
        edcnameProperty().set(tblBankEdc.getEdcname());
        edcnoteProperty().set(tblBankEdc.getEdcnote());
        createDateProperty().set(tblBankEdc.getCreateDate());
        lastUpdateDateProperty().set(tblBankEdc.getLastUpdateDate());

        this.tblReservationPaymentWithBankCards = tblBankEdc.getTblReservationPaymentWithBankCards();
        this.tblBankEdcBankNetworkCards = tblBankEdc.getTblBankEdcBankNetworkCards();
    }

    public final LongProperty idedcProperty() {
        return this.idedc;
    }

    public long getIdedc() {
        return idedcProperty().get();
    }

    public void setIdedc(long idedc) {
        idedcProperty().set(idedc);
    }

    public final ObjectProperty<RefEdcstatus> refEdcstatusProperty() {
        return this.refEdcstatus;
    }

    public RefEdcstatus getRefEdcstatus() {
        return refEdcstatusProperty().get();
    }

    public void setRefEdcstatus(RefEdcstatus refEdcstatus) {
        refEdcstatusProperty().set(refEdcstatus);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblBank> tblBankProperty() {
        return this.tblBank;
    }

    public TblBank getTblBank() {
        return tblBankProperty().get();
    }

    public void setTblBank(TblBank tblBank) {
        tblBankProperty().set(tblBank);
    }

    public final ObjectProperty<TblBankAccount> tblBankAccountProperty() {
        return this.tblBankAccount;
    }

    public TblBankAccount getTblBankAccount() {
        return tblBankAccountProperty().get();
    }

    public void setTblBankAccount(TblBankAccount tblBankAccount) {
        tblBankAccountProperty().set(tblBankAccount);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final StringProperty codeEdcProperty() {
        return this.codeEdc;
    }

    public String getCodeEdc() {
        return codeEdcProperty().get();
    }

    public void setCodeEdc(String codeEdc) {
        codeEdcProperty().set(codeEdc);
    }

    public final StringProperty edcnumberProperty() {
        return this.edcnumber;
    }

    public String getEdcnumber() {
        return edcnumberProperty().get();
    }

    public void setEdcnumber(String edcnumber) {
        edcnumberProperty().set(edcnumber);
    }

    public final StringProperty edcnameProperty() {
        return this.edcname;
    }

    public String getEdcname() {
        return edcnameProperty().get();
    }

    public void setEdcname(String edcname) {
        edcnameProperty().set(edcname);
    }

    public final StringProperty edcnoteProperty() {
        return this.edcnote;
    }

    public String getEdcnote() {
        return edcnoteProperty().get();
    }

    public void setEdcnote(String edcnote) {
        edcnoteProperty().set(edcnote);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

    public Set getTblReservationPaymentWithBankCards() {
        return this.tblReservationPaymentWithBankCards;
    }

    public void setTblReservationPaymentWithBankCards(Set tblReservationPaymentWithBankCards) {
        this.tblReservationPaymentWithBankCards = tblReservationPaymentWithBankCards;
    }

    public Set getTblBankEdcBankNetworkCards() {
        return this.tblBankEdcBankNetworkCards;
    }

    public void setTblBankEdcBankNetworkCards(Set tblBankEdcBankNetworkCards) {
        this.tblBankEdcBankNetworkCards = tblBankEdcBankNetworkCards;
    }
    
    @Override
    public String toString() {
        return getEdcname();
    }

}
