package hotelfx.persistence.model;
// Generated Oct 18, 2018 4:38:29 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblBrokenItem generated by hbm2java
 */
public class TblBrokenItem implements java.io.Serializable {

    private final LongProperty idbi;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblLocation> tblLocationByIdlocationDestination;
    private final ObjectProperty<TblLocation> tblLocationByIdlocationSource;
    private final StringProperty codeBi;
    private final ObjectProperty<Date> bidate;
    private final StringProperty binote;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    private Set tblBrokenItemDetails;

    public TblBrokenItem() {
        this.idbi = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblLocationByIdlocationDestination = new SimpleObjectProperty<>();
        this.tblLocationByIdlocationSource = new SimpleObjectProperty<>();
        this.codeBi = new SimpleStringProperty();
        this.bidate = new SimpleObjectProperty<>();
        this.binote = new SimpleStringProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

        this.tblBrokenItemDetails = new HashSet(0);
    }

    public TblBrokenItem(long idbi) {
        this();
        idbiProperty().set(idbi);
    }

    public TblBrokenItem(long idbi, RefRecordStatus refRecordStatus, TblEmployee tblEmployeeByLastUpdateBy, TblEmployee tblEmployeeByCreateBy, TblLocation tblLocationByIdlocationDestination, TblLocation tblLocationByIdlocationSource, String codeBi, Date bidate, String binote, Date createDate, Date lastUpdateDate, Set tblBrokenItemDetails) {
        this();
        idbiProperty().set(idbi);
        refRecordStatusProperty().set(refRecordStatus);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblLocationByIdlocationDestinationProperty().set(tblLocationByIdlocationDestination);
        tblLocationByIdlocationSourceProperty().set(tblLocationByIdlocationSource);
        codeBiProperty().set(codeBi);
        bidateProperty().set(bidate);
        binoteProperty().set(binote);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

        this.tblBrokenItemDetails = tblBrokenItemDetails;
    }

    public TblBrokenItem(TblBrokenItem tblBrokenItem) {
        this();
        idbiProperty().set(tblBrokenItem.getIdbi());
        refRecordStatusProperty().set(tblBrokenItem.getRefRecordStatus());
        tblEmployeeByLastUpdateByProperty().set(tblBrokenItem.getTblEmployeeByLastUpdateBy());
        tblEmployeeByCreateByProperty().set(tblBrokenItem.getTblEmployeeByCreateBy());
        tblLocationByIdlocationDestinationProperty().set(tblBrokenItem.getTblLocationByIdlocationDestination());
        tblLocationByIdlocationSourceProperty().set(tblBrokenItem.getTblLocationByIdlocationSource());
        codeBiProperty().set(tblBrokenItem.getCodeBi());
        bidateProperty().set(tblBrokenItem.getBidate());
        binoteProperty().set(tblBrokenItem.getBinote());
        createDateProperty().set(tblBrokenItem.getCreateDate());
        lastUpdateDateProperty().set(tblBrokenItem.getLastUpdateDate());

        this.tblBrokenItemDetails = tblBrokenItem.getTblBrokenItemDetails();
    }

    public final LongProperty idbiProperty() {
        return this.idbi;
    }

    public long getIdbi() {
        return idbiProperty().get();
    }

    public void setIdbi(long idbi) {
        idbiProperty().set(idbi);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblLocation> tblLocationByIdlocationDestinationProperty() {
        return this.tblLocationByIdlocationDestination;
    }

    public TblLocation getTblLocationByIdlocationDestination() {
        return tblLocationByIdlocationDestinationProperty().get();
    }

    public void setTblLocationByIdlocationDestination(TblLocation tblLocationByIdlocationDestination) {
        tblLocationByIdlocationDestinationProperty().set(tblLocationByIdlocationDestination);
    }

    public final ObjectProperty<TblLocation> tblLocationByIdlocationSourceProperty() {
        return this.tblLocationByIdlocationSource;
    }

    public TblLocation getTblLocationByIdlocationSource() {
        return tblLocationByIdlocationSourceProperty().get();
    }

    public void setTblLocationByIdlocationSource(TblLocation tblLocationByIdlocationSource) {
        tblLocationByIdlocationSourceProperty().set(tblLocationByIdlocationSource);
    }

    public final StringProperty codeBiProperty() {
        return this.codeBi;
    }

    public String getCodeBi() {
        return codeBiProperty().get();
    }

    public void setCodeBi(String codeBi) {
        codeBiProperty().set(codeBi);
    }

    public final ObjectProperty<Date> bidateProperty() {
        return this.bidate;
    }

    public Date getBidate() {
        return bidateProperty().get();
    }

    public void setBidate(Date bidate) {
        bidateProperty().set(bidate);
    }

    public final StringProperty binoteProperty() {
        return this.binote;
    }

    public String getBinote() {
        return binoteProperty().get();
    }

    public void setBinote(String binote) {
        binoteProperty().set(binote);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

    public Set getTblBrokenItemDetails() {
        return this.tblBrokenItemDetails;
    }

    public void setTblBrokenItemDetails(Set tblBrokenItemDetails) {
        this.tblBrokenItemDetails = tblBrokenItemDetails;
    }

}
