package hotelfx.persistence.model;
// Generated Oct 29, 2018 4:55:34 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblBankEventCard generated by hbm2java
 */
public class TblBankEventCard implements java.io.Serializable {

    private final LongProperty idevent;
    private final ObjectProperty<RefPercentageNominalType> refPercentageNominalType;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblBank> tblBank;
    private final ObjectProperty<TblBankCard> tblBankCard;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final StringProperty codeEvent;
    private final StringProperty eventName;
    private final ObjectProperty<Date> beginEventDate;
    private final ObjectProperty<Date> endEventDate;
    private final StringProperty eventNote;
    private final ObjectProperty<BigDecimal> minTransaction;
    private final ObjectProperty<BigDecimal> maxTransaction;
    private final ObjectProperty<BigDecimal> discountPercentage;
    private final ObjectProperty<BigDecimal> roomDiscountPercentage;
    private final ObjectProperty<BigDecimal> itemDiscountPercentage;
    private final ObjectProperty<BigDecimal> serviceDiscountPercentage;
    private final ObjectProperty<BigDecimal> discountPercentageHc;
    private final ObjectProperty<BigDecimal> discountPercentageBc;
    private final ObjectProperty<BigDecimal> discountNominal;
    private final ObjectProperty<BigDecimal> discountNominalHc;
    private final ObjectProperty<BigDecimal> discountNominalBc;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    private Set tblReservationRescheduleCanceleds;
    private Set tblReservationPaymentWithBankCards;
    private Set tblReservationAdditionalServices;
    private Set tblReservationRoomPriceDetails;
    private Set tblReservationAdditionalItems;

    public TblBankEventCard() {
        this.idevent = new SimpleLongProperty();
        this.refPercentageNominalType = new SimpleObjectProperty<>();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblBank = new SimpleObjectProperty<>();
        this.tblBankCard = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.codeEvent = new SimpleStringProperty();
        this.eventName = new SimpleStringProperty();
        this.beginEventDate = new SimpleObjectProperty<>();
        this.endEventDate = new SimpleObjectProperty<>();
        this.eventNote = new SimpleStringProperty();
        this.minTransaction = new SimpleObjectProperty<>();
        this.maxTransaction = new SimpleObjectProperty<>();
        this.discountPercentage = new SimpleObjectProperty<>();
        this.roomDiscountPercentage = new SimpleObjectProperty<>();
        this.itemDiscountPercentage = new SimpleObjectProperty<>();
        this.serviceDiscountPercentage = new SimpleObjectProperty<>();
        this.discountPercentageHc = new SimpleObjectProperty<>();
        this.discountPercentageBc = new SimpleObjectProperty<>();
        this.discountNominal = new SimpleObjectProperty<>();
        this.discountNominalHc = new SimpleObjectProperty<>();
        this.discountNominalBc = new SimpleObjectProperty<>();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

        this.tblReservationRescheduleCanceleds = new HashSet(0);
        this.tblReservationPaymentWithBankCards = new HashSet(0);
        this.tblReservationAdditionalServices = new HashSet(0);
        this.tblReservationRoomPriceDetails = new HashSet(0);
        this.tblReservationAdditionalItems = new HashSet(0);
    }

    public TblBankEventCard(long idevent) {
        this();
        ideventProperty().set(idevent);
    }

    public TblBankEventCard(long idevent, RefPercentageNominalType refPercentageNominalType, RefRecordStatus refRecordStatus, TblBank tblBank, TblBankCard tblBankCard, TblEmployee tblEmployeeByLastUpdateBy, TblEmployee tblEmployeeByCreateBy, String codeEvent, String eventName, Date beginEventDate, Date endEventDate, String eventNote, BigDecimal minTransaction, BigDecimal maxTransaction, BigDecimal discountPercentage, BigDecimal roomDiscountPercentage, BigDecimal itemDiscountPercentage, BigDecimal serviceDiscountPercentage, BigDecimal discountPercentageHc, BigDecimal discountPercentageBc, BigDecimal discountNominal, BigDecimal discountNominalHc, BigDecimal discountNominalBc, Date createDate, Date lastUpdateDate, Set tblReservationRescheduleCanceleds, Set tblReservationPaymentWithBankCards, Set tblReservationAdditionalServices, Set tblReservationRoomPriceDetails, Set tblReservationAdditionalItems) {
        this();
        ideventProperty().set(idevent);
        refPercentageNominalTypeProperty().set(refPercentageNominalType);
        refRecordStatusProperty().set(refRecordStatus);
        tblBankProperty().set(tblBank);
        tblBankCardProperty().set(tblBankCard);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        codeEventProperty().set(codeEvent);
        eventNameProperty().set(eventName);
        beginEventDateProperty().set(beginEventDate);
        endEventDateProperty().set(endEventDate);
        eventNoteProperty().set(eventNote);
        minTransactionProperty().set(minTransaction);
        maxTransactionProperty().set(maxTransaction);
        discountPercentageProperty().set(discountPercentage);
        roomDiscountPercentageProperty().set(roomDiscountPercentage);
        itemDiscountPercentageProperty().set(itemDiscountPercentage);
        serviceDiscountPercentageProperty().set(serviceDiscountPercentage);
        discountPercentageHcProperty().set(discountPercentageHc);
        discountPercentageBcProperty().set(discountPercentageBc);
        discountNominalProperty().set(discountNominal);
        discountNominalHcProperty().set(discountNominalHc);
        discountNominalBcProperty().set(discountNominalBc);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

        this.tblReservationRescheduleCanceleds = tblReservationRescheduleCanceleds;
        this.tblReservationPaymentWithBankCards = tblReservationPaymentWithBankCards;
        this.tblReservationAdditionalServices = tblReservationAdditionalServices;
        this.tblReservationRoomPriceDetails = tblReservationRoomPriceDetails;
        this.tblReservationAdditionalItems = tblReservationAdditionalItems;
    }

    public TblBankEventCard(TblBankEventCard tblBankEventCard) {
        this();
        ideventProperty().set(tblBankEventCard.getIdevent());
        refPercentageNominalTypeProperty().set(tblBankEventCard.getRefPercentageNominalType());
        refRecordStatusProperty().set(tblBankEventCard.getRefRecordStatus());
        tblBankProperty().set(tblBankEventCard.getTblBank());
        tblBankCardProperty().set(tblBankEventCard.getTblBankCard());
        tblEmployeeByLastUpdateByProperty().set(tblBankEventCard.getTblEmployeeByLastUpdateBy());
        tblEmployeeByCreateByProperty().set(tblBankEventCard.getTblEmployeeByCreateBy());
        codeEventProperty().set(tblBankEventCard.getCodeEvent());
        eventNameProperty().set(tblBankEventCard.getEventName());
        beginEventDateProperty().set(tblBankEventCard.getBeginEventDate());
        endEventDateProperty().set(tblBankEventCard.getEndEventDate());
        eventNoteProperty().set(tblBankEventCard.getEventNote());
        minTransactionProperty().set(tblBankEventCard.getMinTransaction());
        maxTransactionProperty().set(tblBankEventCard.getMaxTransaction());
        discountPercentageProperty().set(tblBankEventCard.getDiscountPercentage());
        roomDiscountPercentageProperty().set(tblBankEventCard.getRoomDiscountPercentage());
        itemDiscountPercentageProperty().set(tblBankEventCard.getItemDiscountPercentage());
        serviceDiscountPercentageProperty().set(tblBankEventCard.getServiceDiscountPercentage());
        discountPercentageHcProperty().set(tblBankEventCard.getDiscountPercentageHc());
        discountPercentageBcProperty().set(tblBankEventCard.getDiscountPercentageBc());
        discountNominalProperty().set(tblBankEventCard.getDiscountNominal());
        discountNominalHcProperty().set(tblBankEventCard.getDiscountNominalHc());
        discountNominalBcProperty().set(tblBankEventCard.getDiscountNominalBc());
        createDateProperty().set(tblBankEventCard.getCreateDate());
        lastUpdateDateProperty().set(tblBankEventCard.getLastUpdateDate());

        this.tblReservationRescheduleCanceleds = tblBankEventCard.getTblReservationRescheduleCanceleds();
        this.tblReservationPaymentWithBankCards = tblBankEventCard.getTblReservationPaymentWithBankCards();
        this.tblReservationAdditionalServices = tblBankEventCard.getTblReservationAdditionalServices();
        this.tblReservationRoomPriceDetails = tblBankEventCard.getTblReservationRoomPriceDetails();
        this.tblReservationAdditionalItems = tblBankEventCard.getTblReservationAdditionalItems();
    }

    public final LongProperty ideventProperty() {
        return this.idevent;
    }

    public long getIdevent() {
        return ideventProperty().get();
    }

    public void setIdevent(long idevent) {
        ideventProperty().set(idevent);
    }

    public final ObjectProperty<RefPercentageNominalType> refPercentageNominalTypeProperty() {
        return this.refPercentageNominalType;
    }

    public RefPercentageNominalType getRefPercentageNominalType() {
        return refPercentageNominalTypeProperty().get();
    }

    public void setRefPercentageNominalType(RefPercentageNominalType refPercentageNominalType) {
        refPercentageNominalTypeProperty().set(refPercentageNominalType);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblBank> tblBankProperty() {
        return this.tblBank;
    }

    public TblBank getTblBank() {
        return tblBankProperty().get();
    }

    public void setTblBank(TblBank tblBank) {
        tblBankProperty().set(tblBank);
    }

    public final ObjectProperty<TblBankCard> tblBankCardProperty() {
        return this.tblBankCard;
    }

    public TblBankCard getTblBankCard() {
        return tblBankCardProperty().get();
    }

    public void setTblBankCard(TblBankCard tblBankCard) {
        tblBankCardProperty().set(tblBankCard);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final StringProperty codeEventProperty() {
        return this.codeEvent;
    }

    public String getCodeEvent() {
        return codeEventProperty().get();
    }

    public void setCodeEvent(String codeEvent) {
        codeEventProperty().set(codeEvent);
    }

    public final StringProperty eventNameProperty() {
        return this.eventName;
    }

    public String getEventName() {
        return eventNameProperty().get();
    }

    public void setEventName(String eventName) {
        eventNameProperty().set(eventName);
    }

    public final ObjectProperty<Date> beginEventDateProperty() {
        return this.beginEventDate;
    }

    public Date getBeginEventDate() {
        return beginEventDateProperty().get();
    }

    public void setBeginEventDate(Date beginEventDate) {
        beginEventDateProperty().set(beginEventDate);
    }

    public final ObjectProperty<Date> endEventDateProperty() {
        return this.endEventDate;
    }

    public Date getEndEventDate() {
        return endEventDateProperty().get();
    }

    public void setEndEventDate(Date endEventDate) {
        endEventDateProperty().set(endEventDate);
    }

    public final StringProperty eventNoteProperty() {
        return this.eventNote;
    }

    public String getEventNote() {
        return eventNoteProperty().get();
    }

    public void setEventNote(String eventNote) {
        eventNoteProperty().set(eventNote);
    }

    public final ObjectProperty<BigDecimal> minTransactionProperty() {
        return this.minTransaction;
    }

    public BigDecimal getMinTransaction() {
        return minTransactionProperty().get();
    }

    public void setMinTransaction(BigDecimal minTransaction) {
        minTransactionProperty().set(minTransaction);
    }

    public final ObjectProperty<BigDecimal> maxTransactionProperty() {
        return this.maxTransaction;
    }

    public BigDecimal getMaxTransaction() {
        return maxTransactionProperty().get();
    }

    public void setMaxTransaction(BigDecimal maxTransaction) {
        maxTransactionProperty().set(maxTransaction);
    }

    public final ObjectProperty<BigDecimal> discountPercentageProperty() {
        return this.discountPercentage;
    }

    public BigDecimal getDiscountPercentage() {
        return discountPercentageProperty().get();
    }

    public void setDiscountPercentage(BigDecimal discountPercentage) {
        discountPercentageProperty().set(discountPercentage);
    }

    public final ObjectProperty<BigDecimal> roomDiscountPercentageProperty() {
        return this.roomDiscountPercentage;
    }

    public BigDecimal getRoomDiscountPercentage() {
        return roomDiscountPercentageProperty().get();
    }

    public void setRoomDiscountPercentage(BigDecimal roomDiscountPercentage) {
        roomDiscountPercentageProperty().set(roomDiscountPercentage);
    }

    public final ObjectProperty<BigDecimal> itemDiscountPercentageProperty() {
        return this.itemDiscountPercentage;
    }

    public BigDecimal getItemDiscountPercentage() {
        return itemDiscountPercentageProperty().get();
    }

    public void setItemDiscountPercentage(BigDecimal itemDiscountPercentage) {
        itemDiscountPercentageProperty().set(itemDiscountPercentage);
    }

    public final ObjectProperty<BigDecimal> serviceDiscountPercentageProperty() {
        return this.serviceDiscountPercentage;
    }

    public BigDecimal getServiceDiscountPercentage() {
        return serviceDiscountPercentageProperty().get();
    }

    public void setServiceDiscountPercentage(BigDecimal serviceDiscountPercentage) {
        serviceDiscountPercentageProperty().set(serviceDiscountPercentage);
    }

    public final ObjectProperty<BigDecimal> discountPercentageHcProperty() {
        return this.discountPercentageHc;
    }

    public BigDecimal getDiscountPercentageHc() {
        return discountPercentageHcProperty().get();
    }

    public void setDiscountPercentageHc(BigDecimal discountPercentageHc) {
        discountPercentageHcProperty().set(discountPercentageHc);
    }

    public final ObjectProperty<BigDecimal> discountPercentageBcProperty() {
        return this.discountPercentageBc;
    }

    public BigDecimal getDiscountPercentageBc() {
        return discountPercentageBcProperty().get();
    }

    public void setDiscountPercentageBc(BigDecimal discountPercentageBc) {
        discountPercentageBcProperty().set(discountPercentageBc);
    }

    public final ObjectProperty<BigDecimal> discountNominalProperty() {
        return this.discountNominal;
    }

    public BigDecimal getDiscountNominal() {
        return discountNominalProperty().get();
    }

    public void setDiscountNominal(BigDecimal discountNominal) {
        discountNominalProperty().set(discountNominal);
    }

    public final ObjectProperty<BigDecimal> discountNominalHcProperty() {
        return this.discountNominalHc;
    }

    public BigDecimal getDiscountNominalHc() {
        return discountNominalHcProperty().get();
    }

    public void setDiscountNominalHc(BigDecimal discountNominalHc) {
        discountNominalHcProperty().set(discountNominalHc);
    }

    public final ObjectProperty<BigDecimal> discountNominalBcProperty() {
        return this.discountNominalBc;
    }

    public BigDecimal getDiscountNominalBc() {
        return discountNominalBcProperty().get();
    }

    public void setDiscountNominalBc(BigDecimal discountNominalBc) {
        discountNominalBcProperty().set(discountNominalBc);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

    public Set getTblReservationRescheduleCanceleds() {
        return this.tblReservationRescheduleCanceleds;
    }

    public void setTblReservationRescheduleCanceleds(Set tblReservationRescheduleCanceleds) {
        this.tblReservationRescheduleCanceleds = tblReservationRescheduleCanceleds;
    }

    public Set getTblReservationPaymentWithBankCards() {
        return this.tblReservationPaymentWithBankCards;
    }

    public void setTblReservationPaymentWithBankCards(Set tblReservationPaymentWithBankCards) {
        this.tblReservationPaymentWithBankCards = tblReservationPaymentWithBankCards;
    }

    public Set getTblReservationAdditionalServices() {
        return this.tblReservationAdditionalServices;
    }

    public void setTblReservationAdditionalServices(Set tblReservationAdditionalServices) {
        this.tblReservationAdditionalServices = tblReservationAdditionalServices;
    }

    public Set getTblReservationRoomPriceDetails() {
        return this.tblReservationRoomPriceDetails;
    }

    public void setTblReservationRoomPriceDetails(Set tblReservationRoomPriceDetails) {
        this.tblReservationRoomPriceDetails = tblReservationRoomPriceDetails;
    }

    public Set getTblReservationAdditionalItems() {
        return this.tblReservationAdditionalItems;
    }

    public void setTblReservationAdditionalItems(Set tblReservationAdditionalItems) {
        this.tblReservationAdditionalItems = tblReservationAdditionalItems;
    }

    @Override
    public String toString() {
        return getEventName();
    }
    
}
