package hotelfx.persistence.model;
// Generated Aug 21, 2017 1:49:32 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblBankNetworkCard generated by hbm2java
 */
public class TblBankNetworkCard implements java.io.Serializable {

    private final LongProperty idnetworkCard;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final StringProperty codeNetworkCard;
    private final StringProperty networkCardName;
    private final StringProperty networkCardNote;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    private Set tblBankEdcBankNetworkCards;
    private Set tblReservationPaymentWithBankCards;

    public TblBankNetworkCard() {
        this.idnetworkCard = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.codeNetworkCard = new SimpleStringProperty();
        this.networkCardName = new SimpleStringProperty();
        this.networkCardNote = new SimpleStringProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

        this.tblBankEdcBankNetworkCards = new HashSet(0);
        this.tblReservationPaymentWithBankCards = new HashSet(0);
    }

    public TblBankNetworkCard(long idnetworkCard) {
        this();
        idnetworkCardProperty().set(idnetworkCard);
    }

    public TblBankNetworkCard(long idnetworkCard, RefRecordStatus refRecordStatus, TblEmployee tblEmployeeByCreateBy, TblEmployee tblEmployeeByLastUpdateBy, String codeNetworkCard, String networkCardName, String networkCardNote, Date createDate, Date lastUpdateDate, Set tblBankEdcBankNetworkCards, Set tblReservationPaymentWithBankCards) {
        this();
        idnetworkCardProperty().set(idnetworkCard);
        refRecordStatusProperty().set(refRecordStatus);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        codeNetworkCardProperty().set(codeNetworkCard);
        networkCardNameProperty().set(networkCardName);
        networkCardNoteProperty().set(networkCardNote);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

        this.tblBankEdcBankNetworkCards = tblBankEdcBankNetworkCards;
        this.tblReservationPaymentWithBankCards = tblReservationPaymentWithBankCards;
    }

    public TblBankNetworkCard(TblBankNetworkCard tblBankNetworkCard) {
        this();
        idnetworkCardProperty().set(tblBankNetworkCard.getIdnetworkCard());
        refRecordStatusProperty().set(tblBankNetworkCard.getRefRecordStatus());
        tblEmployeeByCreateByProperty().set(tblBankNetworkCard.getTblEmployeeByCreateBy());
        tblEmployeeByLastUpdateByProperty().set(tblBankNetworkCard.getTblEmployeeByLastUpdateBy());
        codeNetworkCardProperty().set(tblBankNetworkCard.getCodeNetworkCard());
        networkCardNameProperty().set(tblBankNetworkCard.getNetworkCardName());
        networkCardNoteProperty().set(tblBankNetworkCard.getNetworkCardNote());
        createDateProperty().set(tblBankNetworkCard.getCreateDate());
        lastUpdateDateProperty().set(tblBankNetworkCard.getLastUpdateDate());

        this.tblBankEdcBankNetworkCards = tblBankNetworkCard.getTblBankEdcBankNetworkCards();
        this.tblReservationPaymentWithBankCards = tblBankNetworkCard.getTblReservationPaymentWithBankCards();
    }

    public final LongProperty idnetworkCardProperty() {
        return this.idnetworkCard;
    }

    public long getIdnetworkCard() {
        return idnetworkCardProperty().get();
    }

    public void setIdnetworkCard(long idnetworkCard) {
        idnetworkCardProperty().set(idnetworkCard);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final StringProperty codeNetworkCardProperty() {
        return this.codeNetworkCard;
    }

    public String getCodeNetworkCard() {
        return codeNetworkCardProperty().get();
    }

    public void setCodeNetworkCard(String codeNetworkCard) {
        codeNetworkCardProperty().set(codeNetworkCard);
    }

    public final StringProperty networkCardNameProperty() {
        return this.networkCardName;
    }

    public String getNetworkCardName() {
        return networkCardNameProperty().get();
    }

    public void setNetworkCardName(String networkCardName) {
        networkCardNameProperty().set(networkCardName);
    }

    public final StringProperty networkCardNoteProperty() {
        return this.networkCardNote;
    }

    public String getNetworkCardNote() {
        return networkCardNoteProperty().get();
    }

    public void setNetworkCardNote(String networkCardNote) {
        networkCardNoteProperty().set(networkCardNote);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

    public Set getTblBankEdcBankNetworkCards() {
        return this.tblBankEdcBankNetworkCards;
    }

    public void setTblBankEdcBankNetworkCards(Set tblBankEdcBankNetworkCards) {
        this.tblBankEdcBankNetworkCards = tblBankEdcBankNetworkCards;
    }

    public Set getTblReservationPaymentWithBankCards() {
        return this.tblReservationPaymentWithBankCards;
    }

    public void setTblReservationPaymentWithBankCards(Set tblReservationPaymentWithBankCards) {
        this.tblReservationPaymentWithBankCards = tblReservationPaymentWithBankCards;
    }

    @Override
    public String toString() {
        return getNetworkCardName();
    }

}
