package hotelfx.persistence.model;
// Generated Aug 21, 2017 1:49:32 PM by Hibernate Tools 4.3.1

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TblBuilding generated by hbm2java
 */
public class TblBuilding implements java.io.Serializable {

    private final LongProperty idbuilding;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final StringProperty codeBuilding;
    private final StringProperty buildingName;
    private final StringProperty buildingNote;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    private Set tblLocations;

    public TblBuilding() {
        this.idbuilding = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.codeBuilding = new SimpleStringProperty();
        this.buildingName = new SimpleStringProperty();
        this.buildingNote = new SimpleStringProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

        this.tblLocations = new HashSet(0);
    }

    public TblBuilding(long idbuilding) {
        this();
        idbuildingProperty().set(idbuilding);
    }

    public TblBuilding(long idbuilding, RefRecordStatus refRecordStatus, TblEmployee tblEmployeeByLastUpdateBy, TblEmployee tblEmployeeByCreateBy, String codeBuilding, String buildingName, String buildingNote, Date createDate, Date lastUpdateDate, Set tblLocations) {
        this();
        idbuildingProperty().set(idbuilding);
        refRecordStatusProperty().set(refRecordStatus);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        codeBuildingProperty().set(codeBuilding);
        buildingNameProperty().set(buildingName);
        buildingNoteProperty().set(buildingNote);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

        this.tblLocations = tblLocations;
    }

    public TblBuilding(TblBuilding tblBuilding) {
        this();
        idbuildingProperty().set(tblBuilding.getIdbuilding());
        refRecordStatusProperty().set(tblBuilding.getRefRecordStatus());
        tblEmployeeByLastUpdateByProperty().set(tblBuilding.getTblEmployeeByLastUpdateBy());
        tblEmployeeByCreateByProperty().set(tblBuilding.getTblEmployeeByCreateBy());
        codeBuildingProperty().set(tblBuilding.getCodeBuilding());
        buildingNameProperty().set(tblBuilding.getBuildingName());
        buildingNoteProperty().set(tblBuilding.getBuildingNote());
        createDateProperty().set(tblBuilding.getCreateDate());
        lastUpdateDateProperty().set(tblBuilding.getLastUpdateDate());

        this.tblLocations = tblBuilding.getTblLocations();
    }

    public final LongProperty idbuildingProperty() {
        return this.idbuilding;
    }

    public long getIdbuilding() {
        return idbuildingProperty().get();
    }

    public void setIdbuilding(long idbuilding) {
        idbuildingProperty().set(idbuilding);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final StringProperty codeBuildingProperty() {
        return this.codeBuilding;
    }

    public String getCodeBuilding() {
        return codeBuildingProperty().get();
    }

    public void setCodeBuilding(String codeBuilding) {
        codeBuildingProperty().set(codeBuilding);
    }

    public final StringProperty buildingNameProperty() {
        return this.buildingName;
    }

    public String getBuildingName() {
        return buildingNameProperty().get();
    }

    public void setBuildingName(String buildingName) {
        buildingNameProperty().set(buildingName);
    }

    public final StringProperty buildingNoteProperty() {
        return this.buildingNote;
    }

    public String getBuildingNote() {
        return buildingNoteProperty().get();
    }

    public void setBuildingNote(String buildingNote) {
        buildingNoteProperty().set(buildingNote);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

    public Set getTblLocations() {
        return this.tblLocations;
    }

    public void setTblLocations(Set tblLocations) {
        this.tblLocations = tblLocations;
    }

    @Override
    public String toString() {
        return buildingNameProperty().get();
    }

}
