package hotelfx.persistence.model;
// Generated Oct 24, 2018 12:59:27 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblBankAccount generated by hbm2java
 */
public class TblBankAccount implements java.io.Serializable {

    private final LongProperty idbankAccount;
    private final ObjectProperty<RefBankAccountStatus> refBankAccountStatus;
    private final ObjectProperty<RefBankAccountType> refBankAccountType;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblBank> tblBank;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final StringProperty codeBankAccount;
    private final StringProperty bankAccountHolderName;
    private final StringProperty bankAccountNote;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    private Set tblHotelExpenseTransactionsForIdbankAccountReceiver;
    private Set tblReservationPaymentWithCekGirosForReceiverBankAccount;
    private Set tblReservationPaymentWithBankCards;
    private Set tblSupplierBankAccounts;
    private Set tblHotelFinanceTransactionWithTransfersForReceiverBankAccount;
    private Set tblEmployeeBankAccounts;
    private Set tblReservationPaymentWithGuaranteePaymentsForSenderBankAccount;
    private Set tblBankEdcs;
    private Set tblReservationPaymentWithTransfersForSenderBankAccount;
    private Set tblHotelFinanceTransactionWithCekGirosForSenderBankAccount;
    private Set tblCompanyBalanceBankAccounts;
    private Set logCompanyBalanceCashFlowsForIdreceiverCbbankAccount;
    private Set tblHotelExpenseTransactionsForIdbankAccount;
    private Set tblPartnerBankAccounts;
    private Set tblReservationPaymentWithCekGirosForSenderBankAccount;
    private Set tblRestoBankAccounts;
    private Set tblReservationPaymentWithTransfersForReceiverBankAccount;
    private Set tblHotelFinanceTransactionWithCekGirosForReceiverBankAccount;
    private Set tblHotelFinanceTransactionWithTransfersForSenderBankAccount;
    private Set tblReservationPaymentWithGuaranteePaymentsForReceiverBankAccount;
    private Set logCompanyBalanceCashFlowsForIdsenderCbbankAccount;
    private Set tblCustomerBankAccounts;

    public TblBankAccount() {
        this.idbankAccount = new SimpleLongProperty();
        this.refBankAccountStatus = new SimpleObjectProperty<>();
        this.refBankAccountType = new SimpleObjectProperty<>();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblBank = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.codeBankAccount = new SimpleStringProperty();
        this.bankAccountHolderName = new SimpleStringProperty();
        this.bankAccountNote = new SimpleStringProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

        this.tblHotelExpenseTransactionsForIdbankAccountReceiver = new HashSet(0);
        this.tblReservationPaymentWithCekGirosForReceiverBankAccount = new HashSet(0);
        this.tblReservationPaymentWithBankCards = new HashSet(0);
        this.tblSupplierBankAccounts = new HashSet(0);
        this.tblHotelFinanceTransactionWithTransfersForReceiverBankAccount = new HashSet(0);
        this.tblEmployeeBankAccounts = new HashSet(0);
        this.tblReservationPaymentWithGuaranteePaymentsForSenderBankAccount = new HashSet(0);
        this.tblBankEdcs = new HashSet(0);
        this.tblReservationPaymentWithTransfersForSenderBankAccount = new HashSet(0);
        this.tblHotelFinanceTransactionWithCekGirosForSenderBankAccount = new HashSet(0);
        this.tblCompanyBalanceBankAccounts = new HashSet(0);
        this.logCompanyBalanceCashFlowsForIdreceiverCbbankAccount = new HashSet(0);
        this.tblHotelExpenseTransactionsForIdbankAccount = new HashSet(0);
        this.tblPartnerBankAccounts = new HashSet(0);
        this.tblReservationPaymentWithCekGirosForSenderBankAccount = new HashSet(0);
        this.tblRestoBankAccounts = new HashSet(0);
        this.tblReservationPaymentWithTransfersForReceiverBankAccount = new HashSet(0);
        this.tblHotelFinanceTransactionWithCekGirosForReceiverBankAccount = new HashSet(0);
        this.tblHotelFinanceTransactionWithTransfersForSenderBankAccount = new HashSet(0);
        this.tblReservationPaymentWithGuaranteePaymentsForReceiverBankAccount = new HashSet(0);
        this.logCompanyBalanceCashFlowsForIdsenderCbbankAccount = new HashSet(0);
        this.tblCustomerBankAccounts = new HashSet(0);
    }

    public TblBankAccount(long idbankAccount) {
        this();
        idbankAccountProperty().set(idbankAccount);
    }

    public TblBankAccount(long idbankAccount, RefBankAccountStatus refBankAccountStatus, RefBankAccountType refBankAccountType, RefRecordStatus refRecordStatus, TblBank tblBank, TblEmployee tblEmployeeByLastUpdateBy, TblEmployee tblEmployeeByCreateBy, String codeBankAccount, String bankAccountHolderName, String bankAccountNote, Date createDate, Date lastUpdateDate, Set tblHotelExpenseTransactionsForIdbankAccountReceiver, Set tblReservationPaymentWithCekGirosForReceiverBankAccount, Set tblReservationPaymentWithBankCards, Set tblSupplierBankAccounts, Set tblHotelFinanceTransactionWithTransfersForReceiverBankAccount, Set tblEmployeeBankAccounts, Set tblReservationPaymentWithGuaranteePaymentsForSenderBankAccount, Set tblBankEdcs, Set tblReservationPaymentWithTransfersForSenderBankAccount, Set tblHotelFinanceTransactionWithCekGirosForSenderBankAccount, Set tblCompanyBalanceBankAccounts, Set logCompanyBalanceCashFlowsForIdreceiverCbbankAccount, Set tblHotelExpenseTransactionsForIdbankAccount, Set tblPartnerBankAccounts, Set tblReservationPaymentWithCekGirosForSenderBankAccount, Set tblRestoBankAccounts, Set tblReservationPaymentWithTransfersForReceiverBankAccount, Set tblHotelFinanceTransactionWithCekGirosForReceiverBankAccount, Set tblHotelFinanceTransactionWithTransfersForSenderBankAccount, Set tblReservationPaymentWithGuaranteePaymentsForReceiverBankAccount, Set logCompanyBalanceCashFlowsForIdsenderCbbankAccount, Set tblCustomerBankAccounts) {
        this();
        idbankAccountProperty().set(idbankAccount);
        refBankAccountStatusProperty().set(refBankAccountStatus);
        refBankAccountTypeProperty().set(refBankAccountType);
        refRecordStatusProperty().set(refRecordStatus);
        tblBankProperty().set(tblBank);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        codeBankAccountProperty().set(codeBankAccount);
        bankAccountHolderNameProperty().set(bankAccountHolderName);
        bankAccountNoteProperty().set(bankAccountNote);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

        this.tblHotelExpenseTransactionsForIdbankAccountReceiver = tblHotelExpenseTransactionsForIdbankAccountReceiver;
        this.tblReservationPaymentWithCekGirosForReceiverBankAccount = tblReservationPaymentWithCekGirosForReceiverBankAccount;
        this.tblReservationPaymentWithBankCards = tblReservationPaymentWithBankCards;
        this.tblSupplierBankAccounts = tblSupplierBankAccounts;
        this.tblHotelFinanceTransactionWithTransfersForReceiverBankAccount = tblHotelFinanceTransactionWithTransfersForReceiverBankAccount;
        this.tblEmployeeBankAccounts = tblEmployeeBankAccounts;
        this.tblReservationPaymentWithGuaranteePaymentsForSenderBankAccount = tblReservationPaymentWithGuaranteePaymentsForSenderBankAccount;
        this.tblBankEdcs = tblBankEdcs;
        this.tblReservationPaymentWithTransfersForSenderBankAccount = tblReservationPaymentWithTransfersForSenderBankAccount;
        this.tblHotelFinanceTransactionWithCekGirosForSenderBankAccount = tblHotelFinanceTransactionWithCekGirosForSenderBankAccount;
        this.tblCompanyBalanceBankAccounts = tblCompanyBalanceBankAccounts;
        this.logCompanyBalanceCashFlowsForIdreceiverCbbankAccount = logCompanyBalanceCashFlowsForIdreceiverCbbankAccount;
        this.tblHotelExpenseTransactionsForIdbankAccount = tblHotelExpenseTransactionsForIdbankAccount;
        this.tblPartnerBankAccounts = tblPartnerBankAccounts;
        this.tblReservationPaymentWithCekGirosForSenderBankAccount = tblReservationPaymentWithCekGirosForSenderBankAccount;
        this.tblRestoBankAccounts = tblRestoBankAccounts;
        this.tblReservationPaymentWithTransfersForReceiverBankAccount = tblReservationPaymentWithTransfersForReceiverBankAccount;
        this.tblHotelFinanceTransactionWithCekGirosForReceiverBankAccount = tblHotelFinanceTransactionWithCekGirosForReceiverBankAccount;
        this.tblHotelFinanceTransactionWithTransfersForSenderBankAccount = tblHotelFinanceTransactionWithTransfersForSenderBankAccount;
        this.tblReservationPaymentWithGuaranteePaymentsForReceiverBankAccount = tblReservationPaymentWithGuaranteePaymentsForReceiverBankAccount;
        this.logCompanyBalanceCashFlowsForIdsenderCbbankAccount = logCompanyBalanceCashFlowsForIdsenderCbbankAccount;
        this.tblCustomerBankAccounts = tblCustomerBankAccounts;
    }

    public TblBankAccount(TblBankAccount tblBankAccount) {
        this();
        idbankAccountProperty().set(tblBankAccount.getIdbankAccount());
        refBankAccountStatusProperty().set(tblBankAccount.getRefBankAccountStatus());
        refBankAccountTypeProperty().set(tblBankAccount.getRefBankAccountType());
        refRecordStatusProperty().set(tblBankAccount.getRefRecordStatus());
        tblBankProperty().set(tblBankAccount.getTblBank());
        tblEmployeeByLastUpdateByProperty().set(tblBankAccount.getTblEmployeeByLastUpdateBy());
        tblEmployeeByCreateByProperty().set(tblBankAccount.getTblEmployeeByCreateBy());
        codeBankAccountProperty().set(tblBankAccount.getCodeBankAccount());
        bankAccountHolderNameProperty().set(tblBankAccount.getBankAccountHolderName());
        bankAccountNoteProperty().set(tblBankAccount.getBankAccountNote());
        createDateProperty().set(tblBankAccount.getCreateDate());
        lastUpdateDateProperty().set(tblBankAccount.getLastUpdateDate());

        this.tblHotelExpenseTransactionsForIdbankAccountReceiver = tblBankAccount.getTblHotelExpenseTransactionsForIdbankAccountReceiver();
        this.tblReservationPaymentWithCekGirosForReceiverBankAccount = tblBankAccount.getTblReservationPaymentWithCekGirosForReceiverBankAccount();
        this.tblReservationPaymentWithBankCards = tblBankAccount.getTblReservationPaymentWithBankCards();
        this.tblSupplierBankAccounts = tblBankAccount.getTblSupplierBankAccounts();
        this.tblHotelFinanceTransactionWithTransfersForReceiverBankAccount = tblBankAccount.getTblHotelFinanceTransactionWithTransfersForReceiverBankAccount();
        this.tblEmployeeBankAccounts = tblBankAccount.getTblEmployeeBankAccounts();
        this.tblReservationPaymentWithGuaranteePaymentsForSenderBankAccount = tblBankAccount.getTblReservationPaymentWithGuaranteePaymentsForSenderBankAccount();
        this.tblBankEdcs = tblBankAccount.getTblBankEdcs();
        this.tblReservationPaymentWithTransfersForSenderBankAccount = tblBankAccount.getTblReservationPaymentWithTransfersForSenderBankAccount();
        this.tblHotelFinanceTransactionWithCekGirosForSenderBankAccount = tblBankAccount.getTblHotelFinanceTransactionWithCekGirosForSenderBankAccount();
        this.tblCompanyBalanceBankAccounts = tblBankAccount.getTblCompanyBalanceBankAccounts();
        this.logCompanyBalanceCashFlowsForIdreceiverCbbankAccount = tblBankAccount.getLogCompanyBalanceCashFlowsForIdreceiverCbbankAccount();
        this.tblHotelExpenseTransactionsForIdbankAccount = tblBankAccount.getTblHotelExpenseTransactionsForIdbankAccount();
        this.tblPartnerBankAccounts = tblBankAccount.getTblPartnerBankAccounts();
        this.tblReservationPaymentWithCekGirosForSenderBankAccount = tblBankAccount.getTblReservationPaymentWithCekGirosForSenderBankAccount();
        this.tblRestoBankAccounts = tblBankAccount.getTblRestoBankAccounts();
        this.tblReservationPaymentWithTransfersForReceiverBankAccount = tblBankAccount.getTblReservationPaymentWithTransfersForReceiverBankAccount();
        this.tblHotelFinanceTransactionWithCekGirosForReceiverBankAccount = tblBankAccount.getTblHotelFinanceTransactionWithCekGirosForReceiverBankAccount();
        this.tblHotelFinanceTransactionWithTransfersForSenderBankAccount = tblBankAccount.getTblHotelFinanceTransactionWithTransfersForSenderBankAccount();
        this.tblReservationPaymentWithGuaranteePaymentsForReceiverBankAccount = tblBankAccount.getTblReservationPaymentWithGuaranteePaymentsForReceiverBankAccount();
        this.logCompanyBalanceCashFlowsForIdsenderCbbankAccount = tblBankAccount.getLogCompanyBalanceCashFlowsForIdsenderCbbankAccount();
        this.tblCustomerBankAccounts = tblBankAccount.getTblCustomerBankAccounts();
    }

    public final LongProperty idbankAccountProperty() {
        return this.idbankAccount;
    }

    public long getIdbankAccount() {
        return idbankAccountProperty().get();
    }

    public void setIdbankAccount(long idbankAccount) {
        idbankAccountProperty().set(idbankAccount);
    }

    public final ObjectProperty<RefBankAccountStatus> refBankAccountStatusProperty() {
        return this.refBankAccountStatus;
    }

    public RefBankAccountStatus getRefBankAccountStatus() {
        return refBankAccountStatusProperty().get();
    }

    public void setRefBankAccountStatus(RefBankAccountStatus refBankAccountStatus) {
        refBankAccountStatusProperty().set(refBankAccountStatus);
    }

    public final ObjectProperty<RefBankAccountType> refBankAccountTypeProperty() {
        return this.refBankAccountType;
    }

    public RefBankAccountType getRefBankAccountType() {
        return refBankAccountTypeProperty().get();
    }

    public void setRefBankAccountType(RefBankAccountType refBankAccountType) {
        refBankAccountTypeProperty().set(refBankAccountType);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblBank> tblBankProperty() {
        return this.tblBank;
    }

    public TblBank getTblBank() {
        return tblBankProperty().get();
    }

    public void setTblBank(TblBank tblBank) {
        tblBankProperty().set(tblBank);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final StringProperty codeBankAccountProperty() {
        return this.codeBankAccount;
    }

    public String getCodeBankAccount() {
        return codeBankAccountProperty().get();
    }

    public void setCodeBankAccount(String codeBankAccount) {
        codeBankAccountProperty().set(codeBankAccount);
    }

    public final StringProperty bankAccountHolderNameProperty() {
        return this.bankAccountHolderName;
    }

    public String getBankAccountHolderName() {
        return bankAccountHolderNameProperty().get();
    }

    public void setBankAccountHolderName(String bankAccountHolderName) {
        bankAccountHolderNameProperty().set(bankAccountHolderName);
    }

    public final StringProperty bankAccountNoteProperty() {
        return this.bankAccountNote;
    }

    public String getBankAccountNote() {
        return bankAccountNoteProperty().get();
    }

    public void setBankAccountNote(String bankAccountNote) {
        bankAccountNoteProperty().set(bankAccountNote);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

    public Set getTblHotelExpenseTransactionsForIdbankAccountReceiver() {
        return this.tblHotelExpenseTransactionsForIdbankAccountReceiver;
    }

    public void setTblHotelExpenseTransactionsForIdbankAccountReceiver(Set tblHotelExpenseTransactionsForIdbankAccountReceiver) {
        this.tblHotelExpenseTransactionsForIdbankAccountReceiver = tblHotelExpenseTransactionsForIdbankAccountReceiver;
    }

    public Set getTblReservationPaymentWithCekGirosForReceiverBankAccount() {
        return this.tblReservationPaymentWithCekGirosForReceiverBankAccount;
    }

    public void setTblReservationPaymentWithCekGirosForReceiverBankAccount(Set tblReservationPaymentWithCekGirosForReceiverBankAccount) {
        this.tblReservationPaymentWithCekGirosForReceiverBankAccount = tblReservationPaymentWithCekGirosForReceiverBankAccount;
    }

    public Set getTblReservationPaymentWithBankCards() {
        return this.tblReservationPaymentWithBankCards;
    }

    public void setTblReservationPaymentWithBankCards(Set tblReservationPaymentWithBankCards) {
        this.tblReservationPaymentWithBankCards = tblReservationPaymentWithBankCards;
    }

    public Set getTblSupplierBankAccounts() {
        return this.tblSupplierBankAccounts;
    }

    public void setTblSupplierBankAccounts(Set tblSupplierBankAccounts) {
        this.tblSupplierBankAccounts = tblSupplierBankAccounts;
    }

    public Set getTblHotelFinanceTransactionWithTransfersForReceiverBankAccount() {
        return this.tblHotelFinanceTransactionWithTransfersForReceiverBankAccount;
    }

    public void setTblHotelFinanceTransactionWithTransfersForReceiverBankAccount(Set tblHotelFinanceTransactionWithTransfersForReceiverBankAccount) {
        this.tblHotelFinanceTransactionWithTransfersForReceiverBankAccount = tblHotelFinanceTransactionWithTransfersForReceiverBankAccount;
    }

    public Set getTblEmployeeBankAccounts() {
        return this.tblEmployeeBankAccounts;
    }

    public void setTblEmployeeBankAccounts(Set tblEmployeeBankAccounts) {
        this.tblEmployeeBankAccounts = tblEmployeeBankAccounts;
    }

    public Set getTblReservationPaymentWithGuaranteePaymentsForSenderBankAccount() {
        return this.tblReservationPaymentWithGuaranteePaymentsForSenderBankAccount;
    }

    public void setTblReservationPaymentWithGuaranteePaymentsForSenderBankAccount(Set tblReservationPaymentWithGuaranteePaymentsForSenderBankAccount) {
        this.tblReservationPaymentWithGuaranteePaymentsForSenderBankAccount = tblReservationPaymentWithGuaranteePaymentsForSenderBankAccount;
    }

    public Set getTblBankEdcs() {
        return this.tblBankEdcs;
    }

    public void setTblBankEdcs(Set tblBankEdcs) {
        this.tblBankEdcs = tblBankEdcs;
    }

    public Set getTblReservationPaymentWithTransfersForSenderBankAccount() {
        return this.tblReservationPaymentWithTransfersForSenderBankAccount;
    }

    public void setTblReservationPaymentWithTransfersForSenderBankAccount(Set tblReservationPaymentWithTransfersForSenderBankAccount) {
        this.tblReservationPaymentWithTransfersForSenderBankAccount = tblReservationPaymentWithTransfersForSenderBankAccount;
    }

    public Set getTblHotelFinanceTransactionWithCekGirosForSenderBankAccount() {
        return this.tblHotelFinanceTransactionWithCekGirosForSenderBankAccount;
    }

    public void setTblHotelFinanceTransactionWithCekGirosForSenderBankAccount(Set tblHotelFinanceTransactionWithCekGirosForSenderBankAccount) {
        this.tblHotelFinanceTransactionWithCekGirosForSenderBankAccount = tblHotelFinanceTransactionWithCekGirosForSenderBankAccount;
    }

    public Set getTblCompanyBalanceBankAccounts() {
        return this.tblCompanyBalanceBankAccounts;
    }

    public void setTblCompanyBalanceBankAccounts(Set tblCompanyBalanceBankAccounts) {
        this.tblCompanyBalanceBankAccounts = tblCompanyBalanceBankAccounts;
    }

    public Set getLogCompanyBalanceCashFlowsForIdreceiverCbbankAccount() {
        return this.logCompanyBalanceCashFlowsForIdreceiverCbbankAccount;
    }

    public void setLogCompanyBalanceCashFlowsForIdreceiverCbbankAccount(Set logCompanyBalanceCashFlowsForIdreceiverCbbankAccount) {
        this.logCompanyBalanceCashFlowsForIdreceiverCbbankAccount = logCompanyBalanceCashFlowsForIdreceiverCbbankAccount;
    }

    public Set getTblHotelExpenseTransactionsForIdbankAccount() {
        return this.tblHotelExpenseTransactionsForIdbankAccount;
    }

    public void setTblHotelExpenseTransactionsForIdbankAccount(Set tblHotelExpenseTransactionsForIdbankAccount) {
        this.tblHotelExpenseTransactionsForIdbankAccount = tblHotelExpenseTransactionsForIdbankAccount;
    }

    public Set getTblPartnerBankAccounts() {
        return this.tblPartnerBankAccounts;
    }

    public void setTblPartnerBankAccounts(Set tblPartnerBankAccounts) {
        this.tblPartnerBankAccounts = tblPartnerBankAccounts;
    }

    public Set getTblReservationPaymentWithCekGirosForSenderBankAccount() {
        return this.tblReservationPaymentWithCekGirosForSenderBankAccount;
    }

    public void setTblReservationPaymentWithCekGirosForSenderBankAccount(Set tblReservationPaymentWithCekGirosForSenderBankAccount) {
        this.tblReservationPaymentWithCekGirosForSenderBankAccount = tblReservationPaymentWithCekGirosForSenderBankAccount;
    }

    public Set getTblRestoBankAccounts() {
        return this.tblRestoBankAccounts;
    }

    public void setTblRestoBankAccounts(Set tblRestoBankAccounts) {
        this.tblRestoBankAccounts = tblRestoBankAccounts;
    }

    public Set getTblReservationPaymentWithTransfersForReceiverBankAccount() {
        return this.tblReservationPaymentWithTransfersForReceiverBankAccount;
    }

    public void setTblReservationPaymentWithTransfersForReceiverBankAccount(Set tblReservationPaymentWithTransfersForReceiverBankAccount) {
        this.tblReservationPaymentWithTransfersForReceiverBankAccount = tblReservationPaymentWithTransfersForReceiverBankAccount;
    }

    public Set getTblHotelFinanceTransactionWithCekGirosForReceiverBankAccount() {
        return this.tblHotelFinanceTransactionWithCekGirosForReceiverBankAccount;
    }

    public void setTblHotelFinanceTransactionWithCekGirosForReceiverBankAccount(Set tblHotelFinanceTransactionWithCekGirosForReceiverBankAccount) {
        this.tblHotelFinanceTransactionWithCekGirosForReceiverBankAccount = tblHotelFinanceTransactionWithCekGirosForReceiverBankAccount;
    }

    public Set getTblHotelFinanceTransactionWithTransfersForSenderBankAccount() {
        return this.tblHotelFinanceTransactionWithTransfersForSenderBankAccount;
    }

    public void setTblHotelFinanceTransactionWithTransfersForSenderBankAccount(Set tblHotelFinanceTransactionWithTransfersForSenderBankAccount) {
        this.tblHotelFinanceTransactionWithTransfersForSenderBankAccount = tblHotelFinanceTransactionWithTransfersForSenderBankAccount;
    }

    public Set getTblReservationPaymentWithGuaranteePaymentsForReceiverBankAccount() {
        return this.tblReservationPaymentWithGuaranteePaymentsForReceiverBankAccount;
    }

    public void setTblReservationPaymentWithGuaranteePaymentsForReceiverBankAccount(Set tblReservationPaymentWithGuaranteePaymentsForReceiverBankAccount) {
        this.tblReservationPaymentWithGuaranteePaymentsForReceiverBankAccount = tblReservationPaymentWithGuaranteePaymentsForReceiverBankAccount;
    }

    public Set getLogCompanyBalanceCashFlowsForIdsenderCbbankAccount() {
        return this.logCompanyBalanceCashFlowsForIdsenderCbbankAccount;
    }

    public void setLogCompanyBalanceCashFlowsForIdsenderCbbankAccount(Set logCompanyBalanceCashFlowsForIdsenderCbbankAccount) {
        this.logCompanyBalanceCashFlowsForIdsenderCbbankAccount = logCompanyBalanceCashFlowsForIdsenderCbbankAccount;
    }

    public Set getTblCustomerBankAccounts() {
        return this.tblCustomerBankAccounts;
    }

    public void setTblCustomerBankAccounts(Set tblCustomerBankAccounts) {
        this.tblCustomerBankAccounts = tblCustomerBankAccounts;
    }

    @Override
    public String toString() {
        return getCodeBankAccount();
    }
    
}
