package hotelfx.persistence.model;
// Generated Oct 18, 2018 4:38:29 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblBrokenItemDetail generated by hbm2java
 */
public class TblBrokenItemDetail implements java.io.Serializable {

    private final LongProperty iddetail;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblBrokenItem> tblBrokenItem;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblItem> tblItem;
    private final ObjectProperty<BigDecimal> itemQuantity;
    private final StringProperty itemNote;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    private Set tblBrokenItemDetailItemMutationHistories;

    public TblBrokenItemDetail() {
        this.iddetail = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblBrokenItem = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblItem = new SimpleObjectProperty<>();
        this.itemQuantity = new SimpleObjectProperty<>();
        this.itemNote = new SimpleStringProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

        this.tblBrokenItemDetailItemMutationHistories = new HashSet(0);
    }

    public TblBrokenItemDetail(long iddetail) {
        this();
        iddetailProperty().set(iddetail);
    }

    public TblBrokenItemDetail(long iddetail, RefRecordStatus refRecordStatus, TblBrokenItem tblBrokenItem, TblEmployee tblEmployeeByCreateBy, TblEmployee tblEmployeeByLastUpdateBy, TblItem tblItem, BigDecimal itemQuantity, String itemNote, Date createDate, Date lastUpdateDate, Set tblBrokenItemDetailItemMutationHistories) {
        this();
        iddetailProperty().set(iddetail);
        refRecordStatusProperty().set(refRecordStatus);
        tblBrokenItemProperty().set(tblBrokenItem);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblItemProperty().set(tblItem);
        itemQuantityProperty().set(itemQuantity);
        itemNoteProperty().set(itemNote);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

        this.tblBrokenItemDetailItemMutationHistories = tblBrokenItemDetailItemMutationHistories;
    }

    public TblBrokenItemDetail(TblBrokenItemDetail tblBrokenItemDetail) {
        this();
        iddetailProperty().set(tblBrokenItemDetail.getIddetail());
        refRecordStatusProperty().set(tblBrokenItemDetail.getRefRecordStatus());
        tblBrokenItemProperty().set(tblBrokenItemDetail.getTblBrokenItem());
        tblEmployeeByCreateByProperty().set(tblBrokenItemDetail.getTblEmployeeByCreateBy());
        tblEmployeeByLastUpdateByProperty().set(tblBrokenItemDetail.getTblEmployeeByLastUpdateBy());
        tblItemProperty().set(tblBrokenItemDetail.getTblItem());
        itemQuantityProperty().set(tblBrokenItemDetail.getItemQuantity());
        itemNoteProperty().set(tblBrokenItemDetail.getItemNote());
        createDateProperty().set(tblBrokenItemDetail.getCreateDate());
        lastUpdateDateProperty().set(tblBrokenItemDetail.getLastUpdateDate());

        this.tblBrokenItemDetailItemMutationHistories = tblBrokenItemDetail.getTblBrokenItemDetailItemMutationHistories();
    }

    public final LongProperty iddetailProperty() {
        return this.iddetail;
    }

    public long getIddetail() {
        return iddetailProperty().get();
    }

    public void setIddetail(long iddetail) {
        iddetailProperty().set(iddetail);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblBrokenItem> tblBrokenItemProperty() {
        return this.tblBrokenItem;
    }

    public TblBrokenItem getTblBrokenItem() {
        return tblBrokenItemProperty().get();
    }

    public void setTblBrokenItem(TblBrokenItem tblBrokenItem) {
        tblBrokenItemProperty().set(tblBrokenItem);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblItem> tblItemProperty() {
        return this.tblItem;
    }

    public TblItem getTblItem() {
        return tblItemProperty().get();
    }

    public void setTblItem(TblItem tblItem) {
        tblItemProperty().set(tblItem);
    }

    public final ObjectProperty<BigDecimal> itemQuantityProperty() {
        return this.itemQuantity;
    }

    public BigDecimal getItemQuantity() {
        return itemQuantityProperty().get();
    }

    public void setItemQuantity(BigDecimal itemQuantity) {
        itemQuantityProperty().set(itemQuantity);
    }

    public final StringProperty itemNoteProperty() {
        return this.itemNote;
    }

    public String getItemNote() {
        return itemNoteProperty().get();
    }

    public void setItemNote(String itemNote) {
        itemNoteProperty().set(itemNote);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

    public Set getTblBrokenItemDetailItemMutationHistories() {
        return this.tblBrokenItemDetailItemMutationHistories;
    }

    public void setTblBrokenItemDetailItemMutationHistories(Set tblBrokenItemDetailItemMutationHistories) {
        this.tblBrokenItemDetailItemMutationHistories = tblBrokenItemDetailItemMutationHistories;
    }

}
