package hotelfx.persistence.model;
// Generated Oct 26, 2018 12:41:59 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javafx.beans.property.BooleanProperty;
import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleBooleanProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblBankEdcBankNetworkCard generated by hbm2java
 */
public class TblBankEdcBankNetworkCard implements java.io.Serializable {

    private final LongProperty idrelation;
    private final ObjectProperty<RefBankCardType> refBankCardType;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblBankEdc> tblBankEdc;
    private final ObjectProperty<TblBankNetworkCard> tblBankNetworkCard;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final BooleanProperty onUs;
    private final StringProperty networkNote;
    private final ObjectProperty<BigDecimal> networkMdr;
    private final ObjectProperty<BigDecimal> maxNetworkMdrnominal;
    private final ObjectProperty<BigDecimal> networkDdr;
    private final ObjectProperty<BigDecimal> maxNetworkDdrnominal;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;
    private final ObjectProperty<BigDecimal> debitMdrintern;
    private final ObjectProperty<BigDecimal> debitMdrextern;
    private final ObjectProperty<BigDecimal> creaditMdrintern;
    private final ObjectProperty<BigDecimal> creaditMdrextern;

    private Set tblReservationPaymentWithBankCards;

    public TblBankEdcBankNetworkCard() {
        this.idrelation = new SimpleLongProperty();
        this.refBankCardType = new SimpleObjectProperty<>();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblBankEdc = new SimpleObjectProperty<>();
        this.tblBankNetworkCard = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.onUs = new SimpleBooleanProperty();
        this.networkNote = new SimpleStringProperty();
        this.networkMdr = new SimpleObjectProperty<>();
        this.maxNetworkMdrnominal = new SimpleObjectProperty<>();
        this.networkDdr = new SimpleObjectProperty<>();
        this.maxNetworkDdrnominal = new SimpleObjectProperty<>();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();
        this.debitMdrintern = new SimpleObjectProperty<>();
        this.debitMdrextern = new SimpleObjectProperty<>();
        this.creaditMdrintern = new SimpleObjectProperty<>();
        this.creaditMdrextern = new SimpleObjectProperty<>();

        this.tblReservationPaymentWithBankCards = new HashSet(0);
    }

    public TblBankEdcBankNetworkCard(long idrelation) {
        this();
        idrelationProperty().set(idrelation);
    }

    public TblBankEdcBankNetworkCard(long idrelation, RefBankCardType refBankCardType, RefRecordStatus refRecordStatus, TblBankEdc tblBankEdc, TblBankNetworkCard tblBankNetworkCard, TblEmployee tblEmployeeByLastUpdateBy, TblEmployee tblEmployeeByCreateBy, Boolean onUs, String networkNote, BigDecimal networkMdr, BigDecimal maxNetworkMdrnominal, BigDecimal networkDdr, BigDecimal maxNetworkDdrnominal, Date createDate, Date lastUpdateDate, BigDecimal debitMdrintern, BigDecimal debitMdrextern, BigDecimal creaditMdrintern, BigDecimal creaditMdrextern, Set tblReservationPaymentWithBankCards) {
        this();
        idrelationProperty().set(idrelation);
        refBankCardTypeProperty().set(refBankCardType);
        refRecordStatusProperty().set(refRecordStatus);
        tblBankEdcProperty().set(tblBankEdc);
        tblBankNetworkCardProperty().set(tblBankNetworkCard);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        onUsProperty().set(onUs);
        networkNoteProperty().set(networkNote);
        networkMdrProperty().set(networkMdr);
        maxNetworkMdrnominalProperty().set(maxNetworkMdrnominal);
        networkDdrProperty().set(networkDdr);
        maxNetworkDdrnominalProperty().set(maxNetworkDdrnominal);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);
        debitMdrinternProperty().set(debitMdrintern);
        debitMdrexternProperty().set(debitMdrextern);
        creaditMdrinternProperty().set(creaditMdrintern);
        creaditMdrexternProperty().set(creaditMdrextern);

        this.tblReservationPaymentWithBankCards = tblReservationPaymentWithBankCards;
    }

    public TblBankEdcBankNetworkCard(TblBankEdcBankNetworkCard tblBankEdcBankNetworkCard) {
        this();
        idrelationProperty().set(tblBankEdcBankNetworkCard.getIdrelation());
        refBankCardTypeProperty().set(tblBankEdcBankNetworkCard.getRefBankCardType());
        refRecordStatusProperty().set(tblBankEdcBankNetworkCard.getRefRecordStatus());
        tblBankEdcProperty().set(tblBankEdcBankNetworkCard.getTblBankEdc());
        tblBankNetworkCardProperty().set(tblBankEdcBankNetworkCard.getTblBankNetworkCard());
        tblEmployeeByLastUpdateByProperty().set(tblBankEdcBankNetworkCard.getTblEmployeeByLastUpdateBy());
        tblEmployeeByCreateByProperty().set(tblBankEdcBankNetworkCard.getTblEmployeeByCreateBy());
        onUsProperty().set(tblBankEdcBankNetworkCard.getOnUs());
        networkNoteProperty().set(tblBankEdcBankNetworkCard.getNetworkNote());
        networkMdrProperty().set(tblBankEdcBankNetworkCard.getNetworkMdr());
        maxNetworkMdrnominalProperty().set(tblBankEdcBankNetworkCard.getMaxNetworkMdrnominal());
        networkDdrProperty().set(tblBankEdcBankNetworkCard.getNetworkDdr());
        maxNetworkDdrnominalProperty().set(tblBankEdcBankNetworkCard.getMaxNetworkDdrnominal());
        createDateProperty().set(tblBankEdcBankNetworkCard.getCreateDate());
        lastUpdateDateProperty().set(tblBankEdcBankNetworkCard.getLastUpdateDate());
        debitMdrinternProperty().set(tblBankEdcBankNetworkCard.getDebitMdrintern());
        debitMdrexternProperty().set(tblBankEdcBankNetworkCard.getDebitMdrextern());
        creaditMdrinternProperty().set(tblBankEdcBankNetworkCard.getCreaditMdrintern());
        creaditMdrexternProperty().set(tblBankEdcBankNetworkCard.getCreaditMdrextern());

        this.tblReservationPaymentWithBankCards = tblBankEdcBankNetworkCard.getTblReservationPaymentWithBankCards();
    }

    public final LongProperty idrelationProperty() {
        return this.idrelation;
    }

    public long getIdrelation() {
        return idrelationProperty().get();
    }

    public void setIdrelation(long idrelation) {
        idrelationProperty().set(idrelation);
    }

    public final ObjectProperty<RefBankCardType> refBankCardTypeProperty() {
        return this.refBankCardType;
    }

    public RefBankCardType getRefBankCardType() {
        return refBankCardTypeProperty().get();
    }

    public void setRefBankCardType(RefBankCardType refBankCardType) {
        refBankCardTypeProperty().set(refBankCardType);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblBankEdc> tblBankEdcProperty() {
        return this.tblBankEdc;
    }

    public TblBankEdc getTblBankEdc() {
        return tblBankEdcProperty().get();
    }

    public void setTblBankEdc(TblBankEdc tblBankEdc) {
        tblBankEdcProperty().set(tblBankEdc);
    }

    public final ObjectProperty<TblBankNetworkCard> tblBankNetworkCardProperty() {
        return this.tblBankNetworkCard;
    }

    public TblBankNetworkCard getTblBankNetworkCard() {
        return tblBankNetworkCardProperty().get();
    }

    public void setTblBankNetworkCard(TblBankNetworkCard tblBankNetworkCard) {
        tblBankNetworkCardProperty().set(tblBankNetworkCard);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final BooleanProperty onUsProperty() {
        return this.onUs;
    }

    public Boolean getOnUs() {
        return onUsProperty().get();
    }

    public void setOnUs(Boolean onUs) {
        onUsProperty().set(onUs);
    }

    public final StringProperty networkNoteProperty() {
        return this.networkNote;
    }

    public String getNetworkNote() {
        return networkNoteProperty().get();
    }

    public void setNetworkNote(String networkNote) {
        networkNoteProperty().set(networkNote);
    }

    public final ObjectProperty<BigDecimal> networkMdrProperty() {
        return this.networkMdr;
    }

    public BigDecimal getNetworkMdr() {
        return networkMdrProperty().get();
    }

    public void setNetworkMdr(BigDecimal networkMdr) {
        networkMdrProperty().set(networkMdr);
    }

    public final ObjectProperty<BigDecimal> maxNetworkMdrnominalProperty() {
        return this.maxNetworkMdrnominal;
    }

    public BigDecimal getMaxNetworkMdrnominal() {
        return maxNetworkMdrnominalProperty().get();
    }

    public void setMaxNetworkMdrnominal(BigDecimal maxNetworkMdrnominal) {
        maxNetworkMdrnominalProperty().set(maxNetworkMdrnominal);
    }

    public final ObjectProperty<BigDecimal> networkDdrProperty() {
        return this.networkDdr;
    }

    public BigDecimal getNetworkDdr() {
        return networkDdrProperty().get();
    }

    public void setNetworkDdr(BigDecimal networkDdr) {
        networkDdrProperty().set(networkDdr);
    }

    public final ObjectProperty<BigDecimal> maxNetworkDdrnominalProperty() {
        return this.maxNetworkDdrnominal;
    }

    public BigDecimal getMaxNetworkDdrnominal() {
        return maxNetworkDdrnominalProperty().get();
    }

    public void setMaxNetworkDdrnominal(BigDecimal maxNetworkDdrnominal) {
        maxNetworkDdrnominalProperty().set(maxNetworkDdrnominal);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

    public final ObjectProperty<BigDecimal> debitMdrinternProperty() {
        return this.debitMdrintern;
    }

    public BigDecimal getDebitMdrintern() {
        return debitMdrinternProperty().get();
    }

    public void setDebitMdrintern(BigDecimal debitMdrintern) {
        debitMdrinternProperty().set(debitMdrintern);
    }

    public final ObjectProperty<BigDecimal> debitMdrexternProperty() {
        return this.debitMdrextern;
    }

    public BigDecimal getDebitMdrextern() {
        return debitMdrexternProperty().get();
    }

    public void setDebitMdrextern(BigDecimal debitMdrextern) {
        debitMdrexternProperty().set(debitMdrextern);
    }

    public final ObjectProperty<BigDecimal> creaditMdrinternProperty() {
        return this.creaditMdrintern;
    }

    public BigDecimal getCreaditMdrintern() {
        return creaditMdrinternProperty().get();
    }

    public void setCreaditMdrintern(BigDecimal creaditMdrintern) {
        creaditMdrinternProperty().set(creaditMdrintern);
    }

    public final ObjectProperty<BigDecimal> creaditMdrexternProperty() {
        return this.creaditMdrextern;
    }

    public BigDecimal getCreaditMdrextern() {
        return creaditMdrexternProperty().get();
    }

    public void setCreaditMdrextern(BigDecimal creaditMdrextern) {
        creaditMdrexternProperty().set(creaditMdrextern);
    }

    public Set getTblReservationPaymentWithBankCards() {
        return this.tblReservationPaymentWithBankCards;
    }

    public void setTblReservationPaymentWithBankCards(Set tblReservationPaymentWithBankCards) {
        this.tblReservationPaymentWithBankCards = tblReservationPaymentWithBankCards;
    }

}
