package hotelfx.persistence.model;
// Generated Jun 29, 2018 9:21:45 AM by Hibernate Tools 4.3.1

import java.util.Date;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblCalendarEmployeeWarningLetter generated by hbm2java
 */
public class TblCalendarEmployeeWarningLetter implements java.io.Serializable {

    private final LongProperty idrelation;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdatedBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByIdemployee;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreatedBy;
    private final ObjectProperty<TblEmployeeWarningLetterType> tblEmployeeWarningLetterType;
    private final ObjectProperty<Date> startDate;
    private final ObjectProperty<Date> endDate;
    private final StringProperty noteWarningLetter;
    private final ObjectProperty<Date> createdDate;
    private final ObjectProperty<Date> lastUpdatedDate;

    public TblCalendarEmployeeWarningLetter() {
        this.idrelation = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdatedBy = new SimpleObjectProperty<>();
        this.tblEmployeeByIdemployee = new SimpleObjectProperty<>();
        this.tblEmployeeByCreatedBy = new SimpleObjectProperty<>();
        this.tblEmployeeWarningLetterType = new SimpleObjectProperty<>();
        this.startDate = new SimpleObjectProperty<>();
        this.endDate = new SimpleObjectProperty<>();
        this.noteWarningLetter = new SimpleStringProperty();
        this.createdDate = new SimpleObjectProperty<>();
        this.lastUpdatedDate = new SimpleObjectProperty<>();

    }

    public TblCalendarEmployeeWarningLetter(long idrelation) {
        this();
        idrelationProperty().set(idrelation);
    }

    public TblCalendarEmployeeWarningLetter(long idrelation, RefRecordStatus refRecordStatus, TblEmployee tblEmployeeByLastUpdatedBy, TblEmployee tblEmployeeByIdemployee, TblEmployee tblEmployeeByCreatedBy, TblEmployeeWarningLetterType tblEmployeeWarningLetterType, Date startDate, Date endDate, String noteWarningLetter, Date createdDate, Date lastUpdatedDate) {
        this();
        idrelationProperty().set(idrelation);
        refRecordStatusProperty().set(refRecordStatus);
        tblEmployeeByLastUpdatedByProperty().set(tblEmployeeByLastUpdatedBy);
        tblEmployeeByIdemployeeProperty().set(tblEmployeeByIdemployee);
        tblEmployeeByCreatedByProperty().set(tblEmployeeByCreatedBy);
        tblEmployeeWarningLetterTypeProperty().set(tblEmployeeWarningLetterType);
        startDateProperty().set(startDate);
        endDateProperty().set(endDate);
        noteWarningLetterProperty().set(noteWarningLetter);
        createdDateProperty().set(createdDate);
        lastUpdatedDateProperty().set(lastUpdatedDate);

    }

    public TblCalendarEmployeeWarningLetter(TblCalendarEmployeeWarningLetter tblCalendarEmployeeWarningLetter) {
        this();
        idrelationProperty().set(tblCalendarEmployeeWarningLetter.getIdrelation());
        refRecordStatusProperty().set(tblCalendarEmployeeWarningLetter.getRefRecordStatus());
        tblEmployeeByLastUpdatedByProperty().set(tblCalendarEmployeeWarningLetter.getTblEmployeeByLastUpdatedBy());
        tblEmployeeByIdemployeeProperty().set(tblCalendarEmployeeWarningLetter.getTblEmployeeByIdemployee());
        tblEmployeeByCreatedByProperty().set(tblCalendarEmployeeWarningLetter.getTblEmployeeByCreatedBy());
        tblEmployeeWarningLetterTypeProperty().set(tblCalendarEmployeeWarningLetter.getTblEmployeeWarningLetterType());
        startDateProperty().set(tblCalendarEmployeeWarningLetter.getStartDate());
        endDateProperty().set(tblCalendarEmployeeWarningLetter.getEndDate());
        noteWarningLetterProperty().set(tblCalendarEmployeeWarningLetter.getNoteWarningLetter());
        createdDateProperty().set(tblCalendarEmployeeWarningLetter.getCreatedDate());
        lastUpdatedDateProperty().set(tblCalendarEmployeeWarningLetter.getLastUpdatedDate());

    }

    public final LongProperty idrelationProperty() {
        return this.idrelation;
    }

    public long getIdrelation() {
        return idrelationProperty().get();
    }

    public void setIdrelation(long idrelation) {
        idrelationProperty().set(idrelation);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdatedByProperty() {
        return this.tblEmployeeByLastUpdatedBy;
    }

    public TblEmployee getTblEmployeeByLastUpdatedBy() {
        return tblEmployeeByLastUpdatedByProperty().get();
    }

    public void setTblEmployeeByLastUpdatedBy(TblEmployee tblEmployeeByLastUpdatedBy) {
        tblEmployeeByLastUpdatedByProperty().set(tblEmployeeByLastUpdatedBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByIdemployeeProperty() {
        return this.tblEmployeeByIdemployee;
    }

    public TblEmployee getTblEmployeeByIdemployee() {
        return tblEmployeeByIdemployeeProperty().get();
    }

    public void setTblEmployeeByIdemployee(TblEmployee tblEmployeeByIdemployee) {
        tblEmployeeByIdemployeeProperty().set(tblEmployeeByIdemployee);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreatedByProperty() {
        return this.tblEmployeeByCreatedBy;
    }

    public TblEmployee getTblEmployeeByCreatedBy() {
        return tblEmployeeByCreatedByProperty().get();
    }

    public void setTblEmployeeByCreatedBy(TblEmployee tblEmployeeByCreatedBy) {
        tblEmployeeByCreatedByProperty().set(tblEmployeeByCreatedBy);
    }

    public final ObjectProperty<TblEmployeeWarningLetterType> tblEmployeeWarningLetterTypeProperty() {
        return this.tblEmployeeWarningLetterType;
    }

    public TblEmployeeWarningLetterType getTblEmployeeWarningLetterType() {
        return tblEmployeeWarningLetterTypeProperty().get();
    }

    public void setTblEmployeeWarningLetterType(TblEmployeeWarningLetterType tblEmployeeWarningLetterType) {
        tblEmployeeWarningLetterTypeProperty().set(tblEmployeeWarningLetterType);
    }

    public final ObjectProperty<Date> startDateProperty() {
        return this.startDate;
    }

    public Date getStartDate() {
        return startDateProperty().get();
    }

    public void setStartDate(Date startDate) {
        startDateProperty().set(startDate);
    }

    public final ObjectProperty<Date> endDateProperty() {
        return this.endDate;
    }

    public Date getEndDate() {
        return endDateProperty().get();
    }

    public void setEndDate(Date endDate) {
        endDateProperty().set(endDate);
    }

    public final StringProperty noteWarningLetterProperty() {
        return this.noteWarningLetter;
    }

    public String getNoteWarningLetter() {
        return noteWarningLetterProperty().get();
    }

    public void setNoteWarningLetter(String noteWarningLetter) {
        noteWarningLetterProperty().set(noteWarningLetter);
    }

    public final ObjectProperty<Date> createdDateProperty() {
        return this.createdDate;
    }

    public Date getCreatedDate() {
        return createdDateProperty().get();
    }

    public void setCreatedDate(Date createdDate) {
        createdDateProperty().set(createdDate);
    }

    public final ObjectProperty<Date> lastUpdatedDateProperty() {
        return this.lastUpdatedDate;
    }

    public Date getLastUpdatedDate() {
        return lastUpdatedDateProperty().get();
    }

    public void setLastUpdatedDate(Date lastUpdatedDate) {
        lastUpdatedDateProperty().set(lastUpdatedDate);
    }

}
