package hotelfx.persistence.model;
// Generated Apr 20, 2018 10:15:50 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblCustomer generated by hbm2java
 */
public class TblCustomer implements java.io.Serializable {

    private final LongProperty idcustomer;
    private final ObjectProperty<RefCustomerStatus> refCustomerStatus;
    private final ObjectProperty<RefCustomerType> refCustomerType;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblPeople> tblPeople;
    private final StringProperty codeCustomer;
    private final ObjectProperty<BigDecimal> deposit;
    private final ObjectProperty<Date> registrationDate;
    private final StringProperty customerNote;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    private Set tblCustomerBankAccounts;
    private Set tblReservations;

    public TblCustomer() {
        this.idcustomer = new SimpleLongProperty();
        this.refCustomerStatus = new SimpleObjectProperty<>();
        this.refCustomerType = new SimpleObjectProperty<>();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblPeople = new SimpleObjectProperty<>();
        this.codeCustomer = new SimpleStringProperty();
        this.deposit = new SimpleObjectProperty<>();
        this.registrationDate = new SimpleObjectProperty<>();
        this.customerNote = new SimpleStringProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

        this.tblCustomerBankAccounts = new HashSet(0);
        this.tblReservations = new HashSet(0);
    }

    public TblCustomer(long idcustomer) {
        this();
        idcustomerProperty().set(idcustomer);
    }

    public TblCustomer(long idcustomer, RefCustomerStatus refCustomerStatus, RefCustomerType refCustomerType, RefRecordStatus refRecordStatus, TblEmployee tblEmployeeByLastUpdateBy, TblEmployee tblEmployeeByCreateBy, TblPeople tblPeople, String codeCustomer, BigDecimal deposit, Date registrationDate, String customerNote, Date createDate, Date lastUpdateDate, Set tblCustomerBankAccounts, Set tblReservations) {
        this();
        idcustomerProperty().set(idcustomer);
        refCustomerStatusProperty().set(refCustomerStatus);
        refCustomerTypeProperty().set(refCustomerType);
        refRecordStatusProperty().set(refRecordStatus);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblPeopleProperty().set(tblPeople);
        codeCustomerProperty().set(codeCustomer);
        depositProperty().set(deposit);
        registrationDateProperty().set(registrationDate);
        customerNoteProperty().set(customerNote);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

        this.tblCustomerBankAccounts = tblCustomerBankAccounts;
        this.tblReservations = tblReservations;
    }

    public TblCustomer(TblCustomer tblCustomer) {
        this();
        idcustomerProperty().set(tblCustomer.getIdcustomer());
        refCustomerStatusProperty().set(tblCustomer.getRefCustomerStatus());
        refCustomerTypeProperty().set(tblCustomer.getRefCustomerType());
        refRecordStatusProperty().set(tblCustomer.getRefRecordStatus());
        tblEmployeeByLastUpdateByProperty().set(tblCustomer.getTblEmployeeByLastUpdateBy());
        tblEmployeeByCreateByProperty().set(tblCustomer.getTblEmployeeByCreateBy());
        tblPeopleProperty().set(tblCustomer.getTblPeople());
        codeCustomerProperty().set(tblCustomer.getCodeCustomer());
        depositProperty().set(tblCustomer.getDeposit());
        registrationDateProperty().set(tblCustomer.getRegistrationDate());
        customerNoteProperty().set(tblCustomer.getCustomerNote());
        createDateProperty().set(tblCustomer.getCreateDate());
        lastUpdateDateProperty().set(tblCustomer.getLastUpdateDate());

        this.tblCustomerBankAccounts = tblCustomer.getTblCustomerBankAccounts();
        this.tblReservations = tblCustomer.getTblReservations();
    }

    public final LongProperty idcustomerProperty() {
        return this.idcustomer;
    }

    public long getIdcustomer() {
        return idcustomerProperty().get();
    }

    public void setIdcustomer(long idcustomer) {
        idcustomerProperty().set(idcustomer);
    }

    public final ObjectProperty<RefCustomerStatus> refCustomerStatusProperty() {
        return this.refCustomerStatus;
    }

    public RefCustomerStatus getRefCustomerStatus() {
        return refCustomerStatusProperty().get();
    }

    public void setRefCustomerStatus(RefCustomerStatus refCustomerStatus) {
        refCustomerStatusProperty().set(refCustomerStatus);
    }

    public final ObjectProperty<RefCustomerType> refCustomerTypeProperty() {
        return this.refCustomerType;
    }

    public RefCustomerType getRefCustomerType() {
        return refCustomerTypeProperty().get();
    }

    public void setRefCustomerType(RefCustomerType refCustomerType) {
        refCustomerTypeProperty().set(refCustomerType);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblPeople> tblPeopleProperty() {
        return this.tblPeople;
    }

    public TblPeople getTblPeople() {
        return tblPeopleProperty().get();
    }

    public void setTblPeople(TblPeople tblPeople) {
        tblPeopleProperty().set(tblPeople);
    }

    public final StringProperty codeCustomerProperty() {
        return this.codeCustomer;
    }

    public String getCodeCustomer() {
        return codeCustomerProperty().get();
    }

    public void setCodeCustomer(String codeCustomer) {
        codeCustomerProperty().set(codeCustomer);
    }

    public final ObjectProperty<BigDecimal> depositProperty() {
        return this.deposit;
    }

    public BigDecimal getDeposit() {
        return depositProperty().get();
    }

    public void setDeposit(BigDecimal deposit) {
        depositProperty().set(deposit);
    }

    public final ObjectProperty<Date> registrationDateProperty() {
        return this.registrationDate;
    }

    public Date getRegistrationDate() {
        return registrationDateProperty().get();
    }

    public void setRegistrationDate(Date registrationDate) {
        registrationDateProperty().set(registrationDate);
    }

    public final StringProperty customerNoteProperty() {
        return this.customerNote;
    }

    public String getCustomerNote() {
        return customerNoteProperty().get();
    }

    public void setCustomerNote(String customerNote) {
        customerNoteProperty().set(customerNote);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

    public Set getTblCustomerBankAccounts() {
        return this.tblCustomerBankAccounts;
    }

    public void setTblCustomerBankAccounts(Set tblCustomerBankAccounts) {
        this.tblCustomerBankAccounts = tblCustomerBankAccounts;
    }

    public Set getTblReservations() {
        return this.tblReservations;
    }

    public void setTblReservations(Set tblReservations) {
        this.tblReservations = tblReservations;
    }

    @Override
    public String toString() {
        return codeCustomerProperty().get();
    }
    
}
