package hotelfx.persistence.model;
// Generated Nov 23, 2017 4:51:33 PM by Hibernate Tools 4.3.1

import java.util.Date;

import javafx.beans.property.BooleanProperty;
import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleBooleanProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblCalendarEmployeeLeave generated by hbm2java
 */
public class TblCalendarEmployeeLeave implements java.io.Serializable {

    private final LongProperty idrelation;
    private final ObjectProperty<RefEmployeeLeaveType> refEmployeeLeaveType;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<SysCalendar> sysCalendar;
    private final ObjectProperty<TblEmployee> tblEmployeeByIdemployee;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final StringProperty note;
    private final BooleanProperty cutLeaveStatus;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    public TblCalendarEmployeeLeave() {
        this.idrelation = new SimpleLongProperty();
        this.refEmployeeLeaveType = new SimpleObjectProperty<>();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.sysCalendar = new SimpleObjectProperty<>();
        this.tblEmployeeByIdemployee = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.note = new SimpleStringProperty();
        this.cutLeaveStatus = new SimpleBooleanProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

    }

    public TblCalendarEmployeeLeave(long idrelation) {
        this();
        idrelationProperty().set(idrelation);
    }

    public TblCalendarEmployeeLeave(long idrelation, RefEmployeeLeaveType refEmployeeLeaveType, RefRecordStatus refRecordStatus, SysCalendar sysCalendar, TblEmployee tblEmployeeByIdemployee, TblEmployee tblEmployeeByLastUpdateBy, TblEmployee tblEmployeeByCreateBy, String note, Boolean cutLeaveStatus, Date createDate, Date lastUpdateDate) {
        this();
        idrelationProperty().set(idrelation);
        refEmployeeLeaveTypeProperty().set(refEmployeeLeaveType);
        refRecordStatusProperty().set(refRecordStatus);
        sysCalendarProperty().set(sysCalendar);
        tblEmployeeByIdemployeeProperty().set(tblEmployeeByIdemployee);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        noteProperty().set(note);
        cutLeaveStatusProperty().set(cutLeaveStatus);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

    }

    public TblCalendarEmployeeLeave(TblCalendarEmployeeLeave tblCalendarEmployeeLeave) {
        this();
        idrelationProperty().set(tblCalendarEmployeeLeave.getIdrelation());
        refEmployeeLeaveTypeProperty().set(tblCalendarEmployeeLeave.getRefEmployeeLeaveType());
        refRecordStatusProperty().set(tblCalendarEmployeeLeave.getRefRecordStatus());
        sysCalendarProperty().set(tblCalendarEmployeeLeave.getSysCalendar());
        tblEmployeeByIdemployeeProperty().set(tblCalendarEmployeeLeave.getTblEmployeeByIdemployee());
        tblEmployeeByLastUpdateByProperty().set(tblCalendarEmployeeLeave.getTblEmployeeByLastUpdateBy());
        tblEmployeeByCreateByProperty().set(tblCalendarEmployeeLeave.getTblEmployeeByCreateBy());
        noteProperty().set(tblCalendarEmployeeLeave.getNote());
        cutLeaveStatusProperty().set(tblCalendarEmployeeLeave.getCutLeaveStatus());
        createDateProperty().set(tblCalendarEmployeeLeave.getCreateDate());
        lastUpdateDateProperty().set(tblCalendarEmployeeLeave.getLastUpdateDate());

    }

    public final LongProperty idrelationProperty() {
        return this.idrelation;
    }

    public long getIdrelation() {
        return idrelationProperty().get();
    }

    public void setIdrelation(long idrelation) {
        idrelationProperty().set(idrelation);
    }

    public final ObjectProperty<RefEmployeeLeaveType> refEmployeeLeaveTypeProperty() {
        return this.refEmployeeLeaveType;
    }

    public RefEmployeeLeaveType getRefEmployeeLeaveType() {
        return refEmployeeLeaveTypeProperty().get();
    }

    public void setRefEmployeeLeaveType(RefEmployeeLeaveType refEmployeeLeaveType) {
        refEmployeeLeaveTypeProperty().set(refEmployeeLeaveType);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<SysCalendar> sysCalendarProperty() {
        return this.sysCalendar;
    }

    public SysCalendar getSysCalendar() {
        return sysCalendarProperty().get();
    }

    public void setSysCalendar(SysCalendar sysCalendar) {
        sysCalendarProperty().set(sysCalendar);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByIdemployeeProperty() {
        return this.tblEmployeeByIdemployee;
    }

    public TblEmployee getTblEmployeeByIdemployee() {
        return tblEmployeeByIdemployeeProperty().get();
    }

    public void setTblEmployeeByIdemployee(TblEmployee tblEmployeeByIdemployee) {
        tblEmployeeByIdemployeeProperty().set(tblEmployeeByIdemployee);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final StringProperty noteProperty() {
        return this.note;
    }

    public String getNote() {
        return noteProperty().get();
    }

    public void setNote(String note) {
        noteProperty().set(note);
    }

    public final BooleanProperty cutLeaveStatusProperty() {
        return this.cutLeaveStatus;
    }

    public Boolean getCutLeaveStatus() {
        return cutLeaveStatusProperty().get();
    }

    public void setCutLeaveStatus(Boolean cutLeaveStatus) {
        cutLeaveStatusProperty().set(cutLeaveStatus);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

}
