package hotelfx.persistence.model;
// Generated Sep 25, 2018 4:01:53 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblCalendarEmployeePaymentHistory generated by hbm2java
 */
public class TblCalendarEmployeePaymentHistory implements java.io.Serializable {

    private final LongProperty idhistory;
    private final ObjectProperty<RefFinanceTransactionPaymentType> refFinanceTransactionPaymentType;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblCompanyBalance> tblCompanyBalance;
    private final ObjectProperty<TblCompanyBalanceBankAccount> tblCompanyBalanceBankAccount;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdatedBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByIdemployee;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreatedBy;
    private final ObjectProperty<TblEmployeeBankAccount> tblEmployeeBankAccount;
    private final ObjectProperty<Date> historyDate;
    private final ObjectProperty<BigDecimal> employeePaymentDebtNominal;
    private final StringProperty historyNote;
    private final ObjectProperty<Date> createdDate;
    private final ObjectProperty<Date> lastUpdatedDate;

    public TblCalendarEmployeePaymentHistory() {
        this.idhistory = new SimpleLongProperty();
        this.refFinanceTransactionPaymentType = new SimpleObjectProperty<>();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblCompanyBalance = new SimpleObjectProperty<>();
        this.tblCompanyBalanceBankAccount = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdatedBy = new SimpleObjectProperty<>();
        this.tblEmployeeByIdemployee = new SimpleObjectProperty<>();
        this.tblEmployeeByCreatedBy = new SimpleObjectProperty<>();
        this.tblEmployeeBankAccount = new SimpleObjectProperty<>();
        this.historyDate = new SimpleObjectProperty<>();
        this.employeePaymentDebtNominal = new SimpleObjectProperty<>();
        this.historyNote = new SimpleStringProperty();
        this.createdDate = new SimpleObjectProperty<>();
        this.lastUpdatedDate = new SimpleObjectProperty<>();

    }

    public TblCalendarEmployeePaymentHistory(long idhistory) {
        this();
        idhistoryProperty().set(idhistory);
    }

    public TblCalendarEmployeePaymentHistory(long idhistory, RefFinanceTransactionPaymentType refFinanceTransactionPaymentType, RefRecordStatus refRecordStatus, TblCompanyBalance tblCompanyBalance, TblCompanyBalanceBankAccount tblCompanyBalanceBankAccount, TblEmployee tblEmployeeByLastUpdatedBy, TblEmployee tblEmployeeByIdemployee, TblEmployee tblEmployeeByCreatedBy, TblEmployeeBankAccount tblEmployeeBankAccount, Date historyDate, BigDecimal employeePaymentDebtNominal, String historyNote, Date createdDate, Date lastUpdatedDate) {
        this();
        idhistoryProperty().set(idhistory);
        refFinanceTransactionPaymentTypeProperty().set(refFinanceTransactionPaymentType);
        refRecordStatusProperty().set(refRecordStatus);
        tblCompanyBalanceProperty().set(tblCompanyBalance);
        tblCompanyBalanceBankAccountProperty().set(tblCompanyBalanceBankAccount);
        tblEmployeeByLastUpdatedByProperty().set(tblEmployeeByLastUpdatedBy);
        tblEmployeeByIdemployeeProperty().set(tblEmployeeByIdemployee);
        tblEmployeeByCreatedByProperty().set(tblEmployeeByCreatedBy);
        tblEmployeeBankAccountProperty().set(tblEmployeeBankAccount);
        historyDateProperty().set(historyDate);
        employeePaymentDebtNominalProperty().set(employeePaymentDebtNominal);
        historyNoteProperty().set(historyNote);
        createdDateProperty().set(createdDate);
        lastUpdatedDateProperty().set(lastUpdatedDate);

    }

    public TblCalendarEmployeePaymentHistory(TblCalendarEmployeePaymentHistory tblCalendarEmployeePaymentHistory) {
        this();
        idhistoryProperty().set(tblCalendarEmployeePaymentHistory.getIdhistory());
        refFinanceTransactionPaymentTypeProperty().set(tblCalendarEmployeePaymentHistory.getRefFinanceTransactionPaymentType());
        refRecordStatusProperty().set(tblCalendarEmployeePaymentHistory.getRefRecordStatus());
        tblCompanyBalanceProperty().set(tblCalendarEmployeePaymentHistory.getTblCompanyBalance());
        tblCompanyBalanceBankAccountProperty().set(tblCalendarEmployeePaymentHistory.getTblCompanyBalanceBankAccount());
        tblEmployeeByLastUpdatedByProperty().set(tblCalendarEmployeePaymentHistory.getTblEmployeeByLastUpdatedBy());
        tblEmployeeByIdemployeeProperty().set(tblCalendarEmployeePaymentHistory.getTblEmployeeByIdemployee());
        tblEmployeeByCreatedByProperty().set(tblCalendarEmployeePaymentHistory.getTblEmployeeByCreatedBy());
        tblEmployeeBankAccountProperty().set(tblCalendarEmployeePaymentHistory.getTblEmployeeBankAccount());
        historyDateProperty().set(tblCalendarEmployeePaymentHistory.getHistoryDate());
        employeePaymentDebtNominalProperty().set(tblCalendarEmployeePaymentHistory.getEmployeePaymentDebtNominal());
        historyNoteProperty().set(tblCalendarEmployeePaymentHistory.getHistoryNote());
        createdDateProperty().set(tblCalendarEmployeePaymentHistory.getCreatedDate());
        lastUpdatedDateProperty().set(tblCalendarEmployeePaymentHistory.getLastUpdatedDate());

    }

    public final LongProperty idhistoryProperty() {
        return this.idhistory;
    }

    public long getIdhistory() {
        return idhistoryProperty().get();
    }

    public void setIdhistory(long idhistory) {
        idhistoryProperty().set(idhistory);
    }

    public final ObjectProperty<RefFinanceTransactionPaymentType> refFinanceTransactionPaymentTypeProperty() {
        return this.refFinanceTransactionPaymentType;
    }

    public RefFinanceTransactionPaymentType getRefFinanceTransactionPaymentType() {
        return refFinanceTransactionPaymentTypeProperty().get();
    }

    public void setRefFinanceTransactionPaymentType(RefFinanceTransactionPaymentType refFinanceTransactionPaymentType) {
        refFinanceTransactionPaymentTypeProperty().set(refFinanceTransactionPaymentType);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblCompanyBalance> tblCompanyBalanceProperty() {
        return this.tblCompanyBalance;
    }

    public TblCompanyBalance getTblCompanyBalance() {
        return tblCompanyBalanceProperty().get();
    }

    public void setTblCompanyBalance(TblCompanyBalance tblCompanyBalance) {
        tblCompanyBalanceProperty().set(tblCompanyBalance);
    }

    public final ObjectProperty<TblCompanyBalanceBankAccount> tblCompanyBalanceBankAccountProperty() {
        return this.tblCompanyBalanceBankAccount;
    }

    public TblCompanyBalanceBankAccount getTblCompanyBalanceBankAccount() {
        return tblCompanyBalanceBankAccountProperty().get();
    }

    public void setTblCompanyBalanceBankAccount(TblCompanyBalanceBankAccount tblCompanyBalanceBankAccount) {
        tblCompanyBalanceBankAccountProperty().set(tblCompanyBalanceBankAccount);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdatedByProperty() {
        return this.tblEmployeeByLastUpdatedBy;
    }

    public TblEmployee getTblEmployeeByLastUpdatedBy() {
        return tblEmployeeByLastUpdatedByProperty().get();
    }

    public void setTblEmployeeByLastUpdatedBy(TblEmployee tblEmployeeByLastUpdatedBy) {
        tblEmployeeByLastUpdatedByProperty().set(tblEmployeeByLastUpdatedBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByIdemployeeProperty() {
        return this.tblEmployeeByIdemployee;
    }

    public TblEmployee getTblEmployeeByIdemployee() {
        return tblEmployeeByIdemployeeProperty().get();
    }

    public void setTblEmployeeByIdemployee(TblEmployee tblEmployeeByIdemployee) {
        tblEmployeeByIdemployeeProperty().set(tblEmployeeByIdemployee);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreatedByProperty() {
        return this.tblEmployeeByCreatedBy;
    }

    public TblEmployee getTblEmployeeByCreatedBy() {
        return tblEmployeeByCreatedByProperty().get();
    }

    public void setTblEmployeeByCreatedBy(TblEmployee tblEmployeeByCreatedBy) {
        tblEmployeeByCreatedByProperty().set(tblEmployeeByCreatedBy);
    }

    public final ObjectProperty<TblEmployeeBankAccount> tblEmployeeBankAccountProperty() {
        return this.tblEmployeeBankAccount;
    }

    public TblEmployeeBankAccount getTblEmployeeBankAccount() {
        return tblEmployeeBankAccountProperty().get();
    }

    public void setTblEmployeeBankAccount(TblEmployeeBankAccount tblEmployeeBankAccount) {
        tblEmployeeBankAccountProperty().set(tblEmployeeBankAccount);
    }

    public final ObjectProperty<Date> historyDateProperty() {
        return this.historyDate;
    }

    public Date getHistoryDate() {
        return historyDateProperty().get();
    }

    public void setHistoryDate(Date historyDate) {
        historyDateProperty().set(historyDate);
    }

    public final ObjectProperty<BigDecimal> employeePaymentDebtNominalProperty() {
        return this.employeePaymentDebtNominal;
    }

    public BigDecimal getEmployeePaymentDebtNominal() {
        return employeePaymentDebtNominalProperty().get();
    }

    public void setEmployeePaymentDebtNominal(BigDecimal employeePaymentDebtNominal) {
        employeePaymentDebtNominalProperty().set(employeePaymentDebtNominal);
    }

    public final StringProperty historyNoteProperty() {
        return this.historyNote;
    }

    public String getHistoryNote() {
        return historyNoteProperty().get();
    }

    public void setHistoryNote(String historyNote) {
        historyNoteProperty().set(historyNote);
    }

    public final ObjectProperty<Date> createdDateProperty() {
        return this.createdDate;
    }

    public Date getCreatedDate() {
        return createdDateProperty().get();
    }

    public void setCreatedDate(Date createdDate) {
        createdDateProperty().set(createdDate);
    }

    public final ObjectProperty<Date> lastUpdatedDateProperty() {
        return this.lastUpdatedDate;
    }

    public Date getLastUpdatedDate() {
        return lastUpdatedDateProperty().get();
    }

    public void setLastUpdatedDate(Date lastUpdatedDate) {
        lastUpdatedDateProperty().set(lastUpdatedDate);
    }

}
