package hotelfx.persistence.model;
// Generated Apr 27, 2018 3:35:28 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.sql.Time;
import java.util.Date;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblCalendarEmployeeOvertime generated by hbm2java
 */
public class TblCalendarEmployeeOvertime implements java.io.Serializable {

    private final LongProperty idrelation;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<SysCalendar> sysCalendar;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByIdemployee;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<Time> beginTime;
    private final ObjectProperty<Time> endTime;
    private final ObjectProperty<BigDecimal> nominal;
    private final StringProperty note;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    public TblCalendarEmployeeOvertime() {
        this.idrelation = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.sysCalendar = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByIdemployee = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.beginTime = new SimpleObjectProperty<>();
        this.endTime = new SimpleObjectProperty<>();
        this.nominal = new SimpleObjectProperty<>();
        this.note = new SimpleStringProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

    }

    public TblCalendarEmployeeOvertime(long idrelation) {
        this();
        idrelationProperty().set(idrelation);
    }

    public TblCalendarEmployeeOvertime(long idrelation, RefRecordStatus refRecordStatus, SysCalendar sysCalendar, TblEmployee tblEmployeeByLastUpdateBy, TblEmployee tblEmployeeByIdemployee, TblEmployee tblEmployeeByCreateBy, Time beginTime, Time endTime, BigDecimal nominal, String note, Date createDate, Date lastUpdateDate) {
        this();
        idrelationProperty().set(idrelation);
        refRecordStatusProperty().set(refRecordStatus);
        sysCalendarProperty().set(sysCalendar);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblEmployeeByIdemployeeProperty().set(tblEmployeeByIdemployee);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        beginTimeProperty().set(beginTime);
        endTimeProperty().set(endTime);
        nominalProperty().set(nominal);
        noteProperty().set(note);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

    }

    public TblCalendarEmployeeOvertime(TblCalendarEmployeeOvertime tblCalendarEmployeeOvertime) {
        this();
        idrelationProperty().set(tblCalendarEmployeeOvertime.getIdrelation());
        refRecordStatusProperty().set(tblCalendarEmployeeOvertime.getRefRecordStatus());
        sysCalendarProperty().set(tblCalendarEmployeeOvertime.getSysCalendar());
        tblEmployeeByLastUpdateByProperty().set(tblCalendarEmployeeOvertime.getTblEmployeeByLastUpdateBy());
        tblEmployeeByIdemployeeProperty().set(tblCalendarEmployeeOvertime.getTblEmployeeByIdemployee());
        tblEmployeeByCreateByProperty().set(tblCalendarEmployeeOvertime.getTblEmployeeByCreateBy());
        beginTimeProperty().set(tblCalendarEmployeeOvertime.getBeginTime());
        endTimeProperty().set(tblCalendarEmployeeOvertime.getEndTime());
        nominalProperty().set(tblCalendarEmployeeOvertime.getNominal());
        noteProperty().set(tblCalendarEmployeeOvertime.getNote());
        createDateProperty().set(tblCalendarEmployeeOvertime.getCreateDate());
        lastUpdateDateProperty().set(tblCalendarEmployeeOvertime.getLastUpdateDate());

    }

    public final LongProperty idrelationProperty() {
        return this.idrelation;
    }

    public long getIdrelation() {
        return idrelationProperty().get();
    }

    public void setIdrelation(long idrelation) {
        idrelationProperty().set(idrelation);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<SysCalendar> sysCalendarProperty() {
        return this.sysCalendar;
    }

    public SysCalendar getSysCalendar() {
        return sysCalendarProperty().get();
    }

    public void setSysCalendar(SysCalendar sysCalendar) {
        sysCalendarProperty().set(sysCalendar);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByIdemployeeProperty() {
        return this.tblEmployeeByIdemployee;
    }

    public TblEmployee getTblEmployeeByIdemployee() {
        return tblEmployeeByIdemployeeProperty().get();
    }

    public void setTblEmployeeByIdemployee(TblEmployee tblEmployeeByIdemployee) {
        tblEmployeeByIdemployeeProperty().set(tblEmployeeByIdemployee);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<Time> beginTimeProperty() {
        return this.beginTime;
    }

    public Time getBeginTime() {
        return beginTimeProperty().get();
    }

    public void setBeginTime(Time beginTime) {
        beginTimeProperty().set(beginTime);
    }

    public final ObjectProperty<Time> endTimeProperty() {
        return this.endTime;
    }

    public Time getEndTime() {
        return endTimeProperty().get();
    }

    public void setEndTime(Time endTime) {
        endTimeProperty().set(endTime);
    }

    public final ObjectProperty<BigDecimal> nominalProperty() {
        return this.nominal;
    }

    public BigDecimal getNominal() {
        return nominalProperty().get();
    }

    public void setNominal(BigDecimal nominal) {
        nominalProperty().set(nominal);
    }

    public final StringProperty noteProperty() {
        return this.note;
    }

    public String getNote() {
        return noteProperty().get();
    }

    public void setNote(String note) {
        noteProperty().set(note);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

}
