package hotelfx.persistence.model;
// Generated Aug 21, 2017 1:49:32 PM by Hibernate Tools 4.3.1

import java.util.Date;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblCustomerBankAccount generated by hbm2java
 */
public class TblCustomerBankAccount implements java.io.Serializable {

    private final LongProperty idrelation;
    private final ObjectProperty<RefBankAccountHolderStatus> refBankAccountHolderStatus;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblBankAccount> tblBankAccount;
    private final ObjectProperty<TblCustomer> tblCustomer;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final StringProperty customerBankAccountNote;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    public TblCustomerBankAccount() {
        this.idrelation = new SimpleLongProperty();
        this.refBankAccountHolderStatus = new SimpleObjectProperty<>();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblBankAccount = new SimpleObjectProperty<>();
        this.tblCustomer = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.customerBankAccountNote = new SimpleStringProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

    }

    public TblCustomerBankAccount(long idrelation) {
        this();
        idrelationProperty().set(idrelation);
    }

    public TblCustomerBankAccount(long idrelation, RefBankAccountHolderStatus refBankAccountHolderStatus, RefRecordStatus refRecordStatus, TblBankAccount tblBankAccount, TblCustomer tblCustomer, TblEmployee tblEmployeeByLastUpdateBy, TblEmployee tblEmployeeByCreateBy, String customerBankAccountNote, Date createDate, Date lastUpdateDate) {
        this();
        idrelationProperty().set(idrelation);
        refBankAccountHolderStatusProperty().set(refBankAccountHolderStatus);
        refRecordStatusProperty().set(refRecordStatus);
        tblBankAccountProperty().set(tblBankAccount);
        tblCustomerProperty().set(tblCustomer);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        customerBankAccountNoteProperty().set(customerBankAccountNote);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

    }

    public TblCustomerBankAccount(TblCustomerBankAccount tblCustomerBankAccount) {
        this();
        idrelationProperty().set(tblCustomerBankAccount.getIdrelation());
        refBankAccountHolderStatusProperty().set(tblCustomerBankAccount.getRefBankAccountHolderStatus());
        refRecordStatusProperty().set(tblCustomerBankAccount.getRefRecordStatus());
        tblBankAccountProperty().set(tblCustomerBankAccount.getTblBankAccount());
        tblCustomerProperty().set(tblCustomerBankAccount.getTblCustomer());
        tblEmployeeByLastUpdateByProperty().set(tblCustomerBankAccount.getTblEmployeeByLastUpdateBy());
        tblEmployeeByCreateByProperty().set(tblCustomerBankAccount.getTblEmployeeByCreateBy());
        customerBankAccountNoteProperty().set(tblCustomerBankAccount.getCustomerBankAccountNote());
        createDateProperty().set(tblCustomerBankAccount.getCreateDate());
        lastUpdateDateProperty().set(tblCustomerBankAccount.getLastUpdateDate());

    }

    public final LongProperty idrelationProperty() {
        return this.idrelation;
    }

    public long getIdrelation() {
        return idrelationProperty().get();
    }

    public void setIdrelation(long idrelation) {
        idrelationProperty().set(idrelation);
    }

    public final ObjectProperty<RefBankAccountHolderStatus> refBankAccountHolderStatusProperty() {
        return this.refBankAccountHolderStatus;
    }

    public RefBankAccountHolderStatus getRefBankAccountHolderStatus() {
        return refBankAccountHolderStatusProperty().get();
    }

    public void setRefBankAccountHolderStatus(RefBankAccountHolderStatus refBankAccountHolderStatus) {
        refBankAccountHolderStatusProperty().set(refBankAccountHolderStatus);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblBankAccount> tblBankAccountProperty() {
        return this.tblBankAccount;
    }

    public TblBankAccount getTblBankAccount() {
        return tblBankAccountProperty().get();
    }

    public void setTblBankAccount(TblBankAccount tblBankAccount) {
        tblBankAccountProperty().set(tblBankAccount);
    }

    public final ObjectProperty<TblCustomer> tblCustomerProperty() {
        return this.tblCustomer;
    }

    public TblCustomer getTblCustomer() {
        return tblCustomerProperty().get();
    }

    public void setTblCustomer(TblCustomer tblCustomer) {
        tblCustomerProperty().set(tblCustomer);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final StringProperty customerBankAccountNoteProperty() {
        return this.customerBankAccountNote;
    }

    public String getCustomerBankAccountNote() {
        return customerBankAccountNoteProperty().get();
    }

    public void setCustomerBankAccountNote(String customerBankAccountNote) {
        customerBankAccountNoteProperty().set(customerBankAccountNote);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

}
