package hotelfx.persistence.model;
// Generated Apr 20, 2018 2:26:31 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblCalendarEmployeePaymentDebtHistory generated by hbm2java
 */
public class TblCalendarEmployeePaymentDebtHistory implements java.io.Serializable {

    private final LongProperty idemployeePaymentDebt;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<SysCalendar> sysCalendar;
    private final ObjectProperty<TblCalendarEmployeeDebt> tblCalendarEmployeeDebt;
    private final ObjectProperty<TblCompanyBalance> tblCompanyBalance;
    private final ObjectProperty<TblCompanyBalanceBankAccount> tblCompanyBalanceBankAccount;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreatedBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdatedBy;
    private final ObjectProperty<BigDecimal> employeePaymentDebtNominal;
    private final StringProperty employeePaymentDebtNote;
    private final ObjectProperty<Date> createdDate;
    private final ObjectProperty<Date> lastUpdatedDate;

    public TblCalendarEmployeePaymentDebtHistory() {
        this.idemployeePaymentDebt = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.sysCalendar = new SimpleObjectProperty<>();
        this.tblCalendarEmployeeDebt = new SimpleObjectProperty<>();
        this.tblCompanyBalance = new SimpleObjectProperty<>();
        this.tblCompanyBalanceBankAccount = new SimpleObjectProperty<>();
        this.tblEmployeeByCreatedBy = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdatedBy = new SimpleObjectProperty<>();
        this.employeePaymentDebtNominal = new SimpleObjectProperty<>();
        this.employeePaymentDebtNote = new SimpleStringProperty();
        this.createdDate = new SimpleObjectProperty<>();
        this.lastUpdatedDate = new SimpleObjectProperty<>();

    }

    public TblCalendarEmployeePaymentDebtHistory(long idemployeePaymentDebt) {
        this();
        idemployeePaymentDebtProperty().set(idemployeePaymentDebt);
    }

    public TblCalendarEmployeePaymentDebtHistory(long idemployeePaymentDebt, RefRecordStatus refRecordStatus, SysCalendar sysCalendar, TblCalendarEmployeeDebt tblCalendarEmployeeDebt, TblCompanyBalance tblCompanyBalance, TblCompanyBalanceBankAccount tblCompanyBalanceBankAccount, TblEmployee tblEmployeeByCreatedBy, TblEmployee tblEmployeeByLastUpdatedBy, BigDecimal employeePaymentDebtNominal, String employeePaymentDebtNote, Date createdDate, Date lastUpdatedDate) {
        this();
        idemployeePaymentDebtProperty().set(idemployeePaymentDebt);
        refRecordStatusProperty().set(refRecordStatus);
        sysCalendarProperty().set(sysCalendar);
        tblCalendarEmployeeDebtProperty().set(tblCalendarEmployeeDebt);
        tblCompanyBalanceProperty().set(tblCompanyBalance);
        tblCompanyBalanceBankAccountProperty().set(tblCompanyBalanceBankAccount);
        tblEmployeeByCreatedByProperty().set(tblEmployeeByCreatedBy);
        tblEmployeeByLastUpdatedByProperty().set(tblEmployeeByLastUpdatedBy);
        employeePaymentDebtNominalProperty().set(employeePaymentDebtNominal);
        employeePaymentDebtNoteProperty().set(employeePaymentDebtNote);
        createdDateProperty().set(createdDate);
        lastUpdatedDateProperty().set(lastUpdatedDate);

    }

    public TblCalendarEmployeePaymentDebtHistory(TblCalendarEmployeePaymentDebtHistory tblCalendarEmployeePaymentDebtHistory) {
        this();
        idemployeePaymentDebtProperty().set(tblCalendarEmployeePaymentDebtHistory.getIdemployeePaymentDebt());
        refRecordStatusProperty().set(tblCalendarEmployeePaymentDebtHistory.getRefRecordStatus());
        sysCalendarProperty().set(tblCalendarEmployeePaymentDebtHistory.getSysCalendar());
        tblCalendarEmployeeDebtProperty().set(tblCalendarEmployeePaymentDebtHistory.getTblCalendarEmployeeDebt());
        tblCompanyBalanceProperty().set(tblCalendarEmployeePaymentDebtHistory.getTblCompanyBalance());
        tblCompanyBalanceBankAccountProperty().set(tblCalendarEmployeePaymentDebtHistory.getTblCompanyBalanceBankAccount());
        tblEmployeeByCreatedByProperty().set(tblCalendarEmployeePaymentDebtHistory.getTblEmployeeByCreatedBy());
        tblEmployeeByLastUpdatedByProperty().set(tblCalendarEmployeePaymentDebtHistory.getTblEmployeeByLastUpdatedBy());
        employeePaymentDebtNominalProperty().set(tblCalendarEmployeePaymentDebtHistory.getEmployeePaymentDebtNominal());
        employeePaymentDebtNoteProperty().set(tblCalendarEmployeePaymentDebtHistory.getEmployeePaymentDebtNote());
        createdDateProperty().set(tblCalendarEmployeePaymentDebtHistory.getCreatedDate());
        lastUpdatedDateProperty().set(tblCalendarEmployeePaymentDebtHistory.getLastUpdatedDate());

    }

    public final LongProperty idemployeePaymentDebtProperty() {
        return this.idemployeePaymentDebt;
    }

    public long getIdemployeePaymentDebt() {
        return idemployeePaymentDebtProperty().get();
    }

    public void setIdemployeePaymentDebt(long idemployeePaymentDebt) {
        idemployeePaymentDebtProperty().set(idemployeePaymentDebt);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<SysCalendar> sysCalendarProperty() {
        return this.sysCalendar;
    }

    public SysCalendar getSysCalendar() {
        return sysCalendarProperty().get();
    }

    public void setSysCalendar(SysCalendar sysCalendar) {
        sysCalendarProperty().set(sysCalendar);
    }

    public final ObjectProperty<TblCalendarEmployeeDebt> tblCalendarEmployeeDebtProperty() {
        return this.tblCalendarEmployeeDebt;
    }

    public TblCalendarEmployeeDebt getTblCalendarEmployeeDebt() {
        return tblCalendarEmployeeDebtProperty().get();
    }

    public void setTblCalendarEmployeeDebt(TblCalendarEmployeeDebt tblCalendarEmployeeDebt) {
        tblCalendarEmployeeDebtProperty().set(tblCalendarEmployeeDebt);
    }

    public final ObjectProperty<TblCompanyBalance> tblCompanyBalanceProperty() {
        return this.tblCompanyBalance;
    }

    public TblCompanyBalance getTblCompanyBalance() {
        return tblCompanyBalanceProperty().get();
    }

    public void setTblCompanyBalance(TblCompanyBalance tblCompanyBalance) {
        tblCompanyBalanceProperty().set(tblCompanyBalance);
    }

    public final ObjectProperty<TblCompanyBalanceBankAccount> tblCompanyBalanceBankAccountProperty() {
        return this.tblCompanyBalanceBankAccount;
    }

    public TblCompanyBalanceBankAccount getTblCompanyBalanceBankAccount() {
        return tblCompanyBalanceBankAccountProperty().get();
    }

    public void setTblCompanyBalanceBankAccount(TblCompanyBalanceBankAccount tblCompanyBalanceBankAccount) {
        tblCompanyBalanceBankAccountProperty().set(tblCompanyBalanceBankAccount);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreatedByProperty() {
        return this.tblEmployeeByCreatedBy;
    }

    public TblEmployee getTblEmployeeByCreatedBy() {
        return tblEmployeeByCreatedByProperty().get();
    }

    public void setTblEmployeeByCreatedBy(TblEmployee tblEmployeeByCreatedBy) {
        tblEmployeeByCreatedByProperty().set(tblEmployeeByCreatedBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdatedByProperty() {
        return this.tblEmployeeByLastUpdatedBy;
    }

    public TblEmployee getTblEmployeeByLastUpdatedBy() {
        return tblEmployeeByLastUpdatedByProperty().get();
    }

    public void setTblEmployeeByLastUpdatedBy(TblEmployee tblEmployeeByLastUpdatedBy) {
        tblEmployeeByLastUpdatedByProperty().set(tblEmployeeByLastUpdatedBy);
    }

    public final ObjectProperty<BigDecimal> employeePaymentDebtNominalProperty() {
        return this.employeePaymentDebtNominal;
    }

    public BigDecimal getEmployeePaymentDebtNominal() {
        return employeePaymentDebtNominalProperty().get();
    }

    public void setEmployeePaymentDebtNominal(BigDecimal employeePaymentDebtNominal) {
        employeePaymentDebtNominalProperty().set(employeePaymentDebtNominal);
    }

    public final StringProperty employeePaymentDebtNoteProperty() {
        return this.employeePaymentDebtNote;
    }

    public String getEmployeePaymentDebtNote() {
        return employeePaymentDebtNoteProperty().get();
    }

    public void setEmployeePaymentDebtNote(String employeePaymentDebtNote) {
        employeePaymentDebtNoteProperty().set(employeePaymentDebtNote);
    }

    public final ObjectProperty<Date> createdDateProperty() {
        return this.createdDate;
    }

    public Date getCreatedDate() {
        return createdDateProperty().get();
    }

    public void setCreatedDate(Date createdDate) {
        createdDateProperty().set(createdDate);
    }

    public final ObjectProperty<Date> lastUpdatedDateProperty() {
        return this.lastUpdatedDate;
    }

    public Date getLastUpdatedDate() {
        return lastUpdatedDateProperty().get();
    }

    public void setLastUpdatedDate(Date lastUpdatedDate) {
        lastUpdatedDateProperty().set(lastUpdatedDate);
    }

}
