package hotelfx.persistence.model;
// Generated Sep 27, 2018 10:59:47 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblCalendarEmployeeDebt generated by hbm2java
 */
public class TblCalendarEmployeeDebt implements java.io.Serializable {

    private final LongProperty idemployeeDebt;
    private final ObjectProperty<RefFinanceTransactionPaymentType> refFinanceTransactionPaymentType;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblCompanyBalance> tblCompanyBalance;
    private final ObjectProperty<TblCompanyBalanceBankAccount> tblCompanyBalanceBankAccount;
    private final ObjectProperty<TblEmployee> tblEmployeeByIdemployee;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreatedBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdatedBy;
    private final ObjectProperty<TblEmployeeBankAccount> tblEmployeeBankAccount;
    private final ObjectProperty<Date> approvedDate;
    private final ObjectProperty<Date> rejectDate;
    private final ObjectProperty<BigDecimal> employeeDebtNominal;
    private final StringProperty employeeDebtNote;
    private final StringProperty employeeRejectNote;
    private final StringProperty employeeCanceledNote;
    private final StringProperty employeeDebtPaymentStatus;
    private final StringProperty employeeDebtStatus;
    private final ObjectProperty<Date> createdDate;
    private final ObjectProperty<Date> lastUpdatedDate;

    private Set tblCalendarEmployeePaymentDebtHistories;

    public TblCalendarEmployeeDebt() {
        this.idemployeeDebt = new SimpleLongProperty();
        this.refFinanceTransactionPaymentType = new SimpleObjectProperty<>();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblCompanyBalance = new SimpleObjectProperty<>();
        this.tblCompanyBalanceBankAccount = new SimpleObjectProperty<>();
        this.tblEmployeeByIdemployee = new SimpleObjectProperty<>();
        this.tblEmployeeByCreatedBy = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdatedBy = new SimpleObjectProperty<>();
        this.tblEmployeeBankAccount = new SimpleObjectProperty<>();
        this.approvedDate = new SimpleObjectProperty<>();
        this.rejectDate = new SimpleObjectProperty<>();
        this.employeeDebtNominal = new SimpleObjectProperty<>();
        this.employeeDebtNote = new SimpleStringProperty();
        this.employeeRejectNote = new SimpleStringProperty();
        this.employeeCanceledNote = new SimpleStringProperty();
        this.employeeDebtPaymentStatus = new SimpleStringProperty();
        this.employeeDebtStatus = new SimpleStringProperty();
        this.createdDate = new SimpleObjectProperty<>();
        this.lastUpdatedDate = new SimpleObjectProperty<>();

        this.tblCalendarEmployeePaymentDebtHistories = new HashSet(0);
    }

    public TblCalendarEmployeeDebt(long idemployeeDebt) {
        this();
        idemployeeDebtProperty().set(idemployeeDebt);
    }

    public TblCalendarEmployeeDebt(long idemployeeDebt, RefFinanceTransactionPaymentType refFinanceTransactionPaymentType, RefRecordStatus refRecordStatus, TblCompanyBalance tblCompanyBalance, TblCompanyBalanceBankAccount tblCompanyBalanceBankAccount, TblEmployee tblEmployeeByIdemployee, TblEmployee tblEmployeeByCreatedBy, TblEmployee tblEmployeeByLastUpdatedBy, TblEmployeeBankAccount tblEmployeeBankAccount, Date approvedDate, Date rejectDate, BigDecimal employeeDebtNominal, String employeeDebtNote, String employeeRejectNote, String employeeCanceledNote, String employeeDebtPaymentStatus, String employeeDebtStatus, Date createdDate, Date lastUpdatedDate, Set tblCalendarEmployeePaymentDebtHistories) {
        this();
        idemployeeDebtProperty().set(idemployeeDebt);
        refFinanceTransactionPaymentTypeProperty().set(refFinanceTransactionPaymentType);
        refRecordStatusProperty().set(refRecordStatus);
        tblCompanyBalanceProperty().set(tblCompanyBalance);
        tblCompanyBalanceBankAccountProperty().set(tblCompanyBalanceBankAccount);
        tblEmployeeByIdemployeeProperty().set(tblEmployeeByIdemployee);
        tblEmployeeByCreatedByProperty().set(tblEmployeeByCreatedBy);
        tblEmployeeByLastUpdatedByProperty().set(tblEmployeeByLastUpdatedBy);
        tblEmployeeBankAccountProperty().set(tblEmployeeBankAccount);
        approvedDateProperty().set(approvedDate);
        rejectDateProperty().set(rejectDate);
        employeeDebtNominalProperty().set(employeeDebtNominal);
        employeeDebtNoteProperty().set(employeeDebtNote);
        employeeRejectNoteProperty().set(employeeRejectNote);
        employeeCanceledNoteProperty().set(employeeCanceledNote);
        employeeDebtPaymentStatusProperty().set(employeeDebtPaymentStatus);
        employeeDebtStatusProperty().set(employeeDebtStatus);
        createdDateProperty().set(createdDate);
        lastUpdatedDateProperty().set(lastUpdatedDate);

        this.tblCalendarEmployeePaymentDebtHistories = tblCalendarEmployeePaymentDebtHistories;
    }

    public TblCalendarEmployeeDebt(TblCalendarEmployeeDebt tblCalendarEmployeeDebt) {
        this();
        idemployeeDebtProperty().set(tblCalendarEmployeeDebt.getIdemployeeDebt());
        refFinanceTransactionPaymentTypeProperty().set(tblCalendarEmployeeDebt.getRefFinanceTransactionPaymentType());
        refRecordStatusProperty().set(tblCalendarEmployeeDebt.getRefRecordStatus());
        tblCompanyBalanceProperty().set(tblCalendarEmployeeDebt.getTblCompanyBalance());
        tblCompanyBalanceBankAccountProperty().set(tblCalendarEmployeeDebt.getTblCompanyBalanceBankAccount());
        tblEmployeeByIdemployeeProperty().set(tblCalendarEmployeeDebt.getTblEmployeeByIdemployee());
        tblEmployeeByCreatedByProperty().set(tblCalendarEmployeeDebt.getTblEmployeeByCreatedBy());
        tblEmployeeByLastUpdatedByProperty().set(tblCalendarEmployeeDebt.getTblEmployeeByLastUpdatedBy());
        tblEmployeeBankAccountProperty().set(tblCalendarEmployeeDebt.getTblEmployeeBankAccount());
        approvedDateProperty().set(tblCalendarEmployeeDebt.getApprovedDate());
        rejectDateProperty().set(tblCalendarEmployeeDebt.getRejectDate());
        employeeDebtNominalProperty().set(tblCalendarEmployeeDebt.getEmployeeDebtNominal());
        employeeDebtNoteProperty().set(tblCalendarEmployeeDebt.getEmployeeDebtNote());
        employeeRejectNoteProperty().set(tblCalendarEmployeeDebt.getEmployeeRejectNote());
        employeeCanceledNoteProperty().set(tblCalendarEmployeeDebt.getEmployeeCanceledNote());
        employeeDebtPaymentStatusProperty().set(tblCalendarEmployeeDebt.getEmployeeDebtPaymentStatus());
        employeeDebtStatusProperty().set(tblCalendarEmployeeDebt.getEmployeeDebtStatus());
        createdDateProperty().set(tblCalendarEmployeeDebt.getCreatedDate());
        lastUpdatedDateProperty().set(tblCalendarEmployeeDebt.getLastUpdatedDate());

        this.tblCalendarEmployeePaymentDebtHistories = tblCalendarEmployeeDebt.getTblCalendarEmployeePaymentDebtHistories();
    }

    public final LongProperty idemployeeDebtProperty() {
        return this.idemployeeDebt;
    }

    public long getIdemployeeDebt() {
        return idemployeeDebtProperty().get();
    }

    public void setIdemployeeDebt(long idemployeeDebt) {
        idemployeeDebtProperty().set(idemployeeDebt);
    }

    public final ObjectProperty<RefFinanceTransactionPaymentType> refFinanceTransactionPaymentTypeProperty() {
        return this.refFinanceTransactionPaymentType;
    }

    public RefFinanceTransactionPaymentType getRefFinanceTransactionPaymentType() {
        return refFinanceTransactionPaymentTypeProperty().get();
    }

    public void setRefFinanceTransactionPaymentType(RefFinanceTransactionPaymentType refFinanceTransactionPaymentType) {
        refFinanceTransactionPaymentTypeProperty().set(refFinanceTransactionPaymentType);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblCompanyBalance> tblCompanyBalanceProperty() {
        return this.tblCompanyBalance;
    }

    public TblCompanyBalance getTblCompanyBalance() {
        return tblCompanyBalanceProperty().get();
    }

    public void setTblCompanyBalance(TblCompanyBalance tblCompanyBalance) {
        tblCompanyBalanceProperty().set(tblCompanyBalance);
    }

    public final ObjectProperty<TblCompanyBalanceBankAccount> tblCompanyBalanceBankAccountProperty() {
        return this.tblCompanyBalanceBankAccount;
    }

    public TblCompanyBalanceBankAccount getTblCompanyBalanceBankAccount() {
        return tblCompanyBalanceBankAccountProperty().get();
    }

    public void setTblCompanyBalanceBankAccount(TblCompanyBalanceBankAccount tblCompanyBalanceBankAccount) {
        tblCompanyBalanceBankAccountProperty().set(tblCompanyBalanceBankAccount);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByIdemployeeProperty() {
        return this.tblEmployeeByIdemployee;
    }

    public TblEmployee getTblEmployeeByIdemployee() {
        return tblEmployeeByIdemployeeProperty().get();
    }

    public void setTblEmployeeByIdemployee(TblEmployee tblEmployeeByIdemployee) {
        tblEmployeeByIdemployeeProperty().set(tblEmployeeByIdemployee);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreatedByProperty() {
        return this.tblEmployeeByCreatedBy;
    }

    public TblEmployee getTblEmployeeByCreatedBy() {
        return tblEmployeeByCreatedByProperty().get();
    }

    public void setTblEmployeeByCreatedBy(TblEmployee tblEmployeeByCreatedBy) {
        tblEmployeeByCreatedByProperty().set(tblEmployeeByCreatedBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdatedByProperty() {
        return this.tblEmployeeByLastUpdatedBy;
    }

    public TblEmployee getTblEmployeeByLastUpdatedBy() {
        return tblEmployeeByLastUpdatedByProperty().get();
    }

    public void setTblEmployeeByLastUpdatedBy(TblEmployee tblEmployeeByLastUpdatedBy) {
        tblEmployeeByLastUpdatedByProperty().set(tblEmployeeByLastUpdatedBy);
    }

    public final ObjectProperty<TblEmployeeBankAccount> tblEmployeeBankAccountProperty() {
        return this.tblEmployeeBankAccount;
    }

    public TblEmployeeBankAccount getTblEmployeeBankAccount() {
        return tblEmployeeBankAccountProperty().get();
    }

    public void setTblEmployeeBankAccount(TblEmployeeBankAccount tblEmployeeBankAccount) {
        tblEmployeeBankAccountProperty().set(tblEmployeeBankAccount);
    }

    public final ObjectProperty<Date> approvedDateProperty() {
        return this.approvedDate;
    }

    public Date getApprovedDate() {
        return approvedDateProperty().get();
    }

    public void setApprovedDate(Date approvedDate) {
        approvedDateProperty().set(approvedDate);
    }

    public final ObjectProperty<Date> rejectDateProperty() {
        return this.rejectDate;
    }

    public Date getRejectDate() {
        return rejectDateProperty().get();
    }

    public void setRejectDate(Date rejectDate) {
        rejectDateProperty().set(rejectDate);
    }

    public final ObjectProperty<BigDecimal> employeeDebtNominalProperty() {
        return this.employeeDebtNominal;
    }

    public BigDecimal getEmployeeDebtNominal() {
        return employeeDebtNominalProperty().get();
    }

    public void setEmployeeDebtNominal(BigDecimal employeeDebtNominal) {
        employeeDebtNominalProperty().set(employeeDebtNominal);
    }

    public final StringProperty employeeDebtNoteProperty() {
        return this.employeeDebtNote;
    }

    public String getEmployeeDebtNote() {
        return employeeDebtNoteProperty().get();
    }

    public void setEmployeeDebtNote(String employeeDebtNote) {
        employeeDebtNoteProperty().set(employeeDebtNote);
    }

    public final StringProperty employeeRejectNoteProperty() {
        return this.employeeRejectNote;
    }

    public String getEmployeeRejectNote() {
        return employeeRejectNoteProperty().get();
    }

    public void setEmployeeRejectNote(String employeeRejectNote) {
        employeeRejectNoteProperty().set(employeeRejectNote);
    }

    public final StringProperty employeeCanceledNoteProperty() {
        return this.employeeCanceledNote;
    }

    public String getEmployeeCanceledNote() {
        return employeeCanceledNoteProperty().get();
    }

    public void setEmployeeCanceledNote(String employeeCanceledNote) {
        employeeCanceledNoteProperty().set(employeeCanceledNote);
    }

    public final StringProperty employeeDebtPaymentStatusProperty() {
        return this.employeeDebtPaymentStatus;
    }

    public String getEmployeeDebtPaymentStatus() {
        return employeeDebtPaymentStatusProperty().get();
    }

    public void setEmployeeDebtPaymentStatus(String employeeDebtPaymentStatus) {
        employeeDebtPaymentStatusProperty().set(employeeDebtPaymentStatus);
    }

    public final StringProperty employeeDebtStatusProperty() {
        return this.employeeDebtStatus;
    }

    public String getEmployeeDebtStatus() {
        return employeeDebtStatusProperty().get();
    }

    public void setEmployeeDebtStatus(String employeeDebtStatus) {
        employeeDebtStatusProperty().set(employeeDebtStatus);
    }

    public final ObjectProperty<Date> createdDateProperty() {
        return this.createdDate;
    }

    public Date getCreatedDate() {
        return createdDateProperty().get();
    }

    public void setCreatedDate(Date createdDate) {
        createdDateProperty().set(createdDate);
    }

    public final ObjectProperty<Date> lastUpdatedDateProperty() {
        return this.lastUpdatedDate;
    }

    public Date getLastUpdatedDate() {
        return lastUpdatedDateProperty().get();
    }

    public void setLastUpdatedDate(Date lastUpdatedDate) {
        lastUpdatedDateProperty().set(lastUpdatedDate);
    }

    public Set getTblCalendarEmployeePaymentDebtHistories() {
        return this.tblCalendarEmployeePaymentDebtHistories;
    }

    public void setTblCalendarEmployeePaymentDebtHistories(Set tblCalendarEmployeePaymentDebtHistories) {
        this.tblCalendarEmployeePaymentDebtHistories = tblCalendarEmployeePaymentDebtHistories;
    }

}
