package hotelfx.persistence.model;
// Generated Dec 18, 2017 3:39:13 PM by Hibernate Tools 4.3.1

import java.sql.Time;
import java.util.Date;

import javafx.beans.property.BooleanProperty;
import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleBooleanProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblCalendarEmployeeAttendance generated by hbm2java
 */
public class TblCalendarEmployeeAttendance implements java.io.Serializable {

    private final LongProperty idrelation;
    private final ObjectProperty<RefEmployeeAttendanceEndStatus> refEmployeeAttendanceEndStatus;
    private final ObjectProperty<RefEmployeeAttendanceStartStatus> refEmployeeAttendanceStartStatus;
    private final ObjectProperty<RefEmployeeAttendanceStatus> refEmployeeAttendanceStatus;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<SysCalendar> sysCalendar;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByIdemployee;
    private final StringProperty codeFingerPrint;
    private final StringProperty scheduleName;
    private final ObjectProperty<Time> beginSchedule;
    private final ObjectProperty<Time> endSchedule;
    private final ObjectProperty<Date> beginReal;
    private final ObjectProperty<Date> endReal;
    private final BooleanProperty isOvertime;
    private final StringProperty note;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    public TblCalendarEmployeeAttendance() {
        this.idrelation = new SimpleLongProperty();
        this.refEmployeeAttendanceEndStatus = new SimpleObjectProperty<>();
        this.refEmployeeAttendanceStartStatus = new SimpleObjectProperty<>();
        this.refEmployeeAttendanceStatus = new SimpleObjectProperty<>();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.sysCalendar = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByIdemployee = new SimpleObjectProperty<>();
        this.codeFingerPrint = new SimpleStringProperty();
        this.scheduleName = new SimpleStringProperty();
        this.beginSchedule = new SimpleObjectProperty<>();
        this.endSchedule = new SimpleObjectProperty<>();
        this.beginReal = new SimpleObjectProperty<>();
        this.endReal = new SimpleObjectProperty<>();
        this.isOvertime = new SimpleBooleanProperty();
        this.note = new SimpleStringProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

    }

    public TblCalendarEmployeeAttendance(long idrelation) {
        this();
        idrelationProperty().set(idrelation);
    }

    public TblCalendarEmployeeAttendance(long idrelation, RefEmployeeAttendanceEndStatus refEmployeeAttendanceEndStatus, RefEmployeeAttendanceStartStatus refEmployeeAttendanceStartStatus, RefEmployeeAttendanceStatus refEmployeeAttendanceStatus, RefRecordStatus refRecordStatus, SysCalendar sysCalendar, TblEmployee tblEmployeeByLastUpdateBy, TblEmployee tblEmployeeByCreateBy, TblEmployee tblEmployeeByIdemployee, String codeFingerPrint, String scheduleName, Time beginSchedule, Time endSchedule, Date beginReal, Date endReal, Boolean isOvertime, String note, Date createDate, Date lastUpdateDate) {
        this();
        idrelationProperty().set(idrelation);
        refEmployeeAttendanceEndStatusProperty().set(refEmployeeAttendanceEndStatus);
        refEmployeeAttendanceStartStatusProperty().set(refEmployeeAttendanceStartStatus);
        refEmployeeAttendanceStatusProperty().set(refEmployeeAttendanceStatus);
        refRecordStatusProperty().set(refRecordStatus);
        sysCalendarProperty().set(sysCalendar);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblEmployeeByIdemployeeProperty().set(tblEmployeeByIdemployee);
        codeFingerPrintProperty().set(codeFingerPrint);
        scheduleNameProperty().set(scheduleName);
        beginScheduleProperty().set(beginSchedule);
        endScheduleProperty().set(endSchedule);
        beginRealProperty().set(beginReal);
        endRealProperty().set(endReal);
        isOvertimeProperty().set(isOvertime);
        noteProperty().set(note);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

    }

    public TblCalendarEmployeeAttendance(TblCalendarEmployeeAttendance tblCalendarEmployeeAttendance) {
        this();
        idrelationProperty().set(tblCalendarEmployeeAttendance.getIdrelation());
        refEmployeeAttendanceEndStatusProperty().set(tblCalendarEmployeeAttendance.getRefEmployeeAttendanceEndStatus());
        refEmployeeAttendanceStartStatusProperty().set(tblCalendarEmployeeAttendance.getRefEmployeeAttendanceStartStatus());
        refEmployeeAttendanceStatusProperty().set(tblCalendarEmployeeAttendance.getRefEmployeeAttendanceStatus());
        refRecordStatusProperty().set(tblCalendarEmployeeAttendance.getRefRecordStatus());
        sysCalendarProperty().set(tblCalendarEmployeeAttendance.getSysCalendar());
        tblEmployeeByLastUpdateByProperty().set(tblCalendarEmployeeAttendance.getTblEmployeeByLastUpdateBy());
        tblEmployeeByCreateByProperty().set(tblCalendarEmployeeAttendance.getTblEmployeeByCreateBy());
        tblEmployeeByIdemployeeProperty().set(tblCalendarEmployeeAttendance.getTblEmployeeByIdemployee());
        codeFingerPrintProperty().set(tblCalendarEmployeeAttendance.getCodeFingerPrint());
        scheduleNameProperty().set(tblCalendarEmployeeAttendance.getScheduleName());
        beginScheduleProperty().set(tblCalendarEmployeeAttendance.getBeginSchedule());
        endScheduleProperty().set(tblCalendarEmployeeAttendance.getEndSchedule());
        beginRealProperty().set(tblCalendarEmployeeAttendance.getBeginReal());
        endRealProperty().set(tblCalendarEmployeeAttendance.getEndReal());
        isOvertimeProperty().set(tblCalendarEmployeeAttendance.getIsOvertime());
        noteProperty().set(tblCalendarEmployeeAttendance.getNote());
        createDateProperty().set(tblCalendarEmployeeAttendance.getCreateDate());
        lastUpdateDateProperty().set(tblCalendarEmployeeAttendance.getLastUpdateDate());

    }

    public final LongProperty idrelationProperty() {
        return this.idrelation;
    }

    public long getIdrelation() {
        return idrelationProperty().get();
    }

    public void setIdrelation(long idrelation) {
        idrelationProperty().set(idrelation);
    }

    public final ObjectProperty<RefEmployeeAttendanceEndStatus> refEmployeeAttendanceEndStatusProperty() {
        return this.refEmployeeAttendanceEndStatus;
    }

    public RefEmployeeAttendanceEndStatus getRefEmployeeAttendanceEndStatus() {
        return refEmployeeAttendanceEndStatusProperty().get();
    }

    public void setRefEmployeeAttendanceEndStatus(RefEmployeeAttendanceEndStatus refEmployeeAttendanceEndStatus) {
        refEmployeeAttendanceEndStatusProperty().set(refEmployeeAttendanceEndStatus);
    }

    public final ObjectProperty<RefEmployeeAttendanceStartStatus> refEmployeeAttendanceStartStatusProperty() {
        return this.refEmployeeAttendanceStartStatus;
    }

    public RefEmployeeAttendanceStartStatus getRefEmployeeAttendanceStartStatus() {
        return refEmployeeAttendanceStartStatusProperty().get();
    }

    public void setRefEmployeeAttendanceStartStatus(RefEmployeeAttendanceStartStatus refEmployeeAttendanceStartStatus) {
        refEmployeeAttendanceStartStatusProperty().set(refEmployeeAttendanceStartStatus);
    }

    public final ObjectProperty<RefEmployeeAttendanceStatus> refEmployeeAttendanceStatusProperty() {
        return this.refEmployeeAttendanceStatus;
    }

    public RefEmployeeAttendanceStatus getRefEmployeeAttendanceStatus() {
        return refEmployeeAttendanceStatusProperty().get();
    }

    public void setRefEmployeeAttendanceStatus(RefEmployeeAttendanceStatus refEmployeeAttendanceStatus) {
        refEmployeeAttendanceStatusProperty().set(refEmployeeAttendanceStatus);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<SysCalendar> sysCalendarProperty() {
        return this.sysCalendar;
    }

    public SysCalendar getSysCalendar() {
        return sysCalendarProperty().get();
    }

    public void setSysCalendar(SysCalendar sysCalendar) {
        sysCalendarProperty().set(sysCalendar);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByIdemployeeProperty() {
        return this.tblEmployeeByIdemployee;
    }

    public TblEmployee getTblEmployeeByIdemployee() {
        return tblEmployeeByIdemployeeProperty().get();
    }

    public void setTblEmployeeByIdemployee(TblEmployee tblEmployeeByIdemployee) {
        tblEmployeeByIdemployeeProperty().set(tblEmployeeByIdemployee);
    }

    public final StringProperty codeFingerPrintProperty() {
        return this.codeFingerPrint;
    }

    public String getCodeFingerPrint() {
        return codeFingerPrintProperty().get();
    }

    public void setCodeFingerPrint(String codeFingerPrint) {
        codeFingerPrintProperty().set(codeFingerPrint);
    }

    public final StringProperty scheduleNameProperty() {
        return this.scheduleName;
    }

    public String getScheduleName() {
        return scheduleNameProperty().get();
    }

    public void setScheduleName(String scheduleName) {
        scheduleNameProperty().set(scheduleName);
    }

    public final ObjectProperty<Time> beginScheduleProperty() {
        return this.beginSchedule;
    }

    public Time getBeginSchedule() {
        return beginScheduleProperty().get();
    }

    public void setBeginSchedule(Time beginSchedule) {
        beginScheduleProperty().set(beginSchedule);
    }

    public final ObjectProperty<Time> endScheduleProperty() {
        return this.endSchedule;
    }

    public Time getEndSchedule() {
        return endScheduleProperty().get();
    }

    public void setEndSchedule(Time endSchedule) {
        endScheduleProperty().set(endSchedule);
    }

    public final ObjectProperty<Date> beginRealProperty() {
        return this.beginReal;
    }

    public Date getBeginReal() {
        return beginRealProperty().get();
    }

    public void setBeginReal(Date beginReal) {
        beginRealProperty().set(beginReal);
    }

    public final ObjectProperty<Date> endRealProperty() {
        return this.endReal;
    }

    public Date getEndReal() {
        return endRealProperty().get();
    }

    public void setEndReal(Date endReal) {
        endRealProperty().set(endReal);
    }

    public final BooleanProperty isOvertimeProperty() {
        return this.isOvertime;
    }

    public Boolean getIsOvertime() {
        return isOvertimeProperty().get();
    }

    public void setIsOvertime(Boolean isOvertime) {
        isOvertimeProperty().set(isOvertime);
    }

    public final StringProperty noteProperty() {
        return this.note;
    }

    public String getNote() {
        return noteProperty().get();
    }

    public void setNote(String note) {
        noteProperty().set(note);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

}
