package hotelfx.persistence.model;
// Generated Sep 6, 2018 9:53:41 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

import javafx.beans.property.BooleanProperty;
import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleBooleanProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;

/**
 * TblCompanyBalanceTransferReceived generated by hbm2java
 */
public class TblCompanyBalanceTransferReceived implements java.io.Serializable {

    private final LongProperty idrelation;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblCompanyBalance> tblCompanyBalanceByIdcompanyBalanceSender;
    private final ObjectProperty<TblCompanyBalance> tblCompanyBalanceByIdcompanyBalanceReceived;
    private final ObjectProperty<TblCompanyBalanceBankAccount> tblCompanyBalanceBankAccountByIdcbbankAccountSender;
    private final ObjectProperty<TblCompanyBalanceBankAccount> tblCompanyBalanceBankAccountByIdcbbankAccountReceived;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreatedBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByReceivedBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdatedBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByTransferBy;
    private final ObjectProperty<BigDecimal> nominal;
    private final ObjectProperty<Date> transferDate;
    private final ObjectProperty<Date> receivedDate;
    private final BooleanProperty isReceived;
    private final ObjectProperty<Date> createdDate;
    private final ObjectProperty<Date> lastUpdatedDate;

    public TblCompanyBalanceTransferReceived() {
        this.idrelation = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblCompanyBalanceByIdcompanyBalanceSender = new SimpleObjectProperty<>();
        this.tblCompanyBalanceByIdcompanyBalanceReceived = new SimpleObjectProperty<>();
        this.tblCompanyBalanceBankAccountByIdcbbankAccountSender = new SimpleObjectProperty<>();
        this.tblCompanyBalanceBankAccountByIdcbbankAccountReceived = new SimpleObjectProperty<>();
        this.tblEmployeeByCreatedBy = new SimpleObjectProperty<>();
        this.tblEmployeeByReceivedBy = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdatedBy = new SimpleObjectProperty<>();
        this.tblEmployeeByTransferBy = new SimpleObjectProperty<>();
        this.nominal = new SimpleObjectProperty<>();
        this.transferDate = new SimpleObjectProperty<>();
        this.receivedDate = new SimpleObjectProperty<>();
        this.isReceived = new SimpleBooleanProperty();
        this.createdDate = new SimpleObjectProperty<>();
        this.lastUpdatedDate = new SimpleObjectProperty<>();

    }

    public TblCompanyBalanceTransferReceived(long idrelation) {
        this();
        idrelationProperty().set(idrelation);
    }

    public TblCompanyBalanceTransferReceived(long idrelation, RefRecordStatus refRecordStatus, TblCompanyBalance tblCompanyBalanceByIdcompanyBalanceSender, TblCompanyBalance tblCompanyBalanceByIdcompanyBalanceReceived, TblCompanyBalanceBankAccount tblCompanyBalanceBankAccountByIdcbbankAccountSender, TblCompanyBalanceBankAccount tblCompanyBalanceBankAccountByIdcbbankAccountReceived, TblEmployee tblEmployeeByCreatedBy, TblEmployee tblEmployeeByReceivedBy, TblEmployee tblEmployeeByLastUpdatedBy, TblEmployee tblEmployeeByTransferBy, BigDecimal nominal, Date transferDate, Date receivedDate, Boolean isReceived, Date createdDate, Date lastUpdatedDate) {
        this();
        idrelationProperty().set(idrelation);
        refRecordStatusProperty().set(refRecordStatus);
        tblCompanyBalanceByIdcompanyBalanceSenderProperty().set(tblCompanyBalanceByIdcompanyBalanceSender);
        tblCompanyBalanceByIdcompanyBalanceReceivedProperty().set(tblCompanyBalanceByIdcompanyBalanceReceived);
        tblCompanyBalanceBankAccountByIdcbbankAccountSenderProperty().set(tblCompanyBalanceBankAccountByIdcbbankAccountSender);
        tblCompanyBalanceBankAccountByIdcbbankAccountReceivedProperty().set(tblCompanyBalanceBankAccountByIdcbbankAccountReceived);
        tblEmployeeByCreatedByProperty().set(tblEmployeeByCreatedBy);
        tblEmployeeByReceivedByProperty().set(tblEmployeeByReceivedBy);
        tblEmployeeByLastUpdatedByProperty().set(tblEmployeeByLastUpdatedBy);
        tblEmployeeByTransferByProperty().set(tblEmployeeByTransferBy);
        nominalProperty().set(nominal);
        transferDateProperty().set(transferDate);
        receivedDateProperty().set(receivedDate);
        isReceivedProperty().set(isReceived);
        createdDateProperty().set(createdDate);
        lastUpdatedDateProperty().set(lastUpdatedDate);

    }

    public TblCompanyBalanceTransferReceived(TblCompanyBalanceTransferReceived tblCompanyBalanceTransferReceived) {
        this();
        idrelationProperty().set(tblCompanyBalanceTransferReceived.getIdrelation());
        refRecordStatusProperty().set(tblCompanyBalanceTransferReceived.getRefRecordStatus());
        tblCompanyBalanceByIdcompanyBalanceSenderProperty().set(tblCompanyBalanceTransferReceived.getTblCompanyBalanceByIdcompanyBalanceSender());
        tblCompanyBalanceByIdcompanyBalanceReceivedProperty().set(tblCompanyBalanceTransferReceived.getTblCompanyBalanceByIdcompanyBalanceReceived());
        tblCompanyBalanceBankAccountByIdcbbankAccountSenderProperty().set(tblCompanyBalanceTransferReceived.getTblCompanyBalanceBankAccountByIdcbbankAccountSender());
        tblCompanyBalanceBankAccountByIdcbbankAccountReceivedProperty().set(tblCompanyBalanceTransferReceived.getTblCompanyBalanceBankAccountByIdcbbankAccountReceived());
        tblEmployeeByCreatedByProperty().set(tblCompanyBalanceTransferReceived.getTblEmployeeByCreatedBy());
        tblEmployeeByReceivedByProperty().set(tblCompanyBalanceTransferReceived.getTblEmployeeByReceivedBy());
        tblEmployeeByLastUpdatedByProperty().set(tblCompanyBalanceTransferReceived.getTblEmployeeByLastUpdatedBy());
        tblEmployeeByTransferByProperty().set(tblCompanyBalanceTransferReceived.getTblEmployeeByTransferBy());
        nominalProperty().set(tblCompanyBalanceTransferReceived.getNominal());
        transferDateProperty().set(tblCompanyBalanceTransferReceived.getTransferDate());
        receivedDateProperty().set(tblCompanyBalanceTransferReceived.getReceivedDate());
        isReceivedProperty().set(tblCompanyBalanceTransferReceived.getIsReceived());
        createdDateProperty().set(tblCompanyBalanceTransferReceived.getCreatedDate());
        lastUpdatedDateProperty().set(tblCompanyBalanceTransferReceived.getLastUpdatedDate());

    }

    public final LongProperty idrelationProperty() {
        return this.idrelation;
    }

    public long getIdrelation() {
        return idrelationProperty().get();
    }

    public void setIdrelation(long idrelation) {
        idrelationProperty().set(idrelation);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblCompanyBalance> tblCompanyBalanceByIdcompanyBalanceSenderProperty() {
        return this.tblCompanyBalanceByIdcompanyBalanceSender;
    }

    public TblCompanyBalance getTblCompanyBalanceByIdcompanyBalanceSender() {
        return tblCompanyBalanceByIdcompanyBalanceSenderProperty().get();
    }

    public void setTblCompanyBalanceByIdcompanyBalanceSender(TblCompanyBalance tblCompanyBalanceByIdcompanyBalanceSender) {
        tblCompanyBalanceByIdcompanyBalanceSenderProperty().set(tblCompanyBalanceByIdcompanyBalanceSender);
    }

    public final ObjectProperty<TblCompanyBalance> tblCompanyBalanceByIdcompanyBalanceReceivedProperty() {
        return this.tblCompanyBalanceByIdcompanyBalanceReceived;
    }

    public TblCompanyBalance getTblCompanyBalanceByIdcompanyBalanceReceived() {
        return tblCompanyBalanceByIdcompanyBalanceReceivedProperty().get();
    }

    public void setTblCompanyBalanceByIdcompanyBalanceReceived(TblCompanyBalance tblCompanyBalanceByIdcompanyBalanceReceived) {
        tblCompanyBalanceByIdcompanyBalanceReceivedProperty().set(tblCompanyBalanceByIdcompanyBalanceReceived);
    }

    public final ObjectProperty<TblCompanyBalanceBankAccount> tblCompanyBalanceBankAccountByIdcbbankAccountSenderProperty() {
        return this.tblCompanyBalanceBankAccountByIdcbbankAccountSender;
    }

    public TblCompanyBalanceBankAccount getTblCompanyBalanceBankAccountByIdcbbankAccountSender() {
        return tblCompanyBalanceBankAccountByIdcbbankAccountSenderProperty().get();
    }

    public void setTblCompanyBalanceBankAccountByIdcbbankAccountSender(TblCompanyBalanceBankAccount tblCompanyBalanceBankAccountByIdcbbankAccountSender) {
        tblCompanyBalanceBankAccountByIdcbbankAccountSenderProperty().set(tblCompanyBalanceBankAccountByIdcbbankAccountSender);
    }

    public final ObjectProperty<TblCompanyBalanceBankAccount> tblCompanyBalanceBankAccountByIdcbbankAccountReceivedProperty() {
        return this.tblCompanyBalanceBankAccountByIdcbbankAccountReceived;
    }

    public TblCompanyBalanceBankAccount getTblCompanyBalanceBankAccountByIdcbbankAccountReceived() {
        return tblCompanyBalanceBankAccountByIdcbbankAccountReceivedProperty().get();
    }

    public void setTblCompanyBalanceBankAccountByIdcbbankAccountReceived(TblCompanyBalanceBankAccount tblCompanyBalanceBankAccountByIdcbbankAccountReceived) {
        tblCompanyBalanceBankAccountByIdcbbankAccountReceivedProperty().set(tblCompanyBalanceBankAccountByIdcbbankAccountReceived);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreatedByProperty() {
        return this.tblEmployeeByCreatedBy;
    }

    public TblEmployee getTblEmployeeByCreatedBy() {
        return tblEmployeeByCreatedByProperty().get();
    }

    public void setTblEmployeeByCreatedBy(TblEmployee tblEmployeeByCreatedBy) {
        tblEmployeeByCreatedByProperty().set(tblEmployeeByCreatedBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByReceivedByProperty() {
        return this.tblEmployeeByReceivedBy;
    }

    public TblEmployee getTblEmployeeByReceivedBy() {
        return tblEmployeeByReceivedByProperty().get();
    }

    public void setTblEmployeeByReceivedBy(TblEmployee tblEmployeeByReceivedBy) {
        tblEmployeeByReceivedByProperty().set(tblEmployeeByReceivedBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdatedByProperty() {
        return this.tblEmployeeByLastUpdatedBy;
    }

    public TblEmployee getTblEmployeeByLastUpdatedBy() {
        return tblEmployeeByLastUpdatedByProperty().get();
    }

    public void setTblEmployeeByLastUpdatedBy(TblEmployee tblEmployeeByLastUpdatedBy) {
        tblEmployeeByLastUpdatedByProperty().set(tblEmployeeByLastUpdatedBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByTransferByProperty() {
        return this.tblEmployeeByTransferBy;
    }

    public TblEmployee getTblEmployeeByTransferBy() {
        return tblEmployeeByTransferByProperty().get();
    }

    public void setTblEmployeeByTransferBy(TblEmployee tblEmployeeByTransferBy) {
        tblEmployeeByTransferByProperty().set(tblEmployeeByTransferBy);
    }

    public final ObjectProperty<BigDecimal> nominalProperty() {
        return this.nominal;
    }

    public BigDecimal getNominal() {
        return nominalProperty().get();
    }

    public void setNominal(BigDecimal nominal) {
        nominalProperty().set(nominal);
    }

    public final ObjectProperty<Date> transferDateProperty() {
        return this.transferDate;
    }

    public Date getTransferDate() {
        return transferDateProperty().get();
    }

    public void setTransferDate(Date transferDate) {
        transferDateProperty().set(transferDate);
    }

    public final ObjectProperty<Date> receivedDateProperty() {
        return this.receivedDate;
    }

    public Date getReceivedDate() {
        return receivedDateProperty().get();
    }

    public void setReceivedDate(Date receivedDate) {
        receivedDateProperty().set(receivedDate);
    }

    public final BooleanProperty isReceivedProperty() {
        return this.isReceived;
    }

    public Boolean getIsReceived() {
        return isReceivedProperty().get();
    }

    public void setIsReceived(Boolean isReceived) {
        isReceivedProperty().set(isReceived);
    }

    public final ObjectProperty<Date> createdDateProperty() {
        return this.createdDate;
    }

    public Date getCreatedDate() {
        return createdDateProperty().get();
    }

    public void setCreatedDate(Date createdDate) {
        createdDateProperty().set(createdDate);
    }

    public final ObjectProperty<Date> lastUpdatedDateProperty() {
        return this.lastUpdatedDate;
    }

    public Date getLastUpdatedDate() {
        return lastUpdatedDateProperty().get();
    }

    public void setLastUpdatedDate(Date lastUpdatedDate) {
        lastUpdatedDateProperty().set(lastUpdatedDate);
    }

}
