package hotelfx.persistence.model;
// Generated Sep 25, 2018 4:01:53 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblCompanyBalance generated by hbm2java
 */
public class TblCompanyBalance implements java.io.Serializable {

    private final LongProperty idbalance;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final StringProperty codeBalance;
    private final StringProperty balanceName;
    private final ObjectProperty<BigDecimal> balanceNominal;
    private final ObjectProperty<BigDecimal> minimalBalanceNominal;
    private final StringProperty balanceNote;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    private Set tblCompanyBalanceTransferReceivedsForIdcompanyBalanceSender;
    private Set tblHotelExpenseTransactions;
    private Set logCompanyBalanceCashFlowsForIdsenderCompanyBalance;
    private Set tblCalendarEmployeePaymentHistories;
    private Set tblCompanyBalanceBankAccounts;
    private Set tblCalendarEmployeePaymentDebtHistories;
    private Set tblHotelFinanceTransactionWithCashes;
    private Set tblCalendarEmployeeDebts;
    private Set logCompanyBalanceCashFlowsForIdreceiverCompanyBalance;
    private Set tblCompanyBalanceTransferReceivedsForIdcompanyBalanceReceived;

    public TblCompanyBalance() {
        this.idbalance = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.codeBalance = new SimpleStringProperty();
        this.balanceName = new SimpleStringProperty();
        this.balanceNominal = new SimpleObjectProperty<>();
        this.minimalBalanceNominal = new SimpleObjectProperty<>();
        this.balanceNote = new SimpleStringProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

        this.tblCompanyBalanceTransferReceivedsForIdcompanyBalanceSender = new HashSet(0);
        this.tblHotelExpenseTransactions = new HashSet(0);
        this.logCompanyBalanceCashFlowsForIdsenderCompanyBalance = new HashSet(0);
        this.tblCalendarEmployeePaymentHistories = new HashSet(0);
        this.tblCompanyBalanceBankAccounts = new HashSet(0);
        this.tblCalendarEmployeePaymentDebtHistories = new HashSet(0);
        this.tblHotelFinanceTransactionWithCashes = new HashSet(0);
        this.tblCalendarEmployeeDebts = new HashSet(0);
        this.logCompanyBalanceCashFlowsForIdreceiverCompanyBalance = new HashSet(0);
        this.tblCompanyBalanceTransferReceivedsForIdcompanyBalanceReceived = new HashSet(0);
    }

    public TblCompanyBalance(long idbalance) {
        this();
        idbalanceProperty().set(idbalance);
    }

    public TblCompanyBalance(long idbalance, RefRecordStatus refRecordStatus, TblEmployee tblEmployeeByLastUpdateBy, TblEmployee tblEmployeeByCreateBy, String codeBalance, String balanceName, BigDecimal balanceNominal, BigDecimal minimalBalanceNominal, String balanceNote, Date createDate, Date lastUpdateDate, Set tblCompanyBalanceTransferReceivedsForIdcompanyBalanceSender, Set tblHotelExpenseTransactions, Set logCompanyBalanceCashFlowsForIdsenderCompanyBalance, Set tblCalendarEmployeePaymentHistories, Set tblCompanyBalanceBankAccounts, Set tblCalendarEmployeePaymentDebtHistories, Set tblHotelFinanceTransactionWithCashes, Set tblCalendarEmployeeDebts, Set logCompanyBalanceCashFlowsForIdreceiverCompanyBalance, Set tblCompanyBalanceTransferReceivedsForIdcompanyBalanceReceived) {
        this();
        idbalanceProperty().set(idbalance);
        refRecordStatusProperty().set(refRecordStatus);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        codeBalanceProperty().set(codeBalance);
        balanceNameProperty().set(balanceName);
        balanceNominalProperty().set(balanceNominal);
        minimalBalanceNominalProperty().set(minimalBalanceNominal);
        balanceNoteProperty().set(balanceNote);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

        this.tblCompanyBalanceTransferReceivedsForIdcompanyBalanceSender = tblCompanyBalanceTransferReceivedsForIdcompanyBalanceSender;
        this.tblHotelExpenseTransactions = tblHotelExpenseTransactions;
        this.logCompanyBalanceCashFlowsForIdsenderCompanyBalance = logCompanyBalanceCashFlowsForIdsenderCompanyBalance;
        this.tblCalendarEmployeePaymentHistories = tblCalendarEmployeePaymentHistories;
        this.tblCompanyBalanceBankAccounts = tblCompanyBalanceBankAccounts;
        this.tblCalendarEmployeePaymentDebtHistories = tblCalendarEmployeePaymentDebtHistories;
        this.tblHotelFinanceTransactionWithCashes = tblHotelFinanceTransactionWithCashes;
        this.tblCalendarEmployeeDebts = tblCalendarEmployeeDebts;
        this.logCompanyBalanceCashFlowsForIdreceiverCompanyBalance = logCompanyBalanceCashFlowsForIdreceiverCompanyBalance;
        this.tblCompanyBalanceTransferReceivedsForIdcompanyBalanceReceived = tblCompanyBalanceTransferReceivedsForIdcompanyBalanceReceived;
    }

    public TblCompanyBalance(TblCompanyBalance tblCompanyBalance) {
        this();
        idbalanceProperty().set(tblCompanyBalance.getIdbalance());
        refRecordStatusProperty().set(tblCompanyBalance.getRefRecordStatus());
        tblEmployeeByLastUpdateByProperty().set(tblCompanyBalance.getTblEmployeeByLastUpdateBy());
        tblEmployeeByCreateByProperty().set(tblCompanyBalance.getTblEmployeeByCreateBy());
        codeBalanceProperty().set(tblCompanyBalance.getCodeBalance());
        balanceNameProperty().set(tblCompanyBalance.getBalanceName());
        balanceNominalProperty().set(tblCompanyBalance.getBalanceNominal());
        minimalBalanceNominalProperty().set(tblCompanyBalance.getMinimalBalanceNominal());
        balanceNoteProperty().set(tblCompanyBalance.getBalanceNote());
        createDateProperty().set(tblCompanyBalance.getCreateDate());
        lastUpdateDateProperty().set(tblCompanyBalance.getLastUpdateDate());

        this.tblCompanyBalanceTransferReceivedsForIdcompanyBalanceSender = tblCompanyBalance.getTblCompanyBalanceTransferReceivedsForIdcompanyBalanceSender();
        this.tblHotelExpenseTransactions = tblCompanyBalance.getTblHotelExpenseTransactions();
        this.logCompanyBalanceCashFlowsForIdsenderCompanyBalance = tblCompanyBalance.getLogCompanyBalanceCashFlowsForIdsenderCompanyBalance();
        this.tblCalendarEmployeePaymentHistories = tblCompanyBalance.getTblCalendarEmployeePaymentHistories();
        this.tblCompanyBalanceBankAccounts = tblCompanyBalance.getTblCompanyBalanceBankAccounts();
        this.tblCalendarEmployeePaymentDebtHistories = tblCompanyBalance.getTblCalendarEmployeePaymentDebtHistories();
        this.tblHotelFinanceTransactionWithCashes = tblCompanyBalance.getTblHotelFinanceTransactionWithCashes();
        this.tblCalendarEmployeeDebts = tblCompanyBalance.getTblCalendarEmployeeDebts();
        this.logCompanyBalanceCashFlowsForIdreceiverCompanyBalance = tblCompanyBalance.getLogCompanyBalanceCashFlowsForIdreceiverCompanyBalance();
        this.tblCompanyBalanceTransferReceivedsForIdcompanyBalanceReceived = tblCompanyBalance.getTblCompanyBalanceTransferReceivedsForIdcompanyBalanceReceived();
    }

    public final LongProperty idbalanceProperty() {
        return this.idbalance;
    }

    public long getIdbalance() {
        return idbalanceProperty().get();
    }

    public void setIdbalance(long idbalance) {
        idbalanceProperty().set(idbalance);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final StringProperty codeBalanceProperty() {
        return this.codeBalance;
    }

    public String getCodeBalance() {
        return codeBalanceProperty().get();
    }

    public void setCodeBalance(String codeBalance) {
        codeBalanceProperty().set(codeBalance);
    }

    public final StringProperty balanceNameProperty() {
        return this.balanceName;
    }

    public String getBalanceName() {
        return balanceNameProperty().get();
    }

    public void setBalanceName(String balanceName) {
        balanceNameProperty().set(balanceName);
    }

    public final ObjectProperty<BigDecimal> balanceNominalProperty() {
        return this.balanceNominal;
    }

    public BigDecimal getBalanceNominal() {
        return balanceNominalProperty().get();
    }

    public void setBalanceNominal(BigDecimal balanceNominal) {
        balanceNominalProperty().set(balanceNominal);
    }

    public final ObjectProperty<BigDecimal> minimalBalanceNominalProperty() {
        return this.minimalBalanceNominal;
    }

    public BigDecimal getMinimalBalanceNominal() {
        return minimalBalanceNominalProperty().get();
    }

    public void setMinimalBalanceNominal(BigDecimal minimalBalanceNominal) {
        minimalBalanceNominalProperty().set(minimalBalanceNominal);
    }

    public final StringProperty balanceNoteProperty() {
        return this.balanceNote;
    }

    public String getBalanceNote() {
        return balanceNoteProperty().get();
    }

    public void setBalanceNote(String balanceNote) {
        balanceNoteProperty().set(balanceNote);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

    public Set getTblCompanyBalanceTransferReceivedsForIdcompanyBalanceSender() {
        return this.tblCompanyBalanceTransferReceivedsForIdcompanyBalanceSender;
    }

    public void setTblCompanyBalanceTransferReceivedsForIdcompanyBalanceSender(Set tblCompanyBalanceTransferReceivedsForIdcompanyBalanceSender) {
        this.tblCompanyBalanceTransferReceivedsForIdcompanyBalanceSender = tblCompanyBalanceTransferReceivedsForIdcompanyBalanceSender;
    }

    public Set getTblHotelExpenseTransactions() {
        return this.tblHotelExpenseTransactions;
    }

    public void setTblHotelExpenseTransactions(Set tblHotelExpenseTransactions) {
        this.tblHotelExpenseTransactions = tblHotelExpenseTransactions;
    }

    public Set getLogCompanyBalanceCashFlowsForIdsenderCompanyBalance() {
        return this.logCompanyBalanceCashFlowsForIdsenderCompanyBalance;
    }

    public void setLogCompanyBalanceCashFlowsForIdsenderCompanyBalance(Set logCompanyBalanceCashFlowsForIdsenderCompanyBalance) {
        this.logCompanyBalanceCashFlowsForIdsenderCompanyBalance = logCompanyBalanceCashFlowsForIdsenderCompanyBalance;
    }

    public Set getTblCalendarEmployeePaymentHistories() {
        return this.tblCalendarEmployeePaymentHistories;
    }

    public void setTblCalendarEmployeePaymentHistories(Set tblCalendarEmployeePaymentHistories) {
        this.tblCalendarEmployeePaymentHistories = tblCalendarEmployeePaymentHistories;
    }

    public Set getTblCompanyBalanceBankAccounts() {
        return this.tblCompanyBalanceBankAccounts;
    }

    public void setTblCompanyBalanceBankAccounts(Set tblCompanyBalanceBankAccounts) {
        this.tblCompanyBalanceBankAccounts = tblCompanyBalanceBankAccounts;
    }

    public Set getTblCalendarEmployeePaymentDebtHistories() {
        return this.tblCalendarEmployeePaymentDebtHistories;
    }

    public void setTblCalendarEmployeePaymentDebtHistories(Set tblCalendarEmployeePaymentDebtHistories) {
        this.tblCalendarEmployeePaymentDebtHistories = tblCalendarEmployeePaymentDebtHistories;
    }

    public Set getTblHotelFinanceTransactionWithCashes() {
        return this.tblHotelFinanceTransactionWithCashes;
    }

    public void setTblHotelFinanceTransactionWithCashes(Set tblHotelFinanceTransactionWithCashes) {
        this.tblHotelFinanceTransactionWithCashes = tblHotelFinanceTransactionWithCashes;
    }

    public Set getTblCalendarEmployeeDebts() {
        return this.tblCalendarEmployeeDebts;
    }

    public void setTblCalendarEmployeeDebts(Set tblCalendarEmployeeDebts) {
        this.tblCalendarEmployeeDebts = tblCalendarEmployeeDebts;
    }

    public Set getLogCompanyBalanceCashFlowsForIdreceiverCompanyBalance() {
        return this.logCompanyBalanceCashFlowsForIdreceiverCompanyBalance;
    }

    public void setLogCompanyBalanceCashFlowsForIdreceiverCompanyBalance(Set logCompanyBalanceCashFlowsForIdreceiverCompanyBalance) {
        this.logCompanyBalanceCashFlowsForIdreceiverCompanyBalance = logCompanyBalanceCashFlowsForIdreceiverCompanyBalance;
    }

    public Set getTblCompanyBalanceTransferReceivedsForIdcompanyBalanceReceived() {
        return this.tblCompanyBalanceTransferReceivedsForIdcompanyBalanceReceived;
    }

    public void setTblCompanyBalanceTransferReceivedsForIdcompanyBalanceReceived(Set tblCompanyBalanceTransferReceivedsForIdcompanyBalanceReceived) {
        this.tblCompanyBalanceTransferReceivedsForIdcompanyBalanceReceived = tblCompanyBalanceTransferReceivedsForIdcompanyBalanceReceived;
    }
    
    @Override
    public String toString() {
        return getBalanceName();
    }

}
