package hotelfx.persistence.model;
// Generated Jun 29, 2018 9:21:45 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblEmployeeWarningLetterType generated by hbm2java
 */
public class TblEmployeeWarningLetterType implements java.io.Serializable {

    private final LongProperty idwarningLetter;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreatedBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdatedBy;
    private final StringProperty nameWarningLetter;
    private final StringProperty noteWarningLetter;
    private final ObjectProperty<Date> createdDate;
    private final ObjectProperty<Date> lastUpdatedDate;

    private Set tblCalendarEmployeeWarningLetters;

    public TblEmployeeWarningLetterType() {
        this.idwarningLetter = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByCreatedBy = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdatedBy = new SimpleObjectProperty<>();
        this.nameWarningLetter = new SimpleStringProperty();
        this.noteWarningLetter = new SimpleStringProperty();
        this.createdDate = new SimpleObjectProperty<>();
        this.lastUpdatedDate = new SimpleObjectProperty<>();

        this.tblCalendarEmployeeWarningLetters = new HashSet(0);
    }

    public TblEmployeeWarningLetterType(long idwarningLetter) {
        this();
        idwarningLetterProperty().set(idwarningLetter);
    }

    public TblEmployeeWarningLetterType(long idwarningLetter, RefRecordStatus refRecordStatus, TblEmployee tblEmployeeByCreatedBy, TblEmployee tblEmployeeByLastUpdatedBy, String nameWarningLetter, String noteWarningLetter, Date createdDate, Date lastUpdatedDate, Set tblCalendarEmployeeWarningLetters) {
        this();
        idwarningLetterProperty().set(idwarningLetter);
        refRecordStatusProperty().set(refRecordStatus);
        tblEmployeeByCreatedByProperty().set(tblEmployeeByCreatedBy);
        tblEmployeeByLastUpdatedByProperty().set(tblEmployeeByLastUpdatedBy);
        nameWarningLetterProperty().set(nameWarningLetter);
        noteWarningLetterProperty().set(noteWarningLetter);
        createdDateProperty().set(createdDate);
        lastUpdatedDateProperty().set(lastUpdatedDate);

        this.tblCalendarEmployeeWarningLetters = tblCalendarEmployeeWarningLetters;
    }

    public TblEmployeeWarningLetterType(TblEmployeeWarningLetterType tblEmployeeWarningLetterType) {
        this();
        idwarningLetterProperty().set(tblEmployeeWarningLetterType.getIdwarningLetter());
        refRecordStatusProperty().set(tblEmployeeWarningLetterType.getRefRecordStatus());
        tblEmployeeByCreatedByProperty().set(tblEmployeeWarningLetterType.getTblEmployeeByCreatedBy());
        tblEmployeeByLastUpdatedByProperty().set(tblEmployeeWarningLetterType.getTblEmployeeByLastUpdatedBy());
        nameWarningLetterProperty().set(tblEmployeeWarningLetterType.getNameWarningLetter());
        noteWarningLetterProperty().set(tblEmployeeWarningLetterType.getNoteWarningLetter());
        createdDateProperty().set(tblEmployeeWarningLetterType.getCreatedDate());
        lastUpdatedDateProperty().set(tblEmployeeWarningLetterType.getLastUpdatedDate());

        this.tblCalendarEmployeeWarningLetters = tblEmployeeWarningLetterType.getTblCalendarEmployeeWarningLetters();
    }

    public final LongProperty idwarningLetterProperty() {
        return this.idwarningLetter;
    }

    public long getIdwarningLetter() {
        return idwarningLetterProperty().get();
    }

    public void setIdwarningLetter(long idwarningLetter) {
        idwarningLetterProperty().set(idwarningLetter);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreatedByProperty() {
        return this.tblEmployeeByCreatedBy;
    }

    public TblEmployee getTblEmployeeByCreatedBy() {
        return tblEmployeeByCreatedByProperty().get();
    }

    public void setTblEmployeeByCreatedBy(TblEmployee tblEmployeeByCreatedBy) {
        tblEmployeeByCreatedByProperty().set(tblEmployeeByCreatedBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdatedByProperty() {
        return this.tblEmployeeByLastUpdatedBy;
    }

    public TblEmployee getTblEmployeeByLastUpdatedBy() {
        return tblEmployeeByLastUpdatedByProperty().get();
    }

    public void setTblEmployeeByLastUpdatedBy(TblEmployee tblEmployeeByLastUpdatedBy) {
        tblEmployeeByLastUpdatedByProperty().set(tblEmployeeByLastUpdatedBy);
    }

    public final StringProperty nameWarningLetterProperty() {
        return this.nameWarningLetter;
    }

    public String getNameWarningLetter() {
        return nameWarningLetterProperty().get();
    }

    public void setNameWarningLetter(String nameWarningLetter) {
        nameWarningLetterProperty().set(nameWarningLetter);
    }

    public final StringProperty noteWarningLetterProperty() {
        return this.noteWarningLetter;
    }

    public String getNoteWarningLetter() {
        return noteWarningLetterProperty().get();
    }

    public void setNoteWarningLetter(String noteWarningLetter) {
        noteWarningLetterProperty().set(noteWarningLetter);
    }

    public final ObjectProperty<Date> createdDateProperty() {
        return this.createdDate;
    }

    public Date getCreatedDate() {
        return createdDateProperty().get();
    }

    public void setCreatedDate(Date createdDate) {
        createdDateProperty().set(createdDate);
    }

    public final ObjectProperty<Date> lastUpdatedDateProperty() {
        return this.lastUpdatedDate;
    }

    public Date getLastUpdatedDate() {
        return lastUpdatedDateProperty().get();
    }

    public void setLastUpdatedDate(Date lastUpdatedDate) {
        lastUpdatedDateProperty().set(lastUpdatedDate);
    }

    public Set getTblCalendarEmployeeWarningLetters() {
        return this.tblCalendarEmployeeWarningLetters;
    }

    public void setTblCalendarEmployeeWarningLetters(Set tblCalendarEmployeeWarningLetters) {
        this.tblCalendarEmployeeWarningLetters = tblCalendarEmployeeWarningLetters;
    }

}
