package hotelfx.persistence.model;
// Generated Aug 21, 2017 1:49:32 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;

/**
 * TblEmployeeOvertimeDetail generated by hbm2java
 */
public class TblEmployeeOvertimeDetail implements java.io.Serializable {

    private final LongProperty iddetail;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblEmployeeOvertime> tblEmployeeOvertime;
    private final ObjectProperty<Date> beginDateTime;
    private final ObjectProperty<Date> endDateTime;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUdpateDate;

    private Set tblEmployeeEmployeeOvertimeDetails;

    public TblEmployeeOvertimeDetail() {
        this.iddetail = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblEmployeeOvertime = new SimpleObjectProperty<>();
        this.beginDateTime = new SimpleObjectProperty<>();
        this.endDateTime = new SimpleObjectProperty<>();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUdpateDate = new SimpleObjectProperty<>();

        this.tblEmployeeEmployeeOvertimeDetails = new HashSet(0);
    }

    public TblEmployeeOvertimeDetail(long iddetail) {
        this();
        iddetailProperty().set(iddetail);
    }

    public TblEmployeeOvertimeDetail(long iddetail, RefRecordStatus refRecordStatus, TblEmployee tblEmployeeByCreateBy, TblEmployee tblEmployeeByLastUpdateBy, TblEmployeeOvertime tblEmployeeOvertime, Date beginDateTime, Date endDateTime, Date createDate, Date lastUdpateDate, Set tblEmployeeEmployeeOvertimeDetails) {
        this();
        iddetailProperty().set(iddetail);
        refRecordStatusProperty().set(refRecordStatus);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblEmployeeOvertimeProperty().set(tblEmployeeOvertime);
        beginDateTimeProperty().set(beginDateTime);
        endDateTimeProperty().set(endDateTime);
        createDateProperty().set(createDate);
        lastUdpateDateProperty().set(lastUdpateDate);

        this.tblEmployeeEmployeeOvertimeDetails = tblEmployeeEmployeeOvertimeDetails;
    }

    public TblEmployeeOvertimeDetail(TblEmployeeOvertimeDetail tblEmployeeOvertimeDetail) {
        this();
        iddetailProperty().set(tblEmployeeOvertimeDetail.getIddetail());
        refRecordStatusProperty().set(tblEmployeeOvertimeDetail.getRefRecordStatus());
        tblEmployeeByCreateByProperty().set(tblEmployeeOvertimeDetail.getTblEmployeeByCreateBy());
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeOvertimeDetail.getTblEmployeeByLastUpdateBy());
        tblEmployeeOvertimeProperty().set(tblEmployeeOvertimeDetail.getTblEmployeeOvertime());
        beginDateTimeProperty().set(tblEmployeeOvertimeDetail.getBeginDateTime());
        endDateTimeProperty().set(tblEmployeeOvertimeDetail.getEndDateTime());
        createDateProperty().set(tblEmployeeOvertimeDetail.getCreateDate());
        lastUdpateDateProperty().set(tblEmployeeOvertimeDetail.getLastUdpateDate());

        this.tblEmployeeEmployeeOvertimeDetails = tblEmployeeOvertimeDetail.getTblEmployeeEmployeeOvertimeDetails();
    }

    public final LongProperty iddetailProperty() {
        return this.iddetail;
    }

    public long getIddetail() {
        return iddetailProperty().get();
    }

    public void setIddetail(long iddetail) {
        iddetailProperty().set(iddetail);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblEmployeeOvertime> tblEmployeeOvertimeProperty() {
        return this.tblEmployeeOvertime;
    }

    public TblEmployeeOvertime getTblEmployeeOvertime() {
        return tblEmployeeOvertimeProperty().get();
    }

    public void setTblEmployeeOvertime(TblEmployeeOvertime tblEmployeeOvertime) {
        tblEmployeeOvertimeProperty().set(tblEmployeeOvertime);
    }

    public final ObjectProperty<Date> beginDateTimeProperty() {
        return this.beginDateTime;
    }

    public Date getBeginDateTime() {
        return beginDateTimeProperty().get();
    }

    public void setBeginDateTime(Date beginDateTime) {
        beginDateTimeProperty().set(beginDateTime);
    }

    public final ObjectProperty<Date> endDateTimeProperty() {
        return this.endDateTime;
    }

    public Date getEndDateTime() {
        return endDateTimeProperty().get();
    }

    public void setEndDateTime(Date endDateTime) {
        endDateTimeProperty().set(endDateTime);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUdpateDateProperty() {
        return this.lastUdpateDate;
    }

    public Date getLastUdpateDate() {
        return lastUdpateDateProperty().get();
    }

    public void setLastUdpateDate(Date lastUdpateDate) {
        lastUdpateDateProperty().set(lastUdpateDate);
    }

    public Set getTblEmployeeEmployeeOvertimeDetails() {
        return this.tblEmployeeEmployeeOvertimeDetails;
    }

    public void setTblEmployeeEmployeeOvertimeDetails(Set tblEmployeeEmployeeOvertimeDetails) {
        this.tblEmployeeEmployeeOvertimeDetails = tblEmployeeEmployeeOvertimeDetails;
    }

}
