package hotelfx.persistence.model;
// Generated Aug 21, 2017 1:49:32 PM by Hibernate Tools 4.3.1

import java.util.Date;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblEmployeeWarningLetter generated by hbm2java
 */
public class TblEmployeeWarningLetter implements java.io.Serializable {

    private final LongProperty idwarningLetter;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByIdemployee;
    private final StringProperty codeWarningLetter;
    private final ObjectProperty<Date> dateCreated;
    private final StringProperty warningLetter;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    public TblEmployeeWarningLetter() {
        this.idwarningLetter = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByIdemployee = new SimpleObjectProperty<>();
        this.codeWarningLetter = new SimpleStringProperty();
        this.dateCreated = new SimpleObjectProperty<>();
        this.warningLetter = new SimpleStringProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

    }

    public TblEmployeeWarningLetter(long idwarningLetter) {
        this();
        idwarningLetterProperty().set(idwarningLetter);
    }

    public TblEmployeeWarningLetter(long idwarningLetter, RefRecordStatus refRecordStatus, TblEmployee tblEmployeeByCreateBy, TblEmployee tblEmployeeByLastUpdateBy, TblEmployee tblEmployeeByIdemployee, String codeWarningLetter, Date dateCreated, String warningLetter, Date createDate, Date lastUpdateDate) {
        this();
        idwarningLetterProperty().set(idwarningLetter);
        refRecordStatusProperty().set(refRecordStatus);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblEmployeeByIdemployeeProperty().set(tblEmployeeByIdemployee);
        codeWarningLetterProperty().set(codeWarningLetter);
        dateCreatedProperty().set(dateCreated);
        warningLetterProperty().set(warningLetter);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

    }

    public TblEmployeeWarningLetter(TblEmployeeWarningLetter tblEmployeeWarningLetter) {
        this();
        idwarningLetterProperty().set(tblEmployeeWarningLetter.getIdwarningLetter());
        refRecordStatusProperty().set(tblEmployeeWarningLetter.getRefRecordStatus());
        tblEmployeeByCreateByProperty().set(tblEmployeeWarningLetter.getTblEmployeeByCreateBy());
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeWarningLetter.getTblEmployeeByLastUpdateBy());
        tblEmployeeByIdemployeeProperty().set(tblEmployeeWarningLetter.getTblEmployeeByIdemployee());
        codeWarningLetterProperty().set(tblEmployeeWarningLetter.getCodeWarningLetter());
        dateCreatedProperty().set(tblEmployeeWarningLetter.getDateCreated());
        warningLetterProperty().set(tblEmployeeWarningLetter.getWarningLetter());
        createDateProperty().set(tblEmployeeWarningLetter.getCreateDate());
        lastUpdateDateProperty().set(tblEmployeeWarningLetter.getLastUpdateDate());

    }

    public final LongProperty idwarningLetterProperty() {
        return this.idwarningLetter;
    }

    public long getIdwarningLetter() {
        return idwarningLetterProperty().get();
    }

    public void setIdwarningLetter(long idwarningLetter) {
        idwarningLetterProperty().set(idwarningLetter);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByIdemployeeProperty() {
        return this.tblEmployeeByIdemployee;
    }

    public TblEmployee getTblEmployeeByIdemployee() {
        return tblEmployeeByIdemployeeProperty().get();
    }

    public void setTblEmployeeByIdemployee(TblEmployee tblEmployeeByIdemployee) {
        tblEmployeeByIdemployeeProperty().set(tblEmployeeByIdemployee);
    }

    public final StringProperty codeWarningLetterProperty() {
        return this.codeWarningLetter;
    }

    public String getCodeWarningLetter() {
        return codeWarningLetterProperty().get();
    }

    public void setCodeWarningLetter(String codeWarningLetter) {
        codeWarningLetterProperty().set(codeWarningLetter);
    }

    public final ObjectProperty<Date> dateCreatedProperty() {
        return this.dateCreated;
    }

    public Date getDateCreated() {
        return dateCreatedProperty().get();
    }

    public void setDateCreated(Date dateCreated) {
        dateCreatedProperty().set(dateCreated);
    }

    public final StringProperty warningLetterProperty() {
        return this.warningLetter;
    }

    public String getWarningLetter() {
        return warningLetterProperty().get();
    }

    public void setWarningLetter(String warningLetter) {
        warningLetterProperty().set(warningLetter);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

}
