package hotelfx.persistence.model;
// Generated Aug 21, 2017 1:49:32 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblEmployeeCutOffLeave generated by hbm2java
 */
public class TblEmployeeCutOffLeave implements java.io.Serializable {

    private final LongProperty idcutOff;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblFinanceData> tblFinanceData;
    private final StringProperty codeCutOff;
    private final ObjectProperty<Date> cutOffDate;
    private final ObjectProperty<BigDecimal> refundPercentage;
    private final LongProperty roundValue;
    private final ObjectProperty<Date> cutOffDateCreated;
    private final StringProperty cutOffNote;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    private Set tblEmployeeEmployeeCutOffLeaves;

    public TblEmployeeCutOffLeave() {
        this.idcutOff = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblFinanceData = new SimpleObjectProperty<>();
        this.codeCutOff = new SimpleStringProperty();
        this.cutOffDate = new SimpleObjectProperty<>();
        this.refundPercentage = new SimpleObjectProperty<>();
        this.roundValue = new SimpleLongProperty();
        this.cutOffDateCreated = new SimpleObjectProperty<>();
        this.cutOffNote = new SimpleStringProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

        this.tblEmployeeEmployeeCutOffLeaves = new HashSet(0);
    }

    public TblEmployeeCutOffLeave(long idcutOff) {
        this();
        idcutOffProperty().set(idcutOff);
    }

    public TblEmployeeCutOffLeave(long idcutOff, RefRecordStatus refRecordStatus, TblEmployee tblEmployeeByLastUpdateBy, TblEmployee tblEmployeeByCreateBy, TblFinanceData tblFinanceData, String codeCutOff, Date cutOffDate, BigDecimal refundPercentage, Long roundValue, Date cutOffDateCreated, String cutOffNote, Date createDate, Date lastUpdateDate, Set tblEmployeeEmployeeCutOffLeaves) {
        this();
        idcutOffProperty().set(idcutOff);
        refRecordStatusProperty().set(refRecordStatus);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblFinanceDataProperty().set(tblFinanceData);
        codeCutOffProperty().set(codeCutOff);
        cutOffDateProperty().set(cutOffDate);
        refundPercentageProperty().set(refundPercentage);
        roundValueProperty().set(roundValue);
        cutOffDateCreatedProperty().set(cutOffDateCreated);
        cutOffNoteProperty().set(cutOffNote);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

        this.tblEmployeeEmployeeCutOffLeaves = tblEmployeeEmployeeCutOffLeaves;
    }

    public TblEmployeeCutOffLeave(TblEmployeeCutOffLeave tblEmployeeCutOffLeave) {
        this();
        idcutOffProperty().set(tblEmployeeCutOffLeave.getIdcutOff());
        refRecordStatusProperty().set(tblEmployeeCutOffLeave.getRefRecordStatus());
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeCutOffLeave.getTblEmployeeByLastUpdateBy());
        tblEmployeeByCreateByProperty().set(tblEmployeeCutOffLeave.getTblEmployeeByCreateBy());
        tblFinanceDataProperty().set(tblEmployeeCutOffLeave.getTblFinanceData());
        codeCutOffProperty().set(tblEmployeeCutOffLeave.getCodeCutOff());
        cutOffDateProperty().set(tblEmployeeCutOffLeave.getCutOffDate());
        refundPercentageProperty().set(tblEmployeeCutOffLeave.getRefundPercentage());
        roundValueProperty().set(tblEmployeeCutOffLeave.getRoundValue());
        cutOffDateCreatedProperty().set(tblEmployeeCutOffLeave.getCutOffDateCreated());
        cutOffNoteProperty().set(tblEmployeeCutOffLeave.getCutOffNote());
        createDateProperty().set(tblEmployeeCutOffLeave.getCreateDate());
        lastUpdateDateProperty().set(tblEmployeeCutOffLeave.getLastUpdateDate());

        this.tblEmployeeEmployeeCutOffLeaves = tblEmployeeCutOffLeave.getTblEmployeeEmployeeCutOffLeaves();
    }

    public final LongProperty idcutOffProperty() {
        return this.idcutOff;
    }

    public long getIdcutOff() {
        return idcutOffProperty().get();
    }

    public void setIdcutOff(long idcutOff) {
        idcutOffProperty().set(idcutOff);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblFinanceData> tblFinanceDataProperty() {
        return this.tblFinanceData;
    }

    public TblFinanceData getTblFinanceData() {
        return tblFinanceDataProperty().get();
    }

    public void setTblFinanceData(TblFinanceData tblFinanceData) {
        tblFinanceDataProperty().set(tblFinanceData);
    }

    public final StringProperty codeCutOffProperty() {
        return this.codeCutOff;
    }

    public String getCodeCutOff() {
        return codeCutOffProperty().get();
    }

    public void setCodeCutOff(String codeCutOff) {
        codeCutOffProperty().set(codeCutOff);
    }

    public final ObjectProperty<Date> cutOffDateProperty() {
        return this.cutOffDate;
    }

    public Date getCutOffDate() {
        return cutOffDateProperty().get();
    }

    public void setCutOffDate(Date cutOffDate) {
        cutOffDateProperty().set(cutOffDate);
    }

    public final ObjectProperty<BigDecimal> refundPercentageProperty() {
        return this.refundPercentage;
    }

    public BigDecimal getRefundPercentage() {
        return refundPercentageProperty().get();
    }

    public void setRefundPercentage(BigDecimal refundPercentage) {
        refundPercentageProperty().set(refundPercentage);
    }

    public final LongProperty roundValueProperty() {
        return this.roundValue;
    }

    public Long getRoundValue() {
        return roundValueProperty().get();
    }

    public void setRoundValue(Long roundValue) {
        roundValueProperty().set(roundValue);
    }

    public final ObjectProperty<Date> cutOffDateCreatedProperty() {
        return this.cutOffDateCreated;
    }

    public Date getCutOffDateCreated() {
        return cutOffDateCreatedProperty().get();
    }

    public void setCutOffDateCreated(Date cutOffDateCreated) {
        cutOffDateCreatedProperty().set(cutOffDateCreated);
    }

    public final StringProperty cutOffNoteProperty() {
        return this.cutOffNote;
    }

    public String getCutOffNote() {
        return cutOffNoteProperty().get();
    }

    public void setCutOffNote(String cutOffNote) {
        cutOffNoteProperty().set(cutOffNote);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

    public Set getTblEmployeeEmployeeCutOffLeaves() {
        return this.tblEmployeeEmployeeCutOffLeaves;
    }

    public void setTblEmployeeEmployeeCutOffLeaves(Set tblEmployeeEmployeeCutOffLeaves) {
        this.tblEmployeeEmployeeCutOffLeaves = tblEmployeeEmployeeCutOffLeaves;
    }

}
