package hotelfx.persistence.model;
// Generated Aug 21, 2017 1:49:32 PM by Hibernate Tools 4.3.1

import java.util.Date;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblEmployeeSwitchSchedule generated by hbm2java
 */
public class TblEmployeeSwitchSchedule implements java.io.Serializable {

    private final LongProperty idswitchSchedule;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByIdemployeeTwo;
    private final ObjectProperty<TblEmployee> tblEmployeeByIdemployeeOne;
    private final StringProperty codeSwitchSchedule;
    private final ObjectProperty<Date> dateCreated;
    private final ObjectProperty<Date> beginTimeOne;
    private final ObjectProperty<Date> endTimeOne;
    private final ObjectProperty<Date> beginTimeTwo;
    private final ObjectProperty<Date> endTimeTwo;
    private final StringProperty switchNote;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    public TblEmployeeSwitchSchedule() {
        this.idswitchSchedule = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByIdemployeeTwo = new SimpleObjectProperty<>();
        this.tblEmployeeByIdemployeeOne = new SimpleObjectProperty<>();
        this.codeSwitchSchedule = new SimpleStringProperty();
        this.dateCreated = new SimpleObjectProperty<>();
        this.beginTimeOne = new SimpleObjectProperty<>();
        this.endTimeOne = new SimpleObjectProperty<>();
        this.beginTimeTwo = new SimpleObjectProperty<>();
        this.endTimeTwo = new SimpleObjectProperty<>();
        this.switchNote = new SimpleStringProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

    }

    public TblEmployeeSwitchSchedule(long idswitchSchedule) {
        this();
        idswitchScheduleProperty().set(idswitchSchedule);
    }

    public TblEmployeeSwitchSchedule(long idswitchSchedule, RefRecordStatus refRecordStatus, TblEmployee tblEmployeeByCreateBy, TblEmployee tblEmployeeByLastUpdateBy, TblEmployee tblEmployeeByIdemployeeTwo, TblEmployee tblEmployeeByIdemployeeOne, String codeSwitchSchedule, Date dateCreated, Date beginTimeOne, Date endTimeOne, Date beginTimeTwo, Date endTimeTwo, String switchNote, Date createDate, Date lastUpdateDate) {
        this();
        idswitchScheduleProperty().set(idswitchSchedule);
        refRecordStatusProperty().set(refRecordStatus);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblEmployeeByIdemployeeTwoProperty().set(tblEmployeeByIdemployeeTwo);
        tblEmployeeByIdemployeeOneProperty().set(tblEmployeeByIdemployeeOne);
        codeSwitchScheduleProperty().set(codeSwitchSchedule);
        dateCreatedProperty().set(dateCreated);
        beginTimeOneProperty().set(beginTimeOne);
        endTimeOneProperty().set(endTimeOne);
        beginTimeTwoProperty().set(beginTimeTwo);
        endTimeTwoProperty().set(endTimeTwo);
        switchNoteProperty().set(switchNote);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

    }

    public TblEmployeeSwitchSchedule(TblEmployeeSwitchSchedule tblEmployeeSwitchSchedule) {
        this();
        idswitchScheduleProperty().set(tblEmployeeSwitchSchedule.getIdswitchSchedule());
        refRecordStatusProperty().set(tblEmployeeSwitchSchedule.getRefRecordStatus());
        tblEmployeeByCreateByProperty().set(tblEmployeeSwitchSchedule.getTblEmployeeByCreateBy());
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeSwitchSchedule.getTblEmployeeByLastUpdateBy());
        tblEmployeeByIdemployeeTwoProperty().set(tblEmployeeSwitchSchedule.getTblEmployeeByIdemployeeTwo());
        tblEmployeeByIdemployeeOneProperty().set(tblEmployeeSwitchSchedule.getTblEmployeeByIdemployeeOne());
        codeSwitchScheduleProperty().set(tblEmployeeSwitchSchedule.getCodeSwitchSchedule());
        dateCreatedProperty().set(tblEmployeeSwitchSchedule.getDateCreated());
        beginTimeOneProperty().set(tblEmployeeSwitchSchedule.getBeginTimeOne());
        endTimeOneProperty().set(tblEmployeeSwitchSchedule.getEndTimeOne());
        beginTimeTwoProperty().set(tblEmployeeSwitchSchedule.getBeginTimeTwo());
        endTimeTwoProperty().set(tblEmployeeSwitchSchedule.getEndTimeTwo());
        switchNoteProperty().set(tblEmployeeSwitchSchedule.getSwitchNote());
        createDateProperty().set(tblEmployeeSwitchSchedule.getCreateDate());
        lastUpdateDateProperty().set(tblEmployeeSwitchSchedule.getLastUpdateDate());

    }

    public final LongProperty idswitchScheduleProperty() {
        return this.idswitchSchedule;
    }

    public long getIdswitchSchedule() {
        return idswitchScheduleProperty().get();
    }

    public void setIdswitchSchedule(long idswitchSchedule) {
        idswitchScheduleProperty().set(idswitchSchedule);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByIdemployeeTwoProperty() {
        return this.tblEmployeeByIdemployeeTwo;
    }

    public TblEmployee getTblEmployeeByIdemployeeTwo() {
        return tblEmployeeByIdemployeeTwoProperty().get();
    }

    public void setTblEmployeeByIdemployeeTwo(TblEmployee tblEmployeeByIdemployeeTwo) {
        tblEmployeeByIdemployeeTwoProperty().set(tblEmployeeByIdemployeeTwo);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByIdemployeeOneProperty() {
        return this.tblEmployeeByIdemployeeOne;
    }

    public TblEmployee getTblEmployeeByIdemployeeOne() {
        return tblEmployeeByIdemployeeOneProperty().get();
    }

    public void setTblEmployeeByIdemployeeOne(TblEmployee tblEmployeeByIdemployeeOne) {
        tblEmployeeByIdemployeeOneProperty().set(tblEmployeeByIdemployeeOne);
    }

    public final StringProperty codeSwitchScheduleProperty() {
        return this.codeSwitchSchedule;
    }

    public String getCodeSwitchSchedule() {
        return codeSwitchScheduleProperty().get();
    }

    public void setCodeSwitchSchedule(String codeSwitchSchedule) {
        codeSwitchScheduleProperty().set(codeSwitchSchedule);
    }

    public final ObjectProperty<Date> dateCreatedProperty() {
        return this.dateCreated;
    }

    public Date getDateCreated() {
        return dateCreatedProperty().get();
    }

    public void setDateCreated(Date dateCreated) {
        dateCreatedProperty().set(dateCreated);
    }

    public final ObjectProperty<Date> beginTimeOneProperty() {
        return this.beginTimeOne;
    }

    public Date getBeginTimeOne() {
        return beginTimeOneProperty().get();
    }

    public void setBeginTimeOne(Date beginTimeOne) {
        beginTimeOneProperty().set(beginTimeOne);
    }

    public final ObjectProperty<Date> endTimeOneProperty() {
        return this.endTimeOne;
    }

    public Date getEndTimeOne() {
        return endTimeOneProperty().get();
    }

    public void setEndTimeOne(Date endTimeOne) {
        endTimeOneProperty().set(endTimeOne);
    }

    public final ObjectProperty<Date> beginTimeTwoProperty() {
        return this.beginTimeTwo;
    }

    public Date getBeginTimeTwo() {
        return beginTimeTwoProperty().get();
    }

    public void setBeginTimeTwo(Date beginTimeTwo) {
        beginTimeTwoProperty().set(beginTimeTwo);
    }

    public final ObjectProperty<Date> endTimeTwoProperty() {
        return this.endTimeTwo;
    }

    public Date getEndTimeTwo() {
        return endTimeTwoProperty().get();
    }

    public void setEndTimeTwo(Date endTimeTwo) {
        endTimeTwoProperty().set(endTimeTwo);
    }

    public final StringProperty switchNoteProperty() {
        return this.switchNote;
    }

    public String getSwitchNote() {
        return switchNoteProperty().get();
    }

    public void setSwitchNote(String switchNote) {
        switchNoteProperty().set(switchNote);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

}
