package hotelfx.persistence.model;
// Generated Apr 27, 2018 3:35:28 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblEmployeeInsurance generated by hbm2java
 */
public class TblEmployeeInsurance implements java.io.Serializable {

    private final LongProperty idinsurance;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final StringProperty codeInsurance;
    private final StringProperty insuranceName;
    private final StringProperty insuranceCompany;
    private final ObjectProperty<BigDecimal> insuranceNominal;
    private final StringProperty insuranceNote;
    private final StringProperty companyNote;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    private Set tblEmployeeEmployeeInsurances;

    public TblEmployeeInsurance() {
        this.idinsurance = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.codeInsurance = new SimpleStringProperty();
        this.insuranceName = new SimpleStringProperty();
        this.insuranceCompany = new SimpleStringProperty();
        this.insuranceNominal = new SimpleObjectProperty<>();
        this.insuranceNote = new SimpleStringProperty();
        this.companyNote = new SimpleStringProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

        this.tblEmployeeEmployeeInsurances = new HashSet(0);
    }

    public TblEmployeeInsurance(long idinsurance) {
        this();
        idinsuranceProperty().set(idinsurance);
    }

    public TblEmployeeInsurance(long idinsurance, RefRecordStatus refRecordStatus, TblEmployee tblEmployeeByLastUpdateBy, TblEmployee tblEmployeeByCreateBy, String codeInsurance, String insuranceName, String insuranceCompany, BigDecimal insuranceNominal, String insuranceNote, String companyNote, Date createDate, Date lastUpdateDate, Set tblEmployeeEmployeeInsurances) {
        this();
        idinsuranceProperty().set(idinsurance);
        refRecordStatusProperty().set(refRecordStatus);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        codeInsuranceProperty().set(codeInsurance);
        insuranceNameProperty().set(insuranceName);
        insuranceCompanyProperty().set(insuranceCompany);
        insuranceNominalProperty().set(insuranceNominal);
        insuranceNoteProperty().set(insuranceNote);
        companyNoteProperty().set(companyNote);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

        this.tblEmployeeEmployeeInsurances = tblEmployeeEmployeeInsurances;
    }

    public TblEmployeeInsurance(TblEmployeeInsurance tblEmployeeInsurance) {
        this();
        idinsuranceProperty().set(tblEmployeeInsurance.getIdinsurance());
        refRecordStatusProperty().set(tblEmployeeInsurance.getRefRecordStatus());
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeInsurance.getTblEmployeeByLastUpdateBy());
        tblEmployeeByCreateByProperty().set(tblEmployeeInsurance.getTblEmployeeByCreateBy());
        codeInsuranceProperty().set(tblEmployeeInsurance.getCodeInsurance());
        insuranceNameProperty().set(tblEmployeeInsurance.getInsuranceName());
        insuranceCompanyProperty().set(tblEmployeeInsurance.getInsuranceCompany());
        insuranceNominalProperty().set(tblEmployeeInsurance.getInsuranceNominal());
        insuranceNoteProperty().set(tblEmployeeInsurance.getInsuranceNote());
        companyNoteProperty().set(tblEmployeeInsurance.getCompanyNote());
        createDateProperty().set(tblEmployeeInsurance.getCreateDate());
        lastUpdateDateProperty().set(tblEmployeeInsurance.getLastUpdateDate());

        this.tblEmployeeEmployeeInsurances = tblEmployeeInsurance.getTblEmployeeEmployeeInsurances();
    }

    public final LongProperty idinsuranceProperty() {
        return this.idinsurance;
    }

    public long getIdinsurance() {
        return idinsuranceProperty().get();
    }

    public void setIdinsurance(long idinsurance) {
        idinsuranceProperty().set(idinsurance);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final StringProperty codeInsuranceProperty() {
        return this.codeInsurance;
    }

    public String getCodeInsurance() {
        return codeInsuranceProperty().get();
    }

    public void setCodeInsurance(String codeInsurance) {
        codeInsuranceProperty().set(codeInsurance);
    }

    public final StringProperty insuranceNameProperty() {
        return this.insuranceName;
    }

    public String getInsuranceName() {
        return insuranceNameProperty().get();
    }

    public void setInsuranceName(String insuranceName) {
        insuranceNameProperty().set(insuranceName);
    }

    public final StringProperty insuranceCompanyProperty() {
        return this.insuranceCompany;
    }

    public String getInsuranceCompany() {
        return insuranceCompanyProperty().get();
    }

    public void setInsuranceCompany(String insuranceCompany) {
        insuranceCompanyProperty().set(insuranceCompany);
    }

    public final ObjectProperty<BigDecimal> insuranceNominalProperty() {
        return this.insuranceNominal;
    }

    public BigDecimal getInsuranceNominal() {
        return insuranceNominalProperty().get();
    }

    public void setInsuranceNominal(BigDecimal insuranceNominal) {
        insuranceNominalProperty().set(insuranceNominal);
    }

    public final StringProperty insuranceNoteProperty() {
        return this.insuranceNote;
    }

    public String getInsuranceNote() {
        return insuranceNoteProperty().get();
    }

    public void setInsuranceNote(String insuranceNote) {
        insuranceNoteProperty().set(insuranceNote);
    }

    public final StringProperty companyNoteProperty() {
        return this.companyNote;
    }

    public String getCompanyNote() {
        return companyNoteProperty().get();
    }

    public void setCompanyNote(String companyNote) {
        companyNoteProperty().set(companyNote);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

    public Set getTblEmployeeEmployeeInsurances() {
        return this.tblEmployeeEmployeeInsurances;
    }

    public void setTblEmployeeEmployeeInsurances(Set tblEmployeeEmployeeInsurances) {
        this.tblEmployeeEmployeeInsurances = tblEmployeeEmployeeInsurances;
    }

}
