package hotelfx.persistence.model;
// Generated Aug 21, 2017 1:49:32 PM by Hibernate Tools 4.3.1

import java.util.Date;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblEmployeeEmployeeThr generated by hbm2java
 */
public class TblEmployeeEmployeeThr implements java.io.Serializable {

    private final LongProperty idrelation;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByIdemployee;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblEmployeeThr> tblEmployeeThr;
    private final ObjectProperty<Date> joinDate;
    private final LongProperty basicSalary;
    private final LongProperty thrnominal;
    private final StringProperty detailNote;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    public TblEmployeeEmployeeThr() {
        this.idrelation = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByIdemployee = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblEmployeeThr = new SimpleObjectProperty<>();
        this.joinDate = new SimpleObjectProperty<>();
        this.basicSalary = new SimpleLongProperty();
        this.thrnominal = new SimpleLongProperty();
        this.detailNote = new SimpleStringProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

    }

    public TblEmployeeEmployeeThr(long idrelation) {
        this();
        idrelationProperty().set(idrelation);
    }

    public TblEmployeeEmployeeThr(long idrelation, RefRecordStatus refRecordStatus, TblEmployee tblEmployeeByCreateBy, TblEmployee tblEmployeeByIdemployee, TblEmployee tblEmployeeByLastUpdateBy, TblEmployeeThr tblEmployeeThr, Date joinDate, Long basicSalary, Long thrnominal, String detailNote, Date createDate, Date lastUpdateDate) {
        this();
        idrelationProperty().set(idrelation);
        refRecordStatusProperty().set(refRecordStatus);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblEmployeeByIdemployeeProperty().set(tblEmployeeByIdemployee);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblEmployeeThrProperty().set(tblEmployeeThr);
        joinDateProperty().set(joinDate);
        basicSalaryProperty().set(basicSalary);
        thrnominalProperty().set(thrnominal);
        detailNoteProperty().set(detailNote);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

    }

    public TblEmployeeEmployeeThr(TblEmployeeEmployeeThr tblEmployeeEmployeeThr) {
        this();
        idrelationProperty().set(tblEmployeeEmployeeThr.getIdrelation());
        refRecordStatusProperty().set(tblEmployeeEmployeeThr.getRefRecordStatus());
        tblEmployeeByCreateByProperty().set(tblEmployeeEmployeeThr.getTblEmployeeByCreateBy());
        tblEmployeeByIdemployeeProperty().set(tblEmployeeEmployeeThr.getTblEmployeeByIdemployee());
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeEmployeeThr.getTblEmployeeByLastUpdateBy());
        tblEmployeeThrProperty().set(tblEmployeeEmployeeThr.getTblEmployeeThr());
        joinDateProperty().set(tblEmployeeEmployeeThr.getJoinDate());
        basicSalaryProperty().set(tblEmployeeEmployeeThr.getBasicSalary());
        thrnominalProperty().set(tblEmployeeEmployeeThr.getThrnominal());
        detailNoteProperty().set(tblEmployeeEmployeeThr.getDetailNote());
        createDateProperty().set(tblEmployeeEmployeeThr.getCreateDate());
        lastUpdateDateProperty().set(tblEmployeeEmployeeThr.getLastUpdateDate());

    }

    public final LongProperty idrelationProperty() {
        return this.idrelation;
    }

    public long getIdrelation() {
        return idrelationProperty().get();
    }

    public void setIdrelation(long idrelation) {
        idrelationProperty().set(idrelation);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByIdemployeeProperty() {
        return this.tblEmployeeByIdemployee;
    }

    public TblEmployee getTblEmployeeByIdemployee() {
        return tblEmployeeByIdemployeeProperty().get();
    }

    public void setTblEmployeeByIdemployee(TblEmployee tblEmployeeByIdemployee) {
        tblEmployeeByIdemployeeProperty().set(tblEmployeeByIdemployee);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblEmployeeThr> tblEmployeeThrProperty() {
        return this.tblEmployeeThr;
    }

    public TblEmployeeThr getTblEmployeeThr() {
        return tblEmployeeThrProperty().get();
    }

    public void setTblEmployeeThr(TblEmployeeThr tblEmployeeThr) {
        tblEmployeeThrProperty().set(tblEmployeeThr);
    }

    public final ObjectProperty<Date> joinDateProperty() {
        return this.joinDate;
    }

    public Date getJoinDate() {
        return joinDateProperty().get();
    }

    public void setJoinDate(Date joinDate) {
        joinDateProperty().set(joinDate);
    }

    public final LongProperty basicSalaryProperty() {
        return this.basicSalary;
    }

    public Long getBasicSalary() {
        return basicSalaryProperty().get();
    }

    public void setBasicSalary(Long basicSalary) {
        basicSalaryProperty().set(basicSalary);
    }

    public final LongProperty thrnominalProperty() {
        return this.thrnominal;
    }

    public Long getThrnominal() {
        return thrnominalProperty().get();
    }

    public void setThrnominal(Long thrnominal) {
        thrnominalProperty().set(thrnominal);
    }

    public final StringProperty detailNoteProperty() {
        return this.detailNote;
    }

    public String getDetailNote() {
        return detailNoteProperty().get();
    }

    public void setDetailNote(String detailNote) {
        detailNoteProperty().set(detailNote);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

}
