package hotelfx.persistence.model;
// Generated Aug 21, 2017 1:49:32 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblEmployeeServiceCharge generated by hbm2java
 */
public class TblEmployeeServiceCharge implements java.io.Serializable {

    private final LongProperty idserviceCharge;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblFinanceData> tblFinanceData;
    private final StringProperty codeServiceCharge;
    private final LongProperty companyRecoup;
    private final ObjectProperty<Date> serviceChargeDateCreated;
    private final StringProperty serviceChargeNote;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    private Set tblEmployeeEmployeeServiceCharges;

    public TblEmployeeServiceCharge() {
        this.idserviceCharge = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblFinanceData = new SimpleObjectProperty<>();
        this.codeServiceCharge = new SimpleStringProperty();
        this.companyRecoup = new SimpleLongProperty();
        this.serviceChargeDateCreated = new SimpleObjectProperty<>();
        this.serviceChargeNote = new SimpleStringProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

        this.tblEmployeeEmployeeServiceCharges = new HashSet(0);
    }

    public TblEmployeeServiceCharge(long idserviceCharge) {
        this();
        idserviceChargeProperty().set(idserviceCharge);
    }

    public TblEmployeeServiceCharge(long idserviceCharge, RefRecordStatus refRecordStatus, TblEmployee tblEmployeeByCreateBy, TblEmployee tblEmployeeByLastUpdateBy, TblFinanceData tblFinanceData, String codeServiceCharge, Long companyRecoup, Date serviceChargeDateCreated, String serviceChargeNote, Date createDate, Date lastUpdateDate, Set tblEmployeeEmployeeServiceCharges) {
        this();
        idserviceChargeProperty().set(idserviceCharge);
        refRecordStatusProperty().set(refRecordStatus);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblFinanceDataProperty().set(tblFinanceData);
        codeServiceChargeProperty().set(codeServiceCharge);
        companyRecoupProperty().set(companyRecoup);
        serviceChargeDateCreatedProperty().set(serviceChargeDateCreated);
        serviceChargeNoteProperty().set(serviceChargeNote);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

        this.tblEmployeeEmployeeServiceCharges = tblEmployeeEmployeeServiceCharges;
    }

    public TblEmployeeServiceCharge(TblEmployeeServiceCharge tblEmployeeServiceCharge) {
        this();
        idserviceChargeProperty().set(tblEmployeeServiceCharge.getIdserviceCharge());
        refRecordStatusProperty().set(tblEmployeeServiceCharge.getRefRecordStatus());
        tblEmployeeByCreateByProperty().set(tblEmployeeServiceCharge.getTblEmployeeByCreateBy());
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeServiceCharge.getTblEmployeeByLastUpdateBy());
        tblFinanceDataProperty().set(tblEmployeeServiceCharge.getTblFinanceData());
        codeServiceChargeProperty().set(tblEmployeeServiceCharge.getCodeServiceCharge());
        companyRecoupProperty().set(tblEmployeeServiceCharge.getCompanyRecoup());
        serviceChargeDateCreatedProperty().set(tblEmployeeServiceCharge.getServiceChargeDateCreated());
        serviceChargeNoteProperty().set(tblEmployeeServiceCharge.getServiceChargeNote());
        createDateProperty().set(tblEmployeeServiceCharge.getCreateDate());
        lastUpdateDateProperty().set(tblEmployeeServiceCharge.getLastUpdateDate());

        this.tblEmployeeEmployeeServiceCharges = tblEmployeeServiceCharge.getTblEmployeeEmployeeServiceCharges();
    }

    public final LongProperty idserviceChargeProperty() {
        return this.idserviceCharge;
    }

    public long getIdserviceCharge() {
        return idserviceChargeProperty().get();
    }

    public void setIdserviceCharge(long idserviceCharge) {
        idserviceChargeProperty().set(idserviceCharge);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblFinanceData> tblFinanceDataProperty() {
        return this.tblFinanceData;
    }

    public TblFinanceData getTblFinanceData() {
        return tblFinanceDataProperty().get();
    }

    public void setTblFinanceData(TblFinanceData tblFinanceData) {
        tblFinanceDataProperty().set(tblFinanceData);
    }

    public final StringProperty codeServiceChargeProperty() {
        return this.codeServiceCharge;
    }

    public String getCodeServiceCharge() {
        return codeServiceChargeProperty().get();
    }

    public void setCodeServiceCharge(String codeServiceCharge) {
        codeServiceChargeProperty().set(codeServiceCharge);
    }

    public final LongProperty companyRecoupProperty() {
        return this.companyRecoup;
    }

    public Long getCompanyRecoup() {
        return companyRecoupProperty().get();
    }

    public void setCompanyRecoup(Long companyRecoup) {
        companyRecoupProperty().set(companyRecoup);
    }

    public final ObjectProperty<Date> serviceChargeDateCreatedProperty() {
        return this.serviceChargeDateCreated;
    }

    public Date getServiceChargeDateCreated() {
        return serviceChargeDateCreatedProperty().get();
    }

    public void setServiceChargeDateCreated(Date serviceChargeDateCreated) {
        serviceChargeDateCreatedProperty().set(serviceChargeDateCreated);
    }

    public final StringProperty serviceChargeNoteProperty() {
        return this.serviceChargeNote;
    }

    public String getServiceChargeNote() {
        return serviceChargeNoteProperty().get();
    }

    public void setServiceChargeNote(String serviceChargeNote) {
        serviceChargeNoteProperty().set(serviceChargeNote);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

    public Set getTblEmployeeEmployeeServiceCharges() {
        return this.tblEmployeeEmployeeServiceCharges;
    }

    public void setTblEmployeeEmployeeServiceCharges(Set tblEmployeeEmployeeServiceCharges) {
        this.tblEmployeeEmployeeServiceCharges = tblEmployeeEmployeeServiceCharges;
    }

}
