package hotelfx.persistence.model;
// Generated Aug 21, 2017 1:49:32 PM by Hibernate Tools 4.3.1

import java.util.Date;

import javafx.beans.property.IntegerProperty;
import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleIntegerProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblEmployeeEmployeeServiceCharge generated by hbm2java
 */
public class TblEmployeeEmployeeServiceCharge implements java.io.Serializable {

    private final LongProperty idrelation;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByIdemployee;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblEmployeeServiceCharge> tblEmployeeServiceCharge;
    private final StringProperty idjob;
    private final IntegerProperty serviceChargeWeight;
    private final LongProperty serviceChargeNominal;
    private final StringProperty detailNote;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    public TblEmployeeEmployeeServiceCharge() {
        this.idrelation = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByIdemployee = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblEmployeeServiceCharge = new SimpleObjectProperty<>();
        this.idjob = new SimpleStringProperty();
        this.serviceChargeWeight = new SimpleIntegerProperty();
        this.serviceChargeNominal = new SimpleLongProperty();
        this.detailNote = new SimpleStringProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

    }

    public TblEmployeeEmployeeServiceCharge(long idrelation) {
        this();
        idrelationProperty().set(idrelation);
    }

    public TblEmployeeEmployeeServiceCharge(long idrelation, RefRecordStatus refRecordStatus, TblEmployee tblEmployeeByIdemployee, TblEmployee tblEmployeeByLastUpdateBy, TblEmployee tblEmployeeByCreateBy, TblEmployeeServiceCharge tblEmployeeServiceCharge, String idjob, Integer serviceChargeWeight, Long serviceChargeNominal, String detailNote, Date createDate, Date lastUpdateDate) {
        this();
        idrelationProperty().set(idrelation);
        refRecordStatusProperty().set(refRecordStatus);
        tblEmployeeByIdemployeeProperty().set(tblEmployeeByIdemployee);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblEmployeeServiceChargeProperty().set(tblEmployeeServiceCharge);
        idjobProperty().set(idjob);
        serviceChargeWeightProperty().set(serviceChargeWeight);
        serviceChargeNominalProperty().set(serviceChargeNominal);
        detailNoteProperty().set(detailNote);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

    }

    public TblEmployeeEmployeeServiceCharge(TblEmployeeEmployeeServiceCharge tblEmployeeEmployeeServiceCharge) {
        this();
        idrelationProperty().set(tblEmployeeEmployeeServiceCharge.getIdrelation());
        refRecordStatusProperty().set(tblEmployeeEmployeeServiceCharge.getRefRecordStatus());
        tblEmployeeByIdemployeeProperty().set(tblEmployeeEmployeeServiceCharge.getTblEmployeeByIdemployee());
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeEmployeeServiceCharge.getTblEmployeeByLastUpdateBy());
        tblEmployeeByCreateByProperty().set(tblEmployeeEmployeeServiceCharge.getTblEmployeeByCreateBy());
        tblEmployeeServiceChargeProperty().set(tblEmployeeEmployeeServiceCharge.getTblEmployeeServiceCharge());
        idjobProperty().set(tblEmployeeEmployeeServiceCharge.getIdjob());
        serviceChargeWeightProperty().set(tblEmployeeEmployeeServiceCharge.getServiceChargeWeight());
        serviceChargeNominalProperty().set(tblEmployeeEmployeeServiceCharge.getServiceChargeNominal());
        detailNoteProperty().set(tblEmployeeEmployeeServiceCharge.getDetailNote());
        createDateProperty().set(tblEmployeeEmployeeServiceCharge.getCreateDate());
        lastUpdateDateProperty().set(tblEmployeeEmployeeServiceCharge.getLastUpdateDate());

    }

    public final LongProperty idrelationProperty() {
        return this.idrelation;
    }

    public long getIdrelation() {
        return idrelationProperty().get();
    }

    public void setIdrelation(long idrelation) {
        idrelationProperty().set(idrelation);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByIdemployeeProperty() {
        return this.tblEmployeeByIdemployee;
    }

    public TblEmployee getTblEmployeeByIdemployee() {
        return tblEmployeeByIdemployeeProperty().get();
    }

    public void setTblEmployeeByIdemployee(TblEmployee tblEmployeeByIdemployee) {
        tblEmployeeByIdemployeeProperty().set(tblEmployeeByIdemployee);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblEmployeeServiceCharge> tblEmployeeServiceChargeProperty() {
        return this.tblEmployeeServiceCharge;
    }

    public TblEmployeeServiceCharge getTblEmployeeServiceCharge() {
        return tblEmployeeServiceChargeProperty().get();
    }

    public void setTblEmployeeServiceCharge(TblEmployeeServiceCharge tblEmployeeServiceCharge) {
        tblEmployeeServiceChargeProperty().set(tblEmployeeServiceCharge);
    }

    public final StringProperty idjobProperty() {
        return this.idjob;
    }

    public String getIdjob() {
        return idjobProperty().get();
    }

    public void setIdjob(String idjob) {
        idjobProperty().set(idjob);
    }

    public final IntegerProperty serviceChargeWeightProperty() {
        return this.serviceChargeWeight;
    }

    public Integer getServiceChargeWeight() {
        return serviceChargeWeightProperty().get();
    }

    public void setServiceChargeWeight(Integer serviceChargeWeight) {
        serviceChargeWeightProperty().set(serviceChargeWeight);
    }

    public final LongProperty serviceChargeNominalProperty() {
        return this.serviceChargeNominal;
    }

    public Long getServiceChargeNominal() {
        return serviceChargeNominalProperty().get();
    }

    public void setServiceChargeNominal(Long serviceChargeNominal) {
        serviceChargeNominalProperty().set(serviceChargeNominal);
    }

    public final StringProperty detailNoteProperty() {
        return this.detailNote;
    }

    public String getDetailNote() {
        return detailNoteProperty().get();
    }

    public void setDetailNote(String detailNote) {
        detailNoteProperty().set(detailNote);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

}
