package hotelfx.persistence.model;
// Generated Aug 21, 2017 1:49:32 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblEmployeeOvertime generated by hbm2java
 */
public class TblEmployeeOvertime implements java.io.Serializable {

    private final LongProperty idovertime;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final StringProperty codeOvertime;
    private final StringProperty overtimeName;
    private final ObjectProperty<Date> dateCreated;
    private final StringProperty overtimeNote;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    private Set tblEmployeeOvertimeDetails;

    public TblEmployeeOvertime() {
        this.idovertime = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.codeOvertime = new SimpleStringProperty();
        this.overtimeName = new SimpleStringProperty();
        this.dateCreated = new SimpleObjectProperty<>();
        this.overtimeNote = new SimpleStringProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

        this.tblEmployeeOvertimeDetails = new HashSet(0);
    }

    public TblEmployeeOvertime(long idovertime) {
        this();
        idovertimeProperty().set(idovertime);
    }

    public TblEmployeeOvertime(long idovertime, RefRecordStatus refRecordStatus, TblEmployee tblEmployeeByLastUpdateBy, TblEmployee tblEmployeeByCreateBy, String codeOvertime, String overtimeName, Date dateCreated, String overtimeNote, Date createDate, Date lastUpdateDate, Set tblEmployeeOvertimeDetails) {
        this();
        idovertimeProperty().set(idovertime);
        refRecordStatusProperty().set(refRecordStatus);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        codeOvertimeProperty().set(codeOvertime);
        overtimeNameProperty().set(overtimeName);
        dateCreatedProperty().set(dateCreated);
        overtimeNoteProperty().set(overtimeNote);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

        this.tblEmployeeOvertimeDetails = tblEmployeeOvertimeDetails;
    }

    public TblEmployeeOvertime(TblEmployeeOvertime tblEmployeeOvertime) {
        this();
        idovertimeProperty().set(tblEmployeeOvertime.getIdovertime());
        refRecordStatusProperty().set(tblEmployeeOvertime.getRefRecordStatus());
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeOvertime.getTblEmployeeByLastUpdateBy());
        tblEmployeeByCreateByProperty().set(tblEmployeeOvertime.getTblEmployeeByCreateBy());
        codeOvertimeProperty().set(tblEmployeeOvertime.getCodeOvertime());
        overtimeNameProperty().set(tblEmployeeOvertime.getOvertimeName());
        dateCreatedProperty().set(tblEmployeeOvertime.getDateCreated());
        overtimeNoteProperty().set(tblEmployeeOvertime.getOvertimeNote());
        createDateProperty().set(tblEmployeeOvertime.getCreateDate());
        lastUpdateDateProperty().set(tblEmployeeOvertime.getLastUpdateDate());

        this.tblEmployeeOvertimeDetails = tblEmployeeOvertime.getTblEmployeeOvertimeDetails();
    }

    public final LongProperty idovertimeProperty() {
        return this.idovertime;
    }

    public long getIdovertime() {
        return idovertimeProperty().get();
    }

    public void setIdovertime(long idovertime) {
        idovertimeProperty().set(idovertime);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final StringProperty codeOvertimeProperty() {
        return this.codeOvertime;
    }

    public String getCodeOvertime() {
        return codeOvertimeProperty().get();
    }

    public void setCodeOvertime(String codeOvertime) {
        codeOvertimeProperty().set(codeOvertime);
    }

    public final StringProperty overtimeNameProperty() {
        return this.overtimeName;
    }

    public String getOvertimeName() {
        return overtimeNameProperty().get();
    }

    public void setOvertimeName(String overtimeName) {
        overtimeNameProperty().set(overtimeName);
    }

    public final ObjectProperty<Date> dateCreatedProperty() {
        return this.dateCreated;
    }

    public Date getDateCreated() {
        return dateCreatedProperty().get();
    }

    public void setDateCreated(Date dateCreated) {
        dateCreatedProperty().set(dateCreated);
    }

    public final StringProperty overtimeNoteProperty() {
        return this.overtimeNote;
    }

    public String getOvertimeNote() {
        return overtimeNoteProperty().get();
    }

    public void setOvertimeNote(String overtimeNote) {
        overtimeNoteProperty().set(overtimeNote);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

    public Set getTblEmployeeOvertimeDetails() {
        return this.tblEmployeeOvertimeDetails;
    }

    public void setTblEmployeeOvertimeDetails(Set tblEmployeeOvertimeDetails) {
        this.tblEmployeeOvertimeDetails = tblEmployeeOvertimeDetails;
    }

}
