package hotelfx.persistence.model;
// Generated Aug 21, 2017 1:49:32 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblEmployeeThr generated by hbm2java
 */
public class TblEmployeeThr implements java.io.Serializable {

    private final LongProperty idthr;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblFinanceData> tblFinanceData;
    private final StringProperty codeThr;
    private final StringProperty thrname;
    private final ObjectProperty<Date> thrdate;
    private final ObjectProperty<BigDecimal> thrpercentage;
    private final LongProperty roundValue;
    private final ObjectProperty<Date> thrdateCreated;
    private final StringProperty thrnote;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    private Set tblEmployeeEmployeeThrs;

    public TblEmployeeThr() {
        this.idthr = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblFinanceData = new SimpleObjectProperty<>();
        this.codeThr = new SimpleStringProperty();
        this.thrname = new SimpleStringProperty();
        this.thrdate = new SimpleObjectProperty<>();
        this.thrpercentage = new SimpleObjectProperty<>();
        this.roundValue = new SimpleLongProperty();
        this.thrdateCreated = new SimpleObjectProperty<>();
        this.thrnote = new SimpleStringProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

        this.tblEmployeeEmployeeThrs = new HashSet(0);
    }

    public TblEmployeeThr(long idthr) {
        this();
        idthrProperty().set(idthr);
    }

    public TblEmployeeThr(long idthr, RefRecordStatus refRecordStatus, TblEmployee tblEmployeeByCreateBy, TblEmployee tblEmployeeByLastUpdateBy, TblFinanceData tblFinanceData, String codeThr, String thrname, Date thrdate, BigDecimal thrpercentage, Long roundValue, Date thrdateCreated, String thrnote, Date createDate, Date lastUpdateDate, Set tblEmployeeEmployeeThrs) {
        this();
        idthrProperty().set(idthr);
        refRecordStatusProperty().set(refRecordStatus);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblFinanceDataProperty().set(tblFinanceData);
        codeThrProperty().set(codeThr);
        thrnameProperty().set(thrname);
        thrdateProperty().set(thrdate);
        thrpercentageProperty().set(thrpercentage);
        roundValueProperty().set(roundValue);
        thrdateCreatedProperty().set(thrdateCreated);
        thrnoteProperty().set(thrnote);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

        this.tblEmployeeEmployeeThrs = tblEmployeeEmployeeThrs;
    }

    public TblEmployeeThr(TblEmployeeThr tblEmployeeThr) {
        this();
        idthrProperty().set(tblEmployeeThr.getIdthr());
        refRecordStatusProperty().set(tblEmployeeThr.getRefRecordStatus());
        tblEmployeeByCreateByProperty().set(tblEmployeeThr.getTblEmployeeByCreateBy());
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeThr.getTblEmployeeByLastUpdateBy());
        tblFinanceDataProperty().set(tblEmployeeThr.getTblFinanceData());
        codeThrProperty().set(tblEmployeeThr.getCodeThr());
        thrnameProperty().set(tblEmployeeThr.getThrname());
        thrdateProperty().set(tblEmployeeThr.getThrdate());
        thrpercentageProperty().set(tblEmployeeThr.getThrpercentage());
        roundValueProperty().set(tblEmployeeThr.getRoundValue());
        thrdateCreatedProperty().set(tblEmployeeThr.getThrdateCreated());
        thrnoteProperty().set(tblEmployeeThr.getThrnote());
        createDateProperty().set(tblEmployeeThr.getCreateDate());
        lastUpdateDateProperty().set(tblEmployeeThr.getLastUpdateDate());

        this.tblEmployeeEmployeeThrs = tblEmployeeThr.getTblEmployeeEmployeeThrs();
    }

    public final LongProperty idthrProperty() {
        return this.idthr;
    }

    public long getIdthr() {
        return idthrProperty().get();
    }

    public void setIdthr(long idthr) {
        idthrProperty().set(idthr);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblFinanceData> tblFinanceDataProperty() {
        return this.tblFinanceData;
    }

    public TblFinanceData getTblFinanceData() {
        return tblFinanceDataProperty().get();
    }

    public void setTblFinanceData(TblFinanceData tblFinanceData) {
        tblFinanceDataProperty().set(tblFinanceData);
    }

    public final StringProperty codeThrProperty() {
        return this.codeThr;
    }

    public String getCodeThr() {
        return codeThrProperty().get();
    }

    public void setCodeThr(String codeThr) {
        codeThrProperty().set(codeThr);
    }

    public final StringProperty thrnameProperty() {
        return this.thrname;
    }

    public String getThrname() {
        return thrnameProperty().get();
    }

    public void setThrname(String thrname) {
        thrnameProperty().set(thrname);
    }

    public final ObjectProperty<Date> thrdateProperty() {
        return this.thrdate;
    }

    public Date getThrdate() {
        return thrdateProperty().get();
    }

    public void setThrdate(Date thrdate) {
        thrdateProperty().set(thrdate);
    }

    public final ObjectProperty<BigDecimal> thrpercentageProperty() {
        return this.thrpercentage;
    }

    public BigDecimal getThrpercentage() {
        return thrpercentageProperty().get();
    }

    public void setThrpercentage(BigDecimal thrpercentage) {
        thrpercentageProperty().set(thrpercentage);
    }

    public final LongProperty roundValueProperty() {
        return this.roundValue;
    }

    public Long getRoundValue() {
        return roundValueProperty().get();
    }

    public void setRoundValue(Long roundValue) {
        roundValueProperty().set(roundValue);
    }

    public final ObjectProperty<Date> thrdateCreatedProperty() {
        return this.thrdateCreated;
    }

    public Date getThrdateCreated() {
        return thrdateCreatedProperty().get();
    }

    public void setThrdateCreated(Date thrdateCreated) {
        thrdateCreatedProperty().set(thrdateCreated);
    }

    public final StringProperty thrnoteProperty() {
        return this.thrnote;
    }

    public String getThrnote() {
        return thrnoteProperty().get();
    }

    public void setThrnote(String thrnote) {
        thrnoteProperty().set(thrnote);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

    public Set getTblEmployeeEmployeeThrs() {
        return this.tblEmployeeEmployeeThrs;
    }

    public void setTblEmployeeEmployeeThrs(Set tblEmployeeEmployeeThrs) {
        this.tblEmployeeEmployeeThrs = tblEmployeeEmployeeThrs;
    }

}
