package hotelfx.persistence.model;
// Generated Aug 21, 2017 1:49:32 PM by Hibernate Tools 4.3.1

import java.util.Date;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblEndOfDay generated by hbm2java
 */
public class TblEndOfDay implements java.io.Serializable {

    private final LongProperty ideod;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final StringProperty codeEod;
    private final ObjectProperty<Date> eoddate;
    private final ObjectProperty<Date> eoddateTime;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    public TblEndOfDay() {
        this.ideod = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.codeEod = new SimpleStringProperty();
        this.eoddate = new SimpleObjectProperty<>();
        this.eoddateTime = new SimpleObjectProperty<>();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

    }

    public TblEndOfDay(long ideod) {
        this();
        ideodProperty().set(ideod);
    }

    public TblEndOfDay(long ideod, RefRecordStatus refRecordStatus, TblEmployee tblEmployeeByCreateBy, TblEmployee tblEmployeeByLastUpdateBy, String codeEod, Date eoddate, Date eoddateTime, Date createDate, Date lastUpdateDate) {
        this();
        ideodProperty().set(ideod);
        refRecordStatusProperty().set(refRecordStatus);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        codeEodProperty().set(codeEod);
        eoddateProperty().set(eoddate);
        eoddateTimeProperty().set(eoddateTime);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

    }

    public TblEndOfDay(TblEndOfDay tblEndOfDay) {
        this();
        ideodProperty().set(tblEndOfDay.getIdeod());
        refRecordStatusProperty().set(tblEndOfDay.getRefRecordStatus());
        tblEmployeeByCreateByProperty().set(tblEndOfDay.getTblEmployeeByCreateBy());
        tblEmployeeByLastUpdateByProperty().set(tblEndOfDay.getTblEmployeeByLastUpdateBy());
        codeEodProperty().set(tblEndOfDay.getCodeEod());
        eoddateProperty().set(tblEndOfDay.getEoddate());
        eoddateTimeProperty().set(tblEndOfDay.getEoddateTime());
        createDateProperty().set(tblEndOfDay.getCreateDate());
        lastUpdateDateProperty().set(tblEndOfDay.getLastUpdateDate());

    }

    public final LongProperty ideodProperty() {
        return this.ideod;
    }

    public long getIdeod() {
        return ideodProperty().get();
    }

    public void setIdeod(long ideod) {
        ideodProperty().set(ideod);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final StringProperty codeEodProperty() {
        return this.codeEod;
    }

    public String getCodeEod() {
        return codeEodProperty().get();
    }

    public void setCodeEod(String codeEod) {
        codeEodProperty().set(codeEod);
    }

    public final ObjectProperty<Date> eoddateProperty() {
        return this.eoddate;
    }

    public Date getEoddate() {
        return eoddateProperty().get();
    }

    public void setEoddate(Date eoddate) {
        eoddateProperty().set(eoddate);
    }

    public final ObjectProperty<Date> eoddateTimeProperty() {
        return this.eoddateTime;
    }

    public Date getEoddateTime() {
        return eoddateTimeProperty().get();
    }

    public void setEoddateTime(Date eoddateTime) {
        eoddateTimeProperty().set(eoddateTime);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

}
