package hotelfx.persistence.model;
// Generated Aug 21, 2017 1:49:32 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

import javafx.beans.property.IntegerProperty;
import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleIntegerProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblEmployeeResign generated by hbm2java
 */
public class TblEmployeeResign implements java.io.Serializable {

    private final LongProperty idresign;
    private final ObjectProperty<RefEmployeeResignType> refEmployeeResignType;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByIdemployee;
    private final ObjectProperty<TblEmployeePayroll> tblEmployeePayroll;
    private final ObjectProperty<TblFinanceData> tblFinanceData;
    private final StringProperty codeResign;
    private final LongProperty basicSalary;
    private final LongProperty debt;
    private final IntegerProperty leaveNumber;
    private final ObjectProperty<BigDecimal> refundLeavePercentage;
    private final LongProperty severange;
    private final LongProperty roundValue;
    private final ObjectProperty<Date> resignDate;
    private final StringProperty resignNote;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    public TblEmployeeResign() {
        this.idresign = new SimpleLongProperty();
        this.refEmployeeResignType = new SimpleObjectProperty<>();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByIdemployee = new SimpleObjectProperty<>();
        this.tblEmployeePayroll = new SimpleObjectProperty<>();
        this.tblFinanceData = new SimpleObjectProperty<>();
        this.codeResign = new SimpleStringProperty();
        this.basicSalary = new SimpleLongProperty();
        this.debt = new SimpleLongProperty();
        this.leaveNumber = new SimpleIntegerProperty();
        this.refundLeavePercentage = new SimpleObjectProperty<>();
        this.severange = new SimpleLongProperty();
        this.roundValue = new SimpleLongProperty();
        this.resignDate = new SimpleObjectProperty<>();
        this.resignNote = new SimpleStringProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

    }

    public TblEmployeeResign(long idresign) {
        this();
        idresignProperty().set(idresign);
    }

    public TblEmployeeResign(long idresign, RefEmployeeResignType refEmployeeResignType, RefRecordStatus refRecordStatus, TblEmployee tblEmployeeByCreateBy, TblEmployee tblEmployeeByLastUpdateBy, TblEmployee tblEmployeeByIdemployee, TblEmployeePayroll tblEmployeePayroll, TblFinanceData tblFinanceData, String codeResign, Long basicSalary, Long debt, Integer leaveNumber, BigDecimal refundLeavePercentage, Long severange, Long roundValue, Date resignDate, String resignNote, Date createDate, Date lastUpdateDate) {
        this();
        idresignProperty().set(idresign);
        refEmployeeResignTypeProperty().set(refEmployeeResignType);
        refRecordStatusProperty().set(refRecordStatus);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblEmployeeByIdemployeeProperty().set(tblEmployeeByIdemployee);
        tblEmployeePayrollProperty().set(tblEmployeePayroll);
        tblFinanceDataProperty().set(tblFinanceData);
        codeResignProperty().set(codeResign);
        basicSalaryProperty().set(basicSalary);
        debtProperty().set(debt);
        leaveNumberProperty().set(leaveNumber);
        refundLeavePercentageProperty().set(refundLeavePercentage);
        severangeProperty().set(severange);
        roundValueProperty().set(roundValue);
        resignDateProperty().set(resignDate);
        resignNoteProperty().set(resignNote);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

    }

    public TblEmployeeResign(TblEmployeeResign tblEmployeeResign) {
        this();
        idresignProperty().set(tblEmployeeResign.getIdresign());
        refEmployeeResignTypeProperty().set(tblEmployeeResign.getRefEmployeeResignType());
        refRecordStatusProperty().set(tblEmployeeResign.getRefRecordStatus());
        tblEmployeeByCreateByProperty().set(tblEmployeeResign.getTblEmployeeByCreateBy());
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeResign.getTblEmployeeByLastUpdateBy());
        tblEmployeeByIdemployeeProperty().set(tblEmployeeResign.getTblEmployeeByIdemployee());
        tblEmployeePayrollProperty().set(tblEmployeeResign.getTblEmployeePayroll());
        tblFinanceDataProperty().set(tblEmployeeResign.getTblFinanceData());
        codeResignProperty().set(tblEmployeeResign.getCodeResign());
        basicSalaryProperty().set(tblEmployeeResign.getBasicSalary());
        debtProperty().set(tblEmployeeResign.getDebt());
        leaveNumberProperty().set(tblEmployeeResign.getLeaveNumber());
        refundLeavePercentageProperty().set(tblEmployeeResign.getRefundLeavePercentage());
        severangeProperty().set(tblEmployeeResign.getSeverange());
        roundValueProperty().set(tblEmployeeResign.getRoundValue());
        resignDateProperty().set(tblEmployeeResign.getResignDate());
        resignNoteProperty().set(tblEmployeeResign.getResignNote());
        createDateProperty().set(tblEmployeeResign.getCreateDate());
        lastUpdateDateProperty().set(tblEmployeeResign.getLastUpdateDate());

    }

    public final LongProperty idresignProperty() {
        return this.idresign;
    }

    public long getIdresign() {
        return idresignProperty().get();
    }

    public void setIdresign(long idresign) {
        idresignProperty().set(idresign);
    }

    public final ObjectProperty<RefEmployeeResignType> refEmployeeResignTypeProperty() {
        return this.refEmployeeResignType;
    }

    public RefEmployeeResignType getRefEmployeeResignType() {
        return refEmployeeResignTypeProperty().get();
    }

    public void setRefEmployeeResignType(RefEmployeeResignType refEmployeeResignType) {
        refEmployeeResignTypeProperty().set(refEmployeeResignType);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByIdemployeeProperty() {
        return this.tblEmployeeByIdemployee;
    }

    public TblEmployee getTblEmployeeByIdemployee() {
        return tblEmployeeByIdemployeeProperty().get();
    }

    public void setTblEmployeeByIdemployee(TblEmployee tblEmployeeByIdemployee) {
        tblEmployeeByIdemployeeProperty().set(tblEmployeeByIdemployee);
    }

    public final ObjectProperty<TblEmployeePayroll> tblEmployeePayrollProperty() {
        return this.tblEmployeePayroll;
    }

    public TblEmployeePayroll getTblEmployeePayroll() {
        return tblEmployeePayrollProperty().get();
    }

    public void setTblEmployeePayroll(TblEmployeePayroll tblEmployeePayroll) {
        tblEmployeePayrollProperty().set(tblEmployeePayroll);
    }

    public final ObjectProperty<TblFinanceData> tblFinanceDataProperty() {
        return this.tblFinanceData;
    }

    public TblFinanceData getTblFinanceData() {
        return tblFinanceDataProperty().get();
    }

    public void setTblFinanceData(TblFinanceData tblFinanceData) {
        tblFinanceDataProperty().set(tblFinanceData);
    }

    public final StringProperty codeResignProperty() {
        return this.codeResign;
    }

    public String getCodeResign() {
        return codeResignProperty().get();
    }

    public void setCodeResign(String codeResign) {
        codeResignProperty().set(codeResign);
    }

    public final LongProperty basicSalaryProperty() {
        return this.basicSalary;
    }

    public Long getBasicSalary() {
        return basicSalaryProperty().get();
    }

    public void setBasicSalary(Long basicSalary) {
        basicSalaryProperty().set(basicSalary);
    }

    public final LongProperty debtProperty() {
        return this.debt;
    }

    public Long getDebt() {
        return debtProperty().get();
    }

    public void setDebt(Long debt) {
        debtProperty().set(debt);
    }

    public final IntegerProperty leaveNumberProperty() {
        return this.leaveNumber;
    }

    public Integer getLeaveNumber() {
        return leaveNumberProperty().get();
    }

    public void setLeaveNumber(Integer leaveNumber) {
        leaveNumberProperty().set(leaveNumber);
    }

    public final ObjectProperty<BigDecimal> refundLeavePercentageProperty() {
        return this.refundLeavePercentage;
    }

    public BigDecimal getRefundLeavePercentage() {
        return refundLeavePercentageProperty().get();
    }

    public void setRefundLeavePercentage(BigDecimal refundLeavePercentage) {
        refundLeavePercentageProperty().set(refundLeavePercentage);
    }

    public final LongProperty severangeProperty() {
        return this.severange;
    }

    public Long getSeverange() {
        return severangeProperty().get();
    }

    public void setSeverange(Long severange) {
        severangeProperty().set(severange);
    }

    public final LongProperty roundValueProperty() {
        return this.roundValue;
    }

    public Long getRoundValue() {
        return roundValueProperty().get();
    }

    public void setRoundValue(Long roundValue) {
        roundValueProperty().set(roundValue);
    }

    public final ObjectProperty<Date> resignDateProperty() {
        return this.resignDate;
    }

    public Date getResignDate() {
        return resignDateProperty().get();
    }

    public void setResignDate(Date resignDate) {
        resignDateProperty().set(resignDate);
    }

    public final StringProperty resignNoteProperty() {
        return this.resignNote;
    }

    public String getResignNote() {
        return resignNoteProperty().get();
    }

    public void setResignNote(String resignNote) {
        resignNoteProperty().set(resignNote);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

}
