package hotelfx.persistence.model;
// Generated Aug 21, 2017 1:49:32 PM by Hibernate Tools 4.3.1

import java.util.Date;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblEmployeeLeaveDetail generated by hbm2java
 */
public class TblEmployeeLeaveDetail implements java.io.Serializable {

    private final LongProperty iddetail;
    private final ObjectProperty<RefEmployeeLeaveType> refEmployeeLeaveType;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblEmployeeLeave> tblEmployeeLeave;
    private final ObjectProperty<Date> leaveDate;
    private final StringProperty detailNote;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    public TblEmployeeLeaveDetail() {
        this.iddetail = new SimpleLongProperty();
        this.refEmployeeLeaveType = new SimpleObjectProperty<>();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblEmployeeLeave = new SimpleObjectProperty<>();
        this.leaveDate = new SimpleObjectProperty<>();
        this.detailNote = new SimpleStringProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

    }

    public TblEmployeeLeaveDetail(long iddetail) {
        this();
        iddetailProperty().set(iddetail);
    }

    public TblEmployeeLeaveDetail(long iddetail, RefEmployeeLeaveType refEmployeeLeaveType, RefRecordStatus refRecordStatus, TblEmployee tblEmployeeByLastUpdateBy, TblEmployee tblEmployeeByCreateBy, TblEmployeeLeave tblEmployeeLeave, Date leaveDate, String detailNote, Date createDate, Date lastUpdateDate) {
        this();
        iddetailProperty().set(iddetail);
        refEmployeeLeaveTypeProperty().set(refEmployeeLeaveType);
        refRecordStatusProperty().set(refRecordStatus);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblEmployeeLeaveProperty().set(tblEmployeeLeave);
        leaveDateProperty().set(leaveDate);
        detailNoteProperty().set(detailNote);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

    }

    public TblEmployeeLeaveDetail(TblEmployeeLeaveDetail tblEmployeeLeaveDetail) {
        this();
        iddetailProperty().set(tblEmployeeLeaveDetail.getIddetail());
        refEmployeeLeaveTypeProperty().set(tblEmployeeLeaveDetail.getRefEmployeeLeaveType());
        refRecordStatusProperty().set(tblEmployeeLeaveDetail.getRefRecordStatus());
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeLeaveDetail.getTblEmployeeByLastUpdateBy());
        tblEmployeeByCreateByProperty().set(tblEmployeeLeaveDetail.getTblEmployeeByCreateBy());
        tblEmployeeLeaveProperty().set(tblEmployeeLeaveDetail.getTblEmployeeLeave());
        leaveDateProperty().set(tblEmployeeLeaveDetail.getLeaveDate());
        detailNoteProperty().set(tblEmployeeLeaveDetail.getDetailNote());
        createDateProperty().set(tblEmployeeLeaveDetail.getCreateDate());
        lastUpdateDateProperty().set(tblEmployeeLeaveDetail.getLastUpdateDate());

    }

    public final LongProperty iddetailProperty() {
        return this.iddetail;
    }

    public long getIddetail() {
        return iddetailProperty().get();
    }

    public void setIddetail(long iddetail) {
        iddetailProperty().set(iddetail);
    }

    public final ObjectProperty<RefEmployeeLeaveType> refEmployeeLeaveTypeProperty() {
        return this.refEmployeeLeaveType;
    }

    public RefEmployeeLeaveType getRefEmployeeLeaveType() {
        return refEmployeeLeaveTypeProperty().get();
    }

    public void setRefEmployeeLeaveType(RefEmployeeLeaveType refEmployeeLeaveType) {
        refEmployeeLeaveTypeProperty().set(refEmployeeLeaveType);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblEmployeeLeave> tblEmployeeLeaveProperty() {
        return this.tblEmployeeLeave;
    }

    public TblEmployeeLeave getTblEmployeeLeave() {
        return tblEmployeeLeaveProperty().get();
    }

    public void setTblEmployeeLeave(TblEmployeeLeave tblEmployeeLeave) {
        tblEmployeeLeaveProperty().set(tblEmployeeLeave);
    }

    public final ObjectProperty<Date> leaveDateProperty() {
        return this.leaveDate;
    }

    public Date getLeaveDate() {
        return leaveDateProperty().get();
    }

    public void setLeaveDate(Date leaveDate) {
        leaveDateProperty().set(leaveDate);
    }

    public final StringProperty detailNoteProperty() {
        return this.detailNote;
    }

    public String getDetailNote() {
        return detailNoteProperty().get();
    }

    public void setDetailNote(String detailNote) {
        detailNoteProperty().set(detailNote);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

}
