package hotelfx.persistence.model;
// Generated Jun 29, 2018 9:21:45 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javafx.beans.property.BooleanProperty;
import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleBooleanProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblEmployeeAllowance generated by hbm2java
 */
public class TblEmployeeAllowance implements java.io.Serializable {

    private final LongProperty idallowance;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final StringProperty codeAllowance;
    private final StringProperty allowanceName;
    private final ObjectProperty<BigDecimal> allowanceNominal;
    private final StringProperty allowanceNote;
    private final BooleanProperty allowanceStatus;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    private Set tblEmployeeEmployeeAllowances;

    public TblEmployeeAllowance() {
        this.idallowance = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.codeAllowance = new SimpleStringProperty();
        this.allowanceName = new SimpleStringProperty();
        this.allowanceNominal = new SimpleObjectProperty<>();
        this.allowanceNote = new SimpleStringProperty();
        this.allowanceStatus = new SimpleBooleanProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

        this.tblEmployeeEmployeeAllowances = new HashSet(0);
    }

    public TblEmployeeAllowance(long idallowance) {
        this();
        idallowanceProperty().set(idallowance);
    }

    public TblEmployeeAllowance(long idallowance, RefRecordStatus refRecordStatus, TblEmployee tblEmployeeByCreateBy, TblEmployee tblEmployeeByLastUpdateBy, String codeAllowance, String allowanceName, BigDecimal allowanceNominal, String allowanceNote, Boolean allowanceStatus, Date createDate, Date lastUpdateDate, Set tblEmployeeEmployeeAllowances) {
        this();
        idallowanceProperty().set(idallowance);
        refRecordStatusProperty().set(refRecordStatus);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        codeAllowanceProperty().set(codeAllowance);
        allowanceNameProperty().set(allowanceName);
        allowanceNominalProperty().set(allowanceNominal);
        allowanceNoteProperty().set(allowanceNote);
        allowanceStatusProperty().set(allowanceStatus);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

        this.tblEmployeeEmployeeAllowances = tblEmployeeEmployeeAllowances;
    }

    public TblEmployeeAllowance(TblEmployeeAllowance tblEmployeeAllowance) {
        this();
        idallowanceProperty().set(tblEmployeeAllowance.getIdallowance());
        refRecordStatusProperty().set(tblEmployeeAllowance.getRefRecordStatus());
        tblEmployeeByCreateByProperty().set(tblEmployeeAllowance.getTblEmployeeByCreateBy());
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeAllowance.getTblEmployeeByLastUpdateBy());
        codeAllowanceProperty().set(tblEmployeeAllowance.getCodeAllowance());
        allowanceNameProperty().set(tblEmployeeAllowance.getAllowanceName());
        allowanceNominalProperty().set(tblEmployeeAllowance.getAllowanceNominal());
        allowanceNoteProperty().set(tblEmployeeAllowance.getAllowanceNote());
        allowanceStatusProperty().set(tblEmployeeAllowance.getAllowanceStatus());
        createDateProperty().set(tblEmployeeAllowance.getCreateDate());
        lastUpdateDateProperty().set(tblEmployeeAllowance.getLastUpdateDate());

        this.tblEmployeeEmployeeAllowances = tblEmployeeAllowance.getTblEmployeeEmployeeAllowances();
    }

    public final LongProperty idallowanceProperty() {
        return this.idallowance;
    }

    public long getIdallowance() {
        return idallowanceProperty().get();
    }

    public void setIdallowance(long idallowance) {
        idallowanceProperty().set(idallowance);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final StringProperty codeAllowanceProperty() {
        return this.codeAllowance;
    }

    public String getCodeAllowance() {
        return codeAllowanceProperty().get();
    }

    public void setCodeAllowance(String codeAllowance) {
        codeAllowanceProperty().set(codeAllowance);
    }

    public final StringProperty allowanceNameProperty() {
        return this.allowanceName;
    }

    public String getAllowanceName() {
        return allowanceNameProperty().get();
    }

    public void setAllowanceName(String allowanceName) {
        allowanceNameProperty().set(allowanceName);
    }

    public final ObjectProperty<BigDecimal> allowanceNominalProperty() {
        return this.allowanceNominal;
    }

    public BigDecimal getAllowanceNominal() {
        return allowanceNominalProperty().get();
    }

    public void setAllowanceNominal(BigDecimal allowanceNominal) {
        allowanceNominalProperty().set(allowanceNominal);
    }

    public final StringProperty allowanceNoteProperty() {
        return this.allowanceNote;
    }

    public String getAllowanceNote() {
        return allowanceNoteProperty().get();
    }

    public void setAllowanceNote(String allowanceNote) {
        allowanceNoteProperty().set(allowanceNote);
    }

    public final BooleanProperty allowanceStatusProperty() {
        return this.allowanceStatus;
    }

    public Boolean getAllowanceStatus() {
        return allowanceStatusProperty().get();
    }

    public void setAllowanceStatus(Boolean allowanceStatus) {
        allowanceStatusProperty().set(allowanceStatus);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

    public Set getTblEmployeeEmployeeAllowances() {
        return this.tblEmployeeEmployeeAllowances;
    }

    public void setTblEmployeeEmployeeAllowances(Set tblEmployeeEmployeeAllowances) {
        this.tblEmployeeEmployeeAllowances = tblEmployeeEmployeeAllowances;
    }

}
