package hotelfx.persistence.model;
// Generated Sep 27, 2018 10:59:47 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblEmployeeBankAccount generated by hbm2java
 */
public class TblEmployeeBankAccount implements java.io.Serializable {

    private final LongProperty idrelation;
    private final ObjectProperty<RefBankAccountHolderStatus> refBankAccountHolderStatus;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblBankAccount> tblBankAccount;
    private final ObjectProperty<TblEmployee> tblEmployeeByIdemployee;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final StringProperty employeeBankAccountNote;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    private Set tblCalendarEmployeeDebts;
    private Set tblCalendarEmployeePaymentHistories;

    public TblEmployeeBankAccount() {
        this.idrelation = new SimpleLongProperty();
        this.refBankAccountHolderStatus = new SimpleObjectProperty<>();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblBankAccount = new SimpleObjectProperty<>();
        this.tblEmployeeByIdemployee = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.employeeBankAccountNote = new SimpleStringProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

        this.tblCalendarEmployeeDebts = new HashSet(0);
        this.tblCalendarEmployeePaymentHistories = new HashSet(0);
    }

    public TblEmployeeBankAccount(long idrelation) {
        this();
        idrelationProperty().set(idrelation);
    }

    public TblEmployeeBankAccount(long idrelation, RefBankAccountHolderStatus refBankAccountHolderStatus, RefRecordStatus refRecordStatus, TblBankAccount tblBankAccount, TblEmployee tblEmployeeByIdemployee, TblEmployee tblEmployeeByCreateBy, TblEmployee tblEmployeeByLastUpdateBy, String employeeBankAccountNote, Date createDate, Date lastUpdateDate, Set tblCalendarEmployeeDebts, Set tblCalendarEmployeePaymentHistories) {
        this();
        idrelationProperty().set(idrelation);
        refBankAccountHolderStatusProperty().set(refBankAccountHolderStatus);
        refRecordStatusProperty().set(refRecordStatus);
        tblBankAccountProperty().set(tblBankAccount);
        tblEmployeeByIdemployeeProperty().set(tblEmployeeByIdemployee);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        employeeBankAccountNoteProperty().set(employeeBankAccountNote);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

        this.tblCalendarEmployeeDebts = tblCalendarEmployeeDebts;
        this.tblCalendarEmployeePaymentHistories = tblCalendarEmployeePaymentHistories;
    }

    public TblEmployeeBankAccount(TblEmployeeBankAccount tblEmployeeBankAccount) {
        this();
        idrelationProperty().set(tblEmployeeBankAccount.getIdrelation());
        refBankAccountHolderStatusProperty().set(tblEmployeeBankAccount.getRefBankAccountHolderStatus());
        refRecordStatusProperty().set(tblEmployeeBankAccount.getRefRecordStatus());
        tblBankAccountProperty().set(tblEmployeeBankAccount.getTblBankAccount());
        tblEmployeeByIdemployeeProperty().set(tblEmployeeBankAccount.getTblEmployeeByIdemployee());
        tblEmployeeByCreateByProperty().set(tblEmployeeBankAccount.getTblEmployeeByCreateBy());
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeBankAccount.getTblEmployeeByLastUpdateBy());
        employeeBankAccountNoteProperty().set(tblEmployeeBankAccount.getEmployeeBankAccountNote());
        createDateProperty().set(tblEmployeeBankAccount.getCreateDate());
        lastUpdateDateProperty().set(tblEmployeeBankAccount.getLastUpdateDate());

        this.tblCalendarEmployeeDebts = tblEmployeeBankAccount.getTblCalendarEmployeeDebts();
        this.tblCalendarEmployeePaymentHistories = tblEmployeeBankAccount.getTblCalendarEmployeePaymentHistories();
    }

    public final LongProperty idrelationProperty() {
        return this.idrelation;
    }

    public long getIdrelation() {
        return idrelationProperty().get();
    }

    public void setIdrelation(long idrelation) {
        idrelationProperty().set(idrelation);
    }

    public final ObjectProperty<RefBankAccountHolderStatus> refBankAccountHolderStatusProperty() {
        return this.refBankAccountHolderStatus;
    }

    public RefBankAccountHolderStatus getRefBankAccountHolderStatus() {
        return refBankAccountHolderStatusProperty().get();
    }

    public void setRefBankAccountHolderStatus(RefBankAccountHolderStatus refBankAccountHolderStatus) {
        refBankAccountHolderStatusProperty().set(refBankAccountHolderStatus);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblBankAccount> tblBankAccountProperty() {
        return this.tblBankAccount;
    }

    public TblBankAccount getTblBankAccount() {
        return tblBankAccountProperty().get();
    }

    public void setTblBankAccount(TblBankAccount tblBankAccount) {
        tblBankAccountProperty().set(tblBankAccount);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByIdemployeeProperty() {
        return this.tblEmployeeByIdemployee;
    }

    public TblEmployee getTblEmployeeByIdemployee() {
        return tblEmployeeByIdemployeeProperty().get();
    }

    public void setTblEmployeeByIdemployee(TblEmployee tblEmployeeByIdemployee) {
        tblEmployeeByIdemployeeProperty().set(tblEmployeeByIdemployee);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final StringProperty employeeBankAccountNoteProperty() {
        return this.employeeBankAccountNote;
    }

    public String getEmployeeBankAccountNote() {
        return employeeBankAccountNoteProperty().get();
    }

    public void setEmployeeBankAccountNote(String employeeBankAccountNote) {
        employeeBankAccountNoteProperty().set(employeeBankAccountNote);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

    public Set getTblCalendarEmployeeDebts() {
        return this.tblCalendarEmployeeDebts;
    }

    public void setTblCalendarEmployeeDebts(Set tblCalendarEmployeeDebts) {
        this.tblCalendarEmployeeDebts = tblCalendarEmployeeDebts;
    }

    public Set getTblCalendarEmployeePaymentHistories() {
        return this.tblCalendarEmployeePaymentHistories;
    }

    public void setTblCalendarEmployeePaymentHistories(Set tblCalendarEmployeePaymentHistories) {
        this.tblCalendarEmployeePaymentHistories = tblCalendarEmployeePaymentHistories;
    }

    @Override
    public String toString(){
        return getTblBankAccount().getCodeBankAccount() + " / " + getTblBankAccount().getTblBank().getBankName();
    }
    
}
