package hotelfx.persistence.model;
// Generated Aug 21, 2017 1:49:32 PM by Hibernate Tools 4.3.1

import java.util.Date;

import javafx.beans.property.IntegerProperty;
import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleIntegerProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;

/**
 * TblEmployeeEmployeeCutOffLeave generated by hbm2java
 */
public class TblEmployeeEmployeeCutOffLeave implements java.io.Serializable {

    private final LongProperty idrelation;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByIdemployee;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblEmployeeCutOffLeave> tblEmployeeCutOffLeave;
    private final ObjectProperty<Date> joinDate;
    private final LongProperty basicSalary;
    private final IntegerProperty lastLeaveNumber;
    private final IntegerProperty newLeaveNumber;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    public TblEmployeeEmployeeCutOffLeave() {
        this.idrelation = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByIdemployee = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblEmployeeCutOffLeave = new SimpleObjectProperty<>();
        this.joinDate = new SimpleObjectProperty<>();
        this.basicSalary = new SimpleLongProperty();
        this.lastLeaveNumber = new SimpleIntegerProperty();
        this.newLeaveNumber = new SimpleIntegerProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

    }

    public TblEmployeeEmployeeCutOffLeave(long idrelation) {
        this();
        idrelationProperty().set(idrelation);
    }

    public TblEmployeeEmployeeCutOffLeave(long idrelation, RefRecordStatus refRecordStatus, TblEmployee tblEmployeeByIdemployee, TblEmployee tblEmployeeByLastUpdateBy, TblEmployee tblEmployeeByCreateBy, TblEmployeeCutOffLeave tblEmployeeCutOffLeave, Date joinDate, Long basicSalary, Integer lastLeaveNumber, Integer newLeaveNumber, Date createDate, Date lastUpdateDate) {
        this();
        idrelationProperty().set(idrelation);
        refRecordStatusProperty().set(refRecordStatus);
        tblEmployeeByIdemployeeProperty().set(tblEmployeeByIdemployee);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblEmployeeCutOffLeaveProperty().set(tblEmployeeCutOffLeave);
        joinDateProperty().set(joinDate);
        basicSalaryProperty().set(basicSalary);
        lastLeaveNumberProperty().set(lastLeaveNumber);
        newLeaveNumberProperty().set(newLeaveNumber);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

    }

    public TblEmployeeEmployeeCutOffLeave(TblEmployeeEmployeeCutOffLeave tblEmployeeEmployeeCutOffLeave) {
        this();
        idrelationProperty().set(tblEmployeeEmployeeCutOffLeave.getIdrelation());
        refRecordStatusProperty().set(tblEmployeeEmployeeCutOffLeave.getRefRecordStatus());
        tblEmployeeByIdemployeeProperty().set(tblEmployeeEmployeeCutOffLeave.getTblEmployeeByIdemployee());
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeEmployeeCutOffLeave.getTblEmployeeByLastUpdateBy());
        tblEmployeeByCreateByProperty().set(tblEmployeeEmployeeCutOffLeave.getTblEmployeeByCreateBy());
        tblEmployeeCutOffLeaveProperty().set(tblEmployeeEmployeeCutOffLeave.getTblEmployeeCutOffLeave());
        joinDateProperty().set(tblEmployeeEmployeeCutOffLeave.getJoinDate());
        basicSalaryProperty().set(tblEmployeeEmployeeCutOffLeave.getBasicSalary());
        lastLeaveNumberProperty().set(tblEmployeeEmployeeCutOffLeave.getLastLeaveNumber());
        newLeaveNumberProperty().set(tblEmployeeEmployeeCutOffLeave.getNewLeaveNumber());
        createDateProperty().set(tblEmployeeEmployeeCutOffLeave.getCreateDate());
        lastUpdateDateProperty().set(tblEmployeeEmployeeCutOffLeave.getLastUpdateDate());

    }

    public final LongProperty idrelationProperty() {
        return this.idrelation;
    }

    public long getIdrelation() {
        return idrelationProperty().get();
    }

    public void setIdrelation(long idrelation) {
        idrelationProperty().set(idrelation);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByIdemployeeProperty() {
        return this.tblEmployeeByIdemployee;
    }

    public TblEmployee getTblEmployeeByIdemployee() {
        return tblEmployeeByIdemployeeProperty().get();
    }

    public void setTblEmployeeByIdemployee(TblEmployee tblEmployeeByIdemployee) {
        tblEmployeeByIdemployeeProperty().set(tblEmployeeByIdemployee);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblEmployeeCutOffLeave> tblEmployeeCutOffLeaveProperty() {
        return this.tblEmployeeCutOffLeave;
    }

    public TblEmployeeCutOffLeave getTblEmployeeCutOffLeave() {
        return tblEmployeeCutOffLeaveProperty().get();
    }

    public void setTblEmployeeCutOffLeave(TblEmployeeCutOffLeave tblEmployeeCutOffLeave) {
        tblEmployeeCutOffLeaveProperty().set(tblEmployeeCutOffLeave);
    }

    public final ObjectProperty<Date> joinDateProperty() {
        return this.joinDate;
    }

    public Date getJoinDate() {
        return joinDateProperty().get();
    }

    public void setJoinDate(Date joinDate) {
        joinDateProperty().set(joinDate);
    }

    public final LongProperty basicSalaryProperty() {
        return this.basicSalary;
    }

    public Long getBasicSalary() {
        return basicSalaryProperty().get();
    }

    public void setBasicSalary(Long basicSalary) {
        basicSalaryProperty().set(basicSalary);
    }

    public final IntegerProperty lastLeaveNumberProperty() {
        return this.lastLeaveNumber;
    }

    public Integer getLastLeaveNumber() {
        return lastLeaveNumberProperty().get();
    }

    public void setLastLeaveNumber(Integer lastLeaveNumber) {
        lastLeaveNumberProperty().set(lastLeaveNumber);
    }

    public final IntegerProperty newLeaveNumberProperty() {
        return this.newLeaveNumber;
    }

    public Integer getNewLeaveNumber() {
        return newLeaveNumberProperty().get();
    }

    public void setNewLeaveNumber(Integer newLeaveNumber) {
        newLeaveNumberProperty().set(newLeaveNumber);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

}
