package hotelfx.persistence.model;
// Generated Aug 21, 2017 1:49:32 PM by Hibernate Tools 4.3.1

import java.util.Date;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblFixedTangibleAssetLocation generated by hbm2java
 */
public class TblFixedTangibleAssetLocation implements java.io.Serializable {

    private final LongProperty idrelation;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblFixedTangibleAsset> tblFixedTangibleAsset;
    private final ObjectProperty<TblLocation> tblLocation;
    private final StringProperty note;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    public TblFixedTangibleAssetLocation() {
        this.idrelation = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblFixedTangibleAsset = new SimpleObjectProperty<>();
        this.tblLocation = new SimpleObjectProperty<>();
        this.note = new SimpleStringProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

    }

    public TblFixedTangibleAssetLocation(long idrelation) {
        this();
        idrelationProperty().set(idrelation);
    }

    public TblFixedTangibleAssetLocation(long idrelation, RefRecordStatus refRecordStatus, TblEmployee tblEmployeeByCreateBy, TblEmployee tblEmployeeByLastUpdateBy, TblFixedTangibleAsset tblFixedTangibleAsset, TblLocation tblLocation, String note, Date createDate, Date lastUpdateDate) {
        this();
        idrelationProperty().set(idrelation);
        refRecordStatusProperty().set(refRecordStatus);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblFixedTangibleAssetProperty().set(tblFixedTangibleAsset);
        tblLocationProperty().set(tblLocation);
        noteProperty().set(note);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

    }

    public TblFixedTangibleAssetLocation(TblFixedTangibleAssetLocation tblFixedTangibleAssetLocation) {
        this();
        idrelationProperty().set(tblFixedTangibleAssetLocation.getIdrelation());
        refRecordStatusProperty().set(tblFixedTangibleAssetLocation.getRefRecordStatus());
        tblEmployeeByCreateByProperty().set(tblFixedTangibleAssetLocation.getTblEmployeeByCreateBy());
        tblEmployeeByLastUpdateByProperty().set(tblFixedTangibleAssetLocation.getTblEmployeeByLastUpdateBy());
        tblFixedTangibleAssetProperty().set(tblFixedTangibleAssetLocation.getTblFixedTangibleAsset());
        tblLocationProperty().set(tblFixedTangibleAssetLocation.getTblLocation());
        noteProperty().set(tblFixedTangibleAssetLocation.getNote());
        createDateProperty().set(tblFixedTangibleAssetLocation.getCreateDate());
        lastUpdateDateProperty().set(tblFixedTangibleAssetLocation.getLastUpdateDate());

    }

    public final LongProperty idrelationProperty() {
        return this.idrelation;
    }

    public long getIdrelation() {
        return idrelationProperty().get();
    }

    public void setIdrelation(long idrelation) {
        idrelationProperty().set(idrelation);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblFixedTangibleAsset> tblFixedTangibleAssetProperty() {
        return this.tblFixedTangibleAsset;
    }

    public TblFixedTangibleAsset getTblFixedTangibleAsset() {
        return tblFixedTangibleAssetProperty().get();
    }

    public void setTblFixedTangibleAsset(TblFixedTangibleAsset tblFixedTangibleAsset) {
        tblFixedTangibleAssetProperty().set(tblFixedTangibleAsset);
    }

    public final ObjectProperty<TblLocation> tblLocationProperty() {
        return this.tblLocation;
    }

    public TblLocation getTblLocation() {
        return tblLocationProperty().get();
    }

    public void setTblLocation(TblLocation tblLocation) {
        tblLocationProperty().set(tblLocation);
    }

    public final StringProperty noteProperty() {
        return this.note;
    }

    public String getNote() {
        return noteProperty().get();
    }

    public void setNote(String note) {
        noteProperty().set(note);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

}
