package hotelfx.persistence.model;
// Generated May 14, 2018 4:23:20 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblFixedTangibleAsset generated by hbm2java
 */
public class TblFixedTangibleAsset implements java.io.Serializable {

    private final LongProperty idasset;
    private final ObjectProperty<RefFixedTangibleAssetDepreciationStatus> refFixedTangibleAssetDepreciationStatus;
    private final ObjectProperty<RefFixedTangibleAssetType> refFixedTangibleAssetType;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final StringProperty codeAsset;
    private final StringProperty assetName;
    private final ObjectProperty<Date> beginDate;
    private final ObjectProperty<BigDecimal> beginValue;
    private final ObjectProperty<BigDecimal> currentValue;
    private final ObjectProperty<BigDecimal> economicLife;
    private final StringProperty assetNote;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    private Set tblFixedTangibleAssetLocations;
    private Set tblPropertyBarcodes;

    public TblFixedTangibleAsset() {
        this.idasset = new SimpleLongProperty();
        this.refFixedTangibleAssetDepreciationStatus = new SimpleObjectProperty<>();
        this.refFixedTangibleAssetType = new SimpleObjectProperty<>();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.codeAsset = new SimpleStringProperty();
        this.assetName = new SimpleStringProperty();
        this.beginDate = new SimpleObjectProperty<>();
        this.beginValue = new SimpleObjectProperty<>();
        this.currentValue = new SimpleObjectProperty<>();
        this.economicLife = new SimpleObjectProperty<>();
        this.assetNote = new SimpleStringProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

        this.tblFixedTangibleAssetLocations = new HashSet(0);
        this.tblPropertyBarcodes = new HashSet(0);
    }

    public TblFixedTangibleAsset(long idasset) {
        this();
        idassetProperty().set(idasset);
    }

    public TblFixedTangibleAsset(long idasset, RefFixedTangibleAssetDepreciationStatus refFixedTangibleAssetDepreciationStatus, RefFixedTangibleAssetType refFixedTangibleAssetType, RefRecordStatus refRecordStatus, TblEmployee tblEmployeeByLastUpdateBy, TblEmployee tblEmployeeByCreateBy, String codeAsset, String assetName, Date beginDate, BigDecimal beginValue, BigDecimal currentValue, BigDecimal economicLife, String assetNote, Date createDate, Date lastUpdateDate, Set tblFixedTangibleAssetLocations, Set tblPropertyBarcodes) {
        this();
        idassetProperty().set(idasset);
        refFixedTangibleAssetDepreciationStatusProperty().set(refFixedTangibleAssetDepreciationStatus);
        refFixedTangibleAssetTypeProperty().set(refFixedTangibleAssetType);
        refRecordStatusProperty().set(refRecordStatus);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        codeAssetProperty().set(codeAsset);
        assetNameProperty().set(assetName);
        beginDateProperty().set(beginDate);
        beginValueProperty().set(beginValue);
        currentValueProperty().set(currentValue);
        economicLifeProperty().set(economicLife);
        assetNoteProperty().set(assetNote);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

        this.tblFixedTangibleAssetLocations = tblFixedTangibleAssetLocations;
        this.tblPropertyBarcodes = tblPropertyBarcodes;
    }

    public TblFixedTangibleAsset(TblFixedTangibleAsset tblFixedTangibleAsset) {
        this();
        idassetProperty().set(tblFixedTangibleAsset.getIdasset());
        refFixedTangibleAssetDepreciationStatusProperty().set(tblFixedTangibleAsset.getRefFixedTangibleAssetDepreciationStatus());
        refFixedTangibleAssetTypeProperty().set(tblFixedTangibleAsset.getRefFixedTangibleAssetType());
        refRecordStatusProperty().set(tblFixedTangibleAsset.getRefRecordStatus());
        tblEmployeeByLastUpdateByProperty().set(tblFixedTangibleAsset.getTblEmployeeByLastUpdateBy());
        tblEmployeeByCreateByProperty().set(tblFixedTangibleAsset.getTblEmployeeByCreateBy());
        codeAssetProperty().set(tblFixedTangibleAsset.getCodeAsset());
        assetNameProperty().set(tblFixedTangibleAsset.getAssetName());
        beginDateProperty().set(tblFixedTangibleAsset.getBeginDate());
        beginValueProperty().set(tblFixedTangibleAsset.getBeginValue());
        currentValueProperty().set(tblFixedTangibleAsset.getCurrentValue());
        economicLifeProperty().set(tblFixedTangibleAsset.getEconomicLife());
        assetNoteProperty().set(tblFixedTangibleAsset.getAssetNote());
        createDateProperty().set(tblFixedTangibleAsset.getCreateDate());
        lastUpdateDateProperty().set(tblFixedTangibleAsset.getLastUpdateDate());

        this.tblFixedTangibleAssetLocations = tblFixedTangibleAsset.getTblFixedTangibleAssetLocations();
        this.tblPropertyBarcodes = tblFixedTangibleAsset.getTblPropertyBarcodes();
    }

    public final LongProperty idassetProperty() {
        return this.idasset;
    }

    public long getIdasset() {
        return idassetProperty().get();
    }

    public void setIdasset(long idasset) {
        idassetProperty().set(idasset);
    }

    public final ObjectProperty<RefFixedTangibleAssetDepreciationStatus> refFixedTangibleAssetDepreciationStatusProperty() {
        return this.refFixedTangibleAssetDepreciationStatus;
    }

    public RefFixedTangibleAssetDepreciationStatus getRefFixedTangibleAssetDepreciationStatus() {
        return refFixedTangibleAssetDepreciationStatusProperty().get();
    }

    public void setRefFixedTangibleAssetDepreciationStatus(RefFixedTangibleAssetDepreciationStatus refFixedTangibleAssetDepreciationStatus) {
        refFixedTangibleAssetDepreciationStatusProperty().set(refFixedTangibleAssetDepreciationStatus);
    }

    public final ObjectProperty<RefFixedTangibleAssetType> refFixedTangibleAssetTypeProperty() {
        return this.refFixedTangibleAssetType;
    }

    public RefFixedTangibleAssetType getRefFixedTangibleAssetType() {
        return refFixedTangibleAssetTypeProperty().get();
    }

    public void setRefFixedTangibleAssetType(RefFixedTangibleAssetType refFixedTangibleAssetType) {
        refFixedTangibleAssetTypeProperty().set(refFixedTangibleAssetType);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final StringProperty codeAssetProperty() {
        return this.codeAsset;
    }

    public String getCodeAsset() {
        return codeAssetProperty().get();
    }

    public void setCodeAsset(String codeAsset) {
        codeAssetProperty().set(codeAsset);
    }

    public final StringProperty assetNameProperty() {
        return this.assetName;
    }

    public String getAssetName() {
        return assetNameProperty().get();
    }

    public void setAssetName(String assetName) {
        assetNameProperty().set(assetName);
    }

    public final ObjectProperty<Date> beginDateProperty() {
        return this.beginDate;
    }

    public Date getBeginDate() {
        return beginDateProperty().get();
    }

    public void setBeginDate(Date beginDate) {
        beginDateProperty().set(beginDate);
    }

    public final ObjectProperty<BigDecimal> beginValueProperty() {
        return this.beginValue;
    }

    public BigDecimal getBeginValue() {
        return beginValueProperty().get();
    }

    public void setBeginValue(BigDecimal beginValue) {
        beginValueProperty().set(beginValue);
    }

    public final ObjectProperty<BigDecimal> currentValueProperty() {
        return this.currentValue;
    }

    public BigDecimal getCurrentValue() {
        return currentValueProperty().get();
    }

    public void setCurrentValue(BigDecimal currentValue) {
        currentValueProperty().set(currentValue);
    }

    public final ObjectProperty<BigDecimal> economicLifeProperty() {
        return this.economicLife;
    }

    public BigDecimal getEconomicLife() {
        return economicLifeProperty().get();
    }

    public void setEconomicLife(BigDecimal economicLife) {
        economicLifeProperty().set(economicLife);
    }

    public final StringProperty assetNoteProperty() {
        return this.assetNote;
    }

    public String getAssetNote() {
        return assetNoteProperty().get();
    }

    public void setAssetNote(String assetNote) {
        assetNoteProperty().set(assetNote);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

    public Set getTblFixedTangibleAssetLocations() {
        return this.tblFixedTangibleAssetLocations;
    }

    public void setTblFixedTangibleAssetLocations(Set tblFixedTangibleAssetLocations) {
        this.tblFixedTangibleAssetLocations = tblFixedTangibleAssetLocations;
    }

    public Set getTblPropertyBarcodes() {
        return this.tblPropertyBarcodes;
    }

    public void setTblPropertyBarcodes(Set tblPropertyBarcodes) {
        this.tblPropertyBarcodes = tblPropertyBarcodes;
    }

}
