package hotelfx.persistence.model;
// Generated Mar 29, 2018 3:28:56 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblFoundInformation generated by hbm2java
 */
public class TblFoundInformation implements java.io.Serializable {

    private final LongProperty idfound;
    private final ObjectProperty<RefFounderType> refFounderType;
    private final ObjectProperty<RefLostFoundStatus> refLostFoundStatus;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreatedBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByIdemployeeFounder;
    private final ObjectProperty<TblEmployee> tblEmployeeByUpdatedBy;
    private final StringProperty codeFound;
    private final ObjectProperty<Date> foundDate;
    private final StringProperty foundLocation;
    private final StringProperty itemName;
    private final StringProperty founderName;
    private final StringProperty foundNote;
    private final ObjectProperty<Date> createdDate;
    private final ObjectProperty<Date> updatedDate;

    private Set tblLostFoundInformationDetails;

    public TblFoundInformation() {
        this.idfound = new SimpleLongProperty();
        this.refFounderType = new SimpleObjectProperty<>();
        this.refLostFoundStatus = new SimpleObjectProperty<>();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByCreatedBy = new SimpleObjectProperty<>();
        this.tblEmployeeByIdemployeeFounder = new SimpleObjectProperty<>();
        this.tblEmployeeByUpdatedBy = new SimpleObjectProperty<>();
        this.codeFound = new SimpleStringProperty();
        this.foundDate = new SimpleObjectProperty<>();
        this.foundLocation = new SimpleStringProperty();
        this.itemName = new SimpleStringProperty();
        this.founderName = new SimpleStringProperty();
        this.foundNote = new SimpleStringProperty();
        this.createdDate = new SimpleObjectProperty<>();
        this.updatedDate = new SimpleObjectProperty<>();

        this.tblLostFoundInformationDetails = new HashSet(0);
    }

    public TblFoundInformation(long idfound) {
        this();
        idfoundProperty().set(idfound);
    }

    public TblFoundInformation(long idfound, RefFounderType refFounderType, RefLostFoundStatus refLostFoundStatus, RefRecordStatus refRecordStatus, TblEmployee tblEmployeeByCreatedBy, TblEmployee tblEmployeeByIdemployeeFounder, TblEmployee tblEmployeeByUpdatedBy, String codeFound, Date foundDate, String foundLocation, String itemName, String founderName, String foundNote, Date createdDate, Date updatedDate, Set tblLostFoundInformationDetails) {
        this();
        idfoundProperty().set(idfound);
        refFounderTypeProperty().set(refFounderType);
        refLostFoundStatusProperty().set(refLostFoundStatus);
        refRecordStatusProperty().set(refRecordStatus);
        tblEmployeeByCreatedByProperty().set(tblEmployeeByCreatedBy);
        tblEmployeeByIdemployeeFounderProperty().set(tblEmployeeByIdemployeeFounder);
        tblEmployeeByUpdatedByProperty().set(tblEmployeeByUpdatedBy);
        codeFoundProperty().set(codeFound);
        foundDateProperty().set(foundDate);
        foundLocationProperty().set(foundLocation);
        itemNameProperty().set(itemName);
        founderNameProperty().set(founderName);
        foundNoteProperty().set(foundNote);
        createdDateProperty().set(createdDate);
        updatedDateProperty().set(updatedDate);

        this.tblLostFoundInformationDetails = tblLostFoundInformationDetails;
    }

    public TblFoundInformation(TblFoundInformation tblFoundInformation) {
        this();
        idfoundProperty().set(tblFoundInformation.getIdfound());
        refFounderTypeProperty().set(tblFoundInformation.getRefFounderType());
        refLostFoundStatusProperty().set(tblFoundInformation.getRefLostFoundStatus());
        refRecordStatusProperty().set(tblFoundInformation.getRefRecordStatus());
        tblEmployeeByCreatedByProperty().set(tblFoundInformation.getTblEmployeeByCreatedBy());
        tblEmployeeByIdemployeeFounderProperty().set(tblFoundInformation.getTblEmployeeByIdemployeeFounder());
        tblEmployeeByUpdatedByProperty().set(tblFoundInformation.getTblEmployeeByUpdatedBy());
        codeFoundProperty().set(tblFoundInformation.getCodeFound());
        foundDateProperty().set(tblFoundInformation.getFoundDate());
        foundLocationProperty().set(tblFoundInformation.getFoundLocation());
        itemNameProperty().set(tblFoundInformation.getItemName());
        founderNameProperty().set(tblFoundInformation.getFounderName());
        foundNoteProperty().set(tblFoundInformation.getFoundNote());
        createdDateProperty().set(tblFoundInformation.getCreatedDate());
        updatedDateProperty().set(tblFoundInformation.getUpdatedDate());

        this.tblLostFoundInformationDetails = tblFoundInformation.getTblLostFoundInformationDetails();
    }

    public final LongProperty idfoundProperty() {
        return this.idfound;
    }

    public long getIdfound() {
        return idfoundProperty().get();
    }

    public void setIdfound(long idfound) {
        idfoundProperty().set(idfound);
    }

    public final ObjectProperty<RefFounderType> refFounderTypeProperty() {
        return this.refFounderType;
    }

    public RefFounderType getRefFounderType() {
        return refFounderTypeProperty().get();
    }

    public void setRefFounderType(RefFounderType refFounderType) {
        refFounderTypeProperty().set(refFounderType);
    }

    public final ObjectProperty<RefLostFoundStatus> refLostFoundStatusProperty() {
        return this.refLostFoundStatus;
    }

    public RefLostFoundStatus getRefLostFoundStatus() {
        return refLostFoundStatusProperty().get();
    }

    public void setRefLostFoundStatus(RefLostFoundStatus refLostFoundStatus) {
        refLostFoundStatusProperty().set(refLostFoundStatus);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreatedByProperty() {
        return this.tblEmployeeByCreatedBy;
    }

    public TblEmployee getTblEmployeeByCreatedBy() {
        return tblEmployeeByCreatedByProperty().get();
    }

    public void setTblEmployeeByCreatedBy(TblEmployee tblEmployeeByCreatedBy) {
        tblEmployeeByCreatedByProperty().set(tblEmployeeByCreatedBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByIdemployeeFounderProperty() {
        return this.tblEmployeeByIdemployeeFounder;
    }

    public TblEmployee getTblEmployeeByIdemployeeFounder() {
        return tblEmployeeByIdemployeeFounderProperty().get();
    }

    public void setTblEmployeeByIdemployeeFounder(TblEmployee tblEmployeeByIdemployeeFounder) {
        tblEmployeeByIdemployeeFounderProperty().set(tblEmployeeByIdemployeeFounder);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByUpdatedByProperty() {
        return this.tblEmployeeByUpdatedBy;
    }

    public TblEmployee getTblEmployeeByUpdatedBy() {
        return tblEmployeeByUpdatedByProperty().get();
    }

    public void setTblEmployeeByUpdatedBy(TblEmployee tblEmployeeByUpdatedBy) {
        tblEmployeeByUpdatedByProperty().set(tblEmployeeByUpdatedBy);
    }

    public final StringProperty codeFoundProperty() {
        return this.codeFound;
    }

    public String getCodeFound() {
        return codeFoundProperty().get();
    }

    public void setCodeFound(String codeFound) {
        codeFoundProperty().set(codeFound);
    }

    public final ObjectProperty<Date> foundDateProperty() {
        return this.foundDate;
    }

    public Date getFoundDate() {
        return foundDateProperty().get();
    }

    public void setFoundDate(Date foundDate) {
        foundDateProperty().set(foundDate);
    }

    public final StringProperty foundLocationProperty() {
        return this.foundLocation;
    }

    public String getFoundLocation() {
        return foundLocationProperty().get();
    }

    public void setFoundLocation(String foundLocation) {
        foundLocationProperty().set(foundLocation);
    }

    public final StringProperty itemNameProperty() {
        return this.itemName;
    }

    public String getItemName() {
        return itemNameProperty().get();
    }

    public void setItemName(String itemName) {
        itemNameProperty().set(itemName);
    }

    public final StringProperty founderNameProperty() {
        return this.founderName;
    }

    public String getFounderName() {
        return founderNameProperty().get();
    }

    public void setFounderName(String founderName) {
        founderNameProperty().set(founderName);
    }

    public final StringProperty foundNoteProperty() {
        return this.foundNote;
    }

    public String getFoundNote() {
        return foundNoteProperty().get();
    }

    public void setFoundNote(String foundNote) {
        foundNoteProperty().set(foundNote);
    }

    public final ObjectProperty<Date> createdDateProperty() {
        return this.createdDate;
    }

    public Date getCreatedDate() {
        return createdDateProperty().get();
    }

    public void setCreatedDate(Date createdDate) {
        createdDateProperty().set(createdDate);
    }

    public final ObjectProperty<Date> updatedDateProperty() {
        return this.updatedDate;
    }

    public Date getUpdatedDate() {
        return updatedDateProperty().get();
    }

    public void setUpdatedDate(Date updatedDate) {
        updatedDateProperty().set(updatedDate);
    }

    public Set getTblLostFoundInformationDetails() {
        return this.tblLostFoundInformationDetails;
    }

    public void setTblLostFoundInformationDetails(Set tblLostFoundInformationDetails) {
        this.tblLostFoundInformationDetails = tblLostFoundInformationDetails;
    }

    @Override
    public String toString(){
        return getCodeFound();
    }
    
}
