package hotelfx.persistence.model;
// Generated Aug 21, 2017 1:49:32 PM by Hibernate Tools 4.3.1

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TblFloor generated by hbm2java
 */
public class TblFloor implements java.io.Serializable {

    private final LongProperty idfloor;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final StringProperty codeFloor;
    private final StringProperty floorName;
    private final StringProperty floorNote;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    private Set tblLocations;

    public TblFloor() {
        this.idfloor = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.codeFloor = new SimpleStringProperty();
        this.floorName = new SimpleStringProperty();
        this.floorNote = new SimpleStringProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

        this.tblLocations = new HashSet(0);
    }

    public TblFloor(long idfloor) {
        this();
        idfloorProperty().set(idfloor);
    }

    public TblFloor(long idfloor, RefRecordStatus refRecordStatus, TblEmployee tblEmployeeByCreateBy, TblEmployee tblEmployeeByLastUpdateBy, String codeFloor, String floorName, String floorNote, Date createDate, Date lastUpdateDate, Set tblLocations) {
        this();
        idfloorProperty().set(idfloor);
        refRecordStatusProperty().set(refRecordStatus);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        codeFloorProperty().set(codeFloor);
        floorNameProperty().set(floorName);
        floorNoteProperty().set(floorNote);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

        this.tblLocations = tblLocations;
    }

    public TblFloor(TblFloor tblFloor) {
        this();
        idfloorProperty().set(tblFloor.getIdfloor());
        refRecordStatusProperty().set(tblFloor.getRefRecordStatus());
        tblEmployeeByCreateByProperty().set(tblFloor.getTblEmployeeByCreateBy());
        tblEmployeeByLastUpdateByProperty().set(tblFloor.getTblEmployeeByLastUpdateBy());
        codeFloorProperty().set(tblFloor.getCodeFloor());
        floorNameProperty().set(tblFloor.getFloorName());
        floorNoteProperty().set(tblFloor.getFloorNote());
        createDateProperty().set(tblFloor.getCreateDate());
        lastUpdateDateProperty().set(tblFloor.getLastUpdateDate());

        this.tblLocations = tblFloor.getTblLocations();
    }

    public final LongProperty idfloorProperty() {
        return this.idfloor;
    }

    public long getIdfloor() {
        return idfloorProperty().get();
    }

    public void setIdfloor(long idfloor) {
        idfloorProperty().set(idfloor);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final StringProperty codeFloorProperty() {
        return this.codeFloor;
    }

    public String getCodeFloor() {
        return codeFloorProperty().get();
    }

    public void setCodeFloor(String codeFloor) {
        codeFloorProperty().set(codeFloor);
    }

    public final StringProperty floorNameProperty() {
        return this.floorName;
    }

    public String getFloorName() {
        return floorNameProperty().get();
    }

    public void setFloorName(String floorName) {
        floorNameProperty().set(floorName);
    }

    public final StringProperty floorNoteProperty() {
        return this.floorNote;
    }

    public String getFloorNote() {
        return floorNoteProperty().get();
    }

    public void setFloorNote(String floorNote) {
        floorNoteProperty().set(floorNote);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

    public Set getTblLocations() {
        return this.tblLocations;
    }

    public void setTblLocations(Set tblLocations) {
        this.tblLocations = tblLocations;
    }

    @Override
    public String toString() {
        return floorNameProperty().get();
    }

}
