package hotelfx.persistence.model;
// Generated Mar 8, 2018 2:53:13 PM by Hibernate Tools 4.3.1

import java.util.Date;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblFinanceTransaction generated by hbm2java
 */
public class TblFinanceTransaction implements java.io.Serializable {

    private final LongProperty idtransaction;
    private final ObjectProperty<RefFinanceTransactionType> refFinanceTransactionType;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByIdemployee;
    private final ObjectProperty<TblFinanceData> tblFinanceData;
    private final StringProperty codeTransaction;
    private final StringProperty transactionName;
    private final LongProperty transactionNominal;
    private final ObjectProperty<Date> transactionDate;
    private final ObjectProperty<Date> dueDate;
    private final StringProperty transactionNote;
    private final ObjectProperty<Date> settleDate;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    public TblFinanceTransaction() {
        this.idtransaction = new SimpleLongProperty();
        this.refFinanceTransactionType = new SimpleObjectProperty<>();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByIdemployee = new SimpleObjectProperty<>();
        this.tblFinanceData = new SimpleObjectProperty<>();
        this.codeTransaction = new SimpleStringProperty();
        this.transactionName = new SimpleStringProperty();
        this.transactionNominal = new SimpleLongProperty();
        this.transactionDate = new SimpleObjectProperty<>();
        this.dueDate = new SimpleObjectProperty<>();
        this.transactionNote = new SimpleStringProperty();
        this.settleDate = new SimpleObjectProperty<>();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

    }

    public TblFinanceTransaction(long idtransaction) {
        this();
        idtransactionProperty().set(idtransaction);
    }

    public TblFinanceTransaction(long idtransaction, RefFinanceTransactionType refFinanceTransactionType, RefRecordStatus refRecordStatus, TblEmployee tblEmployeeByCreateBy, TblEmployee tblEmployeeByLastUpdateBy, TblEmployee tblEmployeeByIdemployee, TblFinanceData tblFinanceData, String codeTransaction, String transactionName, Long transactionNominal, Date transactionDate, Date dueDate, String transactionNote, Date settleDate, Date createDate, Date lastUpdateDate) {
        this();
        idtransactionProperty().set(idtransaction);
        refFinanceTransactionTypeProperty().set(refFinanceTransactionType);
        refRecordStatusProperty().set(refRecordStatus);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblEmployeeByIdemployeeProperty().set(tblEmployeeByIdemployee);
        tblFinanceDataProperty().set(tblFinanceData);
        codeTransactionProperty().set(codeTransaction);
        transactionNameProperty().set(transactionName);
        transactionNominalProperty().set(transactionNominal);
        transactionDateProperty().set(transactionDate);
        dueDateProperty().set(dueDate);
        transactionNoteProperty().set(transactionNote);
        settleDateProperty().set(settleDate);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

    }

    public TblFinanceTransaction(TblFinanceTransaction tblFinanceTransaction) {
        this();
        idtransactionProperty().set(tblFinanceTransaction.getIdtransaction());
        refFinanceTransactionTypeProperty().set(tblFinanceTransaction.getRefFinanceTransactionType());
        refRecordStatusProperty().set(tblFinanceTransaction.getRefRecordStatus());
        tblEmployeeByCreateByProperty().set(tblFinanceTransaction.getTblEmployeeByCreateBy());
        tblEmployeeByLastUpdateByProperty().set(tblFinanceTransaction.getTblEmployeeByLastUpdateBy());
        tblEmployeeByIdemployeeProperty().set(tblFinanceTransaction.getTblEmployeeByIdemployee());
        tblFinanceDataProperty().set(tblFinanceTransaction.getTblFinanceData());
        codeTransactionProperty().set(tblFinanceTransaction.getCodeTransaction());
        transactionNameProperty().set(tblFinanceTransaction.getTransactionName());
        transactionNominalProperty().set(tblFinanceTransaction.getTransactionNominal());
        transactionDateProperty().set(tblFinanceTransaction.getTransactionDate());
        dueDateProperty().set(tblFinanceTransaction.getDueDate());
        transactionNoteProperty().set(tblFinanceTransaction.getTransactionNote());
        settleDateProperty().set(tblFinanceTransaction.getSettleDate());
        createDateProperty().set(tblFinanceTransaction.getCreateDate());
        lastUpdateDateProperty().set(tblFinanceTransaction.getLastUpdateDate());

    }

    public final LongProperty idtransactionProperty() {
        return this.idtransaction;
    }

    public long getIdtransaction() {
        return idtransactionProperty().get();
    }

    public void setIdtransaction(long idtransaction) {
        idtransactionProperty().set(idtransaction);
    }

    public final ObjectProperty<RefFinanceTransactionType> refFinanceTransactionTypeProperty() {
        return this.refFinanceTransactionType;
    }

    public RefFinanceTransactionType getRefFinanceTransactionType() {
        return refFinanceTransactionTypeProperty().get();
    }

    public void setRefFinanceTransactionType(RefFinanceTransactionType refFinanceTransactionType) {
        refFinanceTransactionTypeProperty().set(refFinanceTransactionType);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByIdemployeeProperty() {
        return this.tblEmployeeByIdemployee;
    }

    public TblEmployee getTblEmployeeByIdemployee() {
        return tblEmployeeByIdemployeeProperty().get();
    }

    public void setTblEmployeeByIdemployee(TblEmployee tblEmployeeByIdemployee) {
        tblEmployeeByIdemployeeProperty().set(tblEmployeeByIdemployee);
    }

    public final ObjectProperty<TblFinanceData> tblFinanceDataProperty() {
        return this.tblFinanceData;
    }

    public TblFinanceData getTblFinanceData() {
        return tblFinanceDataProperty().get();
    }

    public void setTblFinanceData(TblFinanceData tblFinanceData) {
        tblFinanceDataProperty().set(tblFinanceData);
    }

    public final StringProperty codeTransactionProperty() {
        return this.codeTransaction;
    }

    public String getCodeTransaction() {
        return codeTransactionProperty().get();
    }

    public void setCodeTransaction(String codeTransaction) {
        codeTransactionProperty().set(codeTransaction);
    }

    public final StringProperty transactionNameProperty() {
        return this.transactionName;
    }

    public String getTransactionName() {
        return transactionNameProperty().get();
    }

    public void setTransactionName(String transactionName) {
        transactionNameProperty().set(transactionName);
    }

    public final LongProperty transactionNominalProperty() {
        return this.transactionNominal;
    }

    public Long getTransactionNominal() {
        return transactionNominalProperty().get();
    }

    public void setTransactionNominal(Long transactionNominal) {
        transactionNominalProperty().set(transactionNominal);
    }

    public final ObjectProperty<Date> transactionDateProperty() {
        return this.transactionDate;
    }

    public Date getTransactionDate() {
        return transactionDateProperty().get();
    }

    public void setTransactionDate(Date transactionDate) {
        transactionDateProperty().set(transactionDate);
    }

    public final ObjectProperty<Date> dueDateProperty() {
        return this.dueDate;
    }

    public Date getDueDate() {
        return dueDateProperty().get();
    }

    public void setDueDate(Date dueDate) {
        dueDateProperty().set(dueDate);
    }

    public final StringProperty transactionNoteProperty() {
        return this.transactionNote;
    }

    public String getTransactionNote() {
        return transactionNoteProperty().get();
    }

    public void setTransactionNote(String transactionNote) {
        transactionNoteProperty().set(transactionNote);
    }

    public final ObjectProperty<Date> settleDateProperty() {
        return this.settleDate;
    }

    public Date getSettleDate() {
        return settleDateProperty().get();
    }

    public void setSettleDate(Date settleDate) {
        settleDateProperty().set(settleDate);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

}
