package hotelfx.persistence.model;
// Generated Aug 30, 2018 10:38:05 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblGroup generated by hbm2java
 */
public class TblGroup implements java.io.Serializable {

    private final LongProperty idgroup;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final StringProperty codeGroup;
    private final StringProperty groupName;
    private final StringProperty groupNote;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    private Set tblEmployees;
    private Set tblLocations;

    public TblGroup() {
        this.idgroup = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.codeGroup = new SimpleStringProperty();
        this.groupName = new SimpleStringProperty();
        this.groupNote = new SimpleStringProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

        this.tblEmployees = new HashSet(0);
        this.tblLocations = new HashSet(0);
    }

    public TblGroup(long idgroup) {
        this();
        idgroupProperty().set(idgroup);
    }

    public TblGroup(long idgroup, RefRecordStatus refRecordStatus, TblEmployee tblEmployeeByLastUpdateBy, TblEmployee tblEmployeeByCreateBy, String codeGroup, String groupName, String groupNote, Date createDate, Date lastUpdateDate, Set tblEmployees, Set tblLocations) {
        this();
        idgroupProperty().set(idgroup);
        refRecordStatusProperty().set(refRecordStatus);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        codeGroupProperty().set(codeGroup);
        groupNameProperty().set(groupName);
        groupNoteProperty().set(groupNote);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

        this.tblEmployees = tblEmployees;
        this.tblLocations = tblLocations;
    }

    public TblGroup(TblGroup tblGroup) {
        this();
        idgroupProperty().set(tblGroup.getIdgroup());
        refRecordStatusProperty().set(tblGroup.getRefRecordStatus());
        tblEmployeeByLastUpdateByProperty().set(tblGroup.getTblEmployeeByLastUpdateBy());
        tblEmployeeByCreateByProperty().set(tblGroup.getTblEmployeeByCreateBy());
        codeGroupProperty().set(tblGroup.getCodeGroup());
        groupNameProperty().set(tblGroup.getGroupName());
        groupNoteProperty().set(tblGroup.getGroupNote());
        createDateProperty().set(tblGroup.getCreateDate());
        lastUpdateDateProperty().set(tblGroup.getLastUpdateDate());

        this.tblEmployees = tblGroup.getTblEmployees();
        this.tblLocations = tblGroup.getTblLocations();
    }

    public final LongProperty idgroupProperty() {
        return this.idgroup;
    }

    public long getIdgroup() {
        return idgroupProperty().get();
    }

    public void setIdgroup(long idgroup) {
        idgroupProperty().set(idgroup);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final StringProperty codeGroupProperty() {
        return this.codeGroup;
    }

    public String getCodeGroup() {
        return codeGroupProperty().get();
    }

    public void setCodeGroup(String codeGroup) {
        codeGroupProperty().set(codeGroup);
    }

    public final StringProperty groupNameProperty() {
        return this.groupName;
    }

    public String getGroupName() {
        return groupNameProperty().get();
    }

    public void setGroupName(String groupName) {
        groupNameProperty().set(groupName);
    }

    public final StringProperty groupNoteProperty() {
        return this.groupNote;
    }

    public String getGroupNote() {
        return groupNoteProperty().get();
    }

    public void setGroupNote(String groupNote) {
        groupNoteProperty().set(groupNote);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

    public Set getTblEmployees() {
        return this.tblEmployees;
    }

    public void setTblEmployees(Set tblEmployees) {
        this.tblEmployees = tblEmployees;
    }

    public Set getTblLocations() {
        return this.tblLocations;
    }

    public void setTblLocations(Set tblLocations) {
        this.tblLocations = tblLocations;
    }

    @Override
    public String toString() {
        return getGroupName();
    }
    
}
