package hotelfx.persistence.model;
// Generated Apr 19, 2018 12:58:20 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblGuaranteeLetterItemDetail generated by hbm2java
 */
public class TblGuaranteeLetterItemDetail implements java.io.Serializable {

    private final LongProperty iddetail;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblReservationPaymentWithGuaranteePayment> tblReservationPaymentWithGuaranteePayment;
    private final StringProperty codeRtd;
    private final StringProperty detailName;
    private final StringProperty roomName;
    private final ObjectProperty<Date> detailDate;
    private final ObjectProperty<BigDecimal> detailCost;
    private final ObjectProperty<BigDecimal> detailQuantity;
    private final ObjectProperty<BigDecimal> totalDiscountNominal;
    private final ObjectProperty<BigDecimal> serviceChargePercentage;
    private final ObjectProperty<BigDecimal> taxPercentage;
    private final StringProperty detailType;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    public TblGuaranteeLetterItemDetail() {
        this.iddetail = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblReservationPaymentWithGuaranteePayment = new SimpleObjectProperty<>();
        this.codeRtd = new SimpleStringProperty();
        this.detailName = new SimpleStringProperty();
        this.roomName = new SimpleStringProperty();
        this.detailDate = new SimpleObjectProperty<>();
        this.detailCost = new SimpleObjectProperty<>();
        this.detailQuantity = new SimpleObjectProperty<>();
        this.totalDiscountNominal = new SimpleObjectProperty<>();
        this.serviceChargePercentage = new SimpleObjectProperty<>();
        this.taxPercentage = new SimpleObjectProperty<>();
        this.detailType = new SimpleStringProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

    }

    public TblGuaranteeLetterItemDetail(long iddetail) {
        this();
        iddetailProperty().set(iddetail);
    }

    public TblGuaranteeLetterItemDetail(long iddetail, RefRecordStatus refRecordStatus, TblEmployee tblEmployeeByCreateBy, TblEmployee tblEmployeeByLastUpdateBy, TblReservationPaymentWithGuaranteePayment tblReservationPaymentWithGuaranteePayment, String codeRtd, String detailName, String roomName, Date detailDate, BigDecimal detailCost, BigDecimal detailQuantity, BigDecimal totalDiscountNominal, BigDecimal serviceChargePercentage, BigDecimal taxPercentage, String detailType, Date createDate, Date lastUpdateDate) {
        this();
        iddetailProperty().set(iddetail);
        refRecordStatusProperty().set(refRecordStatus);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblReservationPaymentWithGuaranteePaymentProperty().set(tblReservationPaymentWithGuaranteePayment);
        codeRtdProperty().set(codeRtd);
        detailNameProperty().set(detailName);
        roomNameProperty().set(roomName);
        detailDateProperty().set(detailDate);
        detailCostProperty().set(detailCost);
        detailQuantityProperty().set(detailQuantity);
        totalDiscountNominalProperty().set(totalDiscountNominal);
        serviceChargePercentageProperty().set(serviceChargePercentage);
        taxPercentageProperty().set(taxPercentage);
        detailTypeProperty().set(detailType);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

    }

    public TblGuaranteeLetterItemDetail(TblGuaranteeLetterItemDetail tblGuaranteeLetterItemDetail) {
        this();
        iddetailProperty().set(tblGuaranteeLetterItemDetail.getIddetail());
        refRecordStatusProperty().set(tblGuaranteeLetterItemDetail.getRefRecordStatus());
        tblEmployeeByCreateByProperty().set(tblGuaranteeLetterItemDetail.getTblEmployeeByCreateBy());
        tblEmployeeByLastUpdateByProperty().set(tblGuaranteeLetterItemDetail.getTblEmployeeByLastUpdateBy());
        tblReservationPaymentWithGuaranteePaymentProperty().set(tblGuaranteeLetterItemDetail.getTblReservationPaymentWithGuaranteePayment());
        codeRtdProperty().set(tblGuaranteeLetterItemDetail.getCodeRtd());
        detailNameProperty().set(tblGuaranteeLetterItemDetail.getDetailName());
        roomNameProperty().set(tblGuaranteeLetterItemDetail.getRoomName());
        detailDateProperty().set(tblGuaranteeLetterItemDetail.getDetailDate());
        detailCostProperty().set(tblGuaranteeLetterItemDetail.getDetailCost());
        detailQuantityProperty().set(tblGuaranteeLetterItemDetail.getDetailQuantity());
        totalDiscountNominalProperty().set(tblGuaranteeLetterItemDetail.getTotalDiscountNominal());
        serviceChargePercentageProperty().set(tblGuaranteeLetterItemDetail.getServiceChargePercentage());
        taxPercentageProperty().set(tblGuaranteeLetterItemDetail.getTaxPercentage());
        detailTypeProperty().set(tblGuaranteeLetterItemDetail.getDetailType());
        createDateProperty().set(tblGuaranteeLetterItemDetail.getCreateDate());
        lastUpdateDateProperty().set(tblGuaranteeLetterItemDetail.getLastUpdateDate());

    }

    public final LongProperty iddetailProperty() {
        return this.iddetail;
    }

    public long getIddetail() {
        return iddetailProperty().get();
    }

    public void setIddetail(long iddetail) {
        iddetailProperty().set(iddetail);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblReservationPaymentWithGuaranteePayment> tblReservationPaymentWithGuaranteePaymentProperty() {
        return this.tblReservationPaymentWithGuaranteePayment;
    }

    public TblReservationPaymentWithGuaranteePayment getTblReservationPaymentWithGuaranteePayment() {
        return tblReservationPaymentWithGuaranteePaymentProperty().get();
    }

    public void setTblReservationPaymentWithGuaranteePayment(TblReservationPaymentWithGuaranteePayment tblReservationPaymentWithGuaranteePayment) {
        tblReservationPaymentWithGuaranteePaymentProperty().set(tblReservationPaymentWithGuaranteePayment);
    }

    public final StringProperty codeRtdProperty() {
        return this.codeRtd;
    }

    public String getCodeRtd() {
        return codeRtdProperty().get();
    }

    public void setCodeRtd(String codeRtd) {
        codeRtdProperty().set(codeRtd);
    }

    public final StringProperty detailNameProperty() {
        return this.detailName;
    }

    public String getDetailName() {
        return detailNameProperty().get();
    }

    public void setDetailName(String detailName) {
        detailNameProperty().set(detailName);
    }

    public final StringProperty roomNameProperty() {
        return this.roomName;
    }

    public String getRoomName() {
        return roomNameProperty().get();
    }

    public void setRoomName(String roomName) {
        roomNameProperty().set(roomName);
    }

    public final ObjectProperty<Date> detailDateProperty() {
        return this.detailDate;
    }

    public Date getDetailDate() {
        return detailDateProperty().get();
    }

    public void setDetailDate(Date detailDate) {
        detailDateProperty().set(detailDate);
    }

    public final ObjectProperty<BigDecimal> detailCostProperty() {
        return this.detailCost;
    }

    public BigDecimal getDetailCost() {
        return detailCostProperty().get();
    }

    public void setDetailCost(BigDecimal detailCost) {
        detailCostProperty().set(detailCost);
    }

    public final ObjectProperty<BigDecimal> detailQuantityProperty() {
        return this.detailQuantity;
    }

    public BigDecimal getDetailQuantity() {
        return detailQuantityProperty().get();
    }

    public void setDetailQuantity(BigDecimal detailQuantity) {
        detailQuantityProperty().set(detailQuantity);
    }

    public final ObjectProperty<BigDecimal> totalDiscountNominalProperty() {
        return this.totalDiscountNominal;
    }

    public BigDecimal getTotalDiscountNominal() {
        return totalDiscountNominalProperty().get();
    }

    public void setTotalDiscountNominal(BigDecimal totalDiscountNominal) {
        totalDiscountNominalProperty().set(totalDiscountNominal);
    }

    public final ObjectProperty<BigDecimal> serviceChargePercentageProperty() {
        return this.serviceChargePercentage;
    }

    public BigDecimal getServiceChargePercentage() {
        return serviceChargePercentageProperty().get();
    }

    public void setServiceChargePercentage(BigDecimal serviceChargePercentage) {
        serviceChargePercentageProperty().set(serviceChargePercentage);
    }

    public final ObjectProperty<BigDecimal> taxPercentageProperty() {
        return this.taxPercentage;
    }

    public BigDecimal getTaxPercentage() {
        return taxPercentageProperty().get();
    }

    public void setTaxPercentage(BigDecimal taxPercentage) {
        taxPercentageProperty().set(taxPercentage);
    }

    public final StringProperty detailTypeProperty() {
        return this.detailType;
    }

    public String getDetailType() {
        return detailTypeProperty().get();
    }

    public void setDetailType(String detailType) {
        detailTypeProperty().set(detailType);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

}
