package hotelfx.persistence.model;
// Generated Aug 21, 2018 3:34:00 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javafx.beans.property.BooleanProperty;
import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleBooleanProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblHotelFinanceTransaction generated by hbm2java
 */
public class TblHotelFinanceTransaction implements java.io.Serializable {

    private final LongProperty idtransaction;
    private final ObjectProperty<RefFinanceTransactionPaymentType> refFinanceTransactionPaymentType;
    private final ObjectProperty<RefFinanceTransactionType> refFinanceTransactionType;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final StringProperty codeTransaction;
    private final ObjectProperty<BigDecimal> transactionNominal;
    private final ObjectProperty<BigDecimal> transactionRoundingValue;
    private final BooleanProperty isReturnTransaction;
    private final StringProperty transactionNote;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    private Set tblHotelFinanceTransactionHotelReceivables;
    private Set tblHotelFinanceTransactionWithCekGiros;
    private Set tblHotelFinanceTransactionHotelPayables;
    private Set tblHotelFinanceTransactionWithCashes;
    private Set tblHotelFinanceTransactionWithTransfers;

    public TblHotelFinanceTransaction() {
        this.idtransaction = new SimpleLongProperty();
        this.refFinanceTransactionPaymentType = new SimpleObjectProperty<>();
        this.refFinanceTransactionType = new SimpleObjectProperty<>();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.codeTransaction = new SimpleStringProperty();
        this.transactionNominal = new SimpleObjectProperty<>();
        this.transactionRoundingValue = new SimpleObjectProperty<>();
        this.isReturnTransaction = new SimpleBooleanProperty();
        this.transactionNote = new SimpleStringProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

        this.tblHotelFinanceTransactionHotelReceivables = new HashSet(0);
        this.tblHotelFinanceTransactionWithCekGiros = new HashSet(0);
        this.tblHotelFinanceTransactionHotelPayables = new HashSet(0);
        this.tblHotelFinanceTransactionWithCashes = new HashSet(0);
        this.tblHotelFinanceTransactionWithTransfers = new HashSet(0);
    }

    public TblHotelFinanceTransaction(long idtransaction) {
        this();
        idtransactionProperty().set(idtransaction);
    }

    public TblHotelFinanceTransaction(long idtransaction, RefFinanceTransactionPaymentType refFinanceTransactionPaymentType, RefFinanceTransactionType refFinanceTransactionType, RefRecordStatus refRecordStatus, TblEmployee tblEmployeeByLastUpdateBy, TblEmployee tblEmployeeByCreateBy, String codeTransaction, BigDecimal transactionNominal, BigDecimal transactionRoundingValue, Boolean isReturnTransaction, String transactionNote, Date createDate, Date lastUpdateDate, Set tblHotelFinanceTransactionHotelReceivables, Set tblHotelFinanceTransactionWithCekGiros, Set tblHotelFinanceTransactionHotelPayables, Set tblHotelFinanceTransactionWithCashes, Set tblHotelFinanceTransactionWithTransfers) {
        this();
        idtransactionProperty().set(idtransaction);
        refFinanceTransactionPaymentTypeProperty().set(refFinanceTransactionPaymentType);
        refFinanceTransactionTypeProperty().set(refFinanceTransactionType);
        refRecordStatusProperty().set(refRecordStatus);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        codeTransactionProperty().set(codeTransaction);
        transactionNominalProperty().set(transactionNominal);
        transactionRoundingValueProperty().set(transactionRoundingValue);
        isReturnTransactionProperty().set(isReturnTransaction);
        transactionNoteProperty().set(transactionNote);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

        this.tblHotelFinanceTransactionHotelReceivables = tblHotelFinanceTransactionHotelReceivables;
        this.tblHotelFinanceTransactionWithCekGiros = tblHotelFinanceTransactionWithCekGiros;
        this.tblHotelFinanceTransactionHotelPayables = tblHotelFinanceTransactionHotelPayables;
        this.tblHotelFinanceTransactionWithCashes = tblHotelFinanceTransactionWithCashes;
        this.tblHotelFinanceTransactionWithTransfers = tblHotelFinanceTransactionWithTransfers;
    }

    public TblHotelFinanceTransaction(TblHotelFinanceTransaction tblHotelFinanceTransaction) {
        this();
        idtransactionProperty().set(tblHotelFinanceTransaction.getIdtransaction());
        refFinanceTransactionPaymentTypeProperty().set(tblHotelFinanceTransaction.getRefFinanceTransactionPaymentType());
        refFinanceTransactionTypeProperty().set(tblHotelFinanceTransaction.getRefFinanceTransactionType());
        refRecordStatusProperty().set(tblHotelFinanceTransaction.getRefRecordStatus());
        tblEmployeeByLastUpdateByProperty().set(tblHotelFinanceTransaction.getTblEmployeeByLastUpdateBy());
        tblEmployeeByCreateByProperty().set(tblHotelFinanceTransaction.getTblEmployeeByCreateBy());
        codeTransactionProperty().set(tblHotelFinanceTransaction.getCodeTransaction());
        transactionNominalProperty().set(tblHotelFinanceTransaction.getTransactionNominal());
        transactionRoundingValueProperty().set(tblHotelFinanceTransaction.getTransactionRoundingValue());
        isReturnTransactionProperty().set(tblHotelFinanceTransaction.getIsReturnTransaction());
        transactionNoteProperty().set(tblHotelFinanceTransaction.getTransactionNote());
        createDateProperty().set(tblHotelFinanceTransaction.getCreateDate());
        lastUpdateDateProperty().set(tblHotelFinanceTransaction.getLastUpdateDate());

        this.tblHotelFinanceTransactionHotelReceivables = tblHotelFinanceTransaction.getTblHotelFinanceTransactionHotelReceivables();
        this.tblHotelFinanceTransactionWithCekGiros = tblHotelFinanceTransaction.getTblHotelFinanceTransactionWithCekGiros();
        this.tblHotelFinanceTransactionHotelPayables = tblHotelFinanceTransaction.getTblHotelFinanceTransactionHotelPayables();
        this.tblHotelFinanceTransactionWithCashes = tblHotelFinanceTransaction.getTblHotelFinanceTransactionWithCashes();
        this.tblHotelFinanceTransactionWithTransfers = tblHotelFinanceTransaction.getTblHotelFinanceTransactionWithTransfers();
    }

    public final LongProperty idtransactionProperty() {
        return this.idtransaction;
    }

    public long getIdtransaction() {
        return idtransactionProperty().get();
    }

    public void setIdtransaction(long idtransaction) {
        idtransactionProperty().set(idtransaction);
    }

    public final ObjectProperty<RefFinanceTransactionPaymentType> refFinanceTransactionPaymentTypeProperty() {
        return this.refFinanceTransactionPaymentType;
    }

    public RefFinanceTransactionPaymentType getRefFinanceTransactionPaymentType() {
        return refFinanceTransactionPaymentTypeProperty().get();
    }

    public void setRefFinanceTransactionPaymentType(RefFinanceTransactionPaymentType refFinanceTransactionPaymentType) {
        refFinanceTransactionPaymentTypeProperty().set(refFinanceTransactionPaymentType);
    }

    public final ObjectProperty<RefFinanceTransactionType> refFinanceTransactionTypeProperty() {
        return this.refFinanceTransactionType;
    }

    public RefFinanceTransactionType getRefFinanceTransactionType() {
        return refFinanceTransactionTypeProperty().get();
    }

    public void setRefFinanceTransactionType(RefFinanceTransactionType refFinanceTransactionType) {
        refFinanceTransactionTypeProperty().set(refFinanceTransactionType);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final StringProperty codeTransactionProperty() {
        return this.codeTransaction;
    }

    public String getCodeTransaction() {
        return codeTransactionProperty().get();
    }

    public void setCodeTransaction(String codeTransaction) {
        codeTransactionProperty().set(codeTransaction);
    }

    public final ObjectProperty<BigDecimal> transactionNominalProperty() {
        return this.transactionNominal;
    }

    public BigDecimal getTransactionNominal() {
        return transactionNominalProperty().get();
    }

    public void setTransactionNominal(BigDecimal transactionNominal) {
        transactionNominalProperty().set(transactionNominal);
    }

    public final ObjectProperty<BigDecimal> transactionRoundingValueProperty() {
        return this.transactionRoundingValue;
    }

    public BigDecimal getTransactionRoundingValue() {
        return transactionRoundingValueProperty().get();
    }

    public void setTransactionRoundingValue(BigDecimal transactionRoundingValue) {
        transactionRoundingValueProperty().set(transactionRoundingValue);
    }

    public final BooleanProperty isReturnTransactionProperty() {
        return this.isReturnTransaction;
    }

    public Boolean getIsReturnTransaction() {
        return isReturnTransactionProperty().get();
    }

    public void setIsReturnTransaction(Boolean isReturnTransaction) {
        isReturnTransactionProperty().set(isReturnTransaction);
    }

    public final StringProperty transactionNoteProperty() {
        return this.transactionNote;
    }

    public String getTransactionNote() {
        return transactionNoteProperty().get();
    }

    public void setTransactionNote(String transactionNote) {
        transactionNoteProperty().set(transactionNote);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

    public Set getTblHotelFinanceTransactionHotelReceivables() {
        return this.tblHotelFinanceTransactionHotelReceivables;
    }

    public void setTblHotelFinanceTransactionHotelReceivables(Set tblHotelFinanceTransactionHotelReceivables) {
        this.tblHotelFinanceTransactionHotelReceivables = tblHotelFinanceTransactionHotelReceivables;
    }

    public Set getTblHotelFinanceTransactionWithCekGiros() {
        return this.tblHotelFinanceTransactionWithCekGiros;
    }

    public void setTblHotelFinanceTransactionWithCekGiros(Set tblHotelFinanceTransactionWithCekGiros) {
        this.tblHotelFinanceTransactionWithCekGiros = tblHotelFinanceTransactionWithCekGiros;
    }

    public Set getTblHotelFinanceTransactionHotelPayables() {
        return this.tblHotelFinanceTransactionHotelPayables;
    }

    public void setTblHotelFinanceTransactionHotelPayables(Set tblHotelFinanceTransactionHotelPayables) {
        this.tblHotelFinanceTransactionHotelPayables = tblHotelFinanceTransactionHotelPayables;
    }

    public Set getTblHotelFinanceTransactionWithCashes() {
        return this.tblHotelFinanceTransactionWithCashes;
    }

    public void setTblHotelFinanceTransactionWithCashes(Set tblHotelFinanceTransactionWithCashes) {
        this.tblHotelFinanceTransactionWithCashes = tblHotelFinanceTransactionWithCashes;
    }

    public Set getTblHotelFinanceTransactionWithTransfers() {
        return this.tblHotelFinanceTransactionWithTransfers;
    }

    public void setTblHotelFinanceTransactionWithTransfers(Set tblHotelFinanceTransactionWithTransfers) {
        this.tblHotelFinanceTransactionWithTransfers = tblHotelFinanceTransactionWithTransfers;
    }

}
