package hotelfx.persistence.model;
// Generated Jul 9, 2018 4:37:20 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;

/**
 * TblHotelFinanceTransactionHotelPayable generated by hbm2java
 */
public class TblHotelFinanceTransactionHotelPayable implements java.io.Serializable {

    private final LongProperty idrelation;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblHotelFinanceTransaction> tblHotelFinanceTransaction;
    private final ObjectProperty<TblHotelPayable> tblHotelPayable;
    private final ObjectProperty<BigDecimal> nominalTransaction;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    public TblHotelFinanceTransactionHotelPayable() {
        this.idrelation = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblHotelFinanceTransaction = new SimpleObjectProperty<>();
        this.tblHotelPayable = new SimpleObjectProperty<>();
        this.nominalTransaction = new SimpleObjectProperty<>();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

    }

    public TblHotelFinanceTransactionHotelPayable(long idrelation) {
        this();
        idrelationProperty().set(idrelation);
    }

    public TblHotelFinanceTransactionHotelPayable(long idrelation, RefRecordStatus refRecordStatus, TblEmployee tblEmployeeByCreateBy, TblEmployee tblEmployeeByLastUpdateBy, TblHotelFinanceTransaction tblHotelFinanceTransaction, TblHotelPayable tblHotelPayable, BigDecimal nominalTransaction, Date createDate, Date lastUpdateDate) {
        this();
        idrelationProperty().set(idrelation);
        refRecordStatusProperty().set(refRecordStatus);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblHotelFinanceTransactionProperty().set(tblHotelFinanceTransaction);
        tblHotelPayableProperty().set(tblHotelPayable);
        nominalTransactionProperty().set(nominalTransaction);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

    }

    public TblHotelFinanceTransactionHotelPayable(TblHotelFinanceTransactionHotelPayable tblHotelFinanceTransactionHotelPayable) {
        this();
        idrelationProperty().set(tblHotelFinanceTransactionHotelPayable.getIdrelation());
        refRecordStatusProperty().set(tblHotelFinanceTransactionHotelPayable.getRefRecordStatus());
        tblEmployeeByCreateByProperty().set(tblHotelFinanceTransactionHotelPayable.getTblEmployeeByCreateBy());
        tblEmployeeByLastUpdateByProperty().set(tblHotelFinanceTransactionHotelPayable.getTblEmployeeByLastUpdateBy());
        tblHotelFinanceTransactionProperty().set(tblHotelFinanceTransactionHotelPayable.getTblHotelFinanceTransaction());
        tblHotelPayableProperty().set(tblHotelFinanceTransactionHotelPayable.getTblHotelPayable());
        nominalTransactionProperty().set(tblHotelFinanceTransactionHotelPayable.getNominalTransaction());
        createDateProperty().set(tblHotelFinanceTransactionHotelPayable.getCreateDate());
        lastUpdateDateProperty().set(tblHotelFinanceTransactionHotelPayable.getLastUpdateDate());

    }

    public final LongProperty idrelationProperty() {
        return this.idrelation;
    }

    public long getIdrelation() {
        return idrelationProperty().get();
    }

    public void setIdrelation(long idrelation) {
        idrelationProperty().set(idrelation);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblHotelFinanceTransaction> tblHotelFinanceTransactionProperty() {
        return this.tblHotelFinanceTransaction;
    }

    public TblHotelFinanceTransaction getTblHotelFinanceTransaction() {
        return tblHotelFinanceTransactionProperty().get();
    }

    public void setTblHotelFinanceTransaction(TblHotelFinanceTransaction tblHotelFinanceTransaction) {
        tblHotelFinanceTransactionProperty().set(tblHotelFinanceTransaction);
    }

    public final ObjectProperty<TblHotelPayable> tblHotelPayableProperty() {
        return this.tblHotelPayable;
    }

    public TblHotelPayable getTblHotelPayable() {
        return tblHotelPayableProperty().get();
    }

    public void setTblHotelPayable(TblHotelPayable tblHotelPayable) {
        tblHotelPayableProperty().set(tblHotelPayable);
    }

    public final ObjectProperty<BigDecimal> nominalTransactionProperty() {
        return this.nominalTransaction;
    }

    public BigDecimal getNominalTransaction() {
        return nominalTransactionProperty().get();
    }

    public void setNominalTransaction(BigDecimal nominalTransaction) {
        nominalTransactionProperty().set(nominalTransaction);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

}
