package hotelfx.persistence.model;
// Generated Oct 24, 2018 9:41:20 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblHotelPayable generated by hbm2java
 */
public class TblHotelPayable implements java.io.Serializable {

    private final LongProperty idhotelPayable;
    private final ObjectProperty<RefFinanceTransactionStatus> refFinanceTransactionStatus;
    private final ObjectProperty<RefHotelPayableType> refHotelPayableType;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblHotelInvoice> tblHotelInvoice;
    private final StringProperty codeHotelPayable;
    private final ObjectProperty<BigDecimal> hotelPayableNominal;
    private final StringProperty hotelPayableNote;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    private Set tblPurchaseOrders;
    private Set tblReservationAdditionalServices;
    private Set tblHotelFinanceTransactionHotelPayables;

    public TblHotelPayable() {
        this.idhotelPayable = new SimpleLongProperty();
        this.refFinanceTransactionStatus = new SimpleObjectProperty<>();
        this.refHotelPayableType = new SimpleObjectProperty<>();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblHotelInvoice = new SimpleObjectProperty<>();
        this.codeHotelPayable = new SimpleStringProperty();
        this.hotelPayableNominal = new SimpleObjectProperty<>();
        this.hotelPayableNote = new SimpleStringProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

        this.tblPurchaseOrders = new HashSet(0);
        this.tblReservationAdditionalServices = new HashSet(0);
        this.tblHotelFinanceTransactionHotelPayables = new HashSet(0);
    }

    public TblHotelPayable(long idhotelPayable) {
        this();
        idhotelPayableProperty().set(idhotelPayable);
    }

    public TblHotelPayable(long idhotelPayable, RefFinanceTransactionStatus refFinanceTransactionStatus, RefHotelPayableType refHotelPayableType, RefRecordStatus refRecordStatus, TblEmployee tblEmployeeByLastUpdateBy, TblEmployee tblEmployeeByCreateBy, TblHotelInvoice tblHotelInvoice, String codeHotelPayable, BigDecimal hotelPayableNominal, String hotelPayableNote, Date createDate, Date lastUpdateDate, Set tblPurchaseOrders, Set tblReservationAdditionalServices, Set tblHotelFinanceTransactionHotelPayables) {
        this();
        idhotelPayableProperty().set(idhotelPayable);
        refFinanceTransactionStatusProperty().set(refFinanceTransactionStatus);
        refHotelPayableTypeProperty().set(refHotelPayableType);
        refRecordStatusProperty().set(refRecordStatus);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblHotelInvoiceProperty().set(tblHotelInvoice);
        codeHotelPayableProperty().set(codeHotelPayable);
        hotelPayableNominalProperty().set(hotelPayableNominal);
        hotelPayableNoteProperty().set(hotelPayableNote);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

        this.tblPurchaseOrders = tblPurchaseOrders;
        this.tblReservationAdditionalServices = tblReservationAdditionalServices;
        this.tblHotelFinanceTransactionHotelPayables = tblHotelFinanceTransactionHotelPayables;
    }

    public TblHotelPayable(TblHotelPayable tblHotelPayable) {
        this();
        idhotelPayableProperty().set(tblHotelPayable.getIdhotelPayable());
        refFinanceTransactionStatusProperty().set(tblHotelPayable.getRefFinanceTransactionStatus());
        refHotelPayableTypeProperty().set(tblHotelPayable.getRefHotelPayableType());
        refRecordStatusProperty().set(tblHotelPayable.getRefRecordStatus());
        tblEmployeeByLastUpdateByProperty().set(tblHotelPayable.getTblEmployeeByLastUpdateBy());
        tblEmployeeByCreateByProperty().set(tblHotelPayable.getTblEmployeeByCreateBy());
        tblHotelInvoiceProperty().set(tblHotelPayable.getTblHotelInvoice());
        codeHotelPayableProperty().set(tblHotelPayable.getCodeHotelPayable());
        hotelPayableNominalProperty().set(tblHotelPayable.getHotelPayableNominal());
        hotelPayableNoteProperty().set(tblHotelPayable.getHotelPayableNote());
        createDateProperty().set(tblHotelPayable.getCreateDate());
        lastUpdateDateProperty().set(tblHotelPayable.getLastUpdateDate());

        this.tblPurchaseOrders = tblHotelPayable.getTblPurchaseOrders();
        this.tblReservationAdditionalServices = tblHotelPayable.getTblReservationAdditionalServices();
        this.tblHotelFinanceTransactionHotelPayables = tblHotelPayable.getTblHotelFinanceTransactionHotelPayables();
    }

    public final LongProperty idhotelPayableProperty() {
        return this.idhotelPayable;
    }

    public long getIdhotelPayable() {
        return idhotelPayableProperty().get();
    }

    public void setIdhotelPayable(long idhotelPayable) {
        idhotelPayableProperty().set(idhotelPayable);
    }

    public final ObjectProperty<RefFinanceTransactionStatus> refFinanceTransactionStatusProperty() {
        return this.refFinanceTransactionStatus;
    }

    public RefFinanceTransactionStatus getRefFinanceTransactionStatus() {
        return refFinanceTransactionStatusProperty().get();
    }

    public void setRefFinanceTransactionStatus(RefFinanceTransactionStatus refFinanceTransactionStatus) {
        refFinanceTransactionStatusProperty().set(refFinanceTransactionStatus);
    }

    public final ObjectProperty<RefHotelPayableType> refHotelPayableTypeProperty() {
        return this.refHotelPayableType;
    }

    public RefHotelPayableType getRefHotelPayableType() {
        return refHotelPayableTypeProperty().get();
    }

    public void setRefHotelPayableType(RefHotelPayableType refHotelPayableType) {
        refHotelPayableTypeProperty().set(refHotelPayableType);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblHotelInvoice> tblHotelInvoiceProperty() {
        return this.tblHotelInvoice;
    }

    public TblHotelInvoice getTblHotelInvoice() {
        return tblHotelInvoiceProperty().get();
    }

    public void setTblHotelInvoice(TblHotelInvoice tblHotelInvoice) {
        tblHotelInvoiceProperty().set(tblHotelInvoice);
    }

    public final StringProperty codeHotelPayableProperty() {
        return this.codeHotelPayable;
    }

    public String getCodeHotelPayable() {
        return codeHotelPayableProperty().get();
    }

    public void setCodeHotelPayable(String codeHotelPayable) {
        codeHotelPayableProperty().set(codeHotelPayable);
    }

    public final ObjectProperty<BigDecimal> hotelPayableNominalProperty() {
        return this.hotelPayableNominal;
    }

    public BigDecimal getHotelPayableNominal() {
        return hotelPayableNominalProperty().get();
    }

    public void setHotelPayableNominal(BigDecimal hotelPayableNominal) {
        hotelPayableNominalProperty().set(hotelPayableNominal);
    }

    public final StringProperty hotelPayableNoteProperty() {
        return this.hotelPayableNote;
    }

    public String getHotelPayableNote() {
        return hotelPayableNoteProperty().get();
    }

    public void setHotelPayableNote(String hotelPayableNote) {
        hotelPayableNoteProperty().set(hotelPayableNote);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

    public Set getTblPurchaseOrders() {
        return this.tblPurchaseOrders;
    }

    public void setTblPurchaseOrders(Set tblPurchaseOrders) {
        this.tblPurchaseOrders = tblPurchaseOrders;
    }

    public Set getTblReservationAdditionalServices() {
        return this.tblReservationAdditionalServices;
    }

    public void setTblReservationAdditionalServices(Set tblReservationAdditionalServices) {
        this.tblReservationAdditionalServices = tblReservationAdditionalServices;
    }

    public Set getTblHotelFinanceTransactionHotelPayables() {
        return this.tblHotelFinanceTransactionHotelPayables;
    }

    public void setTblHotelFinanceTransactionHotelPayables(Set tblHotelFinanceTransactionHotelPayables) {
        this.tblHotelFinanceTransactionHotelPayables = tblHotelFinanceTransactionHotelPayables;
    }

}
