package hotelfx.persistence.model;
// Generated Nov 12, 2018 3:38:24 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblHotelExpenseTransaction generated by hbm2java
 */
public class TblHotelExpenseTransaction implements java.io.Serializable {

    private final LongProperty idexpenseTransaction;
    private final ObjectProperty<RefFinanceTransactionPaymentType> refFinanceTransactionPaymentType;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblBankAccount> tblBankAccountByIdbankAccountReceiver;
    private final ObjectProperty<TblBankAccount> tblBankAccountByIdbankAccount;
    private final ObjectProperty<TblCompanyBalance> tblCompanyBalance;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final StringProperty codeExpenseTransaction;
    private final StringProperty expenseTransactionName;
    private final ObjectProperty<Date> expenseTransactionDate;
    private final StringProperty expenseTransactionNote;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    private Set tblHotelExpenseTransactionDetails;
    private Set tblOpenCloseCashierBalanceDetails;

    public TblHotelExpenseTransaction() {
        this.idexpenseTransaction = new SimpleLongProperty();
        this.refFinanceTransactionPaymentType = new SimpleObjectProperty<>();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblBankAccountByIdbankAccountReceiver = new SimpleObjectProperty<>();
        this.tblBankAccountByIdbankAccount = new SimpleObjectProperty<>();
        this.tblCompanyBalance = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.codeExpenseTransaction = new SimpleStringProperty();
        this.expenseTransactionName = new SimpleStringProperty();
        this.expenseTransactionDate = new SimpleObjectProperty<>();
        this.expenseTransactionNote = new SimpleStringProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

        this.tblHotelExpenseTransactionDetails = new HashSet(0);
        this.tblOpenCloseCashierBalanceDetails = new HashSet(0);
    }

    public TblHotelExpenseTransaction(long idexpenseTransaction) {
        this();
        idexpenseTransactionProperty().set(idexpenseTransaction);
    }

    public TblHotelExpenseTransaction(long idexpenseTransaction, RefFinanceTransactionPaymentType refFinanceTransactionPaymentType, RefRecordStatus refRecordStatus, TblBankAccount tblBankAccountByIdbankAccountReceiver, TblBankAccount tblBankAccountByIdbankAccount, TblCompanyBalance tblCompanyBalance, TblEmployee tblEmployeeByLastUpdateBy, TblEmployee tblEmployeeByCreateBy, String codeExpenseTransaction, String expenseTransactionName, Date expenseTransactionDate, String expenseTransactionNote, Date createDate, Date lastUpdateDate, Set tblHotelExpenseTransactionDetails, Set tblOpenCloseCashierBalanceDetails) {
        this();
        idexpenseTransactionProperty().set(idexpenseTransaction);
        refFinanceTransactionPaymentTypeProperty().set(refFinanceTransactionPaymentType);
        refRecordStatusProperty().set(refRecordStatus);
        tblBankAccountByIdbankAccountReceiverProperty().set(tblBankAccountByIdbankAccountReceiver);
        tblBankAccountByIdbankAccountProperty().set(tblBankAccountByIdbankAccount);
        tblCompanyBalanceProperty().set(tblCompanyBalance);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        codeExpenseTransactionProperty().set(codeExpenseTransaction);
        expenseTransactionNameProperty().set(expenseTransactionName);
        expenseTransactionDateProperty().set(expenseTransactionDate);
        expenseTransactionNoteProperty().set(expenseTransactionNote);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

        this.tblHotelExpenseTransactionDetails = tblHotelExpenseTransactionDetails;
        this.tblOpenCloseCashierBalanceDetails = tblOpenCloseCashierBalanceDetails;
    }

    public TblHotelExpenseTransaction(TblHotelExpenseTransaction tblHotelExpenseTransaction) {
        this();
        idexpenseTransactionProperty().set(tblHotelExpenseTransaction.getIdexpenseTransaction());
        refFinanceTransactionPaymentTypeProperty().set(tblHotelExpenseTransaction.getRefFinanceTransactionPaymentType());
        refRecordStatusProperty().set(tblHotelExpenseTransaction.getRefRecordStatus());
        tblBankAccountByIdbankAccountReceiverProperty().set(tblHotelExpenseTransaction.getTblBankAccountByIdbankAccountReceiver());
        tblBankAccountByIdbankAccountProperty().set(tblHotelExpenseTransaction.getTblBankAccountByIdbankAccount());
        tblCompanyBalanceProperty().set(tblHotelExpenseTransaction.getTblCompanyBalance());
        tblEmployeeByLastUpdateByProperty().set(tblHotelExpenseTransaction.getTblEmployeeByLastUpdateBy());
        tblEmployeeByCreateByProperty().set(tblHotelExpenseTransaction.getTblEmployeeByCreateBy());
        codeExpenseTransactionProperty().set(tblHotelExpenseTransaction.getCodeExpenseTransaction());
        expenseTransactionNameProperty().set(tblHotelExpenseTransaction.getExpenseTransactionName());
        expenseTransactionDateProperty().set(tblHotelExpenseTransaction.getExpenseTransactionDate());
        expenseTransactionNoteProperty().set(tblHotelExpenseTransaction.getExpenseTransactionNote());
        createDateProperty().set(tblHotelExpenseTransaction.getCreateDate());
        lastUpdateDateProperty().set(tblHotelExpenseTransaction.getLastUpdateDate());

        this.tblHotelExpenseTransactionDetails = tblHotelExpenseTransaction.getTblHotelExpenseTransactionDetails();
        this.tblOpenCloseCashierBalanceDetails = tblHotelExpenseTransaction.getTblOpenCloseCashierBalanceDetails();
    }

    public final LongProperty idexpenseTransactionProperty() {
        return this.idexpenseTransaction;
    }

    public long getIdexpenseTransaction() {
        return idexpenseTransactionProperty().get();
    }

    public void setIdexpenseTransaction(long idexpenseTransaction) {
        idexpenseTransactionProperty().set(idexpenseTransaction);
    }

    public final ObjectProperty<RefFinanceTransactionPaymentType> refFinanceTransactionPaymentTypeProperty() {
        return this.refFinanceTransactionPaymentType;
    }

    public RefFinanceTransactionPaymentType getRefFinanceTransactionPaymentType() {
        return refFinanceTransactionPaymentTypeProperty().get();
    }

    public void setRefFinanceTransactionPaymentType(RefFinanceTransactionPaymentType refFinanceTransactionPaymentType) {
        refFinanceTransactionPaymentTypeProperty().set(refFinanceTransactionPaymentType);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblBankAccount> tblBankAccountByIdbankAccountReceiverProperty() {
        return this.tblBankAccountByIdbankAccountReceiver;
    }

    public TblBankAccount getTblBankAccountByIdbankAccountReceiver() {
        return tblBankAccountByIdbankAccountReceiverProperty().get();
    }

    public void setTblBankAccountByIdbankAccountReceiver(TblBankAccount tblBankAccountByIdbankAccountReceiver) {
        tblBankAccountByIdbankAccountReceiverProperty().set(tblBankAccountByIdbankAccountReceiver);
    }

    public final ObjectProperty<TblBankAccount> tblBankAccountByIdbankAccountProperty() {
        return this.tblBankAccountByIdbankAccount;
    }

    public TblBankAccount getTblBankAccountByIdbankAccount() {
        return tblBankAccountByIdbankAccountProperty().get();
    }

    public void setTblBankAccountByIdbankAccount(TblBankAccount tblBankAccountByIdbankAccount) {
        tblBankAccountByIdbankAccountProperty().set(tblBankAccountByIdbankAccount);
    }

    public final ObjectProperty<TblCompanyBalance> tblCompanyBalanceProperty() {
        return this.tblCompanyBalance;
    }

    public TblCompanyBalance getTblCompanyBalance() {
        return tblCompanyBalanceProperty().get();
    }

    public void setTblCompanyBalance(TblCompanyBalance tblCompanyBalance) {
        tblCompanyBalanceProperty().set(tblCompanyBalance);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final StringProperty codeExpenseTransactionProperty() {
        return this.codeExpenseTransaction;
    }

    public String getCodeExpenseTransaction() {
        return codeExpenseTransactionProperty().get();
    }

    public void setCodeExpenseTransaction(String codeExpenseTransaction) {
        codeExpenseTransactionProperty().set(codeExpenseTransaction);
    }

    public final StringProperty expenseTransactionNameProperty() {
        return this.expenseTransactionName;
    }

    public String getExpenseTransactionName() {
        return expenseTransactionNameProperty().get();
    }

    public void setExpenseTransactionName(String expenseTransactionName) {
        expenseTransactionNameProperty().set(expenseTransactionName);
    }

    public final ObjectProperty<Date> expenseTransactionDateProperty() {
        return this.expenseTransactionDate;
    }

    public Date getExpenseTransactionDate() {
        return expenseTransactionDateProperty().get();
    }

    public void setExpenseTransactionDate(Date expenseTransactionDate) {
        expenseTransactionDateProperty().set(expenseTransactionDate);
    }

    public final StringProperty expenseTransactionNoteProperty() {
        return this.expenseTransactionNote;
    }

    public String getExpenseTransactionNote() {
        return expenseTransactionNoteProperty().get();
    }

    public void setExpenseTransactionNote(String expenseTransactionNote) {
        expenseTransactionNoteProperty().set(expenseTransactionNote);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

    public Set getTblHotelExpenseTransactionDetails() {
        return this.tblHotelExpenseTransactionDetails;
    }

    public void setTblHotelExpenseTransactionDetails(Set tblHotelExpenseTransactionDetails) {
        this.tblHotelExpenseTransactionDetails = tblHotelExpenseTransactionDetails;
    }

    public Set getTblOpenCloseCashierBalanceDetails() {
        return this.tblOpenCloseCashierBalanceDetails;
    }

    public void setTblOpenCloseCashierBalanceDetails(Set tblOpenCloseCashierBalanceDetails) {
        this.tblOpenCloseCashierBalanceDetails = tblOpenCloseCashierBalanceDetails;
    }

}
