package hotelfx.persistence.model;
// Generated Jul 17, 2018 12:56:10 PM by Hibernate Tools 4.3.1

import java.util.Date;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblHotelFinanceTransactionWithCash generated by hbm2java
 */
public class TblHotelFinanceTransactionWithCash implements java.io.Serializable {

    private final LongProperty iddetail;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblCompanyBalance> tblCompanyBalance;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblHotelFinanceTransaction> tblHotelFinanceTransaction;
    private final StringProperty codeCash;
    private final StringProperty cashNote;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    public TblHotelFinanceTransactionWithCash() {
        this.iddetail = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblCompanyBalance = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblHotelFinanceTransaction = new SimpleObjectProperty<>();
        this.codeCash = new SimpleStringProperty();
        this.cashNote = new SimpleStringProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

    }

    public TblHotelFinanceTransactionWithCash(long iddetail) {
        this();
        iddetailProperty().set(iddetail);
    }

    public TblHotelFinanceTransactionWithCash(long iddetail, RefRecordStatus refRecordStatus, TblCompanyBalance tblCompanyBalance, TblEmployee tblEmployeeByLastUpdateBy, TblEmployee tblEmployeeByCreateBy, TblHotelFinanceTransaction tblHotelFinanceTransaction, String codeCash, String cashNote, Date createDate, Date lastUpdateDate) {
        this();
        iddetailProperty().set(iddetail);
        refRecordStatusProperty().set(refRecordStatus);
        tblCompanyBalanceProperty().set(tblCompanyBalance);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblHotelFinanceTransactionProperty().set(tblHotelFinanceTransaction);
        codeCashProperty().set(codeCash);
        cashNoteProperty().set(cashNote);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

    }

    public TblHotelFinanceTransactionWithCash(TblHotelFinanceTransactionWithCash tblHotelFinanceTransactionWithCash) {
        this();
        iddetailProperty().set(tblHotelFinanceTransactionWithCash.getIddetail());
        refRecordStatusProperty().set(tblHotelFinanceTransactionWithCash.getRefRecordStatus());
        tblCompanyBalanceProperty().set(tblHotelFinanceTransactionWithCash.getTblCompanyBalance());
        tblEmployeeByLastUpdateByProperty().set(tblHotelFinanceTransactionWithCash.getTblEmployeeByLastUpdateBy());
        tblEmployeeByCreateByProperty().set(tblHotelFinanceTransactionWithCash.getTblEmployeeByCreateBy());
        tblHotelFinanceTransactionProperty().set(tblHotelFinanceTransactionWithCash.getTblHotelFinanceTransaction());
        codeCashProperty().set(tblHotelFinanceTransactionWithCash.getCodeCash());
        cashNoteProperty().set(tblHotelFinanceTransactionWithCash.getCashNote());
        createDateProperty().set(tblHotelFinanceTransactionWithCash.getCreateDate());
        lastUpdateDateProperty().set(tblHotelFinanceTransactionWithCash.getLastUpdateDate());

    }

    public final LongProperty iddetailProperty() {
        return this.iddetail;
    }

    public long getIddetail() {
        return iddetailProperty().get();
    }

    public void setIddetail(long iddetail) {
        iddetailProperty().set(iddetail);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblCompanyBalance> tblCompanyBalanceProperty() {
        return this.tblCompanyBalance;
    }

    public TblCompanyBalance getTblCompanyBalance() {
        return tblCompanyBalanceProperty().get();
    }

    public void setTblCompanyBalance(TblCompanyBalance tblCompanyBalance) {
        tblCompanyBalanceProperty().set(tblCompanyBalance);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblHotelFinanceTransaction> tblHotelFinanceTransactionProperty() {
        return this.tblHotelFinanceTransaction;
    }

    public TblHotelFinanceTransaction getTblHotelFinanceTransaction() {
        return tblHotelFinanceTransactionProperty().get();
    }

    public void setTblHotelFinanceTransaction(TblHotelFinanceTransaction tblHotelFinanceTransaction) {
        tblHotelFinanceTransactionProperty().set(tblHotelFinanceTransaction);
    }

    public final StringProperty codeCashProperty() {
        return this.codeCash;
    }

    public String getCodeCash() {
        return codeCashProperty().get();
    }

    public void setCodeCash(String codeCash) {
        codeCashProperty().set(codeCash);
    }

    public final StringProperty cashNoteProperty() {
        return this.cashNote;
    }

    public String getCashNote() {
        return cashNoteProperty().get();
    }

    public void setCashNote(String cashNote) {
        cashNoteProperty().set(cashNote);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

}
