package hotelfx.persistence.model;
// Generated Sep 21, 2018 1:57:14 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblItemLocation generated by hbm2java
 */
public class TblItemLocation implements java.io.Serializable {

    private final LongProperty idrelation;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblItem> tblItem;
    private final ObjectProperty<TblLocation> tblLocation;
    private final ObjectProperty<BigDecimal> itemQuantity;
    private final StringProperty note;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    private Set tblItemLocationPropertyBarcodes;
    private Set tblItemLocationItemExpiredDates;

    public TblItemLocation() {
        this.idrelation = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblItem = new SimpleObjectProperty<>();
        this.tblLocation = new SimpleObjectProperty<>();
        this.itemQuantity = new SimpleObjectProperty<>();
        this.note = new SimpleStringProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

        this.tblItemLocationPropertyBarcodes = new HashSet(0);
        this.tblItemLocationItemExpiredDates = new HashSet(0);
    }

    public TblItemLocation(long idrelation) {
        this();
        idrelationProperty().set(idrelation);
    }

    public TblItemLocation(long idrelation, RefRecordStatus refRecordStatus, TblEmployee tblEmployeeByLastUpdateBy, TblEmployee tblEmployeeByCreateBy, TblItem tblItem, TblLocation tblLocation, BigDecimal itemQuantity, String note, Date createDate, Date lastUpdateDate, Set tblItemLocationPropertyBarcodes, Set tblItemLocationItemExpiredDates) {
        this();
        idrelationProperty().set(idrelation);
        refRecordStatusProperty().set(refRecordStatus);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblItemProperty().set(tblItem);
        tblLocationProperty().set(tblLocation);
        itemQuantityProperty().set(itemQuantity);
        noteProperty().set(note);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

        this.tblItemLocationPropertyBarcodes = tblItemLocationPropertyBarcodes;
        this.tblItemLocationItemExpiredDates = tblItemLocationItemExpiredDates;
    }

    public TblItemLocation(TblItemLocation tblItemLocation) {
        this();
        idrelationProperty().set(tblItemLocation.getIdrelation());
        refRecordStatusProperty().set(tblItemLocation.getRefRecordStatus());
        tblEmployeeByLastUpdateByProperty().set(tblItemLocation.getTblEmployeeByLastUpdateBy());
        tblEmployeeByCreateByProperty().set(tblItemLocation.getTblEmployeeByCreateBy());
        tblItemProperty().set(tblItemLocation.getTblItem());
        tblLocationProperty().set(tblItemLocation.getTblLocation());
        itemQuantityProperty().set(tblItemLocation.getItemQuantity());
        noteProperty().set(tblItemLocation.getNote());
        createDateProperty().set(tblItemLocation.getCreateDate());
        lastUpdateDateProperty().set(tblItemLocation.getLastUpdateDate());

        this.tblItemLocationPropertyBarcodes = tblItemLocation.getTblItemLocationPropertyBarcodes();
        this.tblItemLocationItemExpiredDates = tblItemLocation.getTblItemLocationItemExpiredDates();
    }

    public final LongProperty idrelationProperty() {
        return this.idrelation;
    }

    public long getIdrelation() {
        return idrelationProperty().get();
    }

    public void setIdrelation(long idrelation) {
        idrelationProperty().set(idrelation);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblItem> tblItemProperty() {
        return this.tblItem;
    }

    public TblItem getTblItem() {
        return tblItemProperty().get();
    }

    public void setTblItem(TblItem tblItem) {
        tblItemProperty().set(tblItem);
    }

    public final ObjectProperty<TblLocation> tblLocationProperty() {
        return this.tblLocation;
    }

    public TblLocation getTblLocation() {
        return tblLocationProperty().get();
    }

    public void setTblLocation(TblLocation tblLocation) {
        tblLocationProperty().set(tblLocation);
    }

    public final ObjectProperty<BigDecimal> itemQuantityProperty() {
        return this.itemQuantity;
    }

    public BigDecimal getItemQuantity() {
        return itemQuantityProperty().get();
    }

    public void setItemQuantity(BigDecimal itemQuantity) {
        itemQuantityProperty().set(itemQuantity);
    }

    public final StringProperty noteProperty() {
        return this.note;
    }

    public String getNote() {
        return noteProperty().get();
    }

    public void setNote(String note) {
        noteProperty().set(note);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

    public Set getTblItemLocationPropertyBarcodes() {
        return this.tblItemLocationPropertyBarcodes;
    }

    public void setTblItemLocationPropertyBarcodes(Set tblItemLocationPropertyBarcodes) {
        this.tblItemLocationPropertyBarcodes = tblItemLocationPropertyBarcodes;
    }

    public Set getTblItemLocationItemExpiredDates() {
        return this.tblItemLocationItemExpiredDates;
    }

    public void setTblItemLocationItemExpiredDates(Set tblItemLocationItemExpiredDates) {
        this.tblItemLocationItemExpiredDates = tblItemLocationItemExpiredDates;
    }

    @Override
    public String toString(){
        return getTblItem().getItemName();
    }
    
}
