package hotelfx.persistence.model;
// Generated Oct 18, 2018 4:38:29 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblItemMutationHistory generated by hbm2java
 */
public class TblItemMutationHistory implements java.io.Serializable {

    private final LongProperty idmutation;
    private final ObjectProperty<RefItemMutationType> refItemMutationType;
    private final ObjectProperty<RefItemObsoleteBy> refItemObsoleteBy;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByIdemployee;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblItem> tblItem;
    private final ObjectProperty<TblLocation> tblLocationByIdlocationOfDestination;
    private final ObjectProperty<TblLocation> tblLocationByIdlocationOfSource;
    private final StringProperty codeMutation;
    private final ObjectProperty<BigDecimal> itemQuantity;
    private final ObjectProperty<Date> mutationDate;
    private final StringProperty mutationNote;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    private Set tblBrokenItemDetailItemMutationHistories;
    private Set tblStoreRequestDetailItemMutationHistories;
    private Set tblRoomCheckItemMutationHistories;
    private Set tblInComingDetailItemMutationHistories;
    private Set tblItemMutationHistoryPropertyBarcodes;
    private Set tblItemMutationHistoryItemExpiredDates;
    private Set tblOutGoingDetailItemMutationHistories;

    public TblItemMutationHistory() {
        this.idmutation = new SimpleLongProperty();
        this.refItemMutationType = new SimpleObjectProperty<>();
        this.refItemObsoleteBy = new SimpleObjectProperty<>();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByIdemployee = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblItem = new SimpleObjectProperty<>();
        this.tblLocationByIdlocationOfDestination = new SimpleObjectProperty<>();
        this.tblLocationByIdlocationOfSource = new SimpleObjectProperty<>();
        this.codeMutation = new SimpleStringProperty();
        this.itemQuantity = new SimpleObjectProperty<>();
        this.mutationDate = new SimpleObjectProperty<>();
        this.mutationNote = new SimpleStringProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

        this.tblBrokenItemDetailItemMutationHistories = new HashSet(0);
        this.tblStoreRequestDetailItemMutationHistories = new HashSet(0);
        this.tblRoomCheckItemMutationHistories = new HashSet(0);
        this.tblInComingDetailItemMutationHistories = new HashSet(0);
        this.tblItemMutationHistoryPropertyBarcodes = new HashSet(0);
        this.tblItemMutationHistoryItemExpiredDates = new HashSet(0);
        this.tblOutGoingDetailItemMutationHistories = new HashSet(0);
    }

    public TblItemMutationHistory(long idmutation) {
        this();
        idmutationProperty().set(idmutation);
    }

    public TblItemMutationHistory(long idmutation, RefItemMutationType refItemMutationType, RefItemObsoleteBy refItemObsoleteBy, RefRecordStatus refRecordStatus, TblEmployee tblEmployeeByIdemployee, TblEmployee tblEmployeeByLastUpdateBy, TblEmployee tblEmployeeByCreateBy, TblItem tblItem, TblLocation tblLocationByIdlocationOfDestination, TblLocation tblLocationByIdlocationOfSource, String codeMutation, BigDecimal itemQuantity, Date mutationDate, String mutationNote, Date createDate, Date lastUpdateDate, Set tblBrokenItemDetailItemMutationHistories, Set tblStoreRequestDetailItemMutationHistories, Set tblRoomCheckItemMutationHistories, Set tblInComingDetailItemMutationHistories, Set tblItemMutationHistoryPropertyBarcodes, Set tblItemMutationHistoryItemExpiredDates, Set tblOutGoingDetailItemMutationHistories) {
        this();
        idmutationProperty().set(idmutation);
        refItemMutationTypeProperty().set(refItemMutationType);
        refItemObsoleteByProperty().set(refItemObsoleteBy);
        refRecordStatusProperty().set(refRecordStatus);
        tblEmployeeByIdemployeeProperty().set(tblEmployeeByIdemployee);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblItemProperty().set(tblItem);
        tblLocationByIdlocationOfDestinationProperty().set(tblLocationByIdlocationOfDestination);
        tblLocationByIdlocationOfSourceProperty().set(tblLocationByIdlocationOfSource);
        codeMutationProperty().set(codeMutation);
        itemQuantityProperty().set(itemQuantity);
        mutationDateProperty().set(mutationDate);
        mutationNoteProperty().set(mutationNote);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

        this.tblBrokenItemDetailItemMutationHistories = tblBrokenItemDetailItemMutationHistories;
        this.tblStoreRequestDetailItemMutationHistories = tblStoreRequestDetailItemMutationHistories;
        this.tblRoomCheckItemMutationHistories = tblRoomCheckItemMutationHistories;
        this.tblInComingDetailItemMutationHistories = tblInComingDetailItemMutationHistories;
        this.tblItemMutationHistoryPropertyBarcodes = tblItemMutationHistoryPropertyBarcodes;
        this.tblItemMutationHistoryItemExpiredDates = tblItemMutationHistoryItemExpiredDates;
        this.tblOutGoingDetailItemMutationHistories = tblOutGoingDetailItemMutationHistories;
    }

    public TblItemMutationHistory(TblItemMutationHistory tblItemMutationHistory) {
        this();
        idmutationProperty().set(tblItemMutationHistory.getIdmutation());
        refItemMutationTypeProperty().set(tblItemMutationHistory.getRefItemMutationType());
        refItemObsoleteByProperty().set(tblItemMutationHistory.getRefItemObsoleteBy());
        refRecordStatusProperty().set(tblItemMutationHistory.getRefRecordStatus());
        tblEmployeeByIdemployeeProperty().set(tblItemMutationHistory.getTblEmployeeByIdemployee());
        tblEmployeeByLastUpdateByProperty().set(tblItemMutationHistory.getTblEmployeeByLastUpdateBy());
        tblEmployeeByCreateByProperty().set(tblItemMutationHistory.getTblEmployeeByCreateBy());
        tblItemProperty().set(tblItemMutationHistory.getTblItem());
        tblLocationByIdlocationOfDestinationProperty().set(tblItemMutationHistory.getTblLocationByIdlocationOfDestination());
        tblLocationByIdlocationOfSourceProperty().set(tblItemMutationHistory.getTblLocationByIdlocationOfSource());
        codeMutationProperty().set(tblItemMutationHistory.getCodeMutation());
        itemQuantityProperty().set(tblItemMutationHistory.getItemQuantity());
        mutationDateProperty().set(tblItemMutationHistory.getMutationDate());
        mutationNoteProperty().set(tblItemMutationHistory.getMutationNote());
        createDateProperty().set(tblItemMutationHistory.getCreateDate());
        lastUpdateDateProperty().set(tblItemMutationHistory.getLastUpdateDate());

        this.tblBrokenItemDetailItemMutationHistories = tblItemMutationHistory.getTblBrokenItemDetailItemMutationHistories();
        this.tblStoreRequestDetailItemMutationHistories = tblItemMutationHistory.getTblStoreRequestDetailItemMutationHistories();
        this.tblRoomCheckItemMutationHistories = tblItemMutationHistory.getTblRoomCheckItemMutationHistories();
        this.tblInComingDetailItemMutationHistories = tblItemMutationHistory.getTblInComingDetailItemMutationHistories();
        this.tblItemMutationHistoryPropertyBarcodes = tblItemMutationHistory.getTblItemMutationHistoryPropertyBarcodes();
        this.tblItemMutationHistoryItemExpiredDates = tblItemMutationHistory.getTblItemMutationHistoryItemExpiredDates();
        this.tblOutGoingDetailItemMutationHistories = tblItemMutationHistory.getTblOutGoingDetailItemMutationHistories();
    }

    public final LongProperty idmutationProperty() {
        return this.idmutation;
    }

    public long getIdmutation() {
        return idmutationProperty().get();
    }

    public void setIdmutation(long idmutation) {
        idmutationProperty().set(idmutation);
    }

    public final ObjectProperty<RefItemMutationType> refItemMutationTypeProperty() {
        return this.refItemMutationType;
    }

    public RefItemMutationType getRefItemMutationType() {
        return refItemMutationTypeProperty().get();
    }

    public void setRefItemMutationType(RefItemMutationType refItemMutationType) {
        refItemMutationTypeProperty().set(refItemMutationType);
    }

    public final ObjectProperty<RefItemObsoleteBy> refItemObsoleteByProperty() {
        return this.refItemObsoleteBy;
    }

    public RefItemObsoleteBy getRefItemObsoleteBy() {
        return refItemObsoleteByProperty().get();
    }

    public void setRefItemObsoleteBy(RefItemObsoleteBy refItemObsoleteBy) {
        refItemObsoleteByProperty().set(refItemObsoleteBy);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByIdemployeeProperty() {
        return this.tblEmployeeByIdemployee;
    }

    public TblEmployee getTblEmployeeByIdemployee() {
        return tblEmployeeByIdemployeeProperty().get();
    }

    public void setTblEmployeeByIdemployee(TblEmployee tblEmployeeByIdemployee) {
        tblEmployeeByIdemployeeProperty().set(tblEmployeeByIdemployee);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblItem> tblItemProperty() {
        return this.tblItem;
    }

    public TblItem getTblItem() {
        return tblItemProperty().get();
    }

    public void setTblItem(TblItem tblItem) {
        tblItemProperty().set(tblItem);
    }

    public final ObjectProperty<TblLocation> tblLocationByIdlocationOfDestinationProperty() {
        return this.tblLocationByIdlocationOfDestination;
    }

    public TblLocation getTblLocationByIdlocationOfDestination() {
        return tblLocationByIdlocationOfDestinationProperty().get();
    }

    public void setTblLocationByIdlocationOfDestination(TblLocation tblLocationByIdlocationOfDestination) {
        tblLocationByIdlocationOfDestinationProperty().set(tblLocationByIdlocationOfDestination);
    }

    public final ObjectProperty<TblLocation> tblLocationByIdlocationOfSourceProperty() {
        return this.tblLocationByIdlocationOfSource;
    }

    public TblLocation getTblLocationByIdlocationOfSource() {
        return tblLocationByIdlocationOfSourceProperty().get();
    }

    public void setTblLocationByIdlocationOfSource(TblLocation tblLocationByIdlocationOfSource) {
        tblLocationByIdlocationOfSourceProperty().set(tblLocationByIdlocationOfSource);
    }

    public final StringProperty codeMutationProperty() {
        return this.codeMutation;
    }

    public String getCodeMutation() {
        return codeMutationProperty().get();
    }

    public void setCodeMutation(String codeMutation) {
        codeMutationProperty().set(codeMutation);
    }

    public final ObjectProperty<BigDecimal> itemQuantityProperty() {
        return this.itemQuantity;
    }

    public BigDecimal getItemQuantity() {
        return itemQuantityProperty().get();
    }

    public void setItemQuantity(BigDecimal itemQuantity) {
        itemQuantityProperty().set(itemQuantity);
    }

    public final ObjectProperty<Date> mutationDateProperty() {
        return this.mutationDate;
    }

    public Date getMutationDate() {
        return mutationDateProperty().get();
    }

    public void setMutationDate(Date mutationDate) {
        mutationDateProperty().set(mutationDate);
    }

    public final StringProperty mutationNoteProperty() {
        return this.mutationNote;
    }

    public String getMutationNote() {
        return mutationNoteProperty().get();
    }

    public void setMutationNote(String mutationNote) {
        mutationNoteProperty().set(mutationNote);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

    public Set getTblBrokenItemDetailItemMutationHistories() {
        return this.tblBrokenItemDetailItemMutationHistories;
    }

    public void setTblBrokenItemDetailItemMutationHistories(Set tblBrokenItemDetailItemMutationHistories) {
        this.tblBrokenItemDetailItemMutationHistories = tblBrokenItemDetailItemMutationHistories;
    }

    public Set getTblStoreRequestDetailItemMutationHistories() {
        return this.tblStoreRequestDetailItemMutationHistories;
    }

    public void setTblStoreRequestDetailItemMutationHistories(Set tblStoreRequestDetailItemMutationHistories) {
        this.tblStoreRequestDetailItemMutationHistories = tblStoreRequestDetailItemMutationHistories;
    }

    public Set getTblRoomCheckItemMutationHistories() {
        return this.tblRoomCheckItemMutationHistories;
    }

    public void setTblRoomCheckItemMutationHistories(Set tblRoomCheckItemMutationHistories) {
        this.tblRoomCheckItemMutationHistories = tblRoomCheckItemMutationHistories;
    }

    public Set getTblInComingDetailItemMutationHistories() {
        return this.tblInComingDetailItemMutationHistories;
    }

    public void setTblInComingDetailItemMutationHistories(Set tblInComingDetailItemMutationHistories) {
        this.tblInComingDetailItemMutationHistories = tblInComingDetailItemMutationHistories;
    }

    public Set getTblItemMutationHistoryPropertyBarcodes() {
        return this.tblItemMutationHistoryPropertyBarcodes;
    }

    public void setTblItemMutationHistoryPropertyBarcodes(Set tblItemMutationHistoryPropertyBarcodes) {
        this.tblItemMutationHistoryPropertyBarcodes = tblItemMutationHistoryPropertyBarcodes;
    }

    public Set getTblItemMutationHistoryItemExpiredDates() {
        return this.tblItemMutationHistoryItemExpiredDates;
    }

    public void setTblItemMutationHistoryItemExpiredDates(Set tblItemMutationHistoryItemExpiredDates) {
        this.tblItemMutationHistoryItemExpiredDates = tblItemMutationHistoryItemExpiredDates;
    }

    public Set getTblOutGoingDetailItemMutationHistories() {
        return this.tblOutGoingDetailItemMutationHistories;
    }

    public void setTblOutGoingDetailItemMutationHistories(Set tblOutGoingDetailItemMutationHistories) {
        this.tblOutGoingDetailItemMutationHistories = tblOutGoingDetailItemMutationHistories;
    }

}
