package hotelfx.persistence.model;
// Generated Sep 3, 2018 11:08:35 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblItemTypeHk generated by hbm2java
 */
public class TblItemTypeHk implements java.io.Serializable {

    private final LongProperty iditemTypeHk;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final StringProperty codeItemTypeHk;
    private final StringProperty itemTypeHkname;
    private final StringProperty itemTypeHknote;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    private Set tblItems;

    public TblItemTypeHk() {
        this.iditemTypeHk = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.codeItemTypeHk = new SimpleStringProperty();
        this.itemTypeHkname = new SimpleStringProperty();
        this.itemTypeHknote = new SimpleStringProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

        this.tblItems = new HashSet(0);
    }

    public TblItemTypeHk(long iditemTypeHk) {
        this();
        iditemTypeHkProperty().set(iditemTypeHk);
    }

    public TblItemTypeHk(long iditemTypeHk, RefRecordStatus refRecordStatus, TblEmployee tblEmployeeByCreateBy, TblEmployee tblEmployeeByLastUpdateBy, String codeItemTypeHk, String itemTypeHkname, String itemTypeHknote, Date createDate, Date lastUpdateDate, Set tblItems) {
        this();
        iditemTypeHkProperty().set(iditemTypeHk);
        refRecordStatusProperty().set(refRecordStatus);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        codeItemTypeHkProperty().set(codeItemTypeHk);
        itemTypeHknameProperty().set(itemTypeHkname);
        itemTypeHknoteProperty().set(itemTypeHknote);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

        this.tblItems = tblItems;
    }

    public TblItemTypeHk(TblItemTypeHk tblItemTypeHk) {
        this();
        iditemTypeHkProperty().set(tblItemTypeHk.getIditemTypeHk());
        refRecordStatusProperty().set(tblItemTypeHk.getRefRecordStatus());
        tblEmployeeByCreateByProperty().set(tblItemTypeHk.getTblEmployeeByCreateBy());
        tblEmployeeByLastUpdateByProperty().set(tblItemTypeHk.getTblEmployeeByLastUpdateBy());
        codeItemTypeHkProperty().set(tblItemTypeHk.getCodeItemTypeHk());
        itemTypeHknameProperty().set(tblItemTypeHk.getItemTypeHkname());
        itemTypeHknoteProperty().set(tblItemTypeHk.getItemTypeHknote());
        createDateProperty().set(tblItemTypeHk.getCreateDate());
        lastUpdateDateProperty().set(tblItemTypeHk.getLastUpdateDate());

        this.tblItems = tblItemTypeHk.getTblItems();
    }

    public final LongProperty iditemTypeHkProperty() {
        return this.iditemTypeHk;
    }

    public long getIditemTypeHk() {
        return iditemTypeHkProperty().get();
    }

    public void setIditemTypeHk(long iditemTypeHk) {
        iditemTypeHkProperty().set(iditemTypeHk);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final StringProperty codeItemTypeHkProperty() {
        return this.codeItemTypeHk;
    }

    public String getCodeItemTypeHk() {
        return codeItemTypeHkProperty().get();
    }

    public void setCodeItemTypeHk(String codeItemTypeHk) {
        codeItemTypeHkProperty().set(codeItemTypeHk);
    }

    public final StringProperty itemTypeHknameProperty() {
        return this.itemTypeHkname;
    }

    public String getItemTypeHkname() {
        return itemTypeHknameProperty().get();
    }

    public void setItemTypeHkname(String itemTypeHkname) {
        itemTypeHknameProperty().set(itemTypeHkname);
    }

    public final StringProperty itemTypeHknoteProperty() {
        return this.itemTypeHknote;
    }

    public String getItemTypeHknote() {
        return itemTypeHknoteProperty().get();
    }

    public void setItemTypeHknote(String itemTypeHknote) {
        itemTypeHknoteProperty().set(itemTypeHknote);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

    public Set getTblItems() {
        return this.tblItems;
    }

    public void setTblItems(Set tblItems) {
        this.tblItems = tblItems;
    }

    @Override
    public String toString(){
        return getItemTypeHkname();
    }
    
}
