package hotelfx.persistence.model;
// Generated Oct 10, 2018 2:47:45 PM by Hibernate Tools 4.3.1

import java.util.Date;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;

/**
 * TblInComingDetailItemMutationHistory generated by hbm2java
 */
public class TblInComingDetailItemMutationHistory implements java.io.Serializable {

    private final LongProperty idrelation;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblInComingDetail> tblInComingDetail;
    private final ObjectProperty<TblItemMutationHistory> tblItemMutationHistory;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    public TblInComingDetailItemMutationHistory() {
        this.idrelation = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblInComingDetail = new SimpleObjectProperty<>();
        this.tblItemMutationHistory = new SimpleObjectProperty<>();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

    }

    public TblInComingDetailItemMutationHistory(long idrelation) {
        this();
        idrelationProperty().set(idrelation);
    }

    public TblInComingDetailItemMutationHistory(long idrelation, RefRecordStatus refRecordStatus, TblEmployee tblEmployeeByLastUpdateBy, TblEmployee tblEmployeeByCreateBy, TblInComingDetail tblInComingDetail, TblItemMutationHistory tblItemMutationHistory, Date createDate, Date lastUpdateDate) {
        this();
        idrelationProperty().set(idrelation);
        refRecordStatusProperty().set(refRecordStatus);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblInComingDetailProperty().set(tblInComingDetail);
        tblItemMutationHistoryProperty().set(tblItemMutationHistory);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

    }

    public TblInComingDetailItemMutationHistory(TblInComingDetailItemMutationHistory tblInComingDetailItemMutationHistory) {
        this();
        idrelationProperty().set(tblInComingDetailItemMutationHistory.getIdrelation());
        refRecordStatusProperty().set(tblInComingDetailItemMutationHistory.getRefRecordStatus());
        tblEmployeeByLastUpdateByProperty().set(tblInComingDetailItemMutationHistory.getTblEmployeeByLastUpdateBy());
        tblEmployeeByCreateByProperty().set(tblInComingDetailItemMutationHistory.getTblEmployeeByCreateBy());
        tblInComingDetailProperty().set(tblInComingDetailItemMutationHistory.getTblInComingDetail());
        tblItemMutationHistoryProperty().set(tblInComingDetailItemMutationHistory.getTblItemMutationHistory());
        createDateProperty().set(tblInComingDetailItemMutationHistory.getCreateDate());
        lastUpdateDateProperty().set(tblInComingDetailItemMutationHistory.getLastUpdateDate());

    }

    public final LongProperty idrelationProperty() {
        return this.idrelation;
    }

    public long getIdrelation() {
        return idrelationProperty().get();
    }

    public void setIdrelation(long idrelation) {
        idrelationProperty().set(idrelation);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblInComingDetail> tblInComingDetailProperty() {
        return this.tblInComingDetail;
    }

    public TblInComingDetail getTblInComingDetail() {
        return tblInComingDetailProperty().get();
    }

    public void setTblInComingDetail(TblInComingDetail tblInComingDetail) {
        tblInComingDetailProperty().set(tblInComingDetail);
    }

    public final ObjectProperty<TblItemMutationHistory> tblItemMutationHistoryProperty() {
        return this.tblItemMutationHistory;
    }

    public TblItemMutationHistory getTblItemMutationHistory() {
        return tblItemMutationHistoryProperty().get();
    }

    public void setTblItemMutationHistory(TblItemMutationHistory tblItemMutationHistory) {
        tblItemMutationHistoryProperty().set(tblItemMutationHistory);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

}
