package hotelfx.persistence.model;
// Generated Apr 19, 2018 10:20:39 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblItemCostOfGoodSoldHistory generated by hbm2java
 */
public class TblItemCostOfGoodSoldHistory implements java.io.Serializable {

    private final LongProperty idcostOfGoodsSoldHistory;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblItem> tblItem;
    private final StringProperty codeCostOfGoodsSoldHistory;
    private final ObjectProperty<Date> changedDate;
    private final ObjectProperty<BigDecimal> costOfGoodsSold;
    private final StringProperty historyNote;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    public TblItemCostOfGoodSoldHistory() {
        this.idcostOfGoodsSoldHistory = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblItem = new SimpleObjectProperty<>();
        this.codeCostOfGoodsSoldHistory = new SimpleStringProperty();
        this.changedDate = new SimpleObjectProperty<>();
        this.costOfGoodsSold = new SimpleObjectProperty<>();
        this.historyNote = new SimpleStringProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

    }

    public TblItemCostOfGoodSoldHistory(long idcostOfGoodsSoldHistory) {
        this();
        idcostOfGoodsSoldHistoryProperty().set(idcostOfGoodsSoldHistory);
    }

    public TblItemCostOfGoodSoldHistory(long idcostOfGoodsSoldHistory, RefRecordStatus refRecordStatus, TblEmployee tblEmployeeByLastUpdateBy, TblEmployee tblEmployeeByCreateBy, TblItem tblItem, String codeCostOfGoodsSoldHistory, Date changedDate, BigDecimal costOfGoodsSold, String historyNote, Date createDate, Date lastUpdateDate) {
        this();
        idcostOfGoodsSoldHistoryProperty().set(idcostOfGoodsSoldHistory);
        refRecordStatusProperty().set(refRecordStatus);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblItemProperty().set(tblItem);
        codeCostOfGoodsSoldHistoryProperty().set(codeCostOfGoodsSoldHistory);
        changedDateProperty().set(changedDate);
        costOfGoodsSoldProperty().set(costOfGoodsSold);
        historyNoteProperty().set(historyNote);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

    }

    public TblItemCostOfGoodSoldHistory(TblItemCostOfGoodSoldHistory tblItemCostOfGoodSoldHistory) {
        this();
        idcostOfGoodsSoldHistoryProperty().set(tblItemCostOfGoodSoldHistory.getIdcostOfGoodsSoldHistory());
        refRecordStatusProperty().set(tblItemCostOfGoodSoldHistory.getRefRecordStatus());
        tblEmployeeByLastUpdateByProperty().set(tblItemCostOfGoodSoldHistory.getTblEmployeeByLastUpdateBy());
        tblEmployeeByCreateByProperty().set(tblItemCostOfGoodSoldHistory.getTblEmployeeByCreateBy());
        tblItemProperty().set(tblItemCostOfGoodSoldHistory.getTblItem());
        codeCostOfGoodsSoldHistoryProperty().set(tblItemCostOfGoodSoldHistory.getCodeCostOfGoodsSoldHistory());
        changedDateProperty().set(tblItemCostOfGoodSoldHistory.getChangedDate());
        costOfGoodsSoldProperty().set(tblItemCostOfGoodSoldHistory.getCostOfGoodsSold());
        historyNoteProperty().set(tblItemCostOfGoodSoldHistory.getHistoryNote());
        createDateProperty().set(tblItemCostOfGoodSoldHistory.getCreateDate());
        lastUpdateDateProperty().set(tblItemCostOfGoodSoldHistory.getLastUpdateDate());

    }

    public final LongProperty idcostOfGoodsSoldHistoryProperty() {
        return this.idcostOfGoodsSoldHistory;
    }

    public long getIdcostOfGoodsSoldHistory() {
        return idcostOfGoodsSoldHistoryProperty().get();
    }

    public void setIdcostOfGoodsSoldHistory(long idcostOfGoodsSoldHistory) {
        idcostOfGoodsSoldHistoryProperty().set(idcostOfGoodsSoldHistory);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblItem> tblItemProperty() {
        return this.tblItem;
    }

    public TblItem getTblItem() {
        return tblItemProperty().get();
    }

    public void setTblItem(TblItem tblItem) {
        tblItemProperty().set(tblItem);
    }

    public final StringProperty codeCostOfGoodsSoldHistoryProperty() {
        return this.codeCostOfGoodsSoldHistory;
    }

    public String getCodeCostOfGoodsSoldHistory() {
        return codeCostOfGoodsSoldHistoryProperty().get();
    }

    public void setCodeCostOfGoodsSoldHistory(String codeCostOfGoodsSoldHistory) {
        codeCostOfGoodsSoldHistoryProperty().set(codeCostOfGoodsSoldHistory);
    }

    public final ObjectProperty<Date> changedDateProperty() {
        return this.changedDate;
    }

    public Date getChangedDate() {
        return changedDateProperty().get();
    }

    public void setChangedDate(Date changedDate) {
        changedDateProperty().set(changedDate);
    }

    public final ObjectProperty<BigDecimal> costOfGoodsSoldProperty() {
        return this.costOfGoodsSold;
    }

    public BigDecimal getCostOfGoodsSold() {
        return costOfGoodsSoldProperty().get();
    }

    public void setCostOfGoodsSold(BigDecimal costOfGoodsSold) {
        costOfGoodsSoldProperty().set(costOfGoodsSold);
    }

    public final StringProperty historyNoteProperty() {
        return this.historyNote;
    }

    public String getHistoryNote() {
        return historyNoteProperty().get();
    }

    public void setHistoryNote(String historyNote) {
        historyNoteProperty().set(historyNote);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

}
