package hotelfx.persistence.model;
// Generated Sep 5, 2017 11:14:20 AM by Hibernate Tools 4.3.1

import java.util.Date;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;

/**
 * TblItemLocationPropertyBarcode generated by hbm2java
 */
public class TblItemLocationPropertyBarcode implements java.io.Serializable {

    private final LongProperty idrelation;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblItemLocation> tblItemLocation;
    private final ObjectProperty<TblPropertyBarcode> tblPropertyBarcode;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    public TblItemLocationPropertyBarcode() {
        this.idrelation = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblItemLocation = new SimpleObjectProperty<>();
        this.tblPropertyBarcode = new SimpleObjectProperty<>();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

    }

    public TblItemLocationPropertyBarcode(long idrelation) {
        this();
        idrelationProperty().set(idrelation);
    }

    public TblItemLocationPropertyBarcode(long idrelation, RefRecordStatus refRecordStatus, TblEmployee tblEmployeeByCreateBy, TblEmployee tblEmployeeByLastUpdateBy, TblItemLocation tblItemLocation, TblPropertyBarcode tblPropertyBarcode, Date createDate, Date lastUpdateDate) {
        this();
        idrelationProperty().set(idrelation);
        refRecordStatusProperty().set(refRecordStatus);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblItemLocationProperty().set(tblItemLocation);
        tblPropertyBarcodeProperty().set(tblPropertyBarcode);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

    }

    public TblItemLocationPropertyBarcode(TblItemLocationPropertyBarcode tblItemLocationPropertyBarcode) {
        this();
        idrelationProperty().set(tblItemLocationPropertyBarcode.getIdrelation());
        refRecordStatusProperty().set(tblItemLocationPropertyBarcode.getRefRecordStatus());
        tblEmployeeByCreateByProperty().set(tblItemLocationPropertyBarcode.getTblEmployeeByCreateBy());
        tblEmployeeByLastUpdateByProperty().set(tblItemLocationPropertyBarcode.getTblEmployeeByLastUpdateBy());
        tblItemLocationProperty().set(tblItemLocationPropertyBarcode.getTblItemLocation());
        tblPropertyBarcodeProperty().set(tblItemLocationPropertyBarcode.getTblPropertyBarcode());
        createDateProperty().set(tblItemLocationPropertyBarcode.getCreateDate());
        lastUpdateDateProperty().set(tblItemLocationPropertyBarcode.getLastUpdateDate());

    }

    public final LongProperty idrelationProperty() {
        return this.idrelation;
    }

    public long getIdrelation() {
        return idrelationProperty().get();
    }

    public void setIdrelation(long idrelation) {
        idrelationProperty().set(idrelation);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblItemLocation> tblItemLocationProperty() {
        return this.tblItemLocation;
    }

    public TblItemLocation getTblItemLocation() {
        return tblItemLocationProperty().get();
    }

    public void setTblItemLocation(TblItemLocation tblItemLocation) {
        tblItemLocationProperty().set(tblItemLocation);
    }

    public final ObjectProperty<TblPropertyBarcode> tblPropertyBarcodeProperty() {
        return this.tblPropertyBarcode;
    }

    public TblPropertyBarcode getTblPropertyBarcode() {
        return tblPropertyBarcodeProperty().get();
    }

    public void setTblPropertyBarcode(TblPropertyBarcode tblPropertyBarcode) {
        tblPropertyBarcodeProperty().set(tblPropertyBarcode);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

}
