package hotelfx.persistence.model;
// Generated Nov 1, 2018 9:11:08 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javafx.beans.property.BooleanProperty;
import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleBooleanProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblItem generated by hbm2java
 */
public class TblItem implements java.io.Serializable {

    private final LongProperty iditem;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblItemTypeHk> tblItemTypeHk;
    private final ObjectProperty<TblItemTypeWh> tblItemTypeWh;
    private final ObjectProperty<TblUnit> tblUnit;
    private final StringProperty codeItem;
    private final StringProperty codeWorkSheet;
    private final StringProperty itemName;
    private final StringProperty itemBrand;
    private final ObjectProperty<BigDecimal> itemCostOfGoodsSold;
    private final ObjectProperty<BigDecimal> additionalCharge;
    private final ObjectProperty<BigDecimal> brokenCharge;
    private final ObjectProperty<BigDecimal> stockMinimal;
    private final BooleanProperty consumable;
    private final StringProperty itemNote;
    private final BooleanProperty hotelDiscountable;
    private final BooleanProperty cardDiscountable;
    private final BooleanProperty taxable;
    private final BooleanProperty guestStatus;
    private final BooleanProperty propertyStatus;
    private final BooleanProperty leasedStatus;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    private Set tblReservationRescheduleCanceleds;
    private Set tblSupplierItems;
    private Set tblItemLocations;
    private Set tblRoomTypeItems;
    private Set tblItemMutationHistories;
    private Set tblRoomCheckHouseKeepingAttendanceDetails;
    private Set tblItemCostOfGoodSoldHistories;
    private Set tblReservationAdditionalItemReserveds;
    private Set tblStockOpnameItemExpiredDates;
    private Set tblStoreRequestDetails;
    private Set tblInComingDetails;
    private Set tblPurchaseRequestDetails;
    private Set tblMemorandumInvoiceDetails;
    private Set tblReservationRoomItemDetails;
    private Set tblReservationBrokenItems;
    private Set tblPropertyBarcodes;
    private Set tblStockOpnameDetails;
    private Set tblBrokenItemDetails;
    private Set tblReservationRoomTypeDetailItems;
    private Set tblOutGoingDetails;
    private Set tblReservationAdditionalItems;
    private Set tblItemExpiredDates;

    public TblItem() {
        this.iditem = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblItemTypeHk = new SimpleObjectProperty<>();
        this.tblItemTypeWh = new SimpleObjectProperty<>();
        this.tblUnit = new SimpleObjectProperty<>();
        this.codeItem = new SimpleStringProperty();
        this.codeWorkSheet = new SimpleStringProperty();
        this.itemName = new SimpleStringProperty();
        this.itemBrand = new SimpleStringProperty();
        this.itemCostOfGoodsSold = new SimpleObjectProperty<>();
        this.additionalCharge = new SimpleObjectProperty<>();
        this.brokenCharge = new SimpleObjectProperty<>();
        this.stockMinimal = new SimpleObjectProperty<>();
        this.consumable = new SimpleBooleanProperty();
        this.itemNote = new SimpleStringProperty();
        this.hotelDiscountable = new SimpleBooleanProperty();
        this.cardDiscountable = new SimpleBooleanProperty();
        this.taxable = new SimpleBooleanProperty();
        this.guestStatus = new SimpleBooleanProperty();
        this.propertyStatus = new SimpleBooleanProperty();
        this.leasedStatus = new SimpleBooleanProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

        this.tblReservationRescheduleCanceleds = new HashSet(0);
        this.tblSupplierItems = new HashSet(0);
        this.tblItemLocations = new HashSet(0);
        this.tblRoomTypeItems = new HashSet(0);
        this.tblItemMutationHistories = new HashSet(0);
        this.tblRoomCheckHouseKeepingAttendanceDetails = new HashSet(0);
        this.tblItemCostOfGoodSoldHistories = new HashSet(0);
        this.tblReservationAdditionalItemReserveds = new HashSet(0);
        this.tblStockOpnameItemExpiredDates = new HashSet(0);
        this.tblStoreRequestDetails = new HashSet(0);
        this.tblInComingDetails = new HashSet(0);
        this.tblPurchaseRequestDetails = new HashSet(0);
        this.tblMemorandumInvoiceDetails = new HashSet(0);
        this.tblReservationRoomItemDetails = new HashSet(0);
        this.tblReservationBrokenItems = new HashSet(0);
        this.tblPropertyBarcodes = new HashSet(0);
        this.tblStockOpnameDetails = new HashSet(0);
        this.tblBrokenItemDetails = new HashSet(0);
        this.tblReservationRoomTypeDetailItems = new HashSet(0);
        this.tblOutGoingDetails = new HashSet(0);
        this.tblReservationAdditionalItems = new HashSet(0);
        this.tblItemExpiredDates = new HashSet(0);
    }

    public TblItem(long iditem) {
        this();
        iditemProperty().set(iditem);
    }

    public TblItem(long iditem, RefRecordStatus refRecordStatus, TblEmployee tblEmployeeByCreateBy, TblEmployee tblEmployeeByLastUpdateBy, TblItemTypeHk tblItemTypeHk, TblItemTypeWh tblItemTypeWh, TblUnit tblUnit, String codeItem, String codeWorkSheet, String itemName, String itemBrand, BigDecimal itemCostOfGoodsSold, BigDecimal additionalCharge, BigDecimal brokenCharge, BigDecimal stockMinimal, Boolean consumable, String itemNote, Boolean hotelDiscountable, Boolean cardDiscountable, Boolean taxable, Boolean guestStatus, Boolean propertyStatus, Boolean leasedStatus, Date createDate, Date lastUpdateDate, Set tblReservationRescheduleCanceleds, Set tblSupplierItems, Set tblItemLocations, Set tblRoomTypeItems, Set tblItemMutationHistories, Set tblRoomCheckHouseKeepingAttendanceDetails, Set tblItemCostOfGoodSoldHistories, Set tblReservationAdditionalItemReserveds, Set tblStockOpnameItemExpiredDates, Set tblStoreRequestDetails, Set tblInComingDetails, Set tblPurchaseRequestDetails, Set tblMemorandumInvoiceDetails, Set tblReservationRoomItemDetails, Set tblReservationBrokenItems, Set tblPropertyBarcodes, Set tblStockOpnameDetails, Set tblBrokenItemDetails, Set tblReservationRoomTypeDetailItems, Set tblOutGoingDetails, Set tblReservationAdditionalItems, Set tblItemExpiredDates) {
        this();
        iditemProperty().set(iditem);
        refRecordStatusProperty().set(refRecordStatus);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblItemTypeHkProperty().set(tblItemTypeHk);
        tblItemTypeWhProperty().set(tblItemTypeWh);
        tblUnitProperty().set(tblUnit);
        codeItemProperty().set(codeItem);
        codeWorkSheetProperty().set(codeWorkSheet);
        itemNameProperty().set(itemName);
        itemBrandProperty().set(itemBrand);
        itemCostOfGoodsSoldProperty().set(itemCostOfGoodsSold);
        additionalChargeProperty().set(additionalCharge);
        brokenChargeProperty().set(brokenCharge);
        stockMinimalProperty().set(stockMinimal);
        consumableProperty().set(consumable);
        itemNoteProperty().set(itemNote);
        hotelDiscountableProperty().set(hotelDiscountable);
        cardDiscountableProperty().set(cardDiscountable);
        taxableProperty().set(taxable);
        guestStatusProperty().set(guestStatus);
        propertyStatusProperty().set(propertyStatus);
        leasedStatusProperty().set(leasedStatus);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

        this.tblReservationRescheduleCanceleds = tblReservationRescheduleCanceleds;
        this.tblSupplierItems = tblSupplierItems;
        this.tblItemLocations = tblItemLocations;
        this.tblRoomTypeItems = tblRoomTypeItems;
        this.tblItemMutationHistories = tblItemMutationHistories;
        this.tblRoomCheckHouseKeepingAttendanceDetails = tblRoomCheckHouseKeepingAttendanceDetails;
        this.tblItemCostOfGoodSoldHistories = tblItemCostOfGoodSoldHistories;
        this.tblReservationAdditionalItemReserveds = tblReservationAdditionalItemReserveds;
        this.tblStockOpnameItemExpiredDates = tblStockOpnameItemExpiredDates;
        this.tblStoreRequestDetails = tblStoreRequestDetails;
        this.tblInComingDetails = tblInComingDetails;
        this.tblPurchaseRequestDetails = tblPurchaseRequestDetails;
        this.tblMemorandumInvoiceDetails = tblMemorandumInvoiceDetails;
        this.tblReservationRoomItemDetails = tblReservationRoomItemDetails;
        this.tblReservationBrokenItems = tblReservationBrokenItems;
        this.tblPropertyBarcodes = tblPropertyBarcodes;
        this.tblStockOpnameDetails = tblStockOpnameDetails;
        this.tblBrokenItemDetails = tblBrokenItemDetails;
        this.tblReservationRoomTypeDetailItems = tblReservationRoomTypeDetailItems;
        this.tblOutGoingDetails = tblOutGoingDetails;
        this.tblReservationAdditionalItems = tblReservationAdditionalItems;
        this.tblItemExpiredDates = tblItemExpiredDates;
    }

    public TblItem(TblItem tblItem) {
        this();
        iditemProperty().set(tblItem.getIditem());
        refRecordStatusProperty().set(tblItem.getRefRecordStatus());
        tblEmployeeByCreateByProperty().set(tblItem.getTblEmployeeByCreateBy());
        tblEmployeeByLastUpdateByProperty().set(tblItem.getTblEmployeeByLastUpdateBy());
        tblItemTypeHkProperty().set(tblItem.getTblItemTypeHk());
        tblItemTypeWhProperty().set(tblItem.getTblItemTypeWh());
        tblUnitProperty().set(tblItem.getTblUnit());
        codeItemProperty().set(tblItem.getCodeItem());
        codeWorkSheetProperty().set(tblItem.getCodeWorkSheet());
        itemNameProperty().set(tblItem.getItemName());
        itemBrandProperty().set(tblItem.getItemBrand());
        itemCostOfGoodsSoldProperty().set(tblItem.getItemCostOfGoodsSold());
        additionalChargeProperty().set(tblItem.getAdditionalCharge());
        brokenChargeProperty().set(tblItem.getBrokenCharge());
        stockMinimalProperty().set(tblItem.getStockMinimal());
        consumableProperty().set(tblItem.getConsumable());
        itemNoteProperty().set(tblItem.getItemNote());
        hotelDiscountableProperty().set(tblItem.getHotelDiscountable());
        cardDiscountableProperty().set(tblItem.getCardDiscountable());
        taxableProperty().set(tblItem.getTaxable());
        guestStatusProperty().set(tblItem.getGuestStatus());
        propertyStatusProperty().set(tblItem.getPropertyStatus());
        leasedStatusProperty().set(tblItem.getLeasedStatus());
        createDateProperty().set(tblItem.getCreateDate());
        lastUpdateDateProperty().set(tblItem.getLastUpdateDate());

        this.tblReservationRescheduleCanceleds = tblItem.getTblReservationRescheduleCanceleds();
        this.tblSupplierItems = tblItem.getTblSupplierItems();
        this.tblItemLocations = tblItem.getTblItemLocations();
        this.tblRoomTypeItems = tblItem.getTblRoomTypeItems();
        this.tblItemMutationHistories = tblItem.getTblItemMutationHistories();
        this.tblRoomCheckHouseKeepingAttendanceDetails = tblItem.getTblRoomCheckHouseKeepingAttendanceDetails();
        this.tblItemCostOfGoodSoldHistories = tblItem.getTblItemCostOfGoodSoldHistories();
        this.tblReservationAdditionalItemReserveds = tblItem.getTblReservationAdditionalItemReserveds();
        this.tblStockOpnameItemExpiredDates = tblItem.getTblStockOpnameItemExpiredDates();
        this.tblStoreRequestDetails = tblItem.getTblStoreRequestDetails();
        this.tblInComingDetails = tblItem.getTblInComingDetails();
        this.tblPurchaseRequestDetails = tblItem.getTblPurchaseRequestDetails();
        this.tblMemorandumInvoiceDetails = tblItem.getTblMemorandumInvoiceDetails();
        this.tblReservationRoomItemDetails = tblItem.getTblReservationRoomItemDetails();
        this.tblReservationBrokenItems = tblItem.getTblReservationBrokenItems();
        this.tblPropertyBarcodes = tblItem.getTblPropertyBarcodes();
        this.tblStockOpnameDetails = tblItem.getTblStockOpnameDetails();
        this.tblBrokenItemDetails = tblItem.getTblBrokenItemDetails();
        this.tblReservationRoomTypeDetailItems = tblItem.getTblReservationRoomTypeDetailItems();
        this.tblOutGoingDetails = tblItem.getTblOutGoingDetails();
        this.tblReservationAdditionalItems = tblItem.getTblReservationAdditionalItems();
        this.tblItemExpiredDates = tblItem.getTblItemExpiredDates();
    }

    public final LongProperty iditemProperty() {
        return this.iditem;
    }

    public long getIditem() {
        return iditemProperty().get();
    }

    public void setIditem(long iditem) {
        iditemProperty().set(iditem);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblItemTypeHk> tblItemTypeHkProperty() {
        return this.tblItemTypeHk;
    }

    public TblItemTypeHk getTblItemTypeHk() {
        return tblItemTypeHkProperty().get();
    }

    public void setTblItemTypeHk(TblItemTypeHk tblItemTypeHk) {
        tblItemTypeHkProperty().set(tblItemTypeHk);
    }

    public final ObjectProperty<TblItemTypeWh> tblItemTypeWhProperty() {
        return this.tblItemTypeWh;
    }

    public TblItemTypeWh getTblItemTypeWh() {
        return tblItemTypeWhProperty().get();
    }

    public void setTblItemTypeWh(TblItemTypeWh tblItemTypeWh) {
        tblItemTypeWhProperty().set(tblItemTypeWh);
    }

    public final ObjectProperty<TblUnit> tblUnitProperty() {
        return this.tblUnit;
    }

    public TblUnit getTblUnit() {
        return tblUnitProperty().get();
    }

    public void setTblUnit(TblUnit tblUnit) {
        tblUnitProperty().set(tblUnit);
    }

    public final StringProperty codeItemProperty() {
        return this.codeItem;
    }

    public String getCodeItem() {
        return codeItemProperty().get();
    }

    public void setCodeItem(String codeItem) {
        codeItemProperty().set(codeItem);
    }

    public final StringProperty codeWorkSheetProperty() {
        return this.codeWorkSheet;
    }

    public String getCodeWorkSheet() {
        return codeWorkSheetProperty().get();
    }

    public void setCodeWorkSheet(String codeWorkSheet) {
        codeWorkSheetProperty().set(codeWorkSheet);
    }

    public final StringProperty itemNameProperty() {
        return this.itemName;
    }

    public String getItemName() {
        return itemNameProperty().get();
    }

    public void setItemName(String itemName) {
        itemNameProperty().set(itemName);
    }

    public final StringProperty itemBrandProperty() {
        return this.itemBrand;
    }

    public String getItemBrand() {
        return itemBrandProperty().get();
    }

    public void setItemBrand(String itemBrand) {
        itemBrandProperty().set(itemBrand);
    }

    public final ObjectProperty<BigDecimal> itemCostOfGoodsSoldProperty() {
        return this.itemCostOfGoodsSold;
    }

    public BigDecimal getItemCostOfGoodsSold() {
        return itemCostOfGoodsSoldProperty().get();
    }

    public void setItemCostOfGoodsSold(BigDecimal itemCostOfGoodsSold) {
        itemCostOfGoodsSoldProperty().set(itemCostOfGoodsSold);
    }

    public final ObjectProperty<BigDecimal> additionalChargeProperty() {
        return this.additionalCharge;
    }

    public BigDecimal getAdditionalCharge() {
        return additionalChargeProperty().get();
    }

    public void setAdditionalCharge(BigDecimal additionalCharge) {
        additionalChargeProperty().set(additionalCharge);
    }

    public final ObjectProperty<BigDecimal> brokenChargeProperty() {
        return this.brokenCharge;
    }

    public BigDecimal getBrokenCharge() {
        return brokenChargeProperty().get();
    }

    public void setBrokenCharge(BigDecimal brokenCharge) {
        brokenChargeProperty().set(brokenCharge);
    }

    public final ObjectProperty<BigDecimal> stockMinimalProperty() {
        return this.stockMinimal;
    }

    public BigDecimal getStockMinimal() {
        return stockMinimalProperty().get();
    }

    public void setStockMinimal(BigDecimal stockMinimal) {
        stockMinimalProperty().set(stockMinimal);
    }

    public final BooleanProperty consumableProperty() {
        return this.consumable;
    }

    public Boolean getConsumable() {
        return consumableProperty().get();
    }

    public void setConsumable(Boolean consumable) {
        consumableProperty().set(consumable);
    }

    public final StringProperty itemNoteProperty() {
        return this.itemNote;
    }

    public String getItemNote() {
        return itemNoteProperty().get();
    }

    public void setItemNote(String itemNote) {
        itemNoteProperty().set(itemNote);
    }

    public final BooleanProperty hotelDiscountableProperty() {
        return this.hotelDiscountable;
    }

    public Boolean getHotelDiscountable() {
        return hotelDiscountableProperty().get();
    }

    public void setHotelDiscountable(Boolean hotelDiscountable) {
        hotelDiscountableProperty().set(hotelDiscountable);
    }

    public final BooleanProperty cardDiscountableProperty() {
        return this.cardDiscountable;
    }

    public Boolean getCardDiscountable() {
        return cardDiscountableProperty().get();
    }

    public void setCardDiscountable(Boolean cardDiscountable) {
        cardDiscountableProperty().set(cardDiscountable);
    }

    public final BooleanProperty taxableProperty() {
        return this.taxable;
    }

    public Boolean getTaxable() {
        return taxableProperty().get();
    }

    public void setTaxable(Boolean taxable) {
        taxableProperty().set(taxable);
    }

    public final BooleanProperty guestStatusProperty() {
        return this.guestStatus;
    }

    public Boolean getGuestStatus() {
        return guestStatusProperty().get();
    }

    public void setGuestStatus(Boolean guestStatus) {
        guestStatusProperty().set(guestStatus);
    }

    public final BooleanProperty propertyStatusProperty() {
        return this.propertyStatus;
    }

    public Boolean getPropertyStatus() {
        return propertyStatusProperty().get();
    }

    public void setPropertyStatus(Boolean propertyStatus) {
        propertyStatusProperty().set(propertyStatus);
    }

    public final BooleanProperty leasedStatusProperty() {
        return this.leasedStatus;
    }

    public Boolean getLeasedStatus() {
        return leasedStatusProperty().get();
    }

    public void setLeasedStatus(Boolean leasedStatus) {
        leasedStatusProperty().set(leasedStatus);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

    public Set getTblReservationRescheduleCanceleds() {
        return this.tblReservationRescheduleCanceleds;
    }

    public void setTblReservationRescheduleCanceleds(Set tblReservationRescheduleCanceleds) {
        this.tblReservationRescheduleCanceleds = tblReservationRescheduleCanceleds;
    }

    public Set getTblSupplierItems() {
        return this.tblSupplierItems;
    }

    public void setTblSupplierItems(Set tblSupplierItems) {
        this.tblSupplierItems = tblSupplierItems;
    }

    public Set getTblItemLocations() {
        return this.tblItemLocations;
    }

    public void setTblItemLocations(Set tblItemLocations) {
        this.tblItemLocations = tblItemLocations;
    }

    public Set getTblRoomTypeItems() {
        return this.tblRoomTypeItems;
    }

    public void setTblRoomTypeItems(Set tblRoomTypeItems) {
        this.tblRoomTypeItems = tblRoomTypeItems;
    }

    public Set getTblItemMutationHistories() {
        return this.tblItemMutationHistories;
    }

    public void setTblItemMutationHistories(Set tblItemMutationHistories) {
        this.tblItemMutationHistories = tblItemMutationHistories;
    }

    public Set getTblRoomCheckHouseKeepingAttendanceDetails() {
        return this.tblRoomCheckHouseKeepingAttendanceDetails;
    }

    public void setTblRoomCheckHouseKeepingAttendanceDetails(Set tblRoomCheckHouseKeepingAttendanceDetails) {
        this.tblRoomCheckHouseKeepingAttendanceDetails = tblRoomCheckHouseKeepingAttendanceDetails;
    }

    public Set getTblItemCostOfGoodSoldHistories() {
        return this.tblItemCostOfGoodSoldHistories;
    }

    public void setTblItemCostOfGoodSoldHistories(Set tblItemCostOfGoodSoldHistories) {
        this.tblItemCostOfGoodSoldHistories = tblItemCostOfGoodSoldHistories;
    }

    public Set getTblReservationAdditionalItemReserveds() {
        return this.tblReservationAdditionalItemReserveds;
    }

    public void setTblReservationAdditionalItemReserveds(Set tblReservationAdditionalItemReserveds) {
        this.tblReservationAdditionalItemReserveds = tblReservationAdditionalItemReserveds;
    }

    public Set getTblStockOpnameItemExpiredDates() {
        return this.tblStockOpnameItemExpiredDates;
    }

    public void setTblStockOpnameItemExpiredDates(Set tblStockOpnameItemExpiredDates) {
        this.tblStockOpnameItemExpiredDates = tblStockOpnameItemExpiredDates;
    }

    public Set getTblStoreRequestDetails() {
        return this.tblStoreRequestDetails;
    }

    public void setTblStoreRequestDetails(Set tblStoreRequestDetails) {
        this.tblStoreRequestDetails = tblStoreRequestDetails;
    }

    public Set getTblInComingDetails() {
        return this.tblInComingDetails;
    }

    public void setTblInComingDetails(Set tblInComingDetails) {
        this.tblInComingDetails = tblInComingDetails;
    }

    public Set getTblPurchaseRequestDetails() {
        return this.tblPurchaseRequestDetails;
    }

    public void setTblPurchaseRequestDetails(Set tblPurchaseRequestDetails) {
        this.tblPurchaseRequestDetails = tblPurchaseRequestDetails;
    }

    public Set getTblMemorandumInvoiceDetails() {
        return this.tblMemorandumInvoiceDetails;
    }

    public void setTblMemorandumInvoiceDetails(Set tblMemorandumInvoiceDetails) {
        this.tblMemorandumInvoiceDetails = tblMemorandumInvoiceDetails;
    }

    public Set getTblReservationRoomItemDetails() {
        return this.tblReservationRoomItemDetails;
    }

    public void setTblReservationRoomItemDetails(Set tblReservationRoomItemDetails) {
        this.tblReservationRoomItemDetails = tblReservationRoomItemDetails;
    }

    public Set getTblReservationBrokenItems() {
        return this.tblReservationBrokenItems;
    }

    public void setTblReservationBrokenItems(Set tblReservationBrokenItems) {
        this.tblReservationBrokenItems = tblReservationBrokenItems;
    }

    public Set getTblPropertyBarcodes() {
        return this.tblPropertyBarcodes;
    }

    public void setTblPropertyBarcodes(Set tblPropertyBarcodes) {
        this.tblPropertyBarcodes = tblPropertyBarcodes;
    }

    public Set getTblStockOpnameDetails() {
        return this.tblStockOpnameDetails;
    }

    public void setTblStockOpnameDetails(Set tblStockOpnameDetails) {
        this.tblStockOpnameDetails = tblStockOpnameDetails;
    }

    public Set getTblBrokenItemDetails() {
        return this.tblBrokenItemDetails;
    }

    public void setTblBrokenItemDetails(Set tblBrokenItemDetails) {
        this.tblBrokenItemDetails = tblBrokenItemDetails;
    }

    public Set getTblReservationRoomTypeDetailItems() {
        return this.tblReservationRoomTypeDetailItems;
    }

    public void setTblReservationRoomTypeDetailItems(Set tblReservationRoomTypeDetailItems) {
        this.tblReservationRoomTypeDetailItems = tblReservationRoomTypeDetailItems;
    }

    public Set getTblOutGoingDetails() {
        return this.tblOutGoingDetails;
    }

    public void setTblOutGoingDetails(Set tblOutGoingDetails) {
        this.tblOutGoingDetails = tblOutGoingDetails;
    }

    public Set getTblReservationAdditionalItems() {
        return this.tblReservationAdditionalItems;
    }

    public void setTblReservationAdditionalItems(Set tblReservationAdditionalItems) {
        this.tblReservationAdditionalItems = tblReservationAdditionalItems;
    }

    public Set getTblItemExpiredDates() {
        return this.tblItemExpiredDates;
    }

    public void setTblItemExpiredDates(Set tblItemExpiredDates) {
        this.tblItemExpiredDates = tblItemExpiredDates;
    }

    @Override
    public String toString() {
        return getItemName();
    }
    
}
