package hotelfx.persistence.model;
// Generated Nov 10, 2018 10:51:23 AM by Hibernate Tools 4.3.1

import hotelfx.helper.ClassFormatter;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblItemExpiredDate generated by hbm2java
 */
public class TblItemExpiredDate implements java.io.Serializable {

    private final LongProperty iditemExpiredDate;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUdapteBy;
    private final ObjectProperty<TblItem> tblItem;
    private final StringProperty codeItemExpiredDate;
    private final ObjectProperty<Date> itemExpiredDate;
    private final StringProperty note;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    private Set tblStockOpnameItemExpiredDateDetails;
    private Set tblItemMutationHistoryItemExpiredDates;
    private Set tblStockOpnameDetailItemExpiredDates;
    private Set tblItemLocationItemExpiredDates;
    private Set tblReturDetailItemExpiredDates;
    private Set tblStockOpnameDetails;
    private Set tblMemorandumInvoiceDetailItemExpiredDates;

    public TblItemExpiredDate() {
        this.iditemExpiredDate = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUdapteBy = new SimpleObjectProperty<>();
        this.tblItem = new SimpleObjectProperty<>();
        this.codeItemExpiredDate = new SimpleStringProperty();
        this.itemExpiredDate = new SimpleObjectProperty<>();
        this.note = new SimpleStringProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

        this.tblStockOpnameItemExpiredDateDetails = new HashSet(0);
        this.tblItemMutationHistoryItemExpiredDates = new HashSet(0);
        this.tblStockOpnameDetailItemExpiredDates = new HashSet(0);
        this.tblItemLocationItemExpiredDates = new HashSet(0);
        this.tblReturDetailItemExpiredDates = new HashSet(0);
        this.tblStockOpnameDetails = new HashSet(0);
        this.tblMemorandumInvoiceDetailItemExpiredDates = new HashSet(0);
    }

    public TblItemExpiredDate(long iditemExpiredDate) {
        this();
        iditemExpiredDateProperty().set(iditemExpiredDate);
    }

    public TblItemExpiredDate(long iditemExpiredDate, RefRecordStatus refRecordStatus, TblEmployee tblEmployeeByCreateBy, TblEmployee tblEmployeeByLastUdapteBy, TblItem tblItem, String codeItemExpiredDate, Date itemExpiredDate, String note, Date createDate, Date lastUpdateDate, Set tblStockOpnameItemExpiredDateDetails, Set tblItemMutationHistoryItemExpiredDates, Set tblStockOpnameDetailItemExpiredDates, Set tblItemLocationItemExpiredDates, Set tblReturDetailItemExpiredDates, Set tblStockOpnameDetails, Set tblMemorandumInvoiceDetailItemExpiredDates) {
        this();
        iditemExpiredDateProperty().set(iditemExpiredDate);
        refRecordStatusProperty().set(refRecordStatus);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblEmployeeByLastUdapteByProperty().set(tblEmployeeByLastUdapteBy);
        tblItemProperty().set(tblItem);
        codeItemExpiredDateProperty().set(codeItemExpiredDate);
        itemExpiredDateProperty().set(itemExpiredDate);
        noteProperty().set(note);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

        this.tblStockOpnameItemExpiredDateDetails = tblStockOpnameItemExpiredDateDetails;
        this.tblItemMutationHistoryItemExpiredDates = tblItemMutationHistoryItemExpiredDates;
        this.tblStockOpnameDetailItemExpiredDates = tblStockOpnameDetailItemExpiredDates;
        this.tblItemLocationItemExpiredDates = tblItemLocationItemExpiredDates;
        this.tblReturDetailItemExpiredDates = tblReturDetailItemExpiredDates;
        this.tblStockOpnameDetails = tblStockOpnameDetails;
        this.tblMemorandumInvoiceDetailItemExpiredDates = tblMemorandumInvoiceDetailItemExpiredDates;
    }

    public TblItemExpiredDate(TblItemExpiredDate tblItemExpiredDate) {
        this();
        iditemExpiredDateProperty().set(tblItemExpiredDate.getIditemExpiredDate());
        refRecordStatusProperty().set(tblItemExpiredDate.getRefRecordStatus());
        tblEmployeeByCreateByProperty().set(tblItemExpiredDate.getTblEmployeeByCreateBy());
        tblEmployeeByLastUdapteByProperty().set(tblItemExpiredDate.getTblEmployeeByLastUdapteBy());
        tblItemProperty().set(tblItemExpiredDate.getTblItem());
        codeItemExpiredDateProperty().set(tblItemExpiredDate.getCodeItemExpiredDate());
        itemExpiredDateProperty().set(tblItemExpiredDate.getItemExpiredDate());
        noteProperty().set(tblItemExpiredDate.getNote());
        createDateProperty().set(tblItemExpiredDate.getCreateDate());
        lastUpdateDateProperty().set(tblItemExpiredDate.getLastUpdateDate());

        this.tblStockOpnameItemExpiredDateDetails = tblItemExpiredDate.getTblStockOpnameItemExpiredDateDetails();
        this.tblItemMutationHistoryItemExpiredDates = tblItemExpiredDate.getTblItemMutationHistoryItemExpiredDates();
        this.tblStockOpnameDetailItemExpiredDates = tblItemExpiredDate.getTblStockOpnameDetailItemExpiredDates();
        this.tblItemLocationItemExpiredDates = tblItemExpiredDate.getTblItemLocationItemExpiredDates();
        this.tblReturDetailItemExpiredDates = tblItemExpiredDate.getTblReturDetailItemExpiredDates();
        this.tblStockOpnameDetails = tblItemExpiredDate.getTblStockOpnameDetails();
        this.tblMemorandumInvoiceDetailItemExpiredDates = tblItemExpiredDate.getTblMemorandumInvoiceDetailItemExpiredDates();
    }

    public final LongProperty iditemExpiredDateProperty() {
        return this.iditemExpiredDate;
    }

    public long getIditemExpiredDate() {
        return iditemExpiredDateProperty().get();
    }

    public void setIditemExpiredDate(long iditemExpiredDate) {
        iditemExpiredDateProperty().set(iditemExpiredDate);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUdapteByProperty() {
        return this.tblEmployeeByLastUdapteBy;
    }

    public TblEmployee getTblEmployeeByLastUdapteBy() {
        return tblEmployeeByLastUdapteByProperty().get();
    }

    public void setTblEmployeeByLastUdapteBy(TblEmployee tblEmployeeByLastUdapteBy) {
        tblEmployeeByLastUdapteByProperty().set(tblEmployeeByLastUdapteBy);
    }

    public final ObjectProperty<TblItem> tblItemProperty() {
        return this.tblItem;
    }

    public TblItem getTblItem() {
        return tblItemProperty().get();
    }

    public void setTblItem(TblItem tblItem) {
        tblItemProperty().set(tblItem);
    }

    public final StringProperty codeItemExpiredDateProperty() {
        return this.codeItemExpiredDate;
    }

    public String getCodeItemExpiredDate() {
        return codeItemExpiredDateProperty().get();
    }

    public void setCodeItemExpiredDate(String codeItemExpiredDate) {
        codeItemExpiredDateProperty().set(codeItemExpiredDate);
    }

    public final ObjectProperty<Date> itemExpiredDateProperty() {
        return this.itemExpiredDate;
    }

    public Date getItemExpiredDate() {
        return itemExpiredDateProperty().get();
    }

    public void setItemExpiredDate(Date itemExpiredDate) {
        itemExpiredDateProperty().set(itemExpiredDate);
    }

    public final StringProperty noteProperty() {
        return this.note;
    }

    public String getNote() {
        return noteProperty().get();
    }

    public void setNote(String note) {
        noteProperty().set(note);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

    public Set getTblStockOpnameItemExpiredDateDetails() {
        return this.tblStockOpnameItemExpiredDateDetails;
    }

    public void setTblStockOpnameItemExpiredDateDetails(Set tblStockOpnameItemExpiredDateDetails) {
        this.tblStockOpnameItemExpiredDateDetails = tblStockOpnameItemExpiredDateDetails;
    }

    public Set getTblItemMutationHistoryItemExpiredDates() {
        return this.tblItemMutationHistoryItemExpiredDates;
    }

    public void setTblItemMutationHistoryItemExpiredDates(Set tblItemMutationHistoryItemExpiredDates) {
        this.tblItemMutationHistoryItemExpiredDates = tblItemMutationHistoryItemExpiredDates;
    }

    public Set getTblStockOpnameDetailItemExpiredDates() {
        return this.tblStockOpnameDetailItemExpiredDates;
    }

    public void setTblStockOpnameDetailItemExpiredDates(Set tblStockOpnameDetailItemExpiredDates) {
        this.tblStockOpnameDetailItemExpiredDates = tblStockOpnameDetailItemExpiredDates;
    }

    public Set getTblItemLocationItemExpiredDates() {
        return this.tblItemLocationItemExpiredDates;
    }

    public void setTblItemLocationItemExpiredDates(Set tblItemLocationItemExpiredDates) {
        this.tblItemLocationItemExpiredDates = tblItemLocationItemExpiredDates;
    }

    public Set getTblReturDetailItemExpiredDates() {
        return this.tblReturDetailItemExpiredDates;
    }

    public void setTblReturDetailItemExpiredDates(Set tblReturDetailItemExpiredDates) {
        this.tblReturDetailItemExpiredDates = tblReturDetailItemExpiredDates;
    }

    public Set getTblStockOpnameDetails() {
        return this.tblStockOpnameDetails;
    }

    public void setTblStockOpnameDetails(Set tblStockOpnameDetails) {
        this.tblStockOpnameDetails = tblStockOpnameDetails;
    }

    public Set getTblMemorandumInvoiceDetailItemExpiredDates() {
        return this.tblMemorandumInvoiceDetailItemExpiredDates;
    }

    public void setTblMemorandumInvoiceDetailItemExpiredDates(Set tblMemorandumInvoiceDetailItemExpiredDates) {
        this.tblMemorandumInvoiceDetailItemExpiredDates = tblMemorandumInvoiceDetailItemExpiredDates;
    }

    @Override
    public String toString(){
        return getItemExpiredDate() != null ? ClassFormatter.dateFormate.format(getItemExpiredDate()) : "";
    }
    
}
