package hotelfx.persistence.model;
// Generated Aug 30, 2018 10:38:05 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javafx.beans.property.IntegerProperty;
import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleIntegerProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblJob generated by hbm2java
 */
public class TblJob implements java.io.Serializable {

    private final LongProperty idjob;
    private final ObjectProperty<RefJobRecruitmentShowStatus> refJobRecruitmentShowStatus;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final StringProperty codeJob;
    private final StringProperty jobName;
    private final IntegerProperty serviceChargeWeight;
    private final StringProperty jobNote;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    private Set tblApprovalJobPrivilages;
    private Set tblApplicantsForApplymentJob2;
    private Set tblApplicantsForApplymentJob1;
    private Set tblEmployees;
    private Set tblApprovalJobRequireds;
    private Set tblSystemLogBookJobs;
    private Set tblEmployeeSalaryHistories;

    public TblJob() {
        this.idjob = new SimpleLongProperty();
        this.refJobRecruitmentShowStatus = new SimpleObjectProperty<>();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.codeJob = new SimpleStringProperty();
        this.jobName = new SimpleStringProperty();
        this.serviceChargeWeight = new SimpleIntegerProperty();
        this.jobNote = new SimpleStringProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

        this.tblApprovalJobPrivilages = new HashSet(0);
        this.tblApplicantsForApplymentJob2 = new HashSet(0);
        this.tblApplicantsForApplymentJob1 = new HashSet(0);
        this.tblEmployees = new HashSet(0);
        this.tblApprovalJobRequireds = new HashSet(0);
        this.tblSystemLogBookJobs = new HashSet(0);
        this.tblEmployeeSalaryHistories = new HashSet(0);
    }

    public TblJob(long idjob) {
        this();
        idjobProperty().set(idjob);
    }

    public TblJob(long idjob, RefJobRecruitmentShowStatus refJobRecruitmentShowStatus, RefRecordStatus refRecordStatus, TblEmployee tblEmployeeByLastUpdateBy, TblEmployee tblEmployeeByCreateBy, String codeJob, String jobName, Integer serviceChargeWeight, String jobNote, Date createDate, Date lastUpdateDate, Set tblApprovalJobPrivilages, Set tblApplicantsForApplymentJob2, Set tblApplicantsForApplymentJob1, Set tblEmployees, Set tblApprovalJobRequireds, Set tblSystemLogBookJobs, Set tblEmployeeSalaryHistories) {
        this();
        idjobProperty().set(idjob);
        refJobRecruitmentShowStatusProperty().set(refJobRecruitmentShowStatus);
        refRecordStatusProperty().set(refRecordStatus);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        codeJobProperty().set(codeJob);
        jobNameProperty().set(jobName);
        serviceChargeWeightProperty().set(serviceChargeWeight);
        jobNoteProperty().set(jobNote);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

        this.tblApprovalJobPrivilages = tblApprovalJobPrivilages;
        this.tblApplicantsForApplymentJob2 = tblApplicantsForApplymentJob2;
        this.tblApplicantsForApplymentJob1 = tblApplicantsForApplymentJob1;
        this.tblEmployees = tblEmployees;
        this.tblApprovalJobRequireds = tblApprovalJobRequireds;
        this.tblSystemLogBookJobs = tblSystemLogBookJobs;
        this.tblEmployeeSalaryHistories = tblEmployeeSalaryHistories;
    }

    public TblJob(TblJob tblJob) {
        this();
        idjobProperty().set(tblJob.getIdjob());
        refJobRecruitmentShowStatusProperty().set(tblJob.getRefJobRecruitmentShowStatus());
        refRecordStatusProperty().set(tblJob.getRefRecordStatus());
        tblEmployeeByLastUpdateByProperty().set(tblJob.getTblEmployeeByLastUpdateBy());
        tblEmployeeByCreateByProperty().set(tblJob.getTblEmployeeByCreateBy());
        codeJobProperty().set(tblJob.getCodeJob());
        jobNameProperty().set(tblJob.getJobName());
        serviceChargeWeightProperty().set(tblJob.getServiceChargeWeight());
        jobNoteProperty().set(tblJob.getJobNote());
        createDateProperty().set(tblJob.getCreateDate());
        lastUpdateDateProperty().set(tblJob.getLastUpdateDate());

        this.tblApprovalJobPrivilages = tblJob.getTblApprovalJobPrivilages();
        this.tblApplicantsForApplymentJob2 = tblJob.getTblApplicantsForApplymentJob2();
        this.tblApplicantsForApplymentJob1 = tblJob.getTblApplicantsForApplymentJob1();
        this.tblEmployees = tblJob.getTblEmployees();
        this.tblApprovalJobRequireds = tblJob.getTblApprovalJobRequireds();
        this.tblSystemLogBookJobs = tblJob.getTblSystemLogBookJobs();
        this.tblEmployeeSalaryHistories = tblJob.getTblEmployeeSalaryHistories();
    }

    public final LongProperty idjobProperty() {
        return this.idjob;
    }

    public long getIdjob() {
        return idjobProperty().get();
    }

    public void setIdjob(long idjob) {
        idjobProperty().set(idjob);
    }

    public final ObjectProperty<RefJobRecruitmentShowStatus> refJobRecruitmentShowStatusProperty() {
        return this.refJobRecruitmentShowStatus;
    }

    public RefJobRecruitmentShowStatus getRefJobRecruitmentShowStatus() {
        return refJobRecruitmentShowStatusProperty().get();
    }

    public void setRefJobRecruitmentShowStatus(RefJobRecruitmentShowStatus refJobRecruitmentShowStatus) {
        refJobRecruitmentShowStatusProperty().set(refJobRecruitmentShowStatus);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final StringProperty codeJobProperty() {
        return this.codeJob;
    }

    public String getCodeJob() {
        return codeJobProperty().get();
    }

    public void setCodeJob(String codeJob) {
        codeJobProperty().set(codeJob);
    }

    public final StringProperty jobNameProperty() {
        return this.jobName;
    }

    public String getJobName() {
        return jobNameProperty().get();
    }

    public void setJobName(String jobName) {
        jobNameProperty().set(jobName);
    }

    public final IntegerProperty serviceChargeWeightProperty() {
        return this.serviceChargeWeight;
    }

    public Integer getServiceChargeWeight() {
        return serviceChargeWeightProperty().get();
    }

    public void setServiceChargeWeight(Integer serviceChargeWeight) {
        serviceChargeWeightProperty().set(serviceChargeWeight);
    }

    public final StringProperty jobNoteProperty() {
        return this.jobNote;
    }

    public String getJobNote() {
        return jobNoteProperty().get();
    }

    public void setJobNote(String jobNote) {
        jobNoteProperty().set(jobNote);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

    public Set getTblApprovalJobPrivilages() {
        return this.tblApprovalJobPrivilages;
    }

    public void setTblApprovalJobPrivilages(Set tblApprovalJobPrivilages) {
        this.tblApprovalJobPrivilages = tblApprovalJobPrivilages;
    }

    public Set getTblApplicantsForApplymentJob2() {
        return this.tblApplicantsForApplymentJob2;
    }

    public void setTblApplicantsForApplymentJob2(Set tblApplicantsForApplymentJob2) {
        this.tblApplicantsForApplymentJob2 = tblApplicantsForApplymentJob2;
    }

    public Set getTblApplicantsForApplymentJob1() {
        return this.tblApplicantsForApplymentJob1;
    }

    public void setTblApplicantsForApplymentJob1(Set tblApplicantsForApplymentJob1) {
        this.tblApplicantsForApplymentJob1 = tblApplicantsForApplymentJob1;
    }

    public Set getTblEmployees() {
        return this.tblEmployees;
    }

    public void setTblEmployees(Set tblEmployees) {
        this.tblEmployees = tblEmployees;
    }

    public Set getTblApprovalJobRequireds() {
        return this.tblApprovalJobRequireds;
    }

    public void setTblApprovalJobRequireds(Set tblApprovalJobRequireds) {
        this.tblApprovalJobRequireds = tblApprovalJobRequireds;
    }

    public Set getTblSystemLogBookJobs() {
        return this.tblSystemLogBookJobs;
    }

    public void setTblSystemLogBookJobs(Set tblSystemLogBookJobs) {
        this.tblSystemLogBookJobs = tblSystemLogBookJobs;
    }

    public Set getTblEmployeeSalaryHistories() {
        return this.tblEmployeeSalaryHistories;
    }

    public void setTblEmployeeSalaryHistories(Set tblEmployeeSalaryHistories) {
        this.tblEmployeeSalaryHistories = tblEmployeeSalaryHistories;
    }

    @Override
    public String toString() {
        return getJobName();
    }
    
}
