package hotelfx.persistence.model;
// Generated Mar 29, 2018 3:28:56 PM by Hibernate Tools 4.3.1

import java.util.Date;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblLostFoundInformationDetail generated by hbm2java
 */
public class TblLostFoundInformationDetail implements java.io.Serializable {

    private final LongProperty idrelation;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByUpdatedBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreatedBy;
    private final ObjectProperty<TblFoundInformation> tblFoundInformation;
    private final ObjectProperty<TblLostInformation> tblLostInformation;
    private final StringProperty returnName;
    private final StringProperty returnAddress;
    private final StringProperty returnPhone;
    private final ObjectProperty<Date> returnDate;
    private final StringProperty note;
    private final ObjectProperty<Date> createdDate;
    private final ObjectProperty<Date> updatedDate;

    public TblLostFoundInformationDetail() {
        this.idrelation = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByUpdatedBy = new SimpleObjectProperty<>();
        this.tblEmployeeByCreatedBy = new SimpleObjectProperty<>();
        this.tblFoundInformation = new SimpleObjectProperty<>();
        this.tblLostInformation = new SimpleObjectProperty<>();
        this.returnName = new SimpleStringProperty();
        this.returnAddress = new SimpleStringProperty();
        this.returnPhone = new SimpleStringProperty();
        this.returnDate = new SimpleObjectProperty<>();
        this.note = new SimpleStringProperty();
        this.createdDate = new SimpleObjectProperty<>();
        this.updatedDate = new SimpleObjectProperty<>();

    }

    public TblLostFoundInformationDetail(long idrelation) {
        this();
        idrelationProperty().set(idrelation);
    }

    public TblLostFoundInformationDetail(long idrelation, RefRecordStatus refRecordStatus, TblEmployee tblEmployeeByUpdatedBy, TblEmployee tblEmployeeByCreatedBy, TblFoundInformation tblFoundInformation, TblLostInformation tblLostInformation, String returnName, String returnAddress, String returnPhone, Date returnDate, String note, Date createdDate, Date updatedDate) {
        this();
        idrelationProperty().set(idrelation);
        refRecordStatusProperty().set(refRecordStatus);
        tblEmployeeByUpdatedByProperty().set(tblEmployeeByUpdatedBy);
        tblEmployeeByCreatedByProperty().set(tblEmployeeByCreatedBy);
        tblFoundInformationProperty().set(tblFoundInformation);
        tblLostInformationProperty().set(tblLostInformation);
        returnNameProperty().set(returnName);
        returnAddressProperty().set(returnAddress);
        returnPhoneProperty().set(returnPhone);
        returnDateProperty().set(returnDate);
        noteProperty().set(note);
        createdDateProperty().set(createdDate);
        updatedDateProperty().set(updatedDate);

    }

    public TblLostFoundInformationDetail(TblLostFoundInformationDetail tblLostFoundInformationDetail) {
        this();
        idrelationProperty().set(tblLostFoundInformationDetail.getIdrelation());
        refRecordStatusProperty().set(tblLostFoundInformationDetail.getRefRecordStatus());
        tblEmployeeByUpdatedByProperty().set(tblLostFoundInformationDetail.getTblEmployeeByUpdatedBy());
        tblEmployeeByCreatedByProperty().set(tblLostFoundInformationDetail.getTblEmployeeByCreatedBy());
        tblFoundInformationProperty().set(tblLostFoundInformationDetail.getTblFoundInformation());
        tblLostInformationProperty().set(tblLostFoundInformationDetail.getTblLostInformation());
        returnNameProperty().set(tblLostFoundInformationDetail.getReturnName());
        returnAddressProperty().set(tblLostFoundInformationDetail.getReturnAddress());
        returnPhoneProperty().set(tblLostFoundInformationDetail.getReturnPhone());
        returnDateProperty().set(tblLostFoundInformationDetail.getReturnDate());
        noteProperty().set(tblLostFoundInformationDetail.getNote());
        createdDateProperty().set(tblLostFoundInformationDetail.getCreatedDate());
        updatedDateProperty().set(tblLostFoundInformationDetail.getUpdatedDate());

    }

    public final LongProperty idrelationProperty() {
        return this.idrelation;
    }

    public long getIdrelation() {
        return idrelationProperty().get();
    }

    public void setIdrelation(long idrelation) {
        idrelationProperty().set(idrelation);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByUpdatedByProperty() {
        return this.tblEmployeeByUpdatedBy;
    }

    public TblEmployee getTblEmployeeByUpdatedBy() {
        return tblEmployeeByUpdatedByProperty().get();
    }

    public void setTblEmployeeByUpdatedBy(TblEmployee tblEmployeeByUpdatedBy) {
        tblEmployeeByUpdatedByProperty().set(tblEmployeeByUpdatedBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreatedByProperty() {
        return this.tblEmployeeByCreatedBy;
    }

    public TblEmployee getTblEmployeeByCreatedBy() {
        return tblEmployeeByCreatedByProperty().get();
    }

    public void setTblEmployeeByCreatedBy(TblEmployee tblEmployeeByCreatedBy) {
        tblEmployeeByCreatedByProperty().set(tblEmployeeByCreatedBy);
    }

    public final ObjectProperty<TblFoundInformation> tblFoundInformationProperty() {
        return this.tblFoundInformation;
    }

    public TblFoundInformation getTblFoundInformation() {
        return tblFoundInformationProperty().get();
    }

    public void setTblFoundInformation(TblFoundInformation tblFoundInformation) {
        tblFoundInformationProperty().set(tblFoundInformation);
    }

    public final ObjectProperty<TblLostInformation> tblLostInformationProperty() {
        return this.tblLostInformation;
    }

    public TblLostInformation getTblLostInformation() {
        return tblLostInformationProperty().get();
    }

    public void setTblLostInformation(TblLostInformation tblLostInformation) {
        tblLostInformationProperty().set(tblLostInformation);
    }

    public final StringProperty returnNameProperty() {
        return this.returnName;
    }

    public String getReturnName() {
        return returnNameProperty().get();
    }

    public void setReturnName(String returnName) {
        returnNameProperty().set(returnName);
    }

    public final StringProperty returnAddressProperty() {
        return this.returnAddress;
    }

    public String getReturnAddress() {
        return returnAddressProperty().get();
    }

    public void setReturnAddress(String returnAddress) {
        returnAddressProperty().set(returnAddress);
    }

    public final StringProperty returnPhoneProperty() {
        return this.returnPhone;
    }

    public String getReturnPhone() {
        return returnPhoneProperty().get();
    }

    public void setReturnPhone(String returnPhone) {
        returnPhoneProperty().set(returnPhone);
    }

    public final ObjectProperty<Date> returnDateProperty() {
        return this.returnDate;
    }

    public Date getReturnDate() {
        return returnDateProperty().get();
    }

    public void setReturnDate(Date returnDate) {
        returnDateProperty().set(returnDate);
    }

    public final StringProperty noteProperty() {
        return this.note;
    }

    public String getNote() {
        return noteProperty().get();
    }

    public void setNote(String note) {
        noteProperty().set(note);
    }

    public final ObjectProperty<Date> createdDateProperty() {
        return this.createdDate;
    }

    public Date getCreatedDate() {
        return createdDateProperty().get();
    }

    public void setCreatedDate(Date createdDate) {
        createdDateProperty().set(createdDate);
    }

    public final ObjectProperty<Date> updatedDateProperty() {
        return this.updatedDate;
    }

    public Date getUpdatedDate() {
        return updatedDateProperty().get();
    }

    public void setUpdatedDate(Date updatedDate) {
        updatedDateProperty().set(updatedDate);
    }

}
