package hotelfx.persistence.model;
// Generated Aug 21, 2017 1:49:32 PM by Hibernate Tools 4.3.1

import java.util.Date;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblLocationOfBin generated by hbm2java
 */
public class TblLocationOfBin implements java.io.Serializable {

    private final LongProperty idbin;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblLocation> tblLocation;
    private final StringProperty binName;
    private final StringProperty binNote;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    public TblLocationOfBin() {
        this.idbin = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblLocation = new SimpleObjectProperty<>();
        this.binName = new SimpleStringProperty();
        this.binNote = new SimpleStringProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

    }

    public TblLocationOfBin(long idbin, TblLocation tblLocation) {
        this();
        idbinProperty().set(idbin);
        tblLocationProperty().set(tblLocation);
    }

    public TblLocationOfBin(long idbin, RefRecordStatus refRecordStatus, TblEmployee tblEmployeeByCreateBy, TblEmployee tblEmployeeByLastUpdateBy, TblLocation tblLocation, String binName, String binNote, Date createDate, Date lastUpdateDate) {
        this();
        idbinProperty().set(idbin);
        refRecordStatusProperty().set(refRecordStatus);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblLocationProperty().set(tblLocation);
        binNameProperty().set(binName);
        binNoteProperty().set(binNote);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

    }

    public TblLocationOfBin(TblLocationOfBin tblLocationOfBin) {
        this();
        idbinProperty().set(tblLocationOfBin.getIdbin());
        refRecordStatusProperty().set(tblLocationOfBin.getRefRecordStatus());
        tblEmployeeByCreateByProperty().set(tblLocationOfBin.getTblEmployeeByCreateBy());
        tblEmployeeByLastUpdateByProperty().set(tblLocationOfBin.getTblEmployeeByLastUpdateBy());
        tblLocationProperty().set(tblLocationOfBin.getTblLocation());
        binNameProperty().set(tblLocationOfBin.getBinName());
        binNoteProperty().set(tblLocationOfBin.getBinNote());
        createDateProperty().set(tblLocationOfBin.getCreateDate());
        lastUpdateDateProperty().set(tblLocationOfBin.getLastUpdateDate());

    }

    public final LongProperty idbinProperty() {
        return this.idbin;
    }

    public long getIdbin() {
        return idbinProperty().get();
    }

    public void setIdbin(long idbin) {
        idbinProperty().set(idbin);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblLocation> tblLocationProperty() {
        return this.tblLocation;
    }

    public TblLocation getTblLocation() {
        return tblLocationProperty().get();
    }

    public void setTblLocation(TblLocation tblLocation) {
        tblLocationProperty().set(tblLocation);
    }

    public final StringProperty binNameProperty() {
        return this.binName;
    }

    public String getBinName() {
        return binNameProperty().get();
    }

    public void setBinName(String binName) {
        binNameProperty().set(binName);
    }

    public final StringProperty binNoteProperty() {
        return this.binNote;
    }

    public String getBinNote() {
        return binNoteProperty().get();
    }

    public void setBinNote(String binNote) {
        binNoteProperty().set(binNote);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }
    
    @Override
    public String toString(){
        return getBinName();
    }

}
