package hotelfx.persistence.model;
// Generated Aug 21, 2017 1:49:32 PM by Hibernate Tools 4.3.1

import java.util.Date;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblLocationOfWarehouse generated by hbm2java
 */
public class TblLocationOfWarehouse implements java.io.Serializable {

    private final LongProperty idwarehouse;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblLocation> tblLocation;
    private final StringProperty warehouseName;
    private final StringProperty warehouseNote;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    public TblLocationOfWarehouse() {
        this.idwarehouse = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblLocation = new SimpleObjectProperty<>();
        this.warehouseName = new SimpleStringProperty();
        this.warehouseNote = new SimpleStringProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

    }

    public TblLocationOfWarehouse(long idwarehouse, TblLocation tblLocation) {
        this();
        idwarehouseProperty().set(idwarehouse);
        tblLocationProperty().set(tblLocation);
    }

    public TblLocationOfWarehouse(long idwarehouse, RefRecordStatus refRecordStatus, TblEmployee tblEmployeeByCreateBy, TblEmployee tblEmployeeByLastUpdateBy, TblLocation tblLocation, String warehouseName, String warehouseNote, Date createDate, Date lastUpdateDate) {
        this();
        idwarehouseProperty().set(idwarehouse);
        refRecordStatusProperty().set(refRecordStatus);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblLocationProperty().set(tblLocation);
        warehouseNameProperty().set(warehouseName);
        warehouseNoteProperty().set(warehouseNote);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

    }

    public TblLocationOfWarehouse(TblLocationOfWarehouse tblLocationOfWarehouse) {
        this();
        idwarehouseProperty().set(tblLocationOfWarehouse.getIdwarehouse());
        refRecordStatusProperty().set(tblLocationOfWarehouse.getRefRecordStatus());
        tblEmployeeByCreateByProperty().set(tblLocationOfWarehouse.getTblEmployeeByCreateBy());
        tblEmployeeByLastUpdateByProperty().set(tblLocationOfWarehouse.getTblEmployeeByLastUpdateBy());
        tblLocationProperty().set(tblLocationOfWarehouse.getTblLocation());
        warehouseNameProperty().set(tblLocationOfWarehouse.getWarehouseName());
        warehouseNoteProperty().set(tblLocationOfWarehouse.getWarehouseNote());
        createDateProperty().set(tblLocationOfWarehouse.getCreateDate());
        lastUpdateDateProperty().set(tblLocationOfWarehouse.getLastUpdateDate());

    }

    public final LongProperty idwarehouseProperty() {
        return this.idwarehouse;
    }

    public long getIdwarehouse() {
        return idwarehouseProperty().get();
    }

    public void setIdwarehouse(long idwarehouse) {
        idwarehouseProperty().set(idwarehouse);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblLocation> tblLocationProperty() {
        return this.tblLocation;
    }

    public TblLocation getTblLocation() {
        return tblLocationProperty().get();
    }

    public void setTblLocation(TblLocation tblLocation) {
        tblLocationProperty().set(tblLocation);
    }

    public final StringProperty warehouseNameProperty() {
        return this.warehouseName;
    }

    public String getWarehouseName() {
        return warehouseNameProperty().get();
    }

    public void setWarehouseName(String warehouseName) {
        warehouseNameProperty().set(warehouseName);
    }

    public final StringProperty warehouseNoteProperty() {
        return this.warehouseNote;
    }

    public String getWarehouseNote() {
        return warehouseNoteProperty().get();
    }

    public void setWarehouseNote(String warehouseNote) {
        warehouseNoteProperty().set(warehouseNote);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

    @Override
    public String toString() {
        return getWarehouseName();
    }

}
