package hotelfx.persistence.model;
// Generated Oct 18, 2018 4:38:29 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblLocation generated by hbm2java
 */
public class TblLocation implements java.io.Serializable {

    private final LongProperty idlocation;
    private final ObjectProperty<RefLocationType> refLocationType;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblBuilding> tblBuilding;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblFloor> tblFloor;
    private final ObjectProperty<TblGroup> tblGroup;
    private final StringProperty codeLocation;
    private final StringProperty locationName;
    private final StringProperty locationNote;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    private Set tblInComingsForIdlocationDestination;
    private Set tblItemMutationHistoriesForIdlocationOfDestination;
    private Set tblMemorandumInvoiceDetails;
    private Set tblStockOpnames;
    private Set tblBrokenItemsForIdlocationDestination;
    private Set tblLocationOfBins;
    private Set tblFixedTangibleAssetLocations;
    private Set tblOutGoingsForIdlocationDestination;
    private Set tblBrokenItemsForIdlocationSource;
    private Set tblSuppliers;
    private Set tblLocationOfLaundries;
    private Set tblOutGoingsForIdlocationSource;
    private Set tblItemLocations;
    private Set tblReturDetails;
    private Set tblInComingsForIdlocationSource;
    private Set tblLocationOfWarehouses;
    private Set tblRooms;
    private Set tblStoreRequestsForIdlocationSource;
    private Set tblStoreRequestsForIdlocationDestination;
    private Set tblItemMutationHistoriesForIdlocationOfSource;

    public TblLocation() {
        this.idlocation = new SimpleLongProperty();
        this.refLocationType = new SimpleObjectProperty<>();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblBuilding = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblFloor = new SimpleObjectProperty<>();
        this.tblGroup = new SimpleObjectProperty<>();
        this.codeLocation = new SimpleStringProperty();
        this.locationName = new SimpleStringProperty();
        this.locationNote = new SimpleStringProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

        this.tblInComingsForIdlocationDestination = new HashSet(0);
        this.tblItemMutationHistoriesForIdlocationOfDestination = new HashSet(0);
        this.tblMemorandumInvoiceDetails = new HashSet(0);
        this.tblStockOpnames = new HashSet(0);
        this.tblBrokenItemsForIdlocationDestination = new HashSet(0);
        this.tblLocationOfBins = new HashSet(0);
        this.tblFixedTangibleAssetLocations = new HashSet(0);
        this.tblOutGoingsForIdlocationDestination = new HashSet(0);
        this.tblBrokenItemsForIdlocationSource = new HashSet(0);
        this.tblSuppliers = new HashSet(0);
        this.tblLocationOfLaundries = new HashSet(0);
        this.tblOutGoingsForIdlocationSource = new HashSet(0);
        this.tblItemLocations = new HashSet(0);
        this.tblReturDetails = new HashSet(0);
        this.tblInComingsForIdlocationSource = new HashSet(0);
        this.tblLocationOfWarehouses = new HashSet(0);
        this.tblRooms = new HashSet(0);
        this.tblStoreRequestsForIdlocationSource = new HashSet(0);
        this.tblStoreRequestsForIdlocationDestination = new HashSet(0);
        this.tblItemMutationHistoriesForIdlocationOfSource = new HashSet(0);
    }

    public TblLocation(long idlocation) {
        this();
        idlocationProperty().set(idlocation);
    }

    public TblLocation(long idlocation, RefLocationType refLocationType, RefRecordStatus refRecordStatus, TblBuilding tblBuilding, TblEmployee tblEmployeeByLastUpdateBy, TblEmployee tblEmployeeByCreateBy, TblFloor tblFloor, TblGroup tblGroup, String codeLocation, String locationName, String locationNote, Date createDate, Date lastUpdateDate, Set tblInComingsForIdlocationDestination, Set tblItemMutationHistoriesForIdlocationOfDestination, Set tblMemorandumInvoiceDetails, Set tblStockOpnames, Set tblBrokenItemsForIdlocationDestination, Set tblLocationOfBins, Set tblFixedTangibleAssetLocations, Set tblOutGoingsForIdlocationDestination, Set tblBrokenItemsForIdlocationSource, Set tblSuppliers, Set tblLocationOfLaundries, Set tblOutGoingsForIdlocationSource, Set tblItemLocations, Set tblReturDetails, Set tblInComingsForIdlocationSource, Set tblLocationOfWarehouses, Set tblRooms, Set tblStoreRequestsForIdlocationSource, Set tblStoreRequestsForIdlocationDestination, Set tblItemMutationHistoriesForIdlocationOfSource) {
        this();
        idlocationProperty().set(idlocation);
        refLocationTypeProperty().set(refLocationType);
        refRecordStatusProperty().set(refRecordStatus);
        tblBuildingProperty().set(tblBuilding);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblFloorProperty().set(tblFloor);
        tblGroupProperty().set(tblGroup);
        codeLocationProperty().set(codeLocation);
        locationNameProperty().set(locationName);
        locationNoteProperty().set(locationNote);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

        this.tblInComingsForIdlocationDestination = tblInComingsForIdlocationDestination;
        this.tblItemMutationHistoriesForIdlocationOfDestination = tblItemMutationHistoriesForIdlocationOfDestination;
        this.tblMemorandumInvoiceDetails = tblMemorandumInvoiceDetails;
        this.tblStockOpnames = tblStockOpnames;
        this.tblBrokenItemsForIdlocationDestination = tblBrokenItemsForIdlocationDestination;
        this.tblLocationOfBins = tblLocationOfBins;
        this.tblFixedTangibleAssetLocations = tblFixedTangibleAssetLocations;
        this.tblOutGoingsForIdlocationDestination = tblOutGoingsForIdlocationDestination;
        this.tblBrokenItemsForIdlocationSource = tblBrokenItemsForIdlocationSource;
        this.tblSuppliers = tblSuppliers;
        this.tblLocationOfLaundries = tblLocationOfLaundries;
        this.tblOutGoingsForIdlocationSource = tblOutGoingsForIdlocationSource;
        this.tblItemLocations = tblItemLocations;
        this.tblReturDetails = tblReturDetails;
        this.tblInComingsForIdlocationSource = tblInComingsForIdlocationSource;
        this.tblLocationOfWarehouses = tblLocationOfWarehouses;
        this.tblRooms = tblRooms;
        this.tblStoreRequestsForIdlocationSource = tblStoreRequestsForIdlocationSource;
        this.tblStoreRequestsForIdlocationDestination = tblStoreRequestsForIdlocationDestination;
        this.tblItemMutationHistoriesForIdlocationOfSource = tblItemMutationHistoriesForIdlocationOfSource;
    }

    public TblLocation(TblLocation tblLocation) {
        this();
        idlocationProperty().set(tblLocation.getIdlocation());
        refLocationTypeProperty().set(tblLocation.getRefLocationType());
        refRecordStatusProperty().set(tblLocation.getRefRecordStatus());
        tblBuildingProperty().set(tblLocation.getTblBuilding());
        tblEmployeeByLastUpdateByProperty().set(tblLocation.getTblEmployeeByLastUpdateBy());
        tblEmployeeByCreateByProperty().set(tblLocation.getTblEmployeeByCreateBy());
        tblFloorProperty().set(tblLocation.getTblFloor());
        tblGroupProperty().set(tblLocation.getTblGroup());
        codeLocationProperty().set(tblLocation.getCodeLocation());
        locationNameProperty().set(tblLocation.getLocationName());
        locationNoteProperty().set(tblLocation.getLocationNote());
        createDateProperty().set(tblLocation.getCreateDate());
        lastUpdateDateProperty().set(tblLocation.getLastUpdateDate());

        this.tblInComingsForIdlocationDestination = tblLocation.getTblInComingsForIdlocationDestination();
        this.tblItemMutationHistoriesForIdlocationOfDestination = tblLocation.getTblItemMutationHistoriesForIdlocationOfDestination();
        this.tblMemorandumInvoiceDetails = tblLocation.getTblMemorandumInvoiceDetails();
        this.tblStockOpnames = tblLocation.getTblStockOpnames();
        this.tblBrokenItemsForIdlocationDestination = tblLocation.getTblBrokenItemsForIdlocationDestination();
        this.tblLocationOfBins = tblLocation.getTblLocationOfBins();
        this.tblFixedTangibleAssetLocations = tblLocation.getTblFixedTangibleAssetLocations();
        this.tblOutGoingsForIdlocationDestination = tblLocation.getTblOutGoingsForIdlocationDestination();
        this.tblBrokenItemsForIdlocationSource = tblLocation.getTblBrokenItemsForIdlocationSource();
        this.tblSuppliers = tblLocation.getTblSuppliers();
        this.tblLocationOfLaundries = tblLocation.getTblLocationOfLaundries();
        this.tblOutGoingsForIdlocationSource = tblLocation.getTblOutGoingsForIdlocationSource();
        this.tblItemLocations = tblLocation.getTblItemLocations();
        this.tblReturDetails = tblLocation.getTblReturDetails();
        this.tblInComingsForIdlocationSource = tblLocation.getTblInComingsForIdlocationSource();
        this.tblLocationOfWarehouses = tblLocation.getTblLocationOfWarehouses();
        this.tblRooms = tblLocation.getTblRooms();
        this.tblStoreRequestsForIdlocationSource = tblLocation.getTblStoreRequestsForIdlocationSource();
        this.tblStoreRequestsForIdlocationDestination = tblLocation.getTblStoreRequestsForIdlocationDestination();
        this.tblItemMutationHistoriesForIdlocationOfSource = tblLocation.getTblItemMutationHistoriesForIdlocationOfSource();
    }

    public final LongProperty idlocationProperty() {
        return this.idlocation;
    }

    public long getIdlocation() {
        return idlocationProperty().get();
    }

    public void setIdlocation(long idlocation) {
        idlocationProperty().set(idlocation);
    }

    public final ObjectProperty<RefLocationType> refLocationTypeProperty() {
        return this.refLocationType;
    }

    public RefLocationType getRefLocationType() {
        return refLocationTypeProperty().get();
    }

    public void setRefLocationType(RefLocationType refLocationType) {
        refLocationTypeProperty().set(refLocationType);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblBuilding> tblBuildingProperty() {
        return this.tblBuilding;
    }

    public TblBuilding getTblBuilding() {
        return tblBuildingProperty().get();
    }

    public void setTblBuilding(TblBuilding tblBuilding) {
        tblBuildingProperty().set(tblBuilding);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblFloor> tblFloorProperty() {
        return this.tblFloor;
    }

    public TblFloor getTblFloor() {
        return tblFloorProperty().get();
    }

    public void setTblFloor(TblFloor tblFloor) {
        tblFloorProperty().set(tblFloor);
    }

    public final ObjectProperty<TblGroup> tblGroupProperty() {
        return this.tblGroup;
    }

    public TblGroup getTblGroup() {
        return tblGroupProperty().get();
    }

    public void setTblGroup(TblGroup tblGroup) {
        tblGroupProperty().set(tblGroup);
    }

    public final StringProperty codeLocationProperty() {
        return this.codeLocation;
    }

    public String getCodeLocation() {
        return codeLocationProperty().get();
    }

    public void setCodeLocation(String codeLocation) {
        codeLocationProperty().set(codeLocation);
    }

    public final StringProperty locationNameProperty() {
        return this.locationName;
    }

    public String getLocationName() {
        return locationNameProperty().get();
    }

    public void setLocationName(String locationName) {
        locationNameProperty().set(locationName);
    }

    public final StringProperty locationNoteProperty() {
        return this.locationNote;
    }

    public String getLocationNote() {
        return locationNoteProperty().get();
    }

    public void setLocationNote(String locationNote) {
        locationNoteProperty().set(locationNote);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

    public Set getTblInComingsForIdlocationDestination() {
        return this.tblInComingsForIdlocationDestination;
    }

    public void setTblInComingsForIdlocationDestination(Set tblInComingsForIdlocationDestination) {
        this.tblInComingsForIdlocationDestination = tblInComingsForIdlocationDestination;
    }

    public Set getTblItemMutationHistoriesForIdlocationOfDestination() {
        return this.tblItemMutationHistoriesForIdlocationOfDestination;
    }

    public void setTblItemMutationHistoriesForIdlocationOfDestination(Set tblItemMutationHistoriesForIdlocationOfDestination) {
        this.tblItemMutationHistoriesForIdlocationOfDestination = tblItemMutationHistoriesForIdlocationOfDestination;
    }

    public Set getTblMemorandumInvoiceDetails() {
        return this.tblMemorandumInvoiceDetails;
    }

    public void setTblMemorandumInvoiceDetails(Set tblMemorandumInvoiceDetails) {
        this.tblMemorandumInvoiceDetails = tblMemorandumInvoiceDetails;
    }

    public Set getTblStockOpnames() {
        return this.tblStockOpnames;
    }

    public void setTblStockOpnames(Set tblStockOpnames) {
        this.tblStockOpnames = tblStockOpnames;
    }

    public Set getTblBrokenItemsForIdlocationDestination() {
        return this.tblBrokenItemsForIdlocationDestination;
    }

    public void setTblBrokenItemsForIdlocationDestination(Set tblBrokenItemsForIdlocationDestination) {
        this.tblBrokenItemsForIdlocationDestination = tblBrokenItemsForIdlocationDestination;
    }

    public Set getTblLocationOfBins() {
        return this.tblLocationOfBins;
    }

    public void setTblLocationOfBins(Set tblLocationOfBins) {
        this.tblLocationOfBins = tblLocationOfBins;
    }

    public Set getTblFixedTangibleAssetLocations() {
        return this.tblFixedTangibleAssetLocations;
    }

    public void setTblFixedTangibleAssetLocations(Set tblFixedTangibleAssetLocations) {
        this.tblFixedTangibleAssetLocations = tblFixedTangibleAssetLocations;
    }

    public Set getTblOutGoingsForIdlocationDestination() {
        return this.tblOutGoingsForIdlocationDestination;
    }

    public void setTblOutGoingsForIdlocationDestination(Set tblOutGoingsForIdlocationDestination) {
        this.tblOutGoingsForIdlocationDestination = tblOutGoingsForIdlocationDestination;
    }

    public Set getTblBrokenItemsForIdlocationSource() {
        return this.tblBrokenItemsForIdlocationSource;
    }

    public void setTblBrokenItemsForIdlocationSource(Set tblBrokenItemsForIdlocationSource) {
        this.tblBrokenItemsForIdlocationSource = tblBrokenItemsForIdlocationSource;
    }

    public Set getTblSuppliers() {
        return this.tblSuppliers;
    }

    public void setTblSuppliers(Set tblSuppliers) {
        this.tblSuppliers = tblSuppliers;
    }

    public Set getTblLocationOfLaundries() {
        return this.tblLocationOfLaundries;
    }

    public void setTblLocationOfLaundries(Set tblLocationOfLaundries) {
        this.tblLocationOfLaundries = tblLocationOfLaundries;
    }

    public Set getTblOutGoingsForIdlocationSource() {
        return this.tblOutGoingsForIdlocationSource;
    }

    public void setTblOutGoingsForIdlocationSource(Set tblOutGoingsForIdlocationSource) {
        this.tblOutGoingsForIdlocationSource = tblOutGoingsForIdlocationSource;
    }

    public Set getTblItemLocations() {
        return this.tblItemLocations;
    }

    public void setTblItemLocations(Set tblItemLocations) {
        this.tblItemLocations = tblItemLocations;
    }

    public Set getTblReturDetails() {
        return this.tblReturDetails;
    }

    public void setTblReturDetails(Set tblReturDetails) {
        this.tblReturDetails = tblReturDetails;
    }

    public Set getTblInComingsForIdlocationSource() {
        return this.tblInComingsForIdlocationSource;
    }

    public void setTblInComingsForIdlocationSource(Set tblInComingsForIdlocationSource) {
        this.tblInComingsForIdlocationSource = tblInComingsForIdlocationSource;
    }

    public Set getTblLocationOfWarehouses() {
        return this.tblLocationOfWarehouses;
    }

    public void setTblLocationOfWarehouses(Set tblLocationOfWarehouses) {
        this.tblLocationOfWarehouses = tblLocationOfWarehouses;
    }

    public Set getTblRooms() {
        return this.tblRooms;
    }

    public void setTblRooms(Set tblRooms) {
        this.tblRooms = tblRooms;
    }

    public Set getTblStoreRequestsForIdlocationSource() {
        return this.tblStoreRequestsForIdlocationSource;
    }

    public void setTblStoreRequestsForIdlocationSource(Set tblStoreRequestsForIdlocationSource) {
        this.tblStoreRequestsForIdlocationSource = tblStoreRequestsForIdlocationSource;
    }

    public Set getTblStoreRequestsForIdlocationDestination() {
        return this.tblStoreRequestsForIdlocationDestination;
    }

    public void setTblStoreRequestsForIdlocationDestination(Set tblStoreRequestsForIdlocationDestination) {
        this.tblStoreRequestsForIdlocationDestination = tblStoreRequestsForIdlocationDestination;
    }

    public Set getTblItemMutationHistoriesForIdlocationOfSource() {
        return this.tblItemMutationHistoriesForIdlocationOfSource;
    }

    public void setTblItemMutationHistoriesForIdlocationOfSource(Set tblItemMutationHistoriesForIdlocationOfSource) {
        this.tblItemMutationHistoriesForIdlocationOfSource = tblItemMutationHistoriesForIdlocationOfSource;
    }

    @Override
    public String toString() {
        return getLocationName();
    }
    
}
