package hotelfx.persistence.model;
// Generated Jul 2, 2018 2:28:37 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblMemorandumInvoiceDetail generated by hbm2java
 */
public class TblMemorandumInvoiceDetail implements java.io.Serializable {

    private final LongProperty iddetail;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblItem> tblItem;
    private final ObjectProperty<TblLocation> tblLocation;
    private final ObjectProperty<TblMemorandumInvoice> tblMemorandumInvoice;
    private final ObjectProperty<TblSupplierItem> tblSupplierItem;
    private final ObjectProperty<Date> itemExpiredDate;
    private final ObjectProperty<BigDecimal> itemCost;
    private final ObjectProperty<BigDecimal> itemQuantity;
    private final ObjectProperty<BigDecimal> itemDiscount;
    private final StringProperty itemNote;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    private Set tblMemorandumInvoiceDetailPropertyBarcodes;
    private Set tblMemorandumInvoiceDetailItemExpiredDates;

    public TblMemorandumInvoiceDetail() {
        this.iddetail = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblItem = new SimpleObjectProperty<>();
        this.tblLocation = new SimpleObjectProperty<>();
        this.tblMemorandumInvoice = new SimpleObjectProperty<>();
        this.tblSupplierItem = new SimpleObjectProperty<>();
        this.itemExpiredDate = new SimpleObjectProperty<>();
        this.itemCost = new SimpleObjectProperty<>();
        this.itemQuantity = new SimpleObjectProperty<>();
        this.itemDiscount = new SimpleObjectProperty<>();
        this.itemNote = new SimpleStringProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

        this.tblMemorandumInvoiceDetailPropertyBarcodes = new HashSet(0);
        this.tblMemorandumInvoiceDetailItemExpiredDates = new HashSet(0);
    }

    public TblMemorandumInvoiceDetail(long iddetail) {
        this();
        iddetailProperty().set(iddetail);
    }

    public TblMemorandumInvoiceDetail(long iddetail, RefRecordStatus refRecordStatus, TblEmployee tblEmployeeByCreateBy, TblEmployee tblEmployeeByLastUpdateBy, TblItem tblItem, TblLocation tblLocation, TblMemorandumInvoice tblMemorandumInvoice, TblSupplierItem tblSupplierItem, Date itemExpiredDate, BigDecimal itemCost, BigDecimal itemQuantity, BigDecimal itemDiscount, String itemNote, Date createDate, Date lastUpdateDate, Set tblMemorandumInvoiceDetailPropertyBarcodes, Set tblMemorandumInvoiceDetailItemExpiredDates) {
        this();
        iddetailProperty().set(iddetail);
        refRecordStatusProperty().set(refRecordStatus);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblItemProperty().set(tblItem);
        tblLocationProperty().set(tblLocation);
        tblMemorandumInvoiceProperty().set(tblMemorandumInvoice);
        tblSupplierItemProperty().set(tblSupplierItem);
        itemExpiredDateProperty().set(itemExpiredDate);
        itemCostProperty().set(itemCost);
        itemQuantityProperty().set(itemQuantity);
        itemDiscountProperty().set(itemDiscount);
        itemNoteProperty().set(itemNote);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

        this.tblMemorandumInvoiceDetailPropertyBarcodes = tblMemorandumInvoiceDetailPropertyBarcodes;
        this.tblMemorandumInvoiceDetailItemExpiredDates = tblMemorandumInvoiceDetailItemExpiredDates;
    }

    public TblMemorandumInvoiceDetail(TblMemorandumInvoiceDetail tblMemorandumInvoiceDetail) {
        this();
        iddetailProperty().set(tblMemorandumInvoiceDetail.getIddetail());
        refRecordStatusProperty().set(tblMemorandumInvoiceDetail.getRefRecordStatus());
        tblEmployeeByCreateByProperty().set(tblMemorandumInvoiceDetail.getTblEmployeeByCreateBy());
        tblEmployeeByLastUpdateByProperty().set(tblMemorandumInvoiceDetail.getTblEmployeeByLastUpdateBy());
        tblItemProperty().set(tblMemorandumInvoiceDetail.getTblItem());
        tblLocationProperty().set(tblMemorandumInvoiceDetail.getTblLocation());
        tblMemorandumInvoiceProperty().set(tblMemorandumInvoiceDetail.getTblMemorandumInvoice());
        tblSupplierItemProperty().set(tblMemorandumInvoiceDetail.getTblSupplierItem());
        itemExpiredDateProperty().set(tblMemorandumInvoiceDetail.getItemExpiredDate());
        itemCostProperty().set(tblMemorandumInvoiceDetail.getItemCost());
        itemQuantityProperty().set(tblMemorandumInvoiceDetail.getItemQuantity());
        itemDiscountProperty().set(tblMemorandumInvoiceDetail.getItemDiscount());
        itemNoteProperty().set(tblMemorandumInvoiceDetail.getItemNote());
        createDateProperty().set(tblMemorandumInvoiceDetail.getCreateDate());
        lastUpdateDateProperty().set(tblMemorandumInvoiceDetail.getLastUpdateDate());

        this.tblMemorandumInvoiceDetailPropertyBarcodes = tblMemorandumInvoiceDetail.getTblMemorandumInvoiceDetailPropertyBarcodes();
        this.tblMemorandumInvoiceDetailItemExpiredDates = tblMemorandumInvoiceDetail.getTblMemorandumInvoiceDetailItemExpiredDates();
    }

    public final LongProperty iddetailProperty() {
        return this.iddetail;
    }

    public long getIddetail() {
        return iddetailProperty().get();
    }

    public void setIddetail(long iddetail) {
        iddetailProperty().set(iddetail);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblItem> tblItemProperty() {
        return this.tblItem;
    }

    public TblItem getTblItem() {
        return tblItemProperty().get();
    }

    public void setTblItem(TblItem tblItem) {
        tblItemProperty().set(tblItem);
    }

    public final ObjectProperty<TblLocation> tblLocationProperty() {
        return this.tblLocation;
    }

    public TblLocation getTblLocation() {
        return tblLocationProperty().get();
    }

    public void setTblLocation(TblLocation tblLocation) {
        tblLocationProperty().set(tblLocation);
    }

    public final ObjectProperty<TblMemorandumInvoice> tblMemorandumInvoiceProperty() {
        return this.tblMemorandumInvoice;
    }

    public TblMemorandumInvoice getTblMemorandumInvoice() {
        return tblMemorandumInvoiceProperty().get();
    }

    public void setTblMemorandumInvoice(TblMemorandumInvoice tblMemorandumInvoice) {
        tblMemorandumInvoiceProperty().set(tblMemorandumInvoice);
    }

    public final ObjectProperty<TblSupplierItem> tblSupplierItemProperty() {
        return this.tblSupplierItem;
    }

    public TblSupplierItem getTblSupplierItem() {
        return tblSupplierItemProperty().get();
    }

    public void setTblSupplierItem(TblSupplierItem tblSupplierItem) {
        tblSupplierItemProperty().set(tblSupplierItem);
    }

    public final ObjectProperty<Date> itemExpiredDateProperty() {
        return this.itemExpiredDate;
    }

    public Date getItemExpiredDate() {
        return itemExpiredDateProperty().get();
    }

    public void setItemExpiredDate(Date itemExpiredDate) {
        itemExpiredDateProperty().set(itemExpiredDate);
    }

    public final ObjectProperty<BigDecimal> itemCostProperty() {
        return this.itemCost;
    }

    public BigDecimal getItemCost() {
        return itemCostProperty().get();
    }

    public void setItemCost(BigDecimal itemCost) {
        itemCostProperty().set(itemCost);
    }

    public final ObjectProperty<BigDecimal> itemQuantityProperty() {
        return this.itemQuantity;
    }

    public BigDecimal getItemQuantity() {
        return itemQuantityProperty().get();
    }

    public void setItemQuantity(BigDecimal itemQuantity) {
        itemQuantityProperty().set(itemQuantity);
    }

    public final ObjectProperty<BigDecimal> itemDiscountProperty() {
        return this.itemDiscount;
    }

    public BigDecimal getItemDiscount() {
        return itemDiscountProperty().get();
    }

    public void setItemDiscount(BigDecimal itemDiscount) {
        itemDiscountProperty().set(itemDiscount);
    }

    public final StringProperty itemNoteProperty() {
        return this.itemNote;
    }

    public String getItemNote() {
        return itemNoteProperty().get();
    }

    public void setItemNote(String itemNote) {
        itemNoteProperty().set(itemNote);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

    public Set getTblMemorandumInvoiceDetailPropertyBarcodes() {
        return this.tblMemorandumInvoiceDetailPropertyBarcodes;
    }

    public void setTblMemorandumInvoiceDetailPropertyBarcodes(Set tblMemorandumInvoiceDetailPropertyBarcodes) {
        this.tblMemorandumInvoiceDetailPropertyBarcodes = tblMemorandumInvoiceDetailPropertyBarcodes;
    }

    public Set getTblMemorandumInvoiceDetailItemExpiredDates() {
        return this.tblMemorandumInvoiceDetailItemExpiredDates;
    }

    public void setTblMemorandumInvoiceDetailItemExpiredDates(Set tblMemorandumInvoiceDetailItemExpiredDates) {
        this.tblMemorandumInvoiceDetailItemExpiredDates = tblMemorandumInvoiceDetailItemExpiredDates;
    }

}
