package hotelfx.persistence.model;
// Generated May 15, 2018 12:47:45 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblMemorandumInvoice generated by hbm2java
 */
public class TblMemorandumInvoice implements java.io.Serializable {

    private final LongProperty idmi;
    private final ObjectProperty<RefMemorandumInvoiceStatus> refMemorandumInvoiceStatus;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblApprovalData> tblApprovalData;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblFinanceData> tblFinanceData;
    private final ObjectProperty<TblPurchaseOrder> tblPurchaseOrder;
    private final ObjectProperty<TblSupplier> tblSupplier;
    private final StringProperty codeMi;
    private final ObjectProperty<Date> receivingDate;
    private final StringProperty deliveryNumber;
    private final StringProperty deliveryName;
    private final StringProperty receivingNote;
    private final ObjectProperty<Date> storingDate;
    private final ObjectProperty<Date> balancingCostDate;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    private Set tblMemorandumInvoiceDetails;
    private Set tblReturDetails;

    public TblMemorandumInvoice() {
        this.idmi = new SimpleLongProperty();
        this.refMemorandumInvoiceStatus = new SimpleObjectProperty<>();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblApprovalData = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblFinanceData = new SimpleObjectProperty<>();
        this.tblPurchaseOrder = new SimpleObjectProperty<>();
        this.tblSupplier = new SimpleObjectProperty<>();
        this.codeMi = new SimpleStringProperty();
        this.receivingDate = new SimpleObjectProperty<>();
        this.deliveryNumber = new SimpleStringProperty();
        this.deliveryName = new SimpleStringProperty();
        this.receivingNote = new SimpleStringProperty();
        this.storingDate = new SimpleObjectProperty<>();
        this.balancingCostDate = new SimpleObjectProperty<>();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

        this.tblMemorandumInvoiceDetails = new HashSet(0);
        this.tblReturDetails = new HashSet(0);
    }

    public TblMemorandumInvoice(long idmi) {
        this();
        idmiProperty().set(idmi);
    }

    public TblMemorandumInvoice(long idmi, RefMemorandumInvoiceStatus refMemorandumInvoiceStatus, RefRecordStatus refRecordStatus, TblApprovalData tblApprovalData, TblEmployee tblEmployeeByLastUpdateBy, TblEmployee tblEmployeeByCreateBy, TblFinanceData tblFinanceData, TblPurchaseOrder tblPurchaseOrder, TblSupplier tblSupplier, String codeMi, Date receivingDate, String deliveryNumber, String deliveryName, String receivingNote, Date storingDate, Date balancingCostDate, Date createDate, Date lastUpdateDate, Set tblMemorandumInvoiceDetails, Set tblReturDetails) {
        this();
        idmiProperty().set(idmi);
        refMemorandumInvoiceStatusProperty().set(refMemorandumInvoiceStatus);
        refRecordStatusProperty().set(refRecordStatus);
        tblApprovalDataProperty().set(tblApprovalData);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblFinanceDataProperty().set(tblFinanceData);
        tblPurchaseOrderProperty().set(tblPurchaseOrder);
        tblSupplierProperty().set(tblSupplier);
        codeMiProperty().set(codeMi);
        receivingDateProperty().set(receivingDate);
        deliveryNumberProperty().set(deliveryNumber);
        deliveryNameProperty().set(deliveryName);
        receivingNoteProperty().set(receivingNote);
        storingDateProperty().set(storingDate);
        balancingCostDateProperty().set(balancingCostDate);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

        this.tblMemorandumInvoiceDetails = tblMemorandumInvoiceDetails;
        this.tblReturDetails = tblReturDetails;
    }

    public TblMemorandumInvoice(TblMemorandumInvoice tblMemorandumInvoice) {
        this();
        idmiProperty().set(tblMemorandumInvoice.getIdmi());
        refMemorandumInvoiceStatusProperty().set(tblMemorandumInvoice.getRefMemorandumInvoiceStatus());
        refRecordStatusProperty().set(tblMemorandumInvoice.getRefRecordStatus());
        tblApprovalDataProperty().set(tblMemorandumInvoice.getTblApprovalData());
        tblEmployeeByLastUpdateByProperty().set(tblMemorandumInvoice.getTblEmployeeByLastUpdateBy());
        tblEmployeeByCreateByProperty().set(tblMemorandumInvoice.getTblEmployeeByCreateBy());
        tblFinanceDataProperty().set(tblMemorandumInvoice.getTblFinanceData());
        tblPurchaseOrderProperty().set(tblMemorandumInvoice.getTblPurchaseOrder());
        tblSupplierProperty().set(tblMemorandumInvoice.getTblSupplier());
        codeMiProperty().set(tblMemorandumInvoice.getCodeMi());
        receivingDateProperty().set(tblMemorandumInvoice.getReceivingDate());
        deliveryNumberProperty().set(tblMemorandumInvoice.getDeliveryNumber());
        deliveryNameProperty().set(tblMemorandumInvoice.getDeliveryName());
        receivingNoteProperty().set(tblMemorandumInvoice.getReceivingNote());
        storingDateProperty().set(tblMemorandumInvoice.getStoringDate());
        balancingCostDateProperty().set(tblMemorandumInvoice.getBalancingCostDate());
        createDateProperty().set(tblMemorandumInvoice.getCreateDate());
        lastUpdateDateProperty().set(tblMemorandumInvoice.getLastUpdateDate());

        this.tblMemorandumInvoiceDetails = tblMemorandumInvoice.getTblMemorandumInvoiceDetails();
        this.tblReturDetails = tblMemorandumInvoice.getTblReturDetails();
    }

    public final LongProperty idmiProperty() {
        return this.idmi;
    }

    public long getIdmi() {
        return idmiProperty().get();
    }

    public void setIdmi(long idmi) {
        idmiProperty().set(idmi);
    }

    public final ObjectProperty<RefMemorandumInvoiceStatus> refMemorandumInvoiceStatusProperty() {
        return this.refMemorandumInvoiceStatus;
    }

    public RefMemorandumInvoiceStatus getRefMemorandumInvoiceStatus() {
        return refMemorandumInvoiceStatusProperty().get();
    }

    public void setRefMemorandumInvoiceStatus(RefMemorandumInvoiceStatus refMemorandumInvoiceStatus) {
        refMemorandumInvoiceStatusProperty().set(refMemorandumInvoiceStatus);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblApprovalData> tblApprovalDataProperty() {
        return this.tblApprovalData;
    }

    public TblApprovalData getTblApprovalData() {
        return tblApprovalDataProperty().get();
    }

    public void setTblApprovalData(TblApprovalData tblApprovalData) {
        tblApprovalDataProperty().set(tblApprovalData);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblFinanceData> tblFinanceDataProperty() {
        return this.tblFinanceData;
    }

    public TblFinanceData getTblFinanceData() {
        return tblFinanceDataProperty().get();
    }

    public void setTblFinanceData(TblFinanceData tblFinanceData) {
        tblFinanceDataProperty().set(tblFinanceData);
    }

    public final ObjectProperty<TblPurchaseOrder> tblPurchaseOrderProperty() {
        return this.tblPurchaseOrder;
    }

    public TblPurchaseOrder getTblPurchaseOrder() {
        return tblPurchaseOrderProperty().get();
    }

    public void setTblPurchaseOrder(TblPurchaseOrder tblPurchaseOrder) {
        tblPurchaseOrderProperty().set(tblPurchaseOrder);
    }

    public final ObjectProperty<TblSupplier> tblSupplierProperty() {
        return this.tblSupplier;
    }

    public TblSupplier getTblSupplier() {
        return tblSupplierProperty().get();
    }

    public void setTblSupplier(TblSupplier tblSupplier) {
        tblSupplierProperty().set(tblSupplier);
    }

    public final StringProperty codeMiProperty() {
        return this.codeMi;
    }

    public String getCodeMi() {
        return codeMiProperty().get();
    }

    public void setCodeMi(String codeMi) {
        codeMiProperty().set(codeMi);
    }

    public final ObjectProperty<Date> receivingDateProperty() {
        return this.receivingDate;
    }

    public Date getReceivingDate() {
        return receivingDateProperty().get();
    }

    public void setReceivingDate(Date receivingDate) {
        receivingDateProperty().set(receivingDate);
    }

    public final StringProperty deliveryNumberProperty() {
        return this.deliveryNumber;
    }

    public String getDeliveryNumber() {
        return deliveryNumberProperty().get();
    }

    public void setDeliveryNumber(String deliveryNumber) {
        deliveryNumberProperty().set(deliveryNumber);
    }

    public final StringProperty deliveryNameProperty() {
        return this.deliveryName;
    }

    public String getDeliveryName() {
        return deliveryNameProperty().get();
    }

    public void setDeliveryName(String deliveryName) {
        deliveryNameProperty().set(deliveryName);
    }

    public final StringProperty receivingNoteProperty() {
        return this.receivingNote;
    }

    public String getReceivingNote() {
        return receivingNoteProperty().get();
    }

    public void setReceivingNote(String receivingNote) {
        receivingNoteProperty().set(receivingNote);
    }

    public final ObjectProperty<Date> storingDateProperty() {
        return this.storingDate;
    }

    public Date getStoringDate() {
        return storingDateProperty().get();
    }

    public void setStoringDate(Date storingDate) {
        storingDateProperty().set(storingDate);
    }

    public final ObjectProperty<Date> balancingCostDateProperty() {
        return this.balancingCostDate;
    }

    public Date getBalancingCostDate() {
        return balancingCostDateProperty().get();
    }

    public void setBalancingCostDate(Date balancingCostDate) {
        balancingCostDateProperty().set(balancingCostDate);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

    public Set getTblMemorandumInvoiceDetails() {
        return this.tblMemorandumInvoiceDetails;
    }

    public void setTblMemorandumInvoiceDetails(Set tblMemorandumInvoiceDetails) {
        this.tblMemorandumInvoiceDetails = tblMemorandumInvoiceDetails;
    }

    public Set getTblReturDetails() {
        return this.tblReturDetails;
    }

    public void setTblReturDetails(Set tblReturDetails) {
        this.tblReturDetails = tblReturDetails;
    }

    @Override
    public String toString() {
        return getCodeMi();
    }
    
}
