package hotelfx.persistence.model;
// Generated Sep 21, 2018 2:55:56 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;

/**
 * TblMemorandumInvoiceDetailItemExpiredDate generated by hbm2java
 */
public class TblMemorandumInvoiceDetailItemExpiredDate implements java.io.Serializable {

    private final LongProperty idrelation;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblItemExpiredDate> tblItemExpiredDate;
    private final ObjectProperty<TblMemorandumInvoiceDetail> tblMemorandumInvoiceDetail;
    private final ObjectProperty<BigDecimal> itemQuantity;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    public TblMemorandumInvoiceDetailItemExpiredDate() {
        this.idrelation = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblItemExpiredDate = new SimpleObjectProperty<>();
        this.tblMemorandumInvoiceDetail = new SimpleObjectProperty<>();
        this.itemQuantity = new SimpleObjectProperty<>();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

    }

    public TblMemorandumInvoiceDetailItemExpiredDate(long idrelation) {
        this();
        idrelationProperty().set(idrelation);
    }

    public TblMemorandumInvoiceDetailItemExpiredDate(long idrelation, RefRecordStatus refRecordStatus, TblEmployee tblEmployeeByCreateBy, TblEmployee tblEmployeeByLastUpdateBy, TblItemExpiredDate tblItemExpiredDate, TblMemorandumInvoiceDetail tblMemorandumInvoiceDetail, BigDecimal itemQuantity, Date createDate, Date lastUpdateDate) {
        this();
        idrelationProperty().set(idrelation);
        refRecordStatusProperty().set(refRecordStatus);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblItemExpiredDateProperty().set(tblItemExpiredDate);
        tblMemorandumInvoiceDetailProperty().set(tblMemorandumInvoiceDetail);
        itemQuantityProperty().set(itemQuantity);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

    }

    public TblMemorandumInvoiceDetailItemExpiredDate(TblMemorandumInvoiceDetailItemExpiredDate tblMemorandumInvoiceDetailItemExpiredDate) {
        this();
        idrelationProperty().set(tblMemorandumInvoiceDetailItemExpiredDate.getIdrelation());
        refRecordStatusProperty().set(tblMemorandumInvoiceDetailItemExpiredDate.getRefRecordStatus());
        tblEmployeeByCreateByProperty().set(tblMemorandumInvoiceDetailItemExpiredDate.getTblEmployeeByCreateBy());
        tblEmployeeByLastUpdateByProperty().set(tblMemorandumInvoiceDetailItemExpiredDate.getTblEmployeeByLastUpdateBy());
        tblItemExpiredDateProperty().set(tblMemorandumInvoiceDetailItemExpiredDate.getTblItemExpiredDate());
        tblMemorandumInvoiceDetailProperty().set(tblMemorandumInvoiceDetailItemExpiredDate.getTblMemorandumInvoiceDetail());
        itemQuantityProperty().set(tblMemorandumInvoiceDetailItemExpiredDate.getItemQuantity());
        createDateProperty().set(tblMemorandumInvoiceDetailItemExpiredDate.getCreateDate());
        lastUpdateDateProperty().set(tblMemorandumInvoiceDetailItemExpiredDate.getLastUpdateDate());

    }

    public final LongProperty idrelationProperty() {
        return this.idrelation;
    }

    public long getIdrelation() {
        return idrelationProperty().get();
    }

    public void setIdrelation(long idrelation) {
        idrelationProperty().set(idrelation);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblItemExpiredDate> tblItemExpiredDateProperty() {
        return this.tblItemExpiredDate;
    }

    public TblItemExpiredDate getTblItemExpiredDate() {
        return tblItemExpiredDateProperty().get();
    }

    public void setTblItemExpiredDate(TblItemExpiredDate tblItemExpiredDate) {
        tblItemExpiredDateProperty().set(tblItemExpiredDate);
    }

    public final ObjectProperty<TblMemorandumInvoiceDetail> tblMemorandumInvoiceDetailProperty() {
        return this.tblMemorandumInvoiceDetail;
    }

    public TblMemorandumInvoiceDetail getTblMemorandumInvoiceDetail() {
        return tblMemorandumInvoiceDetailProperty().get();
    }

    public void setTblMemorandumInvoiceDetail(TblMemorandumInvoiceDetail tblMemorandumInvoiceDetail) {
        tblMemorandumInvoiceDetailProperty().set(tblMemorandumInvoiceDetail);
    }

    public final ObjectProperty<BigDecimal> itemQuantityProperty() {
        return this.itemQuantity;
    }

    public BigDecimal getItemQuantity() {
        return itemQuantityProperty().get();
    }

    public void setItemQuantity(BigDecimal itemQuantity) {
        itemQuantityProperty().set(itemQuantity);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

}
