package hotelfx.persistence.model;
// Generated Oct 5, 2018 4:27:54 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblOutGoing generated by hbm2java
 */
public class TblOutGoing implements java.io.Serializable {

    private final LongProperty idog;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByIdreceiver;
    private final ObjectProperty<TblLocation> tblLocationByIdlocationDestination;
    private final ObjectProperty<TblLocation> tblLocationByIdlocationSource;
    private final ObjectProperty<TblStoreRequest> tblStoreRequest;
    private final StringProperty codeOg;
    private final ObjectProperty<Date> ogdate;
    private final StringProperty ognote;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    private Set tblOutGoingDetails;

    public TblOutGoing() {
        this.idog = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByIdreceiver = new SimpleObjectProperty<>();
        this.tblLocationByIdlocationDestination = new SimpleObjectProperty<>();
        this.tblLocationByIdlocationSource = new SimpleObjectProperty<>();
        this.tblStoreRequest = new SimpleObjectProperty<>();
        this.codeOg = new SimpleStringProperty();
        this.ogdate = new SimpleObjectProperty<>();
        this.ognote = new SimpleStringProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

        this.tblOutGoingDetails = new HashSet(0);
    }

    public TblOutGoing(long idog) {
        this();
        idogProperty().set(idog);
    }

    public TblOutGoing(long idog, RefRecordStatus refRecordStatus, TblEmployee tblEmployeeByLastUpdateBy, TblEmployee tblEmployeeByCreateBy, TblEmployee tblEmployeeByIdreceiver, TblLocation tblLocationByIdlocationDestination, TblLocation tblLocationByIdlocationSource, TblStoreRequest tblStoreRequest, String codeOg, Date ogdate, String ognote, Date createDate, Date lastUpdateDate, Set tblOutGoingDetails) {
        this();
        idogProperty().set(idog);
        refRecordStatusProperty().set(refRecordStatus);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblEmployeeByIdreceiverProperty().set(tblEmployeeByIdreceiver);
        tblLocationByIdlocationDestinationProperty().set(tblLocationByIdlocationDestination);
        tblLocationByIdlocationSourceProperty().set(tblLocationByIdlocationSource);
        tblStoreRequestProperty().set(tblStoreRequest);
        codeOgProperty().set(codeOg);
        ogdateProperty().set(ogdate);
        ognoteProperty().set(ognote);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

        this.tblOutGoingDetails = tblOutGoingDetails;
    }

    public TblOutGoing(TblOutGoing tblOutGoing) {
        this();
        idogProperty().set(tblOutGoing.getIdog());
        refRecordStatusProperty().set(tblOutGoing.getRefRecordStatus());
        tblEmployeeByLastUpdateByProperty().set(tblOutGoing.getTblEmployeeByLastUpdateBy());
        tblEmployeeByCreateByProperty().set(tblOutGoing.getTblEmployeeByCreateBy());
        tblEmployeeByIdreceiverProperty().set(tblOutGoing.getTblEmployeeByIdreceiver());
        tblLocationByIdlocationDestinationProperty().set(tblOutGoing.getTblLocationByIdlocationDestination());
        tblLocationByIdlocationSourceProperty().set(tblOutGoing.getTblLocationByIdlocationSource());
        tblStoreRequestProperty().set(tblOutGoing.getTblStoreRequest());
        codeOgProperty().set(tblOutGoing.getCodeOg());
        ogdateProperty().set(tblOutGoing.getOgdate());
        ognoteProperty().set(tblOutGoing.getOgnote());
        createDateProperty().set(tblOutGoing.getCreateDate());
        lastUpdateDateProperty().set(tblOutGoing.getLastUpdateDate());

        this.tblOutGoingDetails = tblOutGoing.getTblOutGoingDetails();
    }

    public final LongProperty idogProperty() {
        return this.idog;
    }

    public long getIdog() {
        return idogProperty().get();
    }

    public void setIdog(long idog) {
        idogProperty().set(idog);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByIdreceiverProperty() {
        return this.tblEmployeeByIdreceiver;
    }

    public TblEmployee getTblEmployeeByIdreceiver() {
        return tblEmployeeByIdreceiverProperty().get();
    }

    public void setTblEmployeeByIdreceiver(TblEmployee tblEmployeeByIdreceiver) {
        tblEmployeeByIdreceiverProperty().set(tblEmployeeByIdreceiver);
    }

    public final ObjectProperty<TblLocation> tblLocationByIdlocationDestinationProperty() {
        return this.tblLocationByIdlocationDestination;
    }

    public TblLocation getTblLocationByIdlocationDestination() {
        return tblLocationByIdlocationDestinationProperty().get();
    }

    public void setTblLocationByIdlocationDestination(TblLocation tblLocationByIdlocationDestination) {
        tblLocationByIdlocationDestinationProperty().set(tblLocationByIdlocationDestination);
    }

    public final ObjectProperty<TblLocation> tblLocationByIdlocationSourceProperty() {
        return this.tblLocationByIdlocationSource;
    }

    public TblLocation getTblLocationByIdlocationSource() {
        return tblLocationByIdlocationSourceProperty().get();
    }

    public void setTblLocationByIdlocationSource(TblLocation tblLocationByIdlocationSource) {
        tblLocationByIdlocationSourceProperty().set(tblLocationByIdlocationSource);
    }

    public final ObjectProperty<TblStoreRequest> tblStoreRequestProperty() {
        return this.tblStoreRequest;
    }

    public TblStoreRequest getTblStoreRequest() {
        return tblStoreRequestProperty().get();
    }

    public void setTblStoreRequest(TblStoreRequest tblStoreRequest) {
        tblStoreRequestProperty().set(tblStoreRequest);
    }

    public final StringProperty codeOgProperty() {
        return this.codeOg;
    }

    public String getCodeOg() {
        return codeOgProperty().get();
    }

    public void setCodeOg(String codeOg) {
        codeOgProperty().set(codeOg);
    }

    public final ObjectProperty<Date> ogdateProperty() {
        return this.ogdate;
    }

    public Date getOgdate() {
        return ogdateProperty().get();
    }

    public void setOgdate(Date ogdate) {
        ogdateProperty().set(ogdate);
    }

    public final StringProperty ognoteProperty() {
        return this.ognote;
    }

    public String getOgnote() {
        return ognoteProperty().get();
    }

    public void setOgnote(String ognote) {
        ognoteProperty().set(ognote);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

    public Set getTblOutGoingDetails() {
        return this.tblOutGoingDetails;
    }

    public void setTblOutGoingDetails(Set tblOutGoingDetails) {
        this.tblOutGoingDetails = tblOutGoingDetails;
    }

    @Override
    public String toString(){
        return getCodeOg();
    }
    
}
