package hotelfx.persistence.model;
// Generated Mar 20, 2018 9:55:15 AM by Hibernate Tools 4.3.1

import java.util.Date;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblOpenCloseCashierBalanceDetail generated by hbm2java
 */
public class TblOpenCloseCashierBalanceDetail implements java.io.Serializable {

    private final LongProperty iddetail;
    private final ObjectProperty<LogCompanyBalanceCashFlow> logCompanyBalanceCashFlow;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblHotelExpenseTransaction> tblHotelExpenseTransaction;
    private final ObjectProperty<TblOpenCloseCashierBalance> tblOpenCloseCashierBalance;
    private final ObjectProperty<TblReservationPayment> tblReservationPayment;
    private final StringProperty detailData;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    public TblOpenCloseCashierBalanceDetail() {
        this.iddetail = new SimpleLongProperty();
        this.logCompanyBalanceCashFlow = new SimpleObjectProperty<>();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblHotelExpenseTransaction = new SimpleObjectProperty<>();
        this.tblOpenCloseCashierBalance = new SimpleObjectProperty<>();
        this.tblReservationPayment = new SimpleObjectProperty<>();
        this.detailData = new SimpleStringProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

    }

    public TblOpenCloseCashierBalanceDetail(long iddetail) {
        this();
        iddetailProperty().set(iddetail);
    }

    public TblOpenCloseCashierBalanceDetail(long iddetail, LogCompanyBalanceCashFlow logCompanyBalanceCashFlow, RefRecordStatus refRecordStatus, TblEmployee tblEmployeeByLastUpdateBy, TblEmployee tblEmployeeByCreateBy, TblHotelExpenseTransaction tblHotelExpenseTransaction, TblOpenCloseCashierBalance tblOpenCloseCashierBalance, TblReservationPayment tblReservationPayment, String detailData, Date createDate, Date lastUpdateDate) {
        this();
        iddetailProperty().set(iddetail);
        logCompanyBalanceCashFlowProperty().set(logCompanyBalanceCashFlow);
        refRecordStatusProperty().set(refRecordStatus);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblHotelExpenseTransactionProperty().set(tblHotelExpenseTransaction);
        tblOpenCloseCashierBalanceProperty().set(tblOpenCloseCashierBalance);
        tblReservationPaymentProperty().set(tblReservationPayment);
        detailDataProperty().set(detailData);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

    }

    public TblOpenCloseCashierBalanceDetail(TblOpenCloseCashierBalanceDetail tblOpenCloseCashierBalanceDetail) {
        this();
        iddetailProperty().set(tblOpenCloseCashierBalanceDetail.getIddetail());
        logCompanyBalanceCashFlowProperty().set(tblOpenCloseCashierBalanceDetail.getLogCompanyBalanceCashFlow());
        refRecordStatusProperty().set(tblOpenCloseCashierBalanceDetail.getRefRecordStatus());
        tblEmployeeByLastUpdateByProperty().set(tblOpenCloseCashierBalanceDetail.getTblEmployeeByLastUpdateBy());
        tblEmployeeByCreateByProperty().set(tblOpenCloseCashierBalanceDetail.getTblEmployeeByCreateBy());
        tblHotelExpenseTransactionProperty().set(tblOpenCloseCashierBalanceDetail.getTblHotelExpenseTransaction());
        tblOpenCloseCashierBalanceProperty().set(tblOpenCloseCashierBalanceDetail.getTblOpenCloseCashierBalance());
        tblReservationPaymentProperty().set(tblOpenCloseCashierBalanceDetail.getTblReservationPayment());
        detailDataProperty().set(tblOpenCloseCashierBalanceDetail.getDetailData());
        createDateProperty().set(tblOpenCloseCashierBalanceDetail.getCreateDate());
        lastUpdateDateProperty().set(tblOpenCloseCashierBalanceDetail.getLastUpdateDate());

    }

    public final LongProperty iddetailProperty() {
        return this.iddetail;
    }

    public long getIddetail() {
        return iddetailProperty().get();
    }

    public void setIddetail(long iddetail) {
        iddetailProperty().set(iddetail);
    }

    public final ObjectProperty<LogCompanyBalanceCashFlow> logCompanyBalanceCashFlowProperty() {
        return this.logCompanyBalanceCashFlow;
    }

    public LogCompanyBalanceCashFlow getLogCompanyBalanceCashFlow() {
        return logCompanyBalanceCashFlowProperty().get();
    }

    public void setLogCompanyBalanceCashFlow(LogCompanyBalanceCashFlow logCompanyBalanceCashFlow) {
        logCompanyBalanceCashFlowProperty().set(logCompanyBalanceCashFlow);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblHotelExpenseTransaction> tblHotelExpenseTransactionProperty() {
        return this.tblHotelExpenseTransaction;
    }

    public TblHotelExpenseTransaction getTblHotelExpenseTransaction() {
        return tblHotelExpenseTransactionProperty().get();
    }

    public void setTblHotelExpenseTransaction(TblHotelExpenseTransaction tblHotelExpenseTransaction) {
        tblHotelExpenseTransactionProperty().set(tblHotelExpenseTransaction);
    }

    public final ObjectProperty<TblOpenCloseCashierBalance> tblOpenCloseCashierBalanceProperty() {
        return this.tblOpenCloseCashierBalance;
    }

    public TblOpenCloseCashierBalance getTblOpenCloseCashierBalance() {
        return tblOpenCloseCashierBalanceProperty().get();
    }

    public void setTblOpenCloseCashierBalance(TblOpenCloseCashierBalance tblOpenCloseCashierBalance) {
        tblOpenCloseCashierBalanceProperty().set(tblOpenCloseCashierBalance);
    }

    public final ObjectProperty<TblReservationPayment> tblReservationPaymentProperty() {
        return this.tblReservationPayment;
    }

    public TblReservationPayment getTblReservationPayment() {
        return tblReservationPaymentProperty().get();
    }

    public void setTblReservationPayment(TblReservationPayment tblReservationPayment) {
        tblReservationPaymentProperty().set(tblReservationPayment);
    }

    public final StringProperty detailDataProperty() {
        return this.detailData;
    }

    public String getDetailData() {
        return detailDataProperty().get();
    }

    public void setDetailData(String detailData) {
        detailDataProperty().set(detailData);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

}
