package hotelfx.persistence.model;
// Generated Oct 5, 2018 4:27:54 PM by Hibernate Tools 4.3.1

import java.util.Date;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;

/**
 * TblOutGoingDetailItemMutationHistory generated by hbm2java
 */
public class TblOutGoingDetailItemMutationHistory implements java.io.Serializable {

    private final LongProperty idrelation;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblItemMutationHistory> tblItemMutationHistory;
    private final ObjectProperty<TblOutGoingDetail> tblOutGoingDetail;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    public TblOutGoingDetailItemMutationHistory() {
        this.idrelation = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblItemMutationHistory = new SimpleObjectProperty<>();
        this.tblOutGoingDetail = new SimpleObjectProperty<>();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

    }

    public TblOutGoingDetailItemMutationHistory(long idrelation) {
        this();
        idrelationProperty().set(idrelation);
    }

    public TblOutGoingDetailItemMutationHistory(long idrelation, RefRecordStatus refRecordStatus, TblEmployee tblEmployeeByCreateBy, TblEmployee tblEmployeeByLastUpdateBy, TblItemMutationHistory tblItemMutationHistory, TblOutGoingDetail tblOutGoingDetail, Date createDate, Date lastUpdateDate) {
        this();
        idrelationProperty().set(idrelation);
        refRecordStatusProperty().set(refRecordStatus);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblItemMutationHistoryProperty().set(tblItemMutationHistory);
        tblOutGoingDetailProperty().set(tblOutGoingDetail);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

    }

    public TblOutGoingDetailItemMutationHistory(TblOutGoingDetailItemMutationHistory tblOutGoingDetailItemMutationHistory) {
        this();
        idrelationProperty().set(tblOutGoingDetailItemMutationHistory.getIdrelation());
        refRecordStatusProperty().set(tblOutGoingDetailItemMutationHistory.getRefRecordStatus());
        tblEmployeeByCreateByProperty().set(tblOutGoingDetailItemMutationHistory.getTblEmployeeByCreateBy());
        tblEmployeeByLastUpdateByProperty().set(tblOutGoingDetailItemMutationHistory.getTblEmployeeByLastUpdateBy());
        tblItemMutationHistoryProperty().set(tblOutGoingDetailItemMutationHistory.getTblItemMutationHistory());
        tblOutGoingDetailProperty().set(tblOutGoingDetailItemMutationHistory.getTblOutGoingDetail());
        createDateProperty().set(tblOutGoingDetailItemMutationHistory.getCreateDate());
        lastUpdateDateProperty().set(tblOutGoingDetailItemMutationHistory.getLastUpdateDate());

    }

    public final LongProperty idrelationProperty() {
        return this.idrelation;
    }

    public long getIdrelation() {
        return idrelationProperty().get();
    }

    public void setIdrelation(long idrelation) {
        idrelationProperty().set(idrelation);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblItemMutationHistory> tblItemMutationHistoryProperty() {
        return this.tblItemMutationHistory;
    }

    public TblItemMutationHistory getTblItemMutationHistory() {
        return tblItemMutationHistoryProperty().get();
    }

    public void setTblItemMutationHistory(TblItemMutationHistory tblItemMutationHistory) {
        tblItemMutationHistoryProperty().set(tblItemMutationHistory);
    }

    public final ObjectProperty<TblOutGoingDetail> tblOutGoingDetailProperty() {
        return this.tblOutGoingDetail;
    }

    public TblOutGoingDetail getTblOutGoingDetail() {
        return tblOutGoingDetailProperty().get();
    }

    public void setTblOutGoingDetail(TblOutGoingDetail tblOutGoingDetail) {
        tblOutGoingDetailProperty().set(tblOutGoingDetail);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

}
