package hotelfx.persistence.model;
// Generated Apr 24, 2018 1:30:08 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblOpenCloseCashierBalance generated by hbm2java
 */
public class TblOpenCloseCashierBalance implements java.io.Serializable {

    private final LongProperty idopenCloseCashierBalance;
    private final ObjectProperty<RefOpenCloseCashierBalanceStatus> refOpenCloseCashierBalanceStatus;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByIdcashier;
    private final ObjectProperty<Date> openDateTime;
    private final ObjectProperty<Date> closeDateTime;
    private final ObjectProperty<BigDecimal> beginBalanceNominal;
    private final ObjectProperty<BigDecimal> systemEndBalanceNominal;
    private final ObjectProperty<BigDecimal> realEndBalanceNominal;
    private final StringProperty openCloseCashierBalanceNote;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    private Set tblOpenCloseCashierBalanceDetails;

    public TblOpenCloseCashierBalance() {
        this.idopenCloseCashierBalance = new SimpleLongProperty();
        this.refOpenCloseCashierBalanceStatus = new SimpleObjectProperty<>();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByIdcashier = new SimpleObjectProperty<>();
        this.openDateTime = new SimpleObjectProperty<>();
        this.closeDateTime = new SimpleObjectProperty<>();
        this.beginBalanceNominal = new SimpleObjectProperty<>();
        this.systemEndBalanceNominal = new SimpleObjectProperty<>();
        this.realEndBalanceNominal = new SimpleObjectProperty<>();
        this.openCloseCashierBalanceNote = new SimpleStringProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

        this.tblOpenCloseCashierBalanceDetails = new HashSet(0);
    }

    public TblOpenCloseCashierBalance(long idopenCloseCashierBalance) {
        this();
        idopenCloseCashierBalanceProperty().set(idopenCloseCashierBalance);
    }

    public TblOpenCloseCashierBalance(long idopenCloseCashierBalance, RefOpenCloseCashierBalanceStatus refOpenCloseCashierBalanceStatus, RefRecordStatus refRecordStatus, TblEmployee tblEmployeeByLastUpdateBy, TblEmployee tblEmployeeByCreateBy, TblEmployee tblEmployeeByIdcashier, Date openDateTime, Date closeDateTime, BigDecimal beginBalanceNominal, BigDecimal systemEndBalanceNominal, BigDecimal realEndBalanceNominal, String openCloseCashierBalanceNote, Date createDate, Date lastUpdateDate, Set tblOpenCloseCashierBalanceDetails) {
        this();
        idopenCloseCashierBalanceProperty().set(idopenCloseCashierBalance);
        refOpenCloseCashierBalanceStatusProperty().set(refOpenCloseCashierBalanceStatus);
        refRecordStatusProperty().set(refRecordStatus);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblEmployeeByIdcashierProperty().set(tblEmployeeByIdcashier);
        openDateTimeProperty().set(openDateTime);
        closeDateTimeProperty().set(closeDateTime);
        beginBalanceNominalProperty().set(beginBalanceNominal);
        systemEndBalanceNominalProperty().set(systemEndBalanceNominal);
        realEndBalanceNominalProperty().set(realEndBalanceNominal);
        openCloseCashierBalanceNoteProperty().set(openCloseCashierBalanceNote);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

        this.tblOpenCloseCashierBalanceDetails = tblOpenCloseCashierBalanceDetails;
    }

    public TblOpenCloseCashierBalance(TblOpenCloseCashierBalance tblOpenCloseCashierBalance) {
        this();
        idopenCloseCashierBalanceProperty().set(tblOpenCloseCashierBalance.getIdopenCloseCashierBalance());
        refOpenCloseCashierBalanceStatusProperty().set(tblOpenCloseCashierBalance.getRefOpenCloseCashierBalanceStatus());
        refRecordStatusProperty().set(tblOpenCloseCashierBalance.getRefRecordStatus());
        tblEmployeeByLastUpdateByProperty().set(tblOpenCloseCashierBalance.getTblEmployeeByLastUpdateBy());
        tblEmployeeByCreateByProperty().set(tblOpenCloseCashierBalance.getTblEmployeeByCreateBy());
        tblEmployeeByIdcashierProperty().set(tblOpenCloseCashierBalance.getTblEmployeeByIdcashier());
        openDateTimeProperty().set(tblOpenCloseCashierBalance.getOpenDateTime());
        closeDateTimeProperty().set(tblOpenCloseCashierBalance.getCloseDateTime());
        beginBalanceNominalProperty().set(tblOpenCloseCashierBalance.getBeginBalanceNominal());
        systemEndBalanceNominalProperty().set(tblOpenCloseCashierBalance.getSystemEndBalanceNominal());
        realEndBalanceNominalProperty().set(tblOpenCloseCashierBalance.getRealEndBalanceNominal());
        openCloseCashierBalanceNoteProperty().set(tblOpenCloseCashierBalance.getOpenCloseCashierBalanceNote());
        createDateProperty().set(tblOpenCloseCashierBalance.getCreateDate());
        lastUpdateDateProperty().set(tblOpenCloseCashierBalance.getLastUpdateDate());

        this.tblOpenCloseCashierBalanceDetails = tblOpenCloseCashierBalance.getTblOpenCloseCashierBalanceDetails();
    }

    public final LongProperty idopenCloseCashierBalanceProperty() {
        return this.idopenCloseCashierBalance;
    }

    public long getIdopenCloseCashierBalance() {
        return idopenCloseCashierBalanceProperty().get();
    }

    public void setIdopenCloseCashierBalance(long idopenCloseCashierBalance) {
        idopenCloseCashierBalanceProperty().set(idopenCloseCashierBalance);
    }

    public final ObjectProperty<RefOpenCloseCashierBalanceStatus> refOpenCloseCashierBalanceStatusProperty() {
        return this.refOpenCloseCashierBalanceStatus;
    }

    public RefOpenCloseCashierBalanceStatus getRefOpenCloseCashierBalanceStatus() {
        return refOpenCloseCashierBalanceStatusProperty().get();
    }

    public void setRefOpenCloseCashierBalanceStatus(RefOpenCloseCashierBalanceStatus refOpenCloseCashierBalanceStatus) {
        refOpenCloseCashierBalanceStatusProperty().set(refOpenCloseCashierBalanceStatus);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByIdcashierProperty() {
        return this.tblEmployeeByIdcashier;
    }

    public TblEmployee getTblEmployeeByIdcashier() {
        return tblEmployeeByIdcashierProperty().get();
    }

    public void setTblEmployeeByIdcashier(TblEmployee tblEmployeeByIdcashier) {
        tblEmployeeByIdcashierProperty().set(tblEmployeeByIdcashier);
    }

    public final ObjectProperty<Date> openDateTimeProperty() {
        return this.openDateTime;
    }

    public Date getOpenDateTime() {
        return openDateTimeProperty().get();
    }

    public void setOpenDateTime(Date openDateTime) {
        openDateTimeProperty().set(openDateTime);
    }

    public final ObjectProperty<Date> closeDateTimeProperty() {
        return this.closeDateTime;
    }

    public Date getCloseDateTime() {
        return closeDateTimeProperty().get();
    }

    public void setCloseDateTime(Date closeDateTime) {
        closeDateTimeProperty().set(closeDateTime);
    }

    public final ObjectProperty<BigDecimal> beginBalanceNominalProperty() {
        return this.beginBalanceNominal;
    }

    public BigDecimal getBeginBalanceNominal() {
        return beginBalanceNominalProperty().get();
    }

    public void setBeginBalanceNominal(BigDecimal beginBalanceNominal) {
        beginBalanceNominalProperty().set(beginBalanceNominal);
    }

    public final ObjectProperty<BigDecimal> systemEndBalanceNominalProperty() {
        return this.systemEndBalanceNominal;
    }

    public BigDecimal getSystemEndBalanceNominal() {
        return systemEndBalanceNominalProperty().get();
    }

    public void setSystemEndBalanceNominal(BigDecimal systemEndBalanceNominal) {
        systemEndBalanceNominalProperty().set(systemEndBalanceNominal);
    }

    public final ObjectProperty<BigDecimal> realEndBalanceNominalProperty() {
        return this.realEndBalanceNominal;
    }

    public BigDecimal getRealEndBalanceNominal() {
        return realEndBalanceNominalProperty().get();
    }

    public void setRealEndBalanceNominal(BigDecimal realEndBalanceNominal) {
        realEndBalanceNominalProperty().set(realEndBalanceNominal);
    }

    public final StringProperty openCloseCashierBalanceNoteProperty() {
        return this.openCloseCashierBalanceNote;
    }

    public String getOpenCloseCashierBalanceNote() {
        return openCloseCashierBalanceNoteProperty().get();
    }

    public void setOpenCloseCashierBalanceNote(String openCloseCashierBalanceNote) {
        openCloseCashierBalanceNoteProperty().set(openCloseCashierBalanceNote);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

    public Set getTblOpenCloseCashierBalanceDetails() {
        return this.tblOpenCloseCashierBalanceDetails;
    }

    public void setTblOpenCloseCashierBalanceDetails(Set tblOpenCloseCashierBalanceDetails) {
        this.tblOpenCloseCashierBalanceDetails = tblOpenCloseCashierBalanceDetails;
    }

}
