package hotelfx.persistence.model;
// Generated Sep 21, 2018 11:01:09 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblPurchaseRequest generated by hbm2java
 */
public class TblPurchaseRequest implements java.io.Serializable {

    private final LongProperty idpr;
    private final ObjectProperty<RefPurchaseRequestStatus> refPurchaseRequestStatus;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblApprovalData> tblApprovalData;
    private final ObjectProperty<TblEmployee> tblEmployeeByCanceledBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreatedBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByClosingBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByApprovedBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblSupplier> tblSupplier;
    private final StringProperty codePr;
    private final ObjectProperty<Date> prdate;
    private final ObjectProperty<Date> prdueDate;
    private final ObjectProperty<Date> createdDate;
    private final ObjectProperty<Date> approvedDate;
    private final ObjectProperty<Date> canceledDate;
    private final ObjectProperty<Date> closingDate;
    private final StringProperty prnote;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    private Set tblPurchaseOrders;
    private Set tblPurchaseRequestDetails;

    public TblPurchaseRequest() {
        this.idpr = new SimpleLongProperty();
        this.refPurchaseRequestStatus = new SimpleObjectProperty<>();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblApprovalData = new SimpleObjectProperty<>();
        this.tblEmployeeByCanceledBy = new SimpleObjectProperty<>();
        this.tblEmployeeByCreatedBy = new SimpleObjectProperty<>();
        this.tblEmployeeByClosingBy = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByApprovedBy = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblSupplier = new SimpleObjectProperty<>();
        this.codePr = new SimpleStringProperty();
        this.prdate = new SimpleObjectProperty<>();
        this.prdueDate = new SimpleObjectProperty<>();
        this.createdDate = new SimpleObjectProperty<>();
        this.approvedDate = new SimpleObjectProperty<>();
        this.canceledDate = new SimpleObjectProperty<>();
        this.closingDate = new SimpleObjectProperty<>();
        this.prnote = new SimpleStringProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

        this.tblPurchaseOrders = new HashSet(0);
        this.tblPurchaseRequestDetails = new HashSet(0);
    }

    public TblPurchaseRequest(long idpr) {
        this();
        idprProperty().set(idpr);
    }

    public TblPurchaseRequest(long idpr, RefPurchaseRequestStatus refPurchaseRequestStatus, RefRecordStatus refRecordStatus, TblApprovalData tblApprovalData, TblEmployee tblEmployeeByCanceledBy, TblEmployee tblEmployeeByCreatedBy, TblEmployee tblEmployeeByClosingBy, TblEmployee tblEmployeeByCreateBy, TblEmployee tblEmployeeByApprovedBy, TblEmployee tblEmployeeByLastUpdateBy, TblSupplier tblSupplier, String codePr, Date prdate, Date prdueDate, Date createdDate, Date approvedDate, Date canceledDate, Date closingDate, String prnote, Date createDate, Date lastUpdateDate, Set tblPurchaseOrders, Set tblPurchaseRequestDetails) {
        this();
        idprProperty().set(idpr);
        refPurchaseRequestStatusProperty().set(refPurchaseRequestStatus);
        refRecordStatusProperty().set(refRecordStatus);
        tblApprovalDataProperty().set(tblApprovalData);
        tblEmployeeByCanceledByProperty().set(tblEmployeeByCanceledBy);
        tblEmployeeByCreatedByProperty().set(tblEmployeeByCreatedBy);
        tblEmployeeByClosingByProperty().set(tblEmployeeByClosingBy);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblEmployeeByApprovedByProperty().set(tblEmployeeByApprovedBy);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblSupplierProperty().set(tblSupplier);
        codePrProperty().set(codePr);
        prdateProperty().set(prdate);
        prdueDateProperty().set(prdueDate);
        createdDateProperty().set(createdDate);
        approvedDateProperty().set(approvedDate);
        canceledDateProperty().set(canceledDate);
        closingDateProperty().set(closingDate);
        prnoteProperty().set(prnote);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

        this.tblPurchaseOrders = tblPurchaseOrders;
        this.tblPurchaseRequestDetails = tblPurchaseRequestDetails;
    }

    public TblPurchaseRequest(TblPurchaseRequest tblPurchaseRequest) {
        this();
        idprProperty().set(tblPurchaseRequest.getIdpr());
        refPurchaseRequestStatusProperty().set(tblPurchaseRequest.getRefPurchaseRequestStatus());
        refRecordStatusProperty().set(tblPurchaseRequest.getRefRecordStatus());
        tblApprovalDataProperty().set(tblPurchaseRequest.getTblApprovalData());
        tblEmployeeByCanceledByProperty().set(tblPurchaseRequest.getTblEmployeeByCanceledBy());
        tblEmployeeByCreatedByProperty().set(tblPurchaseRequest.getTblEmployeeByCreatedBy());
        tblEmployeeByClosingByProperty().set(tblPurchaseRequest.getTblEmployeeByClosingBy());
        tblEmployeeByCreateByProperty().set(tblPurchaseRequest.getTblEmployeeByCreateBy());
        tblEmployeeByApprovedByProperty().set(tblPurchaseRequest.getTblEmployeeByApprovedBy());
        tblEmployeeByLastUpdateByProperty().set(tblPurchaseRequest.getTblEmployeeByLastUpdateBy());
        tblSupplierProperty().set(tblPurchaseRequest.getTblSupplier());
        codePrProperty().set(tblPurchaseRequest.getCodePr());
        prdateProperty().set(tblPurchaseRequest.getPrdate());
        prdueDateProperty().set(tblPurchaseRequest.getPrdueDate());
        createdDateProperty().set(tblPurchaseRequest.getCreatedDate());
        approvedDateProperty().set(tblPurchaseRequest.getApprovedDate());
        canceledDateProperty().set(tblPurchaseRequest.getCanceledDate());
        closingDateProperty().set(tblPurchaseRequest.getClosingDate());
        prnoteProperty().set(tblPurchaseRequest.getPrnote());
        createDateProperty().set(tblPurchaseRequest.getCreateDate());
        lastUpdateDateProperty().set(tblPurchaseRequest.getLastUpdateDate());

        this.tblPurchaseOrders = tblPurchaseRequest.getTblPurchaseOrders();
        this.tblPurchaseRequestDetails = tblPurchaseRequest.getTblPurchaseRequestDetails();
    }

    public final LongProperty idprProperty() {
        return this.idpr;
    }

    public long getIdpr() {
        return idprProperty().get();
    }

    public void setIdpr(long idpr) {
        idprProperty().set(idpr);
    }

    public final ObjectProperty<RefPurchaseRequestStatus> refPurchaseRequestStatusProperty() {
        return this.refPurchaseRequestStatus;
    }

    public RefPurchaseRequestStatus getRefPurchaseRequestStatus() {
        return refPurchaseRequestStatusProperty().get();
    }

    public void setRefPurchaseRequestStatus(RefPurchaseRequestStatus refPurchaseRequestStatus) {
        refPurchaseRequestStatusProperty().set(refPurchaseRequestStatus);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblApprovalData> tblApprovalDataProperty() {
        return this.tblApprovalData;
    }

    public TblApprovalData getTblApprovalData() {
        return tblApprovalDataProperty().get();
    }

    public void setTblApprovalData(TblApprovalData tblApprovalData) {
        tblApprovalDataProperty().set(tblApprovalData);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCanceledByProperty() {
        return this.tblEmployeeByCanceledBy;
    }

    public TblEmployee getTblEmployeeByCanceledBy() {
        return tblEmployeeByCanceledByProperty().get();
    }

    public void setTblEmployeeByCanceledBy(TblEmployee tblEmployeeByCanceledBy) {
        tblEmployeeByCanceledByProperty().set(tblEmployeeByCanceledBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreatedByProperty() {
        return this.tblEmployeeByCreatedBy;
    }

    public TblEmployee getTblEmployeeByCreatedBy() {
        return tblEmployeeByCreatedByProperty().get();
    }

    public void setTblEmployeeByCreatedBy(TblEmployee tblEmployeeByCreatedBy) {
        tblEmployeeByCreatedByProperty().set(tblEmployeeByCreatedBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByClosingByProperty() {
        return this.tblEmployeeByClosingBy;
    }

    public TblEmployee getTblEmployeeByClosingBy() {
        return tblEmployeeByClosingByProperty().get();
    }

    public void setTblEmployeeByClosingBy(TblEmployee tblEmployeeByClosingBy) {
        tblEmployeeByClosingByProperty().set(tblEmployeeByClosingBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByApprovedByProperty() {
        return this.tblEmployeeByApprovedBy;
    }

    public TblEmployee getTblEmployeeByApprovedBy() {
        return tblEmployeeByApprovedByProperty().get();
    }

    public void setTblEmployeeByApprovedBy(TblEmployee tblEmployeeByApprovedBy) {
        tblEmployeeByApprovedByProperty().set(tblEmployeeByApprovedBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblSupplier> tblSupplierProperty() {
        return this.tblSupplier;
    }

    public TblSupplier getTblSupplier() {
        return tblSupplierProperty().get();
    }

    public void setTblSupplier(TblSupplier tblSupplier) {
        tblSupplierProperty().set(tblSupplier);
    }

    public final StringProperty codePrProperty() {
        return this.codePr;
    }

    public String getCodePr() {
        return codePrProperty().get();
    }

    public void setCodePr(String codePr) {
        codePrProperty().set(codePr);
    }

    public final ObjectProperty<Date> prdateProperty() {
        return this.prdate;
    }

    public Date getPrdate() {
        return prdateProperty().get();
    }

    public void setPrdate(Date prdate) {
        prdateProperty().set(prdate);
    }

    public final ObjectProperty<Date> prdueDateProperty() {
        return this.prdueDate;
    }

    public Date getPrdueDate() {
        return prdueDateProperty().get();
    }

    public void setPrdueDate(Date prdueDate) {
        prdueDateProperty().set(prdueDate);
    }

    public final ObjectProperty<Date> createdDateProperty() {
        return this.createdDate;
    }

    public Date getCreatedDate() {
        return createdDateProperty().get();
    }

    public void setCreatedDate(Date createdDate) {
        createdDateProperty().set(createdDate);
    }

    public final ObjectProperty<Date> approvedDateProperty() {
        return this.approvedDate;
    }

    public Date getApprovedDate() {
        return approvedDateProperty().get();
    }

    public void setApprovedDate(Date approvedDate) {
        approvedDateProperty().set(approvedDate);
    }

    public final ObjectProperty<Date> canceledDateProperty() {
        return this.canceledDate;
    }

    public Date getCanceledDate() {
        return canceledDateProperty().get();
    }

    public void setCanceledDate(Date canceledDate) {
        canceledDateProperty().set(canceledDate);
    }

    public final ObjectProperty<Date> closingDateProperty() {
        return this.closingDate;
    }

    public Date getClosingDate() {
        return closingDateProperty().get();
    }

    public void setClosingDate(Date closingDate) {
        closingDateProperty().set(closingDate);
    }

    public final StringProperty prnoteProperty() {
        return this.prnote;
    }

    public String getPrnote() {
        return prnoteProperty().get();
    }

    public void setPrnote(String prnote) {
        prnoteProperty().set(prnote);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

    public Set getTblPurchaseOrders() {
        return this.tblPurchaseOrders;
    }

    public void setTblPurchaseOrders(Set tblPurchaseOrders) {
        this.tblPurchaseOrders = tblPurchaseOrders;
    }

    public Set getTblPurchaseRequestDetails() {
        return this.tblPurchaseRequestDetails;
    }

    public void setTblPurchaseRequestDetails(Set tblPurchaseRequestDetails) {
        this.tblPurchaseRequestDetails = tblPurchaseRequestDetails;
    }

    @Override
    public String toString() {
        return getCodePr();
    }
    
}
