package hotelfx.persistence.model;
// Generated Jun 29, 2018 3:18:31 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblPurchaseOrderDetail generated by hbm2java
 */
public class TblPurchaseOrderDetail implements java.io.Serializable {

    private final LongProperty iddetail;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblPurchaseOrder> tblPurchaseOrder;
    private final ObjectProperty<TblSupplierItem> tblSupplierItem;
    private final ObjectProperty<BigDecimal> itemCost;
    private final ObjectProperty<BigDecimal> itemQuantity;
    private final ObjectProperty<BigDecimal> itemDiscount;
    private final StringProperty itemNote;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    public TblPurchaseOrderDetail() {
        this.iddetail = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblPurchaseOrder = new SimpleObjectProperty<>();
        this.tblSupplierItem = new SimpleObjectProperty<>();
        this.itemCost = new SimpleObjectProperty<>();
        this.itemQuantity = new SimpleObjectProperty<>();
        this.itemDiscount = new SimpleObjectProperty<>();
        this.itemNote = new SimpleStringProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

    }

    public TblPurchaseOrderDetail(long iddetail) {
        this();
        iddetailProperty().set(iddetail);
    }

    public TblPurchaseOrderDetail(long iddetail, RefRecordStatus refRecordStatus, TblEmployee tblEmployeeByLastUpdateBy, TblEmployee tblEmployeeByCreateBy, TblPurchaseOrder tblPurchaseOrder, TblSupplierItem tblSupplierItem, BigDecimal itemCost, BigDecimal itemQuantity, BigDecimal itemDiscount, String itemNote, Date createDate, Date lastUpdateDate) {
        this();
        iddetailProperty().set(iddetail);
        refRecordStatusProperty().set(refRecordStatus);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblPurchaseOrderProperty().set(tblPurchaseOrder);
        tblSupplierItemProperty().set(tblSupplierItem);
        itemCostProperty().set(itemCost);
        itemQuantityProperty().set(itemQuantity);
        itemDiscountProperty().set(itemDiscount);
        itemNoteProperty().set(itemNote);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

    }

    public TblPurchaseOrderDetail(TblPurchaseOrderDetail tblPurchaseOrderDetail) {
        this();
        iddetailProperty().set(tblPurchaseOrderDetail.getIddetail());
        refRecordStatusProperty().set(tblPurchaseOrderDetail.getRefRecordStatus());
        tblEmployeeByLastUpdateByProperty().set(tblPurchaseOrderDetail.getTblEmployeeByLastUpdateBy());
        tblEmployeeByCreateByProperty().set(tblPurchaseOrderDetail.getTblEmployeeByCreateBy());
        tblPurchaseOrderProperty().set(tblPurchaseOrderDetail.getTblPurchaseOrder());
        tblSupplierItemProperty().set(tblPurchaseOrderDetail.getTblSupplierItem());
        itemCostProperty().set(tblPurchaseOrderDetail.getItemCost());
        itemQuantityProperty().set(tblPurchaseOrderDetail.getItemQuantity());
        itemDiscountProperty().set(tblPurchaseOrderDetail.getItemDiscount());
        itemNoteProperty().set(tblPurchaseOrderDetail.getItemNote());
        createDateProperty().set(tblPurchaseOrderDetail.getCreateDate());
        lastUpdateDateProperty().set(tblPurchaseOrderDetail.getLastUpdateDate());

    }

    public final LongProperty iddetailProperty() {
        return this.iddetail;
    }

    public long getIddetail() {
        return iddetailProperty().get();
    }

    public void setIddetail(long iddetail) {
        iddetailProperty().set(iddetail);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblPurchaseOrder> tblPurchaseOrderProperty() {
        return this.tblPurchaseOrder;
    }

    public TblPurchaseOrder getTblPurchaseOrder() {
        return tblPurchaseOrderProperty().get();
    }

    public void setTblPurchaseOrder(TblPurchaseOrder tblPurchaseOrder) {
        tblPurchaseOrderProperty().set(tblPurchaseOrder);
    }

    public final ObjectProperty<TblSupplierItem> tblSupplierItemProperty() {
        return this.tblSupplierItem;
    }

    public TblSupplierItem getTblSupplierItem() {
        return tblSupplierItemProperty().get();
    }

    public void setTblSupplierItem(TblSupplierItem tblSupplierItem) {
        tblSupplierItemProperty().set(tblSupplierItem);
    }

    public final ObjectProperty<BigDecimal> itemCostProperty() {
        return this.itemCost;
    }

    public BigDecimal getItemCost() {
        return itemCostProperty().get();
    }

    public void setItemCost(BigDecimal itemCost) {
        itemCostProperty().set(itemCost);
    }

    public final ObjectProperty<BigDecimal> itemQuantityProperty() {
        return this.itemQuantity;
    }

    public BigDecimal getItemQuantity() {
        return itemQuantityProperty().get();
    }

    public void setItemQuantity(BigDecimal itemQuantity) {
        itemQuantityProperty().set(itemQuantity);
    }

    public final ObjectProperty<BigDecimal> itemDiscountProperty() {
        return this.itemDiscount;
    }

    public BigDecimal getItemDiscount() {
        return itemDiscountProperty().get();
    }

    public void setItemDiscount(BigDecimal itemDiscount) {
        itemDiscountProperty().set(itemDiscount);
    }

    public final StringProperty itemNoteProperty() {
        return this.itemNote;
    }

    public String getItemNote() {
        return itemNoteProperty().get();
    }

    public void setItemNote(String itemNote) {
        itemNoteProperty().set(itemNote);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

}
