package hotelfx.persistence.model;
// Generated Mar 29, 2018 3:28:56 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblPeople generated by hbm2java
 */
public class TblPeople implements java.io.Serializable {

    private final LongProperty idpeople;
    private final ObjectProperty<RefCountry> refCountry;
    private final ObjectProperty<RefPeopleGender> refPeopleGender;
    private final ObjectProperty<RefPeopleIdentifierType> refPeopleIdentifierType;
    private final ObjectProperty<RefPeopleReligion> refPeopleReligion;
    private final ObjectProperty<RefPeopleStatus> refPeopleStatus;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final StringProperty codePeople;
    private final StringProperty ktpnumber;
    private final StringProperty simnumber;
    private final StringProperty passportNumber;
    private final StringProperty fullName;
    private final StringProperty birthPlace;
    private final ObjectProperty<Date> birthDate;
    private final StringProperty address;
    private final StringProperty rt;
    private final StringProperty rw;
    private final StringProperty kelurahan;
    private final StringProperty kecamatan;
    private final StringProperty town;
    private final StringProperty poscode;
    private final StringProperty region;
    private final StringProperty telpNumber;
    private final StringProperty hpnumber;
    private final StringProperty email;
    private final StringProperty imageUrl;
    private final StringProperty peopleNote;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    private Set tblApplicants;
    private Set tblEmployees;
    private Set tblPeopleEmploymentHistories;
    private Set tblPeopleEducationHistories;
    private Set tblCustomers;
    private Set tblLostInformations;
    private Set tblPeopleFamilies;

    public TblPeople() {
        this.idpeople = new SimpleLongProperty();
        this.refCountry = new SimpleObjectProperty<>();
        this.refPeopleGender = new SimpleObjectProperty<>();
        this.refPeopleIdentifierType = new SimpleObjectProperty<>();
        this.refPeopleReligion = new SimpleObjectProperty<>();
        this.refPeopleStatus = new SimpleObjectProperty<>();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.codePeople = new SimpleStringProperty();
        this.ktpnumber = new SimpleStringProperty();
        this.simnumber = new SimpleStringProperty();
        this.passportNumber = new SimpleStringProperty();
        this.fullName = new SimpleStringProperty();
        this.birthPlace = new SimpleStringProperty();
        this.birthDate = new SimpleObjectProperty<>();
        this.address = new SimpleStringProperty();
        this.rt = new SimpleStringProperty();
        this.rw = new SimpleStringProperty();
        this.kelurahan = new SimpleStringProperty();
        this.kecamatan = new SimpleStringProperty();
        this.town = new SimpleStringProperty();
        this.poscode = new SimpleStringProperty();
        this.region = new SimpleStringProperty();
        this.telpNumber = new SimpleStringProperty();
        this.hpnumber = new SimpleStringProperty();
        this.email = new SimpleStringProperty();
        this.imageUrl = new SimpleStringProperty();
        this.peopleNote = new SimpleStringProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

        this.tblApplicants = new HashSet(0);
        this.tblEmployees = new HashSet(0);
        this.tblPeopleEmploymentHistories = new HashSet(0);
        this.tblPeopleEducationHistories = new HashSet(0);
        this.tblCustomers = new HashSet(0);
        this.tblLostInformations = new HashSet(0);
        this.tblPeopleFamilies = new HashSet(0);
    }

    public TblPeople(long idpeople) {
        this();
        idpeopleProperty().set(idpeople);
    }

    public TblPeople(long idpeople, RefCountry refCountry, RefPeopleGender refPeopleGender, RefPeopleIdentifierType refPeopleIdentifierType, RefPeopleReligion refPeopleReligion, RefPeopleStatus refPeopleStatus, RefRecordStatus refRecordStatus, TblEmployee tblEmployeeByCreateBy, TblEmployee tblEmployeeByLastUpdateBy, String codePeople, String ktpnumber, String simnumber, String passportNumber, String fullName, String birthPlace, Date birthDate, String address, String rt, String rw, String kelurahan, String kecamatan, String town, String poscode, String region, String telpNumber, String hpnumber, String email, String imageUrl, String peopleNote, Date createDate, Date lastUpdateDate, Set tblApplicants, Set tblEmployees, Set tblPeopleEmploymentHistories, Set tblPeopleEducationHistories, Set tblCustomers, Set tblLostInformations, Set tblPeopleFamilies) {
        this();
        idpeopleProperty().set(idpeople);
        refCountryProperty().set(refCountry);
        refPeopleGenderProperty().set(refPeopleGender);
        refPeopleIdentifierTypeProperty().set(refPeopleIdentifierType);
        refPeopleReligionProperty().set(refPeopleReligion);
        refPeopleStatusProperty().set(refPeopleStatus);
        refRecordStatusProperty().set(refRecordStatus);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        codePeopleProperty().set(codePeople);
        ktpnumberProperty().set(ktpnumber);
        simnumberProperty().set(simnumber);
        passportNumberProperty().set(passportNumber);
        fullNameProperty().set(fullName);
        birthPlaceProperty().set(birthPlace);
        birthDateProperty().set(birthDate);
        addressProperty().set(address);
        rtProperty().set(rt);
        rwProperty().set(rw);
        kelurahanProperty().set(kelurahan);
        kecamatanProperty().set(kecamatan);
        townProperty().set(town);
        poscodeProperty().set(poscode);
        regionProperty().set(region);
        telpNumberProperty().set(telpNumber);
        hpnumberProperty().set(hpnumber);
        emailProperty().set(email);
        imageUrlProperty().set(imageUrl);
        peopleNoteProperty().set(peopleNote);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

        this.tblApplicants = tblApplicants;
        this.tblEmployees = tblEmployees;
        this.tblPeopleEmploymentHistories = tblPeopleEmploymentHistories;
        this.tblPeopleEducationHistories = tblPeopleEducationHistories;
        this.tblCustomers = tblCustomers;
        this.tblLostInformations = tblLostInformations;
        this.tblPeopleFamilies = tblPeopleFamilies;
    }

    public TblPeople(TblPeople tblPeople) {
        this();
        idpeopleProperty().set(tblPeople.getIdpeople());
        refCountryProperty().set(tblPeople.getRefCountry());
        refPeopleGenderProperty().set(tblPeople.getRefPeopleGender());
        refPeopleIdentifierTypeProperty().set(tblPeople.getRefPeopleIdentifierType());
        refPeopleReligionProperty().set(tblPeople.getRefPeopleReligion());
        refPeopleStatusProperty().set(tblPeople.getRefPeopleStatus());
        refRecordStatusProperty().set(tblPeople.getRefRecordStatus());
        tblEmployeeByCreateByProperty().set(tblPeople.getTblEmployeeByCreateBy());
        tblEmployeeByLastUpdateByProperty().set(tblPeople.getTblEmployeeByLastUpdateBy());
        codePeopleProperty().set(tblPeople.getCodePeople());
        ktpnumberProperty().set(tblPeople.getKtpnumber());
        simnumberProperty().set(tblPeople.getSimnumber());
        passportNumberProperty().set(tblPeople.getPassportNumber());
        fullNameProperty().set(tblPeople.getFullName());
        birthPlaceProperty().set(tblPeople.getBirthPlace());
        birthDateProperty().set(tblPeople.getBirthDate());
        addressProperty().set(tblPeople.getAddress());
        rtProperty().set(tblPeople.getRt());
        rwProperty().set(tblPeople.getRw());
        kelurahanProperty().set(tblPeople.getKelurahan());
        kecamatanProperty().set(tblPeople.getKecamatan());
        townProperty().set(tblPeople.getTown());
        poscodeProperty().set(tblPeople.getPoscode());
        regionProperty().set(tblPeople.getRegion());
        telpNumberProperty().set(tblPeople.getTelpNumber());
        hpnumberProperty().set(tblPeople.getHpnumber());
        emailProperty().set(tblPeople.getEmail());
        imageUrlProperty().set(tblPeople.getImageUrl());
        peopleNoteProperty().set(tblPeople.getPeopleNote());
        createDateProperty().set(tblPeople.getCreateDate());
        lastUpdateDateProperty().set(tblPeople.getLastUpdateDate());

        this.tblApplicants = tblPeople.getTblApplicants();
        this.tblEmployees = tblPeople.getTblEmployees();
        this.tblPeopleEmploymentHistories = tblPeople.getTblPeopleEmploymentHistories();
        this.tblPeopleEducationHistories = tblPeople.getTblPeopleEducationHistories();
        this.tblCustomers = tblPeople.getTblCustomers();
        this.tblLostInformations = tblPeople.getTblLostInformations();
        this.tblPeopleFamilies = tblPeople.getTblPeopleFamilies();
    }

    public final LongProperty idpeopleProperty() {
        return this.idpeople;
    }

    public long getIdpeople() {
        return idpeopleProperty().get();
    }

    public void setIdpeople(long idpeople) {
        idpeopleProperty().set(idpeople);
    }

    public final ObjectProperty<RefCountry> refCountryProperty() {
        return this.refCountry;
    }

    public RefCountry getRefCountry() {
        return refCountryProperty().get();
    }

    public void setRefCountry(RefCountry refCountry) {
        refCountryProperty().set(refCountry);
    }

    public final ObjectProperty<RefPeopleGender> refPeopleGenderProperty() {
        return this.refPeopleGender;
    }

    public RefPeopleGender getRefPeopleGender() {
        return refPeopleGenderProperty().get();
    }

    public void setRefPeopleGender(RefPeopleGender refPeopleGender) {
        refPeopleGenderProperty().set(refPeopleGender);
    }

    public final ObjectProperty<RefPeopleIdentifierType> refPeopleIdentifierTypeProperty() {
        return this.refPeopleIdentifierType;
    }

    public RefPeopleIdentifierType getRefPeopleIdentifierType() {
        return refPeopleIdentifierTypeProperty().get();
    }

    public void setRefPeopleIdentifierType(RefPeopleIdentifierType refPeopleIdentifierType) {
        refPeopleIdentifierTypeProperty().set(refPeopleIdentifierType);
    }

    public final ObjectProperty<RefPeopleReligion> refPeopleReligionProperty() {
        return this.refPeopleReligion;
    }

    public RefPeopleReligion getRefPeopleReligion() {
        return refPeopleReligionProperty().get();
    }

    public void setRefPeopleReligion(RefPeopleReligion refPeopleReligion) {
        refPeopleReligionProperty().set(refPeopleReligion);
    }

    public final ObjectProperty<RefPeopleStatus> refPeopleStatusProperty() {
        return this.refPeopleStatus;
    }

    public RefPeopleStatus getRefPeopleStatus() {
        return refPeopleStatusProperty().get();
    }

    public void setRefPeopleStatus(RefPeopleStatus refPeopleStatus) {
        refPeopleStatusProperty().set(refPeopleStatus);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final StringProperty codePeopleProperty() {
        return this.codePeople;
    }

    public String getCodePeople() {
        return codePeopleProperty().get();
    }

    public void setCodePeople(String codePeople) {
        codePeopleProperty().set(codePeople);
    }

    public final StringProperty ktpnumberProperty() {
        return this.ktpnumber;
    }

    public String getKtpnumber() {
        return ktpnumberProperty().get();
    }

    public void setKtpnumber(String ktpnumber) {
        ktpnumberProperty().set(ktpnumber);
    }

    public final StringProperty simnumberProperty() {
        return this.simnumber;
    }

    public String getSimnumber() {
        return simnumberProperty().get();
    }

    public void setSimnumber(String simnumber) {
        simnumberProperty().set(simnumber);
    }

    public final StringProperty passportNumberProperty() {
        return this.passportNumber;
    }

    public String getPassportNumber() {
        return passportNumberProperty().get();
    }

    public void setPassportNumber(String passportNumber) {
        passportNumberProperty().set(passportNumber);
    }

    public final StringProperty fullNameProperty() {
        return this.fullName;
    }

    public String getFullName() {
        return fullNameProperty().get();
    }

    public void setFullName(String fullName) {
        fullNameProperty().set(fullName);
    }

    public final StringProperty birthPlaceProperty() {
        return this.birthPlace;
    }

    public String getBirthPlace() {
        return birthPlaceProperty().get();
    }

    public void setBirthPlace(String birthPlace) {
        birthPlaceProperty().set(birthPlace);
    }

    public final ObjectProperty<Date> birthDateProperty() {
        return this.birthDate;
    }

    public Date getBirthDate() {
        return birthDateProperty().get();
    }

    public void setBirthDate(Date birthDate) {
        birthDateProperty().set(birthDate);
    }

    public final StringProperty addressProperty() {
        return this.address;
    }

    public String getAddress() {
        return addressProperty().get();
    }

    public void setAddress(String address) {
        addressProperty().set(address);
    }

    public final StringProperty rtProperty() {
        return this.rt;
    }

    public String getRt() {
        return rtProperty().get();
    }

    public void setRt(String rt) {
        rtProperty().set(rt);
    }

    public final StringProperty rwProperty() {
        return this.rw;
    }

    public String getRw() {
        return rwProperty().get();
    }

    public void setRw(String rw) {
        rwProperty().set(rw);
    }

    public final StringProperty kelurahanProperty() {
        return this.kelurahan;
    }

    public String getKelurahan() {
        return kelurahanProperty().get();
    }

    public void setKelurahan(String kelurahan) {
        kelurahanProperty().set(kelurahan);
    }

    public final StringProperty kecamatanProperty() {
        return this.kecamatan;
    }

    public String getKecamatan() {
        return kecamatanProperty().get();
    }

    public void setKecamatan(String kecamatan) {
        kecamatanProperty().set(kecamatan);
    }

    public final StringProperty townProperty() {
        return this.town;
    }

    public String getTown() {
        return townProperty().get();
    }

    public void setTown(String town) {
        townProperty().set(town);
    }

    public final StringProperty poscodeProperty() {
        return this.poscode;
    }

    public String getPoscode() {
        return poscodeProperty().get();
    }

    public void setPoscode(String poscode) {
        poscodeProperty().set(poscode);
    }

    public final StringProperty regionProperty() {
        return this.region;
    }

    public String getRegion() {
        return regionProperty().get();
    }

    public void setRegion(String region) {
        regionProperty().set(region);
    }

    public final StringProperty telpNumberProperty() {
        return this.telpNumber;
    }

    public String getTelpNumber() {
        return telpNumberProperty().get();
    }

    public void setTelpNumber(String telpNumber) {
        telpNumberProperty().set(telpNumber);
    }

    public final StringProperty hpnumberProperty() {
        return this.hpnumber;
    }

    public String getHpnumber() {
        return hpnumberProperty().get();
    }

    public void setHpnumber(String hpnumber) {
        hpnumberProperty().set(hpnumber);
    }

    public final StringProperty emailProperty() {
        return this.email;
    }

    public String getEmail() {
        return emailProperty().get();
    }

    public void setEmail(String email) {
        emailProperty().set(email);
    }

    public final StringProperty imageUrlProperty() {
        return this.imageUrl;
    }

    public String getImageUrl() {
        return imageUrlProperty().get();
    }

    public void setImageUrl(String imageUrl) {
        imageUrlProperty().set(imageUrl);
    }

    public final StringProperty peopleNoteProperty() {
        return this.peopleNote;
    }

    public String getPeopleNote() {
        return peopleNoteProperty().get();
    }

    public void setPeopleNote(String peopleNote) {
        peopleNoteProperty().set(peopleNote);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

    public Set getTblApplicants() {
        return this.tblApplicants;
    }

    public void setTblApplicants(Set tblApplicants) {
        this.tblApplicants = tblApplicants;
    }

    public Set getTblEmployees() {
        return this.tblEmployees;
    }

    public void setTblEmployees(Set tblEmployees) {
        this.tblEmployees = tblEmployees;
    }

    public Set getTblPeopleEmploymentHistories() {
        return this.tblPeopleEmploymentHistories;
    }

    public void setTblPeopleEmploymentHistories(Set tblPeopleEmploymentHistories) {
        this.tblPeopleEmploymentHistories = tblPeopleEmploymentHistories;
    }

    public Set getTblPeopleEducationHistories() {
        return this.tblPeopleEducationHistories;
    }

    public void setTblPeopleEducationHistories(Set tblPeopleEducationHistories) {
        this.tblPeopleEducationHistories = tblPeopleEducationHistories;
    }

    public Set getTblCustomers() {
        return this.tblCustomers;
    }

    public void setTblCustomers(Set tblCustomers) {
        this.tblCustomers = tblCustomers;
    }

    public Set getTblLostInformations() {
        return this.tblLostInformations;
    }

    public void setTblLostInformations(Set tblLostInformations) {
        this.tblLostInformations = tblLostInformations;
    }

    public Set getTblPeopleFamilies() {
        return this.tblPeopleFamilies;
    }

    public void setTblPeopleFamilies(Set tblPeopleFamilies) {
        this.tblPeopleFamilies = tblPeopleFamilies;
    }

    @Override
    public String toString() {
        return getFullName();
    }
    
}
