package hotelfx.persistence.model;
// Generated Aug 21, 2017 1:49:32 PM by Hibernate Tools 4.3.1

import java.util.Date;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblPartnerBankAccount generated by hbm2java
 */
public class TblPartnerBankAccount implements java.io.Serializable {

    private final LongProperty idrelation;
    private final ObjectProperty<RefBankAccountHolderStatus> refBankAccountHolderStatus;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblBankAccount> tblBankAccount;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblPartner> tblPartner;
    private final StringProperty partnerBankAccountNote;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    public TblPartnerBankAccount() {
        this.idrelation = new SimpleLongProperty();
        this.refBankAccountHolderStatus = new SimpleObjectProperty<>();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblBankAccount = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblPartner = new SimpleObjectProperty<>();
        this.partnerBankAccountNote = new SimpleStringProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

    }

    public TblPartnerBankAccount(long idrelation) {
        this();
        idrelationProperty().set(idrelation);
    }

    public TblPartnerBankAccount(long idrelation, RefBankAccountHolderStatus refBankAccountHolderStatus, RefRecordStatus refRecordStatus, TblBankAccount tblBankAccount, TblEmployee tblEmployeeByCreateBy, TblEmployee tblEmployeeByLastUpdateBy, TblPartner tblPartner, String partnerBankAccountNote, Date createDate, Date lastUpdateDate) {
        this();
        idrelationProperty().set(idrelation);
        refBankAccountHolderStatusProperty().set(refBankAccountHolderStatus);
        refRecordStatusProperty().set(refRecordStatus);
        tblBankAccountProperty().set(tblBankAccount);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblPartnerProperty().set(tblPartner);
        partnerBankAccountNoteProperty().set(partnerBankAccountNote);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

    }

    public TblPartnerBankAccount(TblPartnerBankAccount tblPartnerBankAccount) {
        this();
        idrelationProperty().set(tblPartnerBankAccount.getIdrelation());
        refBankAccountHolderStatusProperty().set(tblPartnerBankAccount.getRefBankAccountHolderStatus());
        refRecordStatusProperty().set(tblPartnerBankAccount.getRefRecordStatus());
        tblBankAccountProperty().set(tblPartnerBankAccount.getTblBankAccount());
        tblEmployeeByCreateByProperty().set(tblPartnerBankAccount.getTblEmployeeByCreateBy());
        tblEmployeeByLastUpdateByProperty().set(tblPartnerBankAccount.getTblEmployeeByLastUpdateBy());
        tblPartnerProperty().set(tblPartnerBankAccount.getTblPartner());
        partnerBankAccountNoteProperty().set(tblPartnerBankAccount.getPartnerBankAccountNote());
        createDateProperty().set(tblPartnerBankAccount.getCreateDate());
        lastUpdateDateProperty().set(tblPartnerBankAccount.getLastUpdateDate());

    }

    public final LongProperty idrelationProperty() {
        return this.idrelation;
    }

    public long getIdrelation() {
        return idrelationProperty().get();
    }

    public void setIdrelation(long idrelation) {
        idrelationProperty().set(idrelation);
    }

    public final ObjectProperty<RefBankAccountHolderStatus> refBankAccountHolderStatusProperty() {
        return this.refBankAccountHolderStatus;
    }

    public RefBankAccountHolderStatus getRefBankAccountHolderStatus() {
        return refBankAccountHolderStatusProperty().get();
    }

    public void setRefBankAccountHolderStatus(RefBankAccountHolderStatus refBankAccountHolderStatus) {
        refBankAccountHolderStatusProperty().set(refBankAccountHolderStatus);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblBankAccount> tblBankAccountProperty() {
        return this.tblBankAccount;
    }

    public TblBankAccount getTblBankAccount() {
        return tblBankAccountProperty().get();
    }

    public void setTblBankAccount(TblBankAccount tblBankAccount) {
        tblBankAccountProperty().set(tblBankAccount);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblPartner> tblPartnerProperty() {
        return this.tblPartner;
    }

    public TblPartner getTblPartner() {
        return tblPartnerProperty().get();
    }

    public void setTblPartner(TblPartner tblPartner) {
        tblPartnerProperty().set(tblPartner);
    }

    public final StringProperty partnerBankAccountNoteProperty() {
        return this.partnerBankAccountNote;
    }

    public String getPartnerBankAccountNote() {
        return partnerBankAccountNoteProperty().get();
    }

    public void setPartnerBankAccountNote(String partnerBankAccountNote) {
        partnerBankAccountNoteProperty().set(partnerBankAccountNote);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

}
