package hotelfx.persistence.model;
// Generated Aug 21, 2017 1:49:32 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblPartnerAgreement generated by hbm2java
 */
public class TblPartnerAgreement implements java.io.Serializable {

    private final LongProperty idagreement;
    private final ObjectProperty<RefPartnerAgreementStatus> refPartnerAgreementStatus;
    private final ObjectProperty<RefPartnerRateInChargeType> refPartnerRateInChargeType;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByIdpersonInCharge;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblPartner> tblPartner;
    private final StringProperty codeAgreement;
    private final ObjectProperty<BigDecimal> partnerRatePercentage;
    private final ObjectProperty<Date> beginValidDate;
    private final ObjectProperty<Date> endValidDate;
    private final StringProperty partnerInChargeName;
    private final StringProperty agreementNote;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    private Set tblReservationPaymentWithGuaranteePayments;

    public TblPartnerAgreement() {
        this.idagreement = new SimpleLongProperty();
        this.refPartnerAgreementStatus = new SimpleObjectProperty<>();
        this.refPartnerRateInChargeType = new SimpleObjectProperty<>();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByIdpersonInCharge = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblPartner = new SimpleObjectProperty<>();
        this.codeAgreement = new SimpleStringProperty();
        this.partnerRatePercentage = new SimpleObjectProperty<>();
        this.beginValidDate = new SimpleObjectProperty<>();
        this.endValidDate = new SimpleObjectProperty<>();
        this.partnerInChargeName = new SimpleStringProperty();
        this.agreementNote = new SimpleStringProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

        this.tblReservationPaymentWithGuaranteePayments = new HashSet(0);
    }

    public TblPartnerAgreement(long idagreement) {
        this();
        idagreementProperty().set(idagreement);
    }

    public TblPartnerAgreement(long idagreement, RefPartnerAgreementStatus refPartnerAgreementStatus, RefPartnerRateInChargeType refPartnerRateInChargeType, RefRecordStatus refRecordStatus, TblEmployee tblEmployeeByIdpersonInCharge, TblEmployee tblEmployeeByCreateBy, TblEmployee tblEmployeeByLastUpdateBy, TblPartner tblPartner, String codeAgreement, BigDecimal partnerRatePercentage, Date beginValidDate, Date endValidDate, String partnerInChargeName, String agreementNote, Date createDate, Date lastUpdateDate, Set tblReservationPaymentWithGuaranteePayments) {
        this();
        idagreementProperty().set(idagreement);
        refPartnerAgreementStatusProperty().set(refPartnerAgreementStatus);
        refPartnerRateInChargeTypeProperty().set(refPartnerRateInChargeType);
        refRecordStatusProperty().set(refRecordStatus);
        tblEmployeeByIdpersonInChargeProperty().set(tblEmployeeByIdpersonInCharge);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblPartnerProperty().set(tblPartner);
        codeAgreementProperty().set(codeAgreement);
        partnerRatePercentageProperty().set(partnerRatePercentage);
        beginValidDateProperty().set(beginValidDate);
        endValidDateProperty().set(endValidDate);
        partnerInChargeNameProperty().set(partnerInChargeName);
        agreementNoteProperty().set(agreementNote);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

        this.tblReservationPaymentWithGuaranteePayments = tblReservationPaymentWithGuaranteePayments;
    }

    public TblPartnerAgreement(TblPartnerAgreement tblPartnerAgreement) {
        this();
        idagreementProperty().set(tblPartnerAgreement.getIdagreement());
        refPartnerAgreementStatusProperty().set(tblPartnerAgreement.getRefPartnerAgreementStatus());
        refPartnerRateInChargeTypeProperty().set(tblPartnerAgreement.getRefPartnerRateInChargeType());
        refRecordStatusProperty().set(tblPartnerAgreement.getRefRecordStatus());
        tblEmployeeByIdpersonInChargeProperty().set(tblPartnerAgreement.getTblEmployeeByIdpersonInCharge());
        tblEmployeeByCreateByProperty().set(tblPartnerAgreement.getTblEmployeeByCreateBy());
        tblEmployeeByLastUpdateByProperty().set(tblPartnerAgreement.getTblEmployeeByLastUpdateBy());
        tblPartnerProperty().set(tblPartnerAgreement.getTblPartner());
        codeAgreementProperty().set(tblPartnerAgreement.getCodeAgreement());
        partnerRatePercentageProperty().set(tblPartnerAgreement.getPartnerRatePercentage());
        beginValidDateProperty().set(tblPartnerAgreement.getBeginValidDate());
        endValidDateProperty().set(tblPartnerAgreement.getEndValidDate());
        partnerInChargeNameProperty().set(tblPartnerAgreement.getPartnerInChargeName());
        agreementNoteProperty().set(tblPartnerAgreement.getAgreementNote());
        createDateProperty().set(tblPartnerAgreement.getCreateDate());
        lastUpdateDateProperty().set(tblPartnerAgreement.getLastUpdateDate());

        this.tblReservationPaymentWithGuaranteePayments = tblPartnerAgreement.getTblReservationPaymentWithGuaranteePayments();
    }

    public final LongProperty idagreementProperty() {
        return this.idagreement;
    }

    public long getIdagreement() {
        return idagreementProperty().get();
    }

    public void setIdagreement(long idagreement) {
        idagreementProperty().set(idagreement);
    }

    public final ObjectProperty<RefPartnerAgreementStatus> refPartnerAgreementStatusProperty() {
        return this.refPartnerAgreementStatus;
    }

    public RefPartnerAgreementStatus getRefPartnerAgreementStatus() {
        return refPartnerAgreementStatusProperty().get();
    }

    public void setRefPartnerAgreementStatus(RefPartnerAgreementStatus refPartnerAgreementStatus) {
        refPartnerAgreementStatusProperty().set(refPartnerAgreementStatus);
    }

    public final ObjectProperty<RefPartnerRateInChargeType> refPartnerRateInChargeTypeProperty() {
        return this.refPartnerRateInChargeType;
    }

    public RefPartnerRateInChargeType getRefPartnerRateInChargeType() {
        return refPartnerRateInChargeTypeProperty().get();
    }

    public void setRefPartnerRateInChargeType(RefPartnerRateInChargeType refPartnerRateInChargeType) {
        refPartnerRateInChargeTypeProperty().set(refPartnerRateInChargeType);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByIdpersonInChargeProperty() {
        return this.tblEmployeeByIdpersonInCharge;
    }

    public TblEmployee getTblEmployeeByIdpersonInCharge() {
        return tblEmployeeByIdpersonInChargeProperty().get();
    }

    public void setTblEmployeeByIdpersonInCharge(TblEmployee tblEmployeeByIdpersonInCharge) {
        tblEmployeeByIdpersonInChargeProperty().set(tblEmployeeByIdpersonInCharge);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblPartner> tblPartnerProperty() {
        return this.tblPartner;
    }

    public TblPartner getTblPartner() {
        return tblPartnerProperty().get();
    }

    public void setTblPartner(TblPartner tblPartner) {
        tblPartnerProperty().set(tblPartner);
    }

    public final StringProperty codeAgreementProperty() {
        return this.codeAgreement;
    }

    public String getCodeAgreement() {
        return codeAgreementProperty().get();
    }

    public void setCodeAgreement(String codeAgreement) {
        codeAgreementProperty().set(codeAgreement);
    }

    public final ObjectProperty<BigDecimal> partnerRatePercentageProperty() {
        return this.partnerRatePercentage;
    }

    public BigDecimal getPartnerRatePercentage() {
        return partnerRatePercentageProperty().get();
    }

    public void setPartnerRatePercentage(BigDecimal partnerRatePercentage) {
        partnerRatePercentageProperty().set(partnerRatePercentage);
    }

    public final ObjectProperty<Date> beginValidDateProperty() {
        return this.beginValidDate;
    }

    public Date getBeginValidDate() {
        return beginValidDateProperty().get();
    }

    public void setBeginValidDate(Date beginValidDate) {
        beginValidDateProperty().set(beginValidDate);
    }

    public final ObjectProperty<Date> endValidDateProperty() {
        return this.endValidDate;
    }

    public Date getEndValidDate() {
        return endValidDateProperty().get();
    }

    public void setEndValidDate(Date endValidDate) {
        endValidDateProperty().set(endValidDate);
    }

    public final StringProperty partnerInChargeNameProperty() {
        return this.partnerInChargeName;
    }

    public String getPartnerInChargeName() {
        return partnerInChargeNameProperty().get();
    }

    public void setPartnerInChargeName(String partnerInChargeName) {
        partnerInChargeNameProperty().set(partnerInChargeName);
    }

    public final StringProperty agreementNoteProperty() {
        return this.agreementNote;
    }

    public String getAgreementNote() {
        return agreementNoteProperty().get();
    }

    public void setAgreementNote(String agreementNote) {
        agreementNoteProperty().set(agreementNote);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

    public Set getTblReservationPaymentWithGuaranteePayments() {
        return this.tblReservationPaymentWithGuaranteePayments;
    }

    public void setTblReservationPaymentWithGuaranteePayments(Set tblReservationPaymentWithGuaranteePayments) {
        this.tblReservationPaymentWithGuaranteePayments = tblReservationPaymentWithGuaranteePayments;
    }

}
