package hotelfx.persistence.model;
// Generated Apr 30, 2018 8:52:05 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblPartner generated by hbm2java
 */
public class TblPartner implements java.io.Serializable {

    private final LongProperty idpartner;
    private final ObjectProperty<RefPartnerStatus> refPartnerStatus;
    private final ObjectProperty<RefPartnerType> refPartnerType;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final StringProperty codePartner;
    private final StringProperty partnerName;
    private final StringProperty partnerAddress;
    private final StringProperty telpNumber;
    private final StringProperty email;
    private final StringProperty website;
    private final StringProperty picname;
    private final StringProperty picphoneNumber;
    private final StringProperty picemailAddress;
    private final ObjectProperty<BigDecimal> partnerDeposit;
    private final StringProperty partnerNote;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    private Set tblPartnerBankAccounts;
    private Set tblHotelInvoices;
    private Set tblTravelAgents;
    private Set tblPartnerAgreements;
    private Set tblReservationPaymentWithGuaranteePayments;
    private Set tblReservationTravelAgentDiscountDetails;
    private Set tblTravelAgentRoomTypes;
    private Set tblReservations;

    public TblPartner() {
        this.idpartner = new SimpleLongProperty();
        this.refPartnerStatus = new SimpleObjectProperty<>();
        this.refPartnerType = new SimpleObjectProperty<>();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.codePartner = new SimpleStringProperty();
        this.partnerName = new SimpleStringProperty();
        this.partnerAddress = new SimpleStringProperty();
        this.telpNumber = new SimpleStringProperty();
        this.email = new SimpleStringProperty();
        this.website = new SimpleStringProperty();
        this.picname = new SimpleStringProperty();
        this.picphoneNumber = new SimpleStringProperty();
        this.picemailAddress = new SimpleStringProperty();
        this.partnerDeposit = new SimpleObjectProperty<>();
        this.partnerNote = new SimpleStringProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

        this.tblPartnerBankAccounts = new HashSet(0);
        this.tblHotelInvoices = new HashSet(0);
        this.tblTravelAgents = new HashSet(0);
        this.tblPartnerAgreements = new HashSet(0);
        this.tblReservationPaymentWithGuaranteePayments = new HashSet(0);
        this.tblReservationTravelAgentDiscountDetails = new HashSet(0);
        this.tblTravelAgentRoomTypes = new HashSet(0);
        this.tblReservations = new HashSet(0);
    }

    public TblPartner(long idpartner) {
        this();
        idpartnerProperty().set(idpartner);
    }

    public TblPartner(long idpartner, RefPartnerStatus refPartnerStatus, RefPartnerType refPartnerType, RefRecordStatus refRecordStatus, TblEmployee tblEmployeeByCreateBy, TblEmployee tblEmployeeByLastUpdateBy, String codePartner, String partnerName, String partnerAddress, String telpNumber, String email, String website, String picname, String picphoneNumber, String picemailAddress, BigDecimal partnerDeposit, String partnerNote, Date createDate, Date lastUpdateDate, Set tblPartnerBankAccounts, Set tblHotelInvoices, Set tblTravelAgents, Set tblPartnerAgreements, Set tblReservationPaymentWithGuaranteePayments, Set tblReservationTravelAgentDiscountDetails, Set tblTravelAgentRoomTypes, Set tblReservations) {
        this();
        idpartnerProperty().set(idpartner);
        refPartnerStatusProperty().set(refPartnerStatus);
        refPartnerTypeProperty().set(refPartnerType);
        refRecordStatusProperty().set(refRecordStatus);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        codePartnerProperty().set(codePartner);
        partnerNameProperty().set(partnerName);
        partnerAddressProperty().set(partnerAddress);
        telpNumberProperty().set(telpNumber);
        emailProperty().set(email);
        websiteProperty().set(website);
        picnameProperty().set(picname);
        picphoneNumberProperty().set(picphoneNumber);
        picemailAddressProperty().set(picemailAddress);
        partnerDepositProperty().set(partnerDeposit);
        partnerNoteProperty().set(partnerNote);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

        this.tblPartnerBankAccounts = tblPartnerBankAccounts;
        this.tblHotelInvoices = tblHotelInvoices;
        this.tblTravelAgents = tblTravelAgents;
        this.tblPartnerAgreements = tblPartnerAgreements;
        this.tblReservationPaymentWithGuaranteePayments = tblReservationPaymentWithGuaranteePayments;
        this.tblReservationTravelAgentDiscountDetails = tblReservationTravelAgentDiscountDetails;
        this.tblTravelAgentRoomTypes = tblTravelAgentRoomTypes;
        this.tblReservations = tblReservations;
    }

    public TblPartner(TblPartner tblPartner) {
        this();
        idpartnerProperty().set(tblPartner.getIdpartner());
        refPartnerStatusProperty().set(tblPartner.getRefPartnerStatus());
        refPartnerTypeProperty().set(tblPartner.getRefPartnerType());
        refRecordStatusProperty().set(tblPartner.getRefRecordStatus());
        tblEmployeeByCreateByProperty().set(tblPartner.getTblEmployeeByCreateBy());
        tblEmployeeByLastUpdateByProperty().set(tblPartner.getTblEmployeeByLastUpdateBy());
        codePartnerProperty().set(tblPartner.getCodePartner());
        partnerNameProperty().set(tblPartner.getPartnerName());
        partnerAddressProperty().set(tblPartner.getPartnerAddress());
        telpNumberProperty().set(tblPartner.getTelpNumber());
        emailProperty().set(tblPartner.getEmail());
        websiteProperty().set(tblPartner.getWebsite());
        picnameProperty().set(tblPartner.getPicname());
        picphoneNumberProperty().set(tblPartner.getPicphoneNumber());
        picemailAddressProperty().set(tblPartner.getPicemailAddress());
        partnerDepositProperty().set(tblPartner.getPartnerDeposit());
        partnerNoteProperty().set(tblPartner.getPartnerNote());
        createDateProperty().set(tblPartner.getCreateDate());
        lastUpdateDateProperty().set(tblPartner.getLastUpdateDate());

        this.tblPartnerBankAccounts = tblPartner.getTblPartnerBankAccounts();
        this.tblHotelInvoices = tblPartner.getTblHotelInvoices();
        this.tblTravelAgents = tblPartner.getTblTravelAgents();
        this.tblPartnerAgreements = tblPartner.getTblPartnerAgreements();
        this.tblReservationPaymentWithGuaranteePayments = tblPartner.getTblReservationPaymentWithGuaranteePayments();
        this.tblReservationTravelAgentDiscountDetails = tblPartner.getTblReservationTravelAgentDiscountDetails();
        this.tblTravelAgentRoomTypes = tblPartner.getTblTravelAgentRoomTypes();
        this.tblReservations = tblPartner.getTblReservations();
    }

    public final LongProperty idpartnerProperty() {
        return this.idpartner;
    }

    public long getIdpartner() {
        return idpartnerProperty().get();
    }

    public void setIdpartner(long idpartner) {
        idpartnerProperty().set(idpartner);
    }

    public final ObjectProperty<RefPartnerStatus> refPartnerStatusProperty() {
        return this.refPartnerStatus;
    }

    public RefPartnerStatus getRefPartnerStatus() {
        return refPartnerStatusProperty().get();
    }

    public void setRefPartnerStatus(RefPartnerStatus refPartnerStatus) {
        refPartnerStatusProperty().set(refPartnerStatus);
    }

    public final ObjectProperty<RefPartnerType> refPartnerTypeProperty() {
        return this.refPartnerType;
    }

    public RefPartnerType getRefPartnerType() {
        return refPartnerTypeProperty().get();
    }

    public void setRefPartnerType(RefPartnerType refPartnerType) {
        refPartnerTypeProperty().set(refPartnerType);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final StringProperty codePartnerProperty() {
        return this.codePartner;
    }

    public String getCodePartner() {
        return codePartnerProperty().get();
    }

    public void setCodePartner(String codePartner) {
        codePartnerProperty().set(codePartner);
    }

    public final StringProperty partnerNameProperty() {
        return this.partnerName;
    }

    public String getPartnerName() {
        return partnerNameProperty().get();
    }

    public void setPartnerName(String partnerName) {
        partnerNameProperty().set(partnerName);
    }

    public final StringProperty partnerAddressProperty() {
        return this.partnerAddress;
    }

    public String getPartnerAddress() {
        return partnerAddressProperty().get();
    }

    public void setPartnerAddress(String partnerAddress) {
        partnerAddressProperty().set(partnerAddress);
    }

    public final StringProperty telpNumberProperty() {
        return this.telpNumber;
    }

    public String getTelpNumber() {
        return telpNumberProperty().get();
    }

    public void setTelpNumber(String telpNumber) {
        telpNumberProperty().set(telpNumber);
    }

    public final StringProperty emailProperty() {
        return this.email;
    }

    public String getEmail() {
        return emailProperty().get();
    }

    public void setEmail(String email) {
        emailProperty().set(email);
    }

    public final StringProperty websiteProperty() {
        return this.website;
    }

    public String getWebsite() {
        return websiteProperty().get();
    }

    public void setWebsite(String website) {
        websiteProperty().set(website);
    }

    public final StringProperty picnameProperty() {
        return this.picname;
    }

    public String getPicname() {
        return picnameProperty().get();
    }

    public void setPicname(String picname) {
        picnameProperty().set(picname);
    }

    public final StringProperty picphoneNumberProperty() {
        return this.picphoneNumber;
    }

    public String getPicphoneNumber() {
        return picphoneNumberProperty().get();
    }

    public void setPicphoneNumber(String picphoneNumber) {
        picphoneNumberProperty().set(picphoneNumber);
    }

    public final StringProperty picemailAddressProperty() {
        return this.picemailAddress;
    }

    public String getPicemailAddress() {
        return picemailAddressProperty().get();
    }

    public void setPicemailAddress(String picemailAddress) {
        picemailAddressProperty().set(picemailAddress);
    }

    public final ObjectProperty<BigDecimal> partnerDepositProperty() {
        return this.partnerDeposit;
    }

    public BigDecimal getPartnerDeposit() {
        return partnerDepositProperty().get();
    }

    public void setPartnerDeposit(BigDecimal partnerDeposit) {
        partnerDepositProperty().set(partnerDeposit);
    }

    public final StringProperty partnerNoteProperty() {
        return this.partnerNote;
    }

    public String getPartnerNote() {
        return partnerNoteProperty().get();
    }

    public void setPartnerNote(String partnerNote) {
        partnerNoteProperty().set(partnerNote);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

    public Set getTblPartnerBankAccounts() {
        return this.tblPartnerBankAccounts;
    }

    public void setTblPartnerBankAccounts(Set tblPartnerBankAccounts) {
        this.tblPartnerBankAccounts = tblPartnerBankAccounts;
    }

    public Set getTblHotelInvoices() {
        return this.tblHotelInvoices;
    }

    public void setTblHotelInvoices(Set tblHotelInvoices) {
        this.tblHotelInvoices = tblHotelInvoices;
    }

    public Set getTblTravelAgents() {
        return this.tblTravelAgents;
    }

    public void setTblTravelAgents(Set tblTravelAgents) {
        this.tblTravelAgents = tblTravelAgents;
    }

    public Set getTblPartnerAgreements() {
        return this.tblPartnerAgreements;
    }

    public void setTblPartnerAgreements(Set tblPartnerAgreements) {
        this.tblPartnerAgreements = tblPartnerAgreements;
    }

    public Set getTblReservationPaymentWithGuaranteePayments() {
        return this.tblReservationPaymentWithGuaranteePayments;
    }

    public void setTblReservationPaymentWithGuaranteePayments(Set tblReservationPaymentWithGuaranteePayments) {
        this.tblReservationPaymentWithGuaranteePayments = tblReservationPaymentWithGuaranteePayments;
    }

    public Set getTblReservationTravelAgentDiscountDetails() {
        return this.tblReservationTravelAgentDiscountDetails;
    }

    public void setTblReservationTravelAgentDiscountDetails(Set tblReservationTravelAgentDiscountDetails) {
        this.tblReservationTravelAgentDiscountDetails = tblReservationTravelAgentDiscountDetails;
    }

    public Set getTblTravelAgentRoomTypes() {
        return this.tblTravelAgentRoomTypes;
    }

    public void setTblTravelAgentRoomTypes(Set tblTravelAgentRoomTypes) {
        this.tblTravelAgentRoomTypes = tblTravelAgentRoomTypes;
    }

    public Set getTblReservations() {
        return this.tblReservations;
    }

    public void setTblReservations(Set tblReservations) {
        this.tblReservations = tblReservations;
    }
    
    @Override
    public String toString() {
        return getPartnerName();
    }

}
