package hotelfx.persistence.model;
// Generated Aug 7, 2018 12:29:52 PM by Hibernate Tools 4.3.1

import java.util.Date;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblPurchaseOrderRevisionHistory generated by hbm2java
 */
public class TblPurchaseOrderRevisionHistory implements java.io.Serializable {

    private final LongProperty idporevisionHistory;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByIdemployee;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblPurchaseOrder> tblPurchaseOrderByIdposource;
    private final ObjectProperty<TblPurchaseOrder> tblPurchaseOrderByIdponew;
    private final ObjectProperty<Date> revisionDate;
    private final StringProperty revisionReason;
    private final StringProperty revisionNote;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    public TblPurchaseOrderRevisionHistory() {
        this.idporevisionHistory = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByIdemployee = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblPurchaseOrderByIdposource = new SimpleObjectProperty<>();
        this.tblPurchaseOrderByIdponew = new SimpleObjectProperty<>();
        this.revisionDate = new SimpleObjectProperty<>();
        this.revisionReason = new SimpleStringProperty();
        this.revisionNote = new SimpleStringProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

    }

    public TblPurchaseOrderRevisionHistory(long idporevisionHistory) {
        this();
        idporevisionHistoryProperty().set(idporevisionHistory);
    }

    public TblPurchaseOrderRevisionHistory(long idporevisionHistory, RefRecordStatus refRecordStatus, TblEmployee tblEmployeeByCreateBy, TblEmployee tblEmployeeByIdemployee, TblEmployee tblEmployeeByLastUpdateBy, TblPurchaseOrder tblPurchaseOrderByIdposource, TblPurchaseOrder tblPurchaseOrderByIdponew, Date revisionDate, String revisionReason, String revisionNote, Date createDate, Date lastUpdateDate) {
        this();
        idporevisionHistoryProperty().set(idporevisionHistory);
        refRecordStatusProperty().set(refRecordStatus);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblEmployeeByIdemployeeProperty().set(tblEmployeeByIdemployee);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblPurchaseOrderByIdposourceProperty().set(tblPurchaseOrderByIdposource);
        tblPurchaseOrderByIdponewProperty().set(tblPurchaseOrderByIdponew);
        revisionDateProperty().set(revisionDate);
        revisionReasonProperty().set(revisionReason);
        revisionNoteProperty().set(revisionNote);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

    }

    public TblPurchaseOrderRevisionHistory(TblPurchaseOrderRevisionHistory tblPurchaseOrderRevisionHistory) {
        this();
        idporevisionHistoryProperty().set(tblPurchaseOrderRevisionHistory.getIdporevisionHistory());
        refRecordStatusProperty().set(tblPurchaseOrderRevisionHistory.getRefRecordStatus());
        tblEmployeeByCreateByProperty().set(tblPurchaseOrderRevisionHistory.getTblEmployeeByCreateBy());
        tblEmployeeByIdemployeeProperty().set(tblPurchaseOrderRevisionHistory.getTblEmployeeByIdemployee());
        tblEmployeeByLastUpdateByProperty().set(tblPurchaseOrderRevisionHistory.getTblEmployeeByLastUpdateBy());
        tblPurchaseOrderByIdposourceProperty().set(tblPurchaseOrderRevisionHistory.getTblPurchaseOrderByIdposource());
        tblPurchaseOrderByIdponewProperty().set(tblPurchaseOrderRevisionHistory.getTblPurchaseOrderByIdponew());
        revisionDateProperty().set(tblPurchaseOrderRevisionHistory.getRevisionDate());
        revisionReasonProperty().set(tblPurchaseOrderRevisionHistory.getRevisionReason());
        revisionNoteProperty().set(tblPurchaseOrderRevisionHistory.getRevisionNote());
        createDateProperty().set(tblPurchaseOrderRevisionHistory.getCreateDate());
        lastUpdateDateProperty().set(tblPurchaseOrderRevisionHistory.getLastUpdateDate());

    }

    public final LongProperty idporevisionHistoryProperty() {
        return this.idporevisionHistory;
    }

    public long getIdporevisionHistory() {
        return idporevisionHistoryProperty().get();
    }

    public void setIdporevisionHistory(long idporevisionHistory) {
        idporevisionHistoryProperty().set(idporevisionHistory);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByIdemployeeProperty() {
        return this.tblEmployeeByIdemployee;
    }

    public TblEmployee getTblEmployeeByIdemployee() {
        return tblEmployeeByIdemployeeProperty().get();
    }

    public void setTblEmployeeByIdemployee(TblEmployee tblEmployeeByIdemployee) {
        tblEmployeeByIdemployeeProperty().set(tblEmployeeByIdemployee);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblPurchaseOrder> tblPurchaseOrderByIdposourceProperty() {
        return this.tblPurchaseOrderByIdposource;
    }

    public TblPurchaseOrder getTblPurchaseOrderByIdposource() {
        return tblPurchaseOrderByIdposourceProperty().get();
    }

    public void setTblPurchaseOrderByIdposource(TblPurchaseOrder tblPurchaseOrderByIdposource) {
        tblPurchaseOrderByIdposourceProperty().set(tblPurchaseOrderByIdposource);
    }

    public final ObjectProperty<TblPurchaseOrder> tblPurchaseOrderByIdponewProperty() {
        return this.tblPurchaseOrderByIdponew;
    }

    public TblPurchaseOrder getTblPurchaseOrderByIdponew() {
        return tblPurchaseOrderByIdponewProperty().get();
    }

    public void setTblPurchaseOrderByIdponew(TblPurchaseOrder tblPurchaseOrderByIdponew) {
        tblPurchaseOrderByIdponewProperty().set(tblPurchaseOrderByIdponew);
    }

    public final ObjectProperty<Date> revisionDateProperty() {
        return this.revisionDate;
    }

    public Date getRevisionDate() {
        return revisionDateProperty().get();
    }

    public void setRevisionDate(Date revisionDate) {
        revisionDateProperty().set(revisionDate);
    }

    public final StringProperty revisionReasonProperty() {
        return this.revisionReason;
    }

    public String getRevisionReason() {
        return revisionReasonProperty().get();
    }

    public void setRevisionReason(String revisionReason) {
        revisionReasonProperty().set(revisionReason);
    }

    public final StringProperty revisionNoteProperty() {
        return this.revisionNote;
    }

    public String getRevisionNote() {
        return revisionNoteProperty().get();
    }

    public void setRevisionNote(String revisionNote) {
        revisionNoteProperty().set(revisionNote);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

}
