package hotelfx.persistence.model;
// Generated Apr 25, 2018 3:21:41 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;

/**
 * TblReservationRoomTypeDetailItem generated by hbm2java
 */
public class TblReservationRoomTypeDetailItem implements java.io.Serializable {

    private final LongProperty idrelation;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblItem> tblItem;
    private final ObjectProperty<TblReservationRoomTypeDetail> tblReservationRoomTypeDetail;
    private final ObjectProperty<BigDecimal> itemAdditionalCharge;
    private final ObjectProperty<BigDecimal> itemBrokenCharge;
    private final ObjectProperty<BigDecimal> itemQuantity;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    public TblReservationRoomTypeDetailItem() {
        this.idrelation = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblItem = new SimpleObjectProperty<>();
        this.tblReservationRoomTypeDetail = new SimpleObjectProperty<>();
        this.itemAdditionalCharge = new SimpleObjectProperty<>();
        this.itemBrokenCharge = new SimpleObjectProperty<>();
        this.itemQuantity = new SimpleObjectProperty<>();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

    }

    public TblReservationRoomTypeDetailItem(long idrelation) {
        this();
        idrelationProperty().set(idrelation);
    }

    public TblReservationRoomTypeDetailItem(long idrelation, RefRecordStatus refRecordStatus, TblEmployee tblEmployeeByCreateBy, TblEmployee tblEmployeeByLastUpdateBy, TblItem tblItem, TblReservationRoomTypeDetail tblReservationRoomTypeDetail, BigDecimal itemAdditionalCharge, BigDecimal itemBrokenCharge, BigDecimal itemQuantity, Date createDate, Date lastUpdateDate) {
        this();
        idrelationProperty().set(idrelation);
        refRecordStatusProperty().set(refRecordStatus);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblItemProperty().set(tblItem);
        tblReservationRoomTypeDetailProperty().set(tblReservationRoomTypeDetail);
        itemAdditionalChargeProperty().set(itemAdditionalCharge);
        itemBrokenChargeProperty().set(itemBrokenCharge);
        itemQuantityProperty().set(itemQuantity);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

    }

    public TblReservationRoomTypeDetailItem(TblReservationRoomTypeDetailItem tblReservationRoomTypeDetailItem) {
        this();
        idrelationProperty().set(tblReservationRoomTypeDetailItem.getIdrelation());
        refRecordStatusProperty().set(tblReservationRoomTypeDetailItem.getRefRecordStatus());
        tblEmployeeByCreateByProperty().set(tblReservationRoomTypeDetailItem.getTblEmployeeByCreateBy());
        tblEmployeeByLastUpdateByProperty().set(tblReservationRoomTypeDetailItem.getTblEmployeeByLastUpdateBy());
        tblItemProperty().set(tblReservationRoomTypeDetailItem.getTblItem());
        tblReservationRoomTypeDetailProperty().set(tblReservationRoomTypeDetailItem.getTblReservationRoomTypeDetail());
        itemAdditionalChargeProperty().set(tblReservationRoomTypeDetailItem.getItemAdditionalCharge());
        itemBrokenChargeProperty().set(tblReservationRoomTypeDetailItem.getItemBrokenCharge());
        itemQuantityProperty().set(tblReservationRoomTypeDetailItem.getItemQuantity());
        createDateProperty().set(tblReservationRoomTypeDetailItem.getCreateDate());
        lastUpdateDateProperty().set(tblReservationRoomTypeDetailItem.getLastUpdateDate());

    }

    public final LongProperty idrelationProperty() {
        return this.idrelation;
    }

    public long getIdrelation() {
        return idrelationProperty().get();
    }

    public void setIdrelation(long idrelation) {
        idrelationProperty().set(idrelation);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblItem> tblItemProperty() {
        return this.tblItem;
    }

    public TblItem getTblItem() {
        return tblItemProperty().get();
    }

    public void setTblItem(TblItem tblItem) {
        tblItemProperty().set(tblItem);
    }

    public final ObjectProperty<TblReservationRoomTypeDetail> tblReservationRoomTypeDetailProperty() {
        return this.tblReservationRoomTypeDetail;
    }

    public TblReservationRoomTypeDetail getTblReservationRoomTypeDetail() {
        return tblReservationRoomTypeDetailProperty().get();
    }

    public void setTblReservationRoomTypeDetail(TblReservationRoomTypeDetail tblReservationRoomTypeDetail) {
        tblReservationRoomTypeDetailProperty().set(tblReservationRoomTypeDetail);
    }

    public final ObjectProperty<BigDecimal> itemAdditionalChargeProperty() {
        return this.itemAdditionalCharge;
    }

    public BigDecimal getItemAdditionalCharge() {
        return itemAdditionalChargeProperty().get();
    }

    public void setItemAdditionalCharge(BigDecimal itemAdditionalCharge) {
        itemAdditionalChargeProperty().set(itemAdditionalCharge);
    }

    public final ObjectProperty<BigDecimal> itemBrokenChargeProperty() {
        return this.itemBrokenCharge;
    }

    public BigDecimal getItemBrokenCharge() {
        return itemBrokenChargeProperty().get();
    }

    public void setItemBrokenCharge(BigDecimal itemBrokenCharge) {
        itemBrokenChargeProperty().set(itemBrokenCharge);
    }

    public final ObjectProperty<BigDecimal> itemQuantityProperty() {
        return this.itemQuantity;
    }

    public BigDecimal getItemQuantity() {
        return itemQuantityProperty().get();
    }

    public void setItemQuantity(BigDecimal itemQuantity) {
        itemQuantityProperty().set(itemQuantity);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

}
