package hotelfx.persistence.model;
// Generated Jul 3, 2018 12:53:45 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblReturDetail generated by hbm2java
 */
public class TblReturDetail implements java.io.Serializable {

    private final LongProperty iddetailRetur;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblLocation> tblLocation;
    private final ObjectProperty<TblMemorandumInvoice> tblMemorandumInvoice;
    private final ObjectProperty<TblRetur> tblRetur;
    private final ObjectProperty<TblSupplierItem> tblSupplierItem;
    private final ObjectProperty<BigDecimal> itemCost;
    private final ObjectProperty<BigDecimal> itemQuantity;
    private final ObjectProperty<BigDecimal> itemDiscount;
    private final ObjectProperty<BigDecimal> itemTaxPercentage;
    private final StringProperty itemNote;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    private Set tblReturDetailItemExpiredDates;
    private Set tblReturDetailPropertyBarcodes;

    public TblReturDetail() {
        this.iddetailRetur = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblLocation = new SimpleObjectProperty<>();
        this.tblMemorandumInvoice = new SimpleObjectProperty<>();
        this.tblRetur = new SimpleObjectProperty<>();
        this.tblSupplierItem = new SimpleObjectProperty<>();
        this.itemCost = new SimpleObjectProperty<>();
        this.itemQuantity = new SimpleObjectProperty<>();
        this.itemDiscount = new SimpleObjectProperty<>();
        this.itemTaxPercentage = new SimpleObjectProperty<>();
        this.itemNote = new SimpleStringProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

        this.tblReturDetailItemExpiredDates = new HashSet(0);
        this.tblReturDetailPropertyBarcodes = new HashSet(0);
    }

    public TblReturDetail(long iddetailRetur) {
        this();
        iddetailReturProperty().set(iddetailRetur);
    }

    public TblReturDetail(long iddetailRetur, RefRecordStatus refRecordStatus, TblEmployee tblEmployeeByCreateBy, TblEmployee tblEmployeeByLastUpdateBy, TblLocation tblLocation, TblMemorandumInvoice tblMemorandumInvoice, TblRetur tblRetur, TblSupplierItem tblSupplierItem, BigDecimal itemCost, BigDecimal itemQuantity, BigDecimal itemDiscount, BigDecimal itemTaxPercentage, String itemNote, Date createDate, Date lastUpdateDate, Set tblReturDetailItemExpiredDates, Set tblReturDetailPropertyBarcodes) {
        this();
        iddetailReturProperty().set(iddetailRetur);
        refRecordStatusProperty().set(refRecordStatus);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblLocationProperty().set(tblLocation);
        tblMemorandumInvoiceProperty().set(tblMemorandumInvoice);
        tblReturProperty().set(tblRetur);
        tblSupplierItemProperty().set(tblSupplierItem);
        itemCostProperty().set(itemCost);
        itemQuantityProperty().set(itemQuantity);
        itemDiscountProperty().set(itemDiscount);
        itemTaxPercentageProperty().set(itemTaxPercentage);
        itemNoteProperty().set(itemNote);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

        this.tblReturDetailItemExpiredDates = tblReturDetailItemExpiredDates;
        this.tblReturDetailPropertyBarcodes = tblReturDetailPropertyBarcodes;
    }

    public TblReturDetail(TblReturDetail tblReturDetail) {
        this();
        iddetailReturProperty().set(tblReturDetail.getIddetailRetur());
        refRecordStatusProperty().set(tblReturDetail.getRefRecordStatus());
        tblEmployeeByCreateByProperty().set(tblReturDetail.getTblEmployeeByCreateBy());
        tblEmployeeByLastUpdateByProperty().set(tblReturDetail.getTblEmployeeByLastUpdateBy());
        tblLocationProperty().set(tblReturDetail.getTblLocation());
        tblMemorandumInvoiceProperty().set(tblReturDetail.getTblMemorandumInvoice());
        tblReturProperty().set(tblReturDetail.getTblRetur());
        tblSupplierItemProperty().set(tblReturDetail.getTblSupplierItem());
        itemCostProperty().set(tblReturDetail.getItemCost());
        itemQuantityProperty().set(tblReturDetail.getItemQuantity());
        itemDiscountProperty().set(tblReturDetail.getItemDiscount());
        itemTaxPercentageProperty().set(tblReturDetail.getItemTaxPercentage());
        itemNoteProperty().set(tblReturDetail.getItemNote());
        createDateProperty().set(tblReturDetail.getCreateDate());
        lastUpdateDateProperty().set(tblReturDetail.getLastUpdateDate());

        this.tblReturDetailItemExpiredDates = tblReturDetail.getTblReturDetailItemExpiredDates();
        this.tblReturDetailPropertyBarcodes = tblReturDetail.getTblReturDetailPropertyBarcodes();
    }

    public final LongProperty iddetailReturProperty() {
        return this.iddetailRetur;
    }

    public long getIddetailRetur() {
        return iddetailReturProperty().get();
    }

    public void setIddetailRetur(long iddetailRetur) {
        iddetailReturProperty().set(iddetailRetur);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblLocation> tblLocationProperty() {
        return this.tblLocation;
    }

    public TblLocation getTblLocation() {
        return tblLocationProperty().get();
    }

    public void setTblLocation(TblLocation tblLocation) {
        tblLocationProperty().set(tblLocation);
    }

    public final ObjectProperty<TblMemorandumInvoice> tblMemorandumInvoiceProperty() {
        return this.tblMemorandumInvoice;
    }

    public TblMemorandumInvoice getTblMemorandumInvoice() {
        return tblMemorandumInvoiceProperty().get();
    }

    public void setTblMemorandumInvoice(TblMemorandumInvoice tblMemorandumInvoice) {
        tblMemorandumInvoiceProperty().set(tblMemorandumInvoice);
    }

    public final ObjectProperty<TblRetur> tblReturProperty() {
        return this.tblRetur;
    }

    public TblRetur getTblRetur() {
        return tblReturProperty().get();
    }

    public void setTblRetur(TblRetur tblRetur) {
        tblReturProperty().set(tblRetur);
    }

    public final ObjectProperty<TblSupplierItem> tblSupplierItemProperty() {
        return this.tblSupplierItem;
    }

    public TblSupplierItem getTblSupplierItem() {
        return tblSupplierItemProperty().get();
    }

    public void setTblSupplierItem(TblSupplierItem tblSupplierItem) {
        tblSupplierItemProperty().set(tblSupplierItem);
    }

    public final ObjectProperty<BigDecimal> itemCostProperty() {
        return this.itemCost;
    }

    public BigDecimal getItemCost() {
        return itemCostProperty().get();
    }

    public void setItemCost(BigDecimal itemCost) {
        itemCostProperty().set(itemCost);
    }

    public final ObjectProperty<BigDecimal> itemQuantityProperty() {
        return this.itemQuantity;
    }

    public BigDecimal getItemQuantity() {
        return itemQuantityProperty().get();
    }

    public void setItemQuantity(BigDecimal itemQuantity) {
        itemQuantityProperty().set(itemQuantity);
    }

    public final ObjectProperty<BigDecimal> itemDiscountProperty() {
        return this.itemDiscount;
    }

    public BigDecimal getItemDiscount() {
        return itemDiscountProperty().get();
    }

    public void setItemDiscount(BigDecimal itemDiscount) {
        itemDiscountProperty().set(itemDiscount);
    }

    public final ObjectProperty<BigDecimal> itemTaxPercentageProperty() {
        return this.itemTaxPercentage;
    }

    public BigDecimal getItemTaxPercentage() {
        return itemTaxPercentageProperty().get();
    }

    public void setItemTaxPercentage(BigDecimal itemTaxPercentage) {
        itemTaxPercentageProperty().set(itemTaxPercentage);
    }

    public final StringProperty itemNoteProperty() {
        return this.itemNote;
    }

    public String getItemNote() {
        return itemNoteProperty().get();
    }

    public void setItemNote(String itemNote) {
        itemNoteProperty().set(itemNote);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

    public Set getTblReturDetailItemExpiredDates() {
        return this.tblReturDetailItemExpiredDates;
    }

    public void setTblReturDetailItemExpiredDates(Set tblReturDetailItemExpiredDates) {
        this.tblReturDetailItemExpiredDates = tblReturDetailItemExpiredDates;
    }

    public Set getTblReturDetailPropertyBarcodes() {
        return this.tblReturDetailPropertyBarcodes;
    }

    public void setTblReturDetailPropertyBarcodes(Set tblReturDetailPropertyBarcodes) {
        this.tblReturDetailPropertyBarcodes = tblReturDetailPropertyBarcodes;
    }

}
