package hotelfx.persistence.model;
// Generated Aug 31, 2017 4:11:59 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;

/**
 * TblReservationTravelAgentDiscountDetail generated by hbm2java
 */
public class TblReservationTravelAgentDiscountDetail implements java.io.Serializable {

    private final LongProperty iddetail;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblPartner> tblPartner;
    private final ObjectProperty<BigDecimal> detailDiscount;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    private Set tblReservationRoomTypeDetailTravelAgentDiscountDetails;

    public TblReservationTravelAgentDiscountDetail() {
        this.iddetail = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblPartner = new SimpleObjectProperty<>();
        this.detailDiscount = new SimpleObjectProperty<>();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

        this.tblReservationRoomTypeDetailTravelAgentDiscountDetails = new HashSet(0);
    }

    public TblReservationTravelAgentDiscountDetail(long iddetail) {
        this();
        iddetailProperty().set(iddetail);
    }

    public TblReservationTravelAgentDiscountDetail(long iddetail, RefRecordStatus refRecordStatus, TblEmployee tblEmployeeByCreateBy, TblEmployee tblEmployeeByLastUpdateBy, TblPartner tblPartner, BigDecimal detailDiscount, Date createDate, Date lastUpdateDate, Set tblReservationRoomTypeDetailTravelAgentDiscountDetails) {
        this();
        iddetailProperty().set(iddetail);
        refRecordStatusProperty().set(refRecordStatus);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblPartnerProperty().set(tblPartner);
        detailDiscountProperty().set(detailDiscount);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

        this.tblReservationRoomTypeDetailTravelAgentDiscountDetails = tblReservationRoomTypeDetailTravelAgentDiscountDetails;
    }

    public TblReservationTravelAgentDiscountDetail(TblReservationTravelAgentDiscountDetail tblReservationTravelAgentDiscountDetail) {
        this();
        iddetailProperty().set(tblReservationTravelAgentDiscountDetail.getIddetail());
        refRecordStatusProperty().set(tblReservationTravelAgentDiscountDetail.getRefRecordStatus());
        tblEmployeeByCreateByProperty().set(tblReservationTravelAgentDiscountDetail.getTblEmployeeByCreateBy());
        tblEmployeeByLastUpdateByProperty().set(tblReservationTravelAgentDiscountDetail.getTblEmployeeByLastUpdateBy());
        tblPartnerProperty().set(tblReservationTravelAgentDiscountDetail.getTblPartner());
        detailDiscountProperty().set(tblReservationTravelAgentDiscountDetail.getDetailDiscount());
        createDateProperty().set(tblReservationTravelAgentDiscountDetail.getCreateDate());
        lastUpdateDateProperty().set(tblReservationTravelAgentDiscountDetail.getLastUpdateDate());

        this.tblReservationRoomTypeDetailTravelAgentDiscountDetails = tblReservationTravelAgentDiscountDetail.getTblReservationRoomTypeDetailTravelAgentDiscountDetails();
    }

    public final LongProperty iddetailProperty() {
        return this.iddetail;
    }

    public long getIddetail() {
        return iddetailProperty().get();
    }

    public void setIddetail(long iddetail) {
        iddetailProperty().set(iddetail);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblPartner> tblPartnerProperty() {
        return this.tblPartner;
    }

    public TblPartner getTblPartner() {
        return tblPartnerProperty().get();
    }

    public void setTblPartner(TblPartner tblPartner) {
        tblPartnerProperty().set(tblPartner);
    }

    public final ObjectProperty<BigDecimal> detailDiscountProperty() {
        return this.detailDiscount;
    }

    public BigDecimal getDetailDiscount() {
        return detailDiscountProperty().get();
    }

    public void setDetailDiscount(BigDecimal detailDiscount) {
        detailDiscountProperty().set(detailDiscount);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

    public Set getTblReservationRoomTypeDetailTravelAgentDiscountDetails() {
        return this.tblReservationRoomTypeDetailTravelAgentDiscountDetails;
    }

    public void setTblReservationRoomTypeDetailTravelAgentDiscountDetails(Set tblReservationRoomTypeDetailTravelAgentDiscountDetails) {
        this.tblReservationRoomTypeDetailTravelAgentDiscountDetails = tblReservationRoomTypeDetailTravelAgentDiscountDetails;
    }

}
