package hotelfx.persistence.model;
// Generated Aug 21, 2017 1:49:32 PM by Hibernate Tools 4.3.1

import java.util.Date;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblReservationPaymentWithReservationVoucher generated by hbm2java
 */
public class TblReservationPaymentWithReservationVoucher implements java.io.Serializable {

    private final LongProperty iddetail;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblReservationPayment> tblReservationPayment;
    private final ObjectProperty<TblReservationVoucher> tblReservationVoucher;
    private final StringProperty reservationVoucherNote;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    public TblReservationPaymentWithReservationVoucher() {
        this.iddetail = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblReservationPayment = new SimpleObjectProperty<>();
        this.tblReservationVoucher = new SimpleObjectProperty<>();
        this.reservationVoucherNote = new SimpleStringProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

    }

    public TblReservationPaymentWithReservationVoucher(long iddetail) {
        this();
        iddetailProperty().set(iddetail);
    }

    public TblReservationPaymentWithReservationVoucher(long iddetail, RefRecordStatus refRecordStatus, TblEmployee tblEmployeeByLastUpdateBy, TblEmployee tblEmployeeByCreateBy, TblReservationPayment tblReservationPayment, TblReservationVoucher tblReservationVoucher, String reservationVoucherNote, Date createDate, Date lastUpdateDate) {
        this();
        iddetailProperty().set(iddetail);
        refRecordStatusProperty().set(refRecordStatus);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblReservationPaymentProperty().set(tblReservationPayment);
        tblReservationVoucherProperty().set(tblReservationVoucher);
        reservationVoucherNoteProperty().set(reservationVoucherNote);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

    }

    public TblReservationPaymentWithReservationVoucher(TblReservationPaymentWithReservationVoucher tblReservationPaymentWithReservationVoucher) {
        this();
        iddetailProperty().set(tblReservationPaymentWithReservationVoucher.getIddetail());
        refRecordStatusProperty().set(tblReservationPaymentWithReservationVoucher.getRefRecordStatus());
        tblEmployeeByLastUpdateByProperty().set(tblReservationPaymentWithReservationVoucher.getTblEmployeeByLastUpdateBy());
        tblEmployeeByCreateByProperty().set(tblReservationPaymentWithReservationVoucher.getTblEmployeeByCreateBy());
        tblReservationPaymentProperty().set(tblReservationPaymentWithReservationVoucher.getTblReservationPayment());
        tblReservationVoucherProperty().set(tblReservationPaymentWithReservationVoucher.getTblReservationVoucher());
        reservationVoucherNoteProperty().set(tblReservationPaymentWithReservationVoucher.getReservationVoucherNote());
        createDateProperty().set(tblReservationPaymentWithReservationVoucher.getCreateDate());
        lastUpdateDateProperty().set(tblReservationPaymentWithReservationVoucher.getLastUpdateDate());

    }

    public final LongProperty iddetailProperty() {
        return this.iddetail;
    }

    public long getIddetail() {
        return iddetailProperty().get();
    }

    public void setIddetail(long iddetail) {
        iddetailProperty().set(iddetail);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblReservationPayment> tblReservationPaymentProperty() {
        return this.tblReservationPayment;
    }

    public TblReservationPayment getTblReservationPayment() {
        return tblReservationPaymentProperty().get();
    }

    public void setTblReservationPayment(TblReservationPayment tblReservationPayment) {
        tblReservationPaymentProperty().set(tblReservationPayment);
    }

    public final ObjectProperty<TblReservationVoucher> tblReservationVoucherProperty() {
        return this.tblReservationVoucher;
    }

    public TblReservationVoucher getTblReservationVoucher() {
        return tblReservationVoucherProperty().get();
    }

    public void setTblReservationVoucher(TblReservationVoucher tblReservationVoucher) {
        tblReservationVoucherProperty().set(tblReservationVoucher);
    }

    public final StringProperty reservationVoucherNoteProperty() {
        return this.reservationVoucherNote;
    }

    public String getReservationVoucherNote() {
        return reservationVoucherNoteProperty().get();
    }

    public void setReservationVoucherNote(String reservationVoucherNote) {
        reservationVoucherNoteProperty().set(reservationVoucherNote);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

}
