package hotelfx.persistence.model;
// Generated Apr 19, 2018 11:15:52 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

import javafx.beans.property.BooleanProperty;
import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleBooleanProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblReservationAdditionalItem generated by hbm2java
 */
public class TblReservationAdditionalItem implements java.io.Serializable {

    private final LongProperty idadditional;
    private final ObjectProperty<RefEndOfDayDataStatus> refEndOfDayDataStatus;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<RefReservationBillType> refReservationBillType;
    private final ObjectProperty<TblBankEventCard> tblBankEventCard;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblHotelEvent> tblHotelEvent;
    private final ObjectProperty<TblItem> tblItem;
    private final ObjectProperty<TblReservationRoomTypeDetail> tblReservationRoomTypeDetail;
    private final ObjectProperty<Date> additionalDate;
    private final ObjectProperty<BigDecimal> itemCharge;
    private final ObjectProperty<BigDecimal> itemQuantity;
    private final ObjectProperty<BigDecimal> discountPercentage;
    private final BooleanProperty taxable;
    private final StringProperty note;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    public TblReservationAdditionalItem() {
        this.idadditional = new SimpleLongProperty();
        this.refEndOfDayDataStatus = new SimpleObjectProperty<>();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.refReservationBillType = new SimpleObjectProperty<>();
        this.tblBankEventCard = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblHotelEvent = new SimpleObjectProperty<>();
        this.tblItem = new SimpleObjectProperty<>();
        this.tblReservationRoomTypeDetail = new SimpleObjectProperty<>();
        this.additionalDate = new SimpleObjectProperty<>();
        this.itemCharge = new SimpleObjectProperty<>();
        this.itemQuantity = new SimpleObjectProperty<>();
        this.discountPercentage = new SimpleObjectProperty<>();
        this.taxable = new SimpleBooleanProperty();
        this.note = new SimpleStringProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

    }

    public TblReservationAdditionalItem(long idadditional) {
        this();
        idadditionalProperty().set(idadditional);
    }

    public TblReservationAdditionalItem(long idadditional, RefEndOfDayDataStatus refEndOfDayDataStatus, RefRecordStatus refRecordStatus, RefReservationBillType refReservationBillType, TblBankEventCard tblBankEventCard, TblEmployee tblEmployeeByLastUpdateBy, TblEmployee tblEmployeeByCreateBy, TblHotelEvent tblHotelEvent, TblItem tblItem, TblReservationRoomTypeDetail tblReservationRoomTypeDetail, Date additionalDate, BigDecimal itemCharge, BigDecimal itemQuantity, BigDecimal discountPercentage, Boolean taxable, String note, Date createDate, Date lastUpdateDate) {
        this();
        idadditionalProperty().set(idadditional);
        refEndOfDayDataStatusProperty().set(refEndOfDayDataStatus);
        refRecordStatusProperty().set(refRecordStatus);
        refReservationBillTypeProperty().set(refReservationBillType);
        tblBankEventCardProperty().set(tblBankEventCard);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblHotelEventProperty().set(tblHotelEvent);
        tblItemProperty().set(tblItem);
        tblReservationRoomTypeDetailProperty().set(tblReservationRoomTypeDetail);
        additionalDateProperty().set(additionalDate);
        itemChargeProperty().set(itemCharge);
        itemQuantityProperty().set(itemQuantity);
        discountPercentageProperty().set(discountPercentage);
        taxableProperty().set(taxable);
        noteProperty().set(note);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

    }

    public TblReservationAdditionalItem(TblReservationAdditionalItem tblReservationAdditionalItem) {
        this();
        idadditionalProperty().set(tblReservationAdditionalItem.getIdadditional());
        refEndOfDayDataStatusProperty().set(tblReservationAdditionalItem.getRefEndOfDayDataStatus());
        refRecordStatusProperty().set(tblReservationAdditionalItem.getRefRecordStatus());
        refReservationBillTypeProperty().set(tblReservationAdditionalItem.getRefReservationBillType());
        tblBankEventCardProperty().set(tblReservationAdditionalItem.getTblBankEventCard());
        tblEmployeeByLastUpdateByProperty().set(tblReservationAdditionalItem.getTblEmployeeByLastUpdateBy());
        tblEmployeeByCreateByProperty().set(tblReservationAdditionalItem.getTblEmployeeByCreateBy());
        tblHotelEventProperty().set(tblReservationAdditionalItem.getTblHotelEvent());
        tblItemProperty().set(tblReservationAdditionalItem.getTblItem());
        tblReservationRoomTypeDetailProperty().set(tblReservationAdditionalItem.getTblReservationRoomTypeDetail());
        additionalDateProperty().set(tblReservationAdditionalItem.getAdditionalDate());
        itemChargeProperty().set(tblReservationAdditionalItem.getItemCharge());
        itemQuantityProperty().set(tblReservationAdditionalItem.getItemQuantity());
        discountPercentageProperty().set(tblReservationAdditionalItem.getDiscountPercentage());
        taxableProperty().set(tblReservationAdditionalItem.getTaxable());
        noteProperty().set(tblReservationAdditionalItem.getNote());
        createDateProperty().set(tblReservationAdditionalItem.getCreateDate());
        lastUpdateDateProperty().set(tblReservationAdditionalItem.getLastUpdateDate());

    }

    public final LongProperty idadditionalProperty() {
        return this.idadditional;
    }

    public long getIdadditional() {
        return idadditionalProperty().get();
    }

    public void setIdadditional(long idadditional) {
        idadditionalProperty().set(idadditional);
    }

    public final ObjectProperty<RefEndOfDayDataStatus> refEndOfDayDataStatusProperty() {
        return this.refEndOfDayDataStatus;
    }

    public RefEndOfDayDataStatus getRefEndOfDayDataStatus() {
        return refEndOfDayDataStatusProperty().get();
    }

    public void setRefEndOfDayDataStatus(RefEndOfDayDataStatus refEndOfDayDataStatus) {
        refEndOfDayDataStatusProperty().set(refEndOfDayDataStatus);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<RefReservationBillType> refReservationBillTypeProperty() {
        return this.refReservationBillType;
    }

    public RefReservationBillType getRefReservationBillType() {
        return refReservationBillTypeProperty().get();
    }

    public void setRefReservationBillType(RefReservationBillType refReservationBillType) {
        refReservationBillTypeProperty().set(refReservationBillType);
    }

    public final ObjectProperty<TblBankEventCard> tblBankEventCardProperty() {
        return this.tblBankEventCard;
    }

    public TblBankEventCard getTblBankEventCard() {
        return tblBankEventCardProperty().get();
    }

    public void setTblBankEventCard(TblBankEventCard tblBankEventCard) {
        tblBankEventCardProperty().set(tblBankEventCard);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblHotelEvent> tblHotelEventProperty() {
        return this.tblHotelEvent;
    }

    public TblHotelEvent getTblHotelEvent() {
        return tblHotelEventProperty().get();
    }

    public void setTblHotelEvent(TblHotelEvent tblHotelEvent) {
        tblHotelEventProperty().set(tblHotelEvent);
    }

    public final ObjectProperty<TblItem> tblItemProperty() {
        return this.tblItem;
    }

    public TblItem getTblItem() {
        return tblItemProperty().get();
    }

    public void setTblItem(TblItem tblItem) {
        tblItemProperty().set(tblItem);
    }

    public final ObjectProperty<TblReservationRoomTypeDetail> tblReservationRoomTypeDetailProperty() {
        return this.tblReservationRoomTypeDetail;
    }

    public TblReservationRoomTypeDetail getTblReservationRoomTypeDetail() {
        return tblReservationRoomTypeDetailProperty().get();
    }

    public void setTblReservationRoomTypeDetail(TblReservationRoomTypeDetail tblReservationRoomTypeDetail) {
        tblReservationRoomTypeDetailProperty().set(tblReservationRoomTypeDetail);
    }

    public final ObjectProperty<Date> additionalDateProperty() {
        return this.additionalDate;
    }

    public Date getAdditionalDate() {
        return additionalDateProperty().get();
    }

    public void setAdditionalDate(Date additionalDate) {
        additionalDateProperty().set(additionalDate);
    }

    public final ObjectProperty<BigDecimal> itemChargeProperty() {
        return this.itemCharge;
    }

    public BigDecimal getItemCharge() {
        return itemChargeProperty().get();
    }

    public void setItemCharge(BigDecimal itemCharge) {
        itemChargeProperty().set(itemCharge);
    }

    public final ObjectProperty<BigDecimal> itemQuantityProperty() {
        return this.itemQuantity;
    }

    public BigDecimal getItemQuantity() {
        return itemQuantityProperty().get();
    }

    public void setItemQuantity(BigDecimal itemQuantity) {
        itemQuantityProperty().set(itemQuantity);
    }

    public final ObjectProperty<BigDecimal> discountPercentageProperty() {
        return this.discountPercentage;
    }

    public BigDecimal getDiscountPercentage() {
        return discountPercentageProperty().get();
    }

    public void setDiscountPercentage(BigDecimal discountPercentage) {
        discountPercentageProperty().set(discountPercentage);
    }

    public final BooleanProperty taxableProperty() {
        return this.taxable;
    }

    public Boolean getTaxable() {
        return taxableProperty().get();
    }

    public void setTaxable(Boolean taxable) {
        taxableProperty().set(taxable);
    }

    public final StringProperty noteProperty() {
        return this.note;
    }

    public String getNote() {
        return noteProperty().get();
    }

    public void setNote(String note) {
        noteProperty().set(note);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

}
