package hotelfx.persistence.model;
// Generated Oct 31, 2018 8:44:14 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblReservationRescheduleCanceled generated by hbm2java
 */
public class TblReservationRescheduleCanceled implements java.io.Serializable {

    private final LongProperty idrescheduleCanceled;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblBankEventCard> tblBankEventCard;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblHotelEvent> tblHotelEvent;
    private final ObjectProperty<TblItem> tblItem;
    private final ObjectProperty<TblReservation> tblReservation;
    private final ObjectProperty<TblReservationRoomTypeDetail> tblReservationRoomTypeDetail;
    private final ObjectProperty<TblRoomService> tblRoomService;
    private final ObjectProperty<Date> reservedForDate;
    private final ObjectProperty<Date> reservedDate;
    private final ObjectProperty<BigDecimal> price;
    private final ObjectProperty<BigDecimal> quantity;
    private final ObjectProperty<BigDecimal> discountPercentage;
    private final ObjectProperty<BigDecimal> complimentary;
    private final StringProperty note;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    public TblReservationRescheduleCanceled() {
        this.idrescheduleCanceled = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblBankEventCard = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblHotelEvent = new SimpleObjectProperty<>();
        this.tblItem = new SimpleObjectProperty<>();
        this.tblReservation = new SimpleObjectProperty<>();
        this.tblReservationRoomTypeDetail = new SimpleObjectProperty<>();
        this.tblRoomService = new SimpleObjectProperty<>();
        this.reservedForDate = new SimpleObjectProperty<>();
        this.reservedDate = new SimpleObjectProperty<>();
        this.price = new SimpleObjectProperty<>();
        this.quantity = new SimpleObjectProperty<>();
        this.discountPercentage = new SimpleObjectProperty<>();
        this.complimentary = new SimpleObjectProperty<>();
        this.note = new SimpleStringProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

    }

    public TblReservationRescheduleCanceled(long idrescheduleCanceled) {
        this();
        idrescheduleCanceledProperty().set(idrescheduleCanceled);
    }

    public TblReservationRescheduleCanceled(long idrescheduleCanceled, RefRecordStatus refRecordStatus, TblBankEventCard tblBankEventCard, TblEmployee tblEmployeeByCreateBy, TblEmployee tblEmployeeByLastUpdateBy, TblHotelEvent tblHotelEvent, TblItem tblItem, TblReservation tblReservation, TblReservationRoomTypeDetail tblReservationRoomTypeDetail, TblRoomService tblRoomService, Date reservedForDate, Date reservedDate, BigDecimal price, BigDecimal quantity, BigDecimal discountPercentage, BigDecimal complimentary, String note, Date createDate, Date lastUpdateDate) {
        this();
        idrescheduleCanceledProperty().set(idrescheduleCanceled);
        refRecordStatusProperty().set(refRecordStatus);
        tblBankEventCardProperty().set(tblBankEventCard);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblHotelEventProperty().set(tblHotelEvent);
        tblItemProperty().set(tblItem);
        tblReservationProperty().set(tblReservation);
        tblReservationRoomTypeDetailProperty().set(tblReservationRoomTypeDetail);
        tblRoomServiceProperty().set(tblRoomService);
        reservedForDateProperty().set(reservedForDate);
        reservedDateProperty().set(reservedDate);
        priceProperty().set(price);
        quantityProperty().set(quantity);
        discountPercentageProperty().set(discountPercentage);
        complimentaryProperty().set(complimentary);
        noteProperty().set(note);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

    }

    public TblReservationRescheduleCanceled(TblReservationRescheduleCanceled tblReservationRescheduleCanceled) {
        this();
        idrescheduleCanceledProperty().set(tblReservationRescheduleCanceled.getIdrescheduleCanceled());
        refRecordStatusProperty().set(tblReservationRescheduleCanceled.getRefRecordStatus());
        tblBankEventCardProperty().set(tblReservationRescheduleCanceled.getTblBankEventCard());
        tblEmployeeByCreateByProperty().set(tblReservationRescheduleCanceled.getTblEmployeeByCreateBy());
        tblEmployeeByLastUpdateByProperty().set(tblReservationRescheduleCanceled.getTblEmployeeByLastUpdateBy());
        tblHotelEventProperty().set(tblReservationRescheduleCanceled.getTblHotelEvent());
        tblItemProperty().set(tblReservationRescheduleCanceled.getTblItem());
        tblReservationProperty().set(tblReservationRescheduleCanceled.getTblReservation());
        tblReservationRoomTypeDetailProperty().set(tblReservationRescheduleCanceled.getTblReservationRoomTypeDetail());
        tblRoomServiceProperty().set(tblReservationRescheduleCanceled.getTblRoomService());
        reservedForDateProperty().set(tblReservationRescheduleCanceled.getReservedForDate());
        reservedDateProperty().set(tblReservationRescheduleCanceled.getReservedDate());
        priceProperty().set(tblReservationRescheduleCanceled.getPrice());
        quantityProperty().set(tblReservationRescheduleCanceled.getQuantity());
        discountPercentageProperty().set(tblReservationRescheduleCanceled.getDiscountPercentage());
        complimentaryProperty().set(tblReservationRescheduleCanceled.getComplimentary());
        noteProperty().set(tblReservationRescheduleCanceled.getNote());
        createDateProperty().set(tblReservationRescheduleCanceled.getCreateDate());
        lastUpdateDateProperty().set(tblReservationRescheduleCanceled.getLastUpdateDate());

    }

    public final LongProperty idrescheduleCanceledProperty() {
        return this.idrescheduleCanceled;
    }

    public long getIdrescheduleCanceled() {
        return idrescheduleCanceledProperty().get();
    }

    public void setIdrescheduleCanceled(long idrescheduleCanceled) {
        idrescheduleCanceledProperty().set(idrescheduleCanceled);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblBankEventCard> tblBankEventCardProperty() {
        return this.tblBankEventCard;
    }

    public TblBankEventCard getTblBankEventCard() {
        return tblBankEventCardProperty().get();
    }

    public void setTblBankEventCard(TblBankEventCard tblBankEventCard) {
        tblBankEventCardProperty().set(tblBankEventCard);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblHotelEvent> tblHotelEventProperty() {
        return this.tblHotelEvent;
    }

    public TblHotelEvent getTblHotelEvent() {
        return tblHotelEventProperty().get();
    }

    public void setTblHotelEvent(TblHotelEvent tblHotelEvent) {
        tblHotelEventProperty().set(tblHotelEvent);
    }

    public final ObjectProperty<TblItem> tblItemProperty() {
        return this.tblItem;
    }

    public TblItem getTblItem() {
        return tblItemProperty().get();
    }

    public void setTblItem(TblItem tblItem) {
        tblItemProperty().set(tblItem);
    }

    public final ObjectProperty<TblReservation> tblReservationProperty() {
        return this.tblReservation;
    }

    public TblReservation getTblReservation() {
        return tblReservationProperty().get();
    }

    public void setTblReservation(TblReservation tblReservation) {
        tblReservationProperty().set(tblReservation);
    }

    public final ObjectProperty<TblReservationRoomTypeDetail> tblReservationRoomTypeDetailProperty() {
        return this.tblReservationRoomTypeDetail;
    }

    public TblReservationRoomTypeDetail getTblReservationRoomTypeDetail() {
        return tblReservationRoomTypeDetailProperty().get();
    }

    public void setTblReservationRoomTypeDetail(TblReservationRoomTypeDetail tblReservationRoomTypeDetail) {
        tblReservationRoomTypeDetailProperty().set(tblReservationRoomTypeDetail);
    }

    public final ObjectProperty<TblRoomService> tblRoomServiceProperty() {
        return this.tblRoomService;
    }

    public TblRoomService getTblRoomService() {
        return tblRoomServiceProperty().get();
    }

    public void setTblRoomService(TblRoomService tblRoomService) {
        tblRoomServiceProperty().set(tblRoomService);
    }

    public final ObjectProperty<Date> reservedForDateProperty() {
        return this.reservedForDate;
    }

    public Date getReservedForDate() {
        return reservedForDateProperty().get();
    }

    public void setReservedForDate(Date reservedForDate) {
        reservedForDateProperty().set(reservedForDate);
    }

    public final ObjectProperty<Date> reservedDateProperty() {
        return this.reservedDate;
    }

    public Date getReservedDate() {
        return reservedDateProperty().get();
    }

    public void setReservedDate(Date reservedDate) {
        reservedDateProperty().set(reservedDate);
    }

    public final ObjectProperty<BigDecimal> priceProperty() {
        return this.price;
    }

    public BigDecimal getPrice() {
        return priceProperty().get();
    }

    public void setPrice(BigDecimal price) {
        priceProperty().set(price);
    }

    public final ObjectProperty<BigDecimal> quantityProperty() {
        return this.quantity;
    }

    public BigDecimal getQuantity() {
        return quantityProperty().get();
    }

    public void setQuantity(BigDecimal quantity) {
        quantityProperty().set(quantity);
    }

    public final ObjectProperty<BigDecimal> discountPercentageProperty() {
        return this.discountPercentage;
    }

    public BigDecimal getDiscountPercentage() {
        return discountPercentageProperty().get();
    }

    public void setDiscountPercentage(BigDecimal discountPercentage) {
        discountPercentageProperty().set(discountPercentage);
    }

    public final ObjectProperty<BigDecimal> complimentaryProperty() {
        return this.complimentary;
    }

    public BigDecimal getComplimentary() {
        return complimentaryProperty().get();
    }

    public void setComplimentary(BigDecimal complimentary) {
        complimentaryProperty().set(complimentary);
    }

    public final StringProperty noteProperty() {
        return this.note;
    }

    public String getNote() {
        return noteProperty().get();
    }

    public void setNote(String note) {
        noteProperty().set(note);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

}
