package hotelfx.persistence.model;
// Generated Oct 24, 2018 12:59:27 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblResto generated by hbm2java
 */
public class TblResto implements java.io.Serializable {

    private final LongProperty idresto;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final StringProperty codeResto;
    private final StringProperty restoName;
    private final StringProperty restoNote;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    private Set tblRestoBankAccounts;

    public TblResto() {
        this.idresto = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.codeResto = new SimpleStringProperty();
        this.restoName = new SimpleStringProperty();
        this.restoNote = new SimpleStringProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

        this.tblRestoBankAccounts = new HashSet(0);
    }

    public TblResto(long idresto) {
        this();
        idrestoProperty().set(idresto);
    }

    public TblResto(long idresto, RefRecordStatus refRecordStatus, TblEmployee tblEmployeeByLastUpdateBy, TblEmployee tblEmployeeByCreateBy, String codeResto, String restoName, String restoNote, Date createDate, Date lastUpdateDate, Set tblRestoBankAccounts) {
        this();
        idrestoProperty().set(idresto);
        refRecordStatusProperty().set(refRecordStatus);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        codeRestoProperty().set(codeResto);
        restoNameProperty().set(restoName);
        restoNoteProperty().set(restoNote);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

        this.tblRestoBankAccounts = tblRestoBankAccounts;
    }

    public TblResto(TblResto tblResto) {
        this();
        idrestoProperty().set(tblResto.getIdresto());
        refRecordStatusProperty().set(tblResto.getRefRecordStatus());
        tblEmployeeByLastUpdateByProperty().set(tblResto.getTblEmployeeByLastUpdateBy());
        tblEmployeeByCreateByProperty().set(tblResto.getTblEmployeeByCreateBy());
        codeRestoProperty().set(tblResto.getCodeResto());
        restoNameProperty().set(tblResto.getRestoName());
        restoNoteProperty().set(tblResto.getRestoNote());
        createDateProperty().set(tblResto.getCreateDate());
        lastUpdateDateProperty().set(tblResto.getLastUpdateDate());

        this.tblRestoBankAccounts = tblResto.getTblRestoBankAccounts();
    }

    public final LongProperty idrestoProperty() {
        return this.idresto;
    }

    public long getIdresto() {
        return idrestoProperty().get();
    }

    public void setIdresto(long idresto) {
        idrestoProperty().set(idresto);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final StringProperty codeRestoProperty() {
        return this.codeResto;
    }

    public String getCodeResto() {
        return codeRestoProperty().get();
    }

    public void setCodeResto(String codeResto) {
        codeRestoProperty().set(codeResto);
    }

    public final StringProperty restoNameProperty() {
        return this.restoName;
    }

    public String getRestoName() {
        return restoNameProperty().get();
    }

    public void setRestoName(String restoName) {
        restoNameProperty().set(restoName);
    }

    public final StringProperty restoNoteProperty() {
        return this.restoNote;
    }

    public String getRestoNote() {
        return restoNoteProperty().get();
    }

    public void setRestoNote(String restoNote) {
        restoNoteProperty().set(restoNote);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

    public Set getTblRestoBankAccounts() {
        return this.tblRestoBankAccounts;
    }

    public void setTblRestoBankAccounts(Set tblRestoBankAccounts) {
        this.tblRestoBankAccounts = tblRestoBankAccounts;
    }

    @Override
    public String toString(){
        return getRestoName();
    }
    
}
