package hotelfx.persistence.model;
// Generated Aug 21, 2017 1:49:32 PM by Hibernate Tools 4.3.1

import java.util.Date;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;

/**
 * TblReservationCalendarBar generated by hbm2java
 */
public class TblReservationCalendarBar implements java.io.Serializable {

    private final LongProperty idcalendarBar;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblReservationBar> tblReservationBar;
    private final ObjectProperty<TblReservationSeason> tblReservationSeason;
    private final ObjectProperty<Date> calendarDate;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    public TblReservationCalendarBar() {
        this.idcalendarBar = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblReservationBar = new SimpleObjectProperty<>();
        this.tblReservationSeason = new SimpleObjectProperty<>();
        this.calendarDate = new SimpleObjectProperty<>();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

    }

    public TblReservationCalendarBar(long idcalendarBar) {
        this();
        idcalendarBarProperty().set(idcalendarBar);
    }

    public TblReservationCalendarBar(long idcalendarBar, RefRecordStatus refRecordStatus, TblEmployee tblEmployeeByCreateBy, TblEmployee tblEmployeeByLastUpdateBy, TblReservationBar tblReservationBar, TblReservationSeason tblReservationSeason, Date calendarDate, Date createDate, Date lastUpdateDate) {
        this();
        idcalendarBarProperty().set(idcalendarBar);
        refRecordStatusProperty().set(refRecordStatus);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblReservationBarProperty().set(tblReservationBar);
        tblReservationSeasonProperty().set(tblReservationSeason);
        calendarDateProperty().set(calendarDate);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

    }

    public TblReservationCalendarBar(TblReservationCalendarBar tblReservationCalendarBar) {
        this();
        idcalendarBarProperty().set(tblReservationCalendarBar.getIdcalendarBar());
        refRecordStatusProperty().set(tblReservationCalendarBar.getRefRecordStatus());
        tblEmployeeByCreateByProperty().set(tblReservationCalendarBar.getTblEmployeeByCreateBy());
        tblEmployeeByLastUpdateByProperty().set(tblReservationCalendarBar.getTblEmployeeByLastUpdateBy());
        tblReservationBarProperty().set(tblReservationCalendarBar.getTblReservationBar());
        tblReservationSeasonProperty().set(tblReservationCalendarBar.getTblReservationSeason());
        calendarDateProperty().set(tblReservationCalendarBar.getCalendarDate());
        createDateProperty().set(tblReservationCalendarBar.getCreateDate());
        lastUpdateDateProperty().set(tblReservationCalendarBar.getLastUpdateDate());

    }

    public final LongProperty idcalendarBarProperty() {
        return this.idcalendarBar;
    }

    public long getIdcalendarBar() {
        return idcalendarBarProperty().get();
    }

    public void setIdcalendarBar(long idcalendarBar) {
        idcalendarBarProperty().set(idcalendarBar);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblReservationBar> tblReservationBarProperty() {
        return this.tblReservationBar;
    }

    public TblReservationBar getTblReservationBar() {
        return tblReservationBarProperty().get();
    }

    public void setTblReservationBar(TblReservationBar tblReservationBar) {
        tblReservationBarProperty().set(tblReservationBar);
    }

    public final ObjectProperty<TblReservationSeason> tblReservationSeasonProperty() {
        return this.tblReservationSeason;
    }

    public TblReservationSeason getTblReservationSeason() {
        return tblReservationSeasonProperty().get();
    }

    public void setTblReservationSeason(TblReservationSeason tblReservationSeason) {
        tblReservationSeasonProperty().set(tblReservationSeason);
    }

    public final ObjectProperty<Date> calendarDateProperty() {
        return this.calendarDate;
    }

    public Date getCalendarDate() {
        return calendarDateProperty().get();
    }

    public void setCalendarDate(Date calendarDate) {
        calendarDateProperty().set(calendarDate);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

}
