package hotelfx.persistence.model;
// Generated Oct 30, 2018 10:45:55 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblReservation generated by hbm2java
 */
public class TblReservation implements java.io.Serializable {

    private final LongProperty idreservation;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<RefReservationStatus> refReservationStatus;
    private final ObjectProperty<TblCustomer> tblCustomer;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblPartner> tblPartner;
    private final StringProperty codeReservation;
    private final ObjectProperty<Date> reservationDate;
    private final ObjectProperty<Date> planningArrivalTime;
    private final ObjectProperty<Date> arrivalTime;
    private final ObjectProperty<Date> departureTime;
    private final ObjectProperty<Date> maxPaymentDate;
    private final ObjectProperty<Date> maxCancelDate;
    private final StringProperty note;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    private Set tblReservationRoomTypeDetails;
    private Set tblReservationCancelingFees;
    private Set tblReservationRescheduleCanceleds;
    private Set tblReservationBills;
    private Set tblReservationCanceleds;

    public TblReservation() {
        this.idreservation = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.refReservationStatus = new SimpleObjectProperty<>();
        this.tblCustomer = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblPartner = new SimpleObjectProperty<>();
        this.codeReservation = new SimpleStringProperty();
        this.reservationDate = new SimpleObjectProperty<>();
        this.planningArrivalTime = new SimpleObjectProperty<>();
        this.arrivalTime = new SimpleObjectProperty<>();
        this.departureTime = new SimpleObjectProperty<>();
        this.maxPaymentDate = new SimpleObjectProperty<>();
        this.maxCancelDate = new SimpleObjectProperty<>();
        this.note = new SimpleStringProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

        this.tblReservationRoomTypeDetails = new HashSet(0);
        this.tblReservationCancelingFees = new HashSet(0);
        this.tblReservationRescheduleCanceleds = new HashSet(0);
        this.tblReservationBills = new HashSet(0);
        this.tblReservationCanceleds = new HashSet(0);
    }

    public TblReservation(long idreservation) {
        this();
        idreservationProperty().set(idreservation);
    }

    public TblReservation(long idreservation, RefRecordStatus refRecordStatus, RefReservationStatus refReservationStatus, TblCustomer tblCustomer, TblEmployee tblEmployeeByLastUpdateBy, TblEmployee tblEmployeeByCreateBy, TblPartner tblPartner, String codeReservation, Date reservationDate, Date planningArrivalTime, Date arrivalTime, Date departureTime, Date maxPaymentDate, Date maxCancelDate, String note, Date createDate, Date lastUpdateDate, Set tblReservationRoomTypeDetails, Set tblReservationCancelingFees, Set tblReservationRescheduleCanceleds, Set tblReservationBills, Set tblReservationCanceleds) {
        this();
        idreservationProperty().set(idreservation);
        refRecordStatusProperty().set(refRecordStatus);
        refReservationStatusProperty().set(refReservationStatus);
        tblCustomerProperty().set(tblCustomer);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblPartnerProperty().set(tblPartner);
        codeReservationProperty().set(codeReservation);
        reservationDateProperty().set(reservationDate);
        planningArrivalTimeProperty().set(planningArrivalTime);
        arrivalTimeProperty().set(arrivalTime);
        departureTimeProperty().set(departureTime);
        maxPaymentDateProperty().set(maxPaymentDate);
        maxCancelDateProperty().set(maxCancelDate);
        noteProperty().set(note);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

        this.tblReservationRoomTypeDetails = tblReservationRoomTypeDetails;
        this.tblReservationCancelingFees = tblReservationCancelingFees;
        this.tblReservationRescheduleCanceleds = tblReservationRescheduleCanceleds;
        this.tblReservationBills = tblReservationBills;
        this.tblReservationCanceleds = tblReservationCanceleds;
    }

    public TblReservation(TblReservation tblReservation) {
        this();
        idreservationProperty().set(tblReservation.getIdreservation());
        refRecordStatusProperty().set(tblReservation.getRefRecordStatus());
        refReservationStatusProperty().set(tblReservation.getRefReservationStatus());
        tblCustomerProperty().set(tblReservation.getTblCustomer());
        tblEmployeeByLastUpdateByProperty().set(tblReservation.getTblEmployeeByLastUpdateBy());
        tblEmployeeByCreateByProperty().set(tblReservation.getTblEmployeeByCreateBy());
        tblPartnerProperty().set(tblReservation.getTblPartner());
        codeReservationProperty().set(tblReservation.getCodeReservation());
        reservationDateProperty().set(tblReservation.getReservationDate());
        planningArrivalTimeProperty().set(tblReservation.getPlanningArrivalTime());
        arrivalTimeProperty().set(tblReservation.getArrivalTime());
        departureTimeProperty().set(tblReservation.getDepartureTime());
        maxPaymentDateProperty().set(tblReservation.getMaxPaymentDate());
        maxCancelDateProperty().set(tblReservation.getMaxCancelDate());
        noteProperty().set(tblReservation.getNote());
        createDateProperty().set(tblReservation.getCreateDate());
        lastUpdateDateProperty().set(tblReservation.getLastUpdateDate());

        this.tblReservationRoomTypeDetails = tblReservation.getTblReservationRoomTypeDetails();
        this.tblReservationCancelingFees = tblReservation.getTblReservationCancelingFees();
        this.tblReservationRescheduleCanceleds = tblReservation.getTblReservationRescheduleCanceleds();
        this.tblReservationBills = tblReservation.getTblReservationBills();
        this.tblReservationCanceleds = tblReservation.getTblReservationCanceleds();
    }

    public final LongProperty idreservationProperty() {
        return this.idreservation;
    }

    public long getIdreservation() {
        return idreservationProperty().get();
    }

    public void setIdreservation(long idreservation) {
        idreservationProperty().set(idreservation);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<RefReservationStatus> refReservationStatusProperty() {
        return this.refReservationStatus;
    }

    public RefReservationStatus getRefReservationStatus() {
        return refReservationStatusProperty().get();
    }

    public void setRefReservationStatus(RefReservationStatus refReservationStatus) {
        refReservationStatusProperty().set(refReservationStatus);
    }

    public final ObjectProperty<TblCustomer> tblCustomerProperty() {
        return this.tblCustomer;
    }

    public TblCustomer getTblCustomer() {
        return tblCustomerProperty().get();
    }

    public void setTblCustomer(TblCustomer tblCustomer) {
        tblCustomerProperty().set(tblCustomer);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblPartner> tblPartnerProperty() {
        return this.tblPartner;
    }

    public TblPartner getTblPartner() {
        return tblPartnerProperty().get();
    }

    public void setTblPartner(TblPartner tblPartner) {
        tblPartnerProperty().set(tblPartner);
    }

    public final StringProperty codeReservationProperty() {
        return this.codeReservation;
    }

    public String getCodeReservation() {
        return codeReservationProperty().get();
    }

    public void setCodeReservation(String codeReservation) {
        codeReservationProperty().set(codeReservation);
    }

    public final ObjectProperty<Date> reservationDateProperty() {
        return this.reservationDate;
    }

    public Date getReservationDate() {
        return reservationDateProperty().get();
    }

    public void setReservationDate(Date reservationDate) {
        reservationDateProperty().set(reservationDate);
    }

    public final ObjectProperty<Date> planningArrivalTimeProperty() {
        return this.planningArrivalTime;
    }

    public Date getPlanningArrivalTime() {
        return planningArrivalTimeProperty().get();
    }

    public void setPlanningArrivalTime(Date planningArrivalTime) {
        planningArrivalTimeProperty().set(planningArrivalTime);
    }

    public final ObjectProperty<Date> arrivalTimeProperty() {
        return this.arrivalTime;
    }

    public Date getArrivalTime() {
        return arrivalTimeProperty().get();
    }

    public void setArrivalTime(Date arrivalTime) {
        arrivalTimeProperty().set(arrivalTime);
    }

    public final ObjectProperty<Date> departureTimeProperty() {
        return this.departureTime;
    }

    public Date getDepartureTime() {
        return departureTimeProperty().get();
    }

    public void setDepartureTime(Date departureTime) {
        departureTimeProperty().set(departureTime);
    }

    public final ObjectProperty<Date> maxPaymentDateProperty() {
        return this.maxPaymentDate;
    }

    public Date getMaxPaymentDate() {
        return maxPaymentDateProperty().get();
    }

    public void setMaxPaymentDate(Date maxPaymentDate) {
        maxPaymentDateProperty().set(maxPaymentDate);
    }

    public final ObjectProperty<Date> maxCancelDateProperty() {
        return this.maxCancelDate;
    }

    public Date getMaxCancelDate() {
        return maxCancelDateProperty().get();
    }

    public void setMaxCancelDate(Date maxCancelDate) {
        maxCancelDateProperty().set(maxCancelDate);
    }

    public final StringProperty noteProperty() {
        return this.note;
    }

    public String getNote() {
        return noteProperty().get();
    }

    public void setNote(String note) {
        noteProperty().set(note);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

    public Set getTblReservationRoomTypeDetails() {
        return this.tblReservationRoomTypeDetails;
    }

    public void setTblReservationRoomTypeDetails(Set tblReservationRoomTypeDetails) {
        this.tblReservationRoomTypeDetails = tblReservationRoomTypeDetails;
    }

    public Set getTblReservationCancelingFees() {
        return this.tblReservationCancelingFees;
    }

    public void setTblReservationCancelingFees(Set tblReservationCancelingFees) {
        this.tblReservationCancelingFees = tblReservationCancelingFees;
    }

    public Set getTblReservationRescheduleCanceleds() {
        return this.tblReservationRescheduleCanceleds;
    }

    public void setTblReservationRescheduleCanceleds(Set tblReservationRescheduleCanceleds) {
        this.tblReservationRescheduleCanceleds = tblReservationRescheduleCanceleds;
    }

    public Set getTblReservationBills() {
        return this.tblReservationBills;
    }

    public void setTblReservationBills(Set tblReservationBills) {
        this.tblReservationBills = tblReservationBills;
    }

    public Set getTblReservationCanceleds() {
        return this.tblReservationCanceleds;
    }

    public void setTblReservationCanceleds(Set tblReservationCanceleds) {
        this.tblReservationCanceleds = tblReservationCanceleds;
    }

    @Override
    public String toString(){
        return getCodeReservation();
    }
    
}
