package hotelfx.persistence.model;
// Generated Oct 16, 2018 9:09:21 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javafx.beans.property.BooleanProperty;
import javafx.beans.property.IntegerProperty;
import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleBooleanProperty;
import javafx.beans.property.SimpleIntegerProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblRoomType generated by hbm2java
 */
public class TblRoomType implements java.io.Serializable {

    private final LongProperty idroomType;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final StringProperty codeRoomType;
    private final StringProperty roomTypeName;
    private final IntegerProperty adultNumber;
    private final IntegerProperty childNumber;
    private final ObjectProperty<BigDecimal> roomTypePrice;
    private final StringProperty roomTypeNote;
    private final BooleanProperty hotelDiscountable;
    private final BooleanProperty cardDiscountable;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    private Set tblTravelAgentRoomTypes;
    private Set tblRoomTypeRoomServices;
    private Set tblReservationRoomTypeDetails;
    private Set logRoomTypePriceChangedHistories;
    private Set tblRoomTypeItems;
    private Set tblRooms;
    private Set logRoomTypeHistories;

    public TblRoomType() {
        this.idroomType = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.codeRoomType = new SimpleStringProperty();
        this.roomTypeName = new SimpleStringProperty();
        this.adultNumber = new SimpleIntegerProperty();
        this.childNumber = new SimpleIntegerProperty();
        this.roomTypePrice = new SimpleObjectProperty<>();
        this.roomTypeNote = new SimpleStringProperty();
        this.hotelDiscountable = new SimpleBooleanProperty();
        this.cardDiscountable = new SimpleBooleanProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

        this.tblTravelAgentRoomTypes = new HashSet(0);
        this.tblRoomTypeRoomServices = new HashSet(0);
        this.tblReservationRoomTypeDetails = new HashSet(0);
        this.logRoomTypePriceChangedHistories = new HashSet(0);
        this.tblRoomTypeItems = new HashSet(0);
        this.tblRooms = new HashSet(0);
        this.logRoomTypeHistories = new HashSet(0);
    }

    public TblRoomType(long idroomType) {
        this();
        idroomTypeProperty().set(idroomType);
    }

    public TblRoomType(long idroomType, RefRecordStatus refRecordStatus, TblEmployee tblEmployeeByCreateBy, TblEmployee tblEmployeeByLastUpdateBy, String codeRoomType, String roomTypeName, Integer adultNumber, Integer childNumber, BigDecimal roomTypePrice, String roomTypeNote, Boolean hotelDiscountable, Boolean cardDiscountable, Date createDate, Date lastUpdateDate, Set tblTravelAgentRoomTypes, Set tblRoomTypeRoomServices, Set tblReservationRoomTypeDetails, Set logRoomTypePriceChangedHistories, Set tblRoomTypeItems, Set tblRooms, Set logRoomTypeHistories) {
        this();
        idroomTypeProperty().set(idroomType);
        refRecordStatusProperty().set(refRecordStatus);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        codeRoomTypeProperty().set(codeRoomType);
        roomTypeNameProperty().set(roomTypeName);
        adultNumberProperty().set(adultNumber);
        childNumberProperty().set(childNumber);
        roomTypePriceProperty().set(roomTypePrice);
        roomTypeNoteProperty().set(roomTypeNote);
        hotelDiscountableProperty().set(hotelDiscountable);
        cardDiscountableProperty().set(cardDiscountable);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

        this.tblTravelAgentRoomTypes = tblTravelAgentRoomTypes;
        this.tblRoomTypeRoomServices = tblRoomTypeRoomServices;
        this.tblReservationRoomTypeDetails = tblReservationRoomTypeDetails;
        this.logRoomTypePriceChangedHistories = logRoomTypePriceChangedHistories;
        this.tblRoomTypeItems = tblRoomTypeItems;
        this.tblRooms = tblRooms;
        this.logRoomTypeHistories = logRoomTypeHistories;
    }

    public TblRoomType(TblRoomType tblRoomType) {
        this();
        idroomTypeProperty().set(tblRoomType.getIdroomType());
        refRecordStatusProperty().set(tblRoomType.getRefRecordStatus());
        tblEmployeeByCreateByProperty().set(tblRoomType.getTblEmployeeByCreateBy());
        tblEmployeeByLastUpdateByProperty().set(tblRoomType.getTblEmployeeByLastUpdateBy());
        codeRoomTypeProperty().set(tblRoomType.getCodeRoomType());
        roomTypeNameProperty().set(tblRoomType.getRoomTypeName());
        adultNumberProperty().set(tblRoomType.getAdultNumber());
        childNumberProperty().set(tblRoomType.getChildNumber());
        roomTypePriceProperty().set(tblRoomType.getRoomTypePrice());
        roomTypeNoteProperty().set(tblRoomType.getRoomTypeNote());
        hotelDiscountableProperty().set(tblRoomType.getHotelDiscountable());
        cardDiscountableProperty().set(tblRoomType.getCardDiscountable());
        createDateProperty().set(tblRoomType.getCreateDate());
        lastUpdateDateProperty().set(tblRoomType.getLastUpdateDate());

        this.tblTravelAgentRoomTypes = tblRoomType.getTblTravelAgentRoomTypes();
        this.tblRoomTypeRoomServices = tblRoomType.getTblRoomTypeRoomServices();
        this.tblReservationRoomTypeDetails = tblRoomType.getTblReservationRoomTypeDetails();
        this.logRoomTypePriceChangedHistories = tblRoomType.getLogRoomTypePriceChangedHistories();
        this.tblRoomTypeItems = tblRoomType.getTblRoomTypeItems();
        this.tblRooms = tblRoomType.getTblRooms();
        this.logRoomTypeHistories = tblRoomType.getLogRoomTypeHistories();
    }

    public final LongProperty idroomTypeProperty() {
        return this.idroomType;
    }

    public long getIdroomType() {
        return idroomTypeProperty().get();
    }

    public void setIdroomType(long idroomType) {
        idroomTypeProperty().set(idroomType);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final StringProperty codeRoomTypeProperty() {
        return this.codeRoomType;
    }

    public String getCodeRoomType() {
        return codeRoomTypeProperty().get();
    }

    public void setCodeRoomType(String codeRoomType) {
        codeRoomTypeProperty().set(codeRoomType);
    }

    public final StringProperty roomTypeNameProperty() {
        return this.roomTypeName;
    }

    public String getRoomTypeName() {
        return roomTypeNameProperty().get();
    }

    public void setRoomTypeName(String roomTypeName) {
        roomTypeNameProperty().set(roomTypeName);
    }

    public final IntegerProperty adultNumberProperty() {
        return this.adultNumber;
    }

    public Integer getAdultNumber() {
        return adultNumberProperty().get();
    }

    public void setAdultNumber(Integer adultNumber) {
        adultNumberProperty().set(adultNumber);
    }

    public final IntegerProperty childNumberProperty() {
        return this.childNumber;
    }

    public Integer getChildNumber() {
        return childNumberProperty().get();
    }

    public void setChildNumber(Integer childNumber) {
        childNumberProperty().set(childNumber);
    }

    public final ObjectProperty<BigDecimal> roomTypePriceProperty() {
        return this.roomTypePrice;
    }

    public BigDecimal getRoomTypePrice() {
        return roomTypePriceProperty().get();
    }

    public void setRoomTypePrice(BigDecimal roomTypePrice) {
        roomTypePriceProperty().set(roomTypePrice);
    }

    public final StringProperty roomTypeNoteProperty() {
        return this.roomTypeNote;
    }

    public String getRoomTypeNote() {
        return roomTypeNoteProperty().get();
    }

    public void setRoomTypeNote(String roomTypeNote) {
        roomTypeNoteProperty().set(roomTypeNote);
    }

    public final BooleanProperty hotelDiscountableProperty() {
        return this.hotelDiscountable;
    }

    public Boolean getHotelDiscountable() {
        return hotelDiscountableProperty().get();
    }

    public void setHotelDiscountable(Boolean hotelDiscountable) {
        hotelDiscountableProperty().set(hotelDiscountable);
    }

    public final BooleanProperty cardDiscountableProperty() {
        return this.cardDiscountable;
    }

    public Boolean getCardDiscountable() {
        return cardDiscountableProperty().get();
    }

    public void setCardDiscountable(Boolean cardDiscountable) {
        cardDiscountableProperty().set(cardDiscountable);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

    public Set getTblTravelAgentRoomTypes() {
        return this.tblTravelAgentRoomTypes;
    }

    public void setTblTravelAgentRoomTypes(Set tblTravelAgentRoomTypes) {
        this.tblTravelAgentRoomTypes = tblTravelAgentRoomTypes;
    }

    public Set getTblRoomTypeRoomServices() {
        return this.tblRoomTypeRoomServices;
    }

    public void setTblRoomTypeRoomServices(Set tblRoomTypeRoomServices) {
        this.tblRoomTypeRoomServices = tblRoomTypeRoomServices;
    }

    public Set getTblReservationRoomTypeDetails() {
        return this.tblReservationRoomTypeDetails;
    }

    public void setTblReservationRoomTypeDetails(Set tblReservationRoomTypeDetails) {
        this.tblReservationRoomTypeDetails = tblReservationRoomTypeDetails;
    }

    public Set getLogRoomTypePriceChangedHistories() {
        return this.logRoomTypePriceChangedHistories;
    }

    public void setLogRoomTypePriceChangedHistories(Set logRoomTypePriceChangedHistories) {
        this.logRoomTypePriceChangedHistories = logRoomTypePriceChangedHistories;
    }

    public Set getTblRoomTypeItems() {
        return this.tblRoomTypeItems;
    }

    public void setTblRoomTypeItems(Set tblRoomTypeItems) {
        this.tblRoomTypeItems = tblRoomTypeItems;
    }

    public Set getTblRooms() {
        return this.tblRooms;
    }

    public void setTblRooms(Set tblRooms) {
        this.tblRooms = tblRooms;
    }

    public Set getLogRoomTypeHistories() {
        return this.logRoomTypeHistories;
    }

    public void setLogRoomTypeHistories(Set logRoomTypeHistories) {
        this.logRoomTypeHistories = logRoomTypeHistories;
    }

    @Override
    public String toString() {
        return getRoomTypeName();
    }
    
}
