package hotelfx.persistence.model;
// Generated May 15, 2018 9:33:28 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblReservationPayment generated by hbm2java
 */
public class TblReservationPayment implements java.io.Serializable {

    private final LongProperty idpayment;
    private final ObjectProperty<RefFinanceTransactionPaymentType> refFinanceTransactionPaymentType;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<RefReservationBillType> refReservationBillType;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByIdcashier;
    private final ObjectProperty<TblFinanceData> tblFinanceData;
    private final ObjectProperty<TblReservationBill> tblReservationBill;
    private final StringProperty codePayment;
    private final ObjectProperty<Date> paymentDate;
    private final ObjectProperty<BigDecimal> unitNominal;
    private final ObjectProperty<BigDecimal> roundingValue;
    private final StringProperty paymentNote;
    private final ObjectProperty<Date> settleDate;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    private Set tblOpenCloseCashierBalanceDetails;
    private Set tblReservationPaymentWithBankCards;
    private Set tblReservationPaymentWithDeposits;
    private Set tblReservationPaymentWithReservationVouchers;
    private Set tblReservationPaymentWithTransfers;
    private Set tblReservationPaymentWithGuaranteePayments;
    private Set tblReservationPaymentWithCekGiros;

    public TblReservationPayment() {
        this.idpayment = new SimpleLongProperty();
        this.refFinanceTransactionPaymentType = new SimpleObjectProperty<>();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.refReservationBillType = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByIdcashier = new SimpleObjectProperty<>();
        this.tblFinanceData = new SimpleObjectProperty<>();
        this.tblReservationBill = new SimpleObjectProperty<>();
        this.codePayment = new SimpleStringProperty();
        this.paymentDate = new SimpleObjectProperty<>();
        this.unitNominal = new SimpleObjectProperty<>();
        this.roundingValue = new SimpleObjectProperty<>();
        this.paymentNote = new SimpleStringProperty();
        this.settleDate = new SimpleObjectProperty<>();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

        this.tblOpenCloseCashierBalanceDetails = new HashSet(0);
        this.tblReservationPaymentWithBankCards = new HashSet(0);
        this.tblReservationPaymentWithDeposits = new HashSet(0);
        this.tblReservationPaymentWithReservationVouchers = new HashSet(0);
        this.tblReservationPaymentWithTransfers = new HashSet(0);
        this.tblReservationPaymentWithGuaranteePayments = new HashSet(0);
        this.tblReservationPaymentWithCekGiros = new HashSet(0);
    }

    public TblReservationPayment(long idpayment) {
        this();
        idpaymentProperty().set(idpayment);
    }

    public TblReservationPayment(long idpayment, RefFinanceTransactionPaymentType refFinanceTransactionPaymentType, RefRecordStatus refRecordStatus, RefReservationBillType refReservationBillType, TblEmployee tblEmployeeByLastUpdateBy, TblEmployee tblEmployeeByCreateBy, TblEmployee tblEmployeeByIdcashier, TblFinanceData tblFinanceData, TblReservationBill tblReservationBill, String codePayment, Date paymentDate, BigDecimal unitNominal, BigDecimal roundingValue, String paymentNote, Date settleDate, Date createDate, Date lastUpdateDate, Set tblOpenCloseCashierBalanceDetails, Set tblReservationPaymentWithBankCards, Set tblReservationPaymentWithDeposits, Set tblReservationPaymentWithReservationVouchers, Set tblReservationPaymentWithTransfers, Set tblReservationPaymentWithGuaranteePayments, Set tblReservationPaymentWithCekGiros) {
        this();
        idpaymentProperty().set(idpayment);
        refFinanceTransactionPaymentTypeProperty().set(refFinanceTransactionPaymentType);
        refRecordStatusProperty().set(refRecordStatus);
        refReservationBillTypeProperty().set(refReservationBillType);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblEmployeeByIdcashierProperty().set(tblEmployeeByIdcashier);
        tblFinanceDataProperty().set(tblFinanceData);
        tblReservationBillProperty().set(tblReservationBill);
        codePaymentProperty().set(codePayment);
        paymentDateProperty().set(paymentDate);
        unitNominalProperty().set(unitNominal);
        roundingValueProperty().set(roundingValue);
        paymentNoteProperty().set(paymentNote);
        settleDateProperty().set(settleDate);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

        this.tblOpenCloseCashierBalanceDetails = tblOpenCloseCashierBalanceDetails;
        this.tblReservationPaymentWithBankCards = tblReservationPaymentWithBankCards;
        this.tblReservationPaymentWithDeposits = tblReservationPaymentWithDeposits;
        this.tblReservationPaymentWithReservationVouchers = tblReservationPaymentWithReservationVouchers;
        this.tblReservationPaymentWithTransfers = tblReservationPaymentWithTransfers;
        this.tblReservationPaymentWithGuaranteePayments = tblReservationPaymentWithGuaranteePayments;
        this.tblReservationPaymentWithCekGiros = tblReservationPaymentWithCekGiros;
    }

    public TblReservationPayment(TblReservationPayment tblReservationPayment) {
        this();
        idpaymentProperty().set(tblReservationPayment.getIdpayment());
        refFinanceTransactionPaymentTypeProperty().set(tblReservationPayment.getRefFinanceTransactionPaymentType());
        refRecordStatusProperty().set(tblReservationPayment.getRefRecordStatus());
        refReservationBillTypeProperty().set(tblReservationPayment.getRefReservationBillType());
        tblEmployeeByLastUpdateByProperty().set(tblReservationPayment.getTblEmployeeByLastUpdateBy());
        tblEmployeeByCreateByProperty().set(tblReservationPayment.getTblEmployeeByCreateBy());
        tblEmployeeByIdcashierProperty().set(tblReservationPayment.getTblEmployeeByIdcashier());
        tblFinanceDataProperty().set(tblReservationPayment.getTblFinanceData());
        tblReservationBillProperty().set(tblReservationPayment.getTblReservationBill());
        codePaymentProperty().set(tblReservationPayment.getCodePayment());
        paymentDateProperty().set(tblReservationPayment.getPaymentDate());
        unitNominalProperty().set(tblReservationPayment.getUnitNominal());
        roundingValueProperty().set(tblReservationPayment.getRoundingValue());
        paymentNoteProperty().set(tblReservationPayment.getPaymentNote());
        settleDateProperty().set(tblReservationPayment.getSettleDate());
        createDateProperty().set(tblReservationPayment.getCreateDate());
        lastUpdateDateProperty().set(tblReservationPayment.getLastUpdateDate());

        this.tblOpenCloseCashierBalanceDetails = tblReservationPayment.getTblOpenCloseCashierBalanceDetails();
        this.tblReservationPaymentWithBankCards = tblReservationPayment.getTblReservationPaymentWithBankCards();
        this.tblReservationPaymentWithDeposits = tblReservationPayment.getTblReservationPaymentWithDeposits();
        this.tblReservationPaymentWithReservationVouchers = tblReservationPayment.getTblReservationPaymentWithReservationVouchers();
        this.tblReservationPaymentWithTransfers = tblReservationPayment.getTblReservationPaymentWithTransfers();
        this.tblReservationPaymentWithGuaranteePayments = tblReservationPayment.getTblReservationPaymentWithGuaranteePayments();
        this.tblReservationPaymentWithCekGiros = tblReservationPayment.getTblReservationPaymentWithCekGiros();
    }

    public final LongProperty idpaymentProperty() {
        return this.idpayment;
    }

    public long getIdpayment() {
        return idpaymentProperty().get();
    }

    public void setIdpayment(long idpayment) {
        idpaymentProperty().set(idpayment);
    }

    public final ObjectProperty<RefFinanceTransactionPaymentType> refFinanceTransactionPaymentTypeProperty() {
        return this.refFinanceTransactionPaymentType;
    }

    public RefFinanceTransactionPaymentType getRefFinanceTransactionPaymentType() {
        return refFinanceTransactionPaymentTypeProperty().get();
    }

    public void setRefFinanceTransactionPaymentType(RefFinanceTransactionPaymentType refFinanceTransactionPaymentType) {
        refFinanceTransactionPaymentTypeProperty().set(refFinanceTransactionPaymentType);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<RefReservationBillType> refReservationBillTypeProperty() {
        return this.refReservationBillType;
    }

    public RefReservationBillType getRefReservationBillType() {
        return refReservationBillTypeProperty().get();
    }

    public void setRefReservationBillType(RefReservationBillType refReservationBillType) {
        refReservationBillTypeProperty().set(refReservationBillType);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByIdcashierProperty() {
        return this.tblEmployeeByIdcashier;
    }

    public TblEmployee getTblEmployeeByIdcashier() {
        return tblEmployeeByIdcashierProperty().get();
    }

    public void setTblEmployeeByIdcashier(TblEmployee tblEmployeeByIdcashier) {
        tblEmployeeByIdcashierProperty().set(tblEmployeeByIdcashier);
    }

    public final ObjectProperty<TblFinanceData> tblFinanceDataProperty() {
        return this.tblFinanceData;
    }

    public TblFinanceData getTblFinanceData() {
        return tblFinanceDataProperty().get();
    }

    public void setTblFinanceData(TblFinanceData tblFinanceData) {
        tblFinanceDataProperty().set(tblFinanceData);
    }

    public final ObjectProperty<TblReservationBill> tblReservationBillProperty() {
        return this.tblReservationBill;
    }

    public TblReservationBill getTblReservationBill() {
        return tblReservationBillProperty().get();
    }

    public void setTblReservationBill(TblReservationBill tblReservationBill) {
        tblReservationBillProperty().set(tblReservationBill);
    }

    public final StringProperty codePaymentProperty() {
        return this.codePayment;
    }

    public String getCodePayment() {
        return codePaymentProperty().get();
    }

    public void setCodePayment(String codePayment) {
        codePaymentProperty().set(codePayment);
    }

    public final ObjectProperty<Date> paymentDateProperty() {
        return this.paymentDate;
    }

    public Date getPaymentDate() {
        return paymentDateProperty().get();
    }

    public void setPaymentDate(Date paymentDate) {
        paymentDateProperty().set(paymentDate);
    }

    public final ObjectProperty<BigDecimal> unitNominalProperty() {
        return this.unitNominal;
    }

    public BigDecimal getUnitNominal() {
        return unitNominalProperty().get();
    }

    public void setUnitNominal(BigDecimal unitNominal) {
        unitNominalProperty().set(unitNominal);
    }

    public final ObjectProperty<BigDecimal> roundingValueProperty() {
        return this.roundingValue;
    }

    public BigDecimal getRoundingValue() {
        return roundingValueProperty().get();
    }

    public void setRoundingValue(BigDecimal roundingValue) {
        roundingValueProperty().set(roundingValue);
    }

    public final StringProperty paymentNoteProperty() {
        return this.paymentNote;
    }

    public String getPaymentNote() {
        return paymentNoteProperty().get();
    }

    public void setPaymentNote(String paymentNote) {
        paymentNoteProperty().set(paymentNote);
    }

    public final ObjectProperty<Date> settleDateProperty() {
        return this.settleDate;
    }

    public Date getSettleDate() {
        return settleDateProperty().get();
    }

    public void setSettleDate(Date settleDate) {
        settleDateProperty().set(settleDate);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

    public Set getTblOpenCloseCashierBalanceDetails() {
        return this.tblOpenCloseCashierBalanceDetails;
    }

    public void setTblOpenCloseCashierBalanceDetails(Set tblOpenCloseCashierBalanceDetails) {
        this.tblOpenCloseCashierBalanceDetails = tblOpenCloseCashierBalanceDetails;
    }

    public Set getTblReservationPaymentWithBankCards() {
        return this.tblReservationPaymentWithBankCards;
    }

    public void setTblReservationPaymentWithBankCards(Set tblReservationPaymentWithBankCards) {
        this.tblReservationPaymentWithBankCards = tblReservationPaymentWithBankCards;
    }

    public Set getTblReservationPaymentWithDeposits() {
        return this.tblReservationPaymentWithDeposits;
    }

    public void setTblReservationPaymentWithDeposits(Set tblReservationPaymentWithDeposits) {
        this.tblReservationPaymentWithDeposits = tblReservationPaymentWithDeposits;
    }

    public Set getTblReservationPaymentWithReservationVouchers() {
        return this.tblReservationPaymentWithReservationVouchers;
    }

    public void setTblReservationPaymentWithReservationVouchers(Set tblReservationPaymentWithReservationVouchers) {
        this.tblReservationPaymentWithReservationVouchers = tblReservationPaymentWithReservationVouchers;
    }

    public Set getTblReservationPaymentWithTransfers() {
        return this.tblReservationPaymentWithTransfers;
    }

    public void setTblReservationPaymentWithTransfers(Set tblReservationPaymentWithTransfers) {
        this.tblReservationPaymentWithTransfers = tblReservationPaymentWithTransfers;
    }

    public Set getTblReservationPaymentWithGuaranteePayments() {
        return this.tblReservationPaymentWithGuaranteePayments;
    }

    public void setTblReservationPaymentWithGuaranteePayments(Set tblReservationPaymentWithGuaranteePayments) {
        this.tblReservationPaymentWithGuaranteePayments = tblReservationPaymentWithGuaranteePayments;
    }

    public Set getTblReservationPaymentWithCekGiros() {
        return this.tblReservationPaymentWithCekGiros;
    }

    public void setTblReservationPaymentWithCekGiros(Set tblReservationPaymentWithCekGiros) {
        this.tblReservationPaymentWithCekGiros = tblReservationPaymentWithCekGiros;
    }

}
