package hotelfx.persistence.model;
// Generated May 21, 2018 2:53:01 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javafx.beans.property.IntegerProperty;
import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleIntegerProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblReservationCheckInOut generated by hbm2java
 */
public class TblReservationCheckInOut implements java.io.Serializable {

    private final LongProperty idcheckInOut;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<RefReservationCheckInOutStatus> refReservationCheckInOutStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblRoom> tblRoom;
    private final StringProperty codeCheckInOut;
    private final ObjectProperty<Date> checkInDateTime;
    private final ObjectProperty<Date> checkOutDateTime;
    private final IntegerProperty childNumber;
    private final IntegerProperty adultNumber;
    private final IntegerProperty cardUsed;
    private final IntegerProperty cardMissed;
    private final ObjectProperty<BigDecimal> brokenCardCharge;
    private final IntegerProperty cardAdditional;
    private final ObjectProperty<BigDecimal> additionalCardCharge;
    private final StringProperty note;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    private Set tblReservationRoomTypeDetails;
    private Set tblReservationPaymentWithDeposits;
    private Set tblRoomCards;

    public TblReservationCheckInOut() {
        this.idcheckInOut = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.refReservationCheckInOutStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblRoom = new SimpleObjectProperty<>();
        this.codeCheckInOut = new SimpleStringProperty();
        this.checkInDateTime = new SimpleObjectProperty<>();
        this.checkOutDateTime = new SimpleObjectProperty<>();
        this.childNumber = new SimpleIntegerProperty();
        this.adultNumber = new SimpleIntegerProperty();
        this.cardUsed = new SimpleIntegerProperty();
        this.cardMissed = new SimpleIntegerProperty();
        this.brokenCardCharge = new SimpleObjectProperty<>();
        this.cardAdditional = new SimpleIntegerProperty();
        this.additionalCardCharge = new SimpleObjectProperty<>();
        this.note = new SimpleStringProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

        this.tblReservationRoomTypeDetails = new HashSet(0);
        this.tblReservationPaymentWithDeposits = new HashSet(0);
        this.tblRoomCards = new HashSet(0);
    }

    public TblReservationCheckInOut(long idcheckInOut) {
        this();
        idcheckInOutProperty().set(idcheckInOut);
    }

    public TblReservationCheckInOut(long idcheckInOut, RefRecordStatus refRecordStatus, RefReservationCheckInOutStatus refReservationCheckInOutStatus, TblEmployee tblEmployeeByLastUpdateBy, TblEmployee tblEmployeeByCreateBy, TblRoom tblRoom, String codeCheckInOut, Date checkInDateTime, Date checkOutDateTime, Integer childNumber, Integer adultNumber, Integer cardUsed, Integer cardMissed, BigDecimal brokenCardCharge, Integer cardAdditional, BigDecimal additionalCardCharge, String note, Date createDate, Date lastUpdateDate, Set tblReservationRoomTypeDetails, Set tblReservationPaymentWithDeposits, Set tblRoomCards) {
        this();
        idcheckInOutProperty().set(idcheckInOut);
        refRecordStatusProperty().set(refRecordStatus);
        refReservationCheckInOutStatusProperty().set(refReservationCheckInOutStatus);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblRoomProperty().set(tblRoom);
        codeCheckInOutProperty().set(codeCheckInOut);
        checkInDateTimeProperty().set(checkInDateTime);
        checkOutDateTimeProperty().set(checkOutDateTime);
        childNumberProperty().set(childNumber);
        adultNumberProperty().set(adultNumber);
        cardUsedProperty().set(cardUsed);
        cardMissedProperty().set(cardMissed);
        brokenCardChargeProperty().set(brokenCardCharge);
        cardAdditionalProperty().set(cardAdditional);
        additionalCardChargeProperty().set(additionalCardCharge);
        noteProperty().set(note);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

        this.tblReservationRoomTypeDetails = tblReservationRoomTypeDetails;
        this.tblReservationPaymentWithDeposits = tblReservationPaymentWithDeposits;
        this.tblRoomCards = tblRoomCards;
    }

    public TblReservationCheckInOut(TblReservationCheckInOut tblReservationCheckInOut) {
        this();
        idcheckInOutProperty().set(tblReservationCheckInOut.getIdcheckInOut());
        refRecordStatusProperty().set(tblReservationCheckInOut.getRefRecordStatus());
        refReservationCheckInOutStatusProperty().set(tblReservationCheckInOut.getRefReservationCheckInOutStatus());
        tblEmployeeByLastUpdateByProperty().set(tblReservationCheckInOut.getTblEmployeeByLastUpdateBy());
        tblEmployeeByCreateByProperty().set(tblReservationCheckInOut.getTblEmployeeByCreateBy());
        tblRoomProperty().set(tblReservationCheckInOut.getTblRoom());
        codeCheckInOutProperty().set(tblReservationCheckInOut.getCodeCheckInOut());
        checkInDateTimeProperty().set(tblReservationCheckInOut.getCheckInDateTime());
        checkOutDateTimeProperty().set(tblReservationCheckInOut.getCheckOutDateTime());
        childNumberProperty().set(tblReservationCheckInOut.getChildNumber());
        adultNumberProperty().set(tblReservationCheckInOut.getAdultNumber());
        cardUsedProperty().set(tblReservationCheckInOut.getCardUsed());
        cardMissedProperty().set(tblReservationCheckInOut.getCardMissed());
        brokenCardChargeProperty().set(tblReservationCheckInOut.getBrokenCardCharge());
        cardAdditionalProperty().set(tblReservationCheckInOut.getCardAdditional());
        additionalCardChargeProperty().set(tblReservationCheckInOut.getAdditionalCardCharge());
        noteProperty().set(tblReservationCheckInOut.getNote());
        createDateProperty().set(tblReservationCheckInOut.getCreateDate());
        lastUpdateDateProperty().set(tblReservationCheckInOut.getLastUpdateDate());

        this.tblReservationRoomTypeDetails = tblReservationCheckInOut.getTblReservationRoomTypeDetails();
        this.tblReservationPaymentWithDeposits = tblReservationCheckInOut.getTblReservationPaymentWithDeposits();
        this.tblRoomCards = tblReservationCheckInOut.getTblRoomCards();
    }

    public final LongProperty idcheckInOutProperty() {
        return this.idcheckInOut;
    }

    public long getIdcheckInOut() {
        return idcheckInOutProperty().get();
    }

    public void setIdcheckInOut(long idcheckInOut) {
        idcheckInOutProperty().set(idcheckInOut);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<RefReservationCheckInOutStatus> refReservationCheckInOutStatusProperty() {
        return this.refReservationCheckInOutStatus;
    }

    public RefReservationCheckInOutStatus getRefReservationCheckInOutStatus() {
        return refReservationCheckInOutStatusProperty().get();
    }

    public void setRefReservationCheckInOutStatus(RefReservationCheckInOutStatus refReservationCheckInOutStatus) {
        refReservationCheckInOutStatusProperty().set(refReservationCheckInOutStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblRoom> tblRoomProperty() {
        return this.tblRoom;
    }

    public TblRoom getTblRoom() {
        return tblRoomProperty().get();
    }

    public void setTblRoom(TblRoom tblRoom) {
        tblRoomProperty().set(tblRoom);
    }

    public final StringProperty codeCheckInOutProperty() {
        return this.codeCheckInOut;
    }

    public String getCodeCheckInOut() {
        return codeCheckInOutProperty().get();
    }

    public void setCodeCheckInOut(String codeCheckInOut) {
        codeCheckInOutProperty().set(codeCheckInOut);
    }

    public final ObjectProperty<Date> checkInDateTimeProperty() {
        return this.checkInDateTime;
    }

    public Date getCheckInDateTime() {
        return checkInDateTimeProperty().get();
    }

    public void setCheckInDateTime(Date checkInDateTime) {
        checkInDateTimeProperty().set(checkInDateTime);
    }

    public final ObjectProperty<Date> checkOutDateTimeProperty() {
        return this.checkOutDateTime;
    }

    public Date getCheckOutDateTime() {
        return checkOutDateTimeProperty().get();
    }

    public void setCheckOutDateTime(Date checkOutDateTime) {
        checkOutDateTimeProperty().set(checkOutDateTime);
    }

    public final IntegerProperty childNumberProperty() {
        return this.childNumber;
    }

    public Integer getChildNumber() {
        return childNumberProperty().get();
    }

    public void setChildNumber(Integer childNumber) {
        childNumberProperty().set(childNumber);
    }

    public final IntegerProperty adultNumberProperty() {
        return this.adultNumber;
    }

    public Integer getAdultNumber() {
        return adultNumberProperty().get();
    }

    public void setAdultNumber(Integer adultNumber) {
        adultNumberProperty().set(adultNumber);
    }

    public final IntegerProperty cardUsedProperty() {
        return this.cardUsed;
    }

    public Integer getCardUsed() {
        return cardUsedProperty().get();
    }

    public void setCardUsed(Integer cardUsed) {
        cardUsedProperty().set(cardUsed);
    }

    public final IntegerProperty cardMissedProperty() {
        return this.cardMissed;
    }

    public Integer getCardMissed() {
        return cardMissedProperty().get();
    }

    public void setCardMissed(Integer cardMissed) {
        cardMissedProperty().set(cardMissed);
    }

    public final ObjectProperty<BigDecimal> brokenCardChargeProperty() {
        return this.brokenCardCharge;
    }

    public BigDecimal getBrokenCardCharge() {
        return brokenCardChargeProperty().get();
    }

    public void setBrokenCardCharge(BigDecimal brokenCardCharge) {
        brokenCardChargeProperty().set(brokenCardCharge);
    }

    public final IntegerProperty cardAdditionalProperty() {
        return this.cardAdditional;
    }

    public Integer getCardAdditional() {
        return cardAdditionalProperty().get();
    }

    public void setCardAdditional(Integer cardAdditional) {
        cardAdditionalProperty().set(cardAdditional);
    }

    public final ObjectProperty<BigDecimal> additionalCardChargeProperty() {
        return this.additionalCardCharge;
    }

    public BigDecimal getAdditionalCardCharge() {
        return additionalCardChargeProperty().get();
    }

    public void setAdditionalCardCharge(BigDecimal additionalCardCharge) {
        additionalCardChargeProperty().set(additionalCardCharge);
    }

    public final StringProperty noteProperty() {
        return this.note;
    }

    public String getNote() {
        return noteProperty().get();
    }

    public void setNote(String note) {
        noteProperty().set(note);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

    public Set getTblReservationRoomTypeDetails() {
        return this.tblReservationRoomTypeDetails;
    }

    public void setTblReservationRoomTypeDetails(Set tblReservationRoomTypeDetails) {
        this.tblReservationRoomTypeDetails = tblReservationRoomTypeDetails;
    }

    public Set getTblReservationPaymentWithDeposits() {
        return this.tblReservationPaymentWithDeposits;
    }

    public void setTblReservationPaymentWithDeposits(Set tblReservationPaymentWithDeposits) {
        this.tblReservationPaymentWithDeposits = tblReservationPaymentWithDeposits;
    }

    public Set getTblRoomCards() {
        return this.tblRoomCards;
    }

    public void setTblRoomCards(Set tblRoomCards) {
        this.tblRoomCards = tblRoomCards;
    }

}
