package hotelfx.persistence.model;
// Generated Sep 28, 2017 1:30:00 PM by Hibernate Tools 4.3.1

import java.util.Date;

import javafx.beans.property.IntegerProperty;
import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleIntegerProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblReservationRoomTypeDetailChildDetail generated by hbm2java
 */
public class TblReservationRoomTypeDetailChildDetail implements java.io.Serializable {

    private final LongProperty iddetail;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblReservationRoomTypeDetail> tblReservationRoomTypeDetail;
    private final StringProperty childName;
    private final IntegerProperty childAge;
    private final StringProperty childNote;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    public TblReservationRoomTypeDetailChildDetail() {
        this.iddetail = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblReservationRoomTypeDetail = new SimpleObjectProperty<>();
        this.childName = new SimpleStringProperty();
        this.childAge = new SimpleIntegerProperty();
        this.childNote = new SimpleStringProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

    }

    public TblReservationRoomTypeDetailChildDetail(long iddetail) {
        this();
        iddetailProperty().set(iddetail);
    }

    public TblReservationRoomTypeDetailChildDetail(long iddetail, RefRecordStatus refRecordStatus, TblEmployee tblEmployeeByCreateBy, TblEmployee tblEmployeeByLastUpdateBy, TblReservationRoomTypeDetail tblReservationRoomTypeDetail, String childName, Integer childAge, String childNote, Date createDate, Date lastUpdateDate) {
        this();
        iddetailProperty().set(iddetail);
        refRecordStatusProperty().set(refRecordStatus);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblReservationRoomTypeDetailProperty().set(tblReservationRoomTypeDetail);
        childNameProperty().set(childName);
        childAgeProperty().set(childAge);
        childNoteProperty().set(childNote);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

    }

    public TblReservationRoomTypeDetailChildDetail(TblReservationRoomTypeDetailChildDetail tblReservationRoomTypeDetailChildDetail) {
        this();
        iddetailProperty().set(tblReservationRoomTypeDetailChildDetail.getIddetail());
        refRecordStatusProperty().set(tblReservationRoomTypeDetailChildDetail.getRefRecordStatus());
        tblEmployeeByCreateByProperty().set(tblReservationRoomTypeDetailChildDetail.getTblEmployeeByCreateBy());
        tblEmployeeByLastUpdateByProperty().set(tblReservationRoomTypeDetailChildDetail.getTblEmployeeByLastUpdateBy());
        tblReservationRoomTypeDetailProperty().set(tblReservationRoomTypeDetailChildDetail.getTblReservationRoomTypeDetail());
        childNameProperty().set(tblReservationRoomTypeDetailChildDetail.getChildName());
        childAgeProperty().set(tblReservationRoomTypeDetailChildDetail.getChildAge());
        childNoteProperty().set(tblReservationRoomTypeDetailChildDetail.getChildNote());
        createDateProperty().set(tblReservationRoomTypeDetailChildDetail.getCreateDate());
        lastUpdateDateProperty().set(tblReservationRoomTypeDetailChildDetail.getLastUpdateDate());

    }

    public final LongProperty iddetailProperty() {
        return this.iddetail;
    }

    public long getIddetail() {
        return iddetailProperty().get();
    }

    public void setIddetail(long iddetail) {
        iddetailProperty().set(iddetail);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblReservationRoomTypeDetail> tblReservationRoomTypeDetailProperty() {
        return this.tblReservationRoomTypeDetail;
    }

    public TblReservationRoomTypeDetail getTblReservationRoomTypeDetail() {
        return tblReservationRoomTypeDetailProperty().get();
    }

    public void setTblReservationRoomTypeDetail(TblReservationRoomTypeDetail tblReservationRoomTypeDetail) {
        tblReservationRoomTypeDetailProperty().set(tblReservationRoomTypeDetail);
    }

    public final StringProperty childNameProperty() {
        return this.childName;
    }

    public String getChildName() {
        return childNameProperty().get();
    }

    public void setChildName(String childName) {
        childNameProperty().set(childName);
    }

    public final IntegerProperty childAgeProperty() {
        return this.childAge;
    }

    public Integer getChildAge() {
        return childAgeProperty().get();
    }

    public void setChildAge(Integer childAge) {
        childAgeProperty().set(childAge);
    }

    public final StringProperty childNoteProperty() {
        return this.childNote;
    }

    public String getChildNote() {
        return childNoteProperty().get();
    }

    public void setChildNote(String childNote) {
        childNoteProperty().set(childNote);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

}
