package hotelfx.persistence.model;
// Generated Oct 30, 2018 10:45:55 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblReservationCancelingFee generated by hbm2java
 */
public class TblReservationCancelingFee implements java.io.Serializable {

    private final LongProperty idreservationCancelingFee;
    private final ObjectProperty<RefEndOfDayDataStatus> refEndOfDayDataStatus;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblReservation> tblReservation;
    private final ObjectProperty<BigDecimal> cancelingFeeNominal;
    private final StringProperty note;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    public TblReservationCancelingFee() {
        this.idreservationCancelingFee = new SimpleLongProperty();
        this.refEndOfDayDataStatus = new SimpleObjectProperty<>();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblReservation = new SimpleObjectProperty<>();
        this.cancelingFeeNominal = new SimpleObjectProperty<>();
        this.note = new SimpleStringProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

    }

    public TblReservationCancelingFee(long idreservationCancelingFee) {
        this();
        idreservationCancelingFeeProperty().set(idreservationCancelingFee);
    }

    public TblReservationCancelingFee(long idreservationCancelingFee, RefEndOfDayDataStatus refEndOfDayDataStatus, RefRecordStatus refRecordStatus, TblEmployee tblEmployeeByCreateBy, TblEmployee tblEmployeeByLastUpdateBy, TblReservation tblReservation, BigDecimal cancelingFeeNominal, String note, Date createDate, Date lastUpdateDate) {
        this();
        idreservationCancelingFeeProperty().set(idreservationCancelingFee);
        refEndOfDayDataStatusProperty().set(refEndOfDayDataStatus);
        refRecordStatusProperty().set(refRecordStatus);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblReservationProperty().set(tblReservation);
        cancelingFeeNominalProperty().set(cancelingFeeNominal);
        noteProperty().set(note);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

    }

    public TblReservationCancelingFee(TblReservationCancelingFee tblReservationCancelingFee) {
        this();
        idreservationCancelingFeeProperty().set(tblReservationCancelingFee.getIdreservationCancelingFee());
        refEndOfDayDataStatusProperty().set(tblReservationCancelingFee.getRefEndOfDayDataStatus());
        refRecordStatusProperty().set(tblReservationCancelingFee.getRefRecordStatus());
        tblEmployeeByCreateByProperty().set(tblReservationCancelingFee.getTblEmployeeByCreateBy());
        tblEmployeeByLastUpdateByProperty().set(tblReservationCancelingFee.getTblEmployeeByLastUpdateBy());
        tblReservationProperty().set(tblReservationCancelingFee.getTblReservation());
        cancelingFeeNominalProperty().set(tblReservationCancelingFee.getCancelingFeeNominal());
        noteProperty().set(tblReservationCancelingFee.getNote());
        createDateProperty().set(tblReservationCancelingFee.getCreateDate());
        lastUpdateDateProperty().set(tblReservationCancelingFee.getLastUpdateDate());

    }

    public final LongProperty idreservationCancelingFeeProperty() {
        return this.idreservationCancelingFee;
    }

    public long getIdreservationCancelingFee() {
        return idreservationCancelingFeeProperty().get();
    }

    public void setIdreservationCancelingFee(long idreservationCancelingFee) {
        idreservationCancelingFeeProperty().set(idreservationCancelingFee);
    }

    public final ObjectProperty<RefEndOfDayDataStatus> refEndOfDayDataStatusProperty() {
        return this.refEndOfDayDataStatus;
    }

    public RefEndOfDayDataStatus getRefEndOfDayDataStatus() {
        return refEndOfDayDataStatusProperty().get();
    }

    public void setRefEndOfDayDataStatus(RefEndOfDayDataStatus refEndOfDayDataStatus) {
        refEndOfDayDataStatusProperty().set(refEndOfDayDataStatus);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblReservation> tblReservationProperty() {
        return this.tblReservation;
    }

    public TblReservation getTblReservation() {
        return tblReservationProperty().get();
    }

    public void setTblReservation(TblReservation tblReservation) {
        tblReservationProperty().set(tblReservation);
    }

    public final ObjectProperty<BigDecimal> cancelingFeeNominalProperty() {
        return this.cancelingFeeNominal;
    }

    public BigDecimal getCancelingFeeNominal() {
        return cancelingFeeNominalProperty().get();
    }

    public void setCancelingFeeNominal(BigDecimal cancelingFeeNominal) {
        cancelingFeeNominalProperty().set(cancelingFeeNominal);
    }

    public final StringProperty noteProperty() {
        return this.note;
    }

    public String getNote() {
        return noteProperty().get();
    }

    public void setNote(String note) {
        noteProperty().set(note);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

}
