package hotelfx.persistence.model;
// Generated May 16, 2018 4:42:59 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblReservationRoomItem generated by hbm2java
 */
public class TblReservationRoomItem implements java.io.Serializable {

    private final LongProperty idrri;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblReservationRoomTypeDetail> tblReservationRoomTypeDetail;
    private final ObjectProperty<Date> rridate;
    private final StringProperty rrinote;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    private Set tblReservationRoomItemDetails;

    public TblReservationRoomItem() {
        this.idrri = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblReservationRoomTypeDetail = new SimpleObjectProperty<>();
        this.rridate = new SimpleObjectProperty<>();
        this.rrinote = new SimpleStringProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

        this.tblReservationRoomItemDetails = new HashSet(0);
    }

    public TblReservationRoomItem(long idrri) {
        this();
        idrriProperty().set(idrri);
    }

    public TblReservationRoomItem(long idrri, RefRecordStatus refRecordStatus, TblEmployee tblEmployeeByCreateBy, TblEmployee tblEmployeeByLastUpdateBy, TblReservationRoomTypeDetail tblReservationRoomTypeDetail, Date rridate, String rrinote, Date createDate, Date lastUpdateDate, Set tblReservationRoomItemDetails) {
        this();
        idrriProperty().set(idrri);
        refRecordStatusProperty().set(refRecordStatus);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblReservationRoomTypeDetailProperty().set(tblReservationRoomTypeDetail);
        rridateProperty().set(rridate);
        rrinoteProperty().set(rrinote);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

        this.tblReservationRoomItemDetails = tblReservationRoomItemDetails;
    }

    public TblReservationRoomItem(TblReservationRoomItem tblReservationRoomItem) {
        this();
        idrriProperty().set(tblReservationRoomItem.getIdrri());
        refRecordStatusProperty().set(tblReservationRoomItem.getRefRecordStatus());
        tblEmployeeByCreateByProperty().set(tblReservationRoomItem.getTblEmployeeByCreateBy());
        tblEmployeeByLastUpdateByProperty().set(tblReservationRoomItem.getTblEmployeeByLastUpdateBy());
        tblReservationRoomTypeDetailProperty().set(tblReservationRoomItem.getTblReservationRoomTypeDetail());
        rridateProperty().set(tblReservationRoomItem.getRridate());
        rrinoteProperty().set(tblReservationRoomItem.getRrinote());
        createDateProperty().set(tblReservationRoomItem.getCreateDate());
        lastUpdateDateProperty().set(tblReservationRoomItem.getLastUpdateDate());

        this.tblReservationRoomItemDetails = tblReservationRoomItem.getTblReservationRoomItemDetails();
    }

    public final LongProperty idrriProperty() {
        return this.idrri;
    }

    public long getIdrri() {
        return idrriProperty().get();
    }

    public void setIdrri(long idrri) {
        idrriProperty().set(idrri);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblReservationRoomTypeDetail> tblReservationRoomTypeDetailProperty() {
        return this.tblReservationRoomTypeDetail;
    }

    public TblReservationRoomTypeDetail getTblReservationRoomTypeDetail() {
        return tblReservationRoomTypeDetailProperty().get();
    }

    public void setTblReservationRoomTypeDetail(TblReservationRoomTypeDetail tblReservationRoomTypeDetail) {
        tblReservationRoomTypeDetailProperty().set(tblReservationRoomTypeDetail);
    }

    public final ObjectProperty<Date> rridateProperty() {
        return this.rridate;
    }

    public Date getRridate() {
        return rridateProperty().get();
    }

    public void setRridate(Date rridate) {
        rridateProperty().set(rridate);
    }

    public final StringProperty rrinoteProperty() {
        return this.rrinote;
    }

    public String getRrinote() {
        return rrinoteProperty().get();
    }

    public void setRrinote(String rrinote) {
        rrinoteProperty().set(rrinote);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

    public Set getTblReservationRoomItemDetails() {
        return this.tblReservationRoomItemDetails;
    }

    public void setTblReservationRoomItemDetails(Set tblReservationRoomItemDetails) {
        this.tblReservationRoomItemDetails = tblReservationRoomItemDetails;
    }

}
