package hotelfx.persistence.model;
// Generated May 18, 2018 3:25:45 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;

/**
 * TblReservationAdditionalItemReserved generated by hbm2java
 */
public class TblReservationAdditionalItemReserved implements java.io.Serializable {

    private final LongProperty idrair;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<RefReservationAdditionalItemReservedStatus> refReservationAdditionalItemReservedStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblItem> tblItem;
    private final ObjectProperty<TblReservationRoomTypeDetail> tblReservationRoomTypeDetail;
    private final ObjectProperty<Date> reservedDate;
    private final ObjectProperty<BigDecimal> reservedQuantity;
    private final ObjectProperty<BigDecimal> inUsedQuantity;
    private final ObjectProperty<BigDecimal> doneQuantity;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    public TblReservationAdditionalItemReserved() {
        this.idrair = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.refReservationAdditionalItemReservedStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblItem = new SimpleObjectProperty<>();
        this.tblReservationRoomTypeDetail = new SimpleObjectProperty<>();
        this.reservedDate = new SimpleObjectProperty<>();
        this.reservedQuantity = new SimpleObjectProperty<>();
        this.inUsedQuantity = new SimpleObjectProperty<>();
        this.doneQuantity = new SimpleObjectProperty<>();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

    }

    public TblReservationAdditionalItemReserved(long idrair) {
        this();
        idrairProperty().set(idrair);
    }

    public TblReservationAdditionalItemReserved(long idrair, RefRecordStatus refRecordStatus, RefReservationAdditionalItemReservedStatus refReservationAdditionalItemReservedStatus, TblEmployee tblEmployeeByCreateBy, TblEmployee tblEmployeeByLastUpdateBy, TblItem tblItem, TblReservationRoomTypeDetail tblReservationRoomTypeDetail, Date reservedDate, BigDecimal reservedQuantity, BigDecimal inUsedQuantity, BigDecimal doneQuantity, Date createDate, Date lastUpdateDate) {
        this();
        idrairProperty().set(idrair);
        refRecordStatusProperty().set(refRecordStatus);
        refReservationAdditionalItemReservedStatusProperty().set(refReservationAdditionalItemReservedStatus);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblItemProperty().set(tblItem);
        tblReservationRoomTypeDetailProperty().set(tblReservationRoomTypeDetail);
        reservedDateProperty().set(reservedDate);
        reservedQuantityProperty().set(reservedQuantity);
        inUsedQuantityProperty().set(inUsedQuantity);
        doneQuantityProperty().set(doneQuantity);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

    }

    public TblReservationAdditionalItemReserved(TblReservationAdditionalItemReserved tblReservationAdditionalItemReserved) {
        this();
        idrairProperty().set(tblReservationAdditionalItemReserved.getIdrair());
        refRecordStatusProperty().set(tblReservationAdditionalItemReserved.getRefRecordStatus());
        refReservationAdditionalItemReservedStatusProperty().set(tblReservationAdditionalItemReserved.getRefReservationAdditionalItemReservedStatus());
        tblEmployeeByCreateByProperty().set(tblReservationAdditionalItemReserved.getTblEmployeeByCreateBy());
        tblEmployeeByLastUpdateByProperty().set(tblReservationAdditionalItemReserved.getTblEmployeeByLastUpdateBy());
        tblItemProperty().set(tblReservationAdditionalItemReserved.getTblItem());
        tblReservationRoomTypeDetailProperty().set(tblReservationAdditionalItemReserved.getTblReservationRoomTypeDetail());
        reservedDateProperty().set(tblReservationAdditionalItemReserved.getReservedDate());
        reservedQuantityProperty().set(tblReservationAdditionalItemReserved.getReservedQuantity());
        inUsedQuantityProperty().set(tblReservationAdditionalItemReserved.getInUsedQuantity());
        doneQuantityProperty().set(tblReservationAdditionalItemReserved.getDoneQuantity());
        createDateProperty().set(tblReservationAdditionalItemReserved.getCreateDate());
        lastUpdateDateProperty().set(tblReservationAdditionalItemReserved.getLastUpdateDate());

    }

    public final LongProperty idrairProperty() {
        return this.idrair;
    }

    public long getIdrair() {
        return idrairProperty().get();
    }

    public void setIdrair(long idrair) {
        idrairProperty().set(idrair);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<RefReservationAdditionalItemReservedStatus> refReservationAdditionalItemReservedStatusProperty() {
        return this.refReservationAdditionalItemReservedStatus;
    }

    public RefReservationAdditionalItemReservedStatus getRefReservationAdditionalItemReservedStatus() {
        return refReservationAdditionalItemReservedStatusProperty().get();
    }

    public void setRefReservationAdditionalItemReservedStatus(RefReservationAdditionalItemReservedStatus refReservationAdditionalItemReservedStatus) {
        refReservationAdditionalItemReservedStatusProperty().set(refReservationAdditionalItemReservedStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblItem> tblItemProperty() {
        return this.tblItem;
    }

    public TblItem getTblItem() {
        return tblItemProperty().get();
    }

    public void setTblItem(TblItem tblItem) {
        tblItemProperty().set(tblItem);
    }

    public final ObjectProperty<TblReservationRoomTypeDetail> tblReservationRoomTypeDetailProperty() {
        return this.tblReservationRoomTypeDetail;
    }

    public TblReservationRoomTypeDetail getTblReservationRoomTypeDetail() {
        return tblReservationRoomTypeDetailProperty().get();
    }

    public void setTblReservationRoomTypeDetail(TblReservationRoomTypeDetail tblReservationRoomTypeDetail) {
        tblReservationRoomTypeDetailProperty().set(tblReservationRoomTypeDetail);
    }

    public final ObjectProperty<Date> reservedDateProperty() {
        return this.reservedDate;
    }

    public Date getReservedDate() {
        return reservedDateProperty().get();
    }

    public void setReservedDate(Date reservedDate) {
        reservedDateProperty().set(reservedDate);
    }

    public final ObjectProperty<BigDecimal> reservedQuantityProperty() {
        return this.reservedQuantity;
    }

    public BigDecimal getReservedQuantity() {
        return reservedQuantityProperty().get();
    }

    public void setReservedQuantity(BigDecimal reservedQuantity) {
        reservedQuantityProperty().set(reservedQuantity);
    }

    public final ObjectProperty<BigDecimal> inUsedQuantityProperty() {
        return this.inUsedQuantity;
    }

    public BigDecimal getInUsedQuantity() {
        return inUsedQuantityProperty().get();
    }

    public void setInUsedQuantity(BigDecimal inUsedQuantity) {
        inUsedQuantityProperty().set(inUsedQuantity);
    }

    public final ObjectProperty<BigDecimal> doneQuantityProperty() {
        return this.doneQuantity;
    }

    public BigDecimal getDoneQuantity() {
        return doneQuantityProperty().get();
    }

    public void setDoneQuantity(BigDecimal doneQuantity) {
        doneQuantityProperty().set(doneQuantity);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

}
