package hotelfx.persistence.model;
// Generated Nov 30, 2017 4:08:38 PM by Hibernate Tools 4.3.1

import java.util.Date;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblReservationPaymentWithTransfer generated by hbm2java
 */
public class TblReservationPaymentWithTransfer implements java.io.Serializable {

    private final LongProperty iddetail;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblBankAccount> tblBankAccountByReceiverBankAccount;
    private final ObjectProperty<TblBankAccount> tblBankAccountBySenderBankAccount;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblReservationPayment> tblReservationPayment;
    private final StringProperty codeTransfer;
    private final StringProperty senderName;
    private final StringProperty receiverName;
    private final StringProperty transferNote;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    public TblReservationPaymentWithTransfer() {
        this.iddetail = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblBankAccountByReceiverBankAccount = new SimpleObjectProperty<>();
        this.tblBankAccountBySenderBankAccount = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblReservationPayment = new SimpleObjectProperty<>();
        this.codeTransfer = new SimpleStringProperty();
        this.senderName = new SimpleStringProperty();
        this.receiverName = new SimpleStringProperty();
        this.transferNote = new SimpleStringProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

    }

    public TblReservationPaymentWithTransfer(long iddetail) {
        this();
        iddetailProperty().set(iddetail);
    }

    public TblReservationPaymentWithTransfer(long iddetail, RefRecordStatus refRecordStatus, TblBankAccount tblBankAccountByReceiverBankAccount, TblBankAccount tblBankAccountBySenderBankAccount, TblEmployee tblEmployeeByCreateBy, TblEmployee tblEmployeeByLastUpdateBy, TblReservationPayment tblReservationPayment, String codeTransfer, String senderName, String receiverName, String transferNote, Date createDate, Date lastUpdateDate) {
        this();
        iddetailProperty().set(iddetail);
        refRecordStatusProperty().set(refRecordStatus);
        tblBankAccountByReceiverBankAccountProperty().set(tblBankAccountByReceiverBankAccount);
        tblBankAccountBySenderBankAccountProperty().set(tblBankAccountBySenderBankAccount);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblReservationPaymentProperty().set(tblReservationPayment);
        codeTransferProperty().set(codeTransfer);
        senderNameProperty().set(senderName);
        receiverNameProperty().set(receiverName);
        transferNoteProperty().set(transferNote);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

    }

    public TblReservationPaymentWithTransfer(TblReservationPaymentWithTransfer tblReservationPaymentWithTransfer) {
        this();
        iddetailProperty().set(tblReservationPaymentWithTransfer.getIddetail());
        refRecordStatusProperty().set(tblReservationPaymentWithTransfer.getRefRecordStatus());
        tblBankAccountByReceiverBankAccountProperty().set(tblReservationPaymentWithTransfer.getTblBankAccountByReceiverBankAccount());
        tblBankAccountBySenderBankAccountProperty().set(tblReservationPaymentWithTransfer.getTblBankAccountBySenderBankAccount());
        tblEmployeeByCreateByProperty().set(tblReservationPaymentWithTransfer.getTblEmployeeByCreateBy());
        tblEmployeeByLastUpdateByProperty().set(tblReservationPaymentWithTransfer.getTblEmployeeByLastUpdateBy());
        tblReservationPaymentProperty().set(tblReservationPaymentWithTransfer.getTblReservationPayment());
        codeTransferProperty().set(tblReservationPaymentWithTransfer.getCodeTransfer());
        senderNameProperty().set(tblReservationPaymentWithTransfer.getSenderName());
        receiverNameProperty().set(tblReservationPaymentWithTransfer.getReceiverName());
        transferNoteProperty().set(tblReservationPaymentWithTransfer.getTransferNote());
        createDateProperty().set(tblReservationPaymentWithTransfer.getCreateDate());
        lastUpdateDateProperty().set(tblReservationPaymentWithTransfer.getLastUpdateDate());

    }

    public final LongProperty iddetailProperty() {
        return this.iddetail;
    }

    public long getIddetail() {
        return iddetailProperty().get();
    }

    public void setIddetail(long iddetail) {
        iddetailProperty().set(iddetail);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblBankAccount> tblBankAccountByReceiverBankAccountProperty() {
        return this.tblBankAccountByReceiverBankAccount;
    }

    public TblBankAccount getTblBankAccountByReceiverBankAccount() {
        return tblBankAccountByReceiverBankAccountProperty().get();
    }

    public void setTblBankAccountByReceiverBankAccount(TblBankAccount tblBankAccountByReceiverBankAccount) {
        tblBankAccountByReceiverBankAccountProperty().set(tblBankAccountByReceiverBankAccount);
    }

    public final ObjectProperty<TblBankAccount> tblBankAccountBySenderBankAccountProperty() {
        return this.tblBankAccountBySenderBankAccount;
    }

    public TblBankAccount getTblBankAccountBySenderBankAccount() {
        return tblBankAccountBySenderBankAccountProperty().get();
    }

    public void setTblBankAccountBySenderBankAccount(TblBankAccount tblBankAccountBySenderBankAccount) {
        tblBankAccountBySenderBankAccountProperty().set(tblBankAccountBySenderBankAccount);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblReservationPayment> tblReservationPaymentProperty() {
        return this.tblReservationPayment;
    }

    public TblReservationPayment getTblReservationPayment() {
        return tblReservationPaymentProperty().get();
    }

    public void setTblReservationPayment(TblReservationPayment tblReservationPayment) {
        tblReservationPaymentProperty().set(tblReservationPayment);
    }

    public final StringProperty codeTransferProperty() {
        return this.codeTransfer;
    }

    public String getCodeTransfer() {
        return codeTransferProperty().get();
    }

    public void setCodeTransfer(String codeTransfer) {
        codeTransferProperty().set(codeTransfer);
    }

    public final StringProperty senderNameProperty() {
        return this.senderName;
    }

    public String getSenderName() {
        return senderNameProperty().get();
    }

    public void setSenderName(String senderName) {
        senderNameProperty().set(senderName);
    }

    public final StringProperty receiverNameProperty() {
        return this.receiverName;
    }

    public String getReceiverName() {
        return receiverNameProperty().get();
    }

    public void setReceiverName(String receiverName) {
        receiverNameProperty().set(receiverName);
    }

    public final StringProperty transferNoteProperty() {
        return this.transferNote;
    }

    public String getTransferNote() {
        return transferNoteProperty().get();
    }

    public void setTransferNote(String transferNote) {
        transferNoteProperty().set(transferNote);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

}
