package hotelfx.persistence.model;
// Generated Oct 29, 2018 4:55:34 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javafx.beans.property.BooleanProperty;
import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleBooleanProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblRoomService generated by hbm2java
 */
public class TblRoomService implements java.io.Serializable {

    private final LongProperty idroomService;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final StringProperty codeRoomService;
    private final StringProperty serviceName;
    private final ObjectProperty<BigDecimal> price;
    private final StringProperty note;
    private final BooleanProperty hotelDiscountable;
    private final BooleanProperty cardDiscountable;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    private Set tblRoomTypeRoomServices;
    private Set tblReservationRescheduleCanceleds;
    private Set tblReservationAdditionalServices;
    private Set tblReservationRoomTypeDetailRoomServices;

    public TblRoomService() {
        this.idroomService = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.codeRoomService = new SimpleStringProperty();
        this.serviceName = new SimpleStringProperty();
        this.price = new SimpleObjectProperty<>();
        this.note = new SimpleStringProperty();
        this.hotelDiscountable = new SimpleBooleanProperty();
        this.cardDiscountable = new SimpleBooleanProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

        this.tblRoomTypeRoomServices = new HashSet(0);
        this.tblReservationRescheduleCanceleds = new HashSet(0);
        this.tblReservationAdditionalServices = new HashSet(0);
        this.tblReservationRoomTypeDetailRoomServices = new HashSet(0);
    }

    public TblRoomService(long idroomService) {
        this();
        idroomServiceProperty().set(idroomService);
    }

    public TblRoomService(long idroomService, RefRecordStatus refRecordStatus, TblEmployee tblEmployeeByLastUpdateBy, TblEmployee tblEmployeeByCreateBy, String codeRoomService, String serviceName, BigDecimal price, String note, Boolean hotelDiscountable, Boolean cardDiscountable, Date createDate, Date lastUpdateDate, Set tblRoomTypeRoomServices, Set tblReservationRescheduleCanceleds, Set tblReservationAdditionalServices, Set tblReservationRoomTypeDetailRoomServices) {
        this();
        idroomServiceProperty().set(idroomService);
        refRecordStatusProperty().set(refRecordStatus);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        codeRoomServiceProperty().set(codeRoomService);
        serviceNameProperty().set(serviceName);
        priceProperty().set(price);
        noteProperty().set(note);
        hotelDiscountableProperty().set(hotelDiscountable);
        cardDiscountableProperty().set(cardDiscountable);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

        this.tblRoomTypeRoomServices = tblRoomTypeRoomServices;
        this.tblReservationRescheduleCanceleds = tblReservationRescheduleCanceleds;
        this.tblReservationAdditionalServices = tblReservationAdditionalServices;
        this.tblReservationRoomTypeDetailRoomServices = tblReservationRoomTypeDetailRoomServices;
    }

    public TblRoomService(TblRoomService tblRoomService) {
        this();
        idroomServiceProperty().set(tblRoomService.getIdroomService());
        refRecordStatusProperty().set(tblRoomService.getRefRecordStatus());
        tblEmployeeByLastUpdateByProperty().set(tblRoomService.getTblEmployeeByLastUpdateBy());
        tblEmployeeByCreateByProperty().set(tblRoomService.getTblEmployeeByCreateBy());
        codeRoomServiceProperty().set(tblRoomService.getCodeRoomService());
        serviceNameProperty().set(tblRoomService.getServiceName());
        priceProperty().set(tblRoomService.getPrice());
        noteProperty().set(tblRoomService.getNote());
        hotelDiscountableProperty().set(tblRoomService.getHotelDiscountable());
        cardDiscountableProperty().set(tblRoomService.getCardDiscountable());
        createDateProperty().set(tblRoomService.getCreateDate());
        lastUpdateDateProperty().set(tblRoomService.getLastUpdateDate());

        this.tblRoomTypeRoomServices = tblRoomService.getTblRoomTypeRoomServices();
        this.tblReservationRescheduleCanceleds = tblRoomService.getTblReservationRescheduleCanceleds();
        this.tblReservationAdditionalServices = tblRoomService.getTblReservationAdditionalServices();
        this.tblReservationRoomTypeDetailRoomServices = tblRoomService.getTblReservationRoomTypeDetailRoomServices();
    }

    public final LongProperty idroomServiceProperty() {
        return this.idroomService;
    }

    public long getIdroomService() {
        return idroomServiceProperty().get();
    }

    public void setIdroomService(long idroomService) {
        idroomServiceProperty().set(idroomService);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final StringProperty codeRoomServiceProperty() {
        return this.codeRoomService;
    }

    public String getCodeRoomService() {
        return codeRoomServiceProperty().get();
    }

    public void setCodeRoomService(String codeRoomService) {
        codeRoomServiceProperty().set(codeRoomService);
    }

    public final StringProperty serviceNameProperty() {
        return this.serviceName;
    }

    public String getServiceName() {
        return serviceNameProperty().get();
    }

    public void setServiceName(String serviceName) {
        serviceNameProperty().set(serviceName);
    }

    public final ObjectProperty<BigDecimal> priceProperty() {
        return this.price;
    }

    public BigDecimal getPrice() {
        return priceProperty().get();
    }

    public void setPrice(BigDecimal price) {
        priceProperty().set(price);
    }

    public final StringProperty noteProperty() {
        return this.note;
    }

    public String getNote() {
        return noteProperty().get();
    }

    public void setNote(String note) {
        noteProperty().set(note);
    }

    public final BooleanProperty hotelDiscountableProperty() {
        return this.hotelDiscountable;
    }

    public Boolean getHotelDiscountable() {
        return hotelDiscountableProperty().get();
    }

    public void setHotelDiscountable(Boolean hotelDiscountable) {
        hotelDiscountableProperty().set(hotelDiscountable);
    }

    public final BooleanProperty cardDiscountableProperty() {
        return this.cardDiscountable;
    }

    public Boolean getCardDiscountable() {
        return cardDiscountableProperty().get();
    }

    public void setCardDiscountable(Boolean cardDiscountable) {
        cardDiscountableProperty().set(cardDiscountable);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

    public Set getTblRoomTypeRoomServices() {
        return this.tblRoomTypeRoomServices;
    }

    public void setTblRoomTypeRoomServices(Set tblRoomTypeRoomServices) {
        this.tblRoomTypeRoomServices = tblRoomTypeRoomServices;
    }

    public Set getTblReservationRescheduleCanceleds() {
        return this.tblReservationRescheduleCanceleds;
    }

    public void setTblReservationRescheduleCanceleds(Set tblReservationRescheduleCanceleds) {
        this.tblReservationRescheduleCanceleds = tblReservationRescheduleCanceleds;
    }

    public Set getTblReservationAdditionalServices() {
        return this.tblReservationAdditionalServices;
    }

    public void setTblReservationAdditionalServices(Set tblReservationAdditionalServices) {
        this.tblReservationAdditionalServices = tblReservationAdditionalServices;
    }

    public Set getTblReservationRoomTypeDetailRoomServices() {
        return this.tblReservationRoomTypeDetailRoomServices;
    }

    public void setTblReservationRoomTypeDetailRoomServices(Set tblReservationRoomTypeDetailRoomServices) {
        this.tblReservationRoomTypeDetailRoomServices = tblReservationRoomTypeDetailRoomServices;
    }

    @Override
    public String toString() {
        return getServiceName();
    }
    
}
