package hotelfx.persistence.model;
// Generated Oct 29, 2018 4:55:34 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblReservationRoomTypeDetail generated by hbm2java
 */
public class TblReservationRoomTypeDetail implements java.io.Serializable {

    private final LongProperty iddetail;
    private final ObjectProperty<RefEndOfDayDataStatus> refEndOfDayDataStatus;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<RefReservationOrderByType> refReservationOrderByType;
    private final ObjectProperty<RefReservationPaymentType> refReservationPaymentType;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblReservation> tblReservation;
    private final ObjectProperty<TblReservationCheckInOut> tblReservationCheckInOut;
    private final ObjectProperty<TblRoomType> tblRoomType;
    private final StringProperty codeDetail;
    private final ObjectProperty<Date> checkInDateTime;
    private final ObjectProperty<Date> checkOutDateTime;
    private final StringProperty note;
    private final ObjectProperty<Date> reservationRoomDate;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    private Set tblReservationBreakfastVouchers;
    private Set tblReservationAdditionalItemReserveds;
    private Set tblReservationRoomTypeDetailRoomServices;
    private Set tblReservationRoomTypeDetailItems;
    private Set tblReservationAdditionalItems;
    private Set tblReservationRoomTypeDetailTravelAgentDiscountDetails;
    private Set tblReservationRoomTypeDetailRoomPriceDetails;
    private Set tblReservationBrokenItems;
    private Set tblReservationRescheduleCanceleds;
    private Set tblReservationRoomItems;
    private Set tblReservationRoomTypeDetailChildDetails;
    private Set tblReservationAdditionalServices;

    public TblReservationRoomTypeDetail() {
        this.iddetail = new SimpleLongProperty();
        this.refEndOfDayDataStatus = new SimpleObjectProperty<>();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.refReservationOrderByType = new SimpleObjectProperty<>();
        this.refReservationPaymentType = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblReservation = new SimpleObjectProperty<>();
        this.tblReservationCheckInOut = new SimpleObjectProperty<>();
        this.tblRoomType = new SimpleObjectProperty<>();
        this.codeDetail = new SimpleStringProperty();
        this.checkInDateTime = new SimpleObjectProperty<>();
        this.checkOutDateTime = new SimpleObjectProperty<>();
        this.note = new SimpleStringProperty();
        this.reservationRoomDate = new SimpleObjectProperty<>();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

        this.tblReservationBreakfastVouchers = new HashSet(0);
        this.tblReservationAdditionalItemReserveds = new HashSet(0);
        this.tblReservationRoomTypeDetailRoomServices = new HashSet(0);
        this.tblReservationRoomTypeDetailItems = new HashSet(0);
        this.tblReservationAdditionalItems = new HashSet(0);
        this.tblReservationRoomTypeDetailTravelAgentDiscountDetails = new HashSet(0);
        this.tblReservationRoomTypeDetailRoomPriceDetails = new HashSet(0);
        this.tblReservationBrokenItems = new HashSet(0);
        this.tblReservationRescheduleCanceleds = new HashSet(0);
        this.tblReservationRoomItems = new HashSet(0);
        this.tblReservationRoomTypeDetailChildDetails = new HashSet(0);
        this.tblReservationAdditionalServices = new HashSet(0);
    }

    public TblReservationRoomTypeDetail(long iddetail) {
        this();
        iddetailProperty().set(iddetail);
    }

    public TblReservationRoomTypeDetail(long iddetail, RefEndOfDayDataStatus refEndOfDayDataStatus, RefRecordStatus refRecordStatus, RefReservationOrderByType refReservationOrderByType, RefReservationPaymentType refReservationPaymentType, TblEmployee tblEmployeeByCreateBy, TblEmployee tblEmployeeByLastUpdateBy, TblReservation tblReservation, TblReservationCheckInOut tblReservationCheckInOut, TblRoomType tblRoomType, String codeDetail, Date checkInDateTime, Date checkOutDateTime, String note, Date reservationRoomDate, Date createDate, Date lastUpdateDate, Set tblReservationBreakfastVouchers, Set tblReservationAdditionalItemReserveds, Set tblReservationRoomTypeDetailRoomServices, Set tblReservationRoomTypeDetailItems, Set tblReservationAdditionalItems, Set tblReservationRoomTypeDetailTravelAgentDiscountDetails, Set tblReservationRoomTypeDetailRoomPriceDetails, Set tblReservationBrokenItems, Set tblReservationRescheduleCanceleds, Set tblReservationRoomItems, Set tblReservationRoomTypeDetailChildDetails, Set tblReservationAdditionalServices) {
        this();
        iddetailProperty().set(iddetail);
        refEndOfDayDataStatusProperty().set(refEndOfDayDataStatus);
        refRecordStatusProperty().set(refRecordStatus);
        refReservationOrderByTypeProperty().set(refReservationOrderByType);
        refReservationPaymentTypeProperty().set(refReservationPaymentType);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblReservationProperty().set(tblReservation);
        tblReservationCheckInOutProperty().set(tblReservationCheckInOut);
        tblRoomTypeProperty().set(tblRoomType);
        codeDetailProperty().set(codeDetail);
        checkInDateTimeProperty().set(checkInDateTime);
        checkOutDateTimeProperty().set(checkOutDateTime);
        noteProperty().set(note);
        reservationRoomDateProperty().set(reservationRoomDate);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

        this.tblReservationBreakfastVouchers = tblReservationBreakfastVouchers;
        this.tblReservationAdditionalItemReserveds = tblReservationAdditionalItemReserveds;
        this.tblReservationRoomTypeDetailRoomServices = tblReservationRoomTypeDetailRoomServices;
        this.tblReservationRoomTypeDetailItems = tblReservationRoomTypeDetailItems;
        this.tblReservationAdditionalItems = tblReservationAdditionalItems;
        this.tblReservationRoomTypeDetailTravelAgentDiscountDetails = tblReservationRoomTypeDetailTravelAgentDiscountDetails;
        this.tblReservationRoomTypeDetailRoomPriceDetails = tblReservationRoomTypeDetailRoomPriceDetails;
        this.tblReservationBrokenItems = tblReservationBrokenItems;
        this.tblReservationRescheduleCanceleds = tblReservationRescheduleCanceleds;
        this.tblReservationRoomItems = tblReservationRoomItems;
        this.tblReservationRoomTypeDetailChildDetails = tblReservationRoomTypeDetailChildDetails;
        this.tblReservationAdditionalServices = tblReservationAdditionalServices;
    }

    public TblReservationRoomTypeDetail(TblReservationRoomTypeDetail tblReservationRoomTypeDetail) {
        this();
        iddetailProperty().set(tblReservationRoomTypeDetail.getIddetail());
        refEndOfDayDataStatusProperty().set(tblReservationRoomTypeDetail.getRefEndOfDayDataStatus());
        refRecordStatusProperty().set(tblReservationRoomTypeDetail.getRefRecordStatus());
        refReservationOrderByTypeProperty().set(tblReservationRoomTypeDetail.getRefReservationOrderByType());
        refReservationPaymentTypeProperty().set(tblReservationRoomTypeDetail.getRefReservationPaymentType());
        tblEmployeeByCreateByProperty().set(tblReservationRoomTypeDetail.getTblEmployeeByCreateBy());
        tblEmployeeByLastUpdateByProperty().set(tblReservationRoomTypeDetail.getTblEmployeeByLastUpdateBy());
        tblReservationProperty().set(tblReservationRoomTypeDetail.getTblReservation());
        tblReservationCheckInOutProperty().set(tblReservationRoomTypeDetail.getTblReservationCheckInOut());
        tblRoomTypeProperty().set(tblReservationRoomTypeDetail.getTblRoomType());
        codeDetailProperty().set(tblReservationRoomTypeDetail.getCodeDetail());
        checkInDateTimeProperty().set(tblReservationRoomTypeDetail.getCheckInDateTime());
        checkOutDateTimeProperty().set(tblReservationRoomTypeDetail.getCheckOutDateTime());
        noteProperty().set(tblReservationRoomTypeDetail.getNote());
        reservationRoomDateProperty().set(tblReservationRoomTypeDetail.getReservationRoomDate());
        createDateProperty().set(tblReservationRoomTypeDetail.getCreateDate());
        lastUpdateDateProperty().set(tblReservationRoomTypeDetail.getLastUpdateDate());

        this.tblReservationBreakfastVouchers = tblReservationRoomTypeDetail.getTblReservationBreakfastVouchers();
        this.tblReservationAdditionalItemReserveds = tblReservationRoomTypeDetail.getTblReservationAdditionalItemReserveds();
        this.tblReservationRoomTypeDetailRoomServices = tblReservationRoomTypeDetail.getTblReservationRoomTypeDetailRoomServices();
        this.tblReservationRoomTypeDetailItems = tblReservationRoomTypeDetail.getTblReservationRoomTypeDetailItems();
        this.tblReservationAdditionalItems = tblReservationRoomTypeDetail.getTblReservationAdditionalItems();
        this.tblReservationRoomTypeDetailTravelAgentDiscountDetails = tblReservationRoomTypeDetail.getTblReservationRoomTypeDetailTravelAgentDiscountDetails();
        this.tblReservationRoomTypeDetailRoomPriceDetails = tblReservationRoomTypeDetail.getTblReservationRoomTypeDetailRoomPriceDetails();
        this.tblReservationBrokenItems = tblReservationRoomTypeDetail.getTblReservationBrokenItems();
        this.tblReservationRescheduleCanceleds = tblReservationRoomTypeDetail.getTblReservationRescheduleCanceleds();
        this.tblReservationRoomItems = tblReservationRoomTypeDetail.getTblReservationRoomItems();
        this.tblReservationRoomTypeDetailChildDetails = tblReservationRoomTypeDetail.getTblReservationRoomTypeDetailChildDetails();
        this.tblReservationAdditionalServices = tblReservationRoomTypeDetail.getTblReservationAdditionalServices();
    }

    public final LongProperty iddetailProperty() {
        return this.iddetail;
    }

    public long getIddetail() {
        return iddetailProperty().get();
    }

    public void setIddetail(long iddetail) {
        iddetailProperty().set(iddetail);
    }

    public final ObjectProperty<RefEndOfDayDataStatus> refEndOfDayDataStatusProperty() {
        return this.refEndOfDayDataStatus;
    }

    public RefEndOfDayDataStatus getRefEndOfDayDataStatus() {
        return refEndOfDayDataStatusProperty().get();
    }

    public void setRefEndOfDayDataStatus(RefEndOfDayDataStatus refEndOfDayDataStatus) {
        refEndOfDayDataStatusProperty().set(refEndOfDayDataStatus);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<RefReservationOrderByType> refReservationOrderByTypeProperty() {
        return this.refReservationOrderByType;
    }

    public RefReservationOrderByType getRefReservationOrderByType() {
        return refReservationOrderByTypeProperty().get();
    }

    public void setRefReservationOrderByType(RefReservationOrderByType refReservationOrderByType) {
        refReservationOrderByTypeProperty().set(refReservationOrderByType);
    }

    public final ObjectProperty<RefReservationPaymentType> refReservationPaymentTypeProperty() {
        return this.refReservationPaymentType;
    }

    public RefReservationPaymentType getRefReservationPaymentType() {
        return refReservationPaymentTypeProperty().get();
    }

    public void setRefReservationPaymentType(RefReservationPaymentType refReservationPaymentType) {
        refReservationPaymentTypeProperty().set(refReservationPaymentType);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblReservation> tblReservationProperty() {
        return this.tblReservation;
    }

    public TblReservation getTblReservation() {
        return tblReservationProperty().get();
    }

    public void setTblReservation(TblReservation tblReservation) {
        tblReservationProperty().set(tblReservation);
    }

    public final ObjectProperty<TblReservationCheckInOut> tblReservationCheckInOutProperty() {
        return this.tblReservationCheckInOut;
    }

    public TblReservationCheckInOut getTblReservationCheckInOut() {
        return tblReservationCheckInOutProperty().get();
    }

    public void setTblReservationCheckInOut(TblReservationCheckInOut tblReservationCheckInOut) {
        tblReservationCheckInOutProperty().set(tblReservationCheckInOut);
    }

    public final ObjectProperty<TblRoomType> tblRoomTypeProperty() {
        return this.tblRoomType;
    }

    public TblRoomType getTblRoomType() {
        return tblRoomTypeProperty().get();
    }

    public void setTblRoomType(TblRoomType tblRoomType) {
        tblRoomTypeProperty().set(tblRoomType);
    }

    public final StringProperty codeDetailProperty() {
        return this.codeDetail;
    }

    public String getCodeDetail() {
        return codeDetailProperty().get();
    }

    public void setCodeDetail(String codeDetail) {
        codeDetailProperty().set(codeDetail);
    }

    public final ObjectProperty<Date> checkInDateTimeProperty() {
        return this.checkInDateTime;
    }

    public Date getCheckInDateTime() {
        return checkInDateTimeProperty().get();
    }

    public void setCheckInDateTime(Date checkInDateTime) {
        checkInDateTimeProperty().set(checkInDateTime);
    }

    public final ObjectProperty<Date> checkOutDateTimeProperty() {
        return this.checkOutDateTime;
    }

    public Date getCheckOutDateTime() {
        return checkOutDateTimeProperty().get();
    }

    public void setCheckOutDateTime(Date checkOutDateTime) {
        checkOutDateTimeProperty().set(checkOutDateTime);
    }

    public final StringProperty noteProperty() {
        return this.note;
    }

    public String getNote() {
        return noteProperty().get();
    }

    public void setNote(String note) {
        noteProperty().set(note);
    }

    public final ObjectProperty<Date> reservationRoomDateProperty() {
        return this.reservationRoomDate;
    }

    public Date getReservationRoomDate() {
        return reservationRoomDateProperty().get();
    }

    public void setReservationRoomDate(Date reservationRoomDate) {
        reservationRoomDateProperty().set(reservationRoomDate);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

    public Set getTblReservationBreakfastVouchers() {
        return this.tblReservationBreakfastVouchers;
    }

    public void setTblReservationBreakfastVouchers(Set tblReservationBreakfastVouchers) {
        this.tblReservationBreakfastVouchers = tblReservationBreakfastVouchers;
    }

    public Set getTblReservationAdditionalItemReserveds() {
        return this.tblReservationAdditionalItemReserveds;
    }

    public void setTblReservationAdditionalItemReserveds(Set tblReservationAdditionalItemReserveds) {
        this.tblReservationAdditionalItemReserveds = tblReservationAdditionalItemReserveds;
    }

    public Set getTblReservationRoomTypeDetailRoomServices() {
        return this.tblReservationRoomTypeDetailRoomServices;
    }

    public void setTblReservationRoomTypeDetailRoomServices(Set tblReservationRoomTypeDetailRoomServices) {
        this.tblReservationRoomTypeDetailRoomServices = tblReservationRoomTypeDetailRoomServices;
    }

    public Set getTblReservationRoomTypeDetailItems() {
        return this.tblReservationRoomTypeDetailItems;
    }

    public void setTblReservationRoomTypeDetailItems(Set tblReservationRoomTypeDetailItems) {
        this.tblReservationRoomTypeDetailItems = tblReservationRoomTypeDetailItems;
    }

    public Set getTblReservationAdditionalItems() {
        return this.tblReservationAdditionalItems;
    }

    public void setTblReservationAdditionalItems(Set tblReservationAdditionalItems) {
        this.tblReservationAdditionalItems = tblReservationAdditionalItems;
    }

    public Set getTblReservationRoomTypeDetailTravelAgentDiscountDetails() {
        return this.tblReservationRoomTypeDetailTravelAgentDiscountDetails;
    }

    public void setTblReservationRoomTypeDetailTravelAgentDiscountDetails(Set tblReservationRoomTypeDetailTravelAgentDiscountDetails) {
        this.tblReservationRoomTypeDetailTravelAgentDiscountDetails = tblReservationRoomTypeDetailTravelAgentDiscountDetails;
    }

    public Set getTblReservationRoomTypeDetailRoomPriceDetails() {
        return this.tblReservationRoomTypeDetailRoomPriceDetails;
    }

    public void setTblReservationRoomTypeDetailRoomPriceDetails(Set tblReservationRoomTypeDetailRoomPriceDetails) {
        this.tblReservationRoomTypeDetailRoomPriceDetails = tblReservationRoomTypeDetailRoomPriceDetails;
    }

    public Set getTblReservationBrokenItems() {
        return this.tblReservationBrokenItems;
    }

    public void setTblReservationBrokenItems(Set tblReservationBrokenItems) {
        this.tblReservationBrokenItems = tblReservationBrokenItems;
    }

    public Set getTblReservationRescheduleCanceleds() {
        return this.tblReservationRescheduleCanceleds;
    }

    public void setTblReservationRescheduleCanceleds(Set tblReservationRescheduleCanceleds) {
        this.tblReservationRescheduleCanceleds = tblReservationRescheduleCanceleds;
    }

    public Set getTblReservationRoomItems() {
        return this.tblReservationRoomItems;
    }

    public void setTblReservationRoomItems(Set tblReservationRoomItems) {
        this.tblReservationRoomItems = tblReservationRoomItems;
    }

    public Set getTblReservationRoomTypeDetailChildDetails() {
        return this.tblReservationRoomTypeDetailChildDetails;
    }

    public void setTblReservationRoomTypeDetailChildDetails(Set tblReservationRoomTypeDetailChildDetails) {
        this.tblReservationRoomTypeDetailChildDetails = tblReservationRoomTypeDetailChildDetails;
    }

    public Set getTblReservationAdditionalServices() {
        return this.tblReservationAdditionalServices;
    }

    public void setTblReservationAdditionalServices(Set tblReservationAdditionalServices) {
        this.tblReservationAdditionalServices = tblReservationAdditionalServices;
    }
    
    @Override
    public String toString(){
        return getCodeDetail();
    }

}
