package hotelfx.persistence.model;
// Generated May 15, 2018 12:47:45 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblReservationBill generated by hbm2java
 */
public class TblReservationBill implements java.io.Serializable {

    private final LongProperty idbill;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<RefReservationBillDiscountType> refReservationBillDiscountType;
    private final ObjectProperty<RefReservationBillStatus> refReservationBillStatus;
    private final ObjectProperty<RefReservationBillType> refReservationBillType;
    private final ObjectProperty<TblBankCard> tblBankCard;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblReservation> tblReservation;
    private final StringProperty codeBill;
    private final ObjectProperty<BigDecimal> serviceChargePercentage;
    private final ObjectProperty<BigDecimal> taxPercentage;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    private Set tblReservationPayments;

    public TblReservationBill() {
        this.idbill = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.refReservationBillDiscountType = new SimpleObjectProperty<>();
        this.refReservationBillStatus = new SimpleObjectProperty<>();
        this.refReservationBillType = new SimpleObjectProperty<>();
        this.tblBankCard = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblReservation = new SimpleObjectProperty<>();
        this.codeBill = new SimpleStringProperty();
        this.serviceChargePercentage = new SimpleObjectProperty<>();
        this.taxPercentage = new SimpleObjectProperty<>();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

        this.tblReservationPayments = new HashSet(0);
    }

    public TblReservationBill(long idbill, TblReservation tblReservation) {
        this();
        idbillProperty().set(idbill);
        tblReservationProperty().set(tblReservation);
    }

    public TblReservationBill(long idbill, RefRecordStatus refRecordStatus, RefReservationBillDiscountType refReservationBillDiscountType, RefReservationBillStatus refReservationBillStatus, RefReservationBillType refReservationBillType, TblBankCard tblBankCard, TblEmployee tblEmployeeByLastUpdateBy, TblEmployee tblEmployeeByCreateBy, TblReservation tblReservation, String codeBill, BigDecimal serviceChargePercentage, BigDecimal taxPercentage, Date createDate, Date lastUpdateDate, Set tblReservationPayments) {
        this();
        idbillProperty().set(idbill);
        refRecordStatusProperty().set(refRecordStatus);
        refReservationBillDiscountTypeProperty().set(refReservationBillDiscountType);
        refReservationBillStatusProperty().set(refReservationBillStatus);
        refReservationBillTypeProperty().set(refReservationBillType);
        tblBankCardProperty().set(tblBankCard);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblReservationProperty().set(tblReservation);
        codeBillProperty().set(codeBill);
        serviceChargePercentageProperty().set(serviceChargePercentage);
        taxPercentageProperty().set(taxPercentage);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

        this.tblReservationPayments = tblReservationPayments;
    }

    public TblReservationBill(TblReservationBill tblReservationBill) {
        this();
        idbillProperty().set(tblReservationBill.getIdbill());
        refRecordStatusProperty().set(tblReservationBill.getRefRecordStatus());
        refReservationBillDiscountTypeProperty().set(tblReservationBill.getRefReservationBillDiscountType());
        refReservationBillStatusProperty().set(tblReservationBill.getRefReservationBillStatus());
        refReservationBillTypeProperty().set(tblReservationBill.getRefReservationBillType());
        tblBankCardProperty().set(tblReservationBill.getTblBankCard());
        tblEmployeeByLastUpdateByProperty().set(tblReservationBill.getTblEmployeeByLastUpdateBy());
        tblEmployeeByCreateByProperty().set(tblReservationBill.getTblEmployeeByCreateBy());
        tblReservationProperty().set(tblReservationBill.getTblReservation());
        codeBillProperty().set(tblReservationBill.getCodeBill());
        serviceChargePercentageProperty().set(tblReservationBill.getServiceChargePercentage());
        taxPercentageProperty().set(tblReservationBill.getTaxPercentage());
        createDateProperty().set(tblReservationBill.getCreateDate());
        lastUpdateDateProperty().set(tblReservationBill.getLastUpdateDate());

        this.tblReservationPayments = tblReservationBill.getTblReservationPayments();
    }

    public final LongProperty idbillProperty() {
        return this.idbill;
    }

    public long getIdbill() {
        return idbillProperty().get();
    }

    public void setIdbill(long idbill) {
        idbillProperty().set(idbill);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<RefReservationBillDiscountType> refReservationBillDiscountTypeProperty() {
        return this.refReservationBillDiscountType;
    }

    public RefReservationBillDiscountType getRefReservationBillDiscountType() {
        return refReservationBillDiscountTypeProperty().get();
    }

    public void setRefReservationBillDiscountType(RefReservationBillDiscountType refReservationBillDiscountType) {
        refReservationBillDiscountTypeProperty().set(refReservationBillDiscountType);
    }

    public final ObjectProperty<RefReservationBillStatus> refReservationBillStatusProperty() {
        return this.refReservationBillStatus;
    }

    public RefReservationBillStatus getRefReservationBillStatus() {
        return refReservationBillStatusProperty().get();
    }

    public void setRefReservationBillStatus(RefReservationBillStatus refReservationBillStatus) {
        refReservationBillStatusProperty().set(refReservationBillStatus);
    }

    public final ObjectProperty<RefReservationBillType> refReservationBillTypeProperty() {
        return this.refReservationBillType;
    }

    public RefReservationBillType getRefReservationBillType() {
        return refReservationBillTypeProperty().get();
    }

    public void setRefReservationBillType(RefReservationBillType refReservationBillType) {
        refReservationBillTypeProperty().set(refReservationBillType);
    }

    public final ObjectProperty<TblBankCard> tblBankCardProperty() {
        return this.tblBankCard;
    }

    public TblBankCard getTblBankCard() {
        return tblBankCardProperty().get();
    }

    public void setTblBankCard(TblBankCard tblBankCard) {
        tblBankCardProperty().set(tblBankCard);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblReservation> tblReservationProperty() {
        return this.tblReservation;
    }

    public TblReservation getTblReservation() {
        return tblReservationProperty().get();
    }

    public void setTblReservation(TblReservation tblReservation) {
        tblReservationProperty().set(tblReservation);
    }

    public final StringProperty codeBillProperty() {
        return this.codeBill;
    }

    public String getCodeBill() {
        return codeBillProperty().get();
    }

    public void setCodeBill(String codeBill) {
        codeBillProperty().set(codeBill);
    }

    public final ObjectProperty<BigDecimal> serviceChargePercentageProperty() {
        return this.serviceChargePercentage;
    }

    public BigDecimal getServiceChargePercentage() {
        return serviceChargePercentageProperty().get();
    }

    public void setServiceChargePercentage(BigDecimal serviceChargePercentage) {
        serviceChargePercentageProperty().set(serviceChargePercentage);
    }

    public final ObjectProperty<BigDecimal> taxPercentageProperty() {
        return this.taxPercentage;
    }

    public BigDecimal getTaxPercentage() {
        return taxPercentageProperty().get();
    }

    public void setTaxPercentage(BigDecimal taxPercentage) {
        taxPercentageProperty().set(taxPercentage);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

    public Set getTblReservationPayments() {
        return this.tblReservationPayments;
    }

    public void setTblReservationPayments(Set tblReservationPayments) {
        this.tblReservationPayments = tblReservationPayments;
    }

}
