package hotelfx.persistence.model;
// Generated Nov 1, 2018 9:11:08 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblRoomCheckHouseKeepingAttendanceDetail generated by hbm2java
 */
public class TblRoomCheckHouseKeepingAttendanceDetail implements java.io.Serializable {

    private final LongProperty idrelation;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdatedBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreatedBy;
    private final ObjectProperty<TblItem> tblItem;
    private final ObjectProperty<TblRoomCheckHouseKeepingAttendance> tblRoomCheckHouseKeepingAttendance;
    private final StringProperty codeWorkSheet;
    private final ObjectProperty<BigDecimal> qtySistem;
    private final ObjectProperty<BigDecimal> qtyReal;
    private final ObjectProperty<Date> createdDate;
    private final ObjectProperty<Date> lastUpdatedDate;

    public TblRoomCheckHouseKeepingAttendanceDetail() {
        this.idrelation = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdatedBy = new SimpleObjectProperty<>();
        this.tblEmployeeByCreatedBy = new SimpleObjectProperty<>();
        this.tblItem = new SimpleObjectProperty<>();
        this.tblRoomCheckHouseKeepingAttendance = new SimpleObjectProperty<>();
        this.codeWorkSheet = new SimpleStringProperty();
        this.qtySistem = new SimpleObjectProperty<>();
        this.qtyReal = new SimpleObjectProperty<>();
        this.createdDate = new SimpleObjectProperty<>();
        this.lastUpdatedDate = new SimpleObjectProperty<>();

    }

    public TblRoomCheckHouseKeepingAttendanceDetail(long idrelation) {
        this();
        idrelationProperty().set(idrelation);
    }

    public TblRoomCheckHouseKeepingAttendanceDetail(long idrelation, RefRecordStatus refRecordStatus, TblEmployee tblEmployeeByLastUpdatedBy, TblEmployee tblEmployeeByCreatedBy, TblItem tblItem, TblRoomCheckHouseKeepingAttendance tblRoomCheckHouseKeepingAttendance, String codeWorkSheet, BigDecimal qtySistem, BigDecimal qtyReal, Date createdDate, Date lastUpdatedDate) {
        this();
        idrelationProperty().set(idrelation);
        refRecordStatusProperty().set(refRecordStatus);
        tblEmployeeByLastUpdatedByProperty().set(tblEmployeeByLastUpdatedBy);
        tblEmployeeByCreatedByProperty().set(tblEmployeeByCreatedBy);
        tblItemProperty().set(tblItem);
        tblRoomCheckHouseKeepingAttendanceProperty().set(tblRoomCheckHouseKeepingAttendance);
        codeWorkSheetProperty().set(codeWorkSheet);
        qtySistemProperty().set(qtySistem);
        qtyRealProperty().set(qtyReal);
        createdDateProperty().set(createdDate);
        lastUpdatedDateProperty().set(lastUpdatedDate);

    }

    public TblRoomCheckHouseKeepingAttendanceDetail(TblRoomCheckHouseKeepingAttendanceDetail tblRoomCheckHouseKeepingAttendanceDetail) {
        this();
        idrelationProperty().set(tblRoomCheckHouseKeepingAttendanceDetail.getIdrelation());
        refRecordStatusProperty().set(tblRoomCheckHouseKeepingAttendanceDetail.getRefRecordStatus());
        tblEmployeeByLastUpdatedByProperty().set(tblRoomCheckHouseKeepingAttendanceDetail.getTblEmployeeByLastUpdatedBy());
        tblEmployeeByCreatedByProperty().set(tblRoomCheckHouseKeepingAttendanceDetail.getTblEmployeeByCreatedBy());
        tblItemProperty().set(tblRoomCheckHouseKeepingAttendanceDetail.getTblItem());
        tblRoomCheckHouseKeepingAttendanceProperty().set(tblRoomCheckHouseKeepingAttendanceDetail.getTblRoomCheckHouseKeepingAttendance());
        codeWorkSheetProperty().set(tblRoomCheckHouseKeepingAttendanceDetail.getCodeWorkSheet());
        qtySistemProperty().set(tblRoomCheckHouseKeepingAttendanceDetail.getQtySistem());
        qtyRealProperty().set(tblRoomCheckHouseKeepingAttendanceDetail.getQtyReal());
        createdDateProperty().set(tblRoomCheckHouseKeepingAttendanceDetail.getCreatedDate());
        lastUpdatedDateProperty().set(tblRoomCheckHouseKeepingAttendanceDetail.getLastUpdatedDate());

    }

    public final LongProperty idrelationProperty() {
        return this.idrelation;
    }

    public long getIdrelation() {
        return idrelationProperty().get();
    }

    public void setIdrelation(long idrelation) {
        idrelationProperty().set(idrelation);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdatedByProperty() {
        return this.tblEmployeeByLastUpdatedBy;
    }

    public TblEmployee getTblEmployeeByLastUpdatedBy() {
        return tblEmployeeByLastUpdatedByProperty().get();
    }

    public void setTblEmployeeByLastUpdatedBy(TblEmployee tblEmployeeByLastUpdatedBy) {
        tblEmployeeByLastUpdatedByProperty().set(tblEmployeeByLastUpdatedBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreatedByProperty() {
        return this.tblEmployeeByCreatedBy;
    }

    public TblEmployee getTblEmployeeByCreatedBy() {
        return tblEmployeeByCreatedByProperty().get();
    }

    public void setTblEmployeeByCreatedBy(TblEmployee tblEmployeeByCreatedBy) {
        tblEmployeeByCreatedByProperty().set(tblEmployeeByCreatedBy);
    }

    public final ObjectProperty<TblItem> tblItemProperty() {
        return this.tblItem;
    }

    public TblItem getTblItem() {
        return tblItemProperty().get();
    }

    public void setTblItem(TblItem tblItem) {
        tblItemProperty().set(tblItem);
    }

    public final ObjectProperty<TblRoomCheckHouseKeepingAttendance> tblRoomCheckHouseKeepingAttendanceProperty() {
        return this.tblRoomCheckHouseKeepingAttendance;
    }

    public TblRoomCheckHouseKeepingAttendance getTblRoomCheckHouseKeepingAttendance() {
        return tblRoomCheckHouseKeepingAttendanceProperty().get();
    }

    public void setTblRoomCheckHouseKeepingAttendance(TblRoomCheckHouseKeepingAttendance tblRoomCheckHouseKeepingAttendance) {
        tblRoomCheckHouseKeepingAttendanceProperty().set(tblRoomCheckHouseKeepingAttendance);
    }

    public final StringProperty codeWorkSheetProperty() {
        return this.codeWorkSheet;
    }

    public String getCodeWorkSheet() {
        return codeWorkSheetProperty().get();
    }

    public void setCodeWorkSheet(String codeWorkSheet) {
        codeWorkSheetProperty().set(codeWorkSheet);
    }

    public final ObjectProperty<BigDecimal> qtySistemProperty() {
        return this.qtySistem;
    }

    public BigDecimal getQtySistem() {
        return qtySistemProperty().get();
    }

    public void setQtySistem(BigDecimal qtySistem) {
        qtySistemProperty().set(qtySistem);
    }

    public final ObjectProperty<BigDecimal> qtyRealProperty() {
        return this.qtyReal;
    }

    public BigDecimal getQtyReal() {
        return qtyRealProperty().get();
    }

    public void setQtyReal(BigDecimal qtyReal) {
        qtyRealProperty().set(qtyReal);
    }

    public final ObjectProperty<Date> createdDateProperty() {
        return this.createdDate;
    }

    public Date getCreatedDate() {
        return createdDateProperty().get();
    }

    public void setCreatedDate(Date createdDate) {
        createdDateProperty().set(createdDate);
    }

    public final ObjectProperty<Date> lastUpdatedDateProperty() {
        return this.lastUpdatedDate;
    }

    public Date getLastUpdatedDate() {
        return lastUpdatedDateProperty().get();
    }

    public void setLastUpdatedDate(Date lastUpdatedDate) {
        lastUpdatedDateProperty().set(lastUpdatedDate);
    }

}
