package hotelfx.persistence.model;
// Generated Oct 26, 2018 11:47:15 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblReservationPaymentWithBankCard generated by hbm2java
 */
public class TblReservationPaymentWithBankCard implements java.io.Serializable {

    private final LongProperty iddetil;
    private final ObjectProperty<RefEdctransactionStatus> refEdctransactionStatus;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblBank> tblBank;
    private final ObjectProperty<TblBankAccount> tblBankAccount;
    private final ObjectProperty<TblBankEdc> tblBankEdc;
    private final ObjectProperty<TblBankEdcBankNetworkCard> tblBankEdcBankNetworkCard;
    private final ObjectProperty<TblBankEventCard> tblBankEventCard;
    private final ObjectProperty<TblBankNetworkCard> tblBankNetworkCard;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblReservationPayment> tblReservationPayment;
    private final StringProperty bankCardHolder;
    private final StringProperty bankCardNumber;
    private final ObjectProperty<Date> bankCardExprDate;
    private final StringProperty approvalCode;
    private final ObjectProperty<BigDecimal> paymentDiscount;
    private final ObjectProperty<BigDecimal> paymentCharge;
    private final StringProperty bankCardNote;
    private final ObjectProperty<Date> settleDate;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    public TblReservationPaymentWithBankCard() {
        this.iddetil = new SimpleLongProperty();
        this.refEdctransactionStatus = new SimpleObjectProperty<>();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblBank = new SimpleObjectProperty<>();
        this.tblBankAccount = new SimpleObjectProperty<>();
        this.tblBankEdc = new SimpleObjectProperty<>();
        this.tblBankEdcBankNetworkCard = new SimpleObjectProperty<>();
        this.tblBankEventCard = new SimpleObjectProperty<>();
        this.tblBankNetworkCard = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblReservationPayment = new SimpleObjectProperty<>();
        this.bankCardHolder = new SimpleStringProperty();
        this.bankCardNumber = new SimpleStringProperty();
        this.bankCardExprDate = new SimpleObjectProperty<>();
        this.approvalCode = new SimpleStringProperty();
        this.paymentDiscount = new SimpleObjectProperty<>();
        this.paymentCharge = new SimpleObjectProperty<>();
        this.bankCardNote = new SimpleStringProperty();
        this.settleDate = new SimpleObjectProperty<>();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

    }

    public TblReservationPaymentWithBankCard(long iddetil) {
        this();
        iddetilProperty().set(iddetil);
    }

    public TblReservationPaymentWithBankCard(long iddetil, RefEdctransactionStatus refEdctransactionStatus, RefRecordStatus refRecordStatus, TblBank tblBank, TblBankAccount tblBankAccount, TblBankEdc tblBankEdc, TblBankEdcBankNetworkCard tblBankEdcBankNetworkCard, TblBankEventCard tblBankEventCard, TblBankNetworkCard tblBankNetworkCard, TblEmployee tblEmployeeByLastUpdateBy, TblEmployee tblEmployeeByCreateBy, TblReservationPayment tblReservationPayment, String bankCardHolder, String bankCardNumber, Date bankCardExprDate, String approvalCode, BigDecimal paymentDiscount, BigDecimal paymentCharge, String bankCardNote, Date settleDate, Date createDate, Date lastUpdateDate) {
        this();
        iddetilProperty().set(iddetil);
        refEdctransactionStatusProperty().set(refEdctransactionStatus);
        refRecordStatusProperty().set(refRecordStatus);
        tblBankProperty().set(tblBank);
        tblBankAccountProperty().set(tblBankAccount);
        tblBankEdcProperty().set(tblBankEdc);
        tblBankEdcBankNetworkCardProperty().set(tblBankEdcBankNetworkCard);
        tblBankEventCardProperty().set(tblBankEventCard);
        tblBankNetworkCardProperty().set(tblBankNetworkCard);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblReservationPaymentProperty().set(tblReservationPayment);
        bankCardHolderProperty().set(bankCardHolder);
        bankCardNumberProperty().set(bankCardNumber);
        bankCardExprDateProperty().set(bankCardExprDate);
        approvalCodeProperty().set(approvalCode);
        paymentDiscountProperty().set(paymentDiscount);
        paymentChargeProperty().set(paymentCharge);
        bankCardNoteProperty().set(bankCardNote);
        settleDateProperty().set(settleDate);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

    }

    public TblReservationPaymentWithBankCard(TblReservationPaymentWithBankCard tblReservationPaymentWithBankCard) {
        this();
        iddetilProperty().set(tblReservationPaymentWithBankCard.getIddetil());
        refEdctransactionStatusProperty().set(tblReservationPaymentWithBankCard.getRefEdctransactionStatus());
        refRecordStatusProperty().set(tblReservationPaymentWithBankCard.getRefRecordStatus());
        tblBankProperty().set(tblReservationPaymentWithBankCard.getTblBank());
        tblBankAccountProperty().set(tblReservationPaymentWithBankCard.getTblBankAccount());
        tblBankEdcProperty().set(tblReservationPaymentWithBankCard.getTblBankEdc());
        tblBankEdcBankNetworkCardProperty().set(tblReservationPaymentWithBankCard.getTblBankEdcBankNetworkCard());
        tblBankEventCardProperty().set(tblReservationPaymentWithBankCard.getTblBankEventCard());
        tblBankNetworkCardProperty().set(tblReservationPaymentWithBankCard.getTblBankNetworkCard());
        tblEmployeeByLastUpdateByProperty().set(tblReservationPaymentWithBankCard.getTblEmployeeByLastUpdateBy());
        tblEmployeeByCreateByProperty().set(tblReservationPaymentWithBankCard.getTblEmployeeByCreateBy());
        tblReservationPaymentProperty().set(tblReservationPaymentWithBankCard.getTblReservationPayment());
        bankCardHolderProperty().set(tblReservationPaymentWithBankCard.getBankCardHolder());
        bankCardNumberProperty().set(tblReservationPaymentWithBankCard.getBankCardNumber());
        bankCardExprDateProperty().set(tblReservationPaymentWithBankCard.getBankCardExprDate());
        approvalCodeProperty().set(tblReservationPaymentWithBankCard.getApprovalCode());
        paymentDiscountProperty().set(tblReservationPaymentWithBankCard.getPaymentDiscount());
        paymentChargeProperty().set(tblReservationPaymentWithBankCard.getPaymentCharge());
        bankCardNoteProperty().set(tblReservationPaymentWithBankCard.getBankCardNote());
        settleDateProperty().set(tblReservationPaymentWithBankCard.getSettleDate());
        createDateProperty().set(tblReservationPaymentWithBankCard.getCreateDate());
        lastUpdateDateProperty().set(tblReservationPaymentWithBankCard.getLastUpdateDate());

    }

    public final LongProperty iddetilProperty() {
        return this.iddetil;
    }

    public long getIddetil() {
        return iddetilProperty().get();
    }

    public void setIddetil(long iddetil) {
        iddetilProperty().set(iddetil);
    }

    public final ObjectProperty<RefEdctransactionStatus> refEdctransactionStatusProperty() {
        return this.refEdctransactionStatus;
    }

    public RefEdctransactionStatus getRefEdctransactionStatus() {
        return refEdctransactionStatusProperty().get();
    }

    public void setRefEdctransactionStatus(RefEdctransactionStatus refEdctransactionStatus) {
        refEdctransactionStatusProperty().set(refEdctransactionStatus);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblBank> tblBankProperty() {
        return this.tblBank;
    }

    public TblBank getTblBank() {
        return tblBankProperty().get();
    }

    public void setTblBank(TblBank tblBank) {
        tblBankProperty().set(tblBank);
    }

    public final ObjectProperty<TblBankAccount> tblBankAccountProperty() {
        return this.tblBankAccount;
    }

    public TblBankAccount getTblBankAccount() {
        return tblBankAccountProperty().get();
    }

    public void setTblBankAccount(TblBankAccount tblBankAccount) {
        tblBankAccountProperty().set(tblBankAccount);
    }

    public final ObjectProperty<TblBankEdc> tblBankEdcProperty() {
        return this.tblBankEdc;
    }

    public TblBankEdc getTblBankEdc() {
        return tblBankEdcProperty().get();
    }

    public void setTblBankEdc(TblBankEdc tblBankEdc) {
        tblBankEdcProperty().set(tblBankEdc);
    }

    public final ObjectProperty<TblBankEdcBankNetworkCard> tblBankEdcBankNetworkCardProperty() {
        return this.tblBankEdcBankNetworkCard;
    }

    public TblBankEdcBankNetworkCard getTblBankEdcBankNetworkCard() {
        return tblBankEdcBankNetworkCardProperty().get();
    }

    public void setTblBankEdcBankNetworkCard(TblBankEdcBankNetworkCard tblBankEdcBankNetworkCard) {
        tblBankEdcBankNetworkCardProperty().set(tblBankEdcBankNetworkCard);
    }

    public final ObjectProperty<TblBankEventCard> tblBankEventCardProperty() {
        return this.tblBankEventCard;
    }

    public TblBankEventCard getTblBankEventCard() {
        return tblBankEventCardProperty().get();
    }

    public void setTblBankEventCard(TblBankEventCard tblBankEventCard) {
        tblBankEventCardProperty().set(tblBankEventCard);
    }

    public final ObjectProperty<TblBankNetworkCard> tblBankNetworkCardProperty() {
        return this.tblBankNetworkCard;
    }

    public TblBankNetworkCard getTblBankNetworkCard() {
        return tblBankNetworkCardProperty().get();
    }

    public void setTblBankNetworkCard(TblBankNetworkCard tblBankNetworkCard) {
        tblBankNetworkCardProperty().set(tblBankNetworkCard);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblReservationPayment> tblReservationPaymentProperty() {
        return this.tblReservationPayment;
    }

    public TblReservationPayment getTblReservationPayment() {
        return tblReservationPaymentProperty().get();
    }

    public void setTblReservationPayment(TblReservationPayment tblReservationPayment) {
        tblReservationPaymentProperty().set(tblReservationPayment);
    }

    public final StringProperty bankCardHolderProperty() {
        return this.bankCardHolder;
    }

    public String getBankCardHolder() {
        return bankCardHolderProperty().get();
    }

    public void setBankCardHolder(String bankCardHolder) {
        bankCardHolderProperty().set(bankCardHolder);
    }

    public final StringProperty bankCardNumberProperty() {
        return this.bankCardNumber;
    }

    public String getBankCardNumber() {
        return bankCardNumberProperty().get();
    }

    public void setBankCardNumber(String bankCardNumber) {
        bankCardNumberProperty().set(bankCardNumber);
    }

    public final ObjectProperty<Date> bankCardExprDateProperty() {
        return this.bankCardExprDate;
    }

    public Date getBankCardExprDate() {
        return bankCardExprDateProperty().get();
    }

    public void setBankCardExprDate(Date bankCardExprDate) {
        bankCardExprDateProperty().set(bankCardExprDate);
    }

    public final StringProperty approvalCodeProperty() {
        return this.approvalCode;
    }

    public String getApprovalCode() {
        return approvalCodeProperty().get();
    }

    public void setApprovalCode(String approvalCode) {
        approvalCodeProperty().set(approvalCode);
    }

    public final ObjectProperty<BigDecimal> paymentDiscountProperty() {
        return this.paymentDiscount;
    }

    public BigDecimal getPaymentDiscount() {
        return paymentDiscountProperty().get();
    }

    public void setPaymentDiscount(BigDecimal paymentDiscount) {
        paymentDiscountProperty().set(paymentDiscount);
    }

    public final ObjectProperty<BigDecimal> paymentChargeProperty() {
        return this.paymentCharge;
    }

    public BigDecimal getPaymentCharge() {
        return paymentChargeProperty().get();
    }

    public void setPaymentCharge(BigDecimal paymentCharge) {
        paymentChargeProperty().set(paymentCharge);
    }

    public final StringProperty bankCardNoteProperty() {
        return this.bankCardNote;
    }

    public String getBankCardNote() {
        return bankCardNoteProperty().get();
    }

    public void setBankCardNote(String bankCardNote) {
        bankCardNoteProperty().set(bankCardNote);
    }

    public final ObjectProperty<Date> settleDateProperty() {
        return this.settleDate;
    }

    public Date getSettleDate() {
        return settleDateProperty().get();
    }

    public void setSettleDate(Date settleDate) {
        settleDateProperty().set(settleDate);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

}
