package hotelfx.persistence.model;
// Generated Nov 24, 2017 1:37:37 PM by Hibernate Tools 4.3.1

import java.util.Date;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblReservationPaymentWithCekGiro generated by hbm2java
 */
public class TblReservationPaymentWithCekGiro implements java.io.Serializable {

    private final LongProperty iddetail;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblBank> tblBank;
    private final ObjectProperty<TblBankAccount> tblBankAccountByReceiverBankAccount;
    private final ObjectProperty<TblBankAccount> tblBankAccountBySenderBankAccount;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblReservationPayment> tblReservationPayment;
    private final StringProperty codeCekGiro;
    private final ObjectProperty<Date> issueDateTime;
    private final ObjectProperty<Date> validUntilDateTime;
    private final StringProperty senderName;
    private final StringProperty receiverName;
    private final StringProperty cekGiroNote;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    public TblReservationPaymentWithCekGiro() {
        this.iddetail = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblBank = new SimpleObjectProperty<>();
        this.tblBankAccountByReceiverBankAccount = new SimpleObjectProperty<>();
        this.tblBankAccountBySenderBankAccount = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblReservationPayment = new SimpleObjectProperty<>();
        this.codeCekGiro = new SimpleStringProperty();
        this.issueDateTime = new SimpleObjectProperty<>();
        this.validUntilDateTime = new SimpleObjectProperty<>();
        this.senderName = new SimpleStringProperty();
        this.receiverName = new SimpleStringProperty();
        this.cekGiroNote = new SimpleStringProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

    }

    public TblReservationPaymentWithCekGiro(long iddetail) {
        this();
        iddetailProperty().set(iddetail);
    }

    public TblReservationPaymentWithCekGiro(long iddetail, RefRecordStatus refRecordStatus, TblBank tblBank, TblBankAccount tblBankAccountByReceiverBankAccount, TblBankAccount tblBankAccountBySenderBankAccount, TblEmployee tblEmployeeByLastUpdateBy, TblEmployee tblEmployeeByCreateBy, TblReservationPayment tblReservationPayment, String codeCekGiro, Date issueDateTime, Date validUntilDateTime, String senderName, String receiverName, String cekGiroNote, Date createDate, Date lastUpdateDate) {
        this();
        iddetailProperty().set(iddetail);
        refRecordStatusProperty().set(refRecordStatus);
        tblBankProperty().set(tblBank);
        tblBankAccountByReceiverBankAccountProperty().set(tblBankAccountByReceiverBankAccount);
        tblBankAccountBySenderBankAccountProperty().set(tblBankAccountBySenderBankAccount);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblReservationPaymentProperty().set(tblReservationPayment);
        codeCekGiroProperty().set(codeCekGiro);
        issueDateTimeProperty().set(issueDateTime);
        validUntilDateTimeProperty().set(validUntilDateTime);
        senderNameProperty().set(senderName);
        receiverNameProperty().set(receiverName);
        cekGiroNoteProperty().set(cekGiroNote);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

    }

    public TblReservationPaymentWithCekGiro(TblReservationPaymentWithCekGiro tblReservationPaymentWithCekGiro) {
        this();
        iddetailProperty().set(tblReservationPaymentWithCekGiro.getIddetail());
        refRecordStatusProperty().set(tblReservationPaymentWithCekGiro.getRefRecordStatus());
        tblBankProperty().set(tblReservationPaymentWithCekGiro.getTblBank());
        tblBankAccountByReceiverBankAccountProperty().set(tblReservationPaymentWithCekGiro.getTblBankAccountByReceiverBankAccount());
        tblBankAccountBySenderBankAccountProperty().set(tblReservationPaymentWithCekGiro.getTblBankAccountBySenderBankAccount());
        tblEmployeeByLastUpdateByProperty().set(tblReservationPaymentWithCekGiro.getTblEmployeeByLastUpdateBy());
        tblEmployeeByCreateByProperty().set(tblReservationPaymentWithCekGiro.getTblEmployeeByCreateBy());
        tblReservationPaymentProperty().set(tblReservationPaymentWithCekGiro.getTblReservationPayment());
        codeCekGiroProperty().set(tblReservationPaymentWithCekGiro.getCodeCekGiro());
        issueDateTimeProperty().set(tblReservationPaymentWithCekGiro.getIssueDateTime());
        validUntilDateTimeProperty().set(tblReservationPaymentWithCekGiro.getValidUntilDateTime());
        senderNameProperty().set(tblReservationPaymentWithCekGiro.getSenderName());
        receiverNameProperty().set(tblReservationPaymentWithCekGiro.getReceiverName());
        cekGiroNoteProperty().set(tblReservationPaymentWithCekGiro.getCekGiroNote());
        createDateProperty().set(tblReservationPaymentWithCekGiro.getCreateDate());
        lastUpdateDateProperty().set(tblReservationPaymentWithCekGiro.getLastUpdateDate());

    }

    public final LongProperty iddetailProperty() {
        return this.iddetail;
    }

    public long getIddetail() {
        return iddetailProperty().get();
    }

    public void setIddetail(long iddetail) {
        iddetailProperty().set(iddetail);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblBank> tblBankProperty() {
        return this.tblBank;
    }

    public TblBank getTblBank() {
        return tblBankProperty().get();
    }

    public void setTblBank(TblBank tblBank) {
        tblBankProperty().set(tblBank);
    }

    public final ObjectProperty<TblBankAccount> tblBankAccountByReceiverBankAccountProperty() {
        return this.tblBankAccountByReceiverBankAccount;
    }

    public TblBankAccount getTblBankAccountByReceiverBankAccount() {
        return tblBankAccountByReceiverBankAccountProperty().get();
    }

    public void setTblBankAccountByReceiverBankAccount(TblBankAccount tblBankAccountByReceiverBankAccount) {
        tblBankAccountByReceiverBankAccountProperty().set(tblBankAccountByReceiverBankAccount);
    }

    public final ObjectProperty<TblBankAccount> tblBankAccountBySenderBankAccountProperty() {
        return this.tblBankAccountBySenderBankAccount;
    }

    public TblBankAccount getTblBankAccountBySenderBankAccount() {
        return tblBankAccountBySenderBankAccountProperty().get();
    }

    public void setTblBankAccountBySenderBankAccount(TblBankAccount tblBankAccountBySenderBankAccount) {
        tblBankAccountBySenderBankAccountProperty().set(tblBankAccountBySenderBankAccount);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblReservationPayment> tblReservationPaymentProperty() {
        return this.tblReservationPayment;
    }

    public TblReservationPayment getTblReservationPayment() {
        return tblReservationPaymentProperty().get();
    }

    public void setTblReservationPayment(TblReservationPayment tblReservationPayment) {
        tblReservationPaymentProperty().set(tblReservationPayment);
    }

    public final StringProperty codeCekGiroProperty() {
        return this.codeCekGiro;
    }

    public String getCodeCekGiro() {
        return codeCekGiroProperty().get();
    }

    public void setCodeCekGiro(String codeCekGiro) {
        codeCekGiroProperty().set(codeCekGiro);
    }

    public final ObjectProperty<Date> issueDateTimeProperty() {
        return this.issueDateTime;
    }

    public Date getIssueDateTime() {
        return issueDateTimeProperty().get();
    }

    public void setIssueDateTime(Date issueDateTime) {
        issueDateTimeProperty().set(issueDateTime);
    }

    public final ObjectProperty<Date> validUntilDateTimeProperty() {
        return this.validUntilDateTime;
    }

    public Date getValidUntilDateTime() {
        return validUntilDateTimeProperty().get();
    }

    public void setValidUntilDateTime(Date validUntilDateTime) {
        validUntilDateTimeProperty().set(validUntilDateTime);
    }

    public final StringProperty senderNameProperty() {
        return this.senderName;
    }

    public String getSenderName() {
        return senderNameProperty().get();
    }

    public void setSenderName(String senderName) {
        senderNameProperty().set(senderName);
    }

    public final StringProperty receiverNameProperty() {
        return this.receiverName;
    }

    public String getReceiverName() {
        return receiverNameProperty().get();
    }

    public void setReceiverName(String receiverName) {
        receiverNameProperty().set(receiverName);
    }

    public final StringProperty cekGiroNoteProperty() {
        return this.cekGiroNote;
    }

    public String getCekGiroNote() {
        return cekGiroNoteProperty().get();
    }

    public void setCekGiroNote(String cekGiroNote) {
        cekGiroNoteProperty().set(cekGiroNote);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

}
