package hotelfx.persistence.model;
// Generated Mar 23, 2018 10:25:20 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblRoomStatusChangeHistory generated by hbm2java
 */
public class TblRoomStatusChangeHistory implements java.io.Serializable {

    private final LongProperty idchangeRoomStatus;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<RefRoomStatus> refRoomStatusByRoomStatusOld;
    private final ObjectProperty<RefRoomStatus> refRoomStatusByRoomStatusNew;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByIdemployee;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblRoom> tblRoom;
    private final ObjectProperty<TblRoomStatusDetail> tblRoomStatusDetail;
    private final ObjectProperty<Date> changeRoomStatusDate;
    private final StringProperty changeRoomStatusNote;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    private Set tblRoomChecks;

    public TblRoomStatusChangeHistory() {
        this.idchangeRoomStatus = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.refRoomStatusByRoomStatusOld = new SimpleObjectProperty<>();
        this.refRoomStatusByRoomStatusNew = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByIdemployee = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblRoom = new SimpleObjectProperty<>();
        this.tblRoomStatusDetail = new SimpleObjectProperty<>();
        this.changeRoomStatusDate = new SimpleObjectProperty<>();
        this.changeRoomStatusNote = new SimpleStringProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

        this.tblRoomChecks = new HashSet(0);
    }

    public TblRoomStatusChangeHistory(long idchangeRoomStatus) {
        this();
        idchangeRoomStatusProperty().set(idchangeRoomStatus);
    }

    public TblRoomStatusChangeHistory(long idchangeRoomStatus, RefRecordStatus refRecordStatus, RefRoomStatus refRoomStatusByRoomStatusOld, RefRoomStatus refRoomStatusByRoomStatusNew, TblEmployee tblEmployeeByLastUpdateBy, TblEmployee tblEmployeeByIdemployee, TblEmployee tblEmployeeByCreateBy, TblRoom tblRoom, TblRoomStatusDetail tblRoomStatusDetail, Date changeRoomStatusDate, String changeRoomStatusNote, Date createDate, Date lastUpdateDate, Set tblRoomChecks) {
        this();
        idchangeRoomStatusProperty().set(idchangeRoomStatus);
        refRecordStatusProperty().set(refRecordStatus);
        refRoomStatusByRoomStatusOldProperty().set(refRoomStatusByRoomStatusOld);
        refRoomStatusByRoomStatusNewProperty().set(refRoomStatusByRoomStatusNew);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblEmployeeByIdemployeeProperty().set(tblEmployeeByIdemployee);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblRoomProperty().set(tblRoom);
        tblRoomStatusDetailProperty().set(tblRoomStatusDetail);
        changeRoomStatusDateProperty().set(changeRoomStatusDate);
        changeRoomStatusNoteProperty().set(changeRoomStatusNote);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

        this.tblRoomChecks = tblRoomChecks;
    }

    public TblRoomStatusChangeHistory(TblRoomStatusChangeHistory tblRoomStatusChangeHistory) {
        this();
        idchangeRoomStatusProperty().set(tblRoomStatusChangeHistory.getIdchangeRoomStatus());
        refRecordStatusProperty().set(tblRoomStatusChangeHistory.getRefRecordStatus());
        refRoomStatusByRoomStatusOldProperty().set(tblRoomStatusChangeHistory.getRefRoomStatusByRoomStatusOld());
        refRoomStatusByRoomStatusNewProperty().set(tblRoomStatusChangeHistory.getRefRoomStatusByRoomStatusNew());
        tblEmployeeByLastUpdateByProperty().set(tblRoomStatusChangeHistory.getTblEmployeeByLastUpdateBy());
        tblEmployeeByIdemployeeProperty().set(tblRoomStatusChangeHistory.getTblEmployeeByIdemployee());
        tblEmployeeByCreateByProperty().set(tblRoomStatusChangeHistory.getTblEmployeeByCreateBy());
        tblRoomProperty().set(tblRoomStatusChangeHistory.getTblRoom());
        tblRoomStatusDetailProperty().set(tblRoomStatusChangeHistory.getTblRoomStatusDetail());
        changeRoomStatusDateProperty().set(tblRoomStatusChangeHistory.getChangeRoomStatusDate());
        changeRoomStatusNoteProperty().set(tblRoomStatusChangeHistory.getChangeRoomStatusNote());
        createDateProperty().set(tblRoomStatusChangeHistory.getCreateDate());
        lastUpdateDateProperty().set(tblRoomStatusChangeHistory.getLastUpdateDate());

        this.tblRoomChecks = tblRoomStatusChangeHistory.getTblRoomChecks();
    }

    public final LongProperty idchangeRoomStatusProperty() {
        return this.idchangeRoomStatus;
    }

    public long getIdchangeRoomStatus() {
        return idchangeRoomStatusProperty().get();
    }

    public void setIdchangeRoomStatus(long idchangeRoomStatus) {
        idchangeRoomStatusProperty().set(idchangeRoomStatus);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<RefRoomStatus> refRoomStatusByRoomStatusOldProperty() {
        return this.refRoomStatusByRoomStatusOld;
    }

    public RefRoomStatus getRefRoomStatusByRoomStatusOld() {
        return refRoomStatusByRoomStatusOldProperty().get();
    }

    public void setRefRoomStatusByRoomStatusOld(RefRoomStatus refRoomStatusByRoomStatusOld) {
        refRoomStatusByRoomStatusOldProperty().set(refRoomStatusByRoomStatusOld);
    }

    public final ObjectProperty<RefRoomStatus> refRoomStatusByRoomStatusNewProperty() {
        return this.refRoomStatusByRoomStatusNew;
    }

    public RefRoomStatus getRefRoomStatusByRoomStatusNew() {
        return refRoomStatusByRoomStatusNewProperty().get();
    }

    public void setRefRoomStatusByRoomStatusNew(RefRoomStatus refRoomStatusByRoomStatusNew) {
        refRoomStatusByRoomStatusNewProperty().set(refRoomStatusByRoomStatusNew);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByIdemployeeProperty() {
        return this.tblEmployeeByIdemployee;
    }

    public TblEmployee getTblEmployeeByIdemployee() {
        return tblEmployeeByIdemployeeProperty().get();
    }

    public void setTblEmployeeByIdemployee(TblEmployee tblEmployeeByIdemployee) {
        tblEmployeeByIdemployeeProperty().set(tblEmployeeByIdemployee);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblRoom> tblRoomProperty() {
        return this.tblRoom;
    }

    public TblRoom getTblRoom() {
        return tblRoomProperty().get();
    }

    public void setTblRoom(TblRoom tblRoom) {
        tblRoomProperty().set(tblRoom);
    }

    public final ObjectProperty<TblRoomStatusDetail> tblRoomStatusDetailProperty() {
        return this.tblRoomStatusDetail;
    }

    public TblRoomStatusDetail getTblRoomStatusDetail() {
        return tblRoomStatusDetailProperty().get();
    }

    public void setTblRoomStatusDetail(TblRoomStatusDetail tblRoomStatusDetail) {
        tblRoomStatusDetailProperty().set(tblRoomStatusDetail);
    }

    public final ObjectProperty<Date> changeRoomStatusDateProperty() {
        return this.changeRoomStatusDate;
    }

    public Date getChangeRoomStatusDate() {
        return changeRoomStatusDateProperty().get();
    }

    public void setChangeRoomStatusDate(Date changeRoomStatusDate) {
        changeRoomStatusDateProperty().set(changeRoomStatusDate);
    }

    public final StringProperty changeRoomStatusNoteProperty() {
        return this.changeRoomStatusNote;
    }

    public String getChangeRoomStatusNote() {
        return changeRoomStatusNoteProperty().get();
    }

    public void setChangeRoomStatusNote(String changeRoomStatusNote) {
        changeRoomStatusNoteProperty().set(changeRoomStatusNote);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

    public Set getTblRoomChecks() {
        return this.tblRoomChecks;
    }

    public void setTblRoomChecks(Set tblRoomChecks) {
        this.tblRoomChecks = tblRoomChecks;
    }

}
