package hotelfx.persistence.model;
// Generated Feb 2, 2018 1:25:58 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblRoomStatusDetail generated by hbm2java
 */
public class TblRoomStatusDetail implements java.io.Serializable {

    private final LongProperty idroomStatusDetail;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblRoom> tblRoom;
    private final ObjectProperty<Date> roomStatusDetailDate;
    private final StringProperty roomStatusDetail;
    private final StringProperty roomStatusDetailNote;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    private Set tblRoomStatusChangeHistories;

    public TblRoomStatusDetail() {
        this.idroomStatusDetail = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblRoom = new SimpleObjectProperty<>();
        this.roomStatusDetailDate = new SimpleObjectProperty<>();
        this.roomStatusDetail = new SimpleStringProperty();
        this.roomStatusDetailNote = new SimpleStringProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

        this.tblRoomStatusChangeHistories = new HashSet(0);
    }

    public TblRoomStatusDetail(long idroomStatusDetail) {
        this();
        idroomStatusDetailProperty().set(idroomStatusDetail);
    }

    public TblRoomStatusDetail(long idroomStatusDetail, RefRecordStatus refRecordStatus, TblEmployee tblEmployeeByCreateBy, TblEmployee tblEmployeeByLastUpdateBy, TblRoom tblRoom, Date roomStatusDetailDate, String roomStatusDetail, String roomStatusDetailNote, Date createDate, Date lastUpdateDate, Set tblRoomStatusChangeHistories) {
        this();
        idroomStatusDetailProperty().set(idroomStatusDetail);
        refRecordStatusProperty().set(refRecordStatus);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblRoomProperty().set(tblRoom);
        roomStatusDetailDateProperty().set(roomStatusDetailDate);
        roomStatusDetailProperty().set(roomStatusDetail);
        roomStatusDetailNoteProperty().set(roomStatusDetailNote);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

        this.tblRoomStatusChangeHistories = tblRoomStatusChangeHistories;
    }

    public TblRoomStatusDetail(TblRoomStatusDetail tblRoomStatusDetail) {
        this();
        idroomStatusDetailProperty().set(tblRoomStatusDetail.getIdroomStatusDetail());
        refRecordStatusProperty().set(tblRoomStatusDetail.getRefRecordStatus());
        tblEmployeeByCreateByProperty().set(tblRoomStatusDetail.getTblEmployeeByCreateBy());
        tblEmployeeByLastUpdateByProperty().set(tblRoomStatusDetail.getTblEmployeeByLastUpdateBy());
        tblRoomProperty().set(tblRoomStatusDetail.getTblRoom());
        roomStatusDetailDateProperty().set(tblRoomStatusDetail.getRoomStatusDetailDate());
        roomStatusDetailProperty().set(tblRoomStatusDetail.getRoomStatusDetail());
        roomStatusDetailNoteProperty().set(tblRoomStatusDetail.getRoomStatusDetailNote());
        createDateProperty().set(tblRoomStatusDetail.getCreateDate());
        lastUpdateDateProperty().set(tblRoomStatusDetail.getLastUpdateDate());

        this.tblRoomStatusChangeHistories = tblRoomStatusDetail.getTblRoomStatusChangeHistories();
    }

    public final LongProperty idroomStatusDetailProperty() {
        return this.idroomStatusDetail;
    }

    public long getIdroomStatusDetail() {
        return idroomStatusDetailProperty().get();
    }

    public void setIdroomStatusDetail(long idroomStatusDetail) {
        idroomStatusDetailProperty().set(idroomStatusDetail);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblRoom> tblRoomProperty() {
        return this.tblRoom;
    }

    public TblRoom getTblRoom() {
        return tblRoomProperty().get();
    }

    public void setTblRoom(TblRoom tblRoom) {
        tblRoomProperty().set(tblRoom);
    }

    public final ObjectProperty<Date> roomStatusDetailDateProperty() {
        return this.roomStatusDetailDate;
    }

    public Date getRoomStatusDetailDate() {
        return roomStatusDetailDateProperty().get();
    }

    public void setRoomStatusDetailDate(Date roomStatusDetailDate) {
        roomStatusDetailDateProperty().set(roomStatusDetailDate);
    }

    public final StringProperty roomStatusDetailProperty() {
        return this.roomStatusDetail;
    }

    public String getRoomStatusDetail() {
        return roomStatusDetailProperty().get();
    }

    public void setRoomStatusDetail(String roomStatusDetail) {
        roomStatusDetailProperty().set(roomStatusDetail);
    }

    public final StringProperty roomStatusDetailNoteProperty() {
        return this.roomStatusDetailNote;
    }

    public String getRoomStatusDetailNote() {
        return roomStatusDetailNoteProperty().get();
    }

    public void setRoomStatusDetailNote(String roomStatusDetailNote) {
        roomStatusDetailNoteProperty().set(roomStatusDetailNote);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

    public Set getTblRoomStatusChangeHistories() {
        return this.tblRoomStatusChangeHistories;
    }

    public void setTblRoomStatusChangeHistories(Set tblRoomStatusChangeHistories) {
        this.tblRoomStatusChangeHistories = tblRoomStatusChangeHistories;
    }

}
