package hotelfx.persistence.model;
// Generated Apr 25, 2018 3:21:41 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

import javafx.beans.property.IntegerProperty;
import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleIntegerProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;

/**
 * TblReservationRoomTypeDetailRoomService generated by hbm2java
 */
public class TblReservationRoomTypeDetailRoomService implements java.io.Serializable {

    private final LongProperty idrelation;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblReservationRoomTypeDetail> tblReservationRoomTypeDetail;
    private final ObjectProperty<TblRoomService> tblRoomService;
    private final ObjectProperty<BigDecimal> roomServiceCost;
    private final IntegerProperty peopleNumber;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    public TblReservationRoomTypeDetailRoomService() {
        this.idrelation = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblReservationRoomTypeDetail = new SimpleObjectProperty<>();
        this.tblRoomService = new SimpleObjectProperty<>();
        this.roomServiceCost = new SimpleObjectProperty<>();
        this.peopleNumber = new SimpleIntegerProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

    }

    public TblReservationRoomTypeDetailRoomService(long idrelation) {
        this();
        idrelationProperty().set(idrelation);
    }

    public TblReservationRoomTypeDetailRoomService(long idrelation, RefRecordStatus refRecordStatus, TblEmployee tblEmployeeByLastUpdateBy, TblEmployee tblEmployeeByCreateBy, TblReservationRoomTypeDetail tblReservationRoomTypeDetail, TblRoomService tblRoomService, BigDecimal roomServiceCost, Integer peopleNumber, Date createDate, Date lastUpdateDate) {
        this();
        idrelationProperty().set(idrelation);
        refRecordStatusProperty().set(refRecordStatus);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblReservationRoomTypeDetailProperty().set(tblReservationRoomTypeDetail);
        tblRoomServiceProperty().set(tblRoomService);
        roomServiceCostProperty().set(roomServiceCost);
        peopleNumberProperty().set(peopleNumber);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

    }

    public TblReservationRoomTypeDetailRoomService(TblReservationRoomTypeDetailRoomService tblReservationRoomTypeDetailRoomService) {
        this();
        idrelationProperty().set(tblReservationRoomTypeDetailRoomService.getIdrelation());
        refRecordStatusProperty().set(tblReservationRoomTypeDetailRoomService.getRefRecordStatus());
        tblEmployeeByLastUpdateByProperty().set(tblReservationRoomTypeDetailRoomService.getTblEmployeeByLastUpdateBy());
        tblEmployeeByCreateByProperty().set(tblReservationRoomTypeDetailRoomService.getTblEmployeeByCreateBy());
        tblReservationRoomTypeDetailProperty().set(tblReservationRoomTypeDetailRoomService.getTblReservationRoomTypeDetail());
        tblRoomServiceProperty().set(tblReservationRoomTypeDetailRoomService.getTblRoomService());
        roomServiceCostProperty().set(tblReservationRoomTypeDetailRoomService.getRoomServiceCost());
        peopleNumberProperty().set(tblReservationRoomTypeDetailRoomService.getPeopleNumber());
        createDateProperty().set(tblReservationRoomTypeDetailRoomService.getCreateDate());
        lastUpdateDateProperty().set(tblReservationRoomTypeDetailRoomService.getLastUpdateDate());

    }

    public final LongProperty idrelationProperty() {
        return this.idrelation;
    }

    public long getIdrelation() {
        return idrelationProperty().get();
    }

    public void setIdrelation(long idrelation) {
        idrelationProperty().set(idrelation);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblReservationRoomTypeDetail> tblReservationRoomTypeDetailProperty() {
        return this.tblReservationRoomTypeDetail;
    }

    public TblReservationRoomTypeDetail getTblReservationRoomTypeDetail() {
        return tblReservationRoomTypeDetailProperty().get();
    }

    public void setTblReservationRoomTypeDetail(TblReservationRoomTypeDetail tblReservationRoomTypeDetail) {
        tblReservationRoomTypeDetailProperty().set(tblReservationRoomTypeDetail);
    }

    public final ObjectProperty<TblRoomService> tblRoomServiceProperty() {
        return this.tblRoomService;
    }

    public TblRoomService getTblRoomService() {
        return tblRoomServiceProperty().get();
    }

    public void setTblRoomService(TblRoomService tblRoomService) {
        tblRoomServiceProperty().set(tblRoomService);
    }

    public final ObjectProperty<BigDecimal> roomServiceCostProperty() {
        return this.roomServiceCost;
    }

    public BigDecimal getRoomServiceCost() {
        return roomServiceCostProperty().get();
    }

    public void setRoomServiceCost(BigDecimal roomServiceCost) {
        roomServiceCostProperty().set(roomServiceCost);
    }

    public final IntegerProperty peopleNumberProperty() {
        return this.peopleNumber;
    }

    public Integer getPeopleNumber() {
        return peopleNumberProperty().get();
    }

    public void setPeopleNumber(Integer peopleNumber) {
        peopleNumberProperty().set(peopleNumber);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

}
