package hotelfx.persistence.model;
// Generated Aug 21, 2017 1:49:32 PM by Hibernate Tools 4.3.1

import java.util.Date;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblRoomCard generated by hbm2java
 */
public class TblRoomCard implements java.io.Serializable {

    private final LongProperty idroomCard;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblReservationCheckInOut> tblReservationCheckInOut;
    private final ObjectProperty<TblRfidcard> tblRfidcard;
    private final ObjectProperty<TblRoomCardType> tblRoomCardType;
    private final StringProperty codeRoomCard;
    private final ObjectProperty<Date> checkIn;
    private final ObjectProperty<Date> checkOut;
    private final StringProperty note;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    public TblRoomCard() {
        this.idroomCard = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblReservationCheckInOut = new SimpleObjectProperty<>();
        this.tblRfidcard = new SimpleObjectProperty<>();
        this.tblRoomCardType = new SimpleObjectProperty<>();
        this.codeRoomCard = new SimpleStringProperty();
        this.checkIn = new SimpleObjectProperty<>();
        this.checkOut = new SimpleObjectProperty<>();
        this.note = new SimpleStringProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

    }

    public TblRoomCard(long idroomCard) {
        this();
        idroomCardProperty().set(idroomCard);
    }

    public TblRoomCard(long idroomCard, RefRecordStatus refRecordStatus, TblEmployee tblEmployeeByCreateBy, TblEmployee tblEmployeeByLastUpdateBy, TblReservationCheckInOut tblReservationCheckInOut, TblRfidcard tblRfidcard, TblRoomCardType tblRoomCardType, String codeRoomCard, Date checkIn, Date checkOut, String note, Date createDate, Date lastUpdateDate) {
        this();
        idroomCardProperty().set(idroomCard);
        refRecordStatusProperty().set(refRecordStatus);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblReservationCheckInOutProperty().set(tblReservationCheckInOut);
        tblRfidcardProperty().set(tblRfidcard);
        tblRoomCardTypeProperty().set(tblRoomCardType);
        codeRoomCardProperty().set(codeRoomCard);
        checkInProperty().set(checkIn);
        checkOutProperty().set(checkOut);
        noteProperty().set(note);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

    }

    public TblRoomCard(TblRoomCard tblRoomCard) {
        this();
        idroomCardProperty().set(tblRoomCard.getIdroomCard());
        refRecordStatusProperty().set(tblRoomCard.getRefRecordStatus());
        tblEmployeeByCreateByProperty().set(tblRoomCard.getTblEmployeeByCreateBy());
        tblEmployeeByLastUpdateByProperty().set(tblRoomCard.getTblEmployeeByLastUpdateBy());
        tblReservationCheckInOutProperty().set(tblRoomCard.getTblReservationCheckInOut());
        tblRfidcardProperty().set(tblRoomCard.getTblRfidcard());
        tblRoomCardTypeProperty().set(tblRoomCard.getTblRoomCardType());
        codeRoomCardProperty().set(tblRoomCard.getCodeRoomCard());
        checkInProperty().set(tblRoomCard.getCheckIn());
        checkOutProperty().set(tblRoomCard.getCheckOut());
        noteProperty().set(tblRoomCard.getNote());
        createDateProperty().set(tblRoomCard.getCreateDate());
        lastUpdateDateProperty().set(tblRoomCard.getLastUpdateDate());

    }

    public final LongProperty idroomCardProperty() {
        return this.idroomCard;
    }

    public long getIdroomCard() {
        return idroomCardProperty().get();
    }

    public void setIdroomCard(long idroomCard) {
        idroomCardProperty().set(idroomCard);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblReservationCheckInOut> tblReservationCheckInOutProperty() {
        return this.tblReservationCheckInOut;
    }

    public TblReservationCheckInOut getTblReservationCheckInOut() {
        return tblReservationCheckInOutProperty().get();
    }

    public void setTblReservationCheckInOut(TblReservationCheckInOut tblReservationCheckInOut) {
        tblReservationCheckInOutProperty().set(tblReservationCheckInOut);
    }

    public final ObjectProperty<TblRfidcard> tblRfidcardProperty() {
        return this.tblRfidcard;
    }

    public TblRfidcard getTblRfidcard() {
        return tblRfidcardProperty().get();
    }

    public void setTblRfidcard(TblRfidcard tblRfidcard) {
        tblRfidcardProperty().set(tblRfidcard);
    }

    public final ObjectProperty<TblRoomCardType> tblRoomCardTypeProperty() {
        return this.tblRoomCardType;
    }

    public TblRoomCardType getTblRoomCardType() {
        return tblRoomCardTypeProperty().get();
    }

    public void setTblRoomCardType(TblRoomCardType tblRoomCardType) {
        tblRoomCardTypeProperty().set(tblRoomCardType);
    }

    public final StringProperty codeRoomCardProperty() {
        return this.codeRoomCard;
    }

    public String getCodeRoomCard() {
        return codeRoomCardProperty().get();
    }

    public void setCodeRoomCard(String codeRoomCard) {
        codeRoomCardProperty().set(codeRoomCard);
    }

    public final ObjectProperty<Date> checkInProperty() {
        return this.checkIn;
    }

    public Date getCheckIn() {
        return checkInProperty().get();
    }

    public void setCheckIn(Date checkIn) {
        checkInProperty().set(checkIn);
    }

    public final ObjectProperty<Date> checkOutProperty() {
        return this.checkOut;
    }

    public Date getCheckOut() {
        return checkOutProperty().get();
    }

    public void setCheckOut(Date checkOut) {
        checkOutProperty().set(checkOut);
    }

    public final StringProperty noteProperty() {
        return this.note;
    }

    public String getNote() {
        return noteProperty().get();
    }

    public void setNote(String note) {
        noteProperty().set(note);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

}
