package hotelfx.persistence.model;
// Generated Jan 22, 2018 2:34:45 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;

/**
 * TblReservationRoomTypeDetailRoomPriceDetail generated by hbm2java
 */
public class TblReservationRoomTypeDetailRoomPriceDetail implements java.io.Serializable {

    private final LongProperty idrelation;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblReservationRoomPriceDetail> tblReservationRoomPriceDetail;
    private final ObjectProperty<TblReservationRoomTypeDetail> tblReservationRoomTypeDetail;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    private Set tblReservationRoomTypeDetailRoomPriceDetailChangeRoomHistoriesForIdrelationNew;
    private Set tblReservationRoomTypeDetailRoomPriceDetailChangeRoomHistoriesForIdrelationOld;

    public TblReservationRoomTypeDetailRoomPriceDetail() {
        this.idrelation = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblReservationRoomPriceDetail = new SimpleObjectProperty<>();
        this.tblReservationRoomTypeDetail = new SimpleObjectProperty<>();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

        this.tblReservationRoomTypeDetailRoomPriceDetailChangeRoomHistoriesForIdrelationNew = new HashSet(0);
        this.tblReservationRoomTypeDetailRoomPriceDetailChangeRoomHistoriesForIdrelationOld = new HashSet(0);
    }

    public TblReservationRoomTypeDetailRoomPriceDetail(long idrelation) {
        this();
        idrelationProperty().set(idrelation);
    }

    public TblReservationRoomTypeDetailRoomPriceDetail(long idrelation, RefRecordStatus refRecordStatus, TblEmployee tblEmployeeByCreateBy, TblEmployee tblEmployeeByLastUpdateBy, TblReservationRoomPriceDetail tblReservationRoomPriceDetail, TblReservationRoomTypeDetail tblReservationRoomTypeDetail, Date createDate, Date lastUpdateDate, Set tblReservationRoomTypeDetailRoomPriceDetailChangeRoomHistoriesForIdrelationNew, Set tblReservationRoomTypeDetailRoomPriceDetailChangeRoomHistoriesForIdrelationOld) {
        this();
        idrelationProperty().set(idrelation);
        refRecordStatusProperty().set(refRecordStatus);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblReservationRoomPriceDetailProperty().set(tblReservationRoomPriceDetail);
        tblReservationRoomTypeDetailProperty().set(tblReservationRoomTypeDetail);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

        this.tblReservationRoomTypeDetailRoomPriceDetailChangeRoomHistoriesForIdrelationNew = tblReservationRoomTypeDetailRoomPriceDetailChangeRoomHistoriesForIdrelationNew;
        this.tblReservationRoomTypeDetailRoomPriceDetailChangeRoomHistoriesForIdrelationOld = tblReservationRoomTypeDetailRoomPriceDetailChangeRoomHistoriesForIdrelationOld;
    }

    public TblReservationRoomTypeDetailRoomPriceDetail(TblReservationRoomTypeDetailRoomPriceDetail tblReservationRoomTypeDetailRoomPriceDetail) {
        this();
        idrelationProperty().set(tblReservationRoomTypeDetailRoomPriceDetail.getIdrelation());
        refRecordStatusProperty().set(tblReservationRoomTypeDetailRoomPriceDetail.getRefRecordStatus());
        tblEmployeeByCreateByProperty().set(tblReservationRoomTypeDetailRoomPriceDetail.getTblEmployeeByCreateBy());
        tblEmployeeByLastUpdateByProperty().set(tblReservationRoomTypeDetailRoomPriceDetail.getTblEmployeeByLastUpdateBy());
        tblReservationRoomPriceDetailProperty().set(tblReservationRoomTypeDetailRoomPriceDetail.getTblReservationRoomPriceDetail());
        tblReservationRoomTypeDetailProperty().set(tblReservationRoomTypeDetailRoomPriceDetail.getTblReservationRoomTypeDetail());
        createDateProperty().set(tblReservationRoomTypeDetailRoomPriceDetail.getCreateDate());
        lastUpdateDateProperty().set(tblReservationRoomTypeDetailRoomPriceDetail.getLastUpdateDate());

        this.tblReservationRoomTypeDetailRoomPriceDetailChangeRoomHistoriesForIdrelationNew = tblReservationRoomTypeDetailRoomPriceDetail.getTblReservationRoomTypeDetailRoomPriceDetailChangeRoomHistoriesForIdrelationNew();
        this.tblReservationRoomTypeDetailRoomPriceDetailChangeRoomHistoriesForIdrelationOld = tblReservationRoomTypeDetailRoomPriceDetail.getTblReservationRoomTypeDetailRoomPriceDetailChangeRoomHistoriesForIdrelationOld();
    }

    public final LongProperty idrelationProperty() {
        return this.idrelation;
    }

    public long getIdrelation() {
        return idrelationProperty().get();
    }

    public void setIdrelation(long idrelation) {
        idrelationProperty().set(idrelation);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblReservationRoomPriceDetail> tblReservationRoomPriceDetailProperty() {
        return this.tblReservationRoomPriceDetail;
    }

    public TblReservationRoomPriceDetail getTblReservationRoomPriceDetail() {
        return tblReservationRoomPriceDetailProperty().get();
    }

    public void setTblReservationRoomPriceDetail(TblReservationRoomPriceDetail tblReservationRoomPriceDetail) {
        tblReservationRoomPriceDetailProperty().set(tblReservationRoomPriceDetail);
    }

    public final ObjectProperty<TblReservationRoomTypeDetail> tblReservationRoomTypeDetailProperty() {
        return this.tblReservationRoomTypeDetail;
    }

    public TblReservationRoomTypeDetail getTblReservationRoomTypeDetail() {
        return tblReservationRoomTypeDetailProperty().get();
    }

    public void setTblReservationRoomTypeDetail(TblReservationRoomTypeDetail tblReservationRoomTypeDetail) {
        tblReservationRoomTypeDetailProperty().set(tblReservationRoomTypeDetail);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

    public Set getTblReservationRoomTypeDetailRoomPriceDetailChangeRoomHistoriesForIdrelationNew() {
        return this.tblReservationRoomTypeDetailRoomPriceDetailChangeRoomHistoriesForIdrelationNew;
    }

    public void setTblReservationRoomTypeDetailRoomPriceDetailChangeRoomHistoriesForIdrelationNew(Set tblReservationRoomTypeDetailRoomPriceDetailChangeRoomHistoriesForIdrelationNew) {
        this.tblReservationRoomTypeDetailRoomPriceDetailChangeRoomHistoriesForIdrelationNew = tblReservationRoomTypeDetailRoomPriceDetailChangeRoomHistoriesForIdrelationNew;
    }

    public Set getTblReservationRoomTypeDetailRoomPriceDetailChangeRoomHistoriesForIdrelationOld() {
        return this.tblReservationRoomTypeDetailRoomPriceDetailChangeRoomHistoriesForIdrelationOld;
    }

    public void setTblReservationRoomTypeDetailRoomPriceDetailChangeRoomHistoriesForIdrelationOld(Set tblReservationRoomTypeDetailRoomPriceDetailChangeRoomHistoriesForIdrelationOld) {
        this.tblReservationRoomTypeDetailRoomPriceDetailChangeRoomHistoriesForIdrelationOld = tblReservationRoomTypeDetailRoomPriceDetailChangeRoomHistoriesForIdrelationOld;
    }

}
