package hotelfx.persistence.model;
// Generated May 15, 2018 12:47:45 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;

/**
 * TblReservationBrokenItem generated by hbm2java
 */
public class TblReservationBrokenItem implements java.io.Serializable {

    private final LongProperty idbroken;
    private final ObjectProperty<RefEndOfDayDataStatus> refEndOfDayDataStatus;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblItem> tblItem;
    private final ObjectProperty<TblReservationRoomTypeDetail> tblReservationRoomTypeDetail;
    private final ObjectProperty<BigDecimal> itemCharge;
    private final ObjectProperty<BigDecimal> itemQuantity;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    private Set tblReservationBrokenItemPropertyBarcodes;

    public TblReservationBrokenItem() {
        this.idbroken = new SimpleLongProperty();
        this.refEndOfDayDataStatus = new SimpleObjectProperty<>();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblItem = new SimpleObjectProperty<>();
        this.tblReservationRoomTypeDetail = new SimpleObjectProperty<>();
        this.itemCharge = new SimpleObjectProperty<>();
        this.itemQuantity = new SimpleObjectProperty<>();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

        this.tblReservationBrokenItemPropertyBarcodes = new HashSet(0);
    }

    public TblReservationBrokenItem(long idbroken) {
        this();
        idbrokenProperty().set(idbroken);
    }

    public TblReservationBrokenItem(long idbroken, RefEndOfDayDataStatus refEndOfDayDataStatus, RefRecordStatus refRecordStatus, TblEmployee tblEmployeeByLastUpdateBy, TblEmployee tblEmployeeByCreateBy, TblItem tblItem, TblReservationRoomTypeDetail tblReservationRoomTypeDetail, BigDecimal itemCharge, BigDecimal itemQuantity, Date createDate, Date lastUpdateDate, Set tblReservationBrokenItemPropertyBarcodes) {
        this();
        idbrokenProperty().set(idbroken);
        refEndOfDayDataStatusProperty().set(refEndOfDayDataStatus);
        refRecordStatusProperty().set(refRecordStatus);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblItemProperty().set(tblItem);
        tblReservationRoomTypeDetailProperty().set(tblReservationRoomTypeDetail);
        itemChargeProperty().set(itemCharge);
        itemQuantityProperty().set(itemQuantity);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

        this.tblReservationBrokenItemPropertyBarcodes = tblReservationBrokenItemPropertyBarcodes;
    }

    public TblReservationBrokenItem(TblReservationBrokenItem tblReservationBrokenItem) {
        this();
        idbrokenProperty().set(tblReservationBrokenItem.getIdbroken());
        refEndOfDayDataStatusProperty().set(tblReservationBrokenItem.getRefEndOfDayDataStatus());
        refRecordStatusProperty().set(tblReservationBrokenItem.getRefRecordStatus());
        tblEmployeeByLastUpdateByProperty().set(tblReservationBrokenItem.getTblEmployeeByLastUpdateBy());
        tblEmployeeByCreateByProperty().set(tblReservationBrokenItem.getTblEmployeeByCreateBy());
        tblItemProperty().set(tblReservationBrokenItem.getTblItem());
        tblReservationRoomTypeDetailProperty().set(tblReservationBrokenItem.getTblReservationRoomTypeDetail());
        itemChargeProperty().set(tblReservationBrokenItem.getItemCharge());
        itemQuantityProperty().set(tblReservationBrokenItem.getItemQuantity());
        createDateProperty().set(tblReservationBrokenItem.getCreateDate());
        lastUpdateDateProperty().set(tblReservationBrokenItem.getLastUpdateDate());

        this.tblReservationBrokenItemPropertyBarcodes = tblReservationBrokenItem.getTblReservationBrokenItemPropertyBarcodes();
    }

    public final LongProperty idbrokenProperty() {
        return this.idbroken;
    }

    public long getIdbroken() {
        return idbrokenProperty().get();
    }

    public void setIdbroken(long idbroken) {
        idbrokenProperty().set(idbroken);
    }

    public final ObjectProperty<RefEndOfDayDataStatus> refEndOfDayDataStatusProperty() {
        return this.refEndOfDayDataStatus;
    }

    public RefEndOfDayDataStatus getRefEndOfDayDataStatus() {
        return refEndOfDayDataStatusProperty().get();
    }

    public void setRefEndOfDayDataStatus(RefEndOfDayDataStatus refEndOfDayDataStatus) {
        refEndOfDayDataStatusProperty().set(refEndOfDayDataStatus);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblItem> tblItemProperty() {
        return this.tblItem;
    }

    public TblItem getTblItem() {
        return tblItemProperty().get();
    }

    public void setTblItem(TblItem tblItem) {
        tblItemProperty().set(tblItem);
    }

    public final ObjectProperty<TblReservationRoomTypeDetail> tblReservationRoomTypeDetailProperty() {
        return this.tblReservationRoomTypeDetail;
    }

    public TblReservationRoomTypeDetail getTblReservationRoomTypeDetail() {
        return tblReservationRoomTypeDetailProperty().get();
    }

    public void setTblReservationRoomTypeDetail(TblReservationRoomTypeDetail tblReservationRoomTypeDetail) {
        tblReservationRoomTypeDetailProperty().set(tblReservationRoomTypeDetail);
    }

    public final ObjectProperty<BigDecimal> itemChargeProperty() {
        return this.itemCharge;
    }

    public BigDecimal getItemCharge() {
        return itemChargeProperty().get();
    }

    public void setItemCharge(BigDecimal itemCharge) {
        itemChargeProperty().set(itemCharge);
    }

    public final ObjectProperty<BigDecimal> itemQuantityProperty() {
        return this.itemQuantity;
    }

    public BigDecimal getItemQuantity() {
        return itemQuantityProperty().get();
    }

    public void setItemQuantity(BigDecimal itemQuantity) {
        itemQuantityProperty().set(itemQuantity);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

    public Set getTblReservationBrokenItemPropertyBarcodes() {
        return this.tblReservationBrokenItemPropertyBarcodes;
    }

    public void setTblReservationBrokenItemPropertyBarcodes(Set tblReservationBrokenItemPropertyBarcodes) {
        this.tblReservationBrokenItemPropertyBarcodes = tblReservationBrokenItemPropertyBarcodes;
    }

}
