package hotelfx.persistence.model;
// Generated Apr 19, 2018 12:58:20 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblReservationVoucher generated by hbm2java
 */
public class TblReservationVoucher implements java.io.Serializable {

    private final LongProperty idvoucher;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<RefVoucherStatus> refVoucherStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final StringProperty codeVoucher;
    private final StringProperty voucherName;
    private final ObjectProperty<BigDecimal> nominal;
    private final ObjectProperty<BigDecimal> minimumPayment;
    private final ObjectProperty<Date> validUntil;
    private final StringProperty voucherNote;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    private Set tblReservationPaymentWithReservationVouchers;

    public TblReservationVoucher() {
        this.idvoucher = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.refVoucherStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.codeVoucher = new SimpleStringProperty();
        this.voucherName = new SimpleStringProperty();
        this.nominal = new SimpleObjectProperty<>();
        this.minimumPayment = new SimpleObjectProperty<>();
        this.validUntil = new SimpleObjectProperty<>();
        this.voucherNote = new SimpleStringProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

        this.tblReservationPaymentWithReservationVouchers = new HashSet(0);
    }

    public TblReservationVoucher(long idvoucher) {
        this();
        idvoucherProperty().set(idvoucher);
    }

    public TblReservationVoucher(long idvoucher, RefRecordStatus refRecordStatus, RefVoucherStatus refVoucherStatus, TblEmployee tblEmployeeByCreateBy, TblEmployee tblEmployeeByLastUpdateBy, String codeVoucher, String voucherName, BigDecimal nominal, BigDecimal minimumPayment, Date validUntil, String voucherNote, Date createDate, Date lastUpdateDate, Set tblReservationPaymentWithReservationVouchers) {
        this();
        idvoucherProperty().set(idvoucher);
        refRecordStatusProperty().set(refRecordStatus);
        refVoucherStatusProperty().set(refVoucherStatus);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        codeVoucherProperty().set(codeVoucher);
        voucherNameProperty().set(voucherName);
        nominalProperty().set(nominal);
        minimumPaymentProperty().set(minimumPayment);
        validUntilProperty().set(validUntil);
        voucherNoteProperty().set(voucherNote);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

        this.tblReservationPaymentWithReservationVouchers = tblReservationPaymentWithReservationVouchers;
    }

    public TblReservationVoucher(TblReservationVoucher tblReservationVoucher) {
        this();
        idvoucherProperty().set(tblReservationVoucher.getIdvoucher());
        refRecordStatusProperty().set(tblReservationVoucher.getRefRecordStatus());
        refVoucherStatusProperty().set(tblReservationVoucher.getRefVoucherStatus());
        tblEmployeeByCreateByProperty().set(tblReservationVoucher.getTblEmployeeByCreateBy());
        tblEmployeeByLastUpdateByProperty().set(tblReservationVoucher.getTblEmployeeByLastUpdateBy());
        codeVoucherProperty().set(tblReservationVoucher.getCodeVoucher());
        voucherNameProperty().set(tblReservationVoucher.getVoucherName());
        nominalProperty().set(tblReservationVoucher.getNominal());
        minimumPaymentProperty().set(tblReservationVoucher.getMinimumPayment());
        validUntilProperty().set(tblReservationVoucher.getValidUntil());
        voucherNoteProperty().set(tblReservationVoucher.getVoucherNote());
        createDateProperty().set(tblReservationVoucher.getCreateDate());
        lastUpdateDateProperty().set(tblReservationVoucher.getLastUpdateDate());

        this.tblReservationPaymentWithReservationVouchers = tblReservationVoucher.getTblReservationPaymentWithReservationVouchers();
    }

    public final LongProperty idvoucherProperty() {
        return this.idvoucher;
    }

    public long getIdvoucher() {
        return idvoucherProperty().get();
    }

    public void setIdvoucher(long idvoucher) {
        idvoucherProperty().set(idvoucher);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<RefVoucherStatus> refVoucherStatusProperty() {
        return this.refVoucherStatus;
    }

    public RefVoucherStatus getRefVoucherStatus() {
        return refVoucherStatusProperty().get();
    }

    public void setRefVoucherStatus(RefVoucherStatus refVoucherStatus) {
        refVoucherStatusProperty().set(refVoucherStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final StringProperty codeVoucherProperty() {
        return this.codeVoucher;
    }

    public String getCodeVoucher() {
        return codeVoucherProperty().get();
    }

    public void setCodeVoucher(String codeVoucher) {
        codeVoucherProperty().set(codeVoucher);
    }

    public final StringProperty voucherNameProperty() {
        return this.voucherName;
    }

    public String getVoucherName() {
        return voucherNameProperty().get();
    }

    public void setVoucherName(String voucherName) {
        voucherNameProperty().set(voucherName);
    }

    public final ObjectProperty<BigDecimal> nominalProperty() {
        return this.nominal;
    }

    public BigDecimal getNominal() {
        return nominalProperty().get();
    }

    public void setNominal(BigDecimal nominal) {
        nominalProperty().set(nominal);
    }

    public final ObjectProperty<BigDecimal> minimumPaymentProperty() {
        return this.minimumPayment;
    }

    public BigDecimal getMinimumPayment() {
        return minimumPaymentProperty().get();
    }

    public void setMinimumPayment(BigDecimal minimumPayment) {
        minimumPaymentProperty().set(minimumPayment);
    }

    public final ObjectProperty<Date> validUntilProperty() {
        return this.validUntil;
    }

    public Date getValidUntil() {
        return validUntilProperty().get();
    }

    public void setValidUntil(Date validUntil) {
        validUntilProperty().set(validUntil);
    }

    public final StringProperty voucherNoteProperty() {
        return this.voucherNote;
    }

    public String getVoucherNote() {
        return voucherNoteProperty().get();
    }

    public void setVoucherNote(String voucherNote) {
        voucherNoteProperty().set(voucherNote);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

    public Set getTblReservationPaymentWithReservationVouchers() {
        return this.tblReservationPaymentWithReservationVouchers;
    }

    public void setTblReservationPaymentWithReservationVouchers(Set tblReservationPaymentWithReservationVouchers) {
        this.tblReservationPaymentWithReservationVouchers = tblReservationPaymentWithReservationVouchers;
    }
    
    @Override
    public String toString() {
        return getCodeVoucher();
    }

}
