package hotelfx.persistence.model;
// Generated Aug 21, 2017 1:49:32 PM by Hibernate Tools 4.3.1

import java.util.Date;

import javafx.beans.property.IntegerProperty;
import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleIntegerProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblReservationBreakfastOrder generated by hbm2java
 */
public class TblReservationBreakfastOrder implements java.io.Serializable {

    private final LongProperty idorder;
    private final ObjectProperty<RefBreakfastType> refBreakfastType;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final StringProperty codeOrder;
    private final ObjectProperty<Date> breakfastDate;
    private final IntegerProperty maxGuest;
    private final LongProperty totalOrder;
    private final StringProperty note;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    public TblReservationBreakfastOrder() {
        this.idorder = new SimpleLongProperty();
        this.refBreakfastType = new SimpleObjectProperty<>();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.codeOrder = new SimpleStringProperty();
        this.breakfastDate = new SimpleObjectProperty<>();
        this.maxGuest = new SimpleIntegerProperty();
        this.totalOrder = new SimpleLongProperty();
        this.note = new SimpleStringProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

    }

    public TblReservationBreakfastOrder(long idorder) {
        this();
        idorderProperty().set(idorder);
    }

    public TblReservationBreakfastOrder(long idorder, RefBreakfastType refBreakfastType, RefRecordStatus refRecordStatus, TblEmployee tblEmployeeByCreateBy, TblEmployee tblEmployeeByLastUpdateBy, String codeOrder, Date breakfastDate, Integer maxGuest, Long totalOrder, String note, Date createDate, Date lastUpdateDate) {
        this();
        idorderProperty().set(idorder);
        refBreakfastTypeProperty().set(refBreakfastType);
        refRecordStatusProperty().set(refRecordStatus);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        codeOrderProperty().set(codeOrder);
        breakfastDateProperty().set(breakfastDate);
        maxGuestProperty().set(maxGuest);
        totalOrderProperty().set(totalOrder);
        noteProperty().set(note);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

    }

    public TblReservationBreakfastOrder(TblReservationBreakfastOrder tblReservationBreakfastOrder) {
        this();
        idorderProperty().set(tblReservationBreakfastOrder.getIdorder());
        refBreakfastTypeProperty().set(tblReservationBreakfastOrder.getRefBreakfastType());
        refRecordStatusProperty().set(tblReservationBreakfastOrder.getRefRecordStatus());
        tblEmployeeByCreateByProperty().set(tblReservationBreakfastOrder.getTblEmployeeByCreateBy());
        tblEmployeeByLastUpdateByProperty().set(tblReservationBreakfastOrder.getTblEmployeeByLastUpdateBy());
        codeOrderProperty().set(tblReservationBreakfastOrder.getCodeOrder());
        breakfastDateProperty().set(tblReservationBreakfastOrder.getBreakfastDate());
        maxGuestProperty().set(tblReservationBreakfastOrder.getMaxGuest());
        totalOrderProperty().set(tblReservationBreakfastOrder.getTotalOrder());
        noteProperty().set(tblReservationBreakfastOrder.getNote());
        createDateProperty().set(tblReservationBreakfastOrder.getCreateDate());
        lastUpdateDateProperty().set(tblReservationBreakfastOrder.getLastUpdateDate());

    }

    public final LongProperty idorderProperty() {
        return this.idorder;
    }

    public long getIdorder() {
        return idorderProperty().get();
    }

    public void setIdorder(long idorder) {
        idorderProperty().set(idorder);
    }

    public final ObjectProperty<RefBreakfastType> refBreakfastTypeProperty() {
        return this.refBreakfastType;
    }

    public RefBreakfastType getRefBreakfastType() {
        return refBreakfastTypeProperty().get();
    }

    public void setRefBreakfastType(RefBreakfastType refBreakfastType) {
        refBreakfastTypeProperty().set(refBreakfastType);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final StringProperty codeOrderProperty() {
        return this.codeOrder;
    }

    public String getCodeOrder() {
        return codeOrderProperty().get();
    }

    public void setCodeOrder(String codeOrder) {
        codeOrderProperty().set(codeOrder);
    }

    public final ObjectProperty<Date> breakfastDateProperty() {
        return this.breakfastDate;
    }

    public Date getBreakfastDate() {
        return breakfastDateProperty().get();
    }

    public void setBreakfastDate(Date breakfastDate) {
        breakfastDateProperty().set(breakfastDate);
    }

    public final IntegerProperty maxGuestProperty() {
        return this.maxGuest;
    }

    public Integer getMaxGuest() {
        return maxGuestProperty().get();
    }

    public void setMaxGuest(Integer maxGuest) {
        maxGuestProperty().set(maxGuest);
    }

    public final LongProperty totalOrderProperty() {
        return this.totalOrder;
    }

    public Long getTotalOrder() {
        return totalOrderProperty().get();
    }

    public void setTotalOrder(Long totalOrder) {
        totalOrderProperty().set(totalOrder);
    }

    public final StringProperty noteProperty() {
        return this.note;
    }

    public String getNote() {
        return noteProperty().get();
    }

    public void setNote(String note) {
        noteProperty().set(note);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

}
