package hotelfx.persistence.model;
// Generated Feb 28, 2018 4:32:44 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblRoomCheck generated by hbm2java
 */
public class TblRoomCheck implements java.io.Serializable {

    private final LongProperty idroomCheck;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<RefRoomCheckStatus> refRoomCheckStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByIdchecker;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblRoom> tblRoom;
    private final ObjectProperty<TblRoomStatusChangeHistory> tblRoomStatusChangeHistory;
    private final StringProperty codeRoomCheck;
    private final ObjectProperty<Date> checkDateTime;
    private final StringProperty checkNote;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    private Set tblRoomCheckItemMutationHistories;

    public TblRoomCheck() {
        this.idroomCheck = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.refRoomCheckStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByIdchecker = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblRoom = new SimpleObjectProperty<>();
        this.tblRoomStatusChangeHistory = new SimpleObjectProperty<>();
        this.codeRoomCheck = new SimpleStringProperty();
        this.checkDateTime = new SimpleObjectProperty<>();
        this.checkNote = new SimpleStringProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

        this.tblRoomCheckItemMutationHistories = new HashSet(0);
    }

    public TblRoomCheck(long idroomCheck) {
        this();
        idroomCheckProperty().set(idroomCheck);
    }

    public TblRoomCheck(long idroomCheck, RefRecordStatus refRecordStatus, RefRoomCheckStatus refRoomCheckStatus, TblEmployee tblEmployeeByCreateBy, TblEmployee tblEmployeeByIdchecker, TblEmployee tblEmployeeByLastUpdateBy, TblRoom tblRoom, TblRoomStatusChangeHistory tblRoomStatusChangeHistory, String codeRoomCheck, Date checkDateTime, String checkNote, Date createDate, Date lastUpdateDate, Set tblRoomCheckItemMutationHistories) {
        this();
        idroomCheckProperty().set(idroomCheck);
        refRecordStatusProperty().set(refRecordStatus);
        refRoomCheckStatusProperty().set(refRoomCheckStatus);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblEmployeeByIdcheckerProperty().set(tblEmployeeByIdchecker);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblRoomProperty().set(tblRoom);
        tblRoomStatusChangeHistoryProperty().set(tblRoomStatusChangeHistory);
        codeRoomCheckProperty().set(codeRoomCheck);
        checkDateTimeProperty().set(checkDateTime);
        checkNoteProperty().set(checkNote);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

        this.tblRoomCheckItemMutationHistories = tblRoomCheckItemMutationHistories;
    }

    public TblRoomCheck(TblRoomCheck tblRoomCheck) {
        this();
        idroomCheckProperty().set(tblRoomCheck.getIdroomCheck());
        refRecordStatusProperty().set(tblRoomCheck.getRefRecordStatus());
        refRoomCheckStatusProperty().set(tblRoomCheck.getRefRoomCheckStatus());
        tblEmployeeByCreateByProperty().set(tblRoomCheck.getTblEmployeeByCreateBy());
        tblEmployeeByIdcheckerProperty().set(tblRoomCheck.getTblEmployeeByIdchecker());
        tblEmployeeByLastUpdateByProperty().set(tblRoomCheck.getTblEmployeeByLastUpdateBy());
        tblRoomProperty().set(tblRoomCheck.getTblRoom());
        tblRoomStatusChangeHistoryProperty().set(tblRoomCheck.getTblRoomStatusChangeHistory());
        codeRoomCheckProperty().set(tblRoomCheck.getCodeRoomCheck());
        checkDateTimeProperty().set(tblRoomCheck.getCheckDateTime());
        checkNoteProperty().set(tblRoomCheck.getCheckNote());
        createDateProperty().set(tblRoomCheck.getCreateDate());
        lastUpdateDateProperty().set(tblRoomCheck.getLastUpdateDate());

        this.tblRoomCheckItemMutationHistories = tblRoomCheck.getTblRoomCheckItemMutationHistories();
    }

    public final LongProperty idroomCheckProperty() {
        return this.idroomCheck;
    }

    public long getIdroomCheck() {
        return idroomCheckProperty().get();
    }

    public void setIdroomCheck(long idroomCheck) {
        idroomCheckProperty().set(idroomCheck);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<RefRoomCheckStatus> refRoomCheckStatusProperty() {
        return this.refRoomCheckStatus;
    }

    public RefRoomCheckStatus getRefRoomCheckStatus() {
        return refRoomCheckStatusProperty().get();
    }

    public void setRefRoomCheckStatus(RefRoomCheckStatus refRoomCheckStatus) {
        refRoomCheckStatusProperty().set(refRoomCheckStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByIdcheckerProperty() {
        return this.tblEmployeeByIdchecker;
    }

    public TblEmployee getTblEmployeeByIdchecker() {
        return tblEmployeeByIdcheckerProperty().get();
    }

    public void setTblEmployeeByIdchecker(TblEmployee tblEmployeeByIdchecker) {
        tblEmployeeByIdcheckerProperty().set(tblEmployeeByIdchecker);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblRoom> tblRoomProperty() {
        return this.tblRoom;
    }

    public TblRoom getTblRoom() {
        return tblRoomProperty().get();
    }

    public void setTblRoom(TblRoom tblRoom) {
        tblRoomProperty().set(tblRoom);
    }

    public final ObjectProperty<TblRoomStatusChangeHistory> tblRoomStatusChangeHistoryProperty() {
        return this.tblRoomStatusChangeHistory;
    }

    public TblRoomStatusChangeHistory getTblRoomStatusChangeHistory() {
        return tblRoomStatusChangeHistoryProperty().get();
    }

    public void setTblRoomStatusChangeHistory(TblRoomStatusChangeHistory tblRoomStatusChangeHistory) {
        tblRoomStatusChangeHistoryProperty().set(tblRoomStatusChangeHistory);
    }

    public final StringProperty codeRoomCheckProperty() {
        return this.codeRoomCheck;
    }

    public String getCodeRoomCheck() {
        return codeRoomCheckProperty().get();
    }

    public void setCodeRoomCheck(String codeRoomCheck) {
        codeRoomCheckProperty().set(codeRoomCheck);
    }

    public final ObjectProperty<Date> checkDateTimeProperty() {
        return this.checkDateTime;
    }

    public Date getCheckDateTime() {
        return checkDateTimeProperty().get();
    }

    public void setCheckDateTime(Date checkDateTime) {
        checkDateTimeProperty().set(checkDateTime);
    }

    public final StringProperty checkNoteProperty() {
        return this.checkNote;
    }

    public String getCheckNote() {
        return checkNoteProperty().get();
    }

    public void setCheckNote(String checkNote) {
        checkNoteProperty().set(checkNote);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

    public Set getTblRoomCheckItemMutationHistories() {
        return this.tblRoomCheckItemMutationHistories;
    }

    public void setTblRoomCheckItemMutationHistories(Set tblRoomCheckItemMutationHistories) {
        this.tblRoomCheckItemMutationHistories = tblRoomCheckItemMutationHistories;
    }

}
