package hotelfx.persistence.model;
// Generated Jul 9, 2018 10:54:12 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javafx.beans.property.BooleanProperty;
import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleBooleanProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblReservationPaymentWithGuaranteePayment generated by hbm2java
 */
public class TblReservationPaymentWithGuaranteePayment implements java.io.Serializable {

    private final LongProperty iddetail;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblBankAccount> tblBankAccountBySenderBankAccount;
    private final ObjectProperty<TblBankAccount> tblBankAccountByReceiverBankAccount;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblHotelReceivable> tblHotelReceivable;
    private final ObjectProperty<TblPartner> tblPartner;
    private final ObjectProperty<TblPartnerAgreement> tblPartnerAgreement;
    private final ObjectProperty<TblReservationPayment> tblReservationPayment;
    private final StringProperty codeGuarantee;
    private final StringProperty senderName;
    private final StringProperty receiverName;
    private final ObjectProperty<Date> dueDate;
    private final BooleanProperty isDebt;
    private final StringProperty guaranteePaymentNote;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    private Set tblGuaranteeLetterItemDetails;

    public TblReservationPaymentWithGuaranteePayment() {
        this.iddetail = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblBankAccountBySenderBankAccount = new SimpleObjectProperty<>();
        this.tblBankAccountByReceiverBankAccount = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblHotelReceivable = new SimpleObjectProperty<>();
        this.tblPartner = new SimpleObjectProperty<>();
        this.tblPartnerAgreement = new SimpleObjectProperty<>();
        this.tblReservationPayment = new SimpleObjectProperty<>();
        this.codeGuarantee = new SimpleStringProperty();
        this.senderName = new SimpleStringProperty();
        this.receiverName = new SimpleStringProperty();
        this.dueDate = new SimpleObjectProperty<>();
        this.isDebt = new SimpleBooleanProperty();
        this.guaranteePaymentNote = new SimpleStringProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

        this.tblGuaranteeLetterItemDetails = new HashSet(0);
    }

    public TblReservationPaymentWithGuaranteePayment(long iddetail) {
        this();
        iddetailProperty().set(iddetail);
    }

    public TblReservationPaymentWithGuaranteePayment(long iddetail, RefRecordStatus refRecordStatus, TblBankAccount tblBankAccountBySenderBankAccount, TblBankAccount tblBankAccountByReceiverBankAccount, TblEmployee tblEmployeeByCreateBy, TblEmployee tblEmployeeByLastUpdateBy, TblHotelReceivable tblHotelReceivable, TblPartner tblPartner, TblPartnerAgreement tblPartnerAgreement, TblReservationPayment tblReservationPayment, String codeGuarantee, String senderName, String receiverName, Date dueDate, Boolean isDebt, String guaranteePaymentNote, Date createDate, Date lastUpdateDate, Set tblGuaranteeLetterItemDetails) {
        this();
        iddetailProperty().set(iddetail);
        refRecordStatusProperty().set(refRecordStatus);
        tblBankAccountBySenderBankAccountProperty().set(tblBankAccountBySenderBankAccount);
        tblBankAccountByReceiverBankAccountProperty().set(tblBankAccountByReceiverBankAccount);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblHotelReceivableProperty().set(tblHotelReceivable);
        tblPartnerProperty().set(tblPartner);
        tblPartnerAgreementProperty().set(tblPartnerAgreement);
        tblReservationPaymentProperty().set(tblReservationPayment);
        codeGuaranteeProperty().set(codeGuarantee);
        senderNameProperty().set(senderName);
        receiverNameProperty().set(receiverName);
        dueDateProperty().set(dueDate);
        isDebtProperty().set(isDebt);
        guaranteePaymentNoteProperty().set(guaranteePaymentNote);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

        this.tblGuaranteeLetterItemDetails = tblGuaranteeLetterItemDetails;
    }

    public TblReservationPaymentWithGuaranteePayment(TblReservationPaymentWithGuaranteePayment tblReservationPaymentWithGuaranteePayment) {
        this();
        iddetailProperty().set(tblReservationPaymentWithGuaranteePayment.getIddetail());
        refRecordStatusProperty().set(tblReservationPaymentWithGuaranteePayment.getRefRecordStatus());
        tblBankAccountBySenderBankAccountProperty().set(tblReservationPaymentWithGuaranteePayment.getTblBankAccountBySenderBankAccount());
        tblBankAccountByReceiverBankAccountProperty().set(tblReservationPaymentWithGuaranteePayment.getTblBankAccountByReceiverBankAccount());
        tblEmployeeByCreateByProperty().set(tblReservationPaymentWithGuaranteePayment.getTblEmployeeByCreateBy());
        tblEmployeeByLastUpdateByProperty().set(tblReservationPaymentWithGuaranteePayment.getTblEmployeeByLastUpdateBy());
        tblHotelReceivableProperty().set(tblReservationPaymentWithGuaranteePayment.getTblHotelReceivable());
        tblPartnerProperty().set(tblReservationPaymentWithGuaranteePayment.getTblPartner());
        tblPartnerAgreementProperty().set(tblReservationPaymentWithGuaranteePayment.getTblPartnerAgreement());
        tblReservationPaymentProperty().set(tblReservationPaymentWithGuaranteePayment.getTblReservationPayment());
        codeGuaranteeProperty().set(tblReservationPaymentWithGuaranteePayment.getCodeGuarantee());
        senderNameProperty().set(tblReservationPaymentWithGuaranteePayment.getSenderName());
        receiverNameProperty().set(tblReservationPaymentWithGuaranteePayment.getReceiverName());
        dueDateProperty().set(tblReservationPaymentWithGuaranteePayment.getDueDate());
        isDebtProperty().set(tblReservationPaymentWithGuaranteePayment.getIsDebt());
        guaranteePaymentNoteProperty().set(tblReservationPaymentWithGuaranteePayment.getGuaranteePaymentNote());
        createDateProperty().set(tblReservationPaymentWithGuaranteePayment.getCreateDate());
        lastUpdateDateProperty().set(tblReservationPaymentWithGuaranteePayment.getLastUpdateDate());

        this.tblGuaranteeLetterItemDetails = tblReservationPaymentWithGuaranteePayment.getTblGuaranteeLetterItemDetails();
    }

    public final LongProperty iddetailProperty() {
        return this.iddetail;
    }

    public long getIddetail() {
        return iddetailProperty().get();
    }

    public void setIddetail(long iddetail) {
        iddetailProperty().set(iddetail);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblBankAccount> tblBankAccountBySenderBankAccountProperty() {
        return this.tblBankAccountBySenderBankAccount;
    }

    public TblBankAccount getTblBankAccountBySenderBankAccount() {
        return tblBankAccountBySenderBankAccountProperty().get();
    }

    public void setTblBankAccountBySenderBankAccount(TblBankAccount tblBankAccountBySenderBankAccount) {
        tblBankAccountBySenderBankAccountProperty().set(tblBankAccountBySenderBankAccount);
    }

    public final ObjectProperty<TblBankAccount> tblBankAccountByReceiverBankAccountProperty() {
        return this.tblBankAccountByReceiverBankAccount;
    }

    public TblBankAccount getTblBankAccountByReceiverBankAccount() {
        return tblBankAccountByReceiverBankAccountProperty().get();
    }

    public void setTblBankAccountByReceiverBankAccount(TblBankAccount tblBankAccountByReceiverBankAccount) {
        tblBankAccountByReceiverBankAccountProperty().set(tblBankAccountByReceiverBankAccount);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblHotelReceivable> tblHotelReceivableProperty() {
        return this.tblHotelReceivable;
    }

    public TblHotelReceivable getTblHotelReceivable() {
        return tblHotelReceivableProperty().get();
    }

    public void setTblHotelReceivable(TblHotelReceivable tblHotelReceivable) {
        tblHotelReceivableProperty().set(tblHotelReceivable);
    }

    public final ObjectProperty<TblPartner> tblPartnerProperty() {
        return this.tblPartner;
    }

    public TblPartner getTblPartner() {
        return tblPartnerProperty().get();
    }

    public void setTblPartner(TblPartner tblPartner) {
        tblPartnerProperty().set(tblPartner);
    }

    public final ObjectProperty<TblPartnerAgreement> tblPartnerAgreementProperty() {
        return this.tblPartnerAgreement;
    }

    public TblPartnerAgreement getTblPartnerAgreement() {
        return tblPartnerAgreementProperty().get();
    }

    public void setTblPartnerAgreement(TblPartnerAgreement tblPartnerAgreement) {
        tblPartnerAgreementProperty().set(tblPartnerAgreement);
    }

    public final ObjectProperty<TblReservationPayment> tblReservationPaymentProperty() {
        return this.tblReservationPayment;
    }

    public TblReservationPayment getTblReservationPayment() {
        return tblReservationPaymentProperty().get();
    }

    public void setTblReservationPayment(TblReservationPayment tblReservationPayment) {
        tblReservationPaymentProperty().set(tblReservationPayment);
    }

    public final StringProperty codeGuaranteeProperty() {
        return this.codeGuarantee;
    }

    public String getCodeGuarantee() {
        return codeGuaranteeProperty().get();
    }

    public void setCodeGuarantee(String codeGuarantee) {
        codeGuaranteeProperty().set(codeGuarantee);
    }

    public final StringProperty senderNameProperty() {
        return this.senderName;
    }

    public String getSenderName() {
        return senderNameProperty().get();
    }

    public void setSenderName(String senderName) {
        senderNameProperty().set(senderName);
    }

    public final StringProperty receiverNameProperty() {
        return this.receiverName;
    }

    public String getReceiverName() {
        return receiverNameProperty().get();
    }

    public void setReceiverName(String receiverName) {
        receiverNameProperty().set(receiverName);
    }

    public final ObjectProperty<Date> dueDateProperty() {
        return this.dueDate;
    }

    public Date getDueDate() {
        return dueDateProperty().get();
    }

    public void setDueDate(Date dueDate) {
        dueDateProperty().set(dueDate);
    }

    public final BooleanProperty isDebtProperty() {
        return this.isDebt;
    }

    public Boolean getIsDebt() {
        return isDebtProperty().get();
    }

    public void setIsDebt(Boolean isDebt) {
        isDebtProperty().set(isDebt);
    }

    public final StringProperty guaranteePaymentNoteProperty() {
        return this.guaranteePaymentNote;
    }

    public String getGuaranteePaymentNote() {
        return guaranteePaymentNoteProperty().get();
    }

    public void setGuaranteePaymentNote(String guaranteePaymentNote) {
        guaranteePaymentNoteProperty().set(guaranteePaymentNote);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

    public Set getTblGuaranteeLetterItemDetails() {
        return this.tblGuaranteeLetterItemDetails;
    }

    public void setTblGuaranteeLetterItemDetails(Set tblGuaranteeLetterItemDetails) {
        this.tblGuaranteeLetterItemDetails = tblGuaranteeLetterItemDetails;
    }

}
