package hotelfx.persistence.model;
// Generated Aug 21, 2017 1:49:32 PM by Hibernate Tools 4.3.1

import java.sql.Time;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblRoomCardType generated by hbm2java
 */
public class TblRoomCardType implements java.io.Serializable {

    private final LongProperty idroomCardType;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final StringProperty codeRoomCardType;
    private final ObjectProperty<Time> beginOperational;
    private final ObjectProperty<Time> endOperational;
    private final StringProperty note;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    private Set tblRoomCards;

    public TblRoomCardType() {
        this.idroomCardType = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.codeRoomCardType = new SimpleStringProperty();
        this.beginOperational = new SimpleObjectProperty<>();
        this.endOperational = new SimpleObjectProperty<>();
        this.note = new SimpleStringProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

        this.tblRoomCards = new HashSet(0);
    }

    public TblRoomCardType(long idroomCardType) {
        this();
        idroomCardTypeProperty().set(idroomCardType);
    }

    public TblRoomCardType(long idroomCardType, RefRecordStatus refRecordStatus, TblEmployee tblEmployeeByCreateBy, TblEmployee tblEmployeeByLastUpdateBy, String codeRoomCardType, Time beginOperational, Time endOperational, String note, Date createDate, Date lastUpdateDate, Set tblRoomCards) {
        this();
        idroomCardTypeProperty().set(idroomCardType);
        refRecordStatusProperty().set(refRecordStatus);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        codeRoomCardTypeProperty().set(codeRoomCardType);
        beginOperationalProperty().set(beginOperational);
        endOperationalProperty().set(endOperational);
        noteProperty().set(note);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

        this.tblRoomCards = tblRoomCards;
    }

    public TblRoomCardType(TblRoomCardType tblRoomCardType) {
        this();
        idroomCardTypeProperty().set(tblRoomCardType.getIdroomCardType());
        refRecordStatusProperty().set(tblRoomCardType.getRefRecordStatus());
        tblEmployeeByCreateByProperty().set(tblRoomCardType.getTblEmployeeByCreateBy());
        tblEmployeeByLastUpdateByProperty().set(tblRoomCardType.getTblEmployeeByLastUpdateBy());
        codeRoomCardTypeProperty().set(tblRoomCardType.getCodeRoomCardType());
        beginOperationalProperty().set(tblRoomCardType.getBeginOperational());
        endOperationalProperty().set(tblRoomCardType.getEndOperational());
        noteProperty().set(tblRoomCardType.getNote());
        createDateProperty().set(tblRoomCardType.getCreateDate());
        lastUpdateDateProperty().set(tblRoomCardType.getLastUpdateDate());

        this.tblRoomCards = tblRoomCardType.getTblRoomCards();
    }

    public final LongProperty idroomCardTypeProperty() {
        return this.idroomCardType;
    }

    public long getIdroomCardType() {
        return idroomCardTypeProperty().get();
    }

    public void setIdroomCardType(long idroomCardType) {
        idroomCardTypeProperty().set(idroomCardType);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final StringProperty codeRoomCardTypeProperty() {
        return this.codeRoomCardType;
    }

    public String getCodeRoomCardType() {
        return codeRoomCardTypeProperty().get();
    }

    public void setCodeRoomCardType(String codeRoomCardType) {
        codeRoomCardTypeProperty().set(codeRoomCardType);
    }

    public final ObjectProperty<Time> beginOperationalProperty() {
        return this.beginOperational;
    }

    public Time getBeginOperational() {
        return beginOperationalProperty().get();
    }

    public void setBeginOperational(Time beginOperational) {
        beginOperationalProperty().set(beginOperational);
    }

    public final ObjectProperty<Time> endOperationalProperty() {
        return this.endOperational;
    }

    public Time getEndOperational() {
        return endOperationalProperty().get();
    }

    public void setEndOperational(Time endOperational) {
        endOperationalProperty().set(endOperational);
    }

    public final StringProperty noteProperty() {
        return this.note;
    }

    public String getNote() {
        return noteProperty().get();
    }

    public void setNote(String note) {
        noteProperty().set(note);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

    public Set getTblRoomCards() {
        return this.tblRoomCards;
    }

    public void setTblRoomCards(Set tblRoomCards) {
        this.tblRoomCards = tblRoomCards;
    }

}
