package hotelfx.persistence.model;
// Generated Aug 24, 2018 1:54:50 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javafx.beans.property.BooleanProperty;
import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleBooleanProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblRetur generated by hbm2java
 */
public class TblRetur implements java.io.Serializable {

    private final LongProperty idretur;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<RefReturPaymentStatus> refReturPaymentStatus;
    private final ObjectProperty<RefReturStatus> refReturStatus;
    private final ObjectProperty<RefReturType> refReturType;
    private final ObjectProperty<TblApprovalData> tblApprovalData;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByCanceledBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreatedBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByApprovedBy;
    private final ObjectProperty<TblFinanceData> tblFinanceData;
    private final ObjectProperty<TblHotelReceivable> tblHotelReceivable;
    private final ObjectProperty<TblSupplier> tblSupplier;
    private final StringProperty codeRetur;
    private final ObjectProperty<Date> returDate;
    private final StringProperty deliveryNumber;
    private final ObjectProperty<BigDecimal> deliveryCost;
    private final ObjectProperty<BigDecimal> taxPercentage;
    private final ObjectProperty<Date> maxReturDate;
    private final ObjectProperty<Date> maxReturPaymentDate;
    private final BooleanProperty updateStockStatus;
    private final StringProperty returNote;
    private final ObjectProperty<Date> createdDate;
    private final ObjectProperty<Date> approvedDate;
    private final ObjectProperty<Date> canceledDate;
    private final StringProperty canceledNote;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    private Set tblPurchaseOrders;
    private Set tblReturDetails;

    public TblRetur() {
        this.idretur = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.refReturPaymentStatus = new SimpleObjectProperty<>();
        this.refReturStatus = new SimpleObjectProperty<>();
        this.refReturType = new SimpleObjectProperty<>();
        this.tblApprovalData = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByCanceledBy = new SimpleObjectProperty<>();
        this.tblEmployeeByCreatedBy = new SimpleObjectProperty<>();
        this.tblEmployeeByApprovedBy = new SimpleObjectProperty<>();
        this.tblFinanceData = new SimpleObjectProperty<>();
        this.tblHotelReceivable = new SimpleObjectProperty<>();
        this.tblSupplier = new SimpleObjectProperty<>();
        this.codeRetur = new SimpleStringProperty();
        this.returDate = new SimpleObjectProperty<>();
        this.deliveryNumber = new SimpleStringProperty();
        this.deliveryCost = new SimpleObjectProperty<>();
        this.taxPercentage = new SimpleObjectProperty<>();
        this.maxReturDate = new SimpleObjectProperty<>();
        this.maxReturPaymentDate = new SimpleObjectProperty<>();
        this.updateStockStatus = new SimpleBooleanProperty();
        this.returNote = new SimpleStringProperty();
        this.createdDate = new SimpleObjectProperty<>();
        this.approvedDate = new SimpleObjectProperty<>();
        this.canceledDate = new SimpleObjectProperty<>();
        this.canceledNote = new SimpleStringProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

        this.tblPurchaseOrders = new HashSet(0);
        this.tblReturDetails = new HashSet(0);
    }

    public TblRetur(long idretur) {
        this();
        idreturProperty().set(idretur);
    }

    public TblRetur(long idretur, RefRecordStatus refRecordStatus, RefReturPaymentStatus refReturPaymentStatus, RefReturStatus refReturStatus, RefReturType refReturType, TblApprovalData tblApprovalData, TblEmployee tblEmployeeByCreateBy, TblEmployee tblEmployeeByLastUpdateBy, TblEmployee tblEmployeeByCanceledBy, TblEmployee tblEmployeeByCreatedBy, TblEmployee tblEmployeeByApprovedBy, TblFinanceData tblFinanceData, TblHotelReceivable tblHotelReceivable, TblSupplier tblSupplier, String codeRetur, Date returDate, String deliveryNumber, BigDecimal deliveryCost, BigDecimal taxPercentage, Date maxReturDate, Date maxReturPaymentDate, Boolean updateStockStatus, String returNote, Date createdDate, Date approvedDate, Date canceledDate, String canceledNote, Date createDate, Date lastUpdateDate, Set tblPurchaseOrders, Set tblReturDetails) {
        this();
        idreturProperty().set(idretur);
        refRecordStatusProperty().set(refRecordStatus);
        refReturPaymentStatusProperty().set(refReturPaymentStatus);
        refReturStatusProperty().set(refReturStatus);
        refReturTypeProperty().set(refReturType);
        tblApprovalDataProperty().set(tblApprovalData);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblEmployeeByCanceledByProperty().set(tblEmployeeByCanceledBy);
        tblEmployeeByCreatedByProperty().set(tblEmployeeByCreatedBy);
        tblEmployeeByApprovedByProperty().set(tblEmployeeByApprovedBy);
        tblFinanceDataProperty().set(tblFinanceData);
        tblHotelReceivableProperty().set(tblHotelReceivable);
        tblSupplierProperty().set(tblSupplier);
        codeReturProperty().set(codeRetur);
        returDateProperty().set(returDate);
        deliveryNumberProperty().set(deliveryNumber);
        deliveryCostProperty().set(deliveryCost);
        taxPercentageProperty().set(taxPercentage);
        maxReturDateProperty().set(maxReturDate);
        maxReturPaymentDateProperty().set(maxReturPaymentDate);
        updateStockStatusProperty().set(updateStockStatus);
        returNoteProperty().set(returNote);
        createdDateProperty().set(createdDate);
        approvedDateProperty().set(approvedDate);
        canceledDateProperty().set(canceledDate);
        canceledNoteProperty().set(canceledNote);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

        this.tblPurchaseOrders = tblPurchaseOrders;
        this.tblReturDetails = tblReturDetails;
    }

    public TblRetur(TblRetur tblRetur) {
        this();
        idreturProperty().set(tblRetur.getIdretur());
        refRecordStatusProperty().set(tblRetur.getRefRecordStatus());
        refReturPaymentStatusProperty().set(tblRetur.getRefReturPaymentStatus());
        refReturStatusProperty().set(tblRetur.getRefReturStatus());
        refReturTypeProperty().set(tblRetur.getRefReturType());
        tblApprovalDataProperty().set(tblRetur.getTblApprovalData());
        tblEmployeeByCreateByProperty().set(tblRetur.getTblEmployeeByCreateBy());
        tblEmployeeByLastUpdateByProperty().set(tblRetur.getTblEmployeeByLastUpdateBy());
        tblEmployeeByCanceledByProperty().set(tblRetur.getTblEmployeeByCanceledBy());
        tblEmployeeByCreatedByProperty().set(tblRetur.getTblEmployeeByCreatedBy());
        tblEmployeeByApprovedByProperty().set(tblRetur.getTblEmployeeByApprovedBy());
        tblFinanceDataProperty().set(tblRetur.getTblFinanceData());
        tblHotelReceivableProperty().set(tblRetur.getTblHotelReceivable());
        tblSupplierProperty().set(tblRetur.getTblSupplier());
        codeReturProperty().set(tblRetur.getCodeRetur());
        returDateProperty().set(tblRetur.getReturDate());
        deliveryNumberProperty().set(tblRetur.getDeliveryNumber());
        deliveryCostProperty().set(tblRetur.getDeliveryCost());
        taxPercentageProperty().set(tblRetur.getTaxPercentage());
        maxReturDateProperty().set(tblRetur.getMaxReturDate());
        maxReturPaymentDateProperty().set(tblRetur.getMaxReturPaymentDate());
        updateStockStatusProperty().set(tblRetur.getUpdateStockStatus());
        returNoteProperty().set(tblRetur.getReturNote());
        createdDateProperty().set(tblRetur.getCreatedDate());
        approvedDateProperty().set(tblRetur.getApprovedDate());
        canceledDateProperty().set(tblRetur.getCanceledDate());
        canceledNoteProperty().set(tblRetur.getCanceledNote());
        createDateProperty().set(tblRetur.getCreateDate());
        lastUpdateDateProperty().set(tblRetur.getLastUpdateDate());

        this.tblPurchaseOrders = tblRetur.getTblPurchaseOrders();
        this.tblReturDetails = tblRetur.getTblReturDetails();
    }

    public final LongProperty idreturProperty() {
        return this.idretur;
    }

    public long getIdretur() {
        return idreturProperty().get();
    }

    public void setIdretur(long idretur) {
        idreturProperty().set(idretur);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<RefReturPaymentStatus> refReturPaymentStatusProperty() {
        return this.refReturPaymentStatus;
    }

    public RefReturPaymentStatus getRefReturPaymentStatus() {
        return refReturPaymentStatusProperty().get();
    }

    public void setRefReturPaymentStatus(RefReturPaymentStatus refReturPaymentStatus) {
        refReturPaymentStatusProperty().set(refReturPaymentStatus);
    }

    public final ObjectProperty<RefReturStatus> refReturStatusProperty() {
        return this.refReturStatus;
    }

    public RefReturStatus getRefReturStatus() {
        return refReturStatusProperty().get();
    }

    public void setRefReturStatus(RefReturStatus refReturStatus) {
        refReturStatusProperty().set(refReturStatus);
    }

    public final ObjectProperty<RefReturType> refReturTypeProperty() {
        return this.refReturType;
    }

    public RefReturType getRefReturType() {
        return refReturTypeProperty().get();
    }

    public void setRefReturType(RefReturType refReturType) {
        refReturTypeProperty().set(refReturType);
    }

    public final ObjectProperty<TblApprovalData> tblApprovalDataProperty() {
        return this.tblApprovalData;
    }

    public TblApprovalData getTblApprovalData() {
        return tblApprovalDataProperty().get();
    }

    public void setTblApprovalData(TblApprovalData tblApprovalData) {
        tblApprovalDataProperty().set(tblApprovalData);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCanceledByProperty() {
        return this.tblEmployeeByCanceledBy;
    }

    public TblEmployee getTblEmployeeByCanceledBy() {
        return tblEmployeeByCanceledByProperty().get();
    }

    public void setTblEmployeeByCanceledBy(TblEmployee tblEmployeeByCanceledBy) {
        tblEmployeeByCanceledByProperty().set(tblEmployeeByCanceledBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreatedByProperty() {
        return this.tblEmployeeByCreatedBy;
    }

    public TblEmployee getTblEmployeeByCreatedBy() {
        return tblEmployeeByCreatedByProperty().get();
    }

    public void setTblEmployeeByCreatedBy(TblEmployee tblEmployeeByCreatedBy) {
        tblEmployeeByCreatedByProperty().set(tblEmployeeByCreatedBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByApprovedByProperty() {
        return this.tblEmployeeByApprovedBy;
    }

    public TblEmployee getTblEmployeeByApprovedBy() {
        return tblEmployeeByApprovedByProperty().get();
    }

    public void setTblEmployeeByApprovedBy(TblEmployee tblEmployeeByApprovedBy) {
        tblEmployeeByApprovedByProperty().set(tblEmployeeByApprovedBy);
    }

    public final ObjectProperty<TblFinanceData> tblFinanceDataProperty() {
        return this.tblFinanceData;
    }

    public TblFinanceData getTblFinanceData() {
        return tblFinanceDataProperty().get();
    }

    public void setTblFinanceData(TblFinanceData tblFinanceData) {
        tblFinanceDataProperty().set(tblFinanceData);
    }

    public final ObjectProperty<TblHotelReceivable> tblHotelReceivableProperty() {
        return this.tblHotelReceivable;
    }

    public TblHotelReceivable getTblHotelReceivable() {
        return tblHotelReceivableProperty().get();
    }

    public void setTblHotelReceivable(TblHotelReceivable tblHotelReceivable) {
        tblHotelReceivableProperty().set(tblHotelReceivable);
    }

    public final ObjectProperty<TblSupplier> tblSupplierProperty() {
        return this.tblSupplier;
    }

    public TblSupplier getTblSupplier() {
        return tblSupplierProperty().get();
    }

    public void setTblSupplier(TblSupplier tblSupplier) {
        tblSupplierProperty().set(tblSupplier);
    }

    public final StringProperty codeReturProperty() {
        return this.codeRetur;
    }

    public String getCodeRetur() {
        return codeReturProperty().get();
    }

    public void setCodeRetur(String codeRetur) {
        codeReturProperty().set(codeRetur);
    }

    public final ObjectProperty<Date> returDateProperty() {
        return this.returDate;
    }

    public Date getReturDate() {
        return returDateProperty().get();
    }

    public void setReturDate(Date returDate) {
        returDateProperty().set(returDate);
    }

    public final StringProperty deliveryNumberProperty() {
        return this.deliveryNumber;
    }

    public String getDeliveryNumber() {
        return deliveryNumberProperty().get();
    }

    public void setDeliveryNumber(String deliveryNumber) {
        deliveryNumberProperty().set(deliveryNumber);
    }

    public final ObjectProperty<BigDecimal> deliveryCostProperty() {
        return this.deliveryCost;
    }

    public BigDecimal getDeliveryCost() {
        return deliveryCostProperty().get();
    }

    public void setDeliveryCost(BigDecimal deliveryCost) {
        deliveryCostProperty().set(deliveryCost);
    }

    public final ObjectProperty<BigDecimal> taxPercentageProperty() {
        return this.taxPercentage;
    }

    public BigDecimal getTaxPercentage() {
        return taxPercentageProperty().get();
    }

    public void setTaxPercentage(BigDecimal taxPercentage) {
        taxPercentageProperty().set(taxPercentage);
    }

    public final ObjectProperty<Date> maxReturDateProperty() {
        return this.maxReturDate;
    }

    public Date getMaxReturDate() {
        return maxReturDateProperty().get();
    }

    public void setMaxReturDate(Date maxReturDate) {
        maxReturDateProperty().set(maxReturDate);
    }

    public final ObjectProperty<Date> maxReturPaymentDateProperty() {
        return this.maxReturPaymentDate;
    }

    public Date getMaxReturPaymentDate() {
        return maxReturPaymentDateProperty().get();
    }

    public void setMaxReturPaymentDate(Date maxReturPaymentDate) {
        maxReturPaymentDateProperty().set(maxReturPaymentDate);
    }

    public final BooleanProperty updateStockStatusProperty() {
        return this.updateStockStatus;
    }

    public Boolean getUpdateStockStatus() {
        return updateStockStatusProperty().get();
    }

    public void setUpdateStockStatus(Boolean updateStockStatus) {
        updateStockStatusProperty().set(updateStockStatus);
    }

    public final StringProperty returNoteProperty() {
        return this.returNote;
    }

    public String getReturNote() {
        return returNoteProperty().get();
    }

    public void setReturNote(String returNote) {
        returNoteProperty().set(returNote);
    }

    public final ObjectProperty<Date> createdDateProperty() {
        return this.createdDate;
    }

    public Date getCreatedDate() {
        return createdDateProperty().get();
    }

    public void setCreatedDate(Date createdDate) {
        createdDateProperty().set(createdDate);
    }

    public final ObjectProperty<Date> approvedDateProperty() {
        return this.approvedDate;
    }

    public Date getApprovedDate() {
        return approvedDateProperty().get();
    }

    public void setApprovedDate(Date approvedDate) {
        approvedDateProperty().set(approvedDate);
    }

    public final ObjectProperty<Date> canceledDateProperty() {
        return this.canceledDate;
    }

    public Date getCanceledDate() {
        return canceledDateProperty().get();
    }

    public void setCanceledDate(Date canceledDate) {
        canceledDateProperty().set(canceledDate);
    }

    public final StringProperty canceledNoteProperty() {
        return this.canceledNote;
    }

    public String getCanceledNote() {
        return canceledNoteProperty().get();
    }

    public void setCanceledNote(String canceledNote) {
        canceledNoteProperty().set(canceledNote);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

    public Set getTblPurchaseOrders() {
        return this.tblPurchaseOrders;
    }

    public void setTblPurchaseOrders(Set tblPurchaseOrders) {
        this.tblPurchaseOrders = tblPurchaseOrders;
    }

    public Set getTblReturDetails() {
        return this.tblReturDetails;
    }

    public void setTblReturDetails(Set tblReturDetails) {
        this.tblReturDetails = tblReturDetails;
    }
    
    @Override
    public String toString() {
        return getCodeRetur();
    }

}
