package hotelfx.persistence.model;
// Generated May 2, 2018 1:18:04 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

import javafx.beans.property.BooleanProperty;
import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleBooleanProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;

/**
 * TblRoomTypeItem generated by hbm2java
 */
public class TblRoomTypeItem implements java.io.Serializable {

    private final LongProperty idrelation;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblItem> tblItem;
    private final ObjectProperty<TblRoomType> tblRoomType;
    private final ObjectProperty<BigDecimal> itemQuantity;
    private final BooleanProperty addAsAdditionalItem;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    public TblRoomTypeItem() {
        this.idrelation = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblItem = new SimpleObjectProperty<>();
        this.tblRoomType = new SimpleObjectProperty<>();
        this.itemQuantity = new SimpleObjectProperty<>();
        this.addAsAdditionalItem = new SimpleBooleanProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

    }

    public TblRoomTypeItem(long idrelation) {
        this();
        idrelationProperty().set(idrelation);
    }

    public TblRoomTypeItem(long idrelation, RefRecordStatus refRecordStatus, TblEmployee tblEmployeeByLastUpdateBy, TblEmployee tblEmployeeByCreateBy, TblItem tblItem, TblRoomType tblRoomType, BigDecimal itemQuantity, Boolean addAsAdditionalItem, Date createDate, Date lastUpdateDate) {
        this();
        idrelationProperty().set(idrelation);
        refRecordStatusProperty().set(refRecordStatus);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblItemProperty().set(tblItem);
        tblRoomTypeProperty().set(tblRoomType);
        itemQuantityProperty().set(itemQuantity);
        addAsAdditionalItemProperty().set(addAsAdditionalItem);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

    }

    public TblRoomTypeItem(TblRoomTypeItem tblRoomTypeItem) {
        this();
        idrelationProperty().set(tblRoomTypeItem.getIdrelation());
        refRecordStatusProperty().set(tblRoomTypeItem.getRefRecordStatus());
        tblEmployeeByLastUpdateByProperty().set(tblRoomTypeItem.getTblEmployeeByLastUpdateBy());
        tblEmployeeByCreateByProperty().set(tblRoomTypeItem.getTblEmployeeByCreateBy());
        tblItemProperty().set(tblRoomTypeItem.getTblItem());
        tblRoomTypeProperty().set(tblRoomTypeItem.getTblRoomType());
        itemQuantityProperty().set(tblRoomTypeItem.getItemQuantity());
        addAsAdditionalItemProperty().set(tblRoomTypeItem.getAddAsAdditionalItem());
        createDateProperty().set(tblRoomTypeItem.getCreateDate());
        lastUpdateDateProperty().set(tblRoomTypeItem.getLastUpdateDate());

    }

    public final LongProperty idrelationProperty() {
        return this.idrelation;
    }

    public long getIdrelation() {
        return idrelationProperty().get();
    }

    public void setIdrelation(long idrelation) {
        idrelationProperty().set(idrelation);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblItem> tblItemProperty() {
        return this.tblItem;
    }

    public TblItem getTblItem() {
        return tblItemProperty().get();
    }

    public void setTblItem(TblItem tblItem) {
        tblItemProperty().set(tblItem);
    }

    public final ObjectProperty<TblRoomType> tblRoomTypeProperty() {
        return this.tblRoomType;
    }

    public TblRoomType getTblRoomType() {
        return tblRoomTypeProperty().get();
    }

    public void setTblRoomType(TblRoomType tblRoomType) {
        tblRoomTypeProperty().set(tblRoomType);
    }

    public final ObjectProperty<BigDecimal> itemQuantityProperty() {
        return this.itemQuantity;
    }

    public BigDecimal getItemQuantity() {
        return itemQuantityProperty().get();
    }

    public void setItemQuantity(BigDecimal itemQuantity) {
        itemQuantityProperty().set(itemQuantity);
    }

    public final BooleanProperty addAsAdditionalItemProperty() {
        return this.addAsAdditionalItem;
    }

    public Boolean getAddAsAdditionalItem() {
        return addAsAdditionalItemProperty().get();
    }

    public void setAddAsAdditionalItem(Boolean addAsAdditionalItem) {
        addAsAdditionalItemProperty().set(addAsAdditionalItem);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

}
