package hotelfx.persistence.model;
// Generated Aug 21, 2017 1:49:32 PM by Hibernate Tools 4.3.1

import java.util.Date;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;

/**
 * TblReservationBrokenItemPropertyBarcode generated by hbm2java
 */
public class TblReservationBrokenItemPropertyBarcode implements java.io.Serializable {

    private final LongProperty idbrokenDetail;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblPropertyBarcode> tblPropertyBarcode;
    private final ObjectProperty<TblReservationBrokenItem> tblReservationBrokenItem;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    public TblReservationBrokenItemPropertyBarcode() {
        this.idbrokenDetail = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblPropertyBarcode = new SimpleObjectProperty<>();
        this.tblReservationBrokenItem = new SimpleObjectProperty<>();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

    }

    public TblReservationBrokenItemPropertyBarcode(long idbrokenDetail) {
        this();
        idbrokenDetailProperty().set(idbrokenDetail);
    }

    public TblReservationBrokenItemPropertyBarcode(long idbrokenDetail, RefRecordStatus refRecordStatus, TblEmployee tblEmployeeByLastUpdateBy, TblEmployee tblEmployeeByCreateBy, TblPropertyBarcode tblPropertyBarcode, TblReservationBrokenItem tblReservationBrokenItem, Date createDate, Date lastUpdateDate) {
        this();
        idbrokenDetailProperty().set(idbrokenDetail);
        refRecordStatusProperty().set(refRecordStatus);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblPropertyBarcodeProperty().set(tblPropertyBarcode);
        tblReservationBrokenItemProperty().set(tblReservationBrokenItem);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

    }

    public TblReservationBrokenItemPropertyBarcode(TblReservationBrokenItemPropertyBarcode tblReservationBrokenItemPropertyBarcode) {
        this();
        idbrokenDetailProperty().set(tblReservationBrokenItemPropertyBarcode.getIdbrokenDetail());
        refRecordStatusProperty().set(tblReservationBrokenItemPropertyBarcode.getRefRecordStatus());
        tblEmployeeByLastUpdateByProperty().set(tblReservationBrokenItemPropertyBarcode.getTblEmployeeByLastUpdateBy());
        tblEmployeeByCreateByProperty().set(tblReservationBrokenItemPropertyBarcode.getTblEmployeeByCreateBy());
        tblPropertyBarcodeProperty().set(tblReservationBrokenItemPropertyBarcode.getTblPropertyBarcode());
        tblReservationBrokenItemProperty().set(tblReservationBrokenItemPropertyBarcode.getTblReservationBrokenItem());
        createDateProperty().set(tblReservationBrokenItemPropertyBarcode.getCreateDate());
        lastUpdateDateProperty().set(tblReservationBrokenItemPropertyBarcode.getLastUpdateDate());

    }

    public final LongProperty idbrokenDetailProperty() {
        return this.idbrokenDetail;
    }

    public long getIdbrokenDetail() {
        return idbrokenDetailProperty().get();
    }

    public void setIdbrokenDetail(long idbrokenDetail) {
        idbrokenDetailProperty().set(idbrokenDetail);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblPropertyBarcode> tblPropertyBarcodeProperty() {
        return this.tblPropertyBarcode;
    }

    public TblPropertyBarcode getTblPropertyBarcode() {
        return tblPropertyBarcodeProperty().get();
    }

    public void setTblPropertyBarcode(TblPropertyBarcode tblPropertyBarcode) {
        tblPropertyBarcodeProperty().set(tblPropertyBarcode);
    }

    public final ObjectProperty<TblReservationBrokenItem> tblReservationBrokenItemProperty() {
        return this.tblReservationBrokenItem;
    }

    public TblReservationBrokenItem getTblReservationBrokenItem() {
        return tblReservationBrokenItemProperty().get();
    }

    public void setTblReservationBrokenItem(TblReservationBrokenItem tblReservationBrokenItem) {
        tblReservationBrokenItemProperty().set(tblReservationBrokenItem);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

}
