package hotelfx.persistence.model;
// Generated Aug 31, 2017 2:12:52 PM by Hibernate Tools 4.3.1

import java.util.Date;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblReservationBreakfastVoucher generated by hbm2java
 */
public class TblReservationBreakfastVoucher implements java.io.Serializable {

    private final LongProperty idvoucher;
    private final ObjectProperty<RefEndOfDayDataStatus> refEndOfDayDataStatus;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<RefReservationFacilityType> refReservationFacilityType;
    private final ObjectProperty<RefVoucherStatus> refVoucherStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblReservationRoomTypeDetail> tblReservationRoomTypeDetail;
    private final StringProperty codeVoucher;
    private final ObjectProperty<Date> validStartDate;
    private final ObjectProperty<Date> validFinishDate;
    private final LongProperty voucherCost;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    public TblReservationBreakfastVoucher() {
        this.idvoucher = new SimpleLongProperty();
        this.refEndOfDayDataStatus = new SimpleObjectProperty<>();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.refReservationFacilityType = new SimpleObjectProperty<>();
        this.refVoucherStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblReservationRoomTypeDetail = new SimpleObjectProperty<>();
        this.codeVoucher = new SimpleStringProperty();
        this.validStartDate = new SimpleObjectProperty<>();
        this.validFinishDate = new SimpleObjectProperty<>();
        this.voucherCost = new SimpleLongProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

    }

    public TblReservationBreakfastVoucher(long idvoucher, TblReservationRoomTypeDetail tblReservationRoomTypeDetail) {
        this();
        idvoucherProperty().set(idvoucher);
        tblReservationRoomTypeDetailProperty().set(tblReservationRoomTypeDetail);
    }

    public TblReservationBreakfastVoucher(long idvoucher, RefEndOfDayDataStatus refEndOfDayDataStatus, RefRecordStatus refRecordStatus, RefReservationFacilityType refReservationFacilityType, RefVoucherStatus refVoucherStatus, TblEmployee tblEmployeeByLastUpdateBy, TblEmployee tblEmployeeByCreateBy, TblReservationRoomTypeDetail tblReservationRoomTypeDetail, String codeVoucher, Date validStartDate, Date validFinishDate, Long voucherCost, Date createDate, Date lastUpdateDate) {
        this();
        idvoucherProperty().set(idvoucher);
        refEndOfDayDataStatusProperty().set(refEndOfDayDataStatus);
        refRecordStatusProperty().set(refRecordStatus);
        refReservationFacilityTypeProperty().set(refReservationFacilityType);
        refVoucherStatusProperty().set(refVoucherStatus);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblReservationRoomTypeDetailProperty().set(tblReservationRoomTypeDetail);
        codeVoucherProperty().set(codeVoucher);
        validStartDateProperty().set(validStartDate);
        validFinishDateProperty().set(validFinishDate);
        voucherCostProperty().set(voucherCost);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

    }

    public TblReservationBreakfastVoucher(TblReservationBreakfastVoucher tblReservationBreakfastVoucher) {
        this();
        idvoucherProperty().set(tblReservationBreakfastVoucher.getIdvoucher());
        refEndOfDayDataStatusProperty().set(tblReservationBreakfastVoucher.getRefEndOfDayDataStatus());
        refRecordStatusProperty().set(tblReservationBreakfastVoucher.getRefRecordStatus());
        refReservationFacilityTypeProperty().set(tblReservationBreakfastVoucher.getRefReservationFacilityType());
        refVoucherStatusProperty().set(tblReservationBreakfastVoucher.getRefVoucherStatus());
        tblEmployeeByLastUpdateByProperty().set(tblReservationBreakfastVoucher.getTblEmployeeByLastUpdateBy());
        tblEmployeeByCreateByProperty().set(tblReservationBreakfastVoucher.getTblEmployeeByCreateBy());
        tblReservationRoomTypeDetailProperty().set(tblReservationBreakfastVoucher.getTblReservationRoomTypeDetail());
        codeVoucherProperty().set(tblReservationBreakfastVoucher.getCodeVoucher());
        validStartDateProperty().set(tblReservationBreakfastVoucher.getValidStartDate());
        validFinishDateProperty().set(tblReservationBreakfastVoucher.getValidFinishDate());
        voucherCostProperty().set(tblReservationBreakfastVoucher.getVoucherCost());
        createDateProperty().set(tblReservationBreakfastVoucher.getCreateDate());
        lastUpdateDateProperty().set(tblReservationBreakfastVoucher.getLastUpdateDate());

    }

    public final LongProperty idvoucherProperty() {
        return this.idvoucher;
    }

    public long getIdvoucher() {
        return idvoucherProperty().get();
    }

    public void setIdvoucher(long idvoucher) {
        idvoucherProperty().set(idvoucher);
    }

    public final ObjectProperty<RefEndOfDayDataStatus> refEndOfDayDataStatusProperty() {
        return this.refEndOfDayDataStatus;
    }

    public RefEndOfDayDataStatus getRefEndOfDayDataStatus() {
        return refEndOfDayDataStatusProperty().get();
    }

    public void setRefEndOfDayDataStatus(RefEndOfDayDataStatus refEndOfDayDataStatus) {
        refEndOfDayDataStatusProperty().set(refEndOfDayDataStatus);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<RefReservationFacilityType> refReservationFacilityTypeProperty() {
        return this.refReservationFacilityType;
    }

    public RefReservationFacilityType getRefReservationFacilityType() {
        return refReservationFacilityTypeProperty().get();
    }

    public void setRefReservationFacilityType(RefReservationFacilityType refReservationFacilityType) {
        refReservationFacilityTypeProperty().set(refReservationFacilityType);
    }

    public final ObjectProperty<RefVoucherStatus> refVoucherStatusProperty() {
        return this.refVoucherStatus;
    }

    public RefVoucherStatus getRefVoucherStatus() {
        return refVoucherStatusProperty().get();
    }

    public void setRefVoucherStatus(RefVoucherStatus refVoucherStatus) {
        refVoucherStatusProperty().set(refVoucherStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblReservationRoomTypeDetail> tblReservationRoomTypeDetailProperty() {
        return this.tblReservationRoomTypeDetail;
    }

    public TblReservationRoomTypeDetail getTblReservationRoomTypeDetail() {
        return tblReservationRoomTypeDetailProperty().get();
    }

    public void setTblReservationRoomTypeDetail(TblReservationRoomTypeDetail tblReservationRoomTypeDetail) {
        tblReservationRoomTypeDetailProperty().set(tblReservationRoomTypeDetail);
    }

    public final StringProperty codeVoucherProperty() {
        return this.codeVoucher;
    }

    public String getCodeVoucher() {
        return codeVoucherProperty().get();
    }

    public void setCodeVoucher(String codeVoucher) {
        codeVoucherProperty().set(codeVoucher);
    }

    public final ObjectProperty<Date> validStartDateProperty() {
        return this.validStartDate;
    }

    public Date getValidStartDate() {
        return validStartDateProperty().get();
    }

    public void setValidStartDate(Date validStartDate) {
        validStartDateProperty().set(validStartDate);
    }

    public final ObjectProperty<Date> validFinishDateProperty() {
        return this.validFinishDate;
    }

    public Date getValidFinishDate() {
        return validFinishDateProperty().get();
    }

    public void setValidFinishDate(Date validFinishDate) {
        validFinishDateProperty().set(validFinishDate);
    }

    public final LongProperty voucherCostProperty() {
        return this.voucherCost;
    }

    public Long getVoucherCost() {
        return voucherCostProperty().get();
    }

    public void setVoucherCost(Long voucherCost) {
        voucherCostProperty().set(voucherCost);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

}
