package hotelfx.persistence.model;
// Generated Sep 21, 2018 2:55:56 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;

/**
 * TblReturDetailItemExpiredDate generated by hbm2java
 */
public class TblReturDetailItemExpiredDate implements java.io.Serializable {

    private final LongProperty idrelation;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblItemExpiredDate> tblItemExpiredDate;
    private final ObjectProperty<TblReturDetail> tblReturDetail;
    private final ObjectProperty<BigDecimal> itemQuantity;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    public TblReturDetailItemExpiredDate() {
        this.idrelation = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblItemExpiredDate = new SimpleObjectProperty<>();
        this.tblReturDetail = new SimpleObjectProperty<>();
        this.itemQuantity = new SimpleObjectProperty<>();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

    }

    public TblReturDetailItemExpiredDate(long idrelation) {
        this();
        idrelationProperty().set(idrelation);
    }

    public TblReturDetailItemExpiredDate(long idrelation, RefRecordStatus refRecordStatus, TblEmployee tblEmployeeByLastUpdateBy, TblEmployee tblEmployeeByCreateBy, TblItemExpiredDate tblItemExpiredDate, TblReturDetail tblReturDetail, BigDecimal itemQuantity, Date createDate, Date lastUpdateDate) {
        this();
        idrelationProperty().set(idrelation);
        refRecordStatusProperty().set(refRecordStatus);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblItemExpiredDateProperty().set(tblItemExpiredDate);
        tblReturDetailProperty().set(tblReturDetail);
        itemQuantityProperty().set(itemQuantity);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

    }

    public TblReturDetailItemExpiredDate(TblReturDetailItemExpiredDate tblReturDetailItemExpiredDate) {
        this();
        idrelationProperty().set(tblReturDetailItemExpiredDate.getIdrelation());
        refRecordStatusProperty().set(tblReturDetailItemExpiredDate.getRefRecordStatus());
        tblEmployeeByLastUpdateByProperty().set(tblReturDetailItemExpiredDate.getTblEmployeeByLastUpdateBy());
        tblEmployeeByCreateByProperty().set(tblReturDetailItemExpiredDate.getTblEmployeeByCreateBy());
        tblItemExpiredDateProperty().set(tblReturDetailItemExpiredDate.getTblItemExpiredDate());
        tblReturDetailProperty().set(tblReturDetailItemExpiredDate.getTblReturDetail());
        itemQuantityProperty().set(tblReturDetailItemExpiredDate.getItemQuantity());
        createDateProperty().set(tblReturDetailItemExpiredDate.getCreateDate());
        lastUpdateDateProperty().set(tblReturDetailItemExpiredDate.getLastUpdateDate());

    }

    public final LongProperty idrelationProperty() {
        return this.idrelation;
    }

    public long getIdrelation() {
        return idrelationProperty().get();
    }

    public void setIdrelation(long idrelation) {
        idrelationProperty().set(idrelation);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblItemExpiredDate> tblItemExpiredDateProperty() {
        return this.tblItemExpiredDate;
    }

    public TblItemExpiredDate getTblItemExpiredDate() {
        return tblItemExpiredDateProperty().get();
    }

    public void setTblItemExpiredDate(TblItemExpiredDate tblItemExpiredDate) {
        tblItemExpiredDateProperty().set(tblItemExpiredDate);
    }

    public final ObjectProperty<TblReturDetail> tblReturDetailProperty() {
        return this.tblReturDetail;
    }

    public TblReturDetail getTblReturDetail() {
        return tblReturDetailProperty().get();
    }

    public void setTblReturDetail(TblReturDetail tblReturDetail) {
        tblReturDetailProperty().set(tblReturDetail);
    }

    public final ObjectProperty<BigDecimal> itemQuantityProperty() {
        return this.itemQuantity;
    }

    public BigDecimal getItemQuantity() {
        return itemQuantityProperty().get();
    }

    public void setItemQuantity(BigDecimal itemQuantity) {
        itemQuantityProperty().set(itemQuantity);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

}
