package hotelfx.persistence.model;
// Generated Aug 10, 2018 11:40:12 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;

/**
 * TblReservationRoomPriceDetail generated by hbm2java
 */
public class TblReservationRoomPriceDetail implements java.io.Serializable {

    private final LongProperty iddetail;
    private final ObjectProperty<RefEndOfDayDataStatus> refEndOfDayDataStatus;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblBankEventCard> tblBankEventCard;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblHotelEvent> tblHotelEvent;
    private final ObjectProperty<Date> detailDate;
    private final ObjectProperty<BigDecimal> detailPrice;
    private final ObjectProperty<BigDecimal> detailDiscountPercentage;
    private final ObjectProperty<BigDecimal> detailComplimentary;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    private Set tblReservationRoomTypeDetailRoomPriceDetails;

    public TblReservationRoomPriceDetail() {
        this.iddetail = new SimpleLongProperty();
        this.refEndOfDayDataStatus = new SimpleObjectProperty<>();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblBankEventCard = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblHotelEvent = new SimpleObjectProperty<>();
        this.detailDate = new SimpleObjectProperty<>();
        this.detailPrice = new SimpleObjectProperty<>();
        this.detailDiscountPercentage = new SimpleObjectProperty<>();
        this.detailComplimentary = new SimpleObjectProperty<>();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

        this.tblReservationRoomTypeDetailRoomPriceDetails = new HashSet(0);
    }

    public TblReservationRoomPriceDetail(long iddetail) {
        this();
        iddetailProperty().set(iddetail);
    }

    public TblReservationRoomPriceDetail(long iddetail, RefEndOfDayDataStatus refEndOfDayDataStatus, RefRecordStatus refRecordStatus, TblBankEventCard tblBankEventCard, TblEmployee tblEmployeeByLastUpdateBy, TblEmployee tblEmployeeByCreateBy, TblHotelEvent tblHotelEvent, Date detailDate, BigDecimal detailPrice, BigDecimal detailDiscountPercentage, BigDecimal detailComplimentary, Date createDate, Date lastUpdateDate, Set tblReservationRoomTypeDetailRoomPriceDetails) {
        this();
        iddetailProperty().set(iddetail);
        refEndOfDayDataStatusProperty().set(refEndOfDayDataStatus);
        refRecordStatusProperty().set(refRecordStatus);
        tblBankEventCardProperty().set(tblBankEventCard);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblHotelEventProperty().set(tblHotelEvent);
        detailDateProperty().set(detailDate);
        detailPriceProperty().set(detailPrice);
        detailDiscountPercentageProperty().set(detailDiscountPercentage);
        detailComplimentaryProperty().set(detailComplimentary);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

        this.tblReservationRoomTypeDetailRoomPriceDetails = tblReservationRoomTypeDetailRoomPriceDetails;
    }

    public TblReservationRoomPriceDetail(TblReservationRoomPriceDetail tblReservationRoomPriceDetail) {
        this();
        iddetailProperty().set(tblReservationRoomPriceDetail.getIddetail());
        refEndOfDayDataStatusProperty().set(tblReservationRoomPriceDetail.getRefEndOfDayDataStatus());
        refRecordStatusProperty().set(tblReservationRoomPriceDetail.getRefRecordStatus());
        tblBankEventCardProperty().set(tblReservationRoomPriceDetail.getTblBankEventCard());
        tblEmployeeByLastUpdateByProperty().set(tblReservationRoomPriceDetail.getTblEmployeeByLastUpdateBy());
        tblEmployeeByCreateByProperty().set(tblReservationRoomPriceDetail.getTblEmployeeByCreateBy());
        tblHotelEventProperty().set(tblReservationRoomPriceDetail.getTblHotelEvent());
        detailDateProperty().set(tblReservationRoomPriceDetail.getDetailDate());
        detailPriceProperty().set(tblReservationRoomPriceDetail.getDetailPrice());
        detailDiscountPercentageProperty().set(tblReservationRoomPriceDetail.getDetailDiscountPercentage());
        detailComplimentaryProperty().set(tblReservationRoomPriceDetail.getDetailComplimentary());
        createDateProperty().set(tblReservationRoomPriceDetail.getCreateDate());
        lastUpdateDateProperty().set(tblReservationRoomPriceDetail.getLastUpdateDate());

        this.tblReservationRoomTypeDetailRoomPriceDetails = tblReservationRoomPriceDetail.getTblReservationRoomTypeDetailRoomPriceDetails();
    }

    public final LongProperty iddetailProperty() {
        return this.iddetail;
    }

    public long getIddetail() {
        return iddetailProperty().get();
    }

    public void setIddetail(long iddetail) {
        iddetailProperty().set(iddetail);
    }

    public final ObjectProperty<RefEndOfDayDataStatus> refEndOfDayDataStatusProperty() {
        return this.refEndOfDayDataStatus;
    }

    public RefEndOfDayDataStatus getRefEndOfDayDataStatus() {
        return refEndOfDayDataStatusProperty().get();
    }

    public void setRefEndOfDayDataStatus(RefEndOfDayDataStatus refEndOfDayDataStatus) {
        refEndOfDayDataStatusProperty().set(refEndOfDayDataStatus);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblBankEventCard> tblBankEventCardProperty() {
        return this.tblBankEventCard;
    }

    public TblBankEventCard getTblBankEventCard() {
        return tblBankEventCardProperty().get();
    }

    public void setTblBankEventCard(TblBankEventCard tblBankEventCard) {
        tblBankEventCardProperty().set(tblBankEventCard);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblHotelEvent> tblHotelEventProperty() {
        return this.tblHotelEvent;
    }

    public TblHotelEvent getTblHotelEvent() {
        return tblHotelEventProperty().get();
    }

    public void setTblHotelEvent(TblHotelEvent tblHotelEvent) {
        tblHotelEventProperty().set(tblHotelEvent);
    }

    public final ObjectProperty<Date> detailDateProperty() {
        return this.detailDate;
    }

    public Date getDetailDate() {
        return detailDateProperty().get();
    }

    public void setDetailDate(Date detailDate) {
        detailDateProperty().set(detailDate);
    }

    public final ObjectProperty<BigDecimal> detailPriceProperty() {
        return this.detailPrice;
    }

    public BigDecimal getDetailPrice() {
        return detailPriceProperty().get();
    }

    public void setDetailPrice(BigDecimal detailPrice) {
        detailPriceProperty().set(detailPrice);
    }

    public final ObjectProperty<BigDecimal> detailDiscountPercentageProperty() {
        return this.detailDiscountPercentage;
    }

    public BigDecimal getDetailDiscountPercentage() {
        return detailDiscountPercentageProperty().get();
    }

    public void setDetailDiscountPercentage(BigDecimal detailDiscountPercentage) {
        detailDiscountPercentageProperty().set(detailDiscountPercentage);
    }

    public final ObjectProperty<BigDecimal> detailComplimentaryProperty() {
        return this.detailComplimentary;
    }

    public BigDecimal getDetailComplimentary() {
        return detailComplimentaryProperty().get();
    }

    public void setDetailComplimentary(BigDecimal detailComplimentary) {
        detailComplimentaryProperty().set(detailComplimentary);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

    public Set getTblReservationRoomTypeDetailRoomPriceDetails() {
        return this.tblReservationRoomTypeDetailRoomPriceDetails;
    }

    public void setTblReservationRoomTypeDetailRoomPriceDetails(Set tblReservationRoomTypeDetailRoomPriceDetails) {
        this.tblReservationRoomTypeDetailRoomPriceDetails = tblReservationRoomTypeDetailRoomPriceDetails;
    }

}
