package hotelfx.persistence.model;
// Generated Aug 21, 2017 1:49:32 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblReservationBar generated by hbm2java
 */
public class TblReservationBar implements java.io.Serializable {

    private final LongProperty idbar;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final StringProperty codeBar;
    private final StringProperty barname;
    private final ObjectProperty<BigDecimal> barpercentage;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    private Set tblReservationDefaultBars;
    private Set tblReservationCalendarBars;

    public TblReservationBar() {
        this.idbar = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.codeBar = new SimpleStringProperty();
        this.barname = new SimpleStringProperty();
        this.barpercentage = new SimpleObjectProperty<>();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

        this.tblReservationDefaultBars = new HashSet(0);
        this.tblReservationCalendarBars = new HashSet(0);
    }

    public TblReservationBar(long idbar) {
        this();
        idbarProperty().set(idbar);
    }

    public TblReservationBar(long idbar, RefRecordStatus refRecordStatus, TblEmployee tblEmployeeByLastUpdateBy, TblEmployee tblEmployeeByCreateBy, String codeBar, String barname, BigDecimal barpercentage, Date createDate, Date lastUpdateDate, Set tblReservationDefaultBars, Set tblReservationCalendarBars) {
        this();
        idbarProperty().set(idbar);
        refRecordStatusProperty().set(refRecordStatus);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        codeBarProperty().set(codeBar);
        barnameProperty().set(barname);
        barpercentageProperty().set(barpercentage);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

        this.tblReservationDefaultBars = tblReservationDefaultBars;
        this.tblReservationCalendarBars = tblReservationCalendarBars;
    }

    public TblReservationBar(TblReservationBar tblReservationBar) {
        this();
        idbarProperty().set(tblReservationBar.getIdbar());
        refRecordStatusProperty().set(tblReservationBar.getRefRecordStatus());
        tblEmployeeByLastUpdateByProperty().set(tblReservationBar.getTblEmployeeByLastUpdateBy());
        tblEmployeeByCreateByProperty().set(tblReservationBar.getTblEmployeeByCreateBy());
        codeBarProperty().set(tblReservationBar.getCodeBar());
        barnameProperty().set(tblReservationBar.getBarname());
        barpercentageProperty().set(tblReservationBar.getBarpercentage());
        createDateProperty().set(tblReservationBar.getCreateDate());
        lastUpdateDateProperty().set(tblReservationBar.getLastUpdateDate());

        this.tblReservationDefaultBars = tblReservationBar.getTblReservationDefaultBars();
        this.tblReservationCalendarBars = tblReservationBar.getTblReservationCalendarBars();
    }

    public final LongProperty idbarProperty() {
        return this.idbar;
    }

    public long getIdbar() {
        return idbarProperty().get();
    }

    public void setIdbar(long idbar) {
        idbarProperty().set(idbar);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final StringProperty codeBarProperty() {
        return this.codeBar;
    }

    public String getCodeBar() {
        return codeBarProperty().get();
    }

    public void setCodeBar(String codeBar) {
        codeBarProperty().set(codeBar);
    }

    public final StringProperty barnameProperty() {
        return this.barname;
    }

    public String getBarname() {
        return barnameProperty().get();
    }

    public void setBarname(String barname) {
        barnameProperty().set(barname);
    }

    public final ObjectProperty<BigDecimal> barpercentageProperty() {
        return this.barpercentage;
    }

    public BigDecimal getBarpercentage() {
        return barpercentageProperty().get();
    }

    public void setBarpercentage(BigDecimal barpercentage) {
        barpercentageProperty().set(barpercentage);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

    public Set getTblReservationDefaultBars() {
        return this.tblReservationDefaultBars;
    }

    public void setTblReservationDefaultBars(Set tblReservationDefaultBars) {
        this.tblReservationDefaultBars = tblReservationDefaultBars;
    }

    public Set getTblReservationCalendarBars() {
        return this.tblReservationCalendarBars;
    }

    public void setTblReservationCalendarBars(Set tblReservationCalendarBars) {
        this.tblReservationCalendarBars = tblReservationCalendarBars;
    }

    @Override
    public String toString() {
        return getBarname();
    }

}
