package hotelfx.persistence.model;
// Generated Sep 25, 2017 8:58:22 AM by Hibernate Tools 4.3.1

import java.util.Date;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;

/**
 * TblReservationRoomTypeDetailTravelAgentDiscountDetail generated by hbm2java
 */
public class TblReservationRoomTypeDetailTravelAgentDiscountDetail implements java.io.Serializable {

    private final LongProperty idrelation;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblReservationRoomTypeDetail> tblReservationRoomTypeDetail;
    private final ObjectProperty<TblReservationTravelAgentDiscountDetail> tblReservationTravelAgentDiscountDetail;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    public TblReservationRoomTypeDetailTravelAgentDiscountDetail() {
        this.idrelation = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblReservationRoomTypeDetail = new SimpleObjectProperty<>();
        this.tblReservationTravelAgentDiscountDetail = new SimpleObjectProperty<>();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

    }

    public TblReservationRoomTypeDetailTravelAgentDiscountDetail(long idrelation) {
        this();
        idrelationProperty().set(idrelation);
    }

    public TblReservationRoomTypeDetailTravelAgentDiscountDetail(long idrelation, RefRecordStatus refRecordStatus, TblEmployee tblEmployeeByCreateBy, TblEmployee tblEmployeeByLastUpdateBy, TblReservationRoomTypeDetail tblReservationRoomTypeDetail, TblReservationTravelAgentDiscountDetail tblReservationTravelAgentDiscountDetail, Date createDate, Date lastUpdateDate) {
        this();
        idrelationProperty().set(idrelation);
        refRecordStatusProperty().set(refRecordStatus);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblReservationRoomTypeDetailProperty().set(tblReservationRoomTypeDetail);
        tblReservationTravelAgentDiscountDetailProperty().set(tblReservationTravelAgentDiscountDetail);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

    }

    public TblReservationRoomTypeDetailTravelAgentDiscountDetail(TblReservationRoomTypeDetailTravelAgentDiscountDetail tblReservationRoomTypeDetailTravelAgentDiscountDetail) {
        this();
        idrelationProperty().set(tblReservationRoomTypeDetailTravelAgentDiscountDetail.getIdrelation());
        refRecordStatusProperty().set(tblReservationRoomTypeDetailTravelAgentDiscountDetail.getRefRecordStatus());
        tblEmployeeByCreateByProperty().set(tblReservationRoomTypeDetailTravelAgentDiscountDetail.getTblEmployeeByCreateBy());
        tblEmployeeByLastUpdateByProperty().set(tblReservationRoomTypeDetailTravelAgentDiscountDetail.getTblEmployeeByLastUpdateBy());
        tblReservationRoomTypeDetailProperty().set(tblReservationRoomTypeDetailTravelAgentDiscountDetail.getTblReservationRoomTypeDetail());
        tblReservationTravelAgentDiscountDetailProperty().set(tblReservationRoomTypeDetailTravelAgentDiscountDetail.getTblReservationTravelAgentDiscountDetail());
        createDateProperty().set(tblReservationRoomTypeDetailTravelAgentDiscountDetail.getCreateDate());
        lastUpdateDateProperty().set(tblReservationRoomTypeDetailTravelAgentDiscountDetail.getLastUpdateDate());

    }

    public final LongProperty idrelationProperty() {
        return this.idrelation;
    }

    public long getIdrelation() {
        return idrelationProperty().get();
    }

    public void setIdrelation(long idrelation) {
        idrelationProperty().set(idrelation);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblReservationRoomTypeDetail> tblReservationRoomTypeDetailProperty() {
        return this.tblReservationRoomTypeDetail;
    }

    public TblReservationRoomTypeDetail getTblReservationRoomTypeDetail() {
        return tblReservationRoomTypeDetailProperty().get();
    }

    public void setTblReservationRoomTypeDetail(TblReservationRoomTypeDetail tblReservationRoomTypeDetail) {
        tblReservationRoomTypeDetailProperty().set(tblReservationRoomTypeDetail);
    }

    public final ObjectProperty<TblReservationTravelAgentDiscountDetail> tblReservationTravelAgentDiscountDetailProperty() {
        return this.tblReservationTravelAgentDiscountDetail;
    }

    public TblReservationTravelAgentDiscountDetail getTblReservationTravelAgentDiscountDetail() {
        return tblReservationTravelAgentDiscountDetailProperty().get();
    }

    public void setTblReservationTravelAgentDiscountDetail(TblReservationTravelAgentDiscountDetail tblReservationTravelAgentDiscountDetail) {
        tblReservationTravelAgentDiscountDetailProperty().set(tblReservationTravelAgentDiscountDetail);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

}
