package hotelfx.persistence.model;
// Generated Oct 2, 2018 10:07:19 AM by Hibernate Tools 4.3.1

import java.util.Date;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblStockOpnameDetailItemExpiredDate generated by hbm2java
 */
public class TblStockOpnameDetailItemExpiredDate implements java.io.Serializable {

    private final LongProperty idrelation;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblItemExpiredDate> tblItemExpiredDate;
    private final ObjectProperty<TblStockOpnameDetail> tblStockOpnameDetail;
    private final StringProperty detailNote;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    public TblStockOpnameDetailItemExpiredDate() {
        this.idrelation = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblItemExpiredDate = new SimpleObjectProperty<>();
        this.tblStockOpnameDetail = new SimpleObjectProperty<>();
        this.detailNote = new SimpleStringProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

    }

    public TblStockOpnameDetailItemExpiredDate(long idrelation) {
        this();
        idrelationProperty().set(idrelation);
    }

    public TblStockOpnameDetailItemExpiredDate(long idrelation, RefRecordStatus refRecordStatus, TblEmployee tblEmployeeByLastUpdateBy, TblEmployee tblEmployeeByCreateBy, TblItemExpiredDate tblItemExpiredDate, TblStockOpnameDetail tblStockOpnameDetail, String detailNote, Date createDate, Date lastUpdateDate) {
        this();
        idrelationProperty().set(idrelation);
        refRecordStatusProperty().set(refRecordStatus);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblItemExpiredDateProperty().set(tblItemExpiredDate);
        tblStockOpnameDetailProperty().set(tblStockOpnameDetail);
        detailNoteProperty().set(detailNote);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

    }

    public TblStockOpnameDetailItemExpiredDate(TblStockOpnameDetailItemExpiredDate tblStockOpnameDetailItemExpiredDate) {
        this();
        idrelationProperty().set(tblStockOpnameDetailItemExpiredDate.getIdrelation());
        refRecordStatusProperty().set(tblStockOpnameDetailItemExpiredDate.getRefRecordStatus());
        tblEmployeeByLastUpdateByProperty().set(tblStockOpnameDetailItemExpiredDate.getTblEmployeeByLastUpdateBy());
        tblEmployeeByCreateByProperty().set(tblStockOpnameDetailItemExpiredDate.getTblEmployeeByCreateBy());
        tblItemExpiredDateProperty().set(tblStockOpnameDetailItemExpiredDate.getTblItemExpiredDate());
        tblStockOpnameDetailProperty().set(tblStockOpnameDetailItemExpiredDate.getTblStockOpnameDetail());
        detailNoteProperty().set(tblStockOpnameDetailItemExpiredDate.getDetailNote());
        createDateProperty().set(tblStockOpnameDetailItemExpiredDate.getCreateDate());
        lastUpdateDateProperty().set(tblStockOpnameDetailItemExpiredDate.getLastUpdateDate());

    }

    public final LongProperty idrelationProperty() {
        return this.idrelation;
    }

    public long getIdrelation() {
        return idrelationProperty().get();
    }

    public void setIdrelation(long idrelation) {
        idrelationProperty().set(idrelation);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblItemExpiredDate> tblItemExpiredDateProperty() {
        return this.tblItemExpiredDate;
    }

    public TblItemExpiredDate getTblItemExpiredDate() {
        return tblItemExpiredDateProperty().get();
    }

    public void setTblItemExpiredDate(TblItemExpiredDate tblItemExpiredDate) {
        tblItemExpiredDateProperty().set(tblItemExpiredDate);
    }

    public final ObjectProperty<TblStockOpnameDetail> tblStockOpnameDetailProperty() {
        return this.tblStockOpnameDetail;
    }

    public TblStockOpnameDetail getTblStockOpnameDetail() {
        return tblStockOpnameDetailProperty().get();
    }

    public void setTblStockOpnameDetail(TblStockOpnameDetail tblStockOpnameDetail) {
        tblStockOpnameDetailProperty().set(tblStockOpnameDetail);
    }

    public final StringProperty detailNoteProperty() {
        return this.detailNote;
    }

    public String getDetailNote() {
        return detailNoteProperty().get();
    }

    public void setDetailNote(String detailNote) {
        detailNoteProperty().set(detailNote);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

}
