package hotelfx.persistence.model;
// Generated Apr 4, 2018 1:25:55 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblSystemUser generated by hbm2java
 */
public class TblSystemUser implements java.io.Serializable {

    private final LongProperty iduser;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<RefSystemUserLockStatus> refSystemUserLockStatus;
    private final ObjectProperty<RefSystemUserLoginStatus> refSystemUserLoginStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByIdemployee;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblSystemRole> tblSystemRole;
    private final StringProperty codeUser;
    private final StringProperty userPassword;
    private final StringProperty userUrlImage;
    private final StringProperty userGuid;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    private Set logSystems;
    private Set tblSystemLogBooks;

    public TblSystemUser() {
        this.iduser = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.refSystemUserLockStatus = new SimpleObjectProperty<>();
        this.refSystemUserLoginStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByIdemployee = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblSystemRole = new SimpleObjectProperty<>();
        this.codeUser = new SimpleStringProperty();
        this.userPassword = new SimpleStringProperty();
        this.userUrlImage = new SimpleStringProperty();
        this.userGuid = new SimpleStringProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

        this.logSystems = new HashSet(0);
        this.tblSystemLogBooks = new HashSet(0);
    }

    public TblSystemUser(long iduser) {
        this();
        iduserProperty().set(iduser);
    }

    public TblSystemUser(long iduser, RefRecordStatus refRecordStatus, RefSystemUserLockStatus refSystemUserLockStatus, RefSystemUserLoginStatus refSystemUserLoginStatus, TblEmployee tblEmployeeByCreateBy, TblEmployee tblEmployeeByIdemployee, TblEmployee tblEmployeeByLastUpdateBy, TblSystemRole tblSystemRole, String codeUser, String userPassword, String userUrlImage, String userGuid, Date createDate, Date lastUpdateDate, Set logSystems, Set tblSystemLogBooks) {
        this();
        iduserProperty().set(iduser);
        refRecordStatusProperty().set(refRecordStatus);
        refSystemUserLockStatusProperty().set(refSystemUserLockStatus);
        refSystemUserLoginStatusProperty().set(refSystemUserLoginStatus);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblEmployeeByIdemployeeProperty().set(tblEmployeeByIdemployee);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblSystemRoleProperty().set(tblSystemRole);
        codeUserProperty().set(codeUser);
        userPasswordProperty().set(userPassword);
        userUrlImageProperty().set(userUrlImage);
        userGuidProperty().set(userGuid);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

        this.logSystems = logSystems;
        this.tblSystemLogBooks = tblSystemLogBooks;
    }

    public TblSystemUser(TblSystemUser tblSystemUser) {
        this();
        iduserProperty().set(tblSystemUser.getIduser());
        refRecordStatusProperty().set(tblSystemUser.getRefRecordStatus());
        refSystemUserLockStatusProperty().set(tblSystemUser.getRefSystemUserLockStatus());
        refSystemUserLoginStatusProperty().set(tblSystemUser.getRefSystemUserLoginStatus());
        tblEmployeeByCreateByProperty().set(tblSystemUser.getTblEmployeeByCreateBy());
        tblEmployeeByIdemployeeProperty().set(tblSystemUser.getTblEmployeeByIdemployee());
        tblEmployeeByLastUpdateByProperty().set(tblSystemUser.getTblEmployeeByLastUpdateBy());
        tblSystemRoleProperty().set(tblSystemUser.getTblSystemRole());
        codeUserProperty().set(tblSystemUser.getCodeUser());
        userPasswordProperty().set(tblSystemUser.getUserPassword());
        userUrlImageProperty().set(tblSystemUser.getUserUrlImage());
        userGuidProperty().set(tblSystemUser.getUserGuid());
        createDateProperty().set(tblSystemUser.getCreateDate());
        lastUpdateDateProperty().set(tblSystemUser.getLastUpdateDate());

        this.logSystems = tblSystemUser.getLogSystems();
        this.tblSystemLogBooks = tblSystemUser.getTblSystemLogBooks();
    }

    public final LongProperty iduserProperty() {
        return this.iduser;
    }

    public long getIduser() {
        return iduserProperty().get();
    }

    public void setIduser(long iduser) {
        iduserProperty().set(iduser);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<RefSystemUserLockStatus> refSystemUserLockStatusProperty() {
        return this.refSystemUserLockStatus;
    }

    public RefSystemUserLockStatus getRefSystemUserLockStatus() {
        return refSystemUserLockStatusProperty().get();
    }

    public void setRefSystemUserLockStatus(RefSystemUserLockStatus refSystemUserLockStatus) {
        refSystemUserLockStatusProperty().set(refSystemUserLockStatus);
    }

    public final ObjectProperty<RefSystemUserLoginStatus> refSystemUserLoginStatusProperty() {
        return this.refSystemUserLoginStatus;
    }

    public RefSystemUserLoginStatus getRefSystemUserLoginStatus() {
        return refSystemUserLoginStatusProperty().get();
    }

    public void setRefSystemUserLoginStatus(RefSystemUserLoginStatus refSystemUserLoginStatus) {
        refSystemUserLoginStatusProperty().set(refSystemUserLoginStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByIdemployeeProperty() {
        return this.tblEmployeeByIdemployee;
    }

    public TblEmployee getTblEmployeeByIdemployee() {
        return tblEmployeeByIdemployeeProperty().get();
    }

    public void setTblEmployeeByIdemployee(TblEmployee tblEmployeeByIdemployee) {
        tblEmployeeByIdemployeeProperty().set(tblEmployeeByIdemployee);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblSystemRole> tblSystemRoleProperty() {
        return this.tblSystemRole;
    }

    public TblSystemRole getTblSystemRole() {
        return tblSystemRoleProperty().get();
    }

    public void setTblSystemRole(TblSystemRole tblSystemRole) {
        tblSystemRoleProperty().set(tblSystemRole);
    }

    public final StringProperty codeUserProperty() {
        return this.codeUser;
    }

    public String getCodeUser() {
        return codeUserProperty().get();
    }

    public void setCodeUser(String codeUser) {
        codeUserProperty().set(codeUser);
    }

    public final StringProperty userPasswordProperty() {
        return this.userPassword;
    }

    public String getUserPassword() {
        return userPasswordProperty().get();
    }

    public void setUserPassword(String userPassword) {
        userPasswordProperty().set(userPassword);
    }

    public final StringProperty userUrlImageProperty() {
        return this.userUrlImage;
    }

    public String getUserUrlImage() {
        return userUrlImageProperty().get();
    }

    public void setUserUrlImage(String userUrlImage) {
        userUrlImageProperty().set(userUrlImage);
    }

    public final StringProperty userGuidProperty() {
        return this.userGuid;
    }

    public String getUserGuid() {
        return userGuidProperty().get();
    }

    public void setUserGuid(String userGuid) {
        userGuidProperty().set(userGuid);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

    public Set getLogSystems() {
        return this.logSystems;
    }

    public void setLogSystems(Set logSystems) {
        this.logSystems = logSystems;
    }

    public Set getTblSystemLogBooks() {
        return this.tblSystemLogBooks;
    }

    public void setTblSystemLogBooks(Set tblSystemLogBooks) {
        this.tblSystemLogBooks = tblSystemLogBooks;
    }

    @Override
    public String toString() {
        return getCodeUser();
    }
    
}
