package hotelfx.persistence.model;
// Generated Oct 5, 2018 4:27:54 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblStoreRequest generated by hbm2java
 */
public class TblStoreRequest implements java.io.Serializable {

    private final LongProperty idsr;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<RefStoreRequestStatus> refStoreRequestStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByApprovedBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByCanceledBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByReceivedBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreatedBy;
    private final ObjectProperty<TblLocation> tblLocationByIdlocationSource;
    private final ObjectProperty<TblLocation> tblLocationByIdlocationDestination;
    private final StringProperty codeSr;
    private final ObjectProperty<Date> srdate;
    private final ObjectProperty<Date> createdDate;
    private final ObjectProperty<Date> approvedDate;
    private final ObjectProperty<Date> receivedDate;
    private final ObjectProperty<Date> canceledDate;
    private final StringProperty srnote;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    private Set tblStoreRequestDetails;
    private Set tblOutGoings;

    public TblStoreRequest() {
        this.idsr = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.refStoreRequestStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByApprovedBy = new SimpleObjectProperty<>();
        this.tblEmployeeByCanceledBy = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByReceivedBy = new SimpleObjectProperty<>();
        this.tblEmployeeByCreatedBy = new SimpleObjectProperty<>();
        this.tblLocationByIdlocationSource = new SimpleObjectProperty<>();
        this.tblLocationByIdlocationDestination = new SimpleObjectProperty<>();
        this.codeSr = new SimpleStringProperty();
        this.srdate = new SimpleObjectProperty<>();
        this.createdDate = new SimpleObjectProperty<>();
        this.approvedDate = new SimpleObjectProperty<>();
        this.receivedDate = new SimpleObjectProperty<>();
        this.canceledDate = new SimpleObjectProperty<>();
        this.srnote = new SimpleStringProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

        this.tblStoreRequestDetails = new HashSet(0);
        this.tblOutGoings = new HashSet(0);
    }

    public TblStoreRequest(long idsr) {
        this();
        idsrProperty().set(idsr);
    }

    public TblStoreRequest(long idsr, RefRecordStatus refRecordStatus, RefStoreRequestStatus refStoreRequestStatus, TblEmployee tblEmployeeByApprovedBy, TblEmployee tblEmployeeByCanceledBy, TblEmployee tblEmployeeByCreateBy, TblEmployee tblEmployeeByLastUpdateBy, TblEmployee tblEmployeeByReceivedBy, TblEmployee tblEmployeeByCreatedBy, TblLocation tblLocationByIdlocationSource, TblLocation tblLocationByIdlocationDestination, String codeSr, Date srdate, Date createdDate, Date approvedDate, Date receivedDate, Date canceledDate, String srnote, Date createDate, Date lastUpdateDate, Set tblStoreRequestDetails, Set tblOutGoings) {
        this();
        idsrProperty().set(idsr);
        refRecordStatusProperty().set(refRecordStatus);
        refStoreRequestStatusProperty().set(refStoreRequestStatus);
        tblEmployeeByApprovedByProperty().set(tblEmployeeByApprovedBy);
        tblEmployeeByCanceledByProperty().set(tblEmployeeByCanceledBy);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblEmployeeByReceivedByProperty().set(tblEmployeeByReceivedBy);
        tblEmployeeByCreatedByProperty().set(tblEmployeeByCreatedBy);
        tblLocationByIdlocationSourceProperty().set(tblLocationByIdlocationSource);
        tblLocationByIdlocationDestinationProperty().set(tblLocationByIdlocationDestination);
        codeSrProperty().set(codeSr);
        srdateProperty().set(srdate);
        createdDateProperty().set(createdDate);
        approvedDateProperty().set(approvedDate);
        receivedDateProperty().set(receivedDate);
        canceledDateProperty().set(canceledDate);
        srnoteProperty().set(srnote);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

        this.tblStoreRequestDetails = tblStoreRequestDetails;
        this.tblOutGoings = tblOutGoings;
    }

    public TblStoreRequest(TblStoreRequest tblStoreRequest) {
        this();
        idsrProperty().set(tblStoreRequest.getIdsr());
        refRecordStatusProperty().set(tblStoreRequest.getRefRecordStatus());
        refStoreRequestStatusProperty().set(tblStoreRequest.getRefStoreRequestStatus());
        tblEmployeeByApprovedByProperty().set(tblStoreRequest.getTblEmployeeByApprovedBy());
        tblEmployeeByCanceledByProperty().set(tblStoreRequest.getTblEmployeeByCanceledBy());
        tblEmployeeByCreateByProperty().set(tblStoreRequest.getTblEmployeeByCreateBy());
        tblEmployeeByLastUpdateByProperty().set(tblStoreRequest.getTblEmployeeByLastUpdateBy());
        tblEmployeeByReceivedByProperty().set(tblStoreRequest.getTblEmployeeByReceivedBy());
        tblEmployeeByCreatedByProperty().set(tblStoreRequest.getTblEmployeeByCreatedBy());
        tblLocationByIdlocationSourceProperty().set(tblStoreRequest.getTblLocationByIdlocationSource());
        tblLocationByIdlocationDestinationProperty().set(tblStoreRequest.getTblLocationByIdlocationDestination());
        codeSrProperty().set(tblStoreRequest.getCodeSr());
        srdateProperty().set(tblStoreRequest.getSrdate());
        createdDateProperty().set(tblStoreRequest.getCreatedDate());
        approvedDateProperty().set(tblStoreRequest.getApprovedDate());
        receivedDateProperty().set(tblStoreRequest.getReceivedDate());
        canceledDateProperty().set(tblStoreRequest.getCanceledDate());
        srnoteProperty().set(tblStoreRequest.getSrnote());
        createDateProperty().set(tblStoreRequest.getCreateDate());
        lastUpdateDateProperty().set(tblStoreRequest.getLastUpdateDate());

        this.tblStoreRequestDetails = tblStoreRequest.getTblStoreRequestDetails();
        this.tblOutGoings = tblStoreRequest.getTblOutGoings();
    }

    public final LongProperty idsrProperty() {
        return this.idsr;
    }

    public long getIdsr() {
        return idsrProperty().get();
    }

    public void setIdsr(long idsr) {
        idsrProperty().set(idsr);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<RefStoreRequestStatus> refStoreRequestStatusProperty() {
        return this.refStoreRequestStatus;
    }

    public RefStoreRequestStatus getRefStoreRequestStatus() {
        return refStoreRequestStatusProperty().get();
    }

    public void setRefStoreRequestStatus(RefStoreRequestStatus refStoreRequestStatus) {
        refStoreRequestStatusProperty().set(refStoreRequestStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByApprovedByProperty() {
        return this.tblEmployeeByApprovedBy;
    }

    public TblEmployee getTblEmployeeByApprovedBy() {
        return tblEmployeeByApprovedByProperty().get();
    }

    public void setTblEmployeeByApprovedBy(TblEmployee tblEmployeeByApprovedBy) {
        tblEmployeeByApprovedByProperty().set(tblEmployeeByApprovedBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCanceledByProperty() {
        return this.tblEmployeeByCanceledBy;
    }

    public TblEmployee getTblEmployeeByCanceledBy() {
        return tblEmployeeByCanceledByProperty().get();
    }

    public void setTblEmployeeByCanceledBy(TblEmployee tblEmployeeByCanceledBy) {
        tblEmployeeByCanceledByProperty().set(tblEmployeeByCanceledBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByReceivedByProperty() {
        return this.tblEmployeeByReceivedBy;
    }

    public TblEmployee getTblEmployeeByReceivedBy() {
        return tblEmployeeByReceivedByProperty().get();
    }

    public void setTblEmployeeByReceivedBy(TblEmployee tblEmployeeByReceivedBy) {
        tblEmployeeByReceivedByProperty().set(tblEmployeeByReceivedBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreatedByProperty() {
        return this.tblEmployeeByCreatedBy;
    }

    public TblEmployee getTblEmployeeByCreatedBy() {
        return tblEmployeeByCreatedByProperty().get();
    }

    public void setTblEmployeeByCreatedBy(TblEmployee tblEmployeeByCreatedBy) {
        tblEmployeeByCreatedByProperty().set(tblEmployeeByCreatedBy);
    }

    public final ObjectProperty<TblLocation> tblLocationByIdlocationSourceProperty() {
        return this.tblLocationByIdlocationSource;
    }

    public TblLocation getTblLocationByIdlocationSource() {
        return tblLocationByIdlocationSourceProperty().get();
    }

    public void setTblLocationByIdlocationSource(TblLocation tblLocationByIdlocationSource) {
        tblLocationByIdlocationSourceProperty().set(tblLocationByIdlocationSource);
    }

    public final ObjectProperty<TblLocation> tblLocationByIdlocationDestinationProperty() {
        return this.tblLocationByIdlocationDestination;
    }

    public TblLocation getTblLocationByIdlocationDestination() {
        return tblLocationByIdlocationDestinationProperty().get();
    }

    public void setTblLocationByIdlocationDestination(TblLocation tblLocationByIdlocationDestination) {
        tblLocationByIdlocationDestinationProperty().set(tblLocationByIdlocationDestination);
    }

    public final StringProperty codeSrProperty() {
        return this.codeSr;
    }

    public String getCodeSr() {
        return codeSrProperty().get();
    }

    public void setCodeSr(String codeSr) {
        codeSrProperty().set(codeSr);
    }

    public final ObjectProperty<Date> srdateProperty() {
        return this.srdate;
    }

    public Date getSrdate() {
        return srdateProperty().get();
    }

    public void setSrdate(Date srdate) {
        srdateProperty().set(srdate);
    }

    public final ObjectProperty<Date> createdDateProperty() {
        return this.createdDate;
    }

    public Date getCreatedDate() {
        return createdDateProperty().get();
    }

    public void setCreatedDate(Date createdDate) {
        createdDateProperty().set(createdDate);
    }

    public final ObjectProperty<Date> approvedDateProperty() {
        return this.approvedDate;
    }

    public Date getApprovedDate() {
        return approvedDateProperty().get();
    }

    public void setApprovedDate(Date approvedDate) {
        approvedDateProperty().set(approvedDate);
    }

    public final ObjectProperty<Date> receivedDateProperty() {
        return this.receivedDate;
    }

    public Date getReceivedDate() {
        return receivedDateProperty().get();
    }

    public void setReceivedDate(Date receivedDate) {
        receivedDateProperty().set(receivedDate);
    }

    public final ObjectProperty<Date> canceledDateProperty() {
        return this.canceledDate;
    }

    public Date getCanceledDate() {
        return canceledDateProperty().get();
    }

    public void setCanceledDate(Date canceledDate) {
        canceledDateProperty().set(canceledDate);
    }

    public final StringProperty srnoteProperty() {
        return this.srnote;
    }

    public String getSrnote() {
        return srnoteProperty().get();
    }

    public void setSrnote(String srnote) {
        srnoteProperty().set(srnote);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

    public Set getTblStoreRequestDetails() {
        return this.tblStoreRequestDetails;
    }

    public void setTblStoreRequestDetails(Set tblStoreRequestDetails) {
        this.tblStoreRequestDetails = tblStoreRequestDetails;
    }

    public Set getTblOutGoings() {
        return this.tblOutGoings;
    }

    public void setTblOutGoings(Set tblOutGoings) {
        this.tblOutGoings = tblOutGoings;
    }

    @Override
    public String toString() {
        return getCodeSr();
    }
    
}
