package hotelfx.persistence.model;
// Generated Aug 21, 2017 1:49:32 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblSystemRole generated by hbm2java
 */
public class TblSystemRole implements java.io.Serializable {

    private final LongProperty idrole;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final StringProperty codeRole;
    private final StringProperty roleName;
    private final StringProperty roleNote;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    private Set tblSystemUsers;
    private Set tblSystemRoleSystemFeatures;

    public TblSystemRole() {
        this.idrole = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.codeRole = new SimpleStringProperty();
        this.roleName = new SimpleStringProperty();
        this.roleNote = new SimpleStringProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

        this.tblSystemUsers = new HashSet(0);
        this.tblSystemRoleSystemFeatures = new HashSet(0);
    }

    public TblSystemRole(long idrole, String roleName) {
        this();
        idroleProperty().set(idrole);
        roleNameProperty().set(roleName);
    }

    public TblSystemRole(long idrole, RefRecordStatus refRecordStatus, TblEmployee tblEmployeeByCreateBy, TblEmployee tblEmployeeByLastUpdateBy, String codeRole, String roleName, String roleNote, Date createDate, Date lastUpdateDate, Set tblSystemUsers, Set tblSystemRoleSystemFeatures) {
        this();
        idroleProperty().set(idrole);
        refRecordStatusProperty().set(refRecordStatus);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        codeRoleProperty().set(codeRole);
        roleNameProperty().set(roleName);
        roleNoteProperty().set(roleNote);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

        this.tblSystemUsers = tblSystemUsers;
        this.tblSystemRoleSystemFeatures = tblSystemRoleSystemFeatures;
    }

    public TblSystemRole(TblSystemRole tblSystemRole) {
        this();
        idroleProperty().set(tblSystemRole.getIdrole());
        refRecordStatusProperty().set(tblSystemRole.getRefRecordStatus());
        tblEmployeeByCreateByProperty().set(tblSystemRole.getTblEmployeeByCreateBy());
        tblEmployeeByLastUpdateByProperty().set(tblSystemRole.getTblEmployeeByLastUpdateBy());
        codeRoleProperty().set(tblSystemRole.getCodeRole());
        roleNameProperty().set(tblSystemRole.getRoleName());
        roleNoteProperty().set(tblSystemRole.getRoleNote());
        createDateProperty().set(tblSystemRole.getCreateDate());
        lastUpdateDateProperty().set(tblSystemRole.getLastUpdateDate());

        this.tblSystemUsers = tblSystemRole.getTblSystemUsers();
        this.tblSystemRoleSystemFeatures = tblSystemRole.getTblSystemRoleSystemFeatures();
    }

    public final LongProperty idroleProperty() {
        return this.idrole;
    }

    public long getIdrole() {
        return idroleProperty().get();
    }

    public void setIdrole(long idrole) {
        idroleProperty().set(idrole);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final StringProperty codeRoleProperty() {
        return this.codeRole;
    }

    public String getCodeRole() {
        return codeRoleProperty().get();
    }

    public void setCodeRole(String codeRole) {
        codeRoleProperty().set(codeRole);
    }

    public final StringProperty roleNameProperty() {
        return this.roleName;
    }

    public String getRoleName() {
        return roleNameProperty().get();
    }

    public void setRoleName(String roleName) {
        roleNameProperty().set(roleName);
    }

    public final StringProperty roleNoteProperty() {
        return this.roleNote;
    }

    public String getRoleNote() {
        return roleNoteProperty().get();
    }

    public void setRoleNote(String roleNote) {
        roleNoteProperty().set(roleNote);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

    public Set getTblSystemUsers() {
        return this.tblSystemUsers;
    }

    public void setTblSystemUsers(Set tblSystemUsers) {
        this.tblSystemUsers = tblSystemUsers;
    }

    public Set getTblSystemRoleSystemFeatures() {
        return this.tblSystemRoleSystemFeatures;
    }

    public void setTblSystemRoleSystemFeatures(Set tblSystemRoleSystemFeatures) {
        this.tblSystemRoleSystemFeatures = tblSystemRoleSystemFeatures;
    }

    @Override
    public String toString() {
        return getRoleName();
    }

}
