package hotelfx.persistence.model;
// Generated Aug 21, 2017 1:49:32 PM by Hibernate Tools 4.3.1

import java.util.Date;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblSupplierBankAccount generated by hbm2java
 */
public class TblSupplierBankAccount implements java.io.Serializable {

    private final LongProperty idrelation;
    private final ObjectProperty<RefBankAccountHolderStatus> refBankAccountHolderStatus;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblBankAccount> tblBankAccount;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblSupplier> tblSupplier;
    private final StringProperty supplierBankAccountNote;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    public TblSupplierBankAccount() {
        this.idrelation = new SimpleLongProperty();
        this.refBankAccountHolderStatus = new SimpleObjectProperty<>();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblBankAccount = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblSupplier = new SimpleObjectProperty<>();
        this.supplierBankAccountNote = new SimpleStringProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

    }

    public TblSupplierBankAccount(long idrelation) {
        this();
        idrelationProperty().set(idrelation);
    }

    public TblSupplierBankAccount(long idrelation, RefBankAccountHolderStatus refBankAccountHolderStatus, RefRecordStatus refRecordStatus, TblBankAccount tblBankAccount, TblEmployee tblEmployeeByCreateBy, TblEmployee tblEmployeeByLastUpdateBy, TblSupplier tblSupplier, String supplierBankAccountNote, Date createDate, Date lastUpdateDate) {
        this();
        idrelationProperty().set(idrelation);
        refBankAccountHolderStatusProperty().set(refBankAccountHolderStatus);
        refRecordStatusProperty().set(refRecordStatus);
        tblBankAccountProperty().set(tblBankAccount);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblSupplierProperty().set(tblSupplier);
        supplierBankAccountNoteProperty().set(supplierBankAccountNote);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

    }

    public TblSupplierBankAccount(TblSupplierBankAccount tblSupplierBankAccount) {
        this();
        idrelationProperty().set(tblSupplierBankAccount.getIdrelation());
        refBankAccountHolderStatusProperty().set(tblSupplierBankAccount.getRefBankAccountHolderStatus());
        refRecordStatusProperty().set(tblSupplierBankAccount.getRefRecordStatus());
        tblBankAccountProperty().set(tblSupplierBankAccount.getTblBankAccount());
        tblEmployeeByCreateByProperty().set(tblSupplierBankAccount.getTblEmployeeByCreateBy());
        tblEmployeeByLastUpdateByProperty().set(tblSupplierBankAccount.getTblEmployeeByLastUpdateBy());
        tblSupplierProperty().set(tblSupplierBankAccount.getTblSupplier());
        supplierBankAccountNoteProperty().set(tblSupplierBankAccount.getSupplierBankAccountNote());
        createDateProperty().set(tblSupplierBankAccount.getCreateDate());
        lastUpdateDateProperty().set(tblSupplierBankAccount.getLastUpdateDate());

    }

    public final LongProperty idrelationProperty() {
        return this.idrelation;
    }

    public long getIdrelation() {
        return idrelationProperty().get();
    }

    public void setIdrelation(long idrelation) {
        idrelationProperty().set(idrelation);
    }

    public final ObjectProperty<RefBankAccountHolderStatus> refBankAccountHolderStatusProperty() {
        return this.refBankAccountHolderStatus;
    }

    public RefBankAccountHolderStatus getRefBankAccountHolderStatus() {
        return refBankAccountHolderStatusProperty().get();
    }

    public void setRefBankAccountHolderStatus(RefBankAccountHolderStatus refBankAccountHolderStatus) {
        refBankAccountHolderStatusProperty().set(refBankAccountHolderStatus);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblBankAccount> tblBankAccountProperty() {
        return this.tblBankAccount;
    }

    public TblBankAccount getTblBankAccount() {
        return tblBankAccountProperty().get();
    }

    public void setTblBankAccount(TblBankAccount tblBankAccount) {
        tblBankAccountProperty().set(tblBankAccount);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblSupplier> tblSupplierProperty() {
        return this.tblSupplier;
    }

    public TblSupplier getTblSupplier() {
        return tblSupplierProperty().get();
    }

    public void setTblSupplier(TblSupplier tblSupplier) {
        tblSupplierProperty().set(tblSupplier);
    }

    public final StringProperty supplierBankAccountNoteProperty() {
        return this.supplierBankAccountNote;
    }

    public String getSupplierBankAccountNote() {
        return supplierBankAccountNoteProperty().get();
    }

    public void setSupplierBankAccountNote(String supplierBankAccountNote) {
        supplierBankAccountNoteProperty().set(supplierBankAccountNote);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

}
