package hotelfx.persistence.model;
// Generated Apr 6, 2018 9:44:05 AM by Hibernate Tools 4.3.1

import java.util.Date;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblSystemLogBookJob generated by hbm2java
 */
public class TblSystemLogBookJob implements java.io.Serializable {

    private final LongProperty idrelation;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblJob> tblJob;
    private final ObjectProperty<TblSystemLogBook> tblSystemLogBook;
    private final StringProperty relationNote;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    public TblSystemLogBookJob() {
        this.idrelation = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblJob = new SimpleObjectProperty<>();
        this.tblSystemLogBook = new SimpleObjectProperty<>();
        this.relationNote = new SimpleStringProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

    }

    public TblSystemLogBookJob(long idrelation) {
        this();
        idrelationProperty().set(idrelation);
    }

    public TblSystemLogBookJob(long idrelation, RefRecordStatus refRecordStatus, TblEmployee tblEmployeeByCreateBy, TblEmployee tblEmployeeByLastUpdateBy, TblJob tblJob, TblSystemLogBook tblSystemLogBook, String relationNote, Date createDate, Date lastUpdateDate) {
        this();
        idrelationProperty().set(idrelation);
        refRecordStatusProperty().set(refRecordStatus);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblJobProperty().set(tblJob);
        tblSystemLogBookProperty().set(tblSystemLogBook);
        relationNoteProperty().set(relationNote);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

    }

    public TblSystemLogBookJob(TblSystemLogBookJob tblSystemLogBookJob) {
        this();
        idrelationProperty().set(tblSystemLogBookJob.getIdrelation());
        refRecordStatusProperty().set(tblSystemLogBookJob.getRefRecordStatus());
        tblEmployeeByCreateByProperty().set(tblSystemLogBookJob.getTblEmployeeByCreateBy());
        tblEmployeeByLastUpdateByProperty().set(tblSystemLogBookJob.getTblEmployeeByLastUpdateBy());
        tblJobProperty().set(tblSystemLogBookJob.getTblJob());
        tblSystemLogBookProperty().set(tblSystemLogBookJob.getTblSystemLogBook());
        relationNoteProperty().set(tblSystemLogBookJob.getRelationNote());
        createDateProperty().set(tblSystemLogBookJob.getCreateDate());
        lastUpdateDateProperty().set(tblSystemLogBookJob.getLastUpdateDate());

    }

    public final LongProperty idrelationProperty() {
        return this.idrelation;
    }

    public long getIdrelation() {
        return idrelationProperty().get();
    }

    public void setIdrelation(long idrelation) {
        idrelationProperty().set(idrelation);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblJob> tblJobProperty() {
        return this.tblJob;
    }

    public TblJob getTblJob() {
        return tblJobProperty().get();
    }

    public void setTblJob(TblJob tblJob) {
        tblJobProperty().set(tblJob);
    }

    public final ObjectProperty<TblSystemLogBook> tblSystemLogBookProperty() {
        return this.tblSystemLogBook;
    }

    public TblSystemLogBook getTblSystemLogBook() {
        return tblSystemLogBookProperty().get();
    }

    public void setTblSystemLogBook(TblSystemLogBook tblSystemLogBook) {
        tblSystemLogBookProperty().set(tblSystemLogBook);
    }

    public final StringProperty relationNoteProperty() {
        return this.relationNote;
    }

    public String getRelationNote() {
        return relationNoteProperty().get();
    }

    public void setRelationNote(String relationNote) {
        relationNoteProperty().set(relationNote);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

}
