package hotelfx.persistence.model;
// Generated Nov 10, 2018 10:51:23 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblStockOpnameDetail generated by hbm2java
 */
public class TblStockOpnameDetail implements java.io.Serializable {

    private final LongProperty iddetail;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblItem> tblItem;
    private final ObjectProperty<TblItemExpiredDate> tblItemExpiredDate;
    private final ObjectProperty<TblPropertyBarcode> tblPropertyBarcode;
    private final ObjectProperty<TblStockOpname> tblStockOpname;
    private final ObjectProperty<BigDecimal> itemQuantitySystem;
    private final ObjectProperty<BigDecimal> itemQuantityReal;
    private final StringProperty detailNote;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    private Set tblStockOpnameDetailItemExpiredDates;
    private Set tblStockOpnameDetailPropertyBarcodes;

    public TblStockOpnameDetail() {
        this.iddetail = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblItem = new SimpleObjectProperty<>();
        this.tblItemExpiredDate = new SimpleObjectProperty<>();
        this.tblPropertyBarcode = new SimpleObjectProperty<>();
        this.tblStockOpname = new SimpleObjectProperty<>();
        this.itemQuantitySystem = new SimpleObjectProperty<>();
        this.itemQuantityReal = new SimpleObjectProperty<>();
        this.detailNote = new SimpleStringProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

        this.tblStockOpnameDetailItemExpiredDates = new HashSet(0);
        this.tblStockOpnameDetailPropertyBarcodes = new HashSet(0);
    }

    public TblStockOpnameDetail(long iddetail) {
        this();
        iddetailProperty().set(iddetail);
    }

    public TblStockOpnameDetail(long iddetail, RefRecordStatus refRecordStatus, TblEmployee tblEmployeeByCreateBy, TblEmployee tblEmployeeByLastUpdateBy, TblItem tblItem, TblItemExpiredDate tblItemExpiredDate, TblPropertyBarcode tblPropertyBarcode, TblStockOpname tblStockOpname, BigDecimal itemQuantitySystem, BigDecimal itemQuantityReal, String detailNote, Date createDate, Date lastUpdateDate, Set tblStockOpnameDetailItemExpiredDates, Set tblStockOpnameDetailPropertyBarcodes) {
        this();
        iddetailProperty().set(iddetail);
        refRecordStatusProperty().set(refRecordStatus);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblItemProperty().set(tblItem);
        tblItemExpiredDateProperty().set(tblItemExpiredDate);
        tblPropertyBarcodeProperty().set(tblPropertyBarcode);
        tblStockOpnameProperty().set(tblStockOpname);
        itemQuantitySystemProperty().set(itemQuantitySystem);
        itemQuantityRealProperty().set(itemQuantityReal);
        detailNoteProperty().set(detailNote);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

        this.tblStockOpnameDetailItemExpiredDates = tblStockOpnameDetailItemExpiredDates;
        this.tblStockOpnameDetailPropertyBarcodes = tblStockOpnameDetailPropertyBarcodes;
    }

    public TblStockOpnameDetail(TblStockOpnameDetail tblStockOpnameDetail) {
        this();
        iddetailProperty().set(tblStockOpnameDetail.getIddetail());
        refRecordStatusProperty().set(tblStockOpnameDetail.getRefRecordStatus());
        tblEmployeeByCreateByProperty().set(tblStockOpnameDetail.getTblEmployeeByCreateBy());
        tblEmployeeByLastUpdateByProperty().set(tblStockOpnameDetail.getTblEmployeeByLastUpdateBy());
        tblItemProperty().set(tblStockOpnameDetail.getTblItem());
        tblItemExpiredDateProperty().set(tblStockOpnameDetail.getTblItemExpiredDate());
        tblPropertyBarcodeProperty().set(tblStockOpnameDetail.getTblPropertyBarcode());
        tblStockOpnameProperty().set(tblStockOpnameDetail.getTblStockOpname());
        itemQuantitySystemProperty().set(tblStockOpnameDetail.getItemQuantitySystem());
        itemQuantityRealProperty().set(tblStockOpnameDetail.getItemQuantityReal());
        detailNoteProperty().set(tblStockOpnameDetail.getDetailNote());
        createDateProperty().set(tblStockOpnameDetail.getCreateDate());
        lastUpdateDateProperty().set(tblStockOpnameDetail.getLastUpdateDate());

        this.tblStockOpnameDetailItemExpiredDates = tblStockOpnameDetail.getTblStockOpnameDetailItemExpiredDates();
        this.tblStockOpnameDetailPropertyBarcodes = tblStockOpnameDetail.getTblStockOpnameDetailPropertyBarcodes();
    }

    public final LongProperty iddetailProperty() {
        return this.iddetail;
    }

    public long getIddetail() {
        return iddetailProperty().get();
    }

    public void setIddetail(long iddetail) {
        iddetailProperty().set(iddetail);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblItem> tblItemProperty() {
        return this.tblItem;
    }

    public TblItem getTblItem() {
        return tblItemProperty().get();
    }

    public void setTblItem(TblItem tblItem) {
        tblItemProperty().set(tblItem);
    }

    public final ObjectProperty<TblItemExpiredDate> tblItemExpiredDateProperty() {
        return this.tblItemExpiredDate;
    }

    public TblItemExpiredDate getTblItemExpiredDate() {
        return tblItemExpiredDateProperty().get();
    }

    public void setTblItemExpiredDate(TblItemExpiredDate tblItemExpiredDate) {
        tblItemExpiredDateProperty().set(tblItemExpiredDate);
    }

    public final ObjectProperty<TblPropertyBarcode> tblPropertyBarcodeProperty() {
        return this.tblPropertyBarcode;
    }

    public TblPropertyBarcode getTblPropertyBarcode() {
        return tblPropertyBarcodeProperty().get();
    }

    public void setTblPropertyBarcode(TblPropertyBarcode tblPropertyBarcode) {
        tblPropertyBarcodeProperty().set(tblPropertyBarcode);
    }

    public final ObjectProperty<TblStockOpname> tblStockOpnameProperty() {
        return this.tblStockOpname;
    }

    public TblStockOpname getTblStockOpname() {
        return tblStockOpnameProperty().get();
    }

    public void setTblStockOpname(TblStockOpname tblStockOpname) {
        tblStockOpnameProperty().set(tblStockOpname);
    }

    public final ObjectProperty<BigDecimal> itemQuantitySystemProperty() {
        return this.itemQuantitySystem;
    }

    public BigDecimal getItemQuantitySystem() {
        return itemQuantitySystemProperty().get();
    }

    public void setItemQuantitySystem(BigDecimal itemQuantitySystem) {
        itemQuantitySystemProperty().set(itemQuantitySystem);
    }

    public final ObjectProperty<BigDecimal> itemQuantityRealProperty() {
        return this.itemQuantityReal;
    }

    public BigDecimal getItemQuantityReal() {
        return itemQuantityRealProperty().get();
    }

    public void setItemQuantityReal(BigDecimal itemQuantityReal) {
        itemQuantityRealProperty().set(itemQuantityReal);
    }

    public final StringProperty detailNoteProperty() {
        return this.detailNote;
    }

    public String getDetailNote() {
        return detailNoteProperty().get();
    }

    public void setDetailNote(String detailNote) {
        detailNoteProperty().set(detailNote);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

    public Set getTblStockOpnameDetailItemExpiredDates() {
        return this.tblStockOpnameDetailItemExpiredDates;
    }

    public void setTblStockOpnameDetailItemExpiredDates(Set tblStockOpnameDetailItemExpiredDates) {
        this.tblStockOpnameDetailItemExpiredDates = tblStockOpnameDetailItemExpiredDates;
    }

    public Set getTblStockOpnameDetailPropertyBarcodes() {
        return this.tblStockOpnameDetailPropertyBarcodes;
    }

    public void setTblStockOpnameDetailPropertyBarcodes(Set tblStockOpnameDetailPropertyBarcodes) {
        this.tblStockOpnameDetailPropertyBarcodes = tblStockOpnameDetailPropertyBarcodes;
    }

}
