package hotelfx.persistence.model;
// Generated Aug 21, 2017 1:49:32 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblServiceCharge generated by hbm2java
 */
public class TblServiceCharge implements java.io.Serializable {

    private final LongProperty idserviceCharge;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final StringProperty codeServiceCharge;
    private final StringProperty serviceName;
    private final ObjectProperty<BigDecimal> serviceChargePercentage;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    public TblServiceCharge() {
        this.idserviceCharge = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.codeServiceCharge = new SimpleStringProperty();
        this.serviceName = new SimpleStringProperty();
        this.serviceChargePercentage = new SimpleObjectProperty<>();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

    }

    public TblServiceCharge(long idserviceCharge) {
        this();
        idserviceChargeProperty().set(idserviceCharge);
    }

    public TblServiceCharge(long idserviceCharge, RefRecordStatus refRecordStatus, TblEmployee tblEmployeeByLastUpdateBy, TblEmployee tblEmployeeByCreateBy, String codeServiceCharge, String serviceName, BigDecimal serviceChargePercentage, Date createDate, Date lastUpdateDate) {
        this();
        idserviceChargeProperty().set(idserviceCharge);
        refRecordStatusProperty().set(refRecordStatus);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        codeServiceChargeProperty().set(codeServiceCharge);
        serviceNameProperty().set(serviceName);
        serviceChargePercentageProperty().set(serviceChargePercentage);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

    }

    public TblServiceCharge(TblServiceCharge tblServiceCharge) {
        this();
        idserviceChargeProperty().set(tblServiceCharge.getIdserviceCharge());
        refRecordStatusProperty().set(tblServiceCharge.getRefRecordStatus());
        tblEmployeeByLastUpdateByProperty().set(tblServiceCharge.getTblEmployeeByLastUpdateBy());
        tblEmployeeByCreateByProperty().set(tblServiceCharge.getTblEmployeeByCreateBy());
        codeServiceChargeProperty().set(tblServiceCharge.getCodeServiceCharge());
        serviceNameProperty().set(tblServiceCharge.getServiceName());
        serviceChargePercentageProperty().set(tblServiceCharge.getServiceChargePercentage());
        createDateProperty().set(tblServiceCharge.getCreateDate());
        lastUpdateDateProperty().set(tblServiceCharge.getLastUpdateDate());

    }

    public final LongProperty idserviceChargeProperty() {
        return this.idserviceCharge;
    }

    public long getIdserviceCharge() {
        return idserviceChargeProperty().get();
    }

    public void setIdserviceCharge(long idserviceCharge) {
        idserviceChargeProperty().set(idserviceCharge);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final StringProperty codeServiceChargeProperty() {
        return this.codeServiceCharge;
    }

    public String getCodeServiceCharge() {
        return codeServiceChargeProperty().get();
    }

    public void setCodeServiceCharge(String codeServiceCharge) {
        codeServiceChargeProperty().set(codeServiceCharge);
    }

    public final StringProperty serviceNameProperty() {
        return this.serviceName;
    }

    public String getServiceName() {
        return serviceNameProperty().get();
    }

    public void setServiceName(String serviceName) {
        serviceNameProperty().set(serviceName);
    }

    public final ObjectProperty<BigDecimal> serviceChargePercentageProperty() {
        return this.serviceChargePercentage;
    }

    public BigDecimal getServiceChargePercentage() {
        return serviceChargePercentageProperty().get();
    }

    public void setServiceChargePercentage(BigDecimal serviceChargePercentage) {
        serviceChargePercentageProperty().set(serviceChargePercentage);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

}
