package hotelfx.persistence.model;
// Generated Jul 3, 2018 12:53:45 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblSupplierItem generated by hbm2java
 */
public class TblSupplierItem implements java.io.Serializable {

    private final LongProperty idrelation;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblItem> tblItem;
    private final ObjectProperty<TblSupplier> tblSupplier;
    private final StringProperty supllierItemCode;
    private final StringProperty supplierItemName;
    private final ObjectProperty<BigDecimal> itemCost;
    private final StringProperty note;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    private Set tblPurchaseOrderDetails;
    private Set tblMemorandumInvoiceDetails;
    private Set tblReturDetails;

    public TblSupplierItem() {
        this.idrelation = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblItem = new SimpleObjectProperty<>();
        this.tblSupplier = new SimpleObjectProperty<>();
        this.supllierItemCode = new SimpleStringProperty();
        this.supplierItemName = new SimpleStringProperty();
        this.itemCost = new SimpleObjectProperty<>();
        this.note = new SimpleStringProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

        this.tblPurchaseOrderDetails = new HashSet(0);
        this.tblMemorandumInvoiceDetails = new HashSet(0);
        this.tblReturDetails = new HashSet(0);
    }

    public TblSupplierItem(long idrelation) {
        this();
        idrelationProperty().set(idrelation);
    }

    public TblSupplierItem(long idrelation, RefRecordStatus refRecordStatus, TblEmployee tblEmployeeByLastUpdateBy, TblEmployee tblEmployeeByCreateBy, TblItem tblItem, TblSupplier tblSupplier, String supllierItemCode, String supplierItemName, BigDecimal itemCost, String note, Date createDate, Date lastUpdateDate, Set tblPurchaseOrderDetails, Set tblMemorandumInvoiceDetails, Set tblReturDetails) {
        this();
        idrelationProperty().set(idrelation);
        refRecordStatusProperty().set(refRecordStatus);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblItemProperty().set(tblItem);
        tblSupplierProperty().set(tblSupplier);
        supllierItemCodeProperty().set(supllierItemCode);
        supplierItemNameProperty().set(supplierItemName);
        itemCostProperty().set(itemCost);
        noteProperty().set(note);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

        this.tblPurchaseOrderDetails = tblPurchaseOrderDetails;
        this.tblMemorandumInvoiceDetails = tblMemorandumInvoiceDetails;
        this.tblReturDetails = tblReturDetails;
    }

    public TblSupplierItem(TblSupplierItem tblSupplierItem) {
        this();
        idrelationProperty().set(tblSupplierItem.getIdrelation());
        refRecordStatusProperty().set(tblSupplierItem.getRefRecordStatus());
        tblEmployeeByLastUpdateByProperty().set(tblSupplierItem.getTblEmployeeByLastUpdateBy());
        tblEmployeeByCreateByProperty().set(tblSupplierItem.getTblEmployeeByCreateBy());
        tblItemProperty().set(tblSupplierItem.getTblItem());
        tblSupplierProperty().set(tblSupplierItem.getTblSupplier());
        supllierItemCodeProperty().set(tblSupplierItem.getSupllierItemCode());
        supplierItemNameProperty().set(tblSupplierItem.getSupplierItemName());
        itemCostProperty().set(tblSupplierItem.getItemCost());
        noteProperty().set(tblSupplierItem.getNote());
        createDateProperty().set(tblSupplierItem.getCreateDate());
        lastUpdateDateProperty().set(tblSupplierItem.getLastUpdateDate());

        this.tblPurchaseOrderDetails = tblSupplierItem.getTblPurchaseOrderDetails();
        this.tblMemorandumInvoiceDetails = tblSupplierItem.getTblMemorandumInvoiceDetails();
        this.tblReturDetails = tblSupplierItem.getTblReturDetails();
    }

    public final LongProperty idrelationProperty() {
        return this.idrelation;
    }

    public long getIdrelation() {
        return idrelationProperty().get();
    }

    public void setIdrelation(long idrelation) {
        idrelationProperty().set(idrelation);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblItem> tblItemProperty() {
        return this.tblItem;
    }

    public TblItem getTblItem() {
        return tblItemProperty().get();
    }

    public void setTblItem(TblItem tblItem) {
        tblItemProperty().set(tblItem);
    }

    public final ObjectProperty<TblSupplier> tblSupplierProperty() {
        return this.tblSupplier;
    }

    public TblSupplier getTblSupplier() {
        return tblSupplierProperty().get();
    }

    public void setTblSupplier(TblSupplier tblSupplier) {
        tblSupplierProperty().set(tblSupplier);
    }

    public final StringProperty supllierItemCodeProperty() {
        return this.supllierItemCode;
    }

    public String getSupllierItemCode() {
        return supllierItemCodeProperty().get();
    }

    public void setSupllierItemCode(String supllierItemCode) {
        supllierItemCodeProperty().set(supllierItemCode);
    }

    public final StringProperty supplierItemNameProperty() {
        return this.supplierItemName;
    }

    public String getSupplierItemName() {
        return supplierItemNameProperty().get();
    }

    public void setSupplierItemName(String supplierItemName) {
        supplierItemNameProperty().set(supplierItemName);
    }

    public final ObjectProperty<BigDecimal> itemCostProperty() {
        return this.itemCost;
    }

    public BigDecimal getItemCost() {
        return itemCostProperty().get();
    }

    public void setItemCost(BigDecimal itemCost) {
        itemCostProperty().set(itemCost);
    }

    public final StringProperty noteProperty() {
        return this.note;
    }

    public String getNote() {
        return noteProperty().get();
    }

    public void setNote(String note) {
        noteProperty().set(note);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

    public Set getTblPurchaseOrderDetails() {
        return this.tblPurchaseOrderDetails;
    }

    public void setTblPurchaseOrderDetails(Set tblPurchaseOrderDetails) {
        this.tblPurchaseOrderDetails = tblPurchaseOrderDetails;
    }

    public Set getTblMemorandumInvoiceDetails() {
        return this.tblMemorandumInvoiceDetails;
    }

    public void setTblMemorandumInvoiceDetails(Set tblMemorandumInvoiceDetails) {
        this.tblMemorandumInvoiceDetails = tblMemorandumInvoiceDetails;
    }

    public Set getTblReturDetails() {
        return this.tblReturDetails;
    }

    public void setTblReturDetails(Set tblReturDetails) {
        this.tblReturDetails = tblReturDetails;
    }

}
