package hotelfx.persistence.model;
// Generated Apr 28, 2018 9:53:55 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblStockOpname generated by hbm2java
 */
public class TblStockOpname implements java.io.Serializable {

    private final LongProperty idstockOpname;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<SysAccount> sysAccount;
    private final ObjectProperty<TblEmployee> tblEmployeeByIdemployee;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblLocation> tblLocation;
    private final StringProperty codeStockOpname;
    private final ObjectProperty<Date> stockOpanameDate;
    private final StringProperty stockOpnameNote;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    private Set tblStockOpnameDetails;

    public TblStockOpname() {
        this.idstockOpname = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.sysAccount = new SimpleObjectProperty<>();
        this.tblEmployeeByIdemployee = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblLocation = new SimpleObjectProperty<>();
        this.codeStockOpname = new SimpleStringProperty();
        this.stockOpanameDate = new SimpleObjectProperty<>();
        this.stockOpnameNote = new SimpleStringProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

        this.tblStockOpnameDetails = new HashSet(0);
    }

    public TblStockOpname(long idstockOpname) {
        this();
        idstockOpnameProperty().set(idstockOpname);
    }

    public TblStockOpname(long idstockOpname, RefRecordStatus refRecordStatus, SysAccount sysAccount, TblEmployee tblEmployeeByIdemployee, TblEmployee tblEmployeeByCreateBy, TblEmployee tblEmployeeByLastUpdateBy, TblLocation tblLocation, String codeStockOpname, Date stockOpanameDate, String stockOpnameNote, Date createDate, Date lastUpdateDate, Set tblStockOpnameDetails) {
        this();
        idstockOpnameProperty().set(idstockOpname);
        refRecordStatusProperty().set(refRecordStatus);
        sysAccountProperty().set(sysAccount);
        tblEmployeeByIdemployeeProperty().set(tblEmployeeByIdemployee);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblLocationProperty().set(tblLocation);
        codeStockOpnameProperty().set(codeStockOpname);
        stockOpanameDateProperty().set(stockOpanameDate);
        stockOpnameNoteProperty().set(stockOpnameNote);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

        this.tblStockOpnameDetails = tblStockOpnameDetails;
    }

    public TblStockOpname(TblStockOpname tblStockOpname) {
        this();
        idstockOpnameProperty().set(tblStockOpname.getIdstockOpname());
        refRecordStatusProperty().set(tblStockOpname.getRefRecordStatus());
        sysAccountProperty().set(tblStockOpname.getSysAccount());
        tblEmployeeByIdemployeeProperty().set(tblStockOpname.getTblEmployeeByIdemployee());
        tblEmployeeByCreateByProperty().set(tblStockOpname.getTblEmployeeByCreateBy());
        tblEmployeeByLastUpdateByProperty().set(tblStockOpname.getTblEmployeeByLastUpdateBy());
        tblLocationProperty().set(tblStockOpname.getTblLocation());
        codeStockOpnameProperty().set(tblStockOpname.getCodeStockOpname());
        stockOpanameDateProperty().set(tblStockOpname.getStockOpanameDate());
        stockOpnameNoteProperty().set(tblStockOpname.getStockOpnameNote());
        createDateProperty().set(tblStockOpname.getCreateDate());
        lastUpdateDateProperty().set(tblStockOpname.getLastUpdateDate());

        this.tblStockOpnameDetails = tblStockOpname.getTblStockOpnameDetails();
    }

    public final LongProperty idstockOpnameProperty() {
        return this.idstockOpname;
    }

    public long getIdstockOpname() {
        return idstockOpnameProperty().get();
    }

    public void setIdstockOpname(long idstockOpname) {
        idstockOpnameProperty().set(idstockOpname);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<SysAccount> sysAccountProperty() {
        return this.sysAccount;
    }

    public SysAccount getSysAccount() {
        return sysAccountProperty().get();
    }

    public void setSysAccount(SysAccount sysAccount) {
        sysAccountProperty().set(sysAccount);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByIdemployeeProperty() {
        return this.tblEmployeeByIdemployee;
    }

    public TblEmployee getTblEmployeeByIdemployee() {
        return tblEmployeeByIdemployeeProperty().get();
    }

    public void setTblEmployeeByIdemployee(TblEmployee tblEmployeeByIdemployee) {
        tblEmployeeByIdemployeeProperty().set(tblEmployeeByIdemployee);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblLocation> tblLocationProperty() {
        return this.tblLocation;
    }

    public TblLocation getTblLocation() {
        return tblLocationProperty().get();
    }

    public void setTblLocation(TblLocation tblLocation) {
        tblLocationProperty().set(tblLocation);
    }

    public final StringProperty codeStockOpnameProperty() {
        return this.codeStockOpname;
    }

    public String getCodeStockOpname() {
        return codeStockOpnameProperty().get();
    }

    public void setCodeStockOpname(String codeStockOpname) {
        codeStockOpnameProperty().set(codeStockOpname);
    }

    public final ObjectProperty<Date> stockOpanameDateProperty() {
        return this.stockOpanameDate;
    }

    public Date getStockOpanameDate() {
        return stockOpanameDateProperty().get();
    }

    public void setStockOpanameDate(Date stockOpanameDate) {
        stockOpanameDateProperty().set(stockOpanameDate);
    }

    public final StringProperty stockOpnameNoteProperty() {
        return this.stockOpnameNote;
    }

    public String getStockOpnameNote() {
        return stockOpnameNoteProperty().get();
    }

    public void setStockOpnameNote(String stockOpnameNote) {
        stockOpnameNoteProperty().set(stockOpnameNote);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

    public Set getTblStockOpnameDetails() {
        return this.tblStockOpnameDetails;
    }

    public void setTblStockOpnameDetails(Set tblStockOpnameDetails) {
        this.tblStockOpnameDetails = tblStockOpnameDetails;
    }

}
