package hotelfx.persistence.model;
// Generated Apr 6, 2018 9:44:05 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javafx.beans.property.BooleanProperty;
import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleBooleanProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblSystemLogBook generated by hbm2java
 */
public class TblSystemLogBook implements java.io.Serializable {

    private final LongProperty idlogBook;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByIdemployee;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblSystemUser> tblSystemUser;
    private final StringProperty codeLogBook;
    private final ObjectProperty<Date> logBookDateTime;
    private final StringProperty hostName;
    private final StringProperty logBookHeader;
    private final StringProperty logBookDetail;
    private final BooleanProperty isReminder;
    private final ObjectProperty<Date> reminderDate;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    private Set tblSystemLogBookJobs;

    public TblSystemLogBook() {
        this.idlogBook = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByIdemployee = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblSystemUser = new SimpleObjectProperty<>();
        this.codeLogBook = new SimpleStringProperty();
        this.logBookDateTime = new SimpleObjectProperty<>();
        this.hostName = new SimpleStringProperty();
        this.logBookHeader = new SimpleStringProperty();
        this.logBookDetail = new SimpleStringProperty();
        this.isReminder = new SimpleBooleanProperty();
        this.reminderDate = new SimpleObjectProperty<>();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

        this.tblSystemLogBookJobs = new HashSet(0);
    }

    public TblSystemLogBook(long idlogBook) {
        this();
        idlogBookProperty().set(idlogBook);
    }

    public TblSystemLogBook(long idlogBook, RefRecordStatus refRecordStatus, TblEmployee tblEmployeeByIdemployee, TblEmployee tblEmployeeByCreateBy, TblEmployee tblEmployeeByLastUpdateBy, TblSystemUser tblSystemUser, String codeLogBook, Date logBookDateTime, String hostName, String logBookHeader, String logBookDetail, Boolean isReminder, Date reminderDate, Date createDate, Date lastUpdateDate, Set tblSystemLogBookJobs) {
        this();
        idlogBookProperty().set(idlogBook);
        refRecordStatusProperty().set(refRecordStatus);
        tblEmployeeByIdemployeeProperty().set(tblEmployeeByIdemployee);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblSystemUserProperty().set(tblSystemUser);
        codeLogBookProperty().set(codeLogBook);
        logBookDateTimeProperty().set(logBookDateTime);
        hostNameProperty().set(hostName);
        logBookHeaderProperty().set(logBookHeader);
        logBookDetailProperty().set(logBookDetail);
        isReminderProperty().set(isReminder);
        reminderDateProperty().set(reminderDate);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

        this.tblSystemLogBookJobs = tblSystemLogBookJobs;
    }

    public TblSystemLogBook(TblSystemLogBook tblSystemLogBook) {
        this();
        idlogBookProperty().set(tblSystemLogBook.getIdlogBook());
        refRecordStatusProperty().set(tblSystemLogBook.getRefRecordStatus());
        tblEmployeeByIdemployeeProperty().set(tblSystemLogBook.getTblEmployeeByIdemployee());
        tblEmployeeByCreateByProperty().set(tblSystemLogBook.getTblEmployeeByCreateBy());
        tblEmployeeByLastUpdateByProperty().set(tblSystemLogBook.getTblEmployeeByLastUpdateBy());
        tblSystemUserProperty().set(tblSystemLogBook.getTblSystemUser());
        codeLogBookProperty().set(tblSystemLogBook.getCodeLogBook());
        logBookDateTimeProperty().set(tblSystemLogBook.getLogBookDateTime());
        hostNameProperty().set(tblSystemLogBook.getHostName());
        logBookHeaderProperty().set(tblSystemLogBook.getLogBookHeader());
        logBookDetailProperty().set(tblSystemLogBook.getLogBookDetail());
        isReminderProperty().set(tblSystemLogBook.getIsReminder());
        reminderDateProperty().set(tblSystemLogBook.getReminderDate());
        createDateProperty().set(tblSystemLogBook.getCreateDate());
        lastUpdateDateProperty().set(tblSystemLogBook.getLastUpdateDate());

        this.tblSystemLogBookJobs = tblSystemLogBook.getTblSystemLogBookJobs();
    }

    public final LongProperty idlogBookProperty() {
        return this.idlogBook;
    }

    public long getIdlogBook() {
        return idlogBookProperty().get();
    }

    public void setIdlogBook(long idlogBook) {
        idlogBookProperty().set(idlogBook);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByIdemployeeProperty() {
        return this.tblEmployeeByIdemployee;
    }

    public TblEmployee getTblEmployeeByIdemployee() {
        return tblEmployeeByIdemployeeProperty().get();
    }

    public void setTblEmployeeByIdemployee(TblEmployee tblEmployeeByIdemployee) {
        tblEmployeeByIdemployeeProperty().set(tblEmployeeByIdemployee);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblSystemUser> tblSystemUserProperty() {
        return this.tblSystemUser;
    }

    public TblSystemUser getTblSystemUser() {
        return tblSystemUserProperty().get();
    }

    public void setTblSystemUser(TblSystemUser tblSystemUser) {
        tblSystemUserProperty().set(tblSystemUser);
    }

    public final StringProperty codeLogBookProperty() {
        return this.codeLogBook;
    }

    public String getCodeLogBook() {
        return codeLogBookProperty().get();
    }

    public void setCodeLogBook(String codeLogBook) {
        codeLogBookProperty().set(codeLogBook);
    }

    public final ObjectProperty<Date> logBookDateTimeProperty() {
        return this.logBookDateTime;
    }

    public Date getLogBookDateTime() {
        return logBookDateTimeProperty().get();
    }

    public void setLogBookDateTime(Date logBookDateTime) {
        logBookDateTimeProperty().set(logBookDateTime);
    }

    public final StringProperty hostNameProperty() {
        return this.hostName;
    }

    public String getHostName() {
        return hostNameProperty().get();
    }

    public void setHostName(String hostName) {
        hostNameProperty().set(hostName);
    }

    public final StringProperty logBookHeaderProperty() {
        return this.logBookHeader;
    }

    public String getLogBookHeader() {
        return logBookHeaderProperty().get();
    }

    public void setLogBookHeader(String logBookHeader) {
        logBookHeaderProperty().set(logBookHeader);
    }

    public final StringProperty logBookDetailProperty() {
        return this.logBookDetail;
    }

    public String getLogBookDetail() {
        return logBookDetailProperty().get();
    }

    public void setLogBookDetail(String logBookDetail) {
        logBookDetailProperty().set(logBookDetail);
    }

    public final BooleanProperty isReminderProperty() {
        return this.isReminder;
    }

    public Boolean getIsReminder() {
        return isReminderProperty().get();
    }

    public void setIsReminder(Boolean isReminder) {
        isReminderProperty().set(isReminder);
    }

    public final ObjectProperty<Date> reminderDateProperty() {
        return this.reminderDate;
    }

    public Date getReminderDate() {
        return reminderDateProperty().get();
    }

    public void setReminderDate(Date reminderDate) {
        reminderDateProperty().set(reminderDate);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

    public Set getTblSystemLogBookJobs() {
        return this.tblSystemLogBookJobs;
    }

    public void setTblSystemLogBookJobs(Set tblSystemLogBookJobs) {
        this.tblSystemLogBookJobs = tblSystemLogBookJobs;
    }

}
