package hotelfx.persistence.model;
// Generated Aug 21, 2017 1:49:32 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblSystemFeature generated by hbm2java
 */
public class TblSystemFeature implements java.io.Serializable {

    private final LongProperty idfeature;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblSystemFeature> tblSystemFeature;
    private final StringProperty codeFeature;
    private final StringProperty featureName;
    private final StringProperty imageIconPath;
    private final StringProperty fxmlpath;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    private Set tblSystemRoleSystemFeatures;
    private Set tblSystemFeatures;

    public TblSystemFeature() {
        this.idfeature = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblSystemFeature = new SimpleObjectProperty<>();
        this.codeFeature = new SimpleStringProperty();
        this.featureName = new SimpleStringProperty();
        this.imageIconPath = new SimpleStringProperty();
        this.fxmlpath = new SimpleStringProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

        this.tblSystemRoleSystemFeatures = new HashSet(0);
        this.tblSystemFeatures = new HashSet(0);
    }

    public TblSystemFeature(long idfeature) {
        this();
        idfeatureProperty().set(idfeature);
    }

    public TblSystemFeature(long idfeature, RefRecordStatus refRecordStatus, TblEmployee tblEmployeeByCreateBy, TblEmployee tblEmployeeByLastUpdateBy, TblSystemFeature tblSystemFeature, String codeFeature, String featureName, String imageIconPath, String fxmlpath, Date createDate, Date lastUpdateDate, Set tblSystemRoleSystemFeatures, Set tblSystemFeatures) {
        this();
        idfeatureProperty().set(idfeature);
        refRecordStatusProperty().set(refRecordStatus);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblSystemFeatureProperty().set(tblSystemFeature);
        codeFeatureProperty().set(codeFeature);
        featureNameProperty().set(featureName);
        imageIconPathProperty().set(imageIconPath);
        fxmlpathProperty().set(fxmlpath);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

        this.tblSystemRoleSystemFeatures = tblSystemRoleSystemFeatures;
        this.tblSystemFeatures = tblSystemFeatures;
    }

    public TblSystemFeature(TblSystemFeature tblSystemFeature) {
        this();
        idfeatureProperty().set(tblSystemFeature.getIdfeature());
        refRecordStatusProperty().set(tblSystemFeature.getRefRecordStatus());
        tblEmployeeByCreateByProperty().set(tblSystemFeature.getTblEmployeeByCreateBy());
        tblEmployeeByLastUpdateByProperty().set(tblSystemFeature.getTblEmployeeByLastUpdateBy());
        tblSystemFeatureProperty().set(tblSystemFeature.getTblSystemFeature());
        codeFeatureProperty().set(tblSystemFeature.getCodeFeature());
        featureNameProperty().set(tblSystemFeature.getFeatureName());
        imageIconPathProperty().set(tblSystemFeature.getImageIconPath());
        fxmlpathProperty().set(tblSystemFeature.getFxmlpath());
        createDateProperty().set(tblSystemFeature.getCreateDate());
        lastUpdateDateProperty().set(tblSystemFeature.getLastUpdateDate());

        this.tblSystemRoleSystemFeatures = tblSystemFeature.getTblSystemRoleSystemFeatures();
        this.tblSystemFeatures = tblSystemFeature.getTblSystemFeatures();
    }

    public final LongProperty idfeatureProperty() {
        return this.idfeature;
    }

    public long getIdfeature() {
        return idfeatureProperty().get();
    }

    public void setIdfeature(long idfeature) {
        idfeatureProperty().set(idfeature);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblSystemFeature> tblSystemFeatureProperty() {
        return this.tblSystemFeature;
    }

    public TblSystemFeature getTblSystemFeature() {
        return tblSystemFeatureProperty().get();
    }

    public void setTblSystemFeature(TblSystemFeature tblSystemFeature) {
        tblSystemFeatureProperty().set(tblSystemFeature);
    }

    public final StringProperty codeFeatureProperty() {
        return this.codeFeature;
    }

    public String getCodeFeature() {
        return codeFeatureProperty().get();
    }

    public void setCodeFeature(String codeFeature) {
        codeFeatureProperty().set(codeFeature);
    }

    public final StringProperty featureNameProperty() {
        return this.featureName;
    }

    public String getFeatureName() {
        return featureNameProperty().get();
    }

    public void setFeatureName(String featureName) {
        featureNameProperty().set(featureName);
    }

    public final StringProperty imageIconPathProperty() {
        return this.imageIconPath;
    }

    public String getImageIconPath() {
        return imageIconPathProperty().get();
    }

    public void setImageIconPath(String imageIconPath) {
        imageIconPathProperty().set(imageIconPath);
    }

    public final StringProperty fxmlpathProperty() {
        return this.fxmlpath;
    }

    public String getFxmlpath() {
        return fxmlpathProperty().get();
    }

    public void setFxmlpath(String fxmlpath) {
        fxmlpathProperty().set(fxmlpath);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

    public Set getTblSystemRoleSystemFeatures() {
        return this.tblSystemRoleSystemFeatures;
    }

    public void setTblSystemRoleSystemFeatures(Set tblSystemRoleSystemFeatures) {
        this.tblSystemRoleSystemFeatures = tblSystemRoleSystemFeatures;
    }

    public Set getTblSystemFeatures() {
        return this.tblSystemFeatures;
    }

    public void setTblSystemFeatures(Set tblSystemFeatures) {
        this.tblSystemFeatures = tblSystemFeatures;
    }

    @Override
    public String toString() {
        return getFeatureName();
    }

}
