package hotelfx.persistence.model;
// Generated May 4, 2018 1:23:17 PM by Hibernate Tools 4.3.1

import java.util.Date;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblStockOpnameItemExpiredDateDetail generated by hbm2java
 */
public class TblStockOpnameItemExpiredDateDetail implements java.io.Serializable {

    private final LongProperty iddetail;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblItemExpiredDate> tblItemExpiredDate;
    private final ObjectProperty<TblStockOpnameItemExpiredDate> tblStockOpnameItemExpiredDate;
    private final StringProperty detailNote;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    public TblStockOpnameItemExpiredDateDetail() {
        this.iddetail = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblItemExpiredDate = new SimpleObjectProperty<>();
        this.tblStockOpnameItemExpiredDate = new SimpleObjectProperty<>();
        this.detailNote = new SimpleStringProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

    }

    public TblStockOpnameItemExpiredDateDetail(long iddetail) {
        this();
        iddetailProperty().set(iddetail);
    }

    public TblStockOpnameItemExpiredDateDetail(long iddetail, RefRecordStatus refRecordStatus, TblEmployee tblEmployeeByCreateBy, TblEmployee tblEmployeeByLastUpdateBy, TblItemExpiredDate tblItemExpiredDate, TblStockOpnameItemExpiredDate tblStockOpnameItemExpiredDate, String detailNote, Date createDate, Date lastUpdateDate) {
        this();
        iddetailProperty().set(iddetail);
        refRecordStatusProperty().set(refRecordStatus);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblItemExpiredDateProperty().set(tblItemExpiredDate);
        tblStockOpnameItemExpiredDateProperty().set(tblStockOpnameItemExpiredDate);
        detailNoteProperty().set(detailNote);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

    }

    public TblStockOpnameItemExpiredDateDetail(TblStockOpnameItemExpiredDateDetail tblStockOpnameItemExpiredDateDetail) {
        this();
        iddetailProperty().set(tblStockOpnameItemExpiredDateDetail.getIddetail());
        refRecordStatusProperty().set(tblStockOpnameItemExpiredDateDetail.getRefRecordStatus());
        tblEmployeeByCreateByProperty().set(tblStockOpnameItemExpiredDateDetail.getTblEmployeeByCreateBy());
        tblEmployeeByLastUpdateByProperty().set(tblStockOpnameItemExpiredDateDetail.getTblEmployeeByLastUpdateBy());
        tblItemExpiredDateProperty().set(tblStockOpnameItemExpiredDateDetail.getTblItemExpiredDate());
        tblStockOpnameItemExpiredDateProperty().set(tblStockOpnameItemExpiredDateDetail.getTblStockOpnameItemExpiredDate());
        detailNoteProperty().set(tblStockOpnameItemExpiredDateDetail.getDetailNote());
        createDateProperty().set(tblStockOpnameItemExpiredDateDetail.getCreateDate());
        lastUpdateDateProperty().set(tblStockOpnameItemExpiredDateDetail.getLastUpdateDate());

    }

    public final LongProperty iddetailProperty() {
        return this.iddetail;
    }

    public long getIddetail() {
        return iddetailProperty().get();
    }

    public void setIddetail(long iddetail) {
        iddetailProperty().set(iddetail);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblItemExpiredDate> tblItemExpiredDateProperty() {
        return this.tblItemExpiredDate;
    }

    public TblItemExpiredDate getTblItemExpiredDate() {
        return tblItemExpiredDateProperty().get();
    }

    public void setTblItemExpiredDate(TblItemExpiredDate tblItemExpiredDate) {
        tblItemExpiredDateProperty().set(tblItemExpiredDate);
    }

    public final ObjectProperty<TblStockOpnameItemExpiredDate> tblStockOpnameItemExpiredDateProperty() {
        return this.tblStockOpnameItemExpiredDate;
    }

    public TblStockOpnameItemExpiredDate getTblStockOpnameItemExpiredDate() {
        return tblStockOpnameItemExpiredDateProperty().get();
    }

    public void setTblStockOpnameItemExpiredDate(TblStockOpnameItemExpiredDate tblStockOpnameItemExpiredDate) {
        tblStockOpnameItemExpiredDateProperty().set(tblStockOpnameItemExpiredDate);
    }

    public final StringProperty detailNoteProperty() {
        return this.detailNote;
    }

    public String getDetailNote() {
        return detailNoteProperty().get();
    }

    public void setDetailNote(String detailNote) {
        detailNoteProperty().set(detailNote);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

}
