package hotelfx.persistence.model;
// Generated Aug 21, 2017 1:49:32 PM by Hibernate Tools 4.3.1

import java.util.Date;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblServiceChargeCashFlow generated by hbm2java
 */
public class TblServiceChargeCashFlow implements java.io.Serializable {

    private final LongProperty idserviceChargeCashFlow;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final StringProperty codeServiceChargeCashFlow;
    private final ObjectProperty<Date> changedDate;
    private final LongProperty changedNominal;
    private final LongProperty balanceNominal;
    private final StringProperty cashFlowNote;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    public TblServiceChargeCashFlow() {
        this.idserviceChargeCashFlow = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.codeServiceChargeCashFlow = new SimpleStringProperty();
        this.changedDate = new SimpleObjectProperty<>();
        this.changedNominal = new SimpleLongProperty();
        this.balanceNominal = new SimpleLongProperty();
        this.cashFlowNote = new SimpleStringProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

    }

    public TblServiceChargeCashFlow(long idserviceChargeCashFlow) {
        this();
        idserviceChargeCashFlowProperty().set(idserviceChargeCashFlow);
    }

    public TblServiceChargeCashFlow(long idserviceChargeCashFlow, RefRecordStatus refRecordStatus, TblEmployee tblEmployeeByLastUpdateBy, TblEmployee tblEmployeeByCreateBy, String codeServiceChargeCashFlow, Date changedDate, Long changedNominal, Long balanceNominal, String cashFlowNote, Date createDate, Date lastUpdateDate) {
        this();
        idserviceChargeCashFlowProperty().set(idserviceChargeCashFlow);
        refRecordStatusProperty().set(refRecordStatus);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        codeServiceChargeCashFlowProperty().set(codeServiceChargeCashFlow);
        changedDateProperty().set(changedDate);
        changedNominalProperty().set(changedNominal);
        balanceNominalProperty().set(balanceNominal);
        cashFlowNoteProperty().set(cashFlowNote);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

    }

    public TblServiceChargeCashFlow(TblServiceChargeCashFlow tblServiceChargeCashFlow) {
        this();
        idserviceChargeCashFlowProperty().set(tblServiceChargeCashFlow.getIdserviceChargeCashFlow());
        refRecordStatusProperty().set(tblServiceChargeCashFlow.getRefRecordStatus());
        tblEmployeeByLastUpdateByProperty().set(tblServiceChargeCashFlow.getTblEmployeeByLastUpdateBy());
        tblEmployeeByCreateByProperty().set(tblServiceChargeCashFlow.getTblEmployeeByCreateBy());
        codeServiceChargeCashFlowProperty().set(tblServiceChargeCashFlow.getCodeServiceChargeCashFlow());
        changedDateProperty().set(tblServiceChargeCashFlow.getChangedDate());
        changedNominalProperty().set(tblServiceChargeCashFlow.getChangedNominal());
        balanceNominalProperty().set(tblServiceChargeCashFlow.getBalanceNominal());
        cashFlowNoteProperty().set(tblServiceChargeCashFlow.getCashFlowNote());
        createDateProperty().set(tblServiceChargeCashFlow.getCreateDate());
        lastUpdateDateProperty().set(tblServiceChargeCashFlow.getLastUpdateDate());

    }

    public final LongProperty idserviceChargeCashFlowProperty() {
        return this.idserviceChargeCashFlow;
    }

    public long getIdserviceChargeCashFlow() {
        return idserviceChargeCashFlowProperty().get();
    }

    public void setIdserviceChargeCashFlow(long idserviceChargeCashFlow) {
        idserviceChargeCashFlowProperty().set(idserviceChargeCashFlow);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final StringProperty codeServiceChargeCashFlowProperty() {
        return this.codeServiceChargeCashFlow;
    }

    public String getCodeServiceChargeCashFlow() {
        return codeServiceChargeCashFlowProperty().get();
    }

    public void setCodeServiceChargeCashFlow(String codeServiceChargeCashFlow) {
        codeServiceChargeCashFlowProperty().set(codeServiceChargeCashFlow);
    }

    public final ObjectProperty<Date> changedDateProperty() {
        return this.changedDate;
    }

    public Date getChangedDate() {
        return changedDateProperty().get();
    }

    public void setChangedDate(Date changedDate) {
        changedDateProperty().set(changedDate);
    }

    public final LongProperty changedNominalProperty() {
        return this.changedNominal;
    }

    public Long getChangedNominal() {
        return changedNominalProperty().get();
    }

    public void setChangedNominal(Long changedNominal) {
        changedNominalProperty().set(changedNominal);
    }

    public final LongProperty balanceNominalProperty() {
        return this.balanceNominal;
    }

    public Long getBalanceNominal() {
        return balanceNominalProperty().get();
    }

    public void setBalanceNominal(Long balanceNominal) {
        balanceNominalProperty().set(balanceNominal);
    }

    public final StringProperty cashFlowNoteProperty() {
        return this.cashFlowNote;
    }

    public String getCashFlowNote() {
        return cashFlowNoteProperty().get();
    }

    public void setCashFlowNote(String cashFlowNote) {
        cashFlowNoteProperty().set(cashFlowNote);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

}
