package hotelfx.persistence.model;
// Generated May 4, 2018 2:03:50 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblStockOpnameItemExpiredDate generated by hbm2java
 */
public class TblStockOpnameItemExpiredDate implements java.io.Serializable {

    private final LongProperty idstockOpnameIed;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByIdemployee;
    private final ObjectProperty<TblItem> tblItem;
    private final StringProperty codeStockOpnameIed;
    private final ObjectProperty<Date> expiredDate;
    private final ObjectProperty<BigDecimal> itemQuantitySystem;
    private final ObjectProperty<BigDecimal> itemQuantityReal;
    private final ObjectProperty<Date> stockOpnameIeddate;
    private final StringProperty stockOpnameIednote;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    private Set tblStockOpnameItemExpiredDateDetails;

    public TblStockOpnameItemExpiredDate() {
        this.idstockOpnameIed = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByIdemployee = new SimpleObjectProperty<>();
        this.tblItem = new SimpleObjectProperty<>();
        this.codeStockOpnameIed = new SimpleStringProperty();
        this.expiredDate = new SimpleObjectProperty<>();
        this.itemQuantitySystem = new SimpleObjectProperty<>();
        this.itemQuantityReal = new SimpleObjectProperty<>();
        this.stockOpnameIeddate = new SimpleObjectProperty<>();
        this.stockOpnameIednote = new SimpleStringProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

        this.tblStockOpnameItemExpiredDateDetails = new HashSet(0);
    }

    public TblStockOpnameItemExpiredDate(long idstockOpnameIed) {
        this();
        idstockOpnameIedProperty().set(idstockOpnameIed);
    }

    public TblStockOpnameItemExpiredDate(long idstockOpnameIed, RefRecordStatus refRecordStatus, TblEmployee tblEmployeeByLastUpdateBy, TblEmployee tblEmployeeByCreateBy, TblEmployee tblEmployeeByIdemployee, TblItem tblItem, String codeStockOpnameIed, Date expiredDate, BigDecimal itemQuantitySystem, BigDecimal itemQuantityReal, Date stockOpnameIeddate, String stockOpnameIednote, Date createDate, Date lastUpdateDate, Set tblStockOpnameItemExpiredDateDetails) {
        this();
        idstockOpnameIedProperty().set(idstockOpnameIed);
        refRecordStatusProperty().set(refRecordStatus);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblEmployeeByIdemployeeProperty().set(tblEmployeeByIdemployee);
        tblItemProperty().set(tblItem);
        codeStockOpnameIedProperty().set(codeStockOpnameIed);
        expiredDateProperty().set(expiredDate);
        itemQuantitySystemProperty().set(itemQuantitySystem);
        itemQuantityRealProperty().set(itemQuantityReal);
        stockOpnameIeddateProperty().set(stockOpnameIeddate);
        stockOpnameIednoteProperty().set(stockOpnameIednote);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

        this.tblStockOpnameItemExpiredDateDetails = tblStockOpnameItemExpiredDateDetails;
    }

    public TblStockOpnameItemExpiredDate(TblStockOpnameItemExpiredDate tblStockOpnameItemExpiredDate) {
        this();
        idstockOpnameIedProperty().set(tblStockOpnameItemExpiredDate.getIdstockOpnameIed());
        refRecordStatusProperty().set(tblStockOpnameItemExpiredDate.getRefRecordStatus());
        tblEmployeeByLastUpdateByProperty().set(tblStockOpnameItemExpiredDate.getTblEmployeeByLastUpdateBy());
        tblEmployeeByCreateByProperty().set(tblStockOpnameItemExpiredDate.getTblEmployeeByCreateBy());
        tblEmployeeByIdemployeeProperty().set(tblStockOpnameItemExpiredDate.getTblEmployeeByIdemployee());
        tblItemProperty().set(tblStockOpnameItemExpiredDate.getTblItem());
        codeStockOpnameIedProperty().set(tblStockOpnameItemExpiredDate.getCodeStockOpnameIed());
        expiredDateProperty().set(tblStockOpnameItemExpiredDate.getExpiredDate());
        itemQuantitySystemProperty().set(tblStockOpnameItemExpiredDate.getItemQuantitySystem());
        itemQuantityRealProperty().set(tblStockOpnameItemExpiredDate.getItemQuantityReal());
        stockOpnameIeddateProperty().set(tblStockOpnameItemExpiredDate.getStockOpnameIeddate());
        stockOpnameIednoteProperty().set(tblStockOpnameItemExpiredDate.getStockOpnameIednote());
        createDateProperty().set(tblStockOpnameItemExpiredDate.getCreateDate());
        lastUpdateDateProperty().set(tblStockOpnameItemExpiredDate.getLastUpdateDate());

        this.tblStockOpnameItemExpiredDateDetails = tblStockOpnameItemExpiredDate.getTblStockOpnameItemExpiredDateDetails();
    }

    public final LongProperty idstockOpnameIedProperty() {
        return this.idstockOpnameIed;
    }

    public long getIdstockOpnameIed() {
        return idstockOpnameIedProperty().get();
    }

    public void setIdstockOpnameIed(long idstockOpnameIed) {
        idstockOpnameIedProperty().set(idstockOpnameIed);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByIdemployeeProperty() {
        return this.tblEmployeeByIdemployee;
    }

    public TblEmployee getTblEmployeeByIdemployee() {
        return tblEmployeeByIdemployeeProperty().get();
    }

    public void setTblEmployeeByIdemployee(TblEmployee tblEmployeeByIdemployee) {
        tblEmployeeByIdemployeeProperty().set(tblEmployeeByIdemployee);
    }

    public final ObjectProperty<TblItem> tblItemProperty() {
        return this.tblItem;
    }

    public TblItem getTblItem() {
        return tblItemProperty().get();
    }

    public void setTblItem(TblItem tblItem) {
        tblItemProperty().set(tblItem);
    }

    public final StringProperty codeStockOpnameIedProperty() {
        return this.codeStockOpnameIed;
    }

    public String getCodeStockOpnameIed() {
        return codeStockOpnameIedProperty().get();
    }

    public void setCodeStockOpnameIed(String codeStockOpnameIed) {
        codeStockOpnameIedProperty().set(codeStockOpnameIed);
    }

    public final ObjectProperty<Date> expiredDateProperty() {
        return this.expiredDate;
    }

    public Date getExpiredDate() {
        return expiredDateProperty().get();
    }

    public void setExpiredDate(Date expiredDate) {
        expiredDateProperty().set(expiredDate);
    }

    public final ObjectProperty<BigDecimal> itemQuantitySystemProperty() {
        return this.itemQuantitySystem;
    }

    public BigDecimal getItemQuantitySystem() {
        return itemQuantitySystemProperty().get();
    }

    public void setItemQuantitySystem(BigDecimal itemQuantitySystem) {
        itemQuantitySystemProperty().set(itemQuantitySystem);
    }

    public final ObjectProperty<BigDecimal> itemQuantityRealProperty() {
        return this.itemQuantityReal;
    }

    public BigDecimal getItemQuantityReal() {
        return itemQuantityRealProperty().get();
    }

    public void setItemQuantityReal(BigDecimal itemQuantityReal) {
        itemQuantityRealProperty().set(itemQuantityReal);
    }

    public final ObjectProperty<Date> stockOpnameIeddateProperty() {
        return this.stockOpnameIeddate;
    }

    public Date getStockOpnameIeddate() {
        return stockOpnameIeddateProperty().get();
    }

    public void setStockOpnameIeddate(Date stockOpnameIeddate) {
        stockOpnameIeddateProperty().set(stockOpnameIeddate);
    }

    public final StringProperty stockOpnameIednoteProperty() {
        return this.stockOpnameIednote;
    }

    public String getStockOpnameIednote() {
        return stockOpnameIednoteProperty().get();
    }

    public void setStockOpnameIednote(String stockOpnameIednote) {
        stockOpnameIednoteProperty().set(stockOpnameIednote);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

    public Set getTblStockOpnameItemExpiredDateDetails() {
        return this.tblStockOpnameItemExpiredDateDetails;
    }

    public void setTblStockOpnameItemExpiredDateDetails(Set tblStockOpnameItemExpiredDateDetails) {
        this.tblStockOpnameItemExpiredDateDetails = tblStockOpnameItemExpiredDateDetails;
    }

}
