package hotelfx.persistence.model;
// Generated Jan 25, 2018 1:13:06 PM by Hibernate Tools 4.3.1

import java.util.Date;

import javafx.beans.property.IntegerProperty;
import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleIntegerProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;

/**
 * TblTravelAgentRoomType generated by hbm2java
 */
public class TblTravelAgentRoomType implements java.io.Serializable {

    private final LongProperty idrelation;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblPartner> tblPartner;
    private final ObjectProperty<TblRoomType> tblRoomType;
    private final ObjectProperty<Date> availableDate;
    private final IntegerProperty roomNumber;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    public TblTravelAgentRoomType() {
        this.idrelation = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblPartner = new SimpleObjectProperty<>();
        this.tblRoomType = new SimpleObjectProperty<>();
        this.availableDate = new SimpleObjectProperty<>();
        this.roomNumber = new SimpleIntegerProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

    }

    public TblTravelAgentRoomType(long idrelation) {
        this();
        idrelationProperty().set(idrelation);
    }

    public TblTravelAgentRoomType(long idrelation, RefRecordStatus refRecordStatus, TblEmployee tblEmployeeByCreateBy, TblEmployee tblEmployeeByLastUpdateBy, TblPartner tblPartner, TblRoomType tblRoomType, Date availableDate, Integer roomNumber, Date createDate, Date lastUpdateDate) {
        this();
        idrelationProperty().set(idrelation);
        refRecordStatusProperty().set(refRecordStatus);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblPartnerProperty().set(tblPartner);
        tblRoomTypeProperty().set(tblRoomType);
        availableDateProperty().set(availableDate);
        roomNumberProperty().set(roomNumber);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

    }

    public TblTravelAgentRoomType(TblTravelAgentRoomType tblTravelAgentRoomType) {
        this();
        idrelationProperty().set(tblTravelAgentRoomType.getIdrelation());
        refRecordStatusProperty().set(tblTravelAgentRoomType.getRefRecordStatus());
        tblEmployeeByCreateByProperty().set(tblTravelAgentRoomType.getTblEmployeeByCreateBy());
        tblEmployeeByLastUpdateByProperty().set(tblTravelAgentRoomType.getTblEmployeeByLastUpdateBy());
        tblPartnerProperty().set(tblTravelAgentRoomType.getTblPartner());
        tblRoomTypeProperty().set(tblTravelAgentRoomType.getTblRoomType());
        availableDateProperty().set(tblTravelAgentRoomType.getAvailableDate());
        roomNumberProperty().set(tblTravelAgentRoomType.getRoomNumber());
        createDateProperty().set(tblTravelAgentRoomType.getCreateDate());
        lastUpdateDateProperty().set(tblTravelAgentRoomType.getLastUpdateDate());

    }

    public final LongProperty idrelationProperty() {
        return this.idrelation;
    }

    public long getIdrelation() {
        return idrelationProperty().get();
    }

    public void setIdrelation(long idrelation) {
        idrelationProperty().set(idrelation);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblPartner> tblPartnerProperty() {
        return this.tblPartner;
    }

    public TblPartner getTblPartner() {
        return tblPartnerProperty().get();
    }

    public void setTblPartner(TblPartner tblPartner) {
        tblPartnerProperty().set(tblPartner);
    }

    public final ObjectProperty<TblRoomType> tblRoomTypeProperty() {
        return this.tblRoomType;
    }

    public TblRoomType getTblRoomType() {
        return tblRoomTypeProperty().get();
    }

    public void setTblRoomType(TblRoomType tblRoomType) {
        tblRoomTypeProperty().set(tblRoomType);
    }

    public final ObjectProperty<Date> availableDateProperty() {
        return this.availableDate;
    }

    public Date getAvailableDate() {
        return availableDateProperty().get();
    }

    public void setAvailableDate(Date availableDate) {
        availableDateProperty().set(availableDate);
    }

    public final IntegerProperty roomNumberProperty() {
        return this.roomNumber;
    }

    public Integer getRoomNumber() {
        return roomNumberProperty().get();
    }

    public void setRoomNumber(Integer roomNumber) {
        roomNumberProperty().set(roomNumber);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

}
