package hotelfx.persistence.model;
// Generated Sep 5, 2017 4:52:36 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;

/**
 * TblTravelAgent generated by hbm2java
 */
public class TblTravelAgent implements java.io.Serializable {

    private final LongProperty idtravelAgent;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final ObjectProperty<TblPartner> tblPartner;
    private final ObjectProperty<BigDecimal> roomTypeDiscountPercentage;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    public TblTravelAgent() {
        this.idtravelAgent = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.tblPartner = new SimpleObjectProperty<>();
        this.roomTypeDiscountPercentage = new SimpleObjectProperty<>();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

    }

    public TblTravelAgent(long idtravelAgent) {
        this();
        idtravelAgentProperty().set(idtravelAgent);
    }

    public TblTravelAgent(long idtravelAgent, RefRecordStatus refRecordStatus, TblEmployee tblEmployeeByLastUpdateBy, TblEmployee tblEmployeeByCreateBy, TblPartner tblPartner, BigDecimal roomTypeDiscountPercentage, Date createDate, Date lastUpdateDate) {
        this();
        idtravelAgentProperty().set(idtravelAgent);
        refRecordStatusProperty().set(refRecordStatus);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        tblPartnerProperty().set(tblPartner);
        roomTypeDiscountPercentageProperty().set(roomTypeDiscountPercentage);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

    }

    public TblTravelAgent(TblTravelAgent tblTravelAgent) {
        this();
        idtravelAgentProperty().set(tblTravelAgent.getIdtravelAgent());
        refRecordStatusProperty().set(tblTravelAgent.getRefRecordStatus());
        tblEmployeeByLastUpdateByProperty().set(tblTravelAgent.getTblEmployeeByLastUpdateBy());
        tblEmployeeByCreateByProperty().set(tblTravelAgent.getTblEmployeeByCreateBy());
        tblPartnerProperty().set(tblTravelAgent.getTblPartner());
        roomTypeDiscountPercentageProperty().set(tblTravelAgent.getRoomTypeDiscountPercentage());
        createDateProperty().set(tblTravelAgent.getCreateDate());
        lastUpdateDateProperty().set(tblTravelAgent.getLastUpdateDate());

    }

    public final LongProperty idtravelAgentProperty() {
        return this.idtravelAgent;
    }

    public long getIdtravelAgent() {
        return idtravelAgentProperty().get();
    }

    public void setIdtravelAgent(long idtravelAgent) {
        idtravelAgentProperty().set(idtravelAgent);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final ObjectProperty<TblPartner> tblPartnerProperty() {
        return this.tblPartner;
    }

    public TblPartner getTblPartner() {
        return tblPartnerProperty().get();
    }

    public void setTblPartner(TblPartner tblPartner) {
        tblPartnerProperty().set(tblPartner);
    }

    public final ObjectProperty<BigDecimal> roomTypeDiscountPercentageProperty() {
        return this.roomTypeDiscountPercentage;
    }

    public BigDecimal getRoomTypeDiscountPercentage() {
        return roomTypeDiscountPercentageProperty().get();
    }

    public void setRoomTypeDiscountPercentage(BigDecimal roomTypeDiscountPercentage) {
        roomTypeDiscountPercentageProperty().set(roomTypeDiscountPercentage);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

    @Override
    public String toString() {
        return getTblPartner().getPartnerName();
    }

}
