package hotelfx.persistence.model;
// Generated Nov 3, 2017 2:12:52 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javafx.beans.property.LongProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleLongProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * TblUnit generated by hbm2java
 */
public class TblUnit implements java.io.Serializable {

    private final LongProperty idunit;
    private final ObjectProperty<RefRecordStatus> refRecordStatus;
    private final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateBy;
    private final ObjectProperty<TblEmployee> tblEmployeeByCreateBy;
    private final StringProperty codeUnit;
    private final StringProperty unitName;
    private final StringProperty unitNote;
    private final ObjectProperty<Date> createDate;
    private final ObjectProperty<Date> lastUpdateDate;

    private Set tblItems;

    public TblUnit() {
        this.idunit = new SimpleLongProperty();
        this.refRecordStatus = new SimpleObjectProperty<>();
        this.tblEmployeeByLastUpdateBy = new SimpleObjectProperty<>();
        this.tblEmployeeByCreateBy = new SimpleObjectProperty<>();
        this.codeUnit = new SimpleStringProperty();
        this.unitName = new SimpleStringProperty();
        this.unitNote = new SimpleStringProperty();
        this.createDate = new SimpleObjectProperty<>();
        this.lastUpdateDate = new SimpleObjectProperty<>();

        this.tblItems = new HashSet(0);
    }

    public TblUnit(long idunit) {
        this();
        idunitProperty().set(idunit);
    }

    public TblUnit(long idunit, RefRecordStatus refRecordStatus, TblEmployee tblEmployeeByLastUpdateBy, TblEmployee tblEmployeeByCreateBy, String codeUnit, String unitName, String unitNote, Date createDate, Date lastUpdateDate, Set tblItems) {
        this();
        idunitProperty().set(idunit);
        refRecordStatusProperty().set(refRecordStatus);
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
        codeUnitProperty().set(codeUnit);
        unitNameProperty().set(unitName);
        unitNoteProperty().set(unitNote);
        createDateProperty().set(createDate);
        lastUpdateDateProperty().set(lastUpdateDate);

        this.tblItems = tblItems;
    }

    public TblUnit(TblUnit tblUnit) {
        this();
        idunitProperty().set(tblUnit.getIdunit());
        refRecordStatusProperty().set(tblUnit.getRefRecordStatus());
        tblEmployeeByLastUpdateByProperty().set(tblUnit.getTblEmployeeByLastUpdateBy());
        tblEmployeeByCreateByProperty().set(tblUnit.getTblEmployeeByCreateBy());
        codeUnitProperty().set(tblUnit.getCodeUnit());
        unitNameProperty().set(tblUnit.getUnitName());
        unitNoteProperty().set(tblUnit.getUnitNote());
        createDateProperty().set(tblUnit.getCreateDate());
        lastUpdateDateProperty().set(tblUnit.getLastUpdateDate());

        this.tblItems = tblUnit.getTblItems();
    }

    public final LongProperty idunitProperty() {
        return this.idunit;
    }

    public long getIdunit() {
        return idunitProperty().get();
    }

    public void setIdunit(long idunit) {
        idunitProperty().set(idunit);
    }

    public final ObjectProperty<RefRecordStatus> refRecordStatusProperty() {
        return this.refRecordStatus;
    }

    public RefRecordStatus getRefRecordStatus() {
        return refRecordStatusProperty().get();
    }

    public void setRefRecordStatus(RefRecordStatus refRecordStatus) {
        refRecordStatusProperty().set(refRecordStatus);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByLastUpdateByProperty() {
        return this.tblEmployeeByLastUpdateBy;
    }

    public TblEmployee getTblEmployeeByLastUpdateBy() {
        return tblEmployeeByLastUpdateByProperty().get();
    }

    public void setTblEmployeeByLastUpdateBy(TblEmployee tblEmployeeByLastUpdateBy) {
        tblEmployeeByLastUpdateByProperty().set(tblEmployeeByLastUpdateBy);
    }

    public final ObjectProperty<TblEmployee> tblEmployeeByCreateByProperty() {
        return this.tblEmployeeByCreateBy;
    }

    public TblEmployee getTblEmployeeByCreateBy() {
        return tblEmployeeByCreateByProperty().get();
    }

    public void setTblEmployeeByCreateBy(TblEmployee tblEmployeeByCreateBy) {
        tblEmployeeByCreateByProperty().set(tblEmployeeByCreateBy);
    }

    public final StringProperty codeUnitProperty() {
        return this.codeUnit;
    }

    public String getCodeUnit() {
        return codeUnitProperty().get();
    }

    public void setCodeUnit(String codeUnit) {
        codeUnitProperty().set(codeUnit);
    }

    public final StringProperty unitNameProperty() {
        return this.unitName;
    }

    public String getUnitName() {
        return unitNameProperty().get();
    }

    public void setUnitName(String unitName) {
        unitNameProperty().set(unitName);
    }

    public final StringProperty unitNoteProperty() {
        return this.unitNote;
    }

    public String getUnitNote() {
        return unitNoteProperty().get();
    }

    public void setUnitNote(String unitNote) {
        unitNoteProperty().set(unitNote);
    }

    public final ObjectProperty<Date> createDateProperty() {
        return this.createDate;
    }

    public Date getCreateDate() {
        return createDateProperty().get();
    }

    public void setCreateDate(Date createDate) {
        createDateProperty().set(createDate);
    }

    public final ObjectProperty<Date> lastUpdateDateProperty() {
        return this.lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDateProperty().get();
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        lastUpdateDateProperty().set(lastUpdateDate);
    }

    public Set getTblItems() {
        return this.tblItems;
    }

    public void setTblItems(Set tblItems) {
        this.tblItems = tblItems;
    }

    @Override
    public String toString() {
        return getUnitName();
    }

}
